- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://sakaiproject.atlassian.net/browse/SAK-46884
Correcting previous issues introduced in this SAK
> SAK-46884 Messages Always sending CC just shows text

- dav/dav/pom.xml
- dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
- dav/dav/src/test/org/sakaiproject/dav/DavTest.java
> SAK-46627 WebDav connection could fail if user id and eid are the same

- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
https://sakaiproject.atlassian.net/browse/SAK-46939
Also, add more protection of dom element calls.
> SAK-46939 GroupManager: Ensure bool is supplied in filter call

- webapi/src/main/java/org/sakaiproject/webapi/controllers/SitesController.java
> TRINITY-47 Add rest endpoint for favorite sites

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-41604
> SAK-46948 Rubrics: Only load current site groups into JWT

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-41604
> SAK-46948 Rubrics: Only load current user's and site groups into JWT

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://sakaiproject.atlassian.net/browse/SAK-46943
> SAK-46943 Rubric's updated weights should update the weights on public shared list

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://sakaiproject.atlassian.net/browse/SAK-46940
> SAK-46940 Rubrics: Weights are missing on the public rubric

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/experimental.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-46616
For testing
> SAK-46616 Download a folder as ZIP from Resources in user sites fails

- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://sakaiproject.atlassian.net/browse/SAK-46884
Duplicated close tag is doing that the "Reply All" view fails
> SAK-46884 Messages "Reply All" is not working

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
[SAK-46914](https://sakaiproject.atlassian.net/browse/SAK-46914)
Low risk
> SAK-46914 Disabling pagination message in Messages tool

- library/pom.xml
- library/src/morpheus-master/.gitignore
- library/src/trinity/.gitignore
- library/src/trinity/config/.eslintrc.js
- library/src/trinity/src/js/examples/_empty.js
- library/src/trinity/src/js/index.js
https://sakaiproject.atlassian.net/browse/TRINITY-53
> TRINITY-53 Fixed Trinity js and sass files for the library build

- kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
https://sakaiproject.atlassian.net/browse/SAK-46969
Also increase the blocked worker timeout from 30 to 60.
> SAK-46969 Ignite remove ignored FailureTypes from failure handler

- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/StatsAuthz.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAuthzImpl.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/Menus.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/OverviewPage.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ActivityWidget.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/VisitsWidget.java
- sitestats/sitestats-tool/src/webapp/WEB-INF/tools/sakai.sitestats.xml
https://sakaiproject.atlassian.net/browse/SAK-46977
> SAK-46977 Sitestats: Added permission for powerusers, sitestats.all

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
https://sakaiproject.atlassian.net/browse/SAK-46968
> SAK-46968 Assignments: canSubmit now checks getUserSubmission

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/README.md
https://sakaiproject.atlassian.net/browse/SAK-47006
Also set DefaultTxTimeout to 3000ms
> SAK-47006 Ignite improved detection of slow nodes

- kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
https://sakaiproject.atlassian.net/browse/SAK-46977
> SAK-46977 Added realm ddl for sitestats.all

- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
- webcomponents/tool/src/main/frontend/.eslintrc.js
- webcomponents/tool/src/main/frontend/package-lock.json
- webcomponents/tool/src/main/frontend/package.json
https://sakaiproject.atlassian.net/browse/SAK-46962
> SAK-46962 GroupManager: fix back button in wizard step 3

- deploy/pom.xml
- entitybroker/core-providers/pom.xml
- kernel/kernel-impl/pom.xml
- kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47018
> SAK-47018 Ignite upgrade from 2.10.0 to 2.12.0

- basiclti/web-ifp/pom.xml
- basiclti/web-ifp/src/bundle/iframe.properties
- basiclti/web-ifp/src/bundle/vm/edit.vm
- basiclti/web-ifp/src/bundle/vm/pick.vm
- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
https://sakaiproject.atlassian.net/browse/SAK-47013
> SAK-47013 BLTI web portlet can cause an NPE when manually placed in a site

- library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
https://sakaiproject.atlassian.net/browse/SAK-46725
> SAK-46725 Resources: Plus sign should be in Other Sites folders with tree view available

- kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
https://sakaiproject.atlassian.net/browse/SAK-46977
> SAK-46977 Added sitestats.own to all student roles in kernel ddl

- kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql
- kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql
https://sakaiproject.atlassian.net/browse/SAK-46977
> SAK-46977 More kernel ddl for sitestats.all

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
https://sakaiproject.atlassian.net/browse/SAK-46984
Picture attached in the Jira showing the result.
> SAK-46984 Assignments - Private Notes from Grader are not displayed on classical grader

- common/privacy-api/src/java/org/sakaiproject/api/privacy/PrivacyManager.java
- common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java
- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-40680
In this change there is also some cleanup of and removal of static
uses of services in SiteAction.
> SAK-40680 SiteManage Joinable groups should show state of locked groups

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-47037
> SAK-47037 Correct Apache Ignite's commented property

- calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js
- lessonbuilder/tool/src/webapp/js/lessons-calendar.js
- library/pom.xml
- library/src/webapp/js/headscripts.js
Includes fullcaleandar upgrade (master [#10343](https://github.com/sakaiproject/sakai/pull/10343/files))
>  TRINITY-56 Apply Bootstrap 5 theme to fullcalendar

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/MessageForumsEntityContentProducer.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47044
> SAK-47044 Discussions: Supply site id from ref in canRead call

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
Jira: [SAK-46978](https://sakaiproject.atlassian.net/browse/SAK-46978)
Info text will show once, without a title.
Users using SR will hear: 
_more info - button - For example, temporary access to students taking assessments with images included on them._
> SAK-46978 Resources: Secure access pop-up repeats text

- webapi/src/main/java/org/sakaiproject/webapi/controllers/SitesController.java
...to retrieve pages and info for gateway site.
> TRINITY-57 Add api endpint for gateway site

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47035
> SAK-47035 Assignment progress bar not updating in student view

- commons/api/src/java/org/sakaiproject/commons/api/SakaiProxy.java
- commons/api/src/java/org/sakaiproject/commons/api/datamodel/Comment.java
- commons/api/src/java/org/sakaiproject/commons/api/datamodel/Post.java
- commons/impl/src/java/org/sakaiproject/commons/impl/CommonsContentProducer.java
- commons/impl/src/java/org/sakaiproject/commons/impl/PersistenceManagerImpl.java
- commons/impl/src/java/org/sakaiproject/commons/impl/SakaiProxyImpl.java
- search/README.md
- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchResult.java
- search/elasticsearch/impl/src/resources/org/sakaiproject/search/elastic/bundle/mapping.json
- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java
- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/filter/impl/SearchSecurityFilter.java
- search/search-api/api/src/java/org/sakaiproject/search/api/EntityContentProducer.java
- search/search-api/api/src/java/org/sakaiproject/search/api/SearchResult.java
- search/search-api/api/src/java/org/sakaiproject/search/api/SearchService.java
https://sakaiproject.atlassian.net/browse/SAK-47038
> SAK-47038 Search: Add the content creator's display name to the index

- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Add checkboxes if Download Zip is activated
> SAK-47031 Content add checkboxes if Download Zip is activated

- signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47067
> SAK-47067 SignUp - Some users are duplicated if they appears in different groups

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.java
https://sakaiproject.atlassian.net/browse/SAK-47027
> SAK-47027 Gradebook - Set score for empty cell does not work in languages with decimal comma

- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
https://sakaiproject.atlassian.net/browse/SAK-46566
> SAK-46566 BLTI content item (not tool) secret keys should be encrypted

- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
You can see the result in Jira https://sakaiproject.atlassian.net/browse/SAK-47072
> SAK-47072 Test & Quizzes - Fix style when try saving not a number

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
https://sakaiproject.atlassian.net/browse/SAK-47081
Regression from: https://sakaiproject.atlassian.net/browse/SAK-44932
> SAK-47081: Missing key on Gradebook Settings: Grade type

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
https://sakaiproject.atlassian.net/browse/SAK-47071
> SAK-47071 Calculated Questions - Add spaces between answers

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46893
> SAK-46893 Rubrics: only handle rubrics refs in entity producer

- library/src/morpheus-master/sass/base/_icons.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/portal-search/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-47005
Cleaned up the bullhorn and search portal bar link to not be text decorated
> SAK-47005 Added FontAwesome font-family to sakai icons

- webcomponents/README.md
- webcomponents/docs/tutorial.md
https://sakaiproject.atlassian.net/browse/SAK-47082
> SAK-47082 Add a webcomponents tutorial to Sakai

- cloud-storage/googledrive/impl/pom.xml
- cloud-storage/googledrive/impl/src/java/org/sakaiproject/googledrive/service/GoogleDriveServiceImpl.java
- cloud-storage/googledrive/impl/src/test/org/sakaiproject/googledrive/service/GoogleDriveServiceImplTest.java
- cloud-storage/googledrive/impl/src/test/org/sakaiproject/googledrive/service/GoogleDriveServiceImplTestConfiguration.java
- cloud-storage/googledrive/impl/src/test/resources/hibernate.properties
This does not test the Google Drive APIs or libraries, just the wrapper that the Google Drive integration uses.
> SAK-47021 Google Drive integration: Add test suite

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Before, when creating a draft assignment the tool creates a task item in the students' dashboard before the assignment is released. Currently, it has been fixed.  I have taken into account when you create or update a gradebook item, if it is released or not.
> SAK-47113 Dashboard and Gradebook: Not released gradebook items are visible to the students via dashboard

- assignment/api/src/resources/assignment.properties
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
Images and more info: [SAK-46349](https://sakaiproject.atlassian.net/browse/SAK-46349)
- Used fieldset & legend tag for the related elements.
- Readability & style improvements.
- Score input will only accept numbers.
- "A Submission" instead of "No submit" for better understanding.
> SAK-46349 Assignments: Bulk grading inputs need to be accessible

- master/pom.xml
- rubrics/impl/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47111
Spring
Jackson Databind
Elasticsearch
> SAK-47111 March 2022 library updates

- jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/renderer/PagerRenderer.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionStatusBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
https://sakaiproject.atlassian.net/browse/SAK-47090
- Added "Show 200", and now it is the default selected item.
- Select input inserted into a fieldset to align it with buttons.
**This also should solve https://sakaiproject.atlassian.net/browse/SAK-46828**
Images attached in Jira
> SAK-47090 Test & Quizzes - Set a bigger number of students in Sakai Pager and set it as default selected value

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
https://sakaiproject.atlassian.net/browse/SAK-47071
This PR is just to correct the description of the changed method
> SAK-47071 Calculated Question - Correcting description of the method

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47113
> SAK-47113 Assignments: Only add user task if not draft

- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47111
> SAK-47111 March 2022 library updates jdom2

- webservices/cxf/pom.xml
- webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java
- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
- webservices/cxf/src/resources/applicationContext.xml
> SAK-47123 Add a SakaiScript method for site archive

- common/archive-impl/impl2/pom.xml
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
- common/archive-impl/impl2/src/webapp/WEB-INF/components.xml
- kernel/kernel-private/src/main/java/org/sakaiproject/serialization/BasicSerializableRepository.java
https://sakaiproject.atlassian.net/browse/SAK-47126
> SAK-47126 SiteArchive add tx template during archive

- help/help/src/sakai_screensteps_quotaIncreasesAdministratorGuide/howdoIincreaseapersonsorsitesDropBoxquota.html
- help/help/src/sakai_screensteps_quotaIncreasesAdministratorGuide/howdoIincreaseasitesResourcesquota.html
- help/help/src/sakai_toc/help.xml
Two updated help files from Wilma
> SAK-46784 updated Sakai 22 help files

- msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/permissions/permissions_include.jsp
https://sakaiproject.atlassian.net/browse/SAK-45399
> SAK-45399 Discussions checkboxes are not associated to parent labels in Template/Forum/Topic Settings

- library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_button-groups.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
Jira: [SAK-47135](https://sakaiproject.atlassian.net/browse/SAK-47135)
> SAK-47135 id=cropToolbar is used twice

- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Category.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
This also reverts a previous modification
> SAK-47115 make sure equalWeight category is not null

- pasystem/pasystem-impl/impl/src/resources/templates/banner_footer.hbs
- pasystem/pasystem-tool/tool/src/webapp/scripts/pasystem.js
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageBody.vm
https://sakaiproject.atlassian.net/browse/SAK-46589
> SAK-46589 resolve aXe issues related to unique landmarks

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm
Also addresses submission submitted after due date does not submit
> SAK-47104 Assignments allow extension no longer allows student to submit

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupReferenceBuilder.java
- kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java
- kernel/api/src/main/java/org/sakaiproject/tasks/api/repository/TaskRepository.java
- kernel/api/src/main/java/org/sakaiproject/tasks/api/repository/UserTaskRepository.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/repository/TaskRepositoryImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/repository/UserTaskRepositoryImpl.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/tasks-components.xml
- kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTestConfiguration.java
https://sakaiproject.atlassian.net/browse/SAK-46986
> SAK-46986 Tasks: remove tasks for removed site users

- calendar/calendar-bundles/resources/calendar.properties
- calendar/calendar-bundles/resources/calendar_es.properties
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_revise.vm
In order to accomplish the features described in this Jira, I have removed the checkbox option in calendar that allows to create tasks from events optionally. Currently, when you create an event in calendar, a task will automatically be created on the dashboard.
> SAK-47073 Checkbox option in Calendar to create Tasks from events has been removed

- library/src/webapp/editor/ckextraplugins/bt_table/lang/es.js
- library/src/webapp/editor/ckextraplugins/bt_table/plugin.js
https://sakaiproject.atlassian.net/browse/SAK-47174
> SAK-47174 Upload spanish translations for CKEditor bt_table extra plugin

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/api/src/resources/assignment.properties
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/grader/submission.js
Add a section to Sakai Grader that will show the content review results
in the same way they are shown on the classic grader thus preventing
instructors from switching back to classic or using the list view to
see them.
> SAK-45221 Assignments add content review score to Sakai Grader

- library/src/webapp/editor/ckextraplugins/bt_table/lang/ca.js
- library/src/webapp/editor/ckextraplugins/bt_table/plugin.js
https://sakaiproject.atlassian.net/browse/SAK-47174
> SAK-47174 Upload català translations for CKEditor bt_table extra plugin

- samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
I have added an onkeypress attribute that calls the submitOnEnter function in order to accomplish with the specs on this Jira. The main purpose is when an instructor presses the enter key, the form will be submitted without pressing the search button.
> SAK-44514 Quiz | Event Log search: sending request

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-47199
The buttons in the Trash UI lack disabling/spinners after clicking, leading to users clicking them multiple times. Add the spinners for clarity and consistency.
> SAK-47199 Assignments > Trash > add spinners on buttons after click

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-46664
> SAK-46664 Grader - Math formula submitted for an Assignment is not rendered correctly while Instructor grades it

- assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
[SAK-47137: Excel failed in "Assignments by student".](https://sakaiproject.atlassian.net/browse/SAK-47137)
> SAK-47137: Excel failed in "Assignments by student".

- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/AbstractGradeRecord.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Category.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Comment.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradableObject.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradeMapping.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Gradebook.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradebookAssignment.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradebookProperty.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradingScale.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/LetterGradePercentMapping.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Permission.java
- gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Spreadsheet.java
https://sakaiproject.atlassian.net/browse/SAK-47194
> SAK-47194 Gradebook: Update DDL to match old schema

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47207
> SAK-47207 Grader - Click on cancel shows error and unsaved changes are discarded automatically

- polls/api/src/java/org/sakaiproject/poll/logic/PollListManager.java
- polls/impl/src/java/org/sakaiproject/poll/logic/impl/PollOrderOptionBackFillJob.java
- polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47205
> SAK-47205 Backfill all existing poll options' order based on their original ID quartz job may cause excessive Garbage Collection

- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfWatchSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-46311
> SAK-46311 Discussions: Improve Notifications page accessibility and make options easier to understand

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_fr_FR.properties
- samigo/samigo-app/src/webapp/jsf/delivery/discrepancyInData.jsp
https://sakaiproject.atlassian.net/browse/SAK-47225
The info provided on the Data Discrepancy page is a little out of date, since we’ve made some improvements in this area. Let’s update the messaging to be a little more descriptive and accurate to the current state of things.
> SAK-47225 Samigo > update Data Discrepancy messaging to be more descriptive and accurate

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
- samigo/samigo-app/src/webapp/jsf/evaluation/evaluationSubmenu.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-47223
Instructors are unable to grade students who have not submitted to an anonymous quiz. The “Apply this score” component is not rendered on the page, and students who have not submitted do not appear in the “Total Scores” table. This is because the “anonymous” IDs being used are actually the `assessmentGradingID` generated when a student submits, so it’s obvious why non-submitters don’t display in the table: they do not have a submission and thus they do not have a corresponding `assessmentGradingID`.
There is also an extremely easy way for instructors to circumvent the anonymity provided for anonymous quizzes: simply visit the “Submission Status” tab, which displays all students within the site, with their real names, and their submission …
> SAK-47223 Samigo > anon quiz > unable to grade non-submitters

- msgcntr/messageforums-app/src/webapp/jsp/synoptic/synMainLite.jsp
Jira [SAK-47014](https://sakaiproject.atlassian.net/browse/SAK-47014)
> SAK-47014 Overview > Message Center Notification - icon A11y issue

- conversations/api/src/main/java/org/sakaiproject/conversations/api/ConversationsService.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/job/SeedSitesAndUsersJob.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
https://sakaiproject.atlassian.net/browse/SAK-47234
> SAK-47234 Conversations: allow muting of emails (for batch jobs)

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46067
> SAK-46067 Conversations: clear post cache when updating settings

- webcomponents/tool/src/main/frontend/package-lock.json
- webcomponents/tool/src/main/frontend/stories/sakai-date-picker.stories.js
https://sakaiproject.atlassian.net/browse/SAK-47237
> SAK-47237 Fixed the storybook sakai-date-picker path

- webcomponents/bundle/src/main/bundle/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46926
> SAK-46926 Conversations: add chars required to title entry

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
- lessonbuilder/tool/src/resources/messages.properties
- lessonbuilder/tool/src/resources/messages_ca.properties
- lessonbuilder/tool/src/resources/messages_es.properties
- lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
- lessonbuilder/tool/src/webapp/templates/QuestionGradingPane.html
In lessons tool, when an instructor goes to grade students submissions on a lessons question, it would be nice to add the student answer date.
> SAK-47235 Show student answer date when grading lessons questions

- library/src/morpheus-master/sass/modules/tool/conversations/_conversations.scss
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-46070
> SAK-46070 Conversations: line up settings icon properly

- library/src/morpheus-master/sass/modules/sakai-options-menu/_sakai-options-menu.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_conversations.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-add-topic.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-conversations-settings.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-conversations-tag-manager.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-post.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic-list.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic-summary.scss
- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic.scss
- webcomponents/tool/src/main/frontend/js/sakai-toggle.js
https://sakaiproject.atlassian.net/browse/SAK-46922
> SAK-46922 Conversations: Dark theme improvements

- webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
- webcomponents/tool/src/main/frontend/js/sakai-date-picker.js
- webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
I fixed a bug in the call to the "isInstructorUser" endpoint to get edit permissions on the site.
Also, the date picker component was causing problems by not updating the input datetime-local when setting epochMillis in the webcomponent.
@mpellicer
> SAK-46436 Add ability for instructors to manually create Tasks that aren't automatically added via tools

- webapi/src/main/java/org/sakaiproject/webapi/beans/AttachmentRestBean.java
- webapi/src/main/java/org/sakaiproject/webapi/beans/CalendarEventRestBean.java
- webapi/src/main/java/org/sakaiproject/webapi/beans/MemberRestBean.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/SitesController.java
Adds several endpoints to get, update and delete members of a site
> TRINITY-75: webapi :: site info :: manage participants :: sui-table compatible api

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/EvaluationRepository.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
- webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
https://sakaiproject.atlassian.net/browse/SAK-47253
Also, this fixes some issues with the rubric not loading in the grade
summary view, for the student.
> SAK-47253 Gradebook: Fixed grade summary view for students

- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Criterion.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Evaluation.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rating.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java
https://sakaiproject.atlassian.net/browse/SAK-46178
> SAK-46178 Rubrics: Added a couple of index names

- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46727
> SAK-46727 Conversations: Fix draft thread replies issue

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46703
> SAK-46703 Conversations: Fixed draft visibility for instructors

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/AuthzGroupServiceTest.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
- kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockAuthzGroupService.java
https://sakaiproject.atlassian.net/browse/SAK-47267
> SAK-47267 Conversations: only email group or instructor members

- kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
- kernel/kernel-impl/src/main/resources/usermessagingservice.properties
- kernel/kernel-impl/src/main/webapp/WEB-INF/user-messaging-components.xml
https://sakaiproject.atlassian.net/browse/SAK-47271
> SAK-47271 Add a preferences link to user messaging service mails

- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46727
> SAK-46727 Conversations: check for anonymous flag on topic

- webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-tag-manager.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-46172
> SAK-46172 Conversations: maintain tag order when editing

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
https://sakaiproject.atlassian.net/browse/SAK-47244
> SAK-47244 Discussions: show grading options on topic

- conversations/tool/src/main/webapp/WEB-INF/tools/sakai.conversations.xml
https://sakaiproject.atlassian.net/browse/SAK-46927
> SAK-46927 Conversations: improve tool description

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://sakaiproject.atlassian.net/browse/SAK-47277
> SAK-47277 Assignments: remove enableLinks reference. Not needed anymore.

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47283
> SAK-47283 Rubrics: Only save association if active set successfully

- commons/tool/src/webapp/WEB-INF/bootstrap.jsp
- commons/tool/src/webapp/WEB-INF/templates/comment.hbs
- commons/tool/src/webapp/WEB-INF/templates/inplace_comment_editor.hbs
- commons/tool/src/webapp/WEB-INF/templates/post.hbs
- commons/tool/src/webapp/WEB-INF/templates/posts.hbs
- commons/tool/src/webapp/js/commons_utils.js
- library/src/morpheus-master/sass/modules/tool/commons/_commons.scss
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-47255
> SAK-47255 Commons: Move to sakai-user-photo and profile popup

- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47289
> SAK-47289 Grader: move to sakai-user-photo component

- library/src/webapp-filtered/editor/ckeditor.launch.js
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- rubrics/tool/src/main/webapp/WEB-INF/templates/index.html
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria-readonly.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-preview.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
- webcomponents/tool/src/main/frontend/js/sakai-editor.js
Jira [SAK-47266](https://sakaiproject.atlassian.net/browse/SAK-47266)
_original commit from UPV by @josecebe_
> SAK-47266 Rubrics: Ability to use basic format on Criterion Description

- signup/api/src/java/org/sakaiproject/signup/model/SignupMeeting.java
- signup/api/src/java/org/sakaiproject/signup/model/SignupTimeslot.java
- signup/tool/src/bundle/messages.properties
- signup/tool/src/bundle/messages_es.properties
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupMeetingWrapper.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupSorter.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/TimeslotWrapper.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/OrganizerSignupMBean.java
- signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
- signup/tool/src/webapp/signup/signupMeetings.jsp
https://sakaiproject.atlassian.net/browse/SAK-46944
> SAK-46944 SIGNUP Provide a counter in the forms title

- webcomponents/tool/src/main/frontend/js/sakai-date-picker.js
https://sakaiproject.atlassian.net/browse/SAK-47293
> SAK-47293 Conversations: Don't show seconds in date picker

- library/src/morpheus-master/sass/modules/tool/roster/_roster.scss
- roster2/tool/src/handlebars/members_cards.handlebars
- roster2/tool/src/handlebars/members_photogrid.handlebars
- roster2/tool/src/handlebars/members_table.handlebars
- roster2/tool/src/webapp/WEB-INF/bootstrap.jsp
- roster2/tool/src/webapp/js/roster.js
- webcomponents/tool/src/main/frontend/.eslintrc.js
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-47298
> SAK-47298 Roster: switch to sakai-user-photo

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47300
> SAK-47300 Rubrics: fix reordering of criteria and ratings

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BasePanel.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47287
> SAK-47287 Gradebook: add checks for null rubrics params

- meetings/teams/pom.xml
- meetings/teams/src/java/org/sakaiproject/meetings/teams/AdminAuthProvider.java
- meetings/teams/src/java/org/sakaiproject/meetings/teams/MicrosoftTeamsService.java
- meetings/tool/src/main/java/org/sakaiproject/meetings/controller/MeetingsController.java
- meetings/tool/src/main/resources/create-meeting.properties
- meetings/tool/src/main/resources/create-meeting_es.properties
- meetings/ui/src/main/frontend/src/views/CreateMeeting.vue
This PR includes a few changes to control exceptions when there's no MS Teams configuration on Sakai properties.
> SAK-45116 MS Teams configuration checks

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Unnecessary optional has been removed
> SAK-38240 Unnecessary optional has been removed

- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
https://sakaiproject.atlassian.net/browse/SAK-47317
> SAK-47317 rubrics: don't throw error while editing criteria

- lessonbuilder/tool/src/webapp/templates/Reorder.html
https://sakaiproject.atlassian.net/browse/SAK-47320
> SAK-47320 Lessons double/multi click reorder save button may cause infinite loop

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
This PR is for fixing an important issue that allows students to view assignments list from lessons (in students_view_grade) even though assignments tool is not visible.
> SAK-38240 Students can access to assignments list bug fixed

- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
https://sakaiproject.atlassian.net/browse/SAK-47330
> SAK-47330 rubrics: fix console error while deleting rating

- webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria-readonly.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-preview.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js
https://sakaiproject.atlassian.net/browse/SAK-47337
> SAK-47337 rubrics: add isCriterionGroup func back in

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47288
> SAK-47288 WC Grader - PDF files are opened on the same window but not embedded in Grader

- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
https://sakaiproject.atlassian.net/browse/SAK-47327
Attached image of the result in Jira.
> SAK-47327 External tools are not displayed in CKEditor

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-43768
> SAK-43768 SAMIGO: Randomize question pools with option: A student's questions are randomized once for all submissions

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js
https://sakaiproject.atlassian.net/browse/SAK-47340
Also, fixes student rubric preview and view of graded rubric
> SAK-47340 Rubrics evaluation can be viewed by anyone in the assignment group

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
https://sakaiproject.atlassian.net/browse/SAK-47272
> SAK-47272 Rubrics only save rubric association if picked

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsConstants.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- rubrics/impl/src/main/webapp/WEB-INF/components.xml
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsTestConfiguration.java
- rubrics/tool/src/main/java/org/sakaiproject/rubrics/tool/controller/RubricsController.java
- rubrics/tool/src/main/webapp/WEB-INF/templates/index.html
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-button.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-pdf.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-readonly.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-helpers.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-list.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-shared-list.js
https://sakaiproject.atlassian.net/browse/SAK-47292
> SAK-47292 rubrics: pdf export broken after traverson pr

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-utils.js
https://sakaiproject.atlassian.net/browse/SAK-47273
> SAK-47273 Rubrics ensure student sees correct comment

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47302
> SAK-47302 Conversations allow drafts to have dates modified

- signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
https://sakaiproject.atlassian.net/browse/SAK-47329
> SAK-47329 - SIGNUP Participants are missing when meeting has already occurred

- sections/sections-app/src/java/org/sakaiproject/tool/section/decorator/SectionDecorator.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/decorator/StudentSectionDecorator.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/AddSectionsBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/CourseDependentBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditStudentSectionsBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditStudentsBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/FilteredSectionListingBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/RosterBean.java
- sections/sections-app/src/webapp/editStudentSections.jsp
- sections/sections-app/src/webapp/overview.jsp
https://sakaiproject.atlassian.net/browse/SAK-46921
> SAK-46921 Sections TAs should only be able to assign students to the section they are a member of

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47295
> SAK-47295 Conversations don't send email on topic updates

- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-post.scss
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
https://sakaiproject.atlassian.net/browse/SAK-46874
> SAK-46874 conversations: don't mark post as instructor on client

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-47344
> SAK-47344 Assignments Style is missing on Trash when the trash is empty

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://sakaiproject.atlassian.net/browse/SAK-47310
> SAK-47310 Discussions - Remove message after editing results in error

- gradebookng/bundle/src/main/bundle/gradebookng.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
https://sakaiproject.atlassian.net/browse/SAK-47339
> SAK-47339 Gradebook shouldn't allow categories with drop / keep to import spreadsheets with different possible point values

- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-47274
> SAK-47274 assignments: only show rubric if one associated

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
[Assignment: Webservice for consulting time in worklog to a task](https://sakaiproject.atlassian.net/browse/SAK-47348)
> SAK-47348: Assignment: Webservice for consulting time in worklog to a task

- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/dao/impl/RWikiCurrentObjectDaoImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47364
This is happening on our 22.0... maybe the oracle driver is the problem
> SAK-47364: Rwiki: ORACLE - Error 500 when searching

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-pdf.js
https://sakaiproject.atlassian.net/browse/SAK-47360
> SAK-47360 rubrics: prevent pdf download from collapsing rubric

- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/dao/impl/RWikiCurrentObjectDaoImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47364
> SAK-47364 Rwiki: ORACLE - Error 500 when searching

- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.java
[SAK-47389: MESSAGES: Scheduling - Avoid DEFAULT NULL](https://sakaiproject.atlassian.net/browse/SAK-47389)
> SAK-47389: MESSAGES: Scheduling - Avoid DEFAULT NULL

- kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47369
> SAK-47369 assignment: fix npe on submission email

- library/src/morpheus-master/sass/base/_extendables.scss
- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-46492
Also, the same for the private notes panel and the rubric panel
> SAK-46492 grader: disable save buttons while feedback panel showing

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://sakaiproject.atlassian.net/browse/SAK-43186
> SAK-43186 Lessons Automatic checklists not importing links

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
[SAK-47399: ORACLE - MESSAGES: Error in reply All](https://sakaiproject.atlassian.net/browse/SAK-47399)
> SAK-47399: ORACLE - MESSAGES: Error in reply All

- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/UserStatistics.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionMessageBean.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
https://sakaiproject.atlassian.net/browse/SAK-47306
> SAK-47306 Forums - Word count is missing on the 'Statistics & Grading' tab

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://sakaiproject.atlassian.net/browse/SAK-47308
> SAK-47308 Discussions - Approving multiple messages does not reload the page and does not show any message

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
[SAK-47401: Messages: Error jquery Datatable](https://sakaiproject.atlassian.net/browse/SAK-47401)
> SAK-47401: Messages: Error jquery Datatable

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/ForumEntity.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47391
> SAK-47391 LESSONS: Edit the groups for which this item should be shown is not working for Topic

- calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/subscribe.jsp
https://sakaiproject.atlassian.net/browse/SAK-46826
> SAK-46826: Overview > Calendar > Publish (private): produces bug report error

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Assignments filters Published Active and Published Inactive were showing drafts.
> SAK-47413 Assignments: Fix published filters showing drafts

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
https://sakaiproject.atlassian.net/browse/SAK-47390
> SAK-47390 rubrics: rubric evaluation not printing for student

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-47414
- Student and section sorting was not working
> SAK-47414 Gradebook - Trying to order datatable does not work

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Useful for resolving references in Lessons archive XML
> SAK-47432 Add the Forum ID to the site archive export

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
[SAK-47326: Private message scheduling should maintain date when an error is shown](https://sakaiproject.atlassian.net/browse/SAK-47326)
> SAK-47326: Private message scheduling should maintain date when an error is shown

- webcomponents/bundle/src/main/bundle/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
https://sakaiproject.atlassian.net/browse/SAK-47379
> SAK-47379 conversations: stop other students seeing late flag

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
[SAK-47441: Messages: Do not clear search text](https://sakaiproject.atlassian.net/browse/SAK-47441)
> SAK-47441: Messages: Do not clear search text

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
[Messages: View->By Conversation (none style tittleHeaders)](https://sakaiproject.atlassian.net/browse/SAK-47440)
> SAK-47440: Messages: View->By Conversation (none style tittleHeaders)

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
https://sakaiproject.atlassian.net/browse/SAK-47139
It's only a null checking about **if (answers != null)** .
All code is the same but with indentation
> SAK-47139 SAMIGO Empty questions cause an error when exporting and downloading all responses to Excel

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java
I added a new control before getting the value of the Optional variable.
> SAK-47453 Assignments: Stacktrace on peer assessment

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/grader/submission.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-site-title.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-list.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-shared-list.js
https://sakaiproject.atlassian.net/browse/SAK-47455
> SAK-47455 rubrics: cut ajax calls to getSiteTitle down

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
https://sakaiproject.atlassian.net/browse/SAK-47459
I just insert a condition checking if list the attachament list exists
> SAK-47459 Assignments: No "Attachment" word should appear if there isn't any attachment on peer assignment

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
[SAK-47444: Messages: Incorrect redirection when saving draft on reply](https://sakaiproject.atlassian.net/browse/SAK-47444)
> SAK-47444: Messages: Incorrect redirection when saving draft on reply

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://sakaiproject.atlassian.net/browse/SAK-47403
> SAK-47403 Discussions: Pending messages are not refreshed on the main tab when approving or deny from the topic

- library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_jumbotron.scss
- library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_variables.scss
- library/src/morpheus-master/sass/base/_bootstrap-defaults.scss
- library/src/morpheus-master/sass/themes/_dark.scss
- library/src/morpheus-master/sass/themes/_light.scss
https://sakaiproject.atlassian.net/browse/SAK-47343
Before:
After:
We don't know if this is the right way to solve this one.
> SAK-47343: Dark mode: Honor pledge (student view)

- webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
https://sakaiproject.atlassian.net/browse/SAK-47456
> SAK-47456 conversations: fix console error while hiding posts

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
[SAK-47464: Worklog: No records appear on Time Sheet tab when a student added some record and sent the assignment](https://sakaiproject.atlassian.net/browse/SAK-47464)
> SAK-47464: Worklog: No records appear on Time Sheet tab when a student added some record and sent the assignment

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
[SAK-47468: Error jquery in messages "By Conversation"](https://sakaiproject.atlassian.net/browse/SAK-47468)
> SAK-47468: Error jquery in messages "By Conversation"

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47458
> SAK-47458 Grader: Only the groups to which the TA belongs should appear in the new grader

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
https://sakaiproject.atlassian.net/browse/SAK-47483
Removing "yellow" color
> SAK-47483: Peer assignment: No attachment color on peer assignment on review part

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- kernel/api/src/main/java/org/sakaiproject/timesheet/api/TimeSheetService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/timesheet/impl/TimeSheetServiceImpl.java
[SAK-47460: Worklog: When removing a record the student can use the time](https://sakaiproject.atlassian.net/browse/SAK-47460)
> SAK-47460: Worklog: When removing a record the student can use the time

- assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
[SAK-47490: Worklog: Fix excel of time spent](https://sakaiproject.atlassian.net/browse/SAK-47490)
> SAK-47490: Worklog: Fix excel of time spent

- library/src/morpheus-master/sass/modules/navigation/_base.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/siteStatus-snippet.vm
Jira: [SAK-47133](https://sakaiproject.atlassian.net/browse/SAK-47133)
- Remove `<h4>` as an A11y improvement.
- Add `aria-describedby`.
- Use the standard Sakai banner.
> SAK-47133 Portal: Remove heading tag from unpublished site banner

- assignment/api/src/resources/assignment.properties
- assignment/api/src/resources/assignment_es.properties
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
[SAK-47407: Worklog: Adding worklog on new grader](https://sakaiproject.atlassian.net/browse/SAK-47407)
> SAK-47407: Worklog: Adding worklog on new grader

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://sakaiproject.atlassian.net/browse/SAK-47510
> SAK-47510: LESSONS: Wrong top parent on Add Layout -> Subpage Listing

- library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
https://sakaiproject.atlassian.net/browse/SAK-47513
> SAK-47513 Check for bullhorn element being present

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
[SAK-47508: Assignments API Rest improvements](https://sakaiproject.atlassian.net/browse/SAK-47508)
> SAK-47508: Assignments API Rest improvements

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47524
> SAK-47524 WC Grader - Add Assigment Submission header

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
topic post count
https://sakaiproject.atlassian.net/browse/SAK-47529
> SAK-47529 conversations: swallow duplicate exception when incrementing

- assignment/tool/src/webapp/js/assignments.js
This is 22.x only manual patch
> SAK-47538 fix JS console error only in 22

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
https://sakaiproject.atlassian.net/browse/SAK-47499
> SAK-47499 GB: stacktrace when attempting to set a rule for a TA

- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
https://sakaiproject.atlassian.net/browse/SAK-47545
> SAK-47545 Site Info: View Members link is not working

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
https://sakaiproject.atlassian.net/browse/SAK-47544
> SAK-47544 rubrics: allow rubric grading in discussions

- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/BaseElasticSearchIndexBuilder.java
- search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/ContentHostingContentProducer.java
https://sakaiproject.atlassian.net/browse/SAK-47542
> SAK-47542 Search security check returns false if secured prop is missing

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html
https://sakaiproject.atlassian.net/browse/SAK-47499
> SAK-47499 GB stacktrace when attempting to set a rule for a TA

- basiclti/basiclti-blis/src/java/org/sakaiproject/lti/entityprovider/LTIEntityProvider.java
- basiclti/basiclti-blis/src/test/org/sakaiproject/lti/entityprovider/LTIEntityProviderTest.java
Support the XML format in addition to json
> SAK-47446 Support XML format for /direct/lti/ endpoint

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-46913
> SAK-46913 grader: ensure navigation clears rubric

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47411
> SAK-47411 conversations: don't count anon posts in topic resolution

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
- kernel/api/src/main/java/org/sakaiproject/content/api/FileConversionService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/FileConversionServiceTest.java
- webcomponents/tool/src/main/frontend/js/grader/sakai-gradable-data-mixin.js
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://sakaiproject.atlassian.net/browse/SAK-47475
> SAK-47475 grader: ensure docx opens in preview  panel

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
https://sakaiproject.atlassian.net/browse/SAK-47559
This piece of code was removed by error on: https://sakaiproject.atlassian.net/browse/SAK-47139
it was introduced here: https://sakaiproject.atlassian.net/browse/SAK-42179
> SAK-47559: Improve graphical display of test statistics (removed by error)

- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-tag-manager.js
https://sakaiproject.atlassian.net/browse/SAK-47263
> SAK-47263 conversations: block duplicate tags in tag manager

- content/content-bundles/resources/content.properties
- content/content-bundles/resources/content_es.properties
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
https://sakaiproject.atlassian.net/browse/SAK-47572
> SAK-47572 Content: Title is missing from file

- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47586
> SAK-47586 rubrics: set creator id and dest site it on rubrics import

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
https://sakaiproject.atlassian.net/browse/SAK-47576
> SAK-47576 rubrics: rubric button displaying even if no rubrics

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-47304
> SAK-47304 Samigo deleting assessment part removes question from pool

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47584
It's only a null checker and the indentations.
https://github.com/sakaiproject/sakai/pull/10744/files#diff-6c59c84e25a593257fed1b6890a60f654495573e4366cf3a181f8fd1fc0da5c9R1783
addSubmission method could return null here:
https://github.com/sakaiproject/sakai/blob/master/assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java#L1348
> SAK-47584 Assignments Error when trying submit an assigments as student (if you are admin which not belong to the site)

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://sakaiproject.atlassian.net/browse/SAK-47590
> SAK-47590 discussions: set gb assignment on duplication

- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/ReferenceComponent.java
- search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/ContentHostingContentProducer.java
https://sakaiproject.atlassian.net/browse/SAK-47595
> SAK-47595 Kernel getProperties should return null if none exist

- profile2/tool/src/java/org/sakaiproject/profile2/tool/components/IconWithToolTip.html
https://sakaiproject.atlassian.net/browse/SAK-47592
> SAK-47592 Profile: Title on Icon i is missing on Widget Settings from Preferences tab (mobile phone)

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47458
> SAK-47458 Assignments - TA can see and grade student submissions from groups to which TA does not belong

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java
For externally maintained gradebook items from assignments that have a rubric
use the student read-only view of the rubric in the gradebook.
> SAK-41579 GBNG view-only rubric view for external items

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47628
> SAK-47628 Assignment > Student View, user attempts to submit who is not a member of the site

- roster2/tool/src/handlebars/members_container_table.handlebars
https://sakaiproject.atlassian.net/browse/SAK-46761
> SAK-46761 Roster / columns incorrect when using list view and hiding photos

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-shared-list.js
https://sakaiproject.atlassian.net/browse/SAK-47583
> SAK-47583 rubrics: fix copying of shared rubric into site

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-list.js
https://sakaiproject.atlassian.net/browse/SAK-47644
> SAK-47644 rubrics: expand new rubric on creation

- conversations/api/pom.xml
- conversations/api/src/main/java/org/sakaiproject/conversations/api/ShowDateContext.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/TopicShowDateMessager.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/TopicTransferBean.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConversationsTopic.java
- conversations/impl/pom.xml
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/TopicShowDateMessagerImpl.java
- conversations/impl/src/main/webapp/WEB-INF/components.xml
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsTestConfiguration.java
https://sakaiproject.atlassian.net/browse/SAK-47609
> SAK-47609 Conversations: Schedule show topic messages

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47609
> SAK-47609 conversations: check sendMail flag in scheduled messages

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/AssessmentFeedbackIfc.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/TemplateMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBeanie.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/FeedbackComponent.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentBase.hbm.xml
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentFeedback.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedFeedback.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://sakaiproject.atlassian.net/browse/SAK-47629
> SAK-47629 samigo: Add incorrect answer filter to student feedback

- roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-46487
> SAK-46487 Roster- Card layout does not display on iPhone 6/7/8 & several Android devices

- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-4763
7
> SAK-47637 grader: add warning when filter settings are in action

- webcomponents/tool/src/main/frontend/.eslintrc.js
- webcomponents/tool/src/main/frontend/js/conversations/conversations-statistics.js
- webcomponents/tool/src/main/frontend/js/conversations/options-menu.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment-editor.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-settings.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-tag-manager.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-list.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-summary.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/sakai-permissions.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-panel.js
- webcomponents/tool/src/main/frontend/package-lock.json
- webcomponents/tool/src/main/frontend/package.json
https://sakaiproject.atlassian.net/browse/SAK-47598
> SAK-47598 conversations: add lit-analyzer and lit-html analysis

- gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java
- gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47481
> SAK-47481 gradebook: init gradebook on getAssignments call

- polls/tool/src/java/org/sakaiproject/poll/tool/entityproviders/PollVoteEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47658
> SAK-47658 Polls - Improve error handling in poll-vote

- library/src/morpheus-master/js/src/sakai.morpheus.profile.popup.js
- roster2/tool/src/handlebars/members_cards.handlebars
- roster2/tool/src/handlebars/members_photogrid.handlebars
- roster2/tool/src/handlebars/members_table.handlebars
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-47614
> SAK-47614 roster: pass title to user photo

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
https://sakaiproject.atlassian.net/browse/SAK-47636
> SAK-47636 assignments: display "" as grade for ungraded submissions

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47630
> SAK-47630 grader: fix ungraded filter

- sitestats/sitestats-bundle/src/resources/Messages.properties
- sitestats/sitestats-bundle/src/resources/Messages_es.properties
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/ImageWithLink.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportDataPage.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ResourcesWidget.java
https://sakaiproject.atlassian.net/browse/SAK-47631
> SAK-47631 SiteStats Most opened file can be null

- library/src/morpheus-master/sass/modules/tool/roster/_roster.scss
- roster2/tool/src/handlebars/enrollment_status.handlebars
- roster2/tool/src/handlebars/overview.handlebars
https://sakaiproject.atlassian.net/browse/SAK-47655
> SAK-47655 ROSTER List view is not visible on mobile view

- syllabus/syllabus-app/src/webapp/js/syllabus.js
I don't think this error was really caused by the JSF upgrade, but fixed it under this jira since that's where it was reported.  My guess is maybe it was a jquery/jquery-ui upgrade that really broke it?  Not for sure, but this change removes the console error and the items are not sortable in the student view (but still are in the instructor view).
> SAK-45501 - Syllabus console error in student view

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-utils.js
Fix for [#10776](https://github.com/sakaiproject/sakai/pull/10776)
Total Grade for weighted Rubrics:
-  wasn't being calculated correctly when using Criterion Groups.
-  wasn't updating when Ratings where added or removed.
> SAK-47640 Rubrics Fix: Total Grade not updating correctly

- signup/tool/src/java/org/sakaiproject/signup/tool/entityproviders/MySignupEventsProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47688
> SAK-47688 Direct request failure: IllegalArgumentException:Invalid event id (:ID:), the id must be a number

- signup/tool/src/java/org/sakaiproject/signup/tool/entityproviders/SignupEventEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47689
> SA-47689 Direct request failure: IllegalArgumentException:Invalid event id (:ID:), the id must be a number -- signupEvent

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47666
> SAK-47666 Assignments: Grading screen no longer visible

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47650
> SAK-47650 Assignments - Add submission timestamp field and submission grade to the simple objects returned by the endpoint

- calendar/calendar-bundles/resources/calendar.properties
- calendar/calendar-bundles/resources/calendar_es.properties
- calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/calendar.jsp
https://sakaiproject.atlassian.net/browse/SAK-47621
> SAK-47621 Accessibility problem on 'Widget' on Home

- portal/portal-tool/tool/pom.xml
- portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java
Related to: [#10656](https://github.com/sakaiproject/sakai/pull/10656)
Jira: [SAK-47596](https://sakaiproject.atlassian.net/browse/SAK-47596)
On Discussions tool, iFrames were missing some head imports (css, js), resulting in an unstyled interface.
> SAK-47596 Grading discussion topic: Uncaught ReferenceError: includeWebjarLibrary is not defined

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
Jira: [SAK-47705](https://sakaiproject.atlassian.net/browse/SAK-47705)
> SAK-47705 Discussions: Error after removing GB item associated to Forum or Topic

- common/import-impl/pom.xml
- common/import-parsers/blackboard_5-5/pom.xml
- common/import-parsers/blackboard_6/impl/pom.xml
- common/import-parsers/common-cartridge/pom.xml
- samigo/samigo-qti/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47663
> SAK-47663 Projects should use the common jaxen lib

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://sakaiproject.atlassian.net/browse/SAK-47686
> SAK-47686 T&Q: Add site id to total scores grading rubrics

- commons/tool/src/webapp/WEB-INF/templates/comment.hbs
- commons/tool/src/webapp/WEB-INF/templates/post.hbs
- roster2/tool/src/handlebars/members_photogrid.handlebars
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-47713
Fixes Conversations, Roster, Commons and the Grader
Fixes the issue with the latest version of Chrome with its new popup
api. popup is now a protected attribute in Chrome.
> SAK-47713 various: some user photos needs to popup the profile

- assignment/api/src/resources/assignment.properties
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
- library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
https://sakaiproject.atlassian.net/browse/SAK-47716
> SAK-47716 assignments: add user photos on grading page

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
https://sakaiproject.atlassian.net/browse/SAK-47723
> SAK-47723 gradebook: add user photos to user rows

- webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://sakaiproject.atlassian.net/browse/SAK-47721
> SAK-47721 rubrics: use uniqe ids for rubrics summary panels

- library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/submissionStatus.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-47727
> SAK-47727 t&q: add user photos to scores pages

- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
- chat/chat-tool/tool/src/webapp/js/chatscript.js
- chat/chat-tool/tool/src/webapp/jsp/room.jsp
- chat/chat-tool/tool/src/webapp/jsp/roomMonitor.jspf
- library/src/morpheus-master/sass/base/_defaults.scss
- library/src/morpheus-master/sass/modules/tool/chat/_chat.scss
- webcomponents/tool/src/main/frontend/js/sakai-user-photo.js
https://sakaiproject.atlassian.net/browse/SAK-47734
> SAK-47734 chat: use user photo component

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://sakaiproject.atlassian.net/browse/SAK-46773
> SAK-46773 Lessons delete overwrites sequence when reordering

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java
- rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/FullSearchBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SearchQuestionBean.java
- samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/QuestionElasticSearchIndexBuilder.java
- search/elasticsearch/api/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchIndexBuilder.java
- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchList.java
- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java
- search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/BaseElasticSearchIndexBuilder.java
- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java
- search/search-api/api/src/java/org/sakaiproject/search/api/SearchService.java
- search/search-tool/tool/src/java/org/sakaiproject/search/tool/SearchBeanImpl.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/SearchController.java
https://sakaiproject.atlassian.net/browse/SAK-47754
> SAK-47754 search: let colon containing searches be parsed fully

- assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
- assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://sakaiproject.atlassian.net/browse/SAK-47394
> SAK-47394 Assignments switch to "read-through" vs "write-through" cache

- polls/tool/src/java/org/sakaiproject/poll/tool/entityproviders/PollEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47773
> SAK-47773 Polls direct request failure: IllegalArgumentException:Invalid poll id (:ID:), the id must be a number

- library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
- library/src/webapp/js/sakai-message-broker.js
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- webapi/src/main/java/org/sakaiproject/webapi/WebMvcConfiguration.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/EventsController.java
- webapi/src/main/resources/static/sakai-sse-service-worker.js
https://sakaiproject.atlassian.net/browse/SAK-47792
> SAK-47792 Add a service worker to handle a single EventSource

- entitybroker/rest/src/java/org/sakaiproject/entitybroker/rest/EntityHandlerImpl.java
- entitybroker/rest/src/test/org/sakaiproject/entitybroker/rest/EntityHandlerImplTest.java
[SAK-47775: Direct request failure: IllegalArgumentException:Invalid reference (/assignment/my)](https://sakaiproject.atlassian.net/browse/SAK-47775)
> SAK-47775: Direct request failure: IllegalArgumentException:Invalid reference (/assignment/my)

- lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-47767
Using locale instead of MM/DD/YYYY
> SAK-47767 Error when editing dates on Items from Lessons

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-47408
> SAK-47408 - Worklog: Removing blankspace before time

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47594
> SAK-47594 conversations: use formatted calendar description

- library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic-summary.scss
https://sakaiproject.atlassian.net/browse/SAK-47569
> SAK-47569 conversations: improve tag pill contrast

- webapi/src/main/java/org/sakaiproject/webapi/beans/GradeRestBean.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
- webcomponents/bundle/src/main/bundle/grades.properties
- webcomponents/tool/src/main/frontend/js/grades/sakai-grades-constants.js
- webcomponents/tool/src/main/frontend/js/grades/sakai-grades.js
https://sakaiproject.atlassian.net/browse/SAK-45040
> SAK-45040 Make grades widget show - for no grades

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
[SAK-47812: Remove deprecated code on Assignment Entity provider](https://sakaiproject.atlassian.net/browse/SAK-47812)
> SAK-47812 Assignment remove deprecated code on Assignment Entity provider

- webcomponents/tool/src/main/frontend/js/sakai-toggle.js
https://sakaiproject.atlassian.net/browse/SAK-47759
> SAK-47759 Conversations: make toggle buttons correct height

- conversations/api/src/main/resources/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-summary.js
https://sakaiproject.atlassian.net/browse/SAK-47771
> SAK-47771 conversations: update tooltip for unread icon

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java
https://sakaiproject.atlassian.net/browse/SAK-47830
Regression from: https://sakaiproject.atlassian.net/browse/SAK-46281
> SAK-47830 ORACLE: Add Resources Folder doesn't work on Lessons tool if site id contains '_' character

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
https://sakaiproject.atlassian.net/browse/SAK-47850
> SAK-47850 FORUMS: org.sakaiproject.portal.api.PortalHandlerException: /jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp(219,5)

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
[SAK-47865: Error 500: /direct/lessons/user.xml](https://sakaiproject.atlassian.net/browse/SAK-47865)
> SAK-47865: Error 500: /direct/lessons/user.xml

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-46303
> SAK-46303 grader: use full ckeditor in notes sections

- assignment/tool/src/webapp/js/assignments.js
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
- content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/skins/default/src/sass/base/_extendables.scss
- library/src/skins/default/src/sass/modules/tool/_menu.scss
- library/src/skins/default/src/sass/modules/tool/assignments/_assignments.scss
- library/src/skins/default/src/sass/modules/tool/navigation/_base.scss
- library/src/skins/default/src/sass/modules/tool/navigation/_breadCrumbs.scss
- library/src/skins/default/src/sass/modules/tool/navigation/_navigation_mixins.scss
- library/src/skins/default/src/sass/modules/tool/navigation/_skipnav.scss
- library/src/skins/default/src/sass/modules/tool/reorderer/_base.scss
- library/src/skins/default/src/sass/print.scss
- library/src/skins/default/src/sass/properties.scss
- library/src/skins/default/src/sass/themes/_light.scss
- library/src/skins/default/src/sass/tool.scss
Minimal Bootstrap-5 class update, and added some missing CSS to match Morpheus look.
> TRIN - Add Bootstrap-5 classes

- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/EntityManagerComponent.java
https://sakaiproject.atlassian.net/browse/SAK-47891
> SAK-47891 Fixed npe in EntityManagerComponent when getting entity url

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/models/CHResourceModel.java
https://sakaiproject.atlassian.net/browse/SAK-47764
> SAK-47764 Sitestats fix injection of Formattedtext in CHResourceModel

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/ShowAttachmentMediaServlet.java
https://sakaiproject.atlassian.net/browse/SAK-47895
Solving error 500 when trying opening an image from Test & Quizzes without session
Regression from: https://sakaiproject.atlassian.net/browse/SAK-46414
> SAK-47895 Error 500 samigo-app/servlet/ShowAttachmentMedia

- syllabus/syllabus-api/src/java/org/sakaiproject/api/app/syllabus/SyllabusData.java
[SAK-47900: ORACLE: Error while importing syllabus](https://sakaiproject.atlassian.net/browse/SAK-47900)
> SAK-47900: ORACLE: Error while importing syllabus

- edu-services/sections-service/sections-api/src/java/org/sakaiproject/section/api/facade/manager/Authz.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/facade/sakai/AuthzSakaiImpl.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/CourseDependentBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditStudentSectionsBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditStudentsBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/FilteredSectionListingBean.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/RosterBean.java
- sections/sections-app/src/webapp/WEB-INF/spring-services.xml
https://sakaiproject.atlassian.net/browse/SAK-47854
> SAK-47854: User whith Admin role should manage groups

- library/src/morpheus-master/sass/modules/grader/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-47906
> SAK-47906 WC Grader - Bad style on Firefox when clicking cog icon

- webapi/src/main/resources/static/sakai-sse-service-worker.js
https://sakaiproject.atlassian.net/browse/SAK-47926
> SAK-47926 bullhorns: forward sse events to all clients

- library/src/webapp/content/webcontent_instructions_es.html
https://sakaiproject.atlassian.net/browse/SAK-47697
> SAK-47967 Changing Opciones to Editar

- admin-tools/src/java/org/sakaiproject/archive/tool/ArchiveAction.java
- admin-tools/src/webapp/vm/archive/chef_archive.vm
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
* Distinguish between success and failure cases and show success or alert 
* Handle exceptions from service archive() methods as failure cases 
* Include the archive log as part of the archive in archive.xml
> SAK-47907 Archive UI, logging and error handling improvements

- kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/MultiSingleStorageSqlOracle.java
- kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/SingleStorageSqlOracle.java
https://sakaiproject.atlassian.net/browse/SAK-47955
@ottenhoff @ern This is the second regression from https://sakaiproject.atlassian.net/browse/SAK-46281
Maybe there is some other regression but I don't know it right now.
Similar solution: https://github.com/sakaiproject/sakai/pull/10869
> SAK-47955 ORACLE Not possible to recover resources from Trash

- entitybroker/rest/src/java/org/sakaiproject/entitybroker/rest/EntityHandlerImpl.java
[SAK-47894: Error 500 - Direct request failure: EntityNotFoundException:Invalid user.](https://sakaiproject.atlassian.net/browse/SAK-47894)
> SAK-47894: Error 500 - Direct request failure: EntityNotFoundException:Invalid user.

- deploy/pom.xml
- kernel/api/pom.xml
- kernel/kernel-impl/pom.xml
- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47954
> SAK-47954 Global upgrade apache ignite to 2.14.0

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47982
> SAK-47982 Discussions new unproxied topic causes cast exception

- library/src/skins/default/src/sass/base/_icons.scss
- plus/tool/src/main/webapp/WEB-INF/templates/context.html
- plus/tool/src/main/webapp/WEB-INF/templates/contexts.html
- plus/tool/src/main/webapp/WEB-INF/templates/delete.html
- plus/tool/src/main/webapp/WEB-INF/templates/form.html
- plus/tool/src/main/webapp/WEB-INF/templates/index.html
- plus/tool/src/main/webapp/WEB-INF/templates/notallow.html
- plus/tool/src/main/webapp/WEB-INF/templates/notfound.html
- plus/tool/src/main/webapp/WEB-INF/templates/tenant.html
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PlusHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePagePlus.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/plus.vm
> SAK-47999 - Trinity Fixes for SakaiPlus and LTI

- library/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-48001
> SAK-48001 Bootstrap icons are not visible in the trinity portal

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- library/src/skins/default/src/sass/themes/_light.scss
- library/src/webapp/js/portal/portal.sidebar.collapse.js
- library/src/webapp/js/portal/portal.sidebar.sites.js
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48004
> SAK-48004 portal: sites sidebar stays collapsed across reloads

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
[SAK-48002: Discussion: Uncaught TypeError: document.getElementById(...) is null](https://sakaiproject.atlassian.net/browse/SAK-48002)
> SAK-48002: Discussion: Uncaught TypeError: document.getElementById(...) is null

- common/common-composite-component/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonManagerImpl.java
- common/common-composite-component/src/java/org/sakaiproject/component/common/type/TypeManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48007
@ern It makes sense these changes
> SAK-48007 org.sakaiproject.profile2.logic.SakaiProxyImpl.getSakaiPerson SakaiProxy.getSakaiPerson(): Couldn't get SakaiPerson

- sitestats/sitestats-bundle/src/resources/Messages.properties
- sitestats/sitestats-bundle/src/resources/Messages_es.properties
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/FileSelectorPanel.java
https://sakaiproject.atlassian.net/browse/SAK-48025
> SAK-48025 SITESTATS Avoid NULL when creating a report and there are folders from different TAs

- lessonbuilder/tool/src/webapp/templates/Reorder.html
This second PR fixes the problem with Cancel while preserving the intent to prevent double-clicks for Save introduced with SAK-47320.
> SAK-46509 - Fixed Cancel while preserving spinner for Save

- rubrics/api/src/main/bundle/rubrics.properties
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-button.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-preview-button.js
If the rubric point value is ever displayed elsewhere (e.g., in the Rubrics tool), then a refactored version of calcMaxPoints should likely be placed elsewhere in the rubrics webcomponents code. That said, this is a first step toward remedying the scenario where instructors use Rubrics for the first time, as described in SAK-47876.
> SAK-47876 - Rubrics: Display warning & rubric point values in rubric association

- admin-tools/src/webapp/vm/sites/chef_sites_edit_tool.vm
https://sakaiproject.atlassian.net/browse/SAK-48036
> SAK-48036 sites: changed from bootstrap-multiselect

- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/EditMeetingSignupMBean.java
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
https://sakaiproject.atlassian.net/browse/SAK-47068
> SAK-47068 SignUp Add drop down with list of current groups separate from drop down to modify them

- library/src/webapp/js/lang-datepicker/lang-datepicker.js
https://sakaiproject.atlassian.net/browse/SAK-41260
> SAK-41260 Accessibility date picker and calendar widget once open with keyboard

- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java
- site-manage/pageorder/tool/src/webapp/content/css/PageList.css
- site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js
- site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
https://sakaiproject.atlassian.net/browse/SAK-48035
> SAK-48035 siteinfo: fix tool reorder for trinity

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
https://sakaiproject.atlassian.net/browse/SAK-46372
> SAK-46372 Discussions comments auto-fill is not available in statistics when grading by topic

- library/src/skins/default/src/sass/modules/_toolmenu.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48056
> SAK-48056 portal: use less space under expanded tool lists

- master/pom.xml
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java
- samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
New version of mXparser
Some new tests
New code because of some E test was failing: https://github.com/mariuszgromada/MathParser.org-mXparser/issues/282
> SAK-47892 Upgrading mXparser to 5.1.0

- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://sakaiproject.atlassian.net/browse/SAK-48061
> SAK-48061 siteinfo: If site.term is empty, don't check dates

- .github/workflows/maven.yml
The problem is that one bad translation will blow up Spring init
See https://sakaiproject.atlassian.net/browse/SAK-47085
> Grep and check for bad unicode characters

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://sakaiproject.atlassian.net/browse/SAK-48070
> SAK-48070 assignments: configure resubmit date picker correctly

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
Info: [SAK-48067](https://sakaiproject.atlassian.net/browse/SAK-48067)
> SAK-48067 T&Q - Questions: Responses table breaks when accessing next page + inconsistent search

- admin-tools/src/webapp/js/userCreateValidation.js
- admin-tools/src/webapp/js/userEditValidation.js
- admin-tools/src/webapp/js/userValidationCommon.js
- admin-tools/src/webapp/vm/user/chef_users_create.vm
- admin-tools/src/webapp/vm/user/chef_users_edit.vm
- library/src/skins/default/src/sass/modules/tool/admin/_admin.scss
https://sakaiproject.atlassian.net/browse/SAK-48075
Also, cleaned up the user validation js, moved the validation call to fetch and async.
> SAK-48075 User address layout issue with Trinity

- .github/workflows/maven.yml
- .github/workflows/server.yml
- bad-unicode.properties
Please do not merge until we can confirm:
1) the badunicode.properties file I uploaded produces a FAIL
2) the badunicode.properties file we will remove produces a PASS
> Using a simple bash script instead of the Github action module

- library/src/webapp/js/portal/portal.sidebar.sites.js
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48078
> SAK-48078 portal: remove event handler for tool menu clicks

- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIRoleMapperImpl.java
- kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql
- kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql
- kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
- library/src/skins/default/src/sass/tool.scss
- plus/docs/TESTING.md
- plus/tool/src/main/resources/Messages.properties
- plus/tool/src/main/webapp/WEB-INF/templates/form.html
Plus a bit of cleanup along the way.
> SAK-48053 - Fall to the JoinerRole when mapping roles

- admin-tools/src/webapp/js/userCreateValidation.js
https://sakaiproject.atlassian.net/browse/SAK-48079
> SAK-48079 - Cannot create new user on Nightly (blocker / regression)

- .gitignore
Two more generated directories can be ignored
> NOJIRA - update .gitignore

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ro_RO.properties
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Un-hardcode title in samigo assessment settings
Fix typo in property key
https://sakaiproject.atlassian.net/browse/SAK-48094
> SAK-48094 Samigo: Assessment Settings "Scoring and Grading" is hardcoded

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48081
> SAK-48081 - Two line page titles in portal don't line up

- library/src/skins/default/src/sass/tool.scss
https://sakaiproject.atlassian.net/browse/SAK-48090
> SAK-48090 - Regression in Choose a custom icon in External Tools

- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
I missed closing brackets in this PR https://github.com/sakaiproject/sakai/pull/11030
This would break samigo settings
> SAK-48103 Add missing closing brackets

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionMessageBean.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
https://sakaiproject.atlassian.net/browse/SAK-48038
> SAK-48038 CLONE - Forums - Error when grading a forum if the gradebook item was deleted

- roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
[SAK-47674: ROSTER: Improving method getAndCacheSortedMembership](https://sakaiproject.atlassian.net/browse/SAK-47674)
> SAK-47674: ROSTER: Improving method getAndCacheSortedMembership

- library/src/skins/default/src/sass/modules/tool/conversations/_conversations.scss
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-48116
Also, convert links to buttons. Semantic, innit.
> SAK-48116 conversations: show general setting button

- samigo/samigo-app/src/webapp/jsf/qti/xmlDisplay.jsp
- samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ImportService.java
https://sakaiproject.atlassian.net/browse/SAK-48104
> SAK-48104 SAMIGO - Some fixing while importing ZIP

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- library/src/webapp/js/portal/portal.sidebar.sites.js
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48121
> SAK-48121 portal: Add popover for site description

- library/src/skins/default/src/sass/modules/tool/navigation/_base.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/roleSwitch-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-48126
> SAK-48126: Trinity Portal: Fix Role Switcher

- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/profile2/_profile2.scss
- profile2/tool/pom.xml
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewProfile.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyBusinessDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyContactDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInterestsDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStaffDisplay.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStudentDisplay.html
- profile2/tool/src/webapp/javascript/profile2.js
- profile2/tool/src/webapp/javascript/pronunciation.js
https://sakaiproject.atlassian.net/browse/SAK-48012
> SAK-48012 profile: Fix section edit button placement issues

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
- webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
> SAK-48142 - Remove excessive "Error retrieving role on site undefined Errors in the log

- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47905
Similar to: https://github.com/sakaiproject/sakai/pull/10908
> SAK-47905 Wiki - Changing HibernateOptimisticLockingFailureException?

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/TopicEntityProviderImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46626
> SAK-46626 Messages Refactor method getDecoratedForum() and more

- commons/tool/src/webapp/WEB-INF/templates/comment.hbs
- commons/tool/src/webapp/WEB-INF/templates/inplace_comment_editor.hbs
- commons/tool/src/webapp/WEB-INF/templates/inplace_post_editor.hbs
- commons/tool/src/webapp/WEB-INF/templates/post.hbs
- commons/tool/src/webapp/WEB-INF/templates/posts.hbs
- commons/tool/src/webapp/js/commons.js
- commons/tool/src/webapp/js/commons_utils.js
- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/commons/_commons.scss
https://sakaiproject.atlassian.net/browse/SAK-48159
> SAK-48159 commons: trinity update to buttons and icons

- basiclti/basiclti-oidc/src/bundle/oidc.properties
- basiclti/basiclti-oidc/src/java/org/sakaiproject/lti13/OIDCServlet.java
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
- basiclti/tsugi-util/src/java/org/tsugi/basiclti/BasicLTIUtil.java
> SAK-42271 - Improve returning inside iFrame from LTI in browser rediects

- login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm
- login/login-tool/tool/src/bundle/auth.properties
https://sakaiproject.atlassian.net/browse/SAK-48175
> SAK-48175  TRINITY: Sign In > Wrong Password > No error message

- assignment/api/src/resources/templates/submission.xml
https://sakaiproject.atlassian.net/browse/SAK-48203
> SAK-48203 Assignments: test for submitter ids in email template

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/BeanDateComparator.java
https://sakaiproject.atlassian.net/browse/SAK-48202
> SAK-48202 SAMIGO Comparison method violates its general contract!

- admin-tools/src/java/org/sakaiproject/authz/tool/RealmsAction.java
- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java
- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- userauditservice/tool/src/bundle/UserAuditMessages.properties
- userauditservice/tool/src/bundle/UserAuditMessages_ca.properties
- userauditservice/tool/src/bundle/UserAuditMessages_es.properties
- userauditservice/tool/src/java/org/sakaiproject/userauditservice/tool/UserAuditEventLog.java
This could need a conversion script for old values, I'm currently working on it. But wIthout the conversion script it would still working as it's working now.
> SAK-48106 UserAuditLogs is not saving consistently the userId and sometimes is using userEid

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.html
- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-sorter.css
https://sakaiproject.atlassian.net/browse/SAK-48172
> SAK-48172 Gradebook: Item Order modal dialog does not display

- webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
https://sakaiproject.atlassian.net/browse/SAK-48186
> SAK-48186 tasks: ensure optionsGroup is initialised

- webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
https://sakaiproject.atlassian.net/browse/SAK-48196
> SAK-48196 Dark mode: Add a new task button is difficult to read

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
- library/pom.xml
- library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-48194
> SAK-48194 resources: fixed multiselect in folder details

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionOutcomeTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RatingTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Criterion.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/CriterionOutcome.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Evaluation.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rating.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ReturnedCriterionOutcome.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ReturnedEvaluation.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/EvaluationRepository.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/RubricRepositoryImpl.java
- rubrics/impl/src/main/webapp/WEB-INF/components.xml
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsTestConfiguration.java
- rubrics/impl/src/test/resources/hibernate.properties
- webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
https://sakaiproject.atlassian.net/browse/SAK-47837 
There is also a lot of persistence updates in this patch
> SAK-47837 Rubrics importing rubrics to other sites

- webcomponents/tool/src/main/frontend/js/sui-picture-changer/sui-picture-changer.js
https://sakaiproject.atlassian.net/browse/SAK-48214
> SAK-48214 Profile: The profile image is not updated immediately after uploading a new image.

- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
https://sakaiproject.atlassian.net/browse/SAK-48206
> SAK-48206 File titles in Resources are doubled

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/CommentsProducer.java
https://sakaiproject.atlassian.net/browse/SAK-48118
> SAK-48118 avoid insert when currentUserId is null

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48237
MySQL doesn't support self referencing updates or deletes
MariaDB supports self refenrencing updates since 10.3
> SAK-48237 Rubrics import from site using replace data fails with SQL exception

- library/src/webapp/js/lessons-subnav.js
https://sakaiproject.atlassian.net/browse/SAK-48243
> SAK-48243 - Imported Lessons Content Appears incorrectly in the Left Navigation

- kernel/api/src/main/java/org/sakaiproject/messaging/api/UserMessagingService.java
- kernel/api/src/main/java/org/sakaiproject/messaging/api/UserNotification.java
- kernel/api/src/main/java/org/sakaiproject/messaging/api/repository/UserNotificationRepository.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/repository/UserNotificationRepositoryImpl.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/messaging-components.xml
- kernel/kernel-impl/src/test/java/org/sakaiproject/messaging/impl/UserMessagingServiceTestConfiguration.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/messaging/impl/UserMessagingServiceTests.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java
- webapi/src/main/resources/static/sakai-sse-service-worker.js
- webcomponents/bundle/src/main/bundle/sui-notifications.properties
- webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
https://sakaiproject.atlassian.net/browse/SAK-48245
> SAK-48245 notifications: add missing types

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/AssignmentConversionServiceImpl.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- kernel/api/src/main/java/org/sakaiproject/hibernate/CrudRepository.java
- kernel/api/src/main/java/org/sakaiproject/hibernate/HibernateCrudRepository.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48249
> SAK-48249 Assignment assigning a persistent set to another entity

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48252
[SAK-48252]: https://sakaiproject.atlassian.net/browse/SAK-48252?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAK-48252 -Portal SiteNav: focus the current tool on load

- lessonbuilder/tool/src/webapp/js/show-page.js
- lessonbuilder/tool/src/webapp/templates/AssignmentPicker.html
- lessonbuilder/tool/src/webapp/templates/Checklist.html
- lessonbuilder/tool/src/webapp/templates/ForumPicker.html
- lessonbuilder/tool/src/webapp/templates/PagePicker.html
- lessonbuilder/tool/src/webapp/templates/PeerEvalStats.html
- lessonbuilder/tool/src/webapp/templates/QuizPicker.html
- lessonbuilder/tool/src/webapp/templates/Reorder.html
- lessonbuilder/tool/src/webapp/templates/ShowItem.html
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
https://sakaiproject.atlassian.net/browse/SAK-48178
> SAK-48178 lessons: trinity : fix section/column break weirdness

- library/src/skins/default/src/sass/modules/tool/authz/_authz.scss
- webcomponents/tool/src/main/frontend/js/sakai-permissions.js
https://sakaiproject.atlassian.net/browse/SAK-48258
Also, replaced jquery code with vanillajs. JQuery was masking problems with the markup, missing elements.
> SAK-48258 permissions: changed <a> to <button>

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47546
[SAK-47546]: https://sakaiproject.atlassian.net/browse/SAK-47546?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAK-47546 assignments: draft site import, remove gradebook association

- webcomponents/tool/src/main/frontend/js/calendar/calendar-styles.js
https://sakaiproject.atlassian.net/browse/SAK-48271
> SAK-48271 -Account Menu > My Calendar: Calendar is poorly formatted On Safari

- webcomponents/tool/src/main/frontend/js/calendar/calendar-styles.js
- webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar.js
https://sakaiproject.atlassian.net/browse/SAK-48269
> SAK-4269 -Account Menu > My Calendar: number of days display is erroneous

- library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/webapp/jsf/author/createAssessment_title.jsp
https://sakaiproject.atlassian.net/browse/SAK-48250
Before:
After:
> SAK-48250 Samigo change to a vertical layout for the Add Assessment

- chat/chat-tool/tool/src/webapp/js/chatscript.js
- chat/chat-tool/tool/src/webapp/jsp/room.jsp
- chat/chat-tool/tool/src/webapp/jsp/roomMonitor.jspf
- library/src/skins/default/src/sass/modules/tool/chat/_chat.scss
https://sakaiproject.atlassian.net/browse/SAK-48256
> SAK-48256 Chat update to bootstrap 5

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemFeedbackIfc.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/print/preview_item/CalculatedQuestion.jsp
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemFeedback.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemFeedback.java
- samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoAssessmentHandler.java
- samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoPoolHandler.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
- samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/facade/ItemHashUtilTest.java
https://sakaiproject.atlassian.net/browse/S2U-12
This is paired with https://github.com/sakaiproject/sakai-reference/pull/186
> S2U-12 5.1.1.8 Improving i18n and feedback on calculated questions

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/bundle/sitenav_ca.properties
- portal/portal-impl/impl/src/bundle/sitenav_es.properties
- portal/portal-impl/impl/src/bundle/sitenav_eu.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
> S2U-44 5.2.8.2 Portal display the user's role of the current site

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
- rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-48291
> SAK-48291 Rubrics association query was using the wrong entity field for rubricId

- webcomponents/tool/src/main/frontend/js/calendar/calendar-styles.js
https://sakaiproject.atlassian.net/browse/SAK-48272
> SAK-48272 Account Menu > My Calendar: Calendar navigation do not appear as links (CSS issue)

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-customize.vm
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/views/banner_form.hbs
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/views/popup_form.hbs
https://sakaiproject.atlassian.net/browse/SAK-48265
And I fixed a typo in the 'announcement tool'.
> SAK-48265 Trinity Portal PA System: create pop up & create banner screens do not obey dark theme

- library/src/skins/default/src/sass/base/_icons.scss
https://sakaiproject.atlassian.net/browse/SAK-48296
> SAK-48296 Trinity Portal: Incorrect icon for Assignments on the navigation

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- webcomponents/tool/src/main/frontend/js/sakai-search.js
https://sakaiproject.atlassian.net/browse/SAK-48289
Removed the pager. The sidebar approach scrolls.
> SAK-48289 search: fix some unclosed tag issues

- webcomponents/bundle/src/main/bundle/forums.properties
- webcomponents/tool/src/main/frontend/js/widgets/sakai-announcements-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-calendar-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-dashboard-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-forums-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-grades-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-status-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-tasks-widget.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-panel.js
- webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-picker.js
https://sakaiproject.atlassian.net/browse/SAK-48312
> SAK-48312 dashboards: Fixed some markup issues and forums widget

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/job/SeedSitesAndUsersJob.java
https://sakaiproject.atlassian.net/browse/SAK-48313
> SAK-48313 SeedSitesAndUsers job adjust the amount of content that is created by default

- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/webapp/js/spinner.js
https://sakaiproject.atlassian.net/browse/SAK-48262
Before:
After:
> SAK-48262 Portal spinner.js is not working properly

- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-48315
> SAK-48315 Adding some disableControlsAndSpin on Tests & Quizzes

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48318
> SAK-48318 Rubrics excessive logging from method RubricsServiceImpl.decorateRubricBean

- library/src/skins/default/src/sass/modules/tool/sitemanage/_sitemanage.scss
- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-import.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importMigrate.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importSelection.vm
https://sakaiproject.atlassian.net/browse/SAK-48279
> SAK-48279 siteimport: reorder options and improve descriptions

- library/src/webapp/bundled-js/sakai.morpheus.reorderer.js
https://sakaiproject.atlassian.net/browse/SAK-48288
> SAK-48288 Not able to use drag and drop functionality when reordering in Resources & Announcements

- admin-tools/src/java/org/sakaiproject/user/tool/UsersAction.java
Jira: [SAK-48251](https://sakaiproject.atlassian.net/browse/SAK-48251)
Issue preventing users -imported with a password containing leading or trailing spaces- to log in.
[SAK-48251]: https://sakaiproject.atlassian.net/browse/SAK-48251?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAK-48251 Users: issue with passwords surrounded by spaces when importing users from file

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://sakaiproject.atlassian.net/browse/SAK-48334
> SAK-48334 assignments: fix groups multiselect

- library/src/webapp/js/portal/portal.login.password.js
https://sakaiproject.atlassian.net/browse/SAK-48299
> Portal: Edge console errors on login - Uncaught TypeError: event.getModifierState is not a function

- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://sakaiproject.atlassian.net/browse/SAK-48322
> SAK-48322 Site Info: Manage Groups page does not display membership or size fields

- admin-tools/src/webapp/vm/archive/chef_archive.vm
https://sakaiproject.atlassian.net/browse/SAK-48355
> SAK-48355 Site Archive: B-5 update

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Message is sent even after removing scheduling date
https://sakaiproject.atlassian.net/browse/SAK-48329
> SAK-48329 Message is sent even after removing scheduling date

- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/fragments/common.html
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/modules.html
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/search.html
https://sakaiproject.atlassian.net/browse/SAK-48352
> SAK-48352 Message Bundle Manager: Bootstrap UI Issues

- msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
- roster2/tool/src/handlebars/enrollment_status.handlebars
- roster2/tool/src/handlebars/members_cards.handlebars
https://sakaiproject.atlassian.net/browse/SAK-48356
> SAK-48356 Roster & Messages: B-5 update

- site/term-manager/tool/src/java/org/sakaiproject/acadtermmanage/tool/pages/SemesterPage.html
https://sakaiproject.atlassian.net/browse/SAK-48354
> SAK-48354 Academic Term Manager: UI layout is out of place

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkGradePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-bulk-edit.js
- gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
- gradebookng/tool/src/webapp/scripts/gradebook-update-ungraded.js
- library/src/skins/default/src/sass/base/_extendables.scss
- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
- webcomponents/tool/src/main/frontend/js/sakai-submission-messager.js
https://sakaiproject.atlassian.net/browse/SAK-48359
> SAK-48359 Gradebook: B-5 update

- signup/tool/src/webapp/js/signupScript.js
https://sakaiproject.atlassian.net/browse/SAK-47270
> SAK-47270 SignUp begins/ends dates always appears in english

- assignment/api/src/resources/assignment.properties
- assignment/api/src/resources/assignment_ca.properties
- assignment/api/src/resources/assignment_es.properties
- assignment/api/src/resources/assignment_eu.properties
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
that have already been evaluated
> S2U-31 5.1.4.2 Assignments: Grades in the main view of assignments 

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/evolvers/SakaiFCKTextEvolver.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/QuestionGradingPaneProducer.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
- lessonbuilder/tool/src/webapp/js/show-page.js
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- lessonbuilder/tool/src/webapp/templates/sakai-FCKEditor.html
- library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Need special jqueryUI handling because of stacking (z-index) issues
> SAK-48235 Lessons use ckeditor for question editing

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/main/webapp/WEB-INF/components.xml
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-48429
> SAK-48429 Conversations: support site import

- library/src/webapp/js/portal/portal.sidebar.sites.js
https://sakaiproject.atlassian.net/browse/SAK-48365
> SAK-48365 Portal: Expand/collapse icon not displaying correct action after user clicks on a tool in the navigation

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
I missed the negation at #11245
> S2U-21 Fix whitespaces being removed from assessment title again

- README.md
https://confluence.sakaiproject.org/display/BOOT/Install+Tomcat+9 404
fyi:
https://sakaiproject.atlassian.net/wiki/spaces/DOC/pages/17310646930/Sakai+21+Install+Guide+Source
> NOJIRA  Update README.md

- kernel/kernel-test/pom.xml
- kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTestConfiguration.java
- kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTests.java
- portal/portal-api/api/pom.xml
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/model/PinnedSite.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/model/RecentSite.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/repository/PinnedSiteRepository.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/repository/RecentSiteRepository.java
- portal/portal-impl/impl/pom.xml
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
- portal/portal-service-impl/impl/pom.xml
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/SiteNeighbourhoodServiceImpl.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/PinnedSiteRepositoryImpl.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/RecentSiteRepositoryImpl.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalTestConfiguration.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/SiteNeighbourhoodServiceImplTest.java
- portal/portal-service-impl/impl/src/test/resources/hibernate.properties
- portal/portal-service-impl/impl/src/test/resources/log4j.properties
- portal/portal-service-impl/impl/src/webapp/WEB-INF/components.xml
https://sakaiproject.atlassian.net/browse/SAK-48444
> SAK-48444 portal: update pinned when user removed

- library/src/webapp/bundled-js/sakai.morpheus.reorderer.js
https://sakaiproject.atlassian.net/browse/SAK-48397
> SAK-48397 Samigo: Uncaught TypeError: (...).sortable is not a function

- kernel/api/src/main/java/org/sakaiproject/util/ServerCookie.java
- kernel/api/src/test/java/org/sakaiproject/util/ServerCookieTest.java
https://sakaiproject.atlassian.net/browse/SAK-48484
> SAK-48484 Kernel SameSite header and cookie not secure

- library/src/webapp/js/BreakpointManager.js
- library/src/webapp/js/portal/portal.login.mobile.js
- library/src/webapp/js/portal/portal.login.password.js
- library/src/webapp/js/portal/portal.serverinfo.js
- library/src/webapp/js/portal/portal.sidebar.collapse.js
- library/src/webapp/js/portal/portal.sidebar.sites.js
https://sakaiproject.atlassian.net/browse/SAK-48487
> SAK-48487 portal: remove hash symbol in portal js methods

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsStatisticsPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-settings.js
- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- library/src/skins/default/src/sass/themes/_dark.scss
https://sakaiproject.atlassian.net/browse/SAK-48485
> SAK-48485 GB > Settings Accordion Update to B-5

- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-48419
> SAK-48419 Upgrading mXparser to 5.2.1

- common/common-composite-component/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonManagerImpl.java
- common/common-composite-component/src/java/org/sakaiproject/component/common/type/TypeManagerImpl.java
- common/common-composite-component/src/webapp/WEB-INF/components.xml
This seemed to be a weird silent failure calling the IdManager cover. I'm not sure what this was related to. Nothing was being inserted into the `CMN_TYPE_T `table and there was an error in the logs from hibernate.
This was used twice in this package so I fixed both of these. 
Also since cleaned up some of the other setters when I added this one
> SAK-48205 - Database error in the logs for Forums related to CMN_TYPE_T_TUPLE_I

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
https://sakaiproject.atlassian.net/browse/SAK-48334
> SAK-48334 announcements: fix group multiselect on edit screen

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://sakaiproject.atlassian.net/browse/SAK-48342
> SAK-48342 assignments: fix multiselect on edit screen

- master/pom.xml
Resolution is to not use the sakai-release profile, so just removing it.
> INFRSTR-366 - Problem deploying snapshot artifacts

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/samlite/QuestionPoolListener.java
https://sakaiproject.atlassian.net/browse/SAK-46417
> SAK-46417 Samigo Question pool loading published facade item

- library/src/morpheus-master/sass/base/_extendables.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
- samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
As @mpellicer pointed out on https://sakaiproject.atlassian.net/browse/S2U-21 after additional following issues were found:
1. There was a null pointer when publishing the assessment from the assessment list -> Actions -> Edit -> Publish
2. More info in the settings about the SEB config mode would be helpful
3. Buttons in student assessment view are not aligned 
Those issues are addressed by this PR.
> S2U-21 SEB: Improve settings info, fix nullpointer and align buttons

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
SAMIGO: When creating an assessment we should add events on the calendar only for the groups which instructor belongs to
https://sakaiproject.atlassian.net/browse/SAK-48494
> SAK-48494 SAMIGO: When creating an assessment we should add events on the calendar only for the groups which instructor belongs to

- roster2/tool/src/webapp/js/roster.js
This fixes an issue when loading more members that have special needs. When more members are loaded, the user cannot access previous and future members because the array only has the most recent members.
> SAK-47992 Roster Keep the member array updated

- config/localization/bundles/pom.xml
- library/src/skins/default/src/sass/modules/tool/navigation/_base.scss
- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48504
> SAK-48504 Portal:  Uncaught SyntaxError: redeclaration of const roleSwitchButton

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
When an instructor published an assessment that has an uploaded SEB configuration it will create a public resource which needs to be allowed.
> S2U-21 SEB: Fix permission exception when instructor published assessment

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/siteStatus-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-48107
> SAK-48107 portal: add publish banner back in

- config/localization/bundles/pom.xml
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
https://sakaiproject.atlassian.net/browse/SAK-48524
> SAK-48524 portal: added home tool title to sitenav properties

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
- library/src/skins/default/src/sass/base/_icons.scss
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-48539
> SAK-48539 T&Q: Unable to select groups

- samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
CLONE - T&Q: Do not allow changing a question type after quiz has been published and has submissions
https://sakaiproject.atlassian.net/browse/SAK-48369
> SAK-48369 CLONE - T&Q: Do not allow changing a question type after quiz has been published and has submissions

- samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
https://sakaiproject.atlassian.net/browse/SAK-48537
> SAK-48537 T&Q: Print view is completely broken

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AjaxBootstrapTabbedPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-grades.css
https://sakaiproject.atlassian.net/browse/SAK-48421
> SAK-48421 gradebook: fix summary modal dialog

- library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
- samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
- samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp
https://sakaiproject.atlassian.net/browse/SAK-48401
> SAK-48401 Samigo: class="hidden spanValue" is not hiding the date strings

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
Adds submission type to the LessonsEntity to be checked when looking for item completion. Non-electronic assignments are "complete" immediately but still comply with the minimum grade rules.
> SAK-48009 Lessons Non-electronic Assignments should unlock

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48465
> SAK-48465 assignments: only complete task if submission completed

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48404
> SAK-48404 grader: updated points from rubric correctly

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-48492
> SAK-48492 conversations: honour selected topic type

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-48406
> SAK-48406 assignments: fix classic grading rubric tab

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
https://sakaiproject.atlassian.net/browse/SAK-48411
> SAK-48411 rubrics: change sort key from class to data attributes

- library/src/skins/default/src/sass/modules/tool/signup/_signup.scss
- signup/tool/src/webapp/css/signupStyle.css
- signup/tool/src/webapp/js/signupScript.js
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
https://sakaiproject.atlassian.net/browse/SAK-48561
> SAK-48561 Singup Tool adds extra margin to sidebar

- library/src/webapp/js/portal/portal.init.js
https://sakaiproject.atlassian.net/browse/SAK-48510
> SAK-48510 Portal Search: Uncaught TypeError: e.target.querySelector(...)?.clear is not a function

- announcement/announcement-api/api/src/bundle/announcement.properties
- announcement/announcement-api/api/src/bundle/announcement_ca.properties
- announcement/announcement-api/api/src/bundle/announcement_es.properties
- announcement/announcement-api/api/src/bundle/announcement_eu.properties
- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
https://sakaiproject.atlassian.net/browse/S2U-37
> S2U-37 5.2.1.2 Announcements: Ability to highlight announcements

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://sakaiproject.atlassian.net/browse/S2U-12
> S2U-12 5.1.1.8 Tests & Quizzes: Improving i18n and feedback on calculated questions

- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-48516
> SAK-48516 Pagination links need to be fixed for b-5

- library/src/webapp/content/gateway/acknowledgements.html
https://sakaiproject.atlassian.net/browse/SAK-48192
> SAK-48192 Portal Gateway Acknowledgements sakai page

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
A screenshot, ProposedPopoverFix.png, of the proposed fix is attached to https://sakaiproject.atlassian.net/browse/SAK-48171.
> SAK-48171 - Gradebook: Cell popovers fail to display for new items

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48607
> SAK-48607 Rubrics during site import associations are linked to the rubric in the from site

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
**Note:** This jira depends on the fix for SAK-48588 to be implemented.
Refer to the screencast, GB-ProposedFixAndScope.mp4, that's attached to the jira. The proposed changes here is displayed in that screencast for an instance where the fix for SAK-48588 is also implemented.
> SAK-48605 Gradebook: Adjust size & location of header menu buttons

- lessonbuilder/tool/src/resources/messages.properties
- lessonbuilder/tool/src/resources/messages_es.properties
- lessonbuilder/tool/src/resources/messages_fr_FR.properties
- lessonbuilder/tool/src/webapp/js/announcements.js
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
Lessons: String "by" is hardcoded in a translation
https://sakaiproject.atlassian.net/browse/SAK-48612
> SAK-48612 Lessons: String by is hardcoded in a translation

- content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
https://sakaiproject.atlassian.net/browse/SAK-48372
> SAK-48372 Syllabus / Messages: cannot add a URL attachment OR select from Resources

- lessonbuilder/tool/src/resources/messages.properties
- lessonbuilder/tool/src/resources/messages_es.properties
- lessonbuilder/tool/src/resources/messages_fr_FR.properties
- lessonbuilder/tool/src/webapp/js/announcements.js
- lessonbuilder/tool/src/webapp/js/forum-summary.js
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
Lessons: String "by" is hardcoded in a forum translation
https://sakaiproject.atlassian.net/browse/SAK-48625
> SAK-48625 Lessons: String 'by' is hardcoded in a forum translation

- gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingPermissionServiceImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://sakaiproject.atlassian.net/browse/SAK-48615
> SAK-48615 gradebook: fix permissions checks for TAs

- webcomponents/tool/src/main/frontend/js/conversations/conversations-statistics.js
https://sakaiproject.atlassian.net/browse/SAK-48642
> SAK-48642 conversations: only request stats when url is ready

- feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
https://sakaiproject.atlassian.net/browse/SAK-48027
> SAK-48027 feedback: Allow students to see instructors in list

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentContentProducer.java
https://sakaiproject.atlassian.net/browse/SAK-48629
> SAK-48629 assignments: block reads on draft search results

- entitybroker/rest/src/java/org/sakaiproject/entitybroker/rest/EntityActionsManager.java
Add more logging to help determine that fonts are the problem
> SAK-48641 - Profile image doesn't work if font libraries aren't available on the system

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm
https://sakaiproject.atlassian.net/browse/SAK-48473
> SAK-48473 portal: switched mobile toolbar icon to bi-list

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48183
> SAK-48183 portal: clicking site takes you into first tool

- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/info.vm
https://sakaiproject.atlassian.net/browse/SAK-48663
Fixes announcements and rwiki. Also, fixes a hover issue with the site links in the tools navigation on the left.
> SAK-48663 css: add underline back to links in some tools

- microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/fragments/autoConfig.html
- microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
- CreateInvitation: Update user property only if is empty or null
- AutoConfig: More info in error list
> S2u-46 5.3.1: Fix

- microsoft-integration/admin-tool/pom.xml
- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/ThymeleafConfig.java
- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/GlobalController.java
- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/SiteSynchronizationController.java
- microsoft-integration/api/pom.xml
- microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/SakaiProxy.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
- Added user locale to request
- Clean pom.xml files
> s2u-46 5.3.1: i18n Fix

- gradebookng/impl/pom.xml
- kernel/kernel-test/pom.xml
- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-48670
> SAK-48670 kernel: don't deploy sakai-kernel-test to lib

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47941
> SAK-47941 grader: enable nav buttons when rubric closed

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
This PR is intended to remedy the following PR that I closed:
https://github.com/sakaiproject/sakai/pull/11364/files
> SAK-48650 Trinity: Display problem for site descriptions

- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/grader/_base.scss
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47951
> SAK-47951 grader: improve on smaller screens

- microsoft-integration/admin-tool/src/main/resources/Messages.properties
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java
- email case insensitive
- refactor in synchronization process
- i18n fix (english)
> S2u-46: Fixes

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48675
> SAK-48675 Rubrics on import association config should be copied

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-update-ungraded.js
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48376
[Related HTML File](https://github.com/sakaiproject/sakai/blob/f6c85e9afcf7ad19aec487189d0a04d0acbd15ba/gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html#L66)
```code
<button type="button" class="button_color gb-update-ungraded-continue active" data-dismiss="modal"><wicket:message key="label.updateungradeditems.confirmation.continue" /></button>
```
> SAK-48376: Please add spinner and disable submit button on "Set Score Confirmation" dialog box

- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-48720
> SAK-48720 portal: don't add "Site Unavailable" to recents

- library/src/webapp/content/gateway/acknowledgements.html
- library/src/webapp/content/gateway/features.html
- library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-48191
> SAK-48191 Gateway: Features Sakai Page B-5 update

- library/src/webapp/content/gateway/about.html
https://sakaiproject.atlassian.net/browse/SAK-48190
> SAK-48190 Gateway: About Sakai Page B-5 update

- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
Check site.upd.grp.mbrshp permission at group level
> SAK-48636: Check site.upd.grp.mbrshp permission at group level

- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/AutoConfigController.java
- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/MainController.java
- microsoft-integration/admin-tool/src/main/java/org/sakaiproject/microsoft/controller/auxiliar/AutoConfigSessionBean.java
- microsoft-integration/admin-tool/src/main/webapp/WEB-INF/templates/index.html
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
- microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java
- Refactor: Found a way to get returned ID when creating a Microsoft Team. Async Team creation process is no longer needed.
- Fixed minor bug with case sensitive searches
- Excluded Lesson auto-generated groups in auto-configuration process.
> s2u-46: Updates

- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
- samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp
https://sakaiproject.atlassian.net/browse/SAK-48735
The Bootstrap library was loading twice on the page so I got rid of it.
I also fixed https://sakaiproject.atlassian.net/browse/SAK-48694
> SAK-48735 Tests & Quizzes: Grade by student in dark mode flips to light

- library/src/skins/default/src/sass/base/_defaults.scss
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-48755
> SAK-48755 rubrics: move student comment to bs5 popover

- library/src/webapp/content/gateway/acknowledgements.html
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48743
Add support for screen readers to the links in Gateway Page.
> SAK-48743: Gateway > Acknowledgement: Explore links are not accessible

- samigo/samigo-app/src/webapp/css/tool_sam.css
https://sakaiproject.atlassian.net/browse/SAK-48681
This PR should be merged on 24, 23, 22, 21 and 20.
Only fix the width of the columns
22
23
> SAK-48681 Tests & Quizzes student scores Statistics tab not displaying colored bars for questions

- samigo/samigo-app/src/webapp/css/print/print.css
- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-48772
According to bootrstrap 5
https://getbootstrap.com/docs/5.0/components/progress/
> SAK-48772 Samigo student scores statistics tab colored bars (trinity problem)

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
Refer to the screencast, SAK-48674-proposed-fix.mp4, attached to the jira: https://sakaiproject.atlassian.net/browse/SAK-48674.
> SAK-48674 Trinity: Sites modal jumps to top when clicked

- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/S2U-31
On a group submission when override a student grade but the main group grade has not been modified.
> S2U-31 Assignments: Grades in the main view of assignments that have already been evaluated

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/util/PrivateMessagesToolHelper.java
- msgcntr/messageforums-app/src/test/org/sakaiproject/msgcntr/tool/PrivateMessagesToolHelperTest.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48664
> SAK-48664: Messages: Blind Carbon Copy (BCC) feature shouldn't show undisclosed recipients 

- lessonbuilder/tool/src/webapp/templates/Checklist.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
https://sakaiproject.atlassian.net/browse/SAK-48722
> SAK-48722 Portal: i circle unresponsive in Site Info>Manage Groups>Create New Group

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47973
> SAK-47973 Assignments instructor comments not persisting when using next and previous buttons

- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/XSLTEntityHandler.java
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/XSLTTransform.java
- rwiki/rwiki-impl/impl/src/webapp/WEB-INF/coreServiceComponents.xml
https://sakaiproject.atlassian.net/browse/SAK-48707
xml serializer factory attempting to load serializers (FOP2PDFSerializer) from the wrong class loader
> SAK-48707 rWiki pdf generation causes Exception during serialization

- library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/ifc/GradebookServiceHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
- samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/ItemCancellationTest.java
Thanks to great QA work from @jesusmmp some issues related to cancelling questions in samigo were identified. This PR should fix all of them. Additionally I disabled the input's for score values of cancelled questions.
https://sakaiproject.atlassian.net/browse/S2U-14
> S2U-14 Samigo: Several improvements related to question cancellation 

- samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
https://sakaiproject.atlassian.net/browse/S2U-10
Fixing when clicking Solution if the calculated question has an attachment.
> S2U-10 5.1.1.6 Tests & Quizzes: Ability to preview calculated questions in question pools

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgFolderAdd.jsp
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48572
> SAK-48572: Trinity Portal / Messages: Label; not in bold text

- library/src/webapp/js/headscripts.js
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
https://sakaiproject.atlassian.net/browse/SAK-48257
> SAK-48257 Trinity Portal / PA System: Banners do not appear for some tools

- library/src/skins/default/src/sass/modules/more-sites/_more-sites.scss
- library/src/webapp/js/portal/portal.all.sites.js
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
https://sakaiproject.atlassian.net/browse/SAK-48802
> SAK-48802 portal: move more sites into the sidebar

- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48549
B-5 update based on https://github.com/sakaiproject/sakai/pull/11206/files
> SAK-48549: Trinity Portal, Messages tool: checkbox overwriting text & labels not in bold on multiple pages

- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/IndexMacro.java
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RenderServiceImpl.java
- rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/SaveCommand.java
S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix
> S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages - fix

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-grades.css
https://sakaiproject.atlassian.net/browse/SAK-48488
> SAK-48488 Gradebook>Instructor view: Group by category is not working as expected

- samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48403
See screenshot.
> SAK-48403: Tests & Quizzes: Reformat the view/search options on the Total Scores page to be more compact

- portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-48809
> SAK-48809 portal: autopin site newly added side members

- webapi/src/main/java/org/sakaiproject/webapi/beans/RecurrenceRuleRestBean.java
@adrianfish in some cases this getUntil() was null and there was a hidden exception here. I'm not sure what this should be returning as a default so just left it at 0. It could be -1?
> SAK-48596 - Calendar: Creating reoccurring event console error: Unexpected end of JSON input

- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
A select for assignments shouln't be visible if there are no assignment in the list
https://sakaiproject.atlassian.net/browse/SAK-48725
> SAK-48725 A select for assignments shouln't be visible if there are no assignment in the list

- webcomponents/bundle/src/main/bundle/sui-notifications.properties
- webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48709
See the screenshot.
> SAK-48709: Academic Alert-Assignments: Only the assignment name is given for when an assignment is published and graded

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
In the case of randomly drawn questions where the user was never presented a question the histogram bean should record 0 correct/incorrect for that question.
https://sakaiproject.atlassian.net/browse/SAK-48786
> SAK-48786 Samigo statistics not every question has an answer

- library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-48837
> SAK-48837 Rubrics js selector failure for student comment popovers

- lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-48839
> SAK-48839 Lessons set default cc export version to 1.3

- lessonbuilder/tool/src/webapp/js/show-page.js
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-48838
> SAK-48838 lessons: fix some issues with cc import

- library/src/morpheus-master/sass/base/_extendables.scss
- library/src/morpheus-master/sass/modules/_b5-polyfill.scss
- library/src/morpheus-master/sass/tool.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetTotalScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionNavListener.java
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/submissionNav.jsp
https://sakaiproject.atlassian.net/browse/S2U-15
> S2U-15 Tests & Quizzes: Improve navigation when grading

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48851
> SAK-48851 Rubrics during import deal properly with multiple active associations

- calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/calendar.jsp
- library/src/skins/default/src/sass/modules/tool/calendar/_calendarSynoptic.scss
- library/src/skins/default/src/sass/tool.scss
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48750
Use ```<div class="tableContainer">``` to wrap the table to adjust the margin.
> SAK-48750: Overview / calendar synoptic view display issues

- roster2/tool/src/handlebars/members_cards.handlebars
- roster2/tool/src/handlebars/members_photogrid.handlebars
- roster2/tool/src/handlebars/members_table.handlebars
- roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-48855
> SAK-48855 roster: use IntersectionObserver for scroll detection

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://sakaiproject.atlassian.net/browse/SAK-48451
> SAK-48451 rubrics: stop edit popover being hidden by sitenav

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
Fixes IdUnsused Exception, if method removeCollection is called on collection, which has still members inside.
> SAK-48733: remove collection with members recursive

- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Refer to the screencast, SAK-48515-ProposedFixDemo.mp4, which is attached to the jira: https://sakaiproject.atlassian.net/browse/SAK-48515
> SAK-48515 Lessons: buttons at top of page need different alignment

- lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-48848
> SAK-48848 lessons: fix picker for existing pages

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
https://sakaiproject.atlassian.net/browse/S2U-14
> S2U-14 Disable item cancellation for assessments with random question from question pool

- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
- user/user-tool-prefs/tool/src/webapp/WEB-INF/faces-config.xml
- user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp
I added @hornersa to the project to be able to assign for review because of #11389
> Trinity Preferences > Sites tab fails to load page

- signup/tool/src/webapp/css/signupStyle.css
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
- signup/tool/src/webapp/signup/updatePermission.jsp
Just removed all these hard-coded background values, looks a lot better on dark mode and the same on light mode.
> SAK-46525 - Dark mode / signup color contrast issues

- site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-45203
> SAK-45203 DateManager update due date in gradebook for Assignments and Samigo

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/api/src/resources/assignment.properties
- assignment/api/src/resources/assignment_es.properties
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Asociate to [SAK-48856: Error in assignment list view](https://sakaiproject.atlassian.net/browse/SAK-48856)
> SAK-48856: Error in assignment list view

- library/src/skins/default/src/sass/base/_icons.scss
- library/src/skins/default/src/sass/tool.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverImageMapQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatching.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMatching.jsp
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-preview-button.js
https://sakaiproject.atlassian.net/browse/SAK-48717
**Incorporated++**
- https://sakaiproject.atlassian.net/browse/SAK-48830
- https://sakaiproject.atlassian.net/browse/SAK-48841
- Update badge class to b-5
- Fixed some hover issues
> SAK-48717 T&Q: Student feedback needs better formatting + some other b-5 update

- library/src/skins/default/src/sass/base/_defaults.scss
- library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
- library/src/skins/default/src/sass/modules/tool/siteinfo/_siteinfo.scss
- site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
- site-manage/pageorder/tool/src/webapp/content/css/PageList.css
- site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
- site-manage/site-manage-link-helper/src/webapp/vm/sakai_link.vm
- site-manage/site-manage-participant-helper/src/webapp/content/templates/Add.html
- site-manage/site-manage-participant-helper/src/webapp/content/templates/SameRole.html
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-editToolGroupFeatures.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importMigrate.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importMtrlMaster.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importSelection.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageOverview.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm
https://sakaiproject.atlassian.net/browse/SAK-48893
**Incorporated++**
- https://sakaiproject.atlassian.net/browse/SAK-48883 (Add participants / text size incorrect)
- https://sakaiproject.atlassian.net/browse/SAK-48727 (Trinity: Dark Theme not obeyed)
- https://sakaiproject.atlassian.net/browse/SAK-48737 (Trinity: Site Info > Manage Tools, "General" not collapsed properly)
- Fix hover background-color on dropdown-items
> SAK-48893 Fixing Site Info UI to Align with 22.x design standards (B-5)

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48884
> SAK-48884 update submission grade with rubric total points

- profile2/api/src/java/org/sakaiproject/profile2/logic/SakaiProxy.java
- profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java
- profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
> SAK-48657 Profile: Restrict photos to site members only

- library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://sakaiproject.atlassian.net/browse/SAK-48451
> SAK-48451 fix criterion edit popover

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-48873
> SAK-48873 Fix upload zip content in lessons

- assignment/api/src/java/org/sakaiproject/assignment/api/AddAssignmentUserNotificationHandler.java
> SAK-44623: Notifications: assignments's open date is in future

- samigo/samigo-app/src/webapp/jsf/evaluation/confirmRetake.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Double clicking "Allow Retake and Go to Settings" creates duplicate records in the DB
https://sakaiproject.atlassian.net/browse/SAK-48878
> SAK-48878 Samigo > double clicking "Allow Retake and Go to Settings" creates duplicate records in the DB

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
https://sakaiproject.atlassian.net/browse/S2U-11
Adding global variables to the calculation list.
> S2U-11 5.1.1.7 Tests & Quizzes: Global variables in calculated questions

- kernel/api/src/main/java/org/sakaiproject/site/api/Site.java
- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- library/src/morpheus-master/sass/modules/_b5-polyfill.scss
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties
- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/DiscussionForum.java
- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/DiscussionTopic.java
- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java
- msgcntr/messageforums-app/pom.xml
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumPublishToFaqBean.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgPublishToFaqEdit.jsp
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/DiscussionForumImpl.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/DiscussionTopicImpl.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/OpenForum.hbm.xml
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/Topic.hbm.xml
https://sakaiproject.atlassian.net/browse/SAK-35033
Conversion scripts: https://github.com/sakaiproject/sakai-reference/pull/204
> S2U-27 Messages: Convert a private message into a forum message in the FAQ forum

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48903
> SAK-48903 Fixed site nav dropdowns for special site ids

- admin-bulk-user-membership/tool/src/main/resources/Messages_ca.properties
- admin-bulk-user-membership/tool/src/main/resources/Messages_es.properties
- admin-bulk-user-membership/tool/src/main/resources/Messages_eu.properties
Same title than in the tools properties
> S2U-43 5.2.8.1 Admin: Ability to enrol, unenrol and disable multiple users in multiple sites.

- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/jsf/HideDivisionRenderer.java
- user/user-tool-prefs/tool/src/webapp/prefs/noti.jsp
https://sakaiproject.atlassian.net/browse/SAK-48351
> SAK-48351 Preferences: Notification options are not displaying on the page

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48899
Remove "Undisclosed-Recipients" before sending the email.
> SAK-48899 Messages: Concealing "Undisclosed-Recipients" in emails with Blind Carbon Copy (BCC) feature

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
- gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/repository/AssignmentGradeRecordRepositoryImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-47832
It appears to be a typo issue. Additionally, I have added a log statement because it was not printing anything even though the error was being caught.
> SAK-47832 Assignments: Grades not passed to the gradebook if released from Submissions page

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-48844
> SAK-48844 grader: hide grading button for lti gradings

- library/src/skins/default/src/sass/modules/tool/navigation/_base.scss
- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- library/src/webapp/js/portal/portal.sidebar.collapse.js
- library/src/webapp/js/portal/portal.sidebar.sites.js
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/bundle/sitenav_ca.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-48804
> SAK-48804 more community suggested portal fixes for 23

- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48618
> SAK-48618 Tests & Quizzes: No rubric when grading by question

- portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalConstants.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48908
> SAK-48908 Expand current site's tools for most page loads

- library/pom.xml
- library/src/morpheus-master/sass/modules/editor/_base.scss
- library/src/webapp/js/headscripts.js
- master/pom.xml
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
> SAK-48937 CKEditor upgrade from 4.16.1 to 4.21.0

- roster2/tool/src/webapp/css/print.css
https://sakaiproject.atlassian.net/browse/SAK-48349
> SAK-48349 Roster: Print views need to be fixed

- library/src/webapp/js/portal/portal.sidebar.sites.js
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48909
> SAK-48909 Filter pinned sites from Recent sites display

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/S2U-32
> S2U-32 5.1.4.3 Assignments: support for tags

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48892
> SAK-48892 Prevent accidental hiding of private notes link

- help/help-component/src/bundle/TutorialMessages.properties
https://sakaiproject.atlassian.net/browse/SAK-48950
> SAK-48950 Portal: Update Tutorial Pop-up Content Based on Wilma's Suggestions

- roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-48855
> SAK-48855 fixed roster scroll when searching

- library/src/skins/default/src/sass/modules/tool/assignments/_assignments.scss
- library/src/skins/default/src/sass/themes/_dark.scss
- library/src/skins/default/src/sass/themes/_light.scss
> SAK-48325 Assignments: Progress status bar theme needs to be fixed

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/test/org/sakaiproject/assignment/tool/SessionStateFake.java
- kernel/api/src/main/java/org/sakaiproject/event/api/SessionState.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/UsageSessionServiceAdaptor.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48897
> SAK-48897 Assignments: If no students in site, and instructor clicks Grade, submissions page has "Found null participant(s)."

- webcomponents/tool/src/main/frontend/js/sakai-pageable-element.js
- webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48872
Make two changes:
1. Update the data for current page to contain only visible data during re-paging. And update the total data count accordingly. (See the screen recording)
2. Jump to the first page after changing the filter.
https://github.com/sakaiproject/sakai/assets/102482288/ed590bed-ae32-4b9a-8787-0fe9e6d64ba8
> SAK-48872 Dashboard > Tasks: Re-paging required after deleting a task

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48964
> SAK-48964 Add submitter's name to top of grading flyout

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48182
> SAK-48182 Discussions remove contextId from grading query params

- roster2/tool/src/handlebars/overview.handlebars
- roster2/tool/src/webapp/css/print.css
https://sakaiproject.atlassian.net/browse/SAK-48965
**Incorporated++**
https://sakaiproject.atlassian.net/browse/SAK-48349
> Roster each print version has extra blank pages added at the end

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48973
**To make it work across all major browsers, I had to add 5 pixels extra margin  `.sakai-sitesAndToolsNav`**
> SAK-48973 fix double scrollbar issue in portal's site nav area

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
https://sakaiproject.atlassian.net/browse/S2U-29
When answering from email an error is generated:
```
at [org.sakaiproject.component.app](http://org.sakaiproject.component.app/).messageforums.ui.PrivateMessageManagerImpl.getContextId([PrivateMessageManagerImpl.java:2202](http://privatemessagemanagerimpl.java:2202/)) ~[?:?]
at [org.sakaiproject.component.app](http://org.sakaiproject.component.app/).messageforums.ui.PrivateMessageManagerImpl.sendConfirmationEmail([PrivateMessageManagerImpl.java:1620](http://privatemessagemanagerimpl.java:1620/)) ~[?:?]
at [org.sakaiproject.component.app](http://org.sakaiproject.component.app/).messageforums.ui.PrivateMessageManagerImpl.markMessageAsReadForUser([PrivateMessageManagerImpl.java:1603](http://privatemessagemanagerimpl.java:1603/)) ~[?:?]
at …
```
> S2U-29 5.1.3.3 Private Messages: Request a read receipt feature

- help/help-component/src/bundle/TutorialMessages.properties
https://sakaiproject.atlassian.net/browse/SAK-48950
This is the second pr for the same JIRA, I forgot to add "&" in the last pr. Thanks.
> Portal: Update Tutorial Pop-up Content Based on Wilma's Suggestions

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48530
> SAK-48530 Rubrics - TAs and students see Rubrics on the navigation even though they have no permissions to access

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48979
> SAK-48979 Portal: the footer is gone

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DataTablesMessages_es.properties
https://sakaiproject.atlassian.net/browse/S2U-24
> S2U-24 5.1.1.20 Tests & Quizzes: Improve event log UI

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/AssessmentAccessControlIfc.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-48972
> SAK-48972 Samigo imported assesments releaseTo using old site

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48182
> SAK-48182 Discussions / unable to grade via Forums or Topics link

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48997
> SAK-48997 Grader. Use BasicText config for private and feedback editors

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
https://sakaiproject.atlassian.net/browse/SAK-49022
> SAK-49022 Portal: Notification content is not readable in dark mode

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48587
> SAK-48587 Rubric icon not displaying in Gradebook

- rubrics/api/src/main/bundle/rubrics.properties
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
https://sakaiproject.atlassian.net/browse/SAK-48580
> SAK-48580 Rubrics add drag to reorder info to aria labels

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-48544
> SAK-48544 - API - Instructor attachments should not be shown if the submission is not grade and published

- roster2/tool/src/handlebars/navbar.handlebars
- roster2/tool/src/webapp/js/card-game/card-game.js
- webapi/pom.xml
- webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
Only display students to learn in the that are in the same  group
https://sakaiproject.atlassian.net/browse/S2U-42
> S2U-42 Roster: Card Game - Make card game group aware

- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/authorSettings_attachment.jsp
- samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf
- samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings_attachment.jsp
For demos before and after the proposed improvement, refer to the screencasts attached to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49053).
> SAK-49053 Samigo settings view has typography issues

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/scheduler/PrivateMessageSchedulerServiceImpl.java
Private Messages: The 'Date Scheduled' of scheduled messages is not displayed.
https://sakaiproject.atlassian.net/browse/SAK-49043
> SAK-49043 msgcntr private messages display 'Date Scheduled' for scheduled messages

- library/src/webapp/js/sakai-message-broker.js
- webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
https://sakaiproject.atlassian.net/browse/SAK-49049
> SAK-49049 ui-notifications redecoration issue when clearing a notification

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48673
Throwing an exception seems to be unnecessary in this function.
> SAK-48673 Assignments IllegalArgumentException when assignment does not have an associated rubric

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-49040
> SAK-49040 sakai-grader fix class cast exception in gradable action

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
https://sakaiproject.atlassian.net/browse/SAK-49068
> SAK-49068 Portal: Home site disappearing when accessing tools in other sites

- roster2/bundle/src/bundle/card_game.properties
https://sakaiproject.atlassian.net/browse/S2U-42
> S2U-42 Fixed typos and changed neutral pronoun

- rwiki/rwiki-api/api/src/java/uk/ac/cam/caret/sakai/rwiki/service/api/RWikiSecurityService.java
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiSecurityServiceImpl.java
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
https://sakaiproject.atlassian.net/jira/software/c/projects/S2U/issues/S2U-39
> S2U-39 5.2.3.1 Wiki: Add group support to Wiki pages

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Jira: https://sakaiproject.atlassian.net/browse/S2U-27
Bug-description: Banner with message "The message was successfully published to FAQ" did not disappear after choosing site like "Compose Message" and then pressing "Cancel", causing the site to return to the previous page.
> S2U-27 5.1.3.1 Messages: fixed message-success-banner not disappearing

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-48014
Instructors should be able to view all sections/groups.
> SAK-48014 GB Instructor cannot set permissions for TA

- gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingCategoryType.java
https://sakaiproject.atlassian.net/browse/SAK-49067
> SAK-49067 Grading. Added extra zero ordinal to cat type enum

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49083
> SAK-49083 Rubrics: fix ConcurrentModificationException

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
JIRA: https://sakaiproject.atlassian.net/browse/SAK-47766
> SAK-47766 Gradebook hide the option to grade the rubric for items maintained externally

- tags/tags-impl/impl/src/java/org/sakaiproject/tags/impl/TagServiceImpl.java
Fix on tags.
Script:
https://github.com/sakaiproject/sakai-reference/pull/215
> S2U-28-32 Tags fixes

- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-49095
> SAK-49095 Samigo importing a question pool/assessment where zip file doesn’t contain the question attachments throws an NPE

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/msgHeader.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
- tags/tags-api/api/src/java/org/sakaiproject/tags/api/TagService.java
Jira: https://sakaiproject.atlassian.net/browse/S2U-28
> S2U-28 Private Messages: Fixed tag column in messages table

- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
Jira: https://sakaiproject.atlassian.net/browse/S2U-27
> S2U-27 5.1.3.1 Messages: Change button labels to be consistent with tools

- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49108
> SAK-49108 Site Info group member print button doesn't use param

- library/src/morpheus-master/sass/modules/_b5-polyfill.scss
- library/src/morpheus-master/sass/modules/tool/roster/_roster.scss
- roster2/tool/src/webapp/js/card-game/card-game.js
Jira: https://sakaiproject.atlassian.net/browse/S2U-42
> S2U-42 Card Game: Force 1:1 aspect ratio for image

- site-manage/site-manage-impl/impl/src/bundle/notifyAboutJoinableSet.xml
- site-manage/site-manage-impl/impl/src/bundle/notifyJoinableSetDayLeft.xml
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
Jira: https://sakaiproject.atlassian.net/browse/S2U-40
> S2U-40 Groups: Fix - User will receive email in wrong language and unicode issues

- library/src/skins/default/src/sass/base/_extendables.scss
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetTotalScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionNavListener.java
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/submissionNav.jsp
https://sakaiproject.atlassian.net/browse/S2U-15
> S2U-15 Tests & Quizzes: Improve navigation when grading - MASTER

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Private messages: Scheduled message saved in draft and later moved to scheduled is not sent.
https://sakaiproject.atlassian.net/browse/SAK-49042
> SAK-49042 Private messages: Scheduled message saved in draft and later moved to scheduled is not sent.

- library/src/skins/default/src/sass/modules/tool/messages/_messages.scss
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
Fixing classes on Private Messages
https://sakaiproject.atlassian.net/browse/SAK-49028
> SAK-49028 Fixing classes on Private Messages

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Private messages: Scheduled message saved in draft and later moved to scheduled is not sent-fix
https://sakaiproject.atlassian.net/browse/SAK-49042
> SAK-49042 Private messages: Scheduled message saved in draft and later moved to scheduled is not sent-fix

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
> S2U-21 Update EU bundle string

- library/src/skins/default/src/sass/modules/tool/_base.scss
- library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAssessmentQuestionPoints.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/part_attachment.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/qti/importAssessment.jsp
A demo of this proposed fix is attached to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49109).
> SAK-49109 T&Q: Images attached to parts display twice

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js
- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js
…te, so we have to set it back if we want the tool tip to display
> SAK-49091 Rubrics bootstrap popover automatically removes the title

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
- samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/ipAccessError.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/passwordAccessError.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
Fixes:
- [S2U-21-1](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
- [S2U-21-4](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
- [S2U-21-5](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
- [S2U-21-7](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
- [S2U-21-8](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
- [S2U-21-9](https://sakaiproject.atlassian.net/browse/S2U-21?focusedCommentId=210536)
> S2U-21 Tests & Quizzes: Several fixes for SEB

- library/src/webapp/js/portal/portal.sidebar.collapse.js
https://sakaiproject.atlassian.net/browse/SAK-49133
> SAK-49133 Portal collapsing or expanding sidebar generates a stacktrace

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
Refer to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49166).
> SAK-49166 Portal help button missing title for accessibility

- library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/edit.jsp
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
https://sakaiproject.atlassian.net/browse/SAK-49143
> SAK-49143 rWiki css broken and preview no longer works

- library/src/skins/default/src/sass/tool.scss
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-49178
> SAK-49178 Site Info student view throws an Uncaught TypeError: this._config is undefined, tooltip.js:465

- library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss
- rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages.properties
Also fixed a minor typo in the tooltip I noticed as I was working on this
> SAK-49218 - Rwiki: Tooltip displayed on hovering is unreadable on dark mode

- lessonbuilder/tool/src/webapp/templates/Checklist.html
- lessonbuilder/tool/src/webapp/templates/EditPage.html
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Refer to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49183). Attached to it are 12 screenshots: 6 screenshots are prefixed with “Issue” to depict issues within this jira’s scope. They also include numbers and sometimes letters for easier reference with respect to the General > Description of the jira. The other 6 screenshots are prefixed with “Fix” and the same numbering/lettering scheme. I recommend downloading the attached screenshots to your OS to more easily compare the before (Issue) and after (Fix) pics.
> SAK-49183 Lessons: Various UI display improvements

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-49213
> SAK-49213 conversations. Don't clear hide dates when showing a topic

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
> SAK-44874 Lessons avoid copying multiple copies of embedded assets if they exist in resources

- webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
https://sakaiproject.atlassian.net/browse/SAK-49211
> SAK-49211 conversations. Only return groups for current user

- conversations/api/src/main/resources/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
https://sakaiproject.atlassian.net/browse/SAK-48961
> SAK-48961 conversations. Validate due, lock and accept dates.

- conversations/api/src/main/resources/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
https://sakaiproject.atlassian.net/browse/SAK-48721
> SAK-48721 conversations. i18n edit tags link text

- library/src/skins/default/src/sass/modules/tool/conversations/_sakai-topic.scss
https://sakaiproject.atlassian.net/browse/SAK-47760
> SAK-47760 conversations. Improve dark mode contrast on good question

- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-48643
> SAK-48643 conversations. Allow TAs to view statistics

- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46072
> SAK-46072 conversations. Update new status as posts are viewed.

- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/TopicTransferBean.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-list.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-48497
> SAK-48497 conversations. Mark topic viewed if clicked an no posts

- admin-tools/src/java/org/sakaiproject/site/tool/AdminSitesAction.java
https://sakaiproject.atlassian.net/browse/SAK-46715
> SAK-46715 Site Alias: Edits are not saved, but a new alias is created instead

- content/content-tool/tool/src/webapp/vm/content/sakai_resources_properties.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_dropbox_multiple_folders_upload.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
- content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
https://sakaiproject.atlassian.net/browse/SAK-49135
> SAK-49135 Drop Box: Pink error banner displays when selecting Upload files to multiple Drop Box folders tab

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48974
**Please read the Jira**
> SAK-48974 Portal- Site title breaks to 3 lines

- master/pom.xml
@SedueRey maintains this webjar/library
> SAK-49222 increment version of ckeditor-html5-video

- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46719
> SAK-46719 conversations. Email on student reply to question

- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/PostTransferBean.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/repository/TopicStatusRepository.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/TopicStatusRepositoryImpl.java
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
- webcomponents/tool/src/main/frontend/js/conversations/conversations-statistics.js
- webcomponents/tool/src/main/frontend/js/conversations/options-menu.js
- webcomponents/tool/src/main/frontend/js/conversations/reactions-mixin.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment-editor.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-settings.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-tag-manager.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-list.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic-summary.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-47575
> SAK-47575 conversations. Don't count draft posts in unreads

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-48996
> SAK-48996 gradebook. Improve keyboard dropdown use

- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/PostTransferBean.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
https://sakaiproject.atlassian.net/browse/SAK-49245
> SAK-49245 conversations. Fix private replies

- calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js
https://sakaiproject.atlassian.net/browse/SAK-49243
> SAK-49243 Calendar FC events should have an end date later than start date

- conversations/api/src/main/resources/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
https://sakaiproject.atlassian.net/browse/SAK-49231
> SAK-49231 conversations. Add alert for duedate in past.

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js
- webcomponents/tool/src/main/frontend/js/grader/submission.js
https://sakaiproject.atlassian.net/browse/SAK-49242
> SAK-49242 grader. Show submitted text after accept until date

- master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-49145
> SAK-49145 Kernel ignite 2.15.0 update

- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-49248
> SAK-49248 conversations. Use _save, not save, in add topic.

- conversations/api/src/main/resources/conversations.properties
- webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js
https://sakaiproject.atlassian.net/browse/SAK-49247
> SAK-49247 conversations. Tidy up some due date validation

- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/api/src/main/java/org/sakaiproject/site/cover/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
- portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-49221
> SAK-49221 Portal Navigation: Deleted site is not removed from navigation

- library/pom.xml
- login/login-tool/tool/src/java/org/sakaiproject/login/tool/ContainerLogout.java
- login/login-tool/tool/src/java/org/sakaiproject/login/tool/SkinnableLogin.java
- samigo/samigo-api/src/java/org/sakaiproject/samigo/api/SamigoReferenceReckoner.java
https://sakaiproject.atlassian.net/browse/SAK-49252
- also a removes a System.out.println("6") from Samigo
- also some logging in portal
> SAK-49252 Library remove temporary build files

- webcomponents/tool/src/main/frontend/js/grades/sakai-grades.js
https://sakaiproject.atlassian.net/browse/SAK-49235
> SAK-49235 WC Grades addressed loading of i18n strings

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
- webapi/src/main/java/org/sakaiproject/webapi/controllers/CalendarController.java
- webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar.js
https://sakaiproject.atlassian.net/browse/SAK-48324
> SAK-48324 WC Calendar addressed loading i18n strings

- site-manage/datemanager/tool/src/main/resources/static/js/initDatePicker.js
This issue effects 24 and 23. This pull request should fix both.
> SAK-49191 DateManager shift dates is not available in expanded sections

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/HtmlPageFilter.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml
> SAK-46008 HTML files should set user's preferred theme in HTML class names

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
Private messages: Advanced search is not consistent with the current listing
https://sakaiproject.atlassian.net/browse/SAK-49041
> SAK-49041 Messages advanced search is not consistent with the current listing

- vuecomponents/tool/src/main/frontend/src/api/conditions-api.js
Fix comparison issue introduced when fixing codacy issues.
> S2U-35 Lessons: Fix non exact comparison

- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/PostTransferBean.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- library/src/skins/default/src/sass/modules/tool/conversations/_sakai-post.scss
- library/src/skins/default/src/sass/modules/tool/conversations/_sakai-topic.scss
- webcomponents/tool/src/main/frontend/js/conversations/reactions-mixin.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-post.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46816
> SAK-46816 conversations. More upvoting fixes

- site-manage/site-manage-participant-helper/src/bundle/org/sakaiproject/site/tool/participant/bundle/sitesetupgeneric_es.properties
Jira: [SAK-49267](https://sakaiproject.atlassian.net/browse/SAK-49267)
[SAK-49267]: https://sakaiproject.atlassian.net/browse/SAK-49267?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAK-49267 Site Info: Improve Spanish translations for 'Add Participants' section

- conditions/api/src/java/org/sakaiproject/condition/api/model/Condition.java
- conditions/impl/src/java/org/sakaiproject/condition/impl/ConditionServiceImpl.java
- vuecomponents/tool/src/main/frontend/src/components/condition-picker.vue
Undo all exact comparisons for itemId
Also removed a check that is not needed
> S2U-35 Lessons: Undo all exact comparisons for itemId

- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
https://sakaiproject.atlassian.net/browse/SAK-49265
> SAK-49265 Kernel SiteService remove stacktrace from getEntity

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-46907
> SAK-46907 Portal sites drawer displays while unauthenticated in Mobile view

- kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml
- kernel/kernel-impl/src/main/resources/antisamy/low-security-policy.xml
- library/src/webapp-filtered/editor/ckeditor.launch.js
> SAK-49264 Kernel antisamy policy update for ckeditor attribute sandbox

- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-49268
> SAK-49268 Assignments wrong method in template list assignments

- library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48364
> SAK-48364 Site Info: Site icons do not work at all

- library/src/webapp/js/sakai-message-broker.js
https://sakaiproject.atlassian.net/browse/SAK-49236
> SAK-49236 Portal: Uncaught (in promise) TypeError: subscription is null - sakai-message-broker.js:30:11

- lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-49278
> SAK-49278 Lessons: Add Content Links shows Embed Content on Page heading

- content/content-bundles/resources/types.properties
- content/content-bundles/resources/types_ca.properties
- content/content-bundles/resources/types_es.properties
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
- content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm
Screenshots: [SAK-49282](https://sakaiproject.atlassian.net/browse/SAK-49282)
- Add text about the meaning of the asterisks: Required items marked with a *
- Action button should be disabled by default
- Missing info about 'Web Address (URL)' input, as only complete URLs are valid.
[SAK-49282]: https://sakaiproject.atlassian.net/browse/SAK-49282?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SAK-49282 Resources: Improvements around 'Add Web Links' required fields

- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/CommentTransferBean.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/beans/PostTransferBean.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConversationsComment.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConversationsPost.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostReaction.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostReactionTotal.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostStatus.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicReaction.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicReactionTotal.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicStatus.java
- conversations/api/src/main/java/org/sakaiproject/conversations/api/model/UserStatistics.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/ConversationsCommentRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/ConversationsPostRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/PostReactionRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/PostReactionTotalRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/PostStatusRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/TopicReactionRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/TopicReactionTotalRepositoryImpl.java
- conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/TopicStatusRepositoryImpl.java
- conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
- kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepository.java
- kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepositoryImpl.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment-editor.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js
- webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://sakaiproject.atlassian.net/browse/SAK-49263
> SAK-49263 conversations. Improve hibernate implementation

- assignment/impl/src/test/org/sakaiproject/assignment/impl/FakeReference.java
- calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteMerger.java
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/EntityManager.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/Reference.java
- kernel/api/src/main/java/org/sakaiproject/entity/cover/EntityManager.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/EntityManagerComponent.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/ReferenceComponent.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/ReferenceVectorComponent.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseEventTrackingService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/entity-components.xml
https://sakaiproject.atlassian.net/browse/SAK-49283
> SAK-49283 Kernel EntityManager improvements

- roster2/bundle/src/bundle/card_game.properties
- roster2/bundle/src/bundle/card_game_ca.properties
- roster2/bundle/src/bundle/card_game_es.properties
- roster2/tool/src/webapp/js/card-game/card-game.js
This addresses [SAK-49271](https://sakaiproject.atlassian.net/browse/SAK-49271) for [S2U-42](https://sakaiproject.atlassian.net/browse/S2U-42)
[SAK-49271]: https://sakaiproject.atlassian.net/browse/SAK-49271?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[S2U-42]: https://sakaiproject.atlassian.net/browse/S2U-42?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> S2U-42 SAK-49271 Card Game: Do not require an answer

- webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js
https://sakaiproject.atlassian.net/browse/SAK-47714
> SAK-47714 dashboard. Expand MOTD if there is a message to view

- roster2/tool/src/webapp/js/card-game/card-game.js
Fix bug in "mark as learned" feature introduced with [SAK-49260](https://sakaiproject.atlassian.net/browse/SAK-49260).
[SAK-49260]: https://sakaiproject.atlassian.net/browse/SAK-49260?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> S2U-42 SAK-49260 Card game: Fix mark as learned

- webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-46454
> SAK-46454 grader. Always set filtered submissions when using settings

- announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementsUserNotificationHandler.java
- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/repository/UserNotificationRepositoryImpl.java
- message/message-api/api/src/java/org/sakaiproject/message/api/MessageService.java
- message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
- webcomponents/bundle/src/main/bundle/sui-notifications.properties
- webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js
- webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
https://sakaiproject.atlassian.net/browse/SAK-49298
> SAK-49298 dashboard. Add MOTD announcments to the bullhorns

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileImageLogicImpl.java
- webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
https://sakaiproject.atlassian.net/browse/SAK-49259
> SAK-49259 Card Game: Skip users with no photo

- roster2/bundle/src/bundle/card_game.properties
- roster2/bundle/src/bundle/card_game_ca.properties
- roster2/bundle/src/bundle/card_game_es.properties
- roster2/tool/src/webapp/js/card-game/card-game.js
https://sakaiproject.atlassian.net/browse/SAK-49271
> SAK-49271 Card Game: Do not require an answer

- webcomponents/tool/src/main/frontend/js/forums/sakai-forums.js
- webcomponents/tool/src/main/frontend/js/tasks/assignation-types.js
- webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
https://sakaiproject.atlassian.net/browse/SAK-48395
> SAK-48395 tasks. Only setup date picker on first updated.

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-49315
> SAK-49315 Assignments skip non loadable submission attachments

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Initially this is for Andrea to test.
> SAK-48967 - Re-enable group LTI submissions

- assignment/api/src/resources/assignment.properties
- assignment/api/src/resources/assignment_ca.properties
- assignment/api/src/resources/assignment_es.properties
- assignment/api/src/resources/assignment_eu.properties
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/S2U-31
> S2U-31 Assignments: Grades in the main view of assignments that have already been evaluated - MASTER

- webcomponents/tool/src/main/frontend/js/imageeditor/sakai-image-editor.js
https://sakaiproject.atlassian.net/browse/SAK-46628
> SAK-46628 dashboard. render imagepicker when i18n loaded

- roster2/bundle/src/bundle/card_game.properties
https://sakaiproject.atlassian.net/browse/SAK-49330
> SAK-49330 roster. Change i18n from students to students'

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-49337
> SAK-49337 Add format field to lesson endpoint for BREAK type

- gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48630
> SAK-48630 Gradebook: Points are not being displayed in Grade Summary for a student

- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html
https://sakaiproject.atlassian.net/browse/SAK-49193
> SAK-49193 Profile > Privacy: page needs formatting

- webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-readonly.js
…bric listing to the "publicly shared" listing.
> SAK-49319 Rubrics add the same rubric draft label to the shared listing

- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Adding empty cells for peer review rows
https://sakaiproject.atlassian.net/browse/SAK-49338
> SAK-49338 Assignments missing cells in peer-review rows in assignment table

- samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
Fix related to: https://sakaiproject.atlassian.net/browse/SAK-49354 for s2u-22x branch
> S2U-25 5.1.1.21 Test & Quizzes: Question pools export
