sakaiproject/sakai

samigo/samigo-app/src/webapp/jsf/qti/choosePoolExportType.jsp
https://sakaiproject.atlassian.net/browse/SAK-49354
=> S2U-25 SAK-49354 Samigo: Export pool and clicking Cancel displays a console error - SPNR is not defined

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/beans/LessonItemRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/beans/SiteEntityRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/beans/TimeExceptionRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/Conditions.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/LessonsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
https://sakaiproject.atlassian.net/browse/SAK-49276
https://sakaiproject.atlassian.net/browse/SAK-49337
https://sakaiproject.atlassian.net/browse/SAK-49258
=> UNIADAPTIVE Work package (s2u-22x)

webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
https://sakaiproject.atlassian.net/browse/SAK-48871
=> SAK-48871 tasks. Clear complete checkbox if cancelled

webcomponents/tool/src/main/frontend/js/coursedashboard/sakai-course-overview.js, webcomponents/tool/src/main/frontend/js/sakai-editor.js
https://sakaiproject.atlassian.net/browse/SAK-48740
=> SAK-48740 dashboard. Use full editor toolbars

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/AssociationRepository.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java, rubrics/impl/src/test/resources/hibernate.properties
https://sakaiproject.atlassian.net/browse/SAK-48860
=> SAK-48860 gradebook. Delete rubric association when deleting item

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/component-manager/src/main/java/org/sakaiproject/component/api/ServerConfigurationService.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-48525
=> SAK-48525 dashboard. Hide tasks widget by default.

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/detailed/refresolvers/AssignmentReferenceResolver.java
https://sakaiproject.atlassian.net/browse/SAK-44565
=> SAK-44565 SiteStats assignment read event incorrectly shows instructor as submitter

basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/SiteEmailPreferenceSetterImpl.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/UserLocaleSetterImpl.java, calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/PrefsBean.java, common/privacy-comp-impl/pom.xml, common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/BaseContentReviewService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/entity/UserPrefsEntityProvider.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
Ensure PreferenceEdit are canceled or committed
https://sakaiproject.atlassian.net/browse/SAK-49358
=> SAK-49358 Preferences improved handling of edits

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateOrganize.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfWatchSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgFolderRevise.jsp
fixed .jsp files: dfTemplateOrganize, dfTemplateSettings, dfWatchSettings, pvtMsgFolderRevise
=> SAK-49351 Msgcntr message bundle baseName in some jsp files were incorrect

roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-49326
=> SAK-49326 roster. Don't use body size to calculate data page size

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, kernel/api/src/main/java/org/sakaiproject/util/comparator/UserNameComparator.java, roster2/tool/src/java/org/sakaiproject/roster/api/RosterMember.java, roster2/tool/src/java/org/sakaiproject/roster/api/RosterMemberComparator.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49350
=> SAK-49350 roster. Remove User object from serialised JSON

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, webapi/src/main/java/org/sakaiproject/webapi/beans/SiteEntityRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
Support resource folders
Support un-setting dueDate and closeDate for forums and resources
=> SAK-49258 UNIADAPTIVE Work package fixes (s2u-22x)

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js, webcomponents/tool/src/main/frontend/js/sakai-jump-to-top.js
https://sakaiproject.atlassian.net/browse/SAK-49242
=> SAK-49242 grader. Show draft inline submission after close date

roster2/tool/src/java/org/sakaiproject/roster/api/RosterMember.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49118
=> SAK-49118 roster. Add instructors to group member's views

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49377
=> SAK-49377 Messages error when moving a message to a different folder

lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-49375
=> SAK-49375 Lessons change default display options for 'Add Learning App'

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, rubrics/api/src/main/bundle/rubrics.properties, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-49370
=> SAK-49370 rubric. Move criterion comment to modal

webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47848
=> SAK-47848 grader. Added curly brace instruction to grader feedback

webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://sakaiproject.atlassian.net/browse/SAK-49390
=> SAK-49390 grader. Only show "Inline Submission" when appropriate

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html
https://sakaiproject.atlassian.net/browse/SAK-49357
=> SAK-49357 Gradebook > Grade Release Rules > Points: Highlight color of preview needs to be adjusted, dark mode is unreadable.

content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
[SAK-49403](https://sakaiproject.atlassian.net/browse/SAK-49403)
[SAK-49403]: https://sakaiproject.atlassian.net/browse/SAK-49403?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49403: Enhance Log Messages for Improved Turnitin Error Detection

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java, assignment/tool/pom.xml, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, content-review/tool/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-47032
- remove review_score submission property as it isn't used
- fix outputDirectory typo in content review
- remove unncessary ant dependency
=> SAK-47032 Assignments switch submission properties cache to lazy

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
If the user it is related to one or more groups, set it by default when creating a new task:
But if it isn't related to any group:
=> S2U-30 5.1.4.1 Assignments: When an assignment is created, assign it by default to the groups where the user is an instructor - Master

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-49342
=> SAK-49342 Contrast Issues with Lessons Subpage Button Text

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
https://sakaiproject.atlassian.net/browse/SAK-49343
=> SAK-49343 Info icon in Worksite Setup tool shows incorrect site information

roster2/bundle/src/bundle/roster.properties, roster2/tool/src/handlebars/members_cards.handlebars
https://sakaiproject.atlassian.net/browse/SAK-48898
=> SAK-48898 Roster add aria-label and title to profile links

signup/tool/src/webapp/js/signupScript.js
…r meeting:emailAttendeeOnly, so make sure the check for it is after the line that returns if it's missing to avoid a js console error.
=> SAK-46755 Signup not all pages that use this script have input elements for emailAttendeeOnly

samigo/samigo-app/src/webapp/js/finInputValidator.js
https://sakaiproject.atlassian.net/browse/SAK-49381
=> SAK-49381 T&Q: Numeric response question > Uncaught TypeError: .popover is not a function

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
https://sakaiproject.atlassian.net/browse/SAK-49370
=> SAK-49370 rubrics. Adjust position and height of comment popover

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/webapp/WEB-INF/applicationContext.xml, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://sakaiproject.atlassian.net/browse/SAK-47987
=> SAK-47987 grader. Add peer review information to submission

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/AssociationRepositoryImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48860
=> SAK-48860 Rubrics ToolItemRubricAssociation improved save method adhering to its equals and hashcode strategy

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramQuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/AssessmentReport.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/AssessmentReportSection.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/SamigoBaseServlet.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExcelExportUtil.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/PdfExportUtil.java, samigo/samigo-app/src/webapp/WEB-INF/web.xml, samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
Adds:
- New "Skewness coefficient" row to (assessment) Statistics and export to PDF and XLSX
- New "Difficulty", "Total attempts", "Total correct" and "Total incorrect" to item analysis and export to PDF and XLSX
https://sakaiproject.atlassian.net/browse/S2U-7
=> S2U-7 Tests & Quizzes: Assessment Report

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
https://sakaiproject.atlassian.net/browse/SAK-47315
This is the dirtiest of hacks and I am not proud of it. But ... until I work out a decent way of not annoying lit by moving stuff around underneath it, it will do the job.
=> SAK-47315 rubrics. Reload page when reordering criteria

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SecureDeliveryController.java
- Add new resource collection under /public for published seb configs 
- Add display name property to resources, both uploaded seb config (draft, in /attachment/site/Assessment/) and copied published version (/public/seb/) 
=> S2U-21 Tests & Quizzes: Add seb resource collection and set display name property

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/assessment/SecureDeliveryServiceImpl.java
=> S2U-21 Samigo: Fixes around linear access through SEB

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
https://sakaiproject.atlassian.net/browse/SAK-49405
Some code missing from https://sakaiproject.atlassian.net/browse/S2U-11 when translating to MASTER
https://github.com/sakaiproject/sakai/commit/ff90549f3ae2b9072cc93af4a308668668d7e915
=> SAK-49405 T&Q: NPE when trying to import an xml file to the Question Pool

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm, webcomponents/tool/src/main/frontend/js/sakai-date-picker.js
https://sakaiproject.atlassian.net/browse/SAK-49409
=> SAK-49409 Assignment update date time inputs with sakai-date-picker

samigo/samigo-app/src/webapp/js/finInputValidator.js
https://sakaiproject.atlassian.net/browse/SAK-49381
=> SAK-49381 Samigo numeric response question can cause js TypeError: .popover is not a function

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/pom.xml, webcomponents/tool/src/main/frontend/js/conversations/sakai-comment.js, webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js, webcomponents/tool/src/main/frontend/js/sakai-reorderer.js, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json
https://sakaiproject.atlassian.net/browse/SAK-49427
=> SAK-49427 sakai-reorderer add a reordering web component

pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/banners/BannerStorage.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/PASystemServlet.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/handlers/BannersHandler.java
https://sakaiproject.atlassian.net/browse/SAK-43953
=> SAK-43953 PA System: Banner Dismissal Resets Upon Any Form of Update

webcomponents/tool/src/main/frontend/js/sakai-date-picker.js, webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
https://sakaiproject.atlassian.net/browse/SAK-48871
=> SAK-48871 tasks. Reset created task correctly.

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
https://sakaiproject.atlassian.net/browse/SAK-49427
=> SAK-49427 rubrics. Add drag handle back to criterion groups

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java
https://sakaiproject.atlassian.net/browse/S2U-7
=> S2U-7 Fix typo in debug log message

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-evaluation-remover.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-48966
=> SAK-48966 grader. Reset rubric correctly between gradings

roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_container_table.handlebars, roster2/tool/src/handlebars/members_table.handlebars, roster2/tool/src/java/org/sakaiproject/roster/api/RosterMember.java, roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java, roster2/tool/src/webapp/js/roster.js, sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsManagerTest.java
https://sakaiproject.atlassian.net/browse/SAK-49429
=> SAK-49429 rubrics. Fix visit count and last visit time

webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-evaluation-remover.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-49007
=> SAK-49007 grader. Show "Saving grade" message to user

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-constants.js
https://sakaiproject.atlassian.net/browse/SAK-47943
=> SAK-47943 grader. Reset rubric view to grading rubric

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-48129
=> SAK-48129 grader. Reset indicator colours on cancel

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/evaluation/ExportReportServlet.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/PdfExportUtil.java, samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp
- Renamed "N" column to "Total attempts"
- Fixed Total attempts vs Total attempts(n) display in export
- Fixed missing not displaying of shorter rows (and possible misalignment) in PDF export
https://sakaiproject.atlassian.net/browse/S2U-7
=> S2U-7 T&Q: Several fixes

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
=> SAK-49460 Samigo remove whitespace after url decoding the resourceId for attachments from questions in a question pool

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/RetakeAssessmentListener.java
=> SAK-49459 Samigo add a new event when an instructor allows an assessment retake

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
=> SAK-49461 Samigo add submission info to event sam.assessment.graded.auto

samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
Do not show export button for student statistics view 
https://sakaiproject.atlassian.net/browse/S2U-7
=> S2U-7 5.1.1.3 Tests & Quizzes: Assessment report - fix

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
=> SAK-49471 Samigo include question text and score when exporting responses

library/src/webapp/js/headscripts.js, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/plus.vm
This second PR fixes the new window non-resize.
=> SAK-49468 Plus single tool iframe and new window not resizing

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
=> SAK-49456 Lessons upgrade pdf-js from 2.9.359 to 4.0.189

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
=> SAK-49385 Assignments some chars in assignment title affect downloading of all submissions

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/ShowMediaServlet.java
=> SAK-49490 Samigo serving files from ShowMediaServlet with non-ascii characters causes a 500 error

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-rating-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sharing-change-event.js, webcomponents/tool/src/main/frontend/js/sakai-reorderer.js
https://sakaiproject.atlassian.net/browse/SAK-49427
=> SAK-49427 Rubrics fix ckeditor warning on reordering

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content_type/content_type_classes.properties, config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content_type/content_type_extensions.properties, config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content_type/content_type_names.properties, config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content_type/content_type_names_es.properties, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
https://sakaiproject.atlassian.net/browse/SAK-49498
=> SAK-49498 Resources detect filetype on a Jupyter Notebook

library/src/webapp/content/server_info.html
https://sakaiproject.atlassian.net/browse/SAK-49244
=> SAK-49244 Portal address insufficient color contrast issues with text/links on Gateway page

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
=> SAK-49384 Portal fix expand/collapse tool list in siteNav with site ids

library/src/webapp/js/lang-datepicker/lang-datepicker.js
https://sakaiproject.atlassian.net/browse/SAK-49044
=> SAK-49044 Calendar Widget / Date Picker: Accessibility: Date picker button needs to be labeled and indicate when it is opened/closed

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementsUserNotificationHandler.java, message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
https://sakaiproject.atlassian.net/browse/SAK-49529
=> SAK-49529 Announcement npe during site import doesn't clear security advisor

webcomponents/tool/src/main/frontend/js/sakai-button.js, webcomponents/tool/src/main/frontend/js/sakai-course-card.js, webcomponents/tool/src/main/frontend/js/sakai-dialog-content.js, webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js, webcomponents/tool/src/main/frontend/js/sakai-lti-iframe.js, webcomponents/tool/src/main/frontend/js/sakai-pageable-element.js, webcomponents/tool/src/main/frontend/js/sakai-permissions.js, webcomponents/tool/src/main/frontend/js/sakai-pronunciation-player.js, webcomponents/tool/src/main/frontend/js/sakai-submission-messager.js, webcomponents/tool/src/main/frontend/js/sakai-user-photo.js, webcomponents/tool/src/main/frontend/package.json
https://sakaiproject.atlassian.net/browse/SAK-49448
=> SAK-49448 webcomponents. More lit-analyzer fixes.

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://sakaiproject.atlassian.net/browse/SAK-49045
=> SAK-49045 grader. Added originality report data to submission maps

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Instead of adding a confirmation, let's get rid of the button for consistency reasons.
=> SAK-49511 Lessons: Deleting a subpage does not display any confirmation

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/util/TotalScoresExportBean.java, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
Not a big fan of the button position, I contributed the patch as it was provided by UPV.
=> SAK-49472 T&Q ability to export the student scores

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
=> SAK-49474 Samigo include the editor in the student's rationale for multiple choice

webcomponents/tool/src/main/frontend/js/sakai-i18n.js
https://sakaiproject.atlassian.net/browse/SAK-49576
=> SAK-49576 webcomponents add better protection when processing translation

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
https://sakaiproject.atlassian.net/browse/SAK-49580
=> SAK-49580 Not all global variables are exported on the xml - S2U-11 - MASTER

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
https://sakaiproject.atlassian.net/browse/SAK-49580
=> SAK-49580 Not all global variables are exported on the xml - S2U-11

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
https://sakaiproject.atlassian.net/browse/SAK-49575
Fixing some S2U-10 problems
https://sakaiproject.atlassian.net/browse/S2U-10
=> SAK-49575 Sometimes some answers are interchanged when clicking Solution - S2U-10 - MASTER

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java, gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-49442
=> SAK-49442 gradebook. Added tooltips to column headers

webcomponents/tool/src/main/frontend/js/sakai-date-fns.js, webcomponents/tool/src/main/frontend/js/sakai-date-picker.js, webcomponents/tool/src/main/frontend/js/sakai-editor.js, webcomponents/tool/src/main/frontend/js/sakai-reorderer.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-constants.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json
https://sakaiproject.atlassian.net/browse/SAK-48871
=> SAK-48871 tasks. Fix completed checkbox issues

library/pom.xml, library/src/webapp-filtered/editor/ckeditor.launch.js, master/pom.xml
Would be good to release this as a Sakai Webjar like other plugins, but I don't know how to do it.
=> SAK-49520 CKEditor: Added FMath plugin

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
https://sakaiproject.atlassian.net/browse/SAK-49575
Fixing some S2U-10 problems
https://sakaiproject.atlassian.net/browse/S2U-10
=> SAK-49575 Sometimes some answers are interchanged when clicking Solution - S2U-10

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradeType.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingConstants.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradebookAssignment.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/chart/AssignmentGradeChart.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
https://sakaiproject.atlassian.net/browse/SAK-49584
=> SAK-49584 Gradebook GradeType ordinal starts at 1

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49590
=> SAK-49590 gradebookng IS_EXCLUDED_FROM_GRADE autoboxing results in an NPE

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/TestGradebookNgBusinessService.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
https://sakaiproject.atlassian.net/browse/SAK-49588
=> SAK-49588 gradebookng use a mock ResourceLoader when running tests

webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
… have the same formatting as other announcement notifications
=> SAK-49546 Announcment add consistent formatting for announcement released in the future

lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDao.java, lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
=> SAK-49207 Lessons deleting item in lessons tool should remove entry in log table

webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js, webcomponents/tool/src/main/frontend/package-lock.json
https://sakaiproject.atlassian.net/browse/SAK-49586
=> SAK-49586 tasks. Dark mode link colour fixes

webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-picker.js
https://sakaiproject.atlassian.net/browse/SAK-49585
=> SAK-49585 dashboard. Fix widget picker link colour dark mode problem

webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/tool/src/main/frontend/js/grades/sakai-grades.js, webcomponents/tool/src/main/frontend/js/widgets/sakai-grades-widget.js
https://sakaiproject.atlassian.net/browse/SAK-49388
=> SAK-49388 gradeswc. Use "me" instead of userId in fetch url

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.html, library/src/webapp/js/sakai-recorder.js, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/AudioUploadActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/ShowMediaServlet.java, samigo/samigo-app/src/webapp/jsf/delivery/item/audioObject.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
https://sakaiproject.atlassian.net/browse/SAK-45593
=> SAK-45593 Samigo file upload questions appear to wipe out audio response on same page

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
https://sakaiproject.atlassian.net/browse/SAK-48432
There are problems with some some test... mmmm
Nowadays, this test code should be...
```
result = gradingService.processFormulaIntoValue("1.8E-4", 2);
//Assert.assertEquals("1.8E-4", result);
Assert.assertEquals("0", result); 
```
I think is incorrect...
=> SAK-48432 SAMIGO Problem on Calculated question with e-4

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, msgcntr/messageforums-app/src/webapp/js/messages.js
Some of the changes requested on #12233
https://sakaiproject.atlassian.net/browse/S2U-32
https://sakaiproject.atlassian.net/browse/S2U-28
=> S2U-32 S2U-28 Spacing fixes

conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionOperator.java, conditions/api/src/java/org/sakaiproject/condition/api/model/ConditionType.java, conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/BaseConditionEvaluator.java
=> S2U-35 Add missing licence headers

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementMessage.java, announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/DbAnnouncementService.java, announcement/announcement-impl/impl/src/webapp/WEB-INF/components.xml, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/entityprovider/AnnouncementEntityProviderImpl.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapper.java, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webcomponents/tool/src/main/frontend/js/announcements/sakai-announcements.js
https://sakaiproject.atlassian.net/browse/SAK-49604
=> SAK-49604 dashboard. Make wc honour role based announcements

usermembership/tool/src/bundle/org/sakaiproject/umem/tool/bundle/Messages.properties, usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/SiteListBean.java
Currently, the site shows up as Published and confuses support staff.
=> SAK-44107 usermembership if the site is deleted it should show as marked for deletion

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemHistoricalIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/convert/AccessTypeConverter.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/convert/UsernameConverter.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java, samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml, samigo/samigo-app/src/webapp/jsf/questionpool/previewQuestion.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemHistorical.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
This needs to be merged after #12210.
This is paired to https://github.com/sakaiproject/sakai-reference/pull/231
=> SAK-49591 T&Q: Show historical changes for questions in question pools

library/src/webapp/js/portal/portal.theme.switcher.js
https://sakaiproject.atlassian.net/browse/SAK-48845
=> SAK-48845 Portal improve iframe dark mode compatibility

library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, library/src/webapp/content/gateway/about.html, library/src/webapp/content/gateway/acknowledgements.html, library/src/webapp/content/gateway/features.html, library/src/webapp/content/server_info.html
https://sakaiproject.atlassian.net/browse/SAK-49519
=> SAK-49519 Portal a11y address insufficient color contrast issues with text or links on Gateway page

samigo/samigo-api/src/java/xml/author/v1p2/sectionTemplate.xml, samigo/samigo-api/src/java/xml/xsl/dataTransform/import/v1p2/extractSection.xsl, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-cp/src/java/org/sakaiproject/tool/assessment/contentpackaging/ManifestGenerator.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/asi/Section.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
This has to be merged after #12210 and #12213
=> SAK-49595 T&Q: Import/Export assessments with parts based on random questions

conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssignmentConditionEvaluator.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- Fix hidden subpage content du to null userId
- Fix assignment conditions when assignment is submitted by a student on behalf of group
=> S2U-35 Lessons: Fixes related to conditions

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://sakaiproject.atlassian.net/browse/SAK-49592
=> SAK-49592 Avoid enter parenthesis from instructors while operating with global variables

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://sakaiproject.atlassian.net/browse/SAK-49592
=> SAK-49592 Avoid enter parenthesis from instructors while operating with global variables - 22.x

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
I probably went too far doing a refactor of the class, I'm fine reverting all the non-related changes and stick to the minimum.
=> SAK-49525 Private Messages: Add a mailto link to the email footer

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
https://sakaiproject.atlassian.net/browse/SAK-49622
=> S2U-18 SAK-49622 T&Q Fix question pool item sorting - s2u-22x

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
Additional cleanup after https://github.com/sakaiproject/sakai/pull/12202
=> SAK-49609 Library: templates.js console errors

meetings/tool/src/main/webapp/WEB-INF/templates/index.html, meetings/ui/src/main/frontend/src/App.vue, meetings/ui/src/main/frontend/src/views/CreateMeeting.vue
- Fixes 404 on vendor.js
- Removed fontawsome styles (provided by sakai)
- Remove console.log
https://sakaiproject.atlassian.net/browse/S2U-47
=> S2U-47 Meetings: Small cleanup

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/RubricRepository.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/RubricRepositoryImpl.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-47669
=> SAK-47669 Rubrics are locked if they have evaluations

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
https://sakaiproject.atlassian.net/browse/SAK-49602
=> SAK-49602 Portal URLs generated by link button have no protocol and shortened URLs don't work

signup/tool/src/java/org/sakaiproject/signup/tool/jsf/HtmlTableRenderer.java, signup/tool/src/webapp/WEB-INF/faces-config.xml
=> SAK-38360 Signup add a col scope to the table renderer

kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java
Defer to content hosting service for more details of creating the resource, like making sure the id is unique
=> SAK-49508 Kernel illegal characters in the title when creating zip files

webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webcomponents/tool/src/main/frontend/js/announcements/sakai-announcements.js
https://sakaiproject.atlassian.net/browse/SAK-49617
=> SAK-49617 Announcements wc should display highlighted messages properly

samigo/samigo-app/src/webapp/js/finInputValidator.js
I restored some pre-existing logic for supporting the qtip popover and for processing negative, complex, and other valid numbers.
Jira: https://sakaiproject.atlassian.net/browse/SAK-49611
=> SAK-49611 Samigo numeric response question regressions

library/src/skins/default/src/sass/base/_icons.scss, library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-49630
=> SAK-49630 Portal hidden sites don't appear in site nav

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
https://sakaiproject.atlassian.net/browse/SAK-49597
=> SAK-49597 Kernel allowAccessSite should consider if user is role swapped

syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49620
=> SAK-49620 Syllabus properly delete attachments using cascading

samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/SebValidation.hbm.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-49642
=> S2U-21 SAK-49642 T&Q: Access denied on repeated attempts - MASTER

samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/SebValidation.hbm.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-49642
=> S2U-21 SAK-49642 T&Q: Access denied on repeated attempts - s2u-22x

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, library/src/webapp/js/sakai-lti-advantage.js
This is to fix an issue identified by Perusal.
=> SAK-49618 LTI add custom frame support using lti_storage_target in LTI Advantage

library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/PartData.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/webapp/js/authoringQuestionCancellation.js, samigo/samigo-app/src/webapp/js/deliveryQuestionCancellation.js, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/ItemCancellationTest.java
Jira [S2U-14](https://sakaiproject.atlassian.net/browse/S2U-14)
Developed by: @stetsche
This is a port from Sakai 22 to 24
From PRs: (#11328) (#11542)
[S2U-14]: https://sakaiproject.atlassian.net/browse/S2U-14?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> S2U-14 5.1.1.10 T&Q: Canceled questions and score re-calculation - MASTER

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/editPart.jsp, samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentData.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
Leaving as a draft for the moment. This will be adapted once https://github.com/sakaiproject/sakai/pull/12134 is merged, some of it is based on it but new conflicts will appear on the places where they diverge.
=> S2U-20 Tests & Quizzes: random questions from multiple pools

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SebSetupActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueriesAPI.java
https://sakaiproject.atlassian.net/browse/SAK-49646
=> S2U-21 SAK-49646 T&Q: Fix early timer start with SEB - s2u-22x

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SebSetupActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/SebValidationFacadeQueriesAPI.java
https://sakaiproject.atlassian.net/browse/SAK-49646
=> S2U-21 SAK-49646 T&Q: Fix early timer start with SEB - MASTER

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
https://sakaiproject.atlassian.net/browse/SAK-49651
=> S2U-21 SAK-49651 T&Q: Add config key input - s2u-22x

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
https://sakaiproject.atlassian.net/browse/SAK-49651
=> S2U-21 SAK-49651 T&Q: Add config key input - MASTER

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/TagIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolTagsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/ClearSelectedTagsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/FilterByTagsListener.java, samigo/samigo-app/src/webapp/jsf/questionpool/statisticsModal.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/questionpool/QuestionPoolTag.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/StatisticsService.java
Also removing unused variable.
https://sakaiproject.atlassian.net/browse/S2U-17
=> S2U-17 Add dialog label for modal

webapi/src/main/java/org/sakaiproject/webapi/controllers/ProfileController.java, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-gradable-data-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/submission.js, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js
https://sakaiproject.atlassian.net/browse/SAK-49659
=> SAK-49659 grader. Fix document preview links after bundling change.

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/sakai-rubrics-utils.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriteria.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionRatingEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionStudent.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricReadonly.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsManager.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsSharedList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubrics.test.js
https://sakaiproject.atlassian.net/browse/SAK-49655
=> SAK-49655 rubrics. Move to modals for rubric and criterion editors

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MenuBuilder.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
SAK-49610 Button Manage Overview in 'Home'
https://sakaiproject.atlassian.net/browse/SAK-49610
=> SAK-49610 Portal button to manage Overview in Home site

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties
https://sakaiproject.atlassian.net/browse/S2U-16
=> S2U-16 Add missing EU translations

samigo/samigo-app/pom.xml, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://sakaiproject.atlassian.net/browse/S2U-9
=> S2U-9 5.1.1.5 Tests & Quizzes: PDF export for assessment submissions - MASTER

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
=> S2U-6 SAK-49674 T&Q: Summary performance fix

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importMigrate.vm
https://sakaiproject.atlassian.net/browse/SAK-49564
=> SAK-49564 sitemanage. Include Templates in list of sites for import

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/beans/LessonItemRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/beans/SiteEntityRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/beans/TimeExceptionRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConditionController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/LessonsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java
https://sakaiproject.atlassian.net/browse/SAK-49258
=> SAK-49258 Webapi: Add endpoints to get and bulk update various entities

samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js
https://sakaiproject.atlassian.net/browse/SAK-49651
=> S2U-21 SAK-49651 Fix endless loading on race condition - s2u-22x

samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js
https://sakaiproject.atlassian.net/browse/SAK-49651
=> S2U-21 SAK-49651 Fix endless loading on race condition - MASTER

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
https://sakaiproject.atlassian.net/browse/S2U-20
=> S2U-20 Add i18n for multiselect

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/SectionDataIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmRemovePartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePartListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/editPart.jsp, samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/AssessmentData.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ItemCancellationUtil.java
https://sakaiproject.atlassian.net/browse/S2U-20
=> S2U-20 Tests & Quizzes: random questions from multiple pools - MASTER

kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTests.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
There is also a test for the favorites migration from preferences.
=> SAK-48700 Portal unit tests for the auto pinning feature

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/RoleSwitchHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/RoleSwitchOutHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://sakaiproject.atlassian.net/browse/SAK-48321
=> SAK-48321 Kernel/Portal - Exiting Role View Redirects Instructor Out of Site and Role Swap Defaults to Overview Page

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
=> SAK-49672 Gradebook provide permission denied error instead of stacktrace

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js
https://sakaiproject.atlassian.net/browse/SAK-49655
=> SAK-49655 rubrics. Add bs fade class to rubric edit modal

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiAddTopic.js
https://sakaiproject.atlassian.net/browse/SAK-49678
=> SAK-49678 WC sakai-editor not loading in conversations

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-settings.js, gradebookng/tool/src/webapp/scripts/gradebook-sorter.js, library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-sorter.css, library/src/webapp/js/ksortable-plugin.js, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm
https://sakaiproject.atlassian.net/browse/SAK-48581
=> SAK-48581 gradebook. Add keyboard ordering to settings->categories

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-import.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-importMigrate.vm
https://sakaiproject.atlassian.net/browse/SAK-49564
=> SAK-49564 sitemanage. Moved template sites to top in replace

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGroup.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradeTableData.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
This is something I improved when contributing the feature to master, so I thought it would be good to have it here too
=> S2U-26 getGradeableUsers refactor

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://sakaiproject.atlassian.net/browse/SAK-49689
=> SAK-49689 Portal view site as will not be visible if site is unpublished

library/src/webapp/js/headscripts.js, library/src/webapp/js/portal/portal.theme.switcher.js, login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-48845
=> SAK-48845 Library Improve Portal Theme Switcher

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/sakai-rubrics-utils.js
This is something that originally comes from S2U-34 (s2u-unidigital), but got lost after SAK-48323
=> SAK-48323 Gradebook : Fix rubrics visibility for students

usermembership/tool/src/webapp/usermembership/userlist.jsp
https://sakaiproject.atlassian.net/browse/SAK-49701
=> SAK-49701 UserMembership results table is not showing all of the columns data

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ReorderProducer.java, lessonbuilder/tool/src/webapp/templates/Reorder.html, lessonbuilder/tool/src/webapp/templates/ShowPage.html, library/src/skins/default/src/sass/base/_icons.scss
https://sakaiproject.atlassian.net/browse/SAK-49615
=> SAK-49615 Lessons: Title of a Question Item incorrectly displayed

library/src/skins/default/src/sass/modules/tool/syllabus/_syllabus.scss, syllabus/syllabus-app/src/webapp/js/syllabus.js, syllabus/syllabus-app/src/webapp/syllabus/main.jsp
syllabus sortable was being setup in both syllabus.js and in morpheus scripts
=> SAK-49724 Syllabus collapse should show icon and syllabus reordering cleanup

webcomponents/tool/src/main/frontend/packages/sakai-picture-changer/src/SakaiPictureChanger.js
=> SAK-48326 WC sakai-picture-changer dont attach all of the cropping until the user wants to change their profile image

sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditManagersBean.java
[SAK-49722: Problem alphabetical order of the student names in the "Section info" tool](https://sakaiproject.atlassian.net/browse/SAK-49722)
=> SAK-49722 Sections student names should be in alphabetical order

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoObserver.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AuthzQueriesFacadeAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/authz/integrated/AuthzQueriesFacade.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/MainController.java
=> SAK-49697 Samigo deleting group linked to draft assessment does delete authz data

library/src/webapp/content/gateway/about.html, library/src/webapp/content/gateway/acknowledgements.html, library/src/webapp/content/gateway/features.html, library/src/webapp/content/gateway/gateway.scss, library/src/webapp/content/server_info.html, library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-49733
I think after this commit. We should have dark mode availability on all pages in whole Sakai :)
=> SAK-49733 Gateway pages are broken due to bootstrap CSS not loading

sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/EditManagersBean.java
[SAK-49722: Problem alphabetical order of the student names in the "Section info" tool ](https://sakaiproject.atlassian.net/browse/SAK-49722)
=> SAK-49722: Problem alphabetical order of the student names in the "Section info" tool - Correction for correct order

kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/MicrosoftMessagingServiceImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/messaging-components.xml, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftAuthorizationServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftConfigurationServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftLoggingServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftSynchronizationServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java, microsoft-integration/impl/src/webapp/WEB-INF/components.xml
https://sakaiproject.atlassian.net/browse/SAK-49758
- should use spring wiring via xml with components not both
- removed noop init methods
- formatting
=> SAK-49758 Microsoft integration should remove ignite message listeners during shutdown

content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm, library/src/skins/default/src/sass/modules/tool/resources/_resources.scss
https://sakaiproject.atlassian.net/browse/SAK-49569
There's still one minor issue. Upon initial load the first nav button seems to be in focus, even though its not active. Probably because its a button.
=> SAK-49569 Assignments file picker navigation when selecting resource from another site

library/src/skins/default/src/sass/modules/tool/resources/_resources.scss
https://sakaiproject.atlassian.net/browse/SAK-49764
=> SAK-49764 Resources Scrolling issue when selecting from other sites

msgcntr/messageforums-app/src/webapp/jsp/compose.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/permissions.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgFolderAdd.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgFolderInFolderAdd.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/topNav.jsp
https://sakaiproject.atlassian.net/browse/SAK-49223
=> SAK-49223 Messages Breadcrumb innacurate

lessonbuilder/tool/src/webapp/templates/Reorder.html
fixed modal close button by correcting the data attribute
=> SAK-49776 Lessons reorder item preview modal close (bs) button not working

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEvaluationRemover.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudent.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentButton.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentPreviewButton.js
https://sakaiproject.atlassian.net/browse/SAK-48716
=> SAK-48716 rubrics. Handle 204 returns in the student buttons

library/src/webapp-filtered/editor/ckeditor.launch.js
https://sakaiproject.atlassian.net/browse/SAK-49196
=> SAK-49196 ckeditor. Moved most used buttons to first bar

webcomponents/tool/src/main/frontend/packages/sakai-editor/src/SakaiEditor.js
https://sakaiproject.atlassian.net/browse/SAK-49679
=> SAK-49679 conversations. Use Full ckeditor when adding topics

polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
…es by deleting any polls in the destination site
=> SAK-49793 Polls implement the option to remove/cleanup during site import

signup/tool/src/java/org/sakaiproject/signup/tool/entityproviders/EventProcessHandler.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupMeetingsBean.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/EditMeetingSignupMBean.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/AddAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/AddWaiter.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/CancelAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/CancelRestoreTimeslot.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/CreateMeetings.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/LockUnlockTimeslot.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/MoveAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/RemoveWaiter.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/ReplaceAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/SwapAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/util/Utilities.java
=> SAK-33584 Signup add the meeting id and title to the default event tracking method

kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/content/cover/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/entity/api/EntityTransferrer.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java, kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml
https://sakaiproject.atlassian.net/browse/SAK-49808
=> SAK-49808 contenthosting. Replace getters/setters with annotations

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-46629
=> SAK-46629 dashboards. Include site description in site import

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
Jira: https://sakaiproject.atlassian.net/browse/SAK-49839
I attached to the jira a screencast named SAK-49839-ProposedFix.mp4 to demo the result of this proposed fix. Also, I added presentation logic to not display the "Send these Open and Close dates to Calendar" checkbox if the Calendar tool is not in the site.
=> SAK-49839 Discussions: Disappearing calendar control in topic/forum settings

library/src/skins/default/src/sass/modules/tool/sitemanage/_sitemanage.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-type.vm
https://sakaiproject.atlassian.net/browse/SAK-49398
=> SAK-49398 Create site from template doesn't display the course name unless the browser window is stretched wide

webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js
https://sakaiproject.atlassian.net/browse/SAK-49843
=> SAK-49843 conversations. Bring sakai-editor tag def in properly

library/src/skins/default/src/sass/tool.scss, library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-49860
=> SAK-49860 Fix Custom Icon (FontAwesome Icon Picker Popup) Issues in Dark Mode and Add Placeholder Text

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/CollectionAccessFormatter.java, library/src/skins/default/src/sass/modules/tool/_access.scss, library/src/skins/default/src/sass/tool.scss
https://sakaiproject.atlassian.net/browse/SAK-49318
=> SAK-49318 Web link does not display correctly in Dark Mode

gradebookng/bundle/src/main/bundle/gradebookng_sr.properties, jsf/jsf-widgets/src/java/org/sakaiproject/jsf/Configuration_sr.properties, jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/Configuration_sr.properties, microsoft-integration/admin-tool/src/main/resources/Messages_sr.properties, microsoft-integration/collaborative-documents/src/main/resources/Messages_sr.properties, microsoft-integration/media-gallery-tool/src/main/resources/Messages_sr.properties, podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages_sr.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/GeneralMessages_sr.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages_sr.properties, syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages_sr.properties
@mpellicer I'm not sure how to alert this translation team in Transifex
=> SAK-49761 Serbian translations had bad 'gggg' year format

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-47591
With regards to proper tabbing, etc. for this fix, I think I need to punt (i.e., would welcome another's push commit to resolve that). Otherwise, this works.
=> SAK-47591 Rubric button for assignments missing from student Gradebook

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js
https://sakaiproject.atlassian.net/browse/SAK-49844
=> SAK-49844 conversations. Dynamically import add-topic when editing

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, kernel/api/src/main/java/org/sakaiproject/authz/api/SecurityService.java, kernel/api/src/main/java/org/sakaiproject/authz/cover/SecurityService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java, kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockSecurityService.java
https://sakaiproject.atlassian.net/browse/SAK-49527
=> SAK-49527 Assignment student assignments shouldn't require a reload when state changes

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49677
=> SAK-49677 conversations. Honour topic type when site importing

library/src/skins/default/src/sass/base/_defaults.scss, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js
https://sakaiproject.atlassian.net/browse/SAK-49872
=> SAK-49872 conversations. Add contrast to kebab menus in dark mode

kernel/api/src/main/java/org/sakaiproject/messaging/api/model/PushSubscription.java
https://sakaiproject.atlassian.net/browse/SAK-49732
=> SAK-49732 push. Use bigger varchar for the PUSH_SUBSCRIPTIONS column

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiCommentEditor.js
https://sakaiproject.atlassian.net/browse/SAK-49890
=> SAK-49890 conversations. Fix issue with comments not saving

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49897
=> SAK-49897 conversations. Honour cleanup flag in site import

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourseManual.vm
https://sakaiproject.atlassian.net/browse/SAK-49284
=> SAK-49284 Worksite Setup: Incorrect Tab Order in New Course Creation Form

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsSharedList.js
can commit this after SAK-49923
=> SAK-49924 Rubrics date sorting should not do text sorting

conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConvStatus.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConversationsPost.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/ConversationsTopic.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostReaction.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostReactionTotal.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/PostStatus.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicReaction.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicReactionTotal.java, conversations/api/src/main/java/org/sakaiproject/conversations/api/model/TopicStatus.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js
https://sakaiproject.atlassian.net/browse/SAK-49845
- also address an undefined object in registerPosts
=> SAK-49845 Conversations SQL duplicate entity TopicStatus

library/src/skins/default/src/sass/modules/tool/sitestats/_sitestats.scss, sitestats/sitestats-tool/src/webapp/html/widget/StudentVisitsWidget.html
https://sakaiproject.atlassian.net/browse/SAK-49833
=> SAK-49833 Sitestats: Student view needs the UI updated

library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss, rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/review.vm, rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/view.vm
This may have fixed some other issues with Wiki as I updated everything I saw on this search page w.r.t. dark mode.
Some of these components may be better being converted to more standard ones but there's custom logic in this tool for the buttons so that would take more effort than just fixing the dark mode theming.
=> SAK-49881 Wiki Search results do not follow dark mode

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://sakaiproject.atlassian.net/browse/SAK-49910
=> SAK-49910 Gateway: Permission Error in SiteHandler (setting selectedPage)

commons/tool/src/webapp/js/commons.js
Added a focus event to this and also refactored some of the common code here.
=> SAK-47929 Commons: Not able to create new post while using screen reader and keyboard

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-49941
=> SAK-49941 Lessons import will fail if assessment can't be accessed

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-49942
=> SAK-49942 Portal adding or deleting a site should update nav

library/src/skins/default/src/sass/themes/_dark.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageOverview.vm
https://sakaiproject.atlassian.net/browse/SAK-49684
=> SAK-49684 Overview: Some text not clear on darkmode in ‘manage overview’

library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss, library/src/skins/default/src/sass/themes/_dark.scss
https://sakaiproject.atlassian.net/browse/SAK-49849
=> SAK-49849 Test and quizzes: Next and previous buttons on test list does not follow dark mode

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
https://sakaiproject.atlassian.net/browse/SAK-49964
=> SAK-49964 grader. Don't attempt to setup editors during lti launch

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-49968
=> SAK-49968 Assignments student assignment status is empty

kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/EntityManagerComponent.java
https://sakaiproject.atlassian.net/browse/SAK-49975
=> SAK-49975 Kernel prevent EntityManager from adding non loadable entities to unresolvable roots cache

kernel/component-manager/pom.xml, meetings/ui/pom.xml, webcomponents/tool/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-49977
=> SAK-49977 Global mvn clean plugin should remove intermediate files

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-49964
=> SAK-49964 SakaiGrader LTI submission not rendering

library/src/skins/default/src/sass/modules/button/_base.scss, library/src/skins/default/src/sass/modules/tool/button/_base.scss, library/src/skins/default/src/sass/tool.scss, profile2/api/src/java/org/sakaiproject/profile2/logic/ProfileConnectionsLogic.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java, roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_table.handlebars, webapi/src/main/java/org/sakaiproject/webapi/beans/ProfileRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ProfileController.java, webcomponents/bundle/src/main/bundle/profile.properties, webcomponents/tool/src/main/frontend/.gitignore, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/packages/sakai-button/src/SakaiButton.js, webcomponents/tool/src/main/frontend/packages/sakai-element/index.js, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiElement.js, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiShadowElement.js, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/sakai-connection-utils.js, webcomponents/tool/src/main/frontend/packages/sakai-user-photo/src/SakaiUserPhoto.js
https://sakaiproject.atlassian.net/browse/SAK-48362
=> SAK-48362 roster. Add profile connections buttons back

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentButton.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49806
I applied the same logic as used in SakaiRubricStudentPreviewButton.js.
=> SAK-49806 Rubrics: Rubric icon appears to students if rubric is hidden

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49934
=> SAK-49934 Rubrics use actual name in generic tooltips

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
Jira: https://sakaiproject.atlassian.net/browse/SAK-49963
=> SAK-49963 Recent Announcements: Incorrect attribution of highlighting

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Jira [SAK-49864](https://sakaiproject.atlassian.net/browse/SAK-49864)
This approach tries to solve the issue with the info we already have, avoiding DB modifications that could be problematic with old instances.
[SAK-49864]: https://sakaiproject.atlassian.net/browse/SAK-49864?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49864 Messages: On 'Reply to all', include last users that joined the groups to which the mail was sent

commons/tool/src/webapp/WEB-INF/templates/comment.hbs, commons/tool/src/webapp/WEB-INF/templates/post.hbs, library/src/skins/default/src/sass/modules/tool/commons/_commons.scss
https://sakaiproject.atlassian.net/browse/SAK-49993
=> SAK-49993 commons. Improve responsiveness at mobile sizes

library/src/skins/default/src/sass/modules/tool/dashboard/_base.scss, webcomponents/tool/src/main/frontend/packages/sakai-course-dashboard/src/SakaiCourseDashboard.js, webcomponents/tool/src/main/frontend/packages/sakai-course-dashboard/src/SakaiCourseHeader.js, webcomponents/tool/src/main/frontend/packages/sakai-dialog-content/src/SakaiDialogContent.js, webcomponents/tool/src/main/frontend/packages/sakai-home-dashboard/src/SakaiHomeDashboard.js, webcomponents/tool/src/main/frontend/packages/sakai-image-editor/src/SakaiImageEditor.js, webcomponents/tool/src/main/frontend/packages/sakai-tasks/src/SakaiTasks.js, webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiWidgetPanel.js
https://sakaiproject.atlassian.net/browse/SAK-49917
=> SAK-49917 dashboard. Improve responsiveness on small displays

library/src/skins/default/package-lock.json, library/src/skins/default/package.json
https://sakaiproject.atlassian.net/browse/SAK-50001
=> SAK-50001 Library - npm update autoprefixer

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/submission.js
https://sakaiproject.atlassian.net/browse/SAK-49718
=> SAK-49718 grader. Reset the feedback between submissions

lessonbuilder/tool/src/webapp/js/jquery.oembed.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
The Spinner on this Save doesn't work because it's a two-step Save process
=> SAK-49916 Lessons oembed: disable API shorteners and disable spinner

msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgFolderAdd.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-49783
=> SAK-49783 Messages tab headers are inconsistent

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
Just moving it out of the loop, as it was causing this exception:
`java.lang.IllegalStateException: The maximum number of Cell Styles was exceeded. You can define up to 64000 style in a .xlsx Workbook`
=> SAK-49987 Assignments: Submission export breaks on big data set

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-49830
=> SAK-49830 SiteInfo view section membership table not contained inside pop-up

samigo/samigo-app/src/webapp/jsf/author/item/audioRecording.jsp, samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp
These JSP comments are not correct and have effect on the backend
=> SAK-50013 Samigo file upload questions don't keep hidden points config

library/src/webapp/js/portal/portal.init.js, portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalConstants.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-50028
=> SAK-50028 WC Tasks disable My Tasks in the account panel

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-49981
The same issue cited for Topics also affects Forums and seemingly translations back and forth from/to XML.
=> SAK-49981 Forums option for read-only after close date does not import

library/src/skins/default/package-lock.json, library/src/skins/default/package.json
https://sakaiproject.atlassian.net/browse/SAK-50027
=> SAK-50027 Library update Bootstrap-Icons 1.11.3

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Embedded and cross-site resources; extends SAK-48756 changes.
=> SAK-50022 Lessons enhancements for archiving attachments

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
jira: https://sakaiproject.atlassian.net/browse/SAK-50030
=> SAK-50030 Announcements highlighted status not always accurate in Edit view

library/src/webapp/js/sakai-lti-advantage.js
Do any of these need to be at the log level or is it fine to have them lower?
The one on line 32 causes excessive messages in the default "Info" log so that's the biggest thing to either remove or reduce, but the others all seem like debugging messages too.
=> SAK-50060 Reduce excessive messages in console output from sakai-lti-advantage.js

site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js
Fixed error where element wasn't selected after keyboard sort Improved scrolling on a long page
Improved scrolling on a long page
=> SAK-49955 Site Info: Tool reordering UX regressions

library/src/webapp/js/jquery/qtip/tutorial.js
https://sakaiproject.atlassian.net/browse/SAK-49824
=> SAK-49824 Portal tutorial pops up on every page for an admin user, even after being dismissed

master/pom.xml, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/cp/QuestionPoolStatisticsServlet.java
https://sakaiproject.atlassian.net/browse/SAK-50069
=> SAK-50069 Global update spring-web to 5.3.34

webcomponents/bundle/src/main/bundle/grades.properties, webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js, webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiGradesWidget.js
https://sakaiproject.atlassian.net/browse/SAK-50029
=> SAK-50029 WC SakaiGrades obfuscate grades on default page load

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
=> SAK-50064 Samigo navigation in questions tab is missing 

webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
https://sakaiproject.atlassian.net/browse/SAK-50029
=> SAK-50029 WC SakaiGrades handle case where gb assignment has no grades

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
=> SAK-49990 Roster the profile link is unique to current user and cant be part of cache

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-49442
=> SAK-49442 Gradebook input student filter redraw when text has changed

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/api/src/main/java/org/sakaiproject/messaging/api/UserMessagingService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java, kernel/kernel-impl/src/main/resources/usermessagingservice.properties, library/src/skins/default/src/sass/modules/notifications/_notifications.scss, library/src/webapp/js/portal/portal.init.js, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/notifications-snippet.vm, webapi/src/main/java/org/sakaiproject/webapi/controllers/NotificationsController.java, webcomponents/bundle/src/main/bundle/sakai-notifications.properties, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiShadowElement.js, webcomponents/tool/src/main/frontend/packages/sakai-notifications/src/SakaiNotifications.js, webcomponents/tool/src/main/frontend/packages/sakai-notifications/src/states.js, webcomponents/tool/src/main/frontend/packages/sakai-push-utils/src/sakai-push-utils.js
https://sakaiproject.atlassian.net/browse/SAK-50050
=> SAK-50050 Notifications improve the user experience in setting up browser push

samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
I don't really understand this .... CC: @bgarciaentornos
=> SAK-50057 Samigo remove unnecessary dropdown initialization

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49934
=> SAK-49934 Rubrics add rubric and criteria titles to aria-label

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
https://sakaiproject.atlassian.net/browse/SAK-49718
=> SAK-49718 Grader Always reset editor on user switch.

webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
https://sakaiproject.atlassian.net/browse/SAK-50096
=> SAK-50096 WC SakaiGrades external tools grade info is based on data shared with gradebook

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
https://sakaiproject.atlassian.net/browse/SAK-50084
=> SAK-50084 Gradebook grading table and student table has uneven padding for TA

library/src/skins/default/src/sass/themes/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-49984
=> SAK-49984 Library use sass math lib when computing contrast and luminance

library/src/skins/default/src/sass/modules/tool/siteinfo/_siteinfo.scss, site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
Jira: https://sakaiproject.atlassian.net/browse/SAK-50110
With this PR I'm also restyling three buttons in the Date Manager for consistency with the standard style used elsewhere in Sakai.
=> SAK-50110 Site Info: Date Manager UX issues

samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
https://sakaiproject.atlassian.net/browse/SAK-50075
=> SAK-50075 Question Pool: calculated question solution cancel button console error

serviceworker/src/main/webapp/index.html
Feel free to suggest alternate approaches.
=> SAK-50129 - Add index.html to ROOT deployment to redirect to /portal

library/src/skins/default/src/sass/themes/_dark.scss
https://sakaiproject.atlassian.net/browse/SAK-49849
=> SAK-49849 Samigo improve next and previous buttons on test list in dark mode

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
https://sakaiproject.atlassian.net/browse/SAK-50150
=> SAK-50150 Kernel not all streams support mark and reset during tika detection

library/src/skins/default/src/sass/modules/tool/grader/_base.scss, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/submission.js
=> SAK-47897 WC SakaiGrader add previous instructor feedback to new Grader after a resubmission

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-50168
=> SAK-50168 Global upgrade Apache Ignite to 2.16.0

gradebookng/tool/src/webapp/scripts/gradebook-quick-entry.js
=> SAK-50170 Gradebook avoid console error when selecting a gb item in quick entry

library/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-50174
=> SAK-50174 Library support for libsass on arm64 arch

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/IgniteEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-50172
=> SAK-50172 EntityBroker add IgniteCoordinatorNode to cluster info

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Jira [SAK-50066](https://sakaiproject.atlassian.net/browse/SAK-50066)
Two conditions were added to join a group:
- make sure the close date hasn't been reached (if there is) - also to leave the group
- each joinable set can have multiple associated groups, make sure the user doesn't join more than one of them
Their respective alert messages are also included, plus one in case the group stops being joinable
[SAK-50066]: https://sakaiproject.atlassian.net/browse/SAK-50066?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-50008 Site Info: more checks to join/leave a joinable set

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50214
=> SAK-50214 Portal when forming the reset urls should only effect the path of a uri

webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-50178
=> SAK-50178 grader Show feedback and private remove links appropriately

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEvaluationRemover.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGradingButton.js
https://sakaiproject.atlassian.net/issues/SAK-50019
=> SAK-50019 grader Clear rubric comments and scores on clear

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-47016
=> SAK-47016 grader Don't display grade saved message for extensions

webcomponents/tool/src/main/frontend/packages/sakai-course-list/src/SakaiCourseList.js
https://sakaiproject.atlassian.net/browse/SAK-50198
=> SAK-50198 Course List WC Only list terms once in filter

webcomponents/bundle/src/main/bundle/courselist.properties, webcomponents/tool/src/main/frontend/packages/sakai-course-list/src/SakaiCourseList.js
https://sakaiproject.atlassian.net/browse/SAK-50224
=> SAK-50224 courselist wc make site filter options clearer

webapi/src/main/java/org/sakaiproject/webapi/controllers/ForumsController.java, webcomponents/tool/src/main/frontend/packages/sakai-forums/src/SakaiForums.js, webcomponents/tool/src/main/frontend/packages/sakai-forums/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-forums/test/sakai-forums.test.js
https://sakaiproject.atlassian.net/browse/SAK-50223
=> SAK-50223 sakai-forums only show sites with activity

webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-49950
=> SAK-49950 webapi dashboard use nickname in welcome if available

assignment/api/src/resources/assignment.properties, assignment/api/src/resources/assignment_es.properties, assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/GradeReportTest.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
https://sakaiproject.atlassian.net/browse/SAK-50210
=> SAK-50210 Assignments add assignment by columns download (xlsx)

content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
=> SAK-47869 Content file size limit check issue when upload max is greater than upload ceiling

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50017
=> SAK-50017 Rubrics ungraded assignments with rubrics should have blank grades

library/src/skins/default/src/sass/themes/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-50253
=> SAK-50253 Library address sass deprecation warnings

roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-50196
rosters api calls
- get-search-index.json
- get-membership.json cause a race condition when loading data
this change may not be the ideal but it does solve the race condition
=> SAK-50196 Roster prevent race condition during roster loading

library/src/webapp/js/postem-dropzone.js
=> SAK-47914 Postem use the response from the xhr if there actually is one

library/src/webapp/js/postem.js, postem/postem-app/src/main/webapp/WEB-INF/templates/create_gradebook.html
…n that it's only going back one path segment rather than 2
=> SAK-50270 Postem when canceling during an add the path is different

mailsender/tool/src/java/org/sakaiproject/mailsender/tool/controller/MainController.java
…bel and actual recipient list
=> SAK-48048 Mailsender add a space between the message sent to and actual recipient list

mailsender/impl/src/java/org/sakaiproject/mailsender/logic/impl/ComposeLogicImpl.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ComposeLogicImplTest.java, mailsender/impl/src/webapp/WEB-INF/components.xml
…oups to see if the group should be included in the compose list or not
=> SAK-48039 Mailsender consult the settings for displaying empty groups when computing the compose list

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-50216
=> SAK-50216 Samigo TA should only see groups they are a member of

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
Blocking ctrl+alt+del options by default
=> S2U-21 Tests & Quizzes: Add new setting for SEB

kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql, kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql, kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql, samigo/samigo-pack/src/sql/hsqldb/sakai_samigo.sql, samigo/samigo-pack/src/sql/mysql/sakai_samigo.sql, samigo/samigo-pack/src/sql/oracle/sakai_samigo.sql
fix the typo in the sql scripts
=> SAK-50234 Admin home: typo in link on home page

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGradingComment.js
https://sakaiproject.atlassian.net/browse/SAK-50010
=> SAK-50010 rubrics Update comment textarea on switching criterion

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://sakaiproject.atlassian.net/browse/SAK-49676
Adds new sakai property
site.setup.publish.default = auto | scheduled | manual
changes default from auto to manual
=> SAK-49676 site-mange add config to specify default site publish type

lessonbuilder/tool/src/webapp/templates/index.html
This is a smoker fix - No one ever went to these links.  But smoker reported them as broken.
=> SAK-47925 Lessons - Fix broken (404) links at /lessonbuilder-tool/templates

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, basiclti/docs/POSTMESSAGE.md, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-constants.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
At this point the work is still under construction.
=> SAK-46953 Assignment/LTI Push notification from LTI tool on grade change

webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-date-picker/package.json, webcomponents/tool/src/main/frontend/packages/sakai-date-picker/src/SakaiDatePicker.js
https://sakaiproject.atlassian.net/browse/SAK-50306
=> SAK-50306 sakai-date-picker Fix timezone in temporal instant call

calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarEvent.java, calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarEventEdit.java, calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarImporterService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/DailyRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericImportRowHandler.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/MWFRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/MWRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/MonthlyRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/SMTWRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/SMWRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/STTRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/TThRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/WeeklyRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/YearlyRecurrenceRule.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/CSVReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/OutlookReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/Reader.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionTest.java
https://sakaiproject.atlassian.net/browse/SAK-50276
=> SAK-50276 Calendar support importing/merging all day events (ics)

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
This is a separate JIRA to avoid merge conflicts.
=> SAK-50329 - LTI-Assignments: Add push notification when grading, so the SakaiGrader gets updated comments

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionStatusBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
…e inconsistent results) or the max (what it was in an earlier commit, but folks thought was a bit extreme)
=> SAK-50254 Samigo setting default page size to min of 20

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48557
=> SAK-48557 Gradebook Extra credit items do not display in course grade

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java
https://sakaiproject.atlassian.net/browse/SAK-50349
=> SAK-50349 SAMIGO Error when print PDF Report if the feedback contains global variables: Unknown character : '@' (or 64)

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-50354
=> SAK-50354 Upgrading jsoup version 1.18.1

samigo/samigo-app/src/webapp/jsf/questionpool/previewQuestion.jsp
https://sakaiproject.atlassian.net/browse/SAK-50355
An example. Left: Before. Right: Later
=> SAK-50355 Complete question types when previewing on question pool

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionOutcomeTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RatingTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java
https://sakaiproject.atlassian.net/browse/SAK-50311
=> SAK-50311 Rubrics api rubrics list should avoid processing nulls

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-50321
=> SAK-50321 Samigo calculated question rounding error for answer key

library/src/skins/default/src/sass/modules/tool/_table.scss, library/src/skins/default/src/sass/modules/tool/chat/_chat.scss, library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
Fixed the responsiveness of Assignment and Chatroom tools using media queries in mobile view.
=> SAK-50358 Responsiveness of Assignment and Chatroom tools

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/tsugi-util/src/java/org/tsugi/basiclti/BasicLTIConstants.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java
https://sakaiproject.atlassian.net/browse/SAK-50336
=> SAK-50336 LTI send institutional id as the lis_person_sourcedid

deploy/pom.xml, help/help-component/pom.xml, help/pom.xml, master/pom.xml, microsoft-integration/impl/pom.xml, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/SakaiProxyImpl.java, microsoft-integration/pom.xml, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/QuestionElasticSearchIndexBuilder.java, search/README.md, search/elasticsearch/impl/pom.xml, search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/serialization/NodeStatsResponseFactory.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/NodeStatsResponseFactoryTest.java, search/elasticsearch/pom.xml, search/elasticsearch/util/pom.xml, search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/BaseElasticSearchIndexBuilder.java, search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java, search/search-api/api/src/java/org/sakaiproject/search/api/SearchIndexBuilder.java, search/search-api/api/src/java/org/sakaiproject/search/api/SearchService.java, search/search-api/api/src/java/org/sakaiproject/search/api/SearchStatus.java, search/search-tool/tool/src/java/org/sakaiproject/search/tool/SearchAdminBeanImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50371
=> SAK-50371 Search upgrade to opensearch 2 and lucene 9

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlDefault.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
https://sakaiproject.atlassian.net/browse/SAK-50375
=> SAK-50375 Content calculate collection sizes by collection type

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java
https://sakaiproject.atlassian.net/browse/SAK-50350
=> SAK-50350 Samigo Feedback should be interpreted when printing PDF report from a submission with global variables on feedback

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionAddGlobalVariableListener.java
https://sakaiproject.atlassian.net/browse/SAK-50322
=> SAK-50322 Test & Quizzes: Unique names are not checked when creating global variables manually

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-50279
=> SAK-50279 Samigo TA should only see assessments assignt to all site or assessment from the groups which does belong to

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java
https://sakaiproject.atlassian.net/browse/SAK-45772
=> SAK-45722 Samigo placing duplicated variables in calculated question (formula placeholders) breaks other placeholder

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/util/TotalScoresExportBean.java
https://sakaiproject.atlassian.net/browse/SAK-50393
=> SAK-50393 Samigo student scores are not rounded when exporting

portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-50401
=> SAK-50401 Portal using DA to visit site should appear in recent sites list

postem/postem-app/src/main/webapp/WEB-INF/templates/index.html, postem/postem-app/src/main/webapp/WEB-INF/templates/student_grade_view.html
Fixed the table responsiveness of the Postem tool. Wrapped the table in an inbuilt boostrap class table-responsive.
=> SAK-50379 PostEm improve ui responsiveness

roster2/tool/src/webapp/js/roster.js, webcomponents/tool/src/main/frontend/bundle-entry-points/base.js
https://sakaiproject.atlassian.net/browse/SAK-50376
=> SAK-50376 roster Build imagesLoaded into base esbuild bundle

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/PDFExportService.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/CSVReaderTest.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/PDFExportServiceTest.java, calendar/calendar-util/util/src/java/org/sakaiproject/util/CalendarUtil.java, calendar/calendar-util/util/src/test/org/sakaiproject/util/CalendarUtilTest.java
https://sakaiproject.atlassian.net/browse/SAK-50418
=> SAK-50418 Calendar unit tests attempt to load CM when using ResourceLoader

assignment/tool/pom.xml, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarConstants.java, calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarService.java, calendar/calendar-impl/impl/pom.xml, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java, calendar/calendar-impl/impl/src/webapp/WEB-INF/components.xml, calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/CalendarBean.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventDetails.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventSummary.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-util/util/src/java/org/sakaiproject/util/CalendarUtil.java, kernel/api/src/main/java/org/sakaiproject/time/api/TimeService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/serialize/impl/conversion/ConversionTimeService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java, webapi/src/main/java/org/sakaiproject/webapi/beans/CalendarEventRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/CalendarController.java, webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/SakaiAnnouncements.js, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js
https://sakaiproject.atlassian.net/browse/SAK-46272
=> SAK-46272 calendar wc make calendar widget display all events

basiclti/basiclti-portlet/src/webapp/WEB-INF/applicationContext.xml, plus/provider/src/main/webapp/WEB-INF/applicationContext.xml
Needed to provide a minimal applicationContext.xml for plus and the basiclti-portlet.
=> SAK-50423 LTI (External Tool) and Plus are not starting up

samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
https://sakaiproject.atlassian.net/browse/SAK-50425
=> SAK-50425 Samigo: Error on console when enabled CKEditor (S2U-22 ticket)

library/pom.xml, library/src/skins/default/src/sass/base/_extendables.scss, library/src/webapp/js/headscripts.js
I think this gets all the spots that were mentioned.
=> SAK-50387 Resources upload file anmiation does not follow dark theme

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ReorderProducer.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-50420
=> SAK-50420 Lessons rich text question prompt distorts reorder view

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/LessonConditionUtil.java
https://sakaiproject.atlassian.net/browse/SAK-50341
=> SAK-50341 Missing condition picker when editing a text on a subpage

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-50429
I just included everything LTI related inside the existing "if", as otherwise it won't work for regular assignments. Please take a look and let me know if this is the way it should go, thanks!
=> SAK-50429 SakaiGrader not loading for non LTI assignments

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, conditions/impl/src/java/org/sakaiproject/condition/impl/evaluator/AssignmentConditionEvaluator.java
https://sakaiproject.atlassian.net/browse/SAK-50432
isParsable method fails for grade like: 7,70
=> SAK-50432 Assignment conditions doesn't work on Spanish language

mailsender/tool/src/webapp/content/css/MailSender.css, mailsender/tool/src/webapp/content/templates/compose.html
Fixed the alignment of elements in Email tool in mobile view.
=> SAK-50434 mailsender improve ui responsiveness

lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-50419
=> SAK-50419 Lessons Change File dialog not appearing

calendar/calendar-bundles/resources/calendar.properties, library/src/skins/default/src/sass/_defaults.scss, library/src/skins/default/src/sass/themes/_dark.scss, library/src/skins/default/src/sass/themes/_light.scss, webapi/src/main/java/org/sakaiproject/webapi/controllers/CalendarController.java, webcomponents/bundle/src/main/bundle/calendar-wc.properties, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/calendar-styles.js, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiShadowElement.js, webcomponents/tool/src/main/frontend/packages/sakai-pageable-element/src/SakaiPageableElement.js, webcomponents/tool/src/main/frontend/packages/sakai-site-picker/src/SakaiSitePicker.js
https://sakaiproject.atlassian.net/browse/SAK-50436
=> SAK-50436 calendarwc improve colour coding of events

webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/SakaiAnnouncements.js, webcomponents/tool/src/main/frontend/packages/sakai-pageable-element/src/SakaiPageableElement.js
https://sakaiproject.atlassian.net/browse/SAK-50442
=> SAK-50442 announcementswc set visible flag on initial load

samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoAvailableNotificationServiceImpl.java
address a bug found by Andrea during testing
=> SAK-50380 Samigo solve availabile mail sending for groups

library/src/skins/default/src/sass/tool.scss, library/src/skins/default/src/sass/webcomponents/permissions/_permissions.scss, webcomponents/tool/src/main/frontend/packages/sakai-permissions/src/SakaiPermissions.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/test/sakai-permissions.test.js
https://sakaiproject.atlassian.net/browse/SAK-50053
=> SAK-50053 WC permissions responsive ui improvements

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ExportAction.java
https://sakaiproject.atlassian.net/browse/SAK-50479
=> SAK-50479 Tests & Quizzes: Submission report error with global variables

signup/tool/src/webapp/signup/attendee/signupMeeting.jsp, signup/tool/src/webapp/signup/signupMeetings.jsp
=> SAK-50381 Signup improve ui responsiveness

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
When there are a large number of assignments in a site, it becomes tedious to search for a specific one. Having a search function by title is quite useful.
=> SAK-50477 Assignments add search box in the assignments list view

library/src/skins/default/src/sass/modules/tool/sitemanage/_sitemanage.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm, velocity/tool/src/templates/VM_chef_library.vm
https://sakaiproject.atlassian.net/browse/SAK-50396
=> SAK-50396 sitemanage improve ui responsiveness of manage participants tab

calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm
https://sakaiproject.atlassian.net/browse/SAK-50398
=> SAK-50398 calendar Line up required star and field label

roster2/tool/src/handlebars/members_container_table.handlebars
https://sakaiproject.atlassian.net/browse/SAK-50410
=> SAK-50410 roster improve ui responsiveness in list view table

rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/info.vm
https://sakaiproject.atlassian.net/browse/SAK-50405
=> SAK-50405 rwiki improve ui responsiveness in info tables

basiclti/basiclti-tool/src/webapp/vm/lti_tool_edit.vm, basiclti/basiclti-tool/src/webapp/vm/lti_tool_site_insert.vm
This is just a small follow-on commit
=> SAK-50378 LTI Improve form markup

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-49907
=> SAK-49907 Assignments non-electronic show feedback and grade once returned

webcomponents/bundle/src/main/bundle/calendar-wc.properties, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/calendar-styles.js, webcomponents/tool/src/main/frontend/packages/sakai-calendar/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiCalendarWidget.js
https://sakaiproject.atlassian.net/browse/SAK-50346
=> SAK-50346 calendarwc Show today's events by default

webcomponents/tool/src/main/frontend/packages/sakai-forums/src/SakaiForums.js, webcomponents/tool/src/main/frontend/packages/sakai-tasks/src/SakaiTasks.js
https://sakaiproject.atlassian.net/browse/SAK-46660
=> SAK-46660 dicussionswc Hide site title when in the course dashboard

webapi/src/main/java/org/sakaiproject/webapi/beans/ConversationsRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js
https://sakaiproject.atlassian.net/browse/SAK-50497
=> SAK-50497 conversations Honour search.enable Sakai property

kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepositoryImpl.java, kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTests.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/repository/PinnedSiteRepository.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/repository/RecentSiteRepository.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/PinnedSiteRepositoryImpl.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/RecentSiteRepositoryImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-50503
=> SAK-50503 Portal remove sites user no longer has access to during login

webcomponents/bundle/src/main/bundle/sakai-notifications.properties, webcomponents/tool/src/main/frontend/packages/sakai-notifications/src/SakaiNotifications.js
https://sakaiproject.atlassian.net/browse/SAK-50508
=> SAK-50508 notificationswc added test notifications clear button

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50503
=> SAK-50503 Portal remove sites user no longer has access to during login, part 2

roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/java/org/sakaiproject/roster/tool/RosterTool.java, roster2/tool/src/webapp/WEB-INF/bootstrap.jsp, roster2/tool/src/webapp/js/roster.js, webapi/src/main/java/org/sakaiproject/webapi/beans/ProfileRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ProfileController.java, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js
https://sakaiproject.atlassian.net/browse/SAK-50501
=> SAK-50501 Roster improve consistency of property profile2.connections.enabled

library/src/skins/default/src/sass/modules/tool/sitestats/_sitestats.scss
There was an issue with the "Activity" widget being left-aligned while the rest were center-aligned which is now fixed.
=> SAK-50456 Sitestats improve ui responsiveness

roster2/tool/src/webapp/js/roster.js, webcomponents/tool/src/main/frontend/packages/sakai-user-photo/src/SakaiUserPhoto.js
https://sakaiproject.atlassian.net/browse/SAK-50114
=> SAK-50114 roster Only display one profile popup at a time

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50530
=> SAK-50530 Roster check for installed profile tool when getting link

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
Made the Grade Report page in the Assignments tool responsive by using the "table-responsive" bootstrap class.
=> SAK-50510 Assignments improve ui responsiveness on grade report view

.gitignore
See https://sakaiproject.atlassian.net/browse/SAK-50453 to learn how to debug on Visual Studio Code
=> SAK-50453 library ignore visual studio dir .vscode

content/content-tool/tool/src/java/org/sakaiproject/content/tool/CopyrightDelegate.java
https://sakaiproject.atlassian.net/browse/SAK-50539
=> SAK-50539 Content copyright selections are not updating

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-50533
=> SAK-50533 Portal don't repin unpinned or recents on login

roster2/tool/src/webapp/js/card-game/card-game.js
User Interface does not match the interface outlined [here](https://sakaiproject.atlassian.net/browse/S2U-42). There are two ‘checks’ buttons instead of one. Button is also inactive during the duration of the game.
https://sakaiproject.atlassian.net/browse/SAK-50067
=> SAK-50067 Roster card game displays an extra check button

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
In the Jira [SAK-49998: Assignments: Improve performance and UX of Assignments by student view](https://sakaiproject.atlassian.net/browse/SAK-49998,) the visual interface of the 'Assignments by Student' view was improved. 
When a user is collapsed or expanded, as well as when returning from the Sakai Grader or the classic Grader, the student who was interacted with is centered on the screen. With many assignments and students, it might be better to have a visual effect that helps the instructor easily identify the student.
https://sakaiproject.atlassian.net/browse/SAK-50552
=> SAK-50552 Assignments: Improving Visual Navigation in 'Assignments by Student' View

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/timeout.vm
https://sakaiproject.atlassian.net/browse/SAK-49885
=> SAK-49885 Portal Add Border to the timeout alert dialog

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-46688
Leads to a 404 when clicked
=> SAK-46688 SakaiGrader instructors attachment feedback filename contains unreserved marks

search/elasticsearch/util/pom.xml, search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/BaseElasticSearchIndexBuilder.java, sitestats/sitestats-impl-hib/pom.xml, sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/DetailedEventImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50590
=> SAK-50590 SiteStats exception when persisting an eventRef longer than 512 chars

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-50594
=> SAK-50594 Portal users may still have favorites data that is influencing pinned sites

samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/previewPool.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/subpoolsTreeTable.jsp
https://sakaiproject.atlassian.net/browse/SAK-50570
=> SAK-50570 Samigo visual inconsistencies in option menus when sharing a QP

sitestats/sitestats-tool/src/webapp/html/components/useractivity/EventRefDetailsButtonPanel.html
Jira: https://sakaiproject.atlassian.net/browse/SAK-50602
=> SAK-50602 Statistics: Show more button missing bootstrap styling

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-50617
=> SAK-50617 Gradebook Cannot read properties of undefined (reading 'replace')

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-50617
=> SAK-50617 Gradebook - Cannot read properties of undefined (reading 'replace')

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.html, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
https://sakaiproject.atlassian.net/browse/SAK-50608
=> SAK-50608 Gradebook Tabulator comment textarea is small size

library/src/skins/default/src/sass/modules/tool/sitestats/_sitestats.scss
=> SAK-50582 Sitestats show more button does not have a keyboard focus indicator on statistics tool

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-50617
=> SAK-50617 Cannot read properties of undefined (reading 'replace')

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java, samigo/samigo-app/src/webapp/css/print/print.css, samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
=> SAK-47738 Samigo improve print contrast and layout

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-50606
=> SAK-50606 Gradebook Tabulator can't read property reinitializeWidth

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
https://sakaiproject.atlassian.net/browse/SAK-50607
=> SAK-50607 Gradebook Tabulator error on console when adding Item

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-48995
=> SAK-48995 Lessons Page Settings Not Retained on Import from Site

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriterionRatingEdit.js
=> SAK-50561 Rubric rating title not updating after save

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-50660
=> SAK-50660 SakaiGrader fails to save grade when using peer review with feedback attachment

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java, gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-50651
=> SAK-50651 Gradebook tabulator exiting student review mode blurs the entire site for instructor

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
https://sakaiproject.atlassian.net/browse/SAK-50652
=> SAK-50652 Gradebook tabulator creating new GB item background issue

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
Jira: https://sakaiproject.atlassian.net/browse/SAK-50655
The second part of the screencast attached to the jira demonstrates the proposed solution in this PR (albeit in a local instance of 23.x).
=> SAK-50655 Recent Announcements in Home Overview with mismatched columns

webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js
…ot yet be loaded on initial render
=> SAK-50525 Calendar promise may not have finished loading i18n data

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-50548
=> SAK-50548 Assignments: New count and Status for feedback attachments

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50676
=> SAK-50676 Portal more sites not displaying course site types

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
=> SAK-50683 Samigo displaced cells in Excel exported from test with random questions

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalConstants.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm, webcomponents/tool/src/main/frontend/packages/sakai-picture-changer/src/SakaiPictureChanger.js
=> SAK-43335 Portal use profileImageService to get cache-busting profile images

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50687
=> SAK-50687 Grader: Launch instructor/evaluator attachments in new tab

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonsAccess.java, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
Inject ConditionService in LessonAccess
https://sakaiproject.atlassian.net/browse/SAK-50704
=> SAK-50704 Gradebook: Nullpointer on ConditionService

webcomponents/tool/src/main/java/org/sakaiproject/webcomponents/permissions/PermissionsEntityProvider.java
I haven't tested this much. Just first working draft.
Maybe it would be nice to look for permissions in the parent folder to display (if no custom realm exists for the site)?
=> SAK-50642 Content fix folder permission editing

kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml, kernel/kernel-impl/src/main/resources/antisamy/low-security-policy.xml
https://sakaiproject.atlassian.net/browse/SAK-50710
=> SAK-50710 Antisamy: Whitelist css background-size property

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/AbstractSiteViewImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50701
=> SAK-50701 Portal more sites is not rendering for admins

lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-50303
=> SAK-50303 Lessons exclude due date for linked assignment

calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_view.vm
@hornersa i noticed 3 GET requests on startup. once i got rid of the three identical requests, the error went away
=> SAK-50711 Calendar json console error on startup

library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Removed max-width so that it fits the page and width is adjusted accordingly.
=> SAK-50663 Lessons checklist item width

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/js/forum.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
Get rid of custom More dropdowns and use bootstrap.
=> SAK-50693 Discussions use bootstrap for dropdowns instead of custom JS

portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalSubPageNavProvider.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/UserController.java
modified:   portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalSubPageNavProvider.java
modified:   webapi/src/main/java/org/sakaiproject/webapi/controllers/UserController.java
=> NOJIRA Checking licenses

webcomponents/tool/src/main/frontend/packages/sakai-element/src/global-styles.js
=> SAK-50741 Webcomponents fix Chrome warning import rules are not allowed here

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, library/src/skins/default/src/sass/modules/tool/resources/_resources.scss, library/src/skins/default/src/sass/themes/_dark.scss
Jira: https://sakaiproject.atlassian.net/browse/SAK-50289
=> SAK-50289 Drop Box fix alignment for UI controls

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
This will compile but not work properly or be testable until the JIRA known as 50720 is merged.
=> SAK-50745 Site navigation improve the fidelity of archive/merge

common/archive-impl/impl2/src/webapp/WEB-INF/components.xml, polls/api/src/java/org/sakaiproject/poll/util/PollUtil.java, polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
This will **not function** until the JIRA known as 50720 is merged.  For now it is draft to demonstrate how to improve archive support for a service.
=> SAK-50744 Polls improve suport for archive/merge

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java, lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java
This also fixes an NPE in Lessons when a tool is deleted or no longer accessible.
=> SAK-50758 LTI Stealthed Tools When removed should be gone

msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-50774
Before
After
=> SAK-50774 Messages: Wrong Display inline style on Settings tab

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-50755
=> SAK-50755 Test & Quizzes: Last Modified and Modified Date should not be modified when importing from site

gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
I tried other methods but nothing worked consistently, Using the timeout was the only way this was working consitently.
=> SAK-50735 Gradebook student summary print option doesn't display any data

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java, lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java
The first commit broke lessons import with LTI tools.  This fix fixes that fix.
=> SAK-50758 Lessons LTI - Fix regression introduced in CC Import

roster2/tool/src/webapp/js/roster.js, webcomponents/tool/src/main/frontend/packages/sakai-user-photo/src/SakaiUserPhoto.js
implemented per https://getbootstrap.com/docs/5.2/components/popovers/#dismiss-on-next-click
=> SAK-50114 Webcomponents dismiss profile photo per Bootstrap recommendation

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js
https://sakaiproject.atlassian.net/browse/SAK-50766
=> SAK-50766 conversations Pass topic reference as external id when grading

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-50810
=> SAK-50810 Assignment in peer review attachmentRefList maybe null

webapi/src/main/java/org/sakaiproject/webapi/beans/DashboardRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webcomponents/tool/src/main/frontend/packages/sakai-course-dashboard/src/SakaiCourseDashboard.js
https://sakaiproject.atlassian.net/browse/SAK-50515
=> SAK-50515 dashboard Retain widgets between layout changes

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java, conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-49219
=> SAK-49219 conversations Lock topics after due date if no late date

plus/api/src/main/java/org/sakaiproject/plus/api/model/Score.java
https://sakaiproject.atlassian.net/browse/SAK-50829
Fixed script:
https://github.com/sakaiproject/sakai-reference/commit/808e42014c05f98f2fa2a4a6c487b74c676685d5#diff-9bb1b6c052ea982f7428e7d185c7f7675d26f2b67654bf48934fc8371b89bf9eR184
=> SAK-50829 ORACLE: COMMENT is a reserved word

kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
https://sakaiproject.atlassian.net/browse/SAK-50832
=> SAK-50832 ORACLE: NOW is not accepted

lessonbuilder/components/src/ddl/oracle/simplepage.sql
https://sakaiproject.atlassian.net/browse/SAK-50833
=> SAK-50833 ORACLE: Column NULL cannot modify to NULL

content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
=> SAK-50818 Content improve alignment in Availability and Access

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
https://sakaiproject.atlassian.net/browse/SAK-50824
=> SAK-50824 Calendar select correct instance of recurring event

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
when user is missing rubrics.editor permission, the entire site import fails
=> SAK-50844 Samigo use a SecurityAdvisor to avoid Site Import failures

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
https://sakaiproject.atlassian.net/browse/SAK-50847
=> SAK-50847 Kernel add SA when creating rolview user

lti/lti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java
https://sakaiproject.atlassian.net/browse/SAK-50860
=> SAK-50860 ORACLE: Error GROUP BY. Not possible to create sites, also error when clicking on Manage Tools

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon_ca.properties, config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon_es.properties
https://sakaiproject.atlassian.net/browse/SAK-50866
=> SAK-50866 i18n resources email text when uploading

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiAddTopic.js
=> SAK-50861 Conversations fix retrieval of posts because of null grading id

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
Important fix for Lessons sub-nav
=> SAK-50874 Lessons when querying against sakaiId it must be done as a String

assignment/tool/src/webapp/js/assignmentsByStudent.js
https://sakaiproject.atlassian.net/browse/SAK-50879
Before:
After:
=> SAK-50879 Assignment: Restore profile photo in Assignments by Student

samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50880
=> SAK-50880 Improve site import performence using item level caching

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-50875
=> SAK-50875 Assignments students must complete all self-report criterions

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
https://sakaiproject.atlassian.net/browse/SAK-50877
=> SAK-50877 Kernel resources site import will not update links pointing to files that exist on the target site

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Reverts sakaiproject/sakai#13198
=> Revert "SAK-50802 Lessons multiple imports create duplicate Lessons links on navigation"

lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java
A small omission from the recent PR.
=> SAK-50820 Assignments / LTI Hide sakai_tool_checksum from UI

samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-48816
Before:
After:
=> SAK-48816 SAMIGO: No bar is present for incorrect answers and The bar present for correct answer is purple in color rather than green

library/src/webapp/js/portal/portal.init.js
https://sakaiproject.atlassian.net/browse/SAK-50893
=> SAK-50893 Portal during site creation console error finding account panel

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-50895
=> SAK-50895 Portal footer links config changed

samigo/samigo-app/src/webapp/jsf/questionpool/checkSolutionCalculatedQuestion.jsp
https://sakaiproject.atlassian.net/browse/SAK-50901
=> SAK-50901 Samigo - Icons are missing on Solution on Calculated Question on Question pools

samigo/samigo-app/src/webapp/jsf/questionpool/solution.jsp
https://sakaiproject.atlassian.net/browse/SAK-50902
Before
After
=> SAK-50902 Samigo - Bad style on question box on Solution on Calculated Question on Question pools

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://sakaiproject.atlassian.net/browse/SAK-50911
Before:
After:
Same style as on Total Scores tab
=> SAK-50911 Samigo improve style on questions tab

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://sakaiproject.atlassian.net/browse/SAK-50911
=> SAK-50911 Samigo - Fixing style on Questions tab

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
SAK-50925 Assignment: When reviewing an assignment, two asn.review.assignment events are created
https://sakaiproject.atlassian.net/browse/SAK-50925
=> SAK-50925 Assignment reviewing an assignment generates two asn.review.assignment events

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
https://sakaiproject.atlassian.net/browse/SAK-50932
=> SAK-50932 Assignment error when downloading spreadsheet on Assignment by Student tab

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-50933
=> SAK-50933 Assignment visible date should show a default date vs dd/mm/aaa

library/src/skins/default/src/sass/base/_defaults.scss
Jira: https://sakaiproject.atlassian.net/browse/SAK-50913
Refer to the screencast (SAK-50913-ProposedFix-20250128.mp4) attached to the jira for how the proposed PR looks in light and dark mode.
=> SAK-50913 Library disabled selected checkbox appears blank

portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-impl/impl/src/bundle/sitenav_es.properties
https://sakaiproject.atlassian.net/browse/SAK-50080
Leaving it as a draft until the right wording is confirmed
=> SAK-50080 Portal display a user's current role in site

library/src/webapp/js/portal/portal.init.js
https://sakaiproject.atlassian.net/browse/SAK-50937
=> SAK-50937 Notifications: Closing the notification panel causes an error in the console

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.java
https://sakaiproject.atlassian.net/browse/SAK-50948
=> SAK-50948 Profile - Personal summary is not persisted

lti/lti-portlet/src/bundle/basiclti.properties, lti/lti-portlet/src/bundle/basiclti_es.properties, lti/lti-portlet/src/java/org/sakaiproject/portlets/IMSLTIPortlet.java
https://sakaiproject.atlassian.net/browse/SAK-50103
=> SAK-50103 LTI add i18n translation for 'Launch' text

samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-edit.test.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubrics.test.js
https://sakaiproject.atlassian.net/browse/SAK-49816
=> SAK-49816 rubrics Remove new flag after initial rubric title save

lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
The lack of an if check was a mistake in the first commit - easy fix
=> SAK-47782 CC+Archive import fix NPE w.r.t. transversalMap

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
https://sakaiproject.atlassian.net/browse/SAK-50959
=> SAK-50959 site-manage project site creation resulting in a TypeError for autosection-dates

lti/lti-portlet/src/java/org/sakaiproject/portlets/IMSLTIPortlet.java
https://sakaiproject.atlassian.net/browse/SAK-50103
=> SAK-50103 'Launch' text is hardcoded on LTI

site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java
https://sakaiproject.atlassian.net/browse/SAK-50974
=> SAK-50974 SiteInfo add non official participants parse account

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html
Jira: https://sakaiproject.atlassian.net/browse/SAK-50967
=> SAK-50967 Gradebook: Finish import button needs spinner

samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-50986
=> SAK-50986 samigo: accessibility issues found with aXe

profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java, roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_photogrid.handlebars, roster2/tool/src/handlebars/members_table.handlebars, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiShadowElement.js, webcomponents/tool/src/main/frontend/packages/sakai-element/src/global-styles.js, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js, webcomponents/tool/src/main/frontend/packages/sakai-tasks/src/SakaiTasks.js, webcomponents/tool/src/main/frontend/packages/sakai-user-photo/src/SakaiUserPhoto.js, webcomponents/tool/src/main/frontend/packages/sakai-user-photo/test/sakai-user-photo.test.js
https://sakaiproject.atlassian.net/browse/SAK-50873
=> SAK-50873 sakai-user-photo Supply siteId to profile endpoint

webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/SakaiAnnouncements.js, webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/sakai-announcements-constants.js, webcomponents/tool/src/main/frontend/packages/sakai-announcements/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-announcements/test/i18n.js, webcomponents/tool/src/main/frontend/packages/sakai-announcements/test/sakai-announcements.test.js, webcomponents/tool/src/main/frontend/packages/sakai-pageable-element/src/SakaiPageableElement.js
https://sakaiproject.atlassian.net/browse/SAK-50996
=> SAK-50996 announcementswc Add instructor order sort option

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm
=> SAK-51001 Assignments clean up student view of assignment with bootstrap

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/webapp/jsf/print/preview_item/CalculatedQuestion.jsp
=> SAK-51012 Samigo add calculated answer values when printing an assessment

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java
=> SAK-50963 Rubrics icon not displaying for peer review items

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, library/src/skins/default/src/sass/modules/tool/signup/_signup.scss, signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java, signup/impl/src/java/org/sakaiproject/signup/logic/SignupCalendarHelperImpl.java, signup/impl/src/java/org/sakaiproject/signup/logic/SignupMeetingServiceImpl.java, signup/tool/src/java/org/sakaiproject/signup/tool/entityproviders/EventProcessHandler.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/attendee/AttendeeSignupMBean.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/AddAttendee.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/CreateMeetings.java, signup/tool/src/webapp/signup/newMeeting/step2.jsp
There are lots of small changes and cleanup in here.
The core functionality change is the helper method for commitEvent
=> SAK-51031 Signup need to commitEvent after opening a CalendarEventEdit

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51035
=> SAK-51035 Portal incorrect menu on gateway when setting property gatewaySiteList

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
Jira: https://sakaiproject.atlassian.net/browse/SAK-51029
Refer to the jira's attached screenshots, ProposedFix-CategoriesCase-20250220.png and ProposedFix-NoCategoriesCase-20250220.png.
=> SAK-51029 Gradebook: Expected icons missing from grade summary

library/src/skins/default/src/sass/modules/more-sites/_more-sites.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
https://sakaiproject.atlassian.net/browse/SAK-51023
=> SAK-51023 Portal more sites long site names should overflow outside the box

sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/PreferencesBean.java
SAK-51008 SECTION INFO: Change the default value from 50 to 20 in the tab Student Memberships
https://sakaiproject.atlassian.net/browse/SAK-51008
=> SAK-51008 Sections change the default students to show to 20 in student memberships tab

library/src/skins/default/src/sass/modules/tool/roster/_roster.scss, roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_table.handlebars
https://sakaiproject.atlassian.net/browse/SAK-51025
=> SAK-51025 Roster - Disaster pop-up functionality on photos

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseSitePublishService.java, edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseSiteRemovalService.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSitePublishServiceImpl.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSiteRemovalServiceImpl.java, jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSitePublishJob.java, jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSiteRemovalJob.java, jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
This job is run via Job Scheduler as an admin user. This idea of a permission to publish or unpublish doesn't make sense.
=> SAK-51041 EduServices remove course_site_publish_service.publish permission from realms

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
https://sakaiproject.atlassian.net/browse/SAK-51013
Fixing this setting it like it was before https://github.com/sakaiproject/sakai/pull/12977
=> SAK-51013 Samigo print option doesn't work inside a test

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
SAK-51059 Assignments: Incorrect sorting by Descending Submitted Date - ORACLE?
https://sakaiproject.atlassian.net/browse/SAK-51059
=> SAK-51059 Assignments: Incorrect sorting by Descending Submitted Date - ORACLE?

library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, library/src/skins/default/src/sass/themes/_dark.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm
https://sakaiproject.atlassian.net/browse/SAK-50930
Before
After
=> SAK-50930 Powered image is missing since Trinity

samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
https://sakaiproject.atlassian.net/browse/SAK-51058
=> SAK-51058 T&Q: Spinner on the SEB launch button

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/webapp/jsp/compose.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/scheduler/PrivateMessageSchedulerServiceImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
=> SAK-48573 Messages send delayed message to email if requested

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestFormatHelper.java
=> SAK-49994 Gradebook fix quick entry in ES locale

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
This is adapted from a PR from @kunaljaykam 
https://github.com/sakaiproject/sakai/pull/13223
=> SAK-50802 Lessons avoid performing import if there is no content

calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/CSVReaderTest.java
https://sakaiproject.atlassian.net/browse/SAK-51084
=> SAK-51084 CALENDAR: Some errors on CalendarImpl Tests (Spanish)

sitestats/sitestats-bundle/src/resources/Messages.properties, sitestats/sitestats-bundle/src/resources/Messages_es.properties, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/LastJobRun.java, sitestats/sitestats-tool/src/webapp/html/components/LastJobRun.html
https://sakaiproject.atlassian.net/browse/SAK-51083
=> SAK-51083 SITESTATS: 'Information about last update' text is hardcoded

rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages_es.properties
https://sakaiproject.atlassian.net/browse/SAK-51082
Also changed on Transifex
=> SAK-51082 Wiki: Last modified by and Date info is missing on Spanish

.github/workflows/maven.yml, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestFormatHelper.java
=> SAK-51087 Gradebook fix failing tests in ES locale

CLAUDE.md
https://docs.anthropic.com/en/docs/agents-and-tools/claude-code/overview
=> NOJIRA Guide for Claude Code

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
23.x only as the permissions have been removed in trunk
=> SAK-50541 Profile 23.x only change permission check

sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ActivityWidget.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/LessonsWidget.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ResourcesWidget.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/VisitsWidget.java
This bug fix was done entirely by an LLM named Claude Code.
=> SAK-50823 SiteStats fix error from wicket9 upgrade

sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/AjaxLazyLoadImage.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/WidgetTabs.java
https://sakaiproject.atlassian.net/browse/SAK-51096
With setSelectedTab(selectedTab, true); width returns 60 and all images are preloading...
=> SAK-51096 Sitestats - First tab is not loading by ajax when clicking  Show more'

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50530
=> SAK-50530 Roster noisy log message about creating profile tool link

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
=> SAK-50627 Gradebook ordering symbol is missing direction

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriteria.js
=> SAK-51131 Rubrics allow user to delete the existing weight and replace it

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriteria.js
=> SAK-49820 Rubrics Weighted rubrics missing total percentage, points

library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, library/src/skins/default/src/sass/themes/_dark.scss, library/src/skins/default/src/sass/themes/_light.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-51139
=> SAK-51139 Portal: move the Sakai logo to CSS

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-51152
=> SAK-51152 Portal: Home should be always at the top on the menu

library/src/skins/default/src/sass/modules/tool/profile2/_profile2.scss
https://sakaiproject.atlassian.net/browse/SAK-51148
=> SAK-51148 Portal: Wrong style on toolBalItem on Profile

library/src/skins/default/src/sass/modules/tool/commons/_commons.scss, library/src/skins/default/src/sass/modules/tool/syllabus/_syllabus.scss
https://sakaiproject.atlassian.net/browse/SAK-51155
=> SAK-51155 Portal: Wrong style on toolBalItem on Syllabus and Commons

library/src/skins/default/package-lock.json, library/src/skins/default/package.json, master/pom.xml
@kunaljaykam this may reduce library build time by 40%+
=> SAK-51163 Library update SASS

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm
https://sakaiproject.atlassian.net/browse/SAK-51164
=> SAK-51164 Portal: Enter Student View - serious aXe issue

content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm, library/src/skins/default/src/sass/modules/tool/resources/_resources.scss
Updated nav-item list to match current portal nav styles
=> SAK-51160 Content improve file picker attachment modal and nav-item design

calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/PrefsBean.java, common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/BaseContentReviewService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, kernel/api/src/main/java/org/sakaiproject/user/api/PreferencesService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BasePreferencesService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/user/impl/BasePreferencesServiceTest.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/SiteEmailPreferenceSetterImpl.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/UserLocaleSetterImpl.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
https://sakaiproject.atlassian.net/browse/SAK-50897
=> SAK-50897 Kernel add preferences auto commit for db locks

vuecomponents/tool/src/main/frontend/src/components/condition-picker.vue
@jesusmmp can you please test it?
=> SAK-50462 Lesson remove html tags from condition-picker dropdown

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-51149
=> SAK-51149 Portal-Navigation: When loading a different tool in the same site, the navigation has to rearrange itself a couple of times

microsoft-integration/collaborative-documents/src/main/webapp/WEB-INF/templates/permissions.html, microsoft-integration/media-gallery-tool/src/main/webapp/WEB-INF/templates/permissions.html, podcasts/podcasts-app/src/webapp/podcasts/podPermissions.jsp, webcomponents/bundle/src/main/bundle/permissions-wc.properties, webcomponents/tool/src/main/frontend/packages/sakai-permissions/README.md, webcomponents/tool/src/main/frontend/packages/sakai-permissions/src/SakaiPermissions.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/test/i18n.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/test/sakai-permissions.test.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/web-test-runner.config.mjs, webcomponents/tool/src/main/frontend/packages/sakai-profile/README.md, webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js
https://sakaiproject.atlassian.net/browse/SAK-51173
Added some unit tests for the permissions web component
=> SAK-51173 Permissions move rest provision to webapi

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
https://sakaiproject.atlassian.net/browse/SAK-47419
=> SAK-47419 Assignments add option to or not to integrate with gradebook

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, samigo/samigo-app/src/webapp/js/authoring.js
=> SAK-51189 Gradebook category selector fix and matchingUserGradebookItem cache removal

.well-known/funding-manifest-urls
FLOSS Fund grant opportunity: https://floss.fund/ 
https://floss.fund/funding-manifest/
=> NOJIRA: Create funding-manifest-urls

webapi/src/main/java/org/sakaiproject/webapi/exception/GlobalExceptionHandler.java
https://sakaiproject.atlassian.net/browse/SAK-51185
=> SAK-51185 permissionswc Allow explicit exceptions through global handler

master/pom.xml
=> SAK-51094 LTI Update io.jsonwebtoken version to 0.11.5

assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java, kernel/api/src/main/java/org/sakaiproject/serialization/BasicSerializableRepository.java, kernel/api/src/main/java/org/sakaiproject/serialization/MapperFactory.java, kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepositoryImpl.java, kernel/api/src/test/java/org/sakaiproject/serialization/MapperFactoryTests.java, kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml, kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTestConfiguration.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsTestConfiguration.java
https://sakaiproject.atlassian.net/browse/SAK-51188
=> SAK-51188 Kernel move MapperFactory to a builder style ObjectMapper

library/src/skins/default/src/sass/print.scss
https://sakaiproject.atlassian.net/browse/SAK-51203
=> SAK-51203 Lessons hide active user count, current role, and portal header breadcrumb when printing

lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-51197
=> SAK-51197 Lessons: breadcrumb missing 'parent' for subpages

lessonbuilder/tool/src/webapp/templates/ShowPage.html, library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
https://sakaiproject.atlassian.net/browse/SAK-51214
=> SAK-51214 Lessons: align lessons options menu and body

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
https://sakaiproject.atlassian.net/browse/SAK-51178
=> SAK-51178 Discussion Topic: console error for GB

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
@jonespm wrote a very long Jira many years ago. In 2025, Gemini Pro 2.5 had no problem taking the Jira description and fixing the bug
=> SAK-29774 Entitybroker fix paging with users

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-50947
=> SAK-50947 Assignments reviewer names should be visible to instructors in peer review

sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/PresenceConsolidationTest.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
https://sakaiproject.atlassian.net/browse/SAK-51200
=> SAK-51200 Sitestats time zone error in unit tests

webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiGradesWidget.js
https://sakaiproject.atlassian.net/browse/SAK-51245
=> SAK-51245 Dashboard: grades not showing anything

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradeTableData.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
I think this is related to the wicket version upgrade, fixing it for the custom export filter too.
Also adding a verification for other filter selection.
=> SAK-51229 Gradebook - Error when Set Score for Empty Cells

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51240
=> SAK-51240 conversations Set anonymous on merging topics

webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/reactions-and-upvoting-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-51259
=> SAK-51259 conversations Fix upvote link addition on server

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50596
=> SAK-50596 conversations Check react perm while supplying link

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiComment.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js
https://sakaiproject.atlassian.net/browse/SAK-47143
=> SAK-47143 conversations use btn-icon for kebab menus

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java, conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-51222
=> SAK-51222 conversations import CC topics as draft

webapi/src/main/java/org/sakaiproject/webapi/controllers/AbstractSakaiApiController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/CalendarController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/EntityController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/EventsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ForumsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/LessonsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/LoginController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/PermissionsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ProfileController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SearchController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SecureDeliveryController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SiteEntityController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SitesController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/TagsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/UserController.java, webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/SakaiAnnouncements.js, webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js, webcomponents/tool/src/main/frontend/packages/sakai-forums/src/SakaiForums.js, webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js, webcomponents/tool/src/main/frontend/packages/sakai-widgets/src/SakaiGradesWidget.js
https://sakaiproject.atlassian.net/browse/SAK-51201
=> SAK-51201 webapi calendar load pinned sites in selector

gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/AbstractGradeRecord.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradingEvent.java
https://sakaiproject.atlassian.net/browse/SAK-51267
=> SAK-51267 Gradebook oracle requires a sequence for database generated IDs

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/permissions/permissions_include.jsp
https://sakaiproject.atlassian.net/browse/SAK-51233
=> SAK-51233 msgcntr gradebookGroupEnabled avoid using jsp script expression

webcomponents/tool/src/main/frontend/packages/sakai-pageable-element/src/SakaiPageableElement.js, webcomponents/tool/src/main/frontend/packages/sakai-pager/src/SakaiPager.js
https://sakaiproject.atlassian.net/browse/SAK-51246
=> SAK-51246 Dashboard style widget pagination and hide when not used

gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/Comment.java
https://sakaiproject.atlassian.net/browse/SAK-51283
=> SAK-51283 Gradebook - ORACLE - ORA-00001: restriccion unica (SAKAI_UPGRADE.SYS_C00813796) violada

webcomponents/tool/src/main/frontend/packages/sakai-permissions/src/SakaiPermissions.js
https://sakaiproject.atlassian.net/browse/SAK-51273
=> SAK-51273 permissionswc Narrow perm column and allow text breaking

search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java, search/elasticsearch/impl/src/webapp/WEB-INF/components.xml, search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java, search/search-api/api/src/java/org/sakaiproject/search/api/SearchConstants.java, search/search-api/api/src/java/org/sakaiproject/search/api/SearchService.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webcomponents/tool/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-51299
=> SAK-51299 conversations Only add search button if enabled for site

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java, conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-51235
=> SAK-51235 conversations Transfer dates in archive/merge

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, library/pom.xml, webcomponents/tool/src/main/frontend/packages/sakai-document-viewer/src/SakaiDocumentViewer.js
https://sakaiproject.atlassian.net/browse/SAK-51294
=> SAK-51294 Library upgrade pdf-js from 4.0.269 to v5.1.91

chat/chat-tool/tool/src/webapp/js/chatscript.js, chat/chat-tool/tool/src/webapp/jsp/roomMonitor.jspf
- Replaced old avatar spans with modern web component, updated dynamic message creation, and fixed user photo rendering
=> SAK-51296 Chat Replace chatUserAvatar with sakai-user-photo web component

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html
- Updated grid system to use Bootstrap 5 classes 
- Added proper row containers for grid layout 
- Changed offset classes to work on all screen sizes including mobile 
- Fixed column widths to use standard 12-column system
=> SAK-51293 Gradebook Fix grid layout for grade release settings

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AjaxBootstrapTabbedPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AjaxBootstrapTabbedPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html, library/src/skins/default/src/sass/modules/tool/_menu.scss, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss, library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-grades.css
**assisted by claude**
fixes screenshots:
-navbar now looks like rest of the portal
- 
- create gradebook item modal now looks like jira modal for create another item, before it was just `+`
=> SAK-51333 Gradebook improve wicket modal styles for navbar and buttons

assignment/impl/src/java/org/sakaiproject/assignment/impl/EmailUtil.java, assignment/impl/src/webapp/WEB-INF/components.xml, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java, content/content-types/src/java/org/sakaiproject/content/types/FolderType.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-util/pom.xml, kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java, kernel/kernel-util/src/test/java/org/sakaiproject/util/ZipContentUtilTest.java
https://sakaiproject.atlassian.net/browse/SAK-51067
=> SAK-51067 Kernel after creating zip file avoid loading it into memory

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51325
=> SAK-51325 Gradebook noisy logging when checking or adding external assignment

library/src/webapp/js/mathjax-config.js
https://sakaiproject.atlassian.net/browse/SAK-51351
=> SAK-51351 Samigo MathJax configuration does not load in exams accessed via URL

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
https://sakaiproject.atlassian.net/browse/SAK-51341
=> SAK-51341 Samigo groups not available for selection

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/templates/ShowPage.html
…V file (#13360)"
This reverts commit d803860152385de9d393ec97f1c46031bd1b4b19.
=> SAK-51063 Lessons fix unnecessary automatic downloading of WAV file

webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-tasks/src/SakaiTasks.js
https://sakaiproject.atlassian.net/browse/SAK-51371
=> SAK-51371 tasks Fix import of lion-dialog

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
https://sakaiproject.atlassian.net/browse/SAK-51205
=> SAK-51205 Assignments new assignment pre select send grades to gradebook

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
Some functions were added because they were removed on the multi gradebook feature
Rendered condition change
=> SAK-51328 msgcntr lesson embed condition and gradebook item change

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://sakaiproject.atlassian.net/browse/SAK-51377
=> SAK-51377 Gradebook: Globe icon is missing when sending gradebook item from external tool

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/sakai-rubrics-utils.js
https://sakaiproject.atlassian.net/browse/SAK-51329
=> SAK-51329 Rubric Preview text is hardcoded

roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_photogrid.handlebars, roster2/tool/src/handlebars/members_table.handlebars
https://sakaiproject.atlassian.net/browse/SAK-51288
=> SAK-51288 Roster: The tooltip is not visible when hovering the mouse over the photos.

search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
https://sakaiproject.atlassian.net/browse/SAK-51299
=> SAK-51299 conversations Only show search button if enabled for site

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/bundle/src/main/bundle/grades.properties, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js, webcomponents/tool/src/main/frontend/packages/sakai-grades/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-grades/test/sakai-grades.test.js
https://sakaiproject.atlassian.net/browse/SAK-51343
=> SAK-51343 gradeswc Check grade visibility with external providers

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
https://sakaiproject.atlassian.net/browse/SAK-51383
=> SAK-51383 Resources: Site import will not update links to files in folders with spaces in their name

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js
https://sakaiproject.atlassian.net/browse/SAK-51401
=> SAK-51401 conversations Default to empty string for grade comment

conversations/impl/src/test/org/sakaiproject/conversations/impl/ConversationsServiceTests.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/topic.test.js
https://sakaiproject.atlassian.net/browse/SAK-51404
=> SAK-51404 conversations Display youngest posts first by default

webapi/src/main/java/org/sakaiproject/webapi/beans/ConversationsRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiAddTopic.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js
https://sakaiproject.atlassian.net/browse/SAK-51396
=> SAK-51396 conversations Only render grade stuff if user has permission

lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-51397
=> SAK-51397 Lessons console error reading print all button

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePortalHeaderBreadcrumb.vm
https://sakaiproject.atlassian.net/browse/SAK-51230
=> SAK-51230 Portal add Manage Overview link after breadcrumb

kernel/api/src/main/java/org/sakaiproject/messaging/api/UserMessagingService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/messaging-components.xml, kernel/kernel-impl/src/test/java/org/sakaiproject/messaging/impl/RuntimeRegistrationTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/messaging/impl/UserMessagingServiceTestConfiguration.java, kernel/kernel-impl/src/test/java/org/sakaiproject/messaging/impl/UserMessagingServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-51399
=> SAK-51399 Kernel thread safety improvements to UserMessagingService

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/post.test.js
https://sakaiproject.atlassian.net/browse/SAK-51407
=> SAK-51407 conversations Add cancel button to grading dropdown

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiPost.js
https://sakaiproject.atlassian.net/browse/SAK-51406
=> SAK-51406 conversations Retain grade when setting comment

velocity/tool/src/templates/permissions.vm, webcomponents/tool/src/main/frontend/packages/sakai-permissions/README.md, webcomponents/tool/src/main/frontend/packages/sakai-permissions/src/SakaiPermissions.js, webcomponents/tool/src/main/frontend/packages/sakai-permissions/test/sakai-permissions.test.js
https://sakaiproject.atlassian.net/browse/SAK-51302
=> SAK-51302 permissionswc Display groups unless explicitly disabled

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp
https://sakaiproject.atlassian.net/browse/SAK-51416
=> SAK-51416 Samigo improve instructions ui for numeric repsonse

assignment/tool/src/webapp/js/studentViewSubmission.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_estimate.vm
https://sakaiproject.atlassian.net/browse/SAK-51424
=> SAK-51424 Assignments timesheet access datepicker fields by name

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js
[SAK-45968: Lessons / three column layout spacing issue](https://sakaiproject.atlassian.net/browse/SAK-45968)
=> SAK-45968 Lessons three column layout remove redundant lastcol logic

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionFormulaBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionFormulaValidatorListener.java, samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
https://sakaiproject.atlassian.net/browse/SAK-51411
=> SAK-51411 Samigo calculated questions allow formula verification and generate new example solutions

assignment/api/src/resources/assignment.properties, assignment/api/src/resources/assignment_es.properties, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-51402
=> SAK-51402 Assignments non-electronic use info text for the message

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ReturnedEvaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/EvaluationRepository.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/repository/ReturnedEvaluationRepository.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/EvaluationRepositoryImpl.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/repository/ReturnedEvaluationRepositoryImpl.java
=> SAK-50199 Rubrics removal of a site doesn't purge rubrics data

kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
https://sakaiproject.atlassian.net/browse/SAK-50082
=> SAK-50082 Kernel users can unjoin sites that are joinable

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiItemDelete.js
https://sakaiproject.atlassian.net/browse/SAK-51447
Rubric
Criterion
=> SAK-51447 Rubrics remove button missing rubric and criterion title

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_estimate.vm
https://sakaiproject.atlassian.net/browse/SAK-51432
=> SAK-51432 Assignments timesheet improve work log modal ui

sitestats/sitestats-tool/src/webapp/html/pages/ReportsEditPage.html
Removed silk icons. Added screenshot in the JIRA: https://sakaiproject.atlassian.net/browse/SAK-51266.
=> SAK-51266 Sitestats add sakai icons for new report

samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://sakaiproject.atlassian.net/browse/SAK-48805
=> SAK-48805 Tests & Quizzes: Missing rubric icon in assessment builder

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
https://sakaiproject.atlassian.net/browse/SAK-51452
=> SAK-51452 Gradebook - Extra credit icon is missing when grade comes from another tool

samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://sakaiproject.atlassian.net/browse/SAK-48861
=> SAK-48861 Rubrics-Tests & Quizzes: Clicking the grading rubric tab displays the rubric below the response

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java, sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
https://sakaiproject.atlassian.net/browse/SAK-51453
=> SAK-51453 sitestats Default to always collecting stats

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-grading.test.js
https://sakaiproject.atlassian.net/browse/SAK-51374
=> SAK-51374 rubrics Rubric grading can now display percentage scores

scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/console/components/ContentPackageDetailPanel.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/console/pages/ConsoleBasePage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/console/pages/PackageConfigurationPage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/console/pages/PackageRemovePage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/reporting/components/LearnerDetailsPanel.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/reporting/pages/BaseResultsPage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/reporting/pages/LearnerResultsPage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/reporting/pages/ResultsListPage.html, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/upload/UploadPage.html, scormplayer/wicket-tool/src/java/org/sakaiproject/wicket/ajax/markup/html/table/SakaiPagingNavigator.html, scormplayer/wicket-tool/src/java/org/sakaiproject/wicket/markup/html/repeater/data/table/ActionPanel.html
Jira: https://sakaiproject.atlassian.net/browse/SAK-51481
I've attached six sets of screenshots to the jira, each referenced in the test plan. Those with file names {X}-Expected.png were taken from a local instance of 26.x with code from this proposed PR. Those with file names {X}-Currently.png are taken currently from 26.x on nightly.
=> SAK-51481 scorm update player to use bootstrap

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MenuBuilder.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-import.vm, site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteConstants.java
https://sakaiproject.atlassian.net/browse/SAK-51469
=> SAK-51469 Site Info Import from site clean tool template error

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51372
=> SAK-51372 gradebook add convertStringToDouble to api

library/src/skins/default/src/sass/modules/tool/conversations/_conversations.scss, webapi/src/main/java/org/sakaiproject/webapi/beans/ConversationsRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/ConversationsController.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/conversations.test.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/data.js
https://sakaiproject.atlassian.net/issues/SAK-51474
=> SAK-51474 conversations Add statistics button

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentEntity.java, kernel/api/src/main/java/org/sakaiproject/entity/api/Entity.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java, samigo/samigo-api/src/java/org/sakaiproject/samigo/api/SamigoReferenceReckoner.java, samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoAssessmentHandler.java, samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
https://sakaiproject.atlassian.net/browse/SAK-51444
=> SAK-51444 gradeswc Check for groups in ungraded calculation

rubrics/api/src/main/bundle/rubrics.properties, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriteria.js
https://sakaiproject.atlassian.net/browse/SAK-51436
=> SAK-51436 rubrics fix disabling of Save Weights button

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-51461
=> SAK-51461 Samigo instructor can not see tests released to groups

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
https://sakaiproject.atlassian.net/browse/SAK-51446
=> SAK-51446 Samigo event sam.assessment.saveitem has a null in reference /sam/null/saved

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
https://sakaiproject.atlassian.net/browse/SAK-51441
=> SAK-51441 Samigo preview icon rubric is missing when Take the test from the Lessons page (CKEditor option)

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentServiceConstants.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java, samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/entity/impl/CoreAssessmentEntityProviderImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/entity/impl/PublishedAssessmentEntityProviderImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/tool/src/main/frontend/packages/sakai-grades/src/SakaiGrades.js
https://sakaiproject.atlassian.net/browse/SAK-51443
=> SAK-51443 gradeswc Only show student type role data

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://sakaiproject.atlassian.net/browse/SAK-51388
=> SAK-51388 Samigo numeric response not processing ranges with spaces

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java
https://sakaiproject.atlassian.net/browse/SAK-51493
=> SAK-51493 Samigo add due date and late submission validation

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-51500
=> SAK-51500 Lessons Cancelling on some windows when adding content displays a console error

lessonbuilder/tool/src/webapp/js/peer-eval.js, lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-51356
=> SAK-51356 Lessons - Rubric criteria are not added from editing student pages

webcomponents/tool/src/main/frontend/packages/sakai-profile/src/SakaiProfile.js
https://sakaiproject.atlassian.net/browse/SAK-51340
=> SAK-51340 profilewc Break user name so it wraps

user/user-tool-prefs/tool/src/webapp/prefs/noti.jsp
https://sakaiproject.atlassian.net/browse/SAK-51498
=> SAK-51498 User jsp syntax for delete image onclick attribute invalid in tag outputText

roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-48187
=> SAK-48187 roster Show no participants in all views after search

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionOutcomeTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RatingTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java, webcomponents/tool/src/main/frontend/packages/sakai-element/src/SakaiElement.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsSharedList.js
https://sakaiproject.atlassian.net/browse/SAK-51514
=> SAK-51514 rubrics Remove null fields from the json downloads

webcomponents/tool/src/main/frontend/packages/sakai-calendar/src/SakaiCalendar.js
https://sakaiproject.atlassian.net/browse/SAK-50604
=> SAK-50604 Dashboard calendar widget shouldn't render invalid links

library/src/skins/default/src/sass/modules/tool/roster/_roster.scss, roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-51247
=> SAK-51247 roster Show spinner graphic on loading users

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Fixed order of entry of values in csv columns.
=> SAK-50351 Gradebook Custom export with no GB items results in extra columns, data in wrong columns

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetResultsCalculatedListener.java, samigo/samigo-app/src/webapp/jsf/author/allHeadings.jsp, samigo/samigo-app/src/webapp/jsf/author/editAssessmentHeadings.jsp, samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp, samigo/samigo-app/src/webapp/jsf/author/restoreAssessmentsHeading.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/evaluationHeadings.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp, samigo/samigo-app/src/webapp/jsf/event/eventLogHeadings.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/questionpoolHeadings.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp, samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivityHeadings.jsp, samigo/samigo-app/src/webapp/jsf/template/templateHeadings.jsp
https://sakaiproject.atlassian.net/browse/SAK-51482
=> SAK-51482 Samigo: Total Scores correct, incorrect and empty counts not displaying for incorrect and empty

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages_es.properties, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-51504
=> SAK-51504 Samigo: Formatting of the new Answer column on the Total Scores page

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://github.com/jesusmmp/sakai/pull/new/SAK-51527
=> SAK-51527 Portal portal.bullhorns.enabled property missing from config

roster2/tool/src/handlebars/enrollment_status.handlebars, roster2/tool/src/handlebars/overview.handlebars, roster2/tool/src/webapp/WEB-INF/bootstrap.jsp, roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-51247
=> SAK-51247 roster Add loading spinner as header renders

roster2/tool/src/webapp/WEB-INF/bootstrap.jsp
https://sakaiproject.atlassian.net/browse/SAK-51529
=> SAK-51529 Roster 404 not found profile2-profile-entity.css

microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51525
=> SAK-51525 Microsoft Integration Settings Modal not loading inside a meeting (updateOnlineMeeting)

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversationsTagManager.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/tag-manager.test.js
dont rely on client-side management of tags -> just submit them to server, let server return a properly-sorted array, display the tags in server-returned order.
=> SAK-51502 Conversations tag sorting improvements

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://sakaiproject.atlassian.net/browse/SAK-24982
=> SAK-24982 msgcntr Moderate and Require users to post before reading does not show student their pending post

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingPersistenceManager.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/repository/GradebookAssignmentRepository.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingPersistenceManagerImpl.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/repository/GradebookAssignmentRepositoryImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51531
=> SAK-51531 Gradebook performance issues when a student click on Gradebook to view the grades

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiConversations.js
https://sakaiproject.atlassian.net/browse/SAK-51548
=> SAK-51548 Conversations avoid duplicate statistics rendering

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventRegistryServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51547
=> SAK-51547 Sitestats thread safe version when rebuilding anonymous tool event ids

webcomponents/tool/src/main/frontend/packages/sakai-notifications/src/SakaiNotifications.js
https://sakaiproject.atlassian.net/browse/SAK-51526
I can't test this on my local instance and our Sakai 25 instance is down right now...
=> SAK-51526 Portal push is not enabled message should not be shown if the push notifications are disabled

kernel/api/src/main/java/org/sakaiproject/emailtemplateservice/api/model/EmailTemplate.java
https://sakaiproject.atlassian.net/browse/SAK-51574
=> SAK-51574 ORACLE - EmailTemplate sequence has a wrong name

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.html
=> SAK-51565 Gradebook accessibility improvements

webcomponents/tool/src/main/frontend/packages/sakai-conversations/src/SakaiTopic.js, webcomponents/tool/src/main/frontend/packages/sakai-conversations/test/topic.test.js
https://sakaiproject.atlassian.net/browse/SAK-51588
=> SAK-51588 Conversations sakai-topic test race condition

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageOverview.vm
https://sakaiproject.atlassian.net/browse/SAK-51600
=> SAK-51600 Manage Overview Missing icons on Unavailable Widgets

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderAccessService.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-50993
=> SAK-50993 Lessons file access as a function of hiding resources

gradebookng/impl/src/test/java/org/sakaiproject/grading/impl/test/GradingServiceTests.java, gradebookng/tool/pom.xml, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestFormatHelper.java
https://sakaiproject.atlassian.net/browse/SAK-51618
=> SAK-51618 Gradebook improve FormatHelper tests

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionOutcomeTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/CriterionTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/EvaluationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RatingTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/RubricTransferBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
https://sakaiproject.atlassian.net/browse/SAK-51519
=> SAK-51519 Rubrics patch requests have missing fields

roster2/tool/src/webapp/js/roster.js
=> SAK-51568 Roster only permission that matters for card game is view all members

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/sakai-rubrics-utils.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-association.test.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-grading.test.js
https://sakaiproject.atlassian.net/browse/SAK-51612
=> SAK-51612 Rubrics wc update to grade as percentage calculation

library/src/skins/default/src/sass/modules/tool/roster/_roster.scss, roster2/tool/src/handlebars/members_cards.handlebars, roster2/tool/src/handlebars/members_photogrid.handlebars, roster2/tool/src/handlebars/members_table.handlebars, roster2/tool/src/java/org/sakaiproject/roster/api/RosterMember.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java, roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-51537
=> SAK-51537 roster Add wrap tag after comma in sort name

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://sakaiproject.atlassian.net/browse/SAK-51592
=> SAK-51592 Lessons student content rubric rows not displaying in the order created

kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java
https://sakaiproject.atlassian.net/browse/SAK-51648
=> SAK-51648 Need spacing between from and subject on the log info when sending an email

vuecomponents/tool/src/main/frontend/src/api/dynamic-rubrics-api.js
https://sakaiproject.atlassian.net/browse/SAK-51599
=> SAK-51599 Dynamic Rubrics Error on console when clicking an assessment submission

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://sakaiproject.atlassian.net/browse/SAK-51647
=> SAK-51647 Lessons - Problem migrating links in Lessonbuilder java.lang.NullPointerException - ORACLE

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
https://sakaiproject.atlassian.net/browse/SAK-51610
=> SAK-51610 Samigo SEB exit password validation is to strict

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
https://sakaiproject.atlassian.net/browse/SAK-51657
=> SAK-51657 Assignments submitted date should not be null in resubmission check

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
https://sakaiproject.atlassian.net/browse/SAK-51672
=> SAK-51672 Gradebook Import back button incorrect cast to previous view

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/RecentSiteRepositoryImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51575
=> SAK-51575 Portal batch delete reuses query on each iteration

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
https://sakaiproject.atlassian.net/browse/SAK-51658
=> SAK-51658 Fixing some icons on Discussions / Messages

library/src/skins/default/src/sass/modules/tool/grader/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-51689
=> SAK-51689 Assignment self-report Rubric does not display inline in the grader

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-51694
=> SAK-51694 SakaiGrader instructor sees extension ui instead of resubmission ui

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51657
=> SAK-51657 Assignments student can't submit a resubmission

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-51673
The proposed PR produces bootstrap accordions that match those used in the Settings tab. The following screenshot demonstrates this:
=> SAK-51673 Gradebook: Use bootstrap accordions for import process

samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
https://sakaiproject.atlassian.net/browse/SAK-51633
=> SAK-51633 Samigo export statistics button should not be visible to the students 

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-51681
=> SAK-51681 LTI add site navigation placement for tools - update sakai.properties

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
https://sakaiproject.atlassian.net/browse/SAK-51610
=> SAK-51610 Tests & Quizzes - SEB: Remove unnecessary text formatting from password

roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java, roster2/tool/src/webapp/js/roster.js
https://sakaiproject.atlassian.net/browse/SAK-33907
=> SAK-33907 roster Allow search by student eid

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
https://sakaiproject.atlassian.net/browse/SAK-51713
=> SAK-51713 Samigo instructors should see all student submissions when a assessment is published to the entire site

site-manage/datemanager/impl/src/main/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51722
=> SAK-51722 Date Manager cannot update gradebook item with gradebook by groups enabled

webcomponents/tool/src/main/frontend/packages/sakai-search/src/SakaiSearch.js
https://sakaiproject.atlassian.net/browse/SAK-51737
=> SAK-51737 portal search Improve no results message appearance

library/src/webapp/editor/ckextraplugins/sakaipreview/plugin.js
https://sakaiproject.atlassian.net/browse/SAK-51734
=> SAK-51734 CK Editor The Preview option no longer opens in a modal

site-manage/datemanager/tool/src/main/resources/static/js/initDatePicker.js
https://sakaiproject.atlassian.net/browse/SAK-51728
=> SAK-51728 DateManager is not shifting dates

library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss
=> SAK-51750 Samigo student can't record an answer for audio response question

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
https://sakaiproject.atlassian.net/browse/SAK-51749
=> SAK-51749 Samigo new assesment should set default grading option to none

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-51409
=> SAK-51409 Assignments view by Student should only include the groups which the TA belongs to

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
https://sakaiproject.atlassian.net/browse/SAK-51410
=> SAK-51410 Assignments On Grade Report the selector should only include the groups which the TA belongs to

site-manage/datemanager/impl/src/main/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51748
=> SAK-51748 DateManager use proper read vs edit messages

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-51741
=> SAK-51741 Uncaught TypeError: Cannot read properties of null (reading 'closest')

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/webapp/js/show-page.js
https://sakaiproject.atlassian.net/browse/SAK-51770
=> SAK-51770 Lessons - Date release page on the following date (the page will be listed with the release date)

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-51803
=> SAK-51803 Scorm - Missing properties on default.sakai.properties

library/src/skins/default/src/sass/modules/tool/portal/_portal.scss
https://sakaiproject.atlassian.net/browse/SAK-51804
=> SAK-51804 Portal Manage Overview does not follow the defined header text color
