archive/archive-tool/tool/src/java/org/sakaiproject/archive/tool/DownloadServlet.java
archive/archive-tool/tool/src/webapp/vm/archive/chef_archive-download.vm

The download links were POST requests, this switches them to GETs and drops the broken jQuery. Also added some handling of errors.

SAK-30646 Fix download links in Site Export

---

samigo/samigo-app/src/webapp/css/tool_sam.css
samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp

Make sure the honor pledge is better formatted when the pledge
is long and wraps to multiple lines by ensuring the checkbox is
always to the left and the text is to the right of that checkbox.

SAM-3126 Improve the Honor Pledge formatting

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/demo.sakai.properties
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutoRun.java
site-manage/site-manage-impl/pack/src/webapp/WEB-INF/components.xml

This allows us to have the demo mode have some random sites and content created automatically at startup when in demo mode. Normal startups don’t run this job, but if you want to have it run at startup you can just set the property:
quartz.seedsites.autorun=true

SAK-32124 Run the seed sites and users job automatically

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
kernel/component-manager/src/main/java/org/sakaiproject/component/api/ServerConfigurationService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/BasicConfigurationService.java
kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockServerConfigurationService.java
sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeServerConfigurationService.java
web/web-portlet/src/java/org/sakaiproject/portlets/PortletIFrame.java

When editing the Site URL in Site Information Display the URL is made relative if it's pointing to the current host. This change also adds support for a set of aliases that the current service is know as.
Having host relative URLs makes is much easier to move the content to a test server and have all the links work.

SAK-31931 Make URLs relative in Overview (Site Information Display)

---

reference/webjars/ckeditor-autosave/pom.xml
reference/webjars/ckeditor-wordcount/pom.xml

This locks down the maven plugin version that would generate errors
like:
[WARNING] Some problems were encountered while building the effective model for org.sakaiproject.webjars:ckeditor-wordcount:jar:4897cb23a9f2ca7fb6b792add4350fb9e2a1722c
[WARNING] 'version' contains an expression but should be a constant.  @ org.sakaiproject.webjars:ckeditor-wordcount:${ckeditor.wordcount.version}, /home/travis/build/sakaiproject/sakai/reference/webjars/ckeditor-wordcount/pom.xml, line 15, column 14
[WARNING] 'build.plugins.plugin.version' for org.sonatype.plugins:nexus-staging-maven-plugin is missing. @ org.sakaiproject.webjars:ckeditor-wordcount:${ckeditor.wordcount.version}, /home/travis/build/sakaiproject/sakai/reference/webjars/ckeditor-wordcount/pom.xml, line 68, column 21

Fix maven build warning in webjars.

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm

By default, the title of a course site is not editable.
In SAK-29823 we enforced the titleNotEditable property in all scenarios,
including initial site creation, so that instructors could not change
the title of a course site. This assumed that a roster would always be
chosen for the course site and the title would be taken from the
roster. This lead to problems when the "Continue with no roster" feature
was enabled (it is off by default), so in SAK-31261 changes were made to
address that problem which essentially reverted SAK-29823, allowing
instructors to change course site titles during site creation.
This patch attempts to address both uses cases above. If a course site
is using a roster, the title will not be editable. If an instructor
chooses to "Continue with no roster", a site …

SAK-32137: Instructors can change course site title during initial creation even if choosing a roster

---

portal/pom.xml
portal/portal-impl/impl/pom.xml
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/BasePortalHandler.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
portal/portal-impl/impl/src/test/org/sakaiproject/portal/charon/handlers/SiteHandlerTest.java

Some characters get longer when they become lowercased and this was causing the portal code to incorrectly inline the tool. In severe cases this would cause an out of bounds exception.
In other cases the returned page would contain multiple closing body tags.
The refactor here makes it possible to write a unit test for the code without having to mock large parts of the request.

SAK-32131 Fix issue with lowercase growing string.

---

config/configuration/bundles/pom.xml

I couldn’t find a nice way to have a default value with the old plugin so I’ve switch to this one. It’s also a little bit faster.

SAK-31502 Don’t fail build when no .git folder

---

reference/library/src/morpheus-master/sass/modules/_toolmenu.scss

See this for the problem: 
After fix:
For more info and images following tests see the Jira.

SAK-31824 Fix issue with hover over titles with collapsed menu.

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-32155
Since the MariaDB driver is used for MySQL connections by default now, we should include the driver configuration in default.sakai.properties.
I've added this line to the MySQL database configuration section:
`driverClassName@javax.sql.BaseDataSource=org.mariadb.jdbc.Driver`
Should we remove the MySQL driver line? Or just leave it in there commented out?

SAK-32155 Include MariaDB driver property in default.sakai.properties

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/empty.js
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java

Delivers #3842.
This ensure that:
1) one version jQuery is loaded into any GradebookNG page
2) the bootstrap widgets are paired with the version of jQuery that Wicket also relies on
3) bootstrap is no longer loaded twice on GradebookNG pages (widgets were sometimes initialized twice)

3842 Force gradebookng to use sakai's preferred version of jQuery and Bootstrap

---

kernel/deploy/shared/pom.xml
master/pom.xml

The upgrade of ical4j to version 2 depends on commons-collection4 so we also need that in the shared classloader. It can co-exist with older commons-collections as all it’s classes are in a different package.

SAK-32163 Add commons-collection4 to tomcat/lib

---

lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/MnemeEntity.java
lessonbuilder/tool/opt-src/test/org/sakaiproject/lessonbuildertool/service/MnemeEntityTest.java
lessonbuilder/tool/pom.xml

In the database we have mneme references of /dummy which are causing the page to blow up. We should stop the /dummy references from appearing but it should also not be the case that these cause the page to blow up.

LSNBLDR-780 Don’t fail to parse bad mneme references.

---

portal/portal-charon/charon/src/webapp/WEB-INF/web.xml
webservices/cxf/src/webapp/WEB-INF/web.xml

Having a tools listener (to register Sakai tools) without any tool registration results in needless warnings in the logs.

SAK-32182 Remove redundant ToolListeners

---

master/pom.xml

If you attempt todo `mvn validate` against an empty repository it will fail because inter project dependencies aren't yet installed in the local repository and so can't be found. Moving the circular dependencies check to later in the builds means we can keep doing it but not break the validate phase.

SAK-32185 Circular dependencies check later in build

---

reference/library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_tables.scss
reference/library/src/morpheus-master/sass/base/_bootstrap-defaults.scss

And this… makes tools like announcements and assignments look terrible. Before and After

SAK-32144 bootstrap 3 applies a nowrap to table cell content 

---

basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SimpleEncryptionTest.java

Sometimes even with a bad key decryption will work, so we well as checking for an exception we also check that we didn’t get the original text back.

SAK-32190 Cope with encryption not always failing.

---

master/pom.xml
portal/portal-service-impl/impl/pom.xml
portal/portal-shared-deploy/pom.xml

This means we’re keeping castor in sync with the version pluto depends on. The dependency isn’t needed in the service as it’s pulled in transitively.
This also fixes the startup warning that were being seen with newer versions of Tomcat as the newer castor JAR doesn’t have a META-INF/MANIFEST.MF that contains a Class-Path attribute.

SAK-25750 Upgrade to a newer version of castor.

---

jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java

When something goes wrong we now log the stack trace so that it’s easier to discover what’s going wrong without having to resort to a debugger.

SAK-32221 Log exceptions in Scheduler Tool.

---

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss

Delivers https://jira.sakaiproject.org/browse/SAK-31799.
Now that links are clickable, I've had to change it so drag is initiated from the drag handle (instead of dragging from anywhere inside the favorite container).  
I've also fixed a bug whereby sortable wasn't working for touch devices on some pages.  `jquery-ui-touch-punch` is required for sortable to work on any touch device, so I've ensured that this is loaded as required.

SAK-31799 make favorites clickable on mobile

---

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
kernel/component-manager/src/main/java/org/sakaiproject/component/impl/SpringCompMgr.java
kernel/component-manager/src/test/java/org/sakaiproject/util/ComponentsLoaderTest.java

If quartz tried to run some misfired jobs while the component manager was still starting up it would deadlock the startup of Sakai.
This introduces the Spring lifecycle to our application context and uses it to start the quartz scheduler once the application context has been refreshed.

SAK-32215 Prevent deadlock at startup due to quartz misfire handler

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

When using the edit tools menu in Site Info of a site that doesn’t have a standard type set (e.g. not project or course) you are presented with a list of possible tools to add to your site, but when you select some and proceed through the wizard it doesn’t actually add them to the site.
This is because when showing the list of tools available it falls back to the default site (project), but when actually adding them it doesn’t do this.

SAK-32150 Allow non-standard site types to work.

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java

There's just a little bug in the KNL-945 hibernate refactor whereby `BaseHibernateManager.updateAssignments` always throws a `ConflictingAssignmentNameException`.  The patch ensure that the assignment being updated is not included in the name-uniqueness query.
Instead of creating a new JIRA for this little change, I've just reused the original JIRA in the commit message.  Hopefully that's ok.

KNL-945 Fix BaseHibernateManager.updateAssignments throwing exception

---

samigo/samigo-app/pom.xml
samigo/samigo-services/src/java/org/sakaiproject/spring/SpringBeanLocator.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/context/IntegrationContextFactory.java
samigo/samigo-services/src/test/org/sakaiproject/spring/SpringBeanLocatorTest.java

The importing job was attempting to read archives containing samigo assessments early in the startup and this showed that the fix to block samigo code until the webapp has been started up wasn’t working correctly.
This correctly uses the `waitLock.wait()` inside the synchronized block, before we were getting an java.lang.IllegalMonitorStateException when attempting to `wait()`;
Also simplified the code as we don’t need to have 2 contexts as we can just actually have one and use more generic interfaces.

SAM-3167 Fix for samigo attempting to work early.

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java

https://jira.sakaiproject.org/browse/SAK-27494
This has been sitting around in JIRA with a patch for over 2 years now.

SAK-27494 prevent samigo from creating duplicate gradebook items (same name)

---

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm

As the administrator, on the Add new assignment page , when I select an option which is not supported by the content review service, the content review service checkbox is not displayed.

SAK-32261 Hide lblUseReview when not available

---

portal/portal-chat/tool/src/java/org/sakaiproject/portal/chat/entity/PCServiceEntityProvider.java

Register jgroups with the platform JMX server. This allow easier
inspection of jgroups while Sakai is running.

SAK-32267 Enable JMX for jgroups.

---

common/pom.xml

We didn't squash down this one in the end but it wasn't part of the build any more. So add it back.

SAK-32184 Add back the import pack

---

library/src/morpheus-master/sass/_defaults.scss

Set the icons to be on the left hand side not above the tool title.
Also increase the tool menu width because of this change.
Post config change:

SAK-32260 Modify tool menu default settings.

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
library/src/morpheus-master/sass/modules/access/_base.scss
login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm
login/login-tool/tool/src/java/org/sakaiproject/login/tool/SkinnableLogin.java

Before change:
After change:
Note that properties need to be set before one can see this external login page - please see the Jira.

SAK-32248 External login page now has configurable message.

---

help/help-component/pom.xml
master/pom.xml

Changes in 2.6.0
* Redesign of the contention code path resulting in doubling contended throughput; now
contended pool access retains 98% of the uncontended throughput.
* issue 793 add new HikariConfig method, setScheduledExecutor(ScheduledExecutorService),
and deprecate method setScheduledExecutorService(ScheduledThreadPoolExecutor). It is
unfortunate that the deprecated method has the more accurate name, but its signature
cannot be changed without breaking binary compatibility.
* issue 770 add a new property initializationFailTimeout, and deprecate configuration
property initializationFailFast.
* issue 774 significantly improve spike load handling.
* issues 518/769 add new metric for tracking how long physical connection acquisition is
taking.  DropWizard histogram name …

KNL-1499 upgrade HikariCP to 2.6.0

---

samigo/samigo-services/src/test/org/sakaiproject/spring/SpringBeanLocatorTest.java

Travis CI had a test failure on this. Probably because the box was heavily loaded and the other threads didn't have a chance to run. This increases the timeout and attempts to break things more by yielding in the current thread.

SAM-3167 Increase chance that tests pass.

---

library/pom.xml

Rather than running the yuicompressor twice (bound to difference phases. We just run it once and have all the generated files inside the /target folder instead of inside the source directory.
We also switch the order so that all our error messages are for the original source files rather than for the concatenated ones which makes fixing them much easier.
Also bump up the version of the plugin.

SAK-32292 Only run yuicompressor once.

---

site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java

RSF does some reflection to look for properties in the classes. When this was removed it broke because the producers used it. I feel like RSF MethodAnalyser maybe could be a little more lenient when this fails rather than throwing a "UniversalRuntimeException". Maybe it can return Optional type now!

SAK-32258 - Page order helper no longer working

---

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

Assignments was failing (NPE) when viewing submissions when there wasn’t a candidate details provider set. Now when there’s no provider we don’t ask it for any notes.

SAK-32276 Cope with no CandidateDetailsProvider

---

common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/ArchiveService2Impl.java

When importing a zip file site archive we expand the site archive into a folder and then import from there. However we don’t delete the expanded archive after importing so that results in not being able to import the archive again.

SAK-32300 Delete the expanded site after import.

---

sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/ReportManagerTest.java
sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsManagerTest.java

Some of the other tests inside site stats still had the collect thread enabled which would cause errors on some test runs. Disabling the collect thread should fix these and the tests still pass without it running.

SAK-32321 Fix intermittent sitestats test failures.

---

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/BaseContentServiceFixTypeAndIdTest.java
kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/BaseContentServiceTest.java

Although this affects the audio recorder in CKEditor it looks to be a general problem with the code that attempts to guess at the MIME type. It doesn't appear to get the filename but instead passes the whole path.

SAK-32264 Fix for MIME detection with path has dots

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/UserEntityProviderGetUserByIdEidTest.java

When looking up a user allow searching by AID as well as EID and ID. If a deployment isn’t using AIDs then it just falls though to searching by EID.

SAK-32302 Allow entitybroker user aid searches.

---

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-32319
Content Review has options to hide settings from the being shown to the instructor while creating an assignment, but it didn't allow for the global setting to be settable from the config. When the setting was hidden from appearing to the admin, it became unset as opposed to using the default.
These are the existing configs.
- contentreview.option.exclude_quoted  == To show field to instructor
- contentreview.option.exclude_quoted.default == default value
- contentreview.option.exclude_self_plag == To show field to instructor
- contentreview.option.exclude_self_plag.default == default value
- contentreview.option.store_inst_index == To show field to instructor
- contentreview.option.store_inst_index.default == default value

SAK-31319 - Use default value for content review options when not shown to instructor

---

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java

When a forum was being duplicated via transferCopyEntitiesRefMigrator
the topic List was retrieved in an unsorted order. As such, it was
possible for a topic with a sortOrder > 1 to be selected first and
imported into the new forum. Then when the forum was saved in
MessageForumsForumManagerImpl#saveDiscussionForum
(org.sakaiproject.api.app.messageforums.DiscussionForum, boolean,
boolean, java.lang.String)
the topics would be retrieved using BaseForumImpl#getTopics. This
method would first check to see if the topicSet was sorted by going
through the topics and checking their sort order, starting at 1.
With the topic list being retrieved in an unsorted order, you could
have the first topic inserted to have a sort order > 1. Then when
getTopics was ran, with only one topic in the set (whose …

SAK-32263 Preserve Forum Topic Order on Dupe

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java
portal/portal-util/util/src/java/org/sakaiproject/portal/util/CSSUtils.java
portal/portal-util/util/src/java/org/sakaiproject/portal/util/ToolUtils.java

https://jira.sakaiproject.org/browse/SAK-32242
For tool content that is inlined into portal, adds a reference to
tool.css and print.css, even though these will already be included on
the page. This results in the styles being loaded and parsed twice by
the browser, which slows down page render time and causes issues when
trying to debug CSS live on a page.
The issue occurs because of the two #parse directives at the top of
includeStandardHead.vm. The first one adds the content of the tool's
header (which portal also contributes to) when the tool is inlined. The
second one just always adds tool.css and print.css.
This patch will address the issue by having portal only add the
tool.css/print.css references to the tool's header if it is not being
inlined.

SAK-32242: Portal loads tool.css and print.css twice for inlined tools

---

jobscheduler/scheduler-component-shared/README.beanjobs.md
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/AuthzGroupProviderSync.java
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfillrole/BackFillRoleJob.java
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfilltool/BackFillToolJob.java
jobscheduler/scheduler-component/src/webapp/WEB-INF/backfill-tool.xml
jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml

Don't allow concurrent execution of the AuthzGroupProviderSync job as it doesn't make sense. Locally we've back an issue where multiple copies of this job were running concurrently and killing system performance. Also allow jobs to be stopped from the administration interface for some of the long running jobs.
We need to switch to spring injected jobs to allow stopping as you need a different instance of the jobs for each run to be able to cancel the correct one.

SAK-32303 Allow stopping of some jobs

---

site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties
site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_en_GB.properties
site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupImportStep2Producer.java

When importing a group into a site using a CSV file as well as searching for a user by EID it can be helpful to also search by AID and email address.
We are also more flexible and ignore rows that have empty values in them.
Also delete en_GB properties todo with importing that are identical to en.

SAK-32316 Allow email/AID for group CSV imports.

---

lessonbuilder/tool/src/webapp/removePage.jsp

This is a fix for Sean Horner's comment (at the bottom of https://jira.sakaiproject.org/browse/LSNBLDR-633) where removePage.jsp is trying to reference a non-static method from a static context.  
It doesn't seem to stop Sakai building or starting up successfully.

LSNBLDR-633: Fix for 'non-static method cannot be referenced'

---

library/pom.xml
library/src/webapp-filtered/editor/ckeditor.launch.js
master/pom.xml
webjars/ckeditor-a11ychecker/README.md
webjars/ckeditor-a11ychecker/pom.xml
webjars/ckeditor-balloonpanel/README.md
webjars/ckeditor-balloonpanel/pom.xml
webjars/pom.xml

This plugin is disabled by default, to enable it you need to build with the maven profile:
mvn -Pckeditor-a11ychecker install
This is because it’s license isn’t compatible with the ECL.

SAK-32075 Add a11y checker plugin to ckeditor.

---

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm

Also add pagination to the list of sites from which one can copy.
Tablet/mobile screen before fix:
Tablet/mobile screen after fix:

SAK-31800 Show Resources Copy Content option on a mobile screen.

---

rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/ImageMacro.java
rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java

Rather than escaping everything in the wiki tool we just escape the output of the image tag so that we don’t accidentally escape content in the tool.

SAK-32295 Just escape the attributes we need to.

---

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/ScheduledInvocationManagerImpl.java
jobscheduler/scheduler-component-shared/src/test/java/org/sakaiproject/component/app/scheduler/ScheduledInvocationTest.java
jobscheduler/scheduler-events-model/src/java/org/sakaiproject/scheduler/events/hibernate/ContextMapping.java

Another option might have been to have quartz use our central transactions, but that would have been a larger change with more risk.

SAK-32349 Fix peer assessment and ScheduledInvocationManager

---

master/pom.xml

Changes in 2.6.1
* issue 835 fix increased CPU consumption under heavy load caused by excessive
spinning in the ConcurrentBag.requite() method.
* issue 821 if a disconnection class exception is thrown during initial connection
setup, do not set the flag that indicates that checkDriverSupport() is complete.
* issue 817 updated behavior of new initializationFailTimeout, please see the
official documentation for details.
* issue 742 add direct MXBean accessor methods to HikariDataSource for users who do 
not want run run JMX.

KNL-1507 HikariCP to 2.6.1

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java

This is adding some config to LSNBLDR-542 so that the feature can be turned on or off.
Default is on.
If this goes back to 11.x, then the property should be set to false and uncommented.

LSNBLDR-542: Adding config

---

deploy/pom.xml
kernel/kernel-impl/pom.xml
kernel/kernel-impl/src/main/webapp/WEB-INF/component-components.xml
master/pom.xml

This is a more firewall friendly JMX connection protocol that by default listens on port 9875.

KNL-1505 support JMXMP out of the box.

---

kernel/api/src/main/java/org/sakaiproject/site/api/SitePage.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseToolConfiguration.java

When saving the placement the SQL code calls getTitle() which checks if the placement has a custom title and unless it does just returns the default title for the tool.
This change means that when we changes the title the flag indicating that it has a custom title is also updated and so the save works.

KNL-1508 Don’t lose title changes on save.

---

edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SiteTitleAdvisorCMS.java
kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupService.java
kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
kernel/api/src/main/java/org/sakaiproject/site/api/SiteTitleAdvisor.java
kernel/api/src/main/java/org/sakaiproject/site/cover/SiteService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java
kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockAuthzGroupService.java
portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalSiteHelper.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/JoinHandler.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/CurrentSiteViewImpl.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/EnrolmentsHandler.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java

https://jira.sakaiproject.org/browse/SAK-32376
A commit from SAK-30334 (21c0baf) broke Preferences obeying the sakai.property to display roster title rather than site title, which was introduced in SAK-29138.
This PR reimplements this aspect of the feature, as well as making the breadcrumbs,  browser/tab title and Membership tool obey the sakai.property. It also contains some performance improvements we've had in production for over a year.

SAK-32376: Ensure multiple places are obeying the option to display roster title rather than site title

---

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

When an assignment is in peer review student review mode there is an option for the student to provide attachments for their review, however we were attempting to check these with content-review which isn’t correct (and was failing). So this check has been disabled when in peer review mode.

SAK-32350 Don’t fail attachments in peer review mode.

---

content/content-bundles/resources/content.properties
content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
kernel/api/src/main/java/org/sakaiproject/exception/IdLengthException.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java

When uploading a file of creating a new file that will exceed the length of the ID column the error message generated wasn’t very good (just generic error, of null in message when creating text file).
Now we say what went wrong and when uploading a file specify what the actual limit is so the user has more of an idea how to fix it.

SAL-32391 Better warning when ID length exceeded.

---

content/content-tool/tool/src/java/org/sakaiproject/content/entityproviders/ContentEntityProvider.java

With the switch to lombok annotations this isn’t needed any more.

LSNBLDR-542 Remove redundant logging declaration.

---

samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp

https://jira.sakaiproject.org/browse/SAM-3184
This PR is for 11.x exclusively; the regression does not exist in master:
SAM-2904 introduced improvements to the landing page of Samigo for students. Instead of showing them empty, useless tables if there are no assessments to take, and/or they haven't made any submissions to assessments, simply provide a meaningful message to the user indicating the situation. There's no point in showing them table headers for an empty table they can't do anything with.
SAM-2904 was first merged to master (f09e9089), then merged to 11.x (41311008). However, the logic in the JSP file has since been removed in the 11.x branch. The strange part is, according to the Git log and Git blame, there is no revision on the JSP file (in 11.x) after the merge to 11.x …

SAM-3184: SAM-2904 was partially reverted in 11.x

---

calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm

There is a conflict with the event message editor (if the editor is removed, the problem dissapears) and a datepicker without indicate hh:mm:ss.
If hh:mm:ss is indicated with the input hidden ISO8601, problem also dissapears.

SAK-31758: In Calendar tool, Manually entering date gives NaN/NaN/NaN

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java
assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java

This feature allows the forums tool to have it's own importAsDraft
functionality.
I also added the import.importAsDraft property into the default.sakai.properties as it was missing.

SAK-31068 Add Forums Import As Draft setting

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java

https://jira.sakaiproject.org/browse/SAK-32386
There was a need at our institution to force the 'Overview' tool (formerly 'Home') to the top of the tool list in every site. We've implemented this behind a sakai.property (portal.forceOverviewToTop) which defaults to false to preserve OOTB functionality .

SAK-32386: force 'overview' tool to the top of the tool menu via sakai.property

---

kernel/api/src/main/java/org/sakaiproject/time/api/Time.java
kernel/api/src/main/java/org/sakaiproject/time/api/TimeBreakdown.java
kernel/api/src/main/java/org/sakaiproject/time/api/TimeService.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/StringUtil.java

<link>java.util.Date</link> => {@link java.util.Date}
@deprecated use commons-lang3 StringUtils.split
http://maven.apache.org/plugins/maven-javadoc-plugin/faq.html#How_to_use_links_option_in_Standard_Doclet

KNL-1511 {@link}

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java

This is adding some config to LSNBLDR-709 so that the feature can be turned on or off.
Default is on.
If this goes back to 11.x, then the property should be set to false and uncommented.

LSNBLDR-709: Adding calendar component config

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java

This is adding some config to LSNBLDR-711 so that the feature can be turned on or off.
Default is on.
If this goes back to 11.x, then the property should be set to false and uncommented.

LSNBLDR-711: Adding config for lessonbuilder.show.twitter.link

---

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java
basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
basiclti/basiclti-tool/src/webapp/vm/lti_content_delete.vm
basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/BltiExport.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/LtiImportItemProducer.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

The LTIService now always wants the site ID passed into all it’s calls as assuming that the context is correct doesn’t work when the tool is in helper mode in My Workspace or the Administration Workspace.
As lots of the method signatures were changing I also did a cleanup, removing lots of useless JavaDoc and adding @Override to the appropriate methods.

SAK-32360 Always pass site ID to LTI calls.

---

rubrics/pom.xml

With older Maven versions you have to specify a version when you specify
a scope even if the version is defined in a parent POM. Later maven
versions cope with this. Maven 3.2.3 which is used on the nightly server
fails. Maven 3.2.5+ seem to work.

SAK-32151 Be explicit about dependency with scope

---

access/access-impl/impl/src/java/org/sakaiproject/access/tool/WebServlet.java
feedback/src/java/org/sakaiproject/feedback/util/FileItemDataSource.java
feedback/src/java/org/sakaiproject/feedback/util/SakaiProxy.java
msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java

This returns the file upload as a byte array which if you are allowing large uploads would all get read onto the heap. Instead it uses an input stream.
Opening this as another PR as #4181 has been looked over and I didn't want to confuse people who are reviewing what code is old and what is new.

SAK-32398 Remove Apache Commons FileItem#get() use

---

library/src/morpheus-master/js/src/sakai.morpheus.quicklinks.js
library/src/morpheus-master/sass/modules/quicklinks/_base.scss

When quicklinks pop-up is open prevent scrolling of page underneath.
Post fix images, see Jira for pre-fix screenshots.

SAK-32384 Make Quicklinks scrollable.

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/UserEntityProviderFindAndCheckUserId.java

The original patch didn’t work correctly as entitybroker wants to check the ID before it actually looks it up and in configurations when we weren’t passing through to getUserByIdEid() this wasn’t working.

SAK-32302 Correctly allows lookups by AID.

---

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

When an assignment was saved with a grade such as ".7" with less
than the number of allowed decimal places (2 is default), the grade was
saved as "0.07"). This changes causes it to be saved as "0.70" by
padding entered scores with trailing 0s as appropriate.
[JIRA](https://jira.sakaiproject.org/browse/SAK-32445)

SAK-32445 Fix Assignments Grading with ".X" Grades

---

kernel/api/src/main/java/org/sakaiproject/memory/api/MemoryService.java

We didn’t have generics on the returned cache.

KNL-1520 Add generics to returned cache.

---

site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm

https://jira.sakaiproject.org/browse/SAK-32470
Duplicate id attribute on the table broke the jQuery selectors in the JavaScript function.

SAK-32470: membership -> 'clear selections' button no longer works

---

samigo/samigo-services/src/java/org/sakaiproject/spring/SpringBeanLocator.java

Under high load on linux you can receive spurious wakeups so you should always wait in a loop and check it your condition is true yet.

SAM-3194 When waiting on a lock should be in loop.

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

Allow a non-global tool in a site to be deployed correctly again.

SAK-32360 Fix for LTI tool inside a site.

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/PrintHandler.java

Problem was parsing a fragment as HTML inserted the full HTML into lessons which caused the page problems. I think this might be a bigger issue for lessons that some tags need to be stripped but this at least keeps it from messing up import fragments.

LSNBLDR-805 - Problem importing more than 1 item on a page

---

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-32475
In a very specific use case (steps to reproduce on the JIRA), the instructor will be presented with the following error message when providing a grade that uses too many decimal places:
> Alert: Please use only 2 decimal place(s) for the grade field. Please use only 2 decimal place(s) for the grade field. Please use a number for the grade field.
The decimal places warning message is repeated twice, and the 3rd message is just confusing.
The problem is that after calling validPointGrade, the STATE_MESSAGE is not checked for null before calling scalePointGrade, which then calls validPointGrade again and dumps the duplicated error message into STATE_MESSAGE. The solution is to simply check STATE_MESSAGE == null before calling scalePointGrade.

SAK-32475: duplicated too many decimal places error message

---

library/src/webapp/js/spinner.js

https://jira.sakaiproject.org/browse/SAK-32477
Drop down selections appear to change when submitting forms that utilize the modern clone/disable & spin JavaScript routine. The submitted value is the user's selection, but it can cause confusion if the user sees the drop down flip selections.
Simple solution: copy over the selectedIndex attribute from the original to the cloned element.

SAK-32477: copy drop down selectedIndex attribute to cloned element

---

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/ShoppingEditPage.html
delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserEditPage.html

Selecting an option causes table alignment to shift.
This only affects 11.x because Master uses Wicket 6.x and is not affected by this issue.

SAK-30700 - Selecting an option causes table alignment to shift

---

edu-services/gradebook-service/sakai-pack/src/webapp/WEB-INF/components.xml
gradebook/xdocs/add_custom_grade_mappings.txt

Custom scale definition doesn't work in Gradebook (components.xml
default file needs update)

SAK-32486 - Custom scale definition doesn't work in Gradebook (components.xml default file needs update)

---

library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/mixins/_tab-focus.scss

I don't like modifying Bootstrap SCSS files either, but I can't find a way to override a bootstrap mixin. Bootstrap v4 does things very differently so I don't think we will need to maintain this hack to make focus work in Firefox.
CC: @fostersdesign

SAK-32484 add a valid outline for Firefox

---

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm

https://jira.sakaiproject.org/browse/SAK-32471
Put a spinner beside the 'Submit as Student' link, as it can take a while for the interface to load.

SAK-32471: put a spinner beside the 'submit as studen't link

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java

Fix precision issue when scoring multiple-choice multiple-correct
questions when the all-or-nothing option is on.

SAM-3191 Fix scoring of all-or-nothing mult choice mult correct

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java

Mapped grades will be null if the student doesn't have a course grade yet.

#3432 Make sure mapped grades are not null when they are collected.

---

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm

https://jira.sakaiproject.org/browse/SAK-32502
The variable being checked in the Velocity template is not the correct one that contains the group ID of the group the user selected. Changing the variable to the correct one solves the problem.
There was also some garbage HTML introduced in SAK-30067 that is useless and just clutters things in the DOM. Not sure how I didn't see that in SAK-30067... It doesn't affect functionality but it shouldn't be there.

SAK-32502: grade report group filter not reflecting selection after page refresh

---

site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupImportStep2Producer.java

It also fixes a problem with non-id members not being correctly added to the group. If you attempt to add a user with an email address or AID then they get looked up in the earlier part of the wizard, but then not added to the group in the last step.
Also the saveGroupMembership call is redundant and can be removed as saving the site will save any changes to the group membership.

SAK-32427 Fix for user email/AID lookups.

---

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java

When displaying the site entity include the portal.include.extrahead property as well. This means that this property is now displayed on HTML pages from resources, in the portal and on Site entities.

KNL-1523 Include portal.include.extrahead on site display

---

basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java

The header should be checked for the oauth_consumer_key. This fix will allow the header to be checked if it is not a parameter.

SAK-32554 Fix LTI oauth_consumer_key check

---

basiclti/basiclti-blis/pom.xml
basiclti/basiclti-blis/src/java/org/sakaiproject/lti/entityprovider/LTIEntityProvider.java
basiclti/basiclti-blis/src/test/org/sakaiproject/lti/entityprovider/LTIEntityProviderTest.java

This allows site members to use /direct/lti, previously you needed to be a maintainer to access these endpoints which mean it’s wasn’t possible to find the LTI tools installed in a site using a JSON request. It just changes the /lti/tool/ /lti/tools /lti/content/ /lit/contents/ endpoints.
It also makes sure we never output passwords in the JSON, even for admins.

SAK-32552 Allow site members to use /direct/lti/

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/UserEntityProviderRestrictedViewTest.java
entitybroker/core-providers/src/webapp/WEB-INF/applicationContext.xml

This checks to see if the profile tool is in the user’s My Workspace and if so allows them a limited  view of the user. It just includes IDs (ID, EID, display), Name and type. None of the dates or properties are displayed.

SAK-32542 Allow non-admins to search and user users.

---

admin-tools/src/webapp/vm/authz-helper/chef_permissions.vm

This also affected the CSS which is fixed here. This prevented the permissions widget to from rendering correctly as well as the clickable columns from working correctly.

SAK-32592 Have permission widget correctly load JS

---

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactory.java
textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/site/SiteFsVolume.java

In elfinder even if the Resources tool was missing from the site the Resources tool would be opened when using elfinder as a file picker. This stops that and prevents the Resources folder form being displayed even when it’s set as the initial folder.
It was always the case that when browsing an alternative site that if the Resources tool wasn’t present you wouldn’t see that folder present in elfinder.
If the resources tool is added, some files added and then removed you will still see the Resources folder when browsing the current site.

SAK-31515 Don’t display Resources when tool missing

---

library/src/morpheus-master/sass/base/_icons.scss

This didn’t have an icon set and this is the same as the end user tool icon.

SAK-32577 Set OAuth Admin Application Icon

---

rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/PrepopulatePages.properties
rwiki/rwiki-util/radeox/src/bundle/META-INF/services/org.radeox.filter.Filter
rwiki/rwiki-util/radeox/src/bundle/radeox_markup.properties
rwiki/rwiki-util/radeox/src/java/org/radeox/filter/CodeFilter.java

Add support to rwiki for monospaced inline text. This is useful for code snippets in a similar way to how backtracks are used in Markdown.

SAK-32603 Add support for monospaced inline text

---

library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
library/src/morpheus-master/sass/modules/more-sites/_base.scss
portal/portal-impl/impl/src/bundle/sitenav.properties
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm

Heavily based on the ideas here: https://inclusive-components.design/toggle-button/
* aria-clicked gets toggled on every user click
* On and Off are visible and simple spans. The two choices are plain and not swapped out or hidden
* "As a rule of thumb, you should never change pressed state and label together. If the label changes, the button has already changed state in a sense, just not via explicit WAI-ARIA state management."
* role="switch" is nice for screen-readers
* SCSS rewritten to use button colors
* simple space or enter or click on the button will change the state
* the button is tabbable with a keyboard
CC: @kyleblythe is NYU interested in the styling of this on/off button in master?

SAK-32495 create an accessible toggle/switch for auto-favorites using aria-clicked and role=switch

---

library/src/morpheus-master/sass/modules/_toolmenu.scss
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/loginImage-snippet.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm

> 1. The reason the “Tools begins here” H1 isn’t read in responsive layout is because it’s hidden with display:none:
> 2. The reason that VoiceOver doesn't announce the text content of the "Tools" and "Sites" links is that the links are wrapped inside "menuitem" roles. Menu item roles can't contain links. The "menu" and "menuitem" roles need to be removed here, as these roles are only applicable for desktop application style menubars and dropdown menus.
> 3. The links in the Tools list are incorrectly marked up with role="presentation"

SAK-32364 implement Hans suggestions to improve iOS Voiceover experience

---

site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css

The last tool in the list would be missing it’s border. You would only see this problem when you had that tool added to the site and went back to the manage tools page. Typically this is the wiki tool, unless you also have some LTI tools available in the site.

SAK-32613 Fix for the last tool in list missing border.

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java

For a while, up to Sakai 11.3, uploading a custom css file directly from the lessonbuilder page could cause Sakai to generate file names like foo.css-1 In such cases, they should appear in the dropdown for custom css

LSNBLDR-820 accept .css-1 endings for custom stylesheets

---

library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm

Before commit 3103b77 clicking anywhere in the <li> for the collapse button would toggle the menu. Changes made in that commit made it so that the double arrows needed to be clicked directly. This commit is an attempt to restore the previous behavior and preserve the changes made in 3103b77.

SAK-32389 Restoring behavior of tool menu toggle button 

---

profile2/api/src/java/org/sakaiproject/profile2/logic/ProfileLogic.java
profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/RosterEntityProvider.java

Calls to /direct/roster/site/….json would fail if the site contained a deleted users. This fixes it so that they aren’t included in the results, just like inactive users.
I also downgraded the logging from info to debug for failure to find users as in production this is an expected case.
I also changed handling of a group not being found, rather than returning an empty collection, it throws an error which gets transformed to a HTTP 404 error. This matches the error handling when a site isn’t found.

SAK-32625 Don’t fail when site has deleted users.

---

content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm

Because this script is used on pages that don’t have the text field we extract the URL from we need to check that it’s present on the page before attempting to shorten it.

SAK-32620 Check that we have a URL before shortening.

---

chat/chat-tool/tool/pom.xml
chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
library/src/webapp/js/lang-datepicker/lang-datepicker.js

The date settings of the chat channel cannot be unset.
Server side: It always require a valid value in the hidden field, but
empty dates are allowed.
Client side: When someone clears the input field, the hidden value is
never updated, and it's processed in the server side. This only affects
the pickers with allowEmptyDate option set to true and the ones who
process the hidden value in the server side.

SAK-32623 - The date settings of the chat channel cannot be unset

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/MembershipEntityProviderTest.java

We found a bug here at Ox, audit records were created via entity broker if an external user was added to a site but not for an official user.  Also, the incorrect user ID for the person doing the change was used.  These two bugs have been fixed in these commits.

 SAK-32285 Fix bug with user ID.

---

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java

This is fix for 2 bugs:
1. Shared page not showing up: Add 2 Lessons Tools (L1 & L2). On first tool, add text to the top page and give the page an owner, then add sub page (SP1) and add text to that sub page. On second lessons tool do 'Add Sub Page' and elect to select an existing page.
On the 'Pick a Page' screen: SP1 page should be listed under L1
2. An owned page cannot have a student page added to it: New Lessons tool -> give it an owner -> -> Click Add Student Content -> 'You do not have the required permissions to do that.'

LSNBLDR-633: Restrict editing of Lessons pages and subpages to one person

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm

Looks like PNotify went through some refactoring between 1.2.0 (used in Sakai 10) and 2.1.0 (used in Sakai 11+) that created new files, but those files were not added as dependencies in portal and so the pin and close buttons weren't rendering.

SAK-30944 AntiSamy alert is not dismissible

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java

In the subsites flyout all the sites were being shown as unpublished because the values wasn’t in the render context. This adds it to the render context for all places the portal renders a site, but it shouldn’t cause a problem in all the other cases.

SAK-32238 Correctly display an unpublished site.

---

podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/PodcastServiceImpl.java

If podcasts folder is hidden don't blow up with a permission exception. The way podcasts uses security advisors isn't very good. I looked at cleaning it up a little more, but in `org.sakaiproject.component.app.podcasts.PodcastServiceImpl#filterResources(java.util.List, java.lang.String)` it looks to see if there are advisors and then removes one and then optionally pushes it back onto the stack.

SAK-32645 Don't blow up if podcasts folder is hidden

---

profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileMessagingLogicImpl.java

If a user uses the profile tool to send a message to one of their connections and doesn’t enter a subject then the message gets stored in the DB without a problem, but an email message doesn’t get sent.

SAK-26761 Don’t fail to send if subject is empty.

---

polls/tool/src/java/org/sakaiproject/poll/tool/producers/PollToolProducer.java

Poles / students see 'Reset selected polls'. The button is not hidden
because the IF sentence only affects the first UICommand and should
affect both.

SAK-32167 - Polls / students see 'Reset selected polls'

---

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java

Dropbox is sending emails when files are copied. there are two
preferences, tool and user. The tool's preference is totally ignored and
only the user's is considered.
The move operation doesn't send any notification, copy should do the
same.
This should be discussed with the core team, i think it's not the best
solution.

SAK-32181 - Drop box / email sent when copying files

---

library/src/webapp/js/spinner.js

https://jira.sakaiproject.org/browse/SAK-32683
The new animated spinner overlay is not being applied to input elements of type="button". We found that this is due to the fact that types button and submit are currently not able to have CSS :after selectors applied.
We were already handling this for type="submit" by cloning the element as a `<button>`, we just need to do the same for type="button".

SAK-32683: spinner overlay not being applied on inputs of type='button'

---

library/src/webapp/WEB-INF/web.xml

Lessons serves up HTML pages from resources with a stricter content security policy that the standard /access view. This causes the browser to check for a CORS header on the font files and refuse to load them when it can’t find the header. This allows request from anywhere for the standard font file extensions. We could be more restrictive and only allow it from known hostnames, but this is more error prone and these fonts are available on CDNs anyway.

SAK-32647 Allow CORS checks for all font files.

---

profile2/api/src/java/org/sakaiproject/profile2/cache/CacheManager.java
profile2/impl/src/java/org/sakaiproject/profile2/cache/CacheManagerImpl.java
profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileSearchLogicImpl.java

If you perform a search in the profile tool and then wait for the cache entry to have expired and attempt to view the search page again, or perform another search the profile tool falls over as it expects to get an item from the cache and when it’s returned as null due to being expired it NPEs. There are several stack traces that you can end up having but they appear to resolve around the search cache.
This changes means we don’t bother testing to see if an item is in the cache and just try to get it and check if it’s null. While looking at this I also added generics to the caching to reduce the amount of casting.

SAK-32541 Fix handling of expired cache entries.

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

I don't know if this fix will cause more bugs than it solves. Someone can confirm, please.

SAK-31490 : Removing Home tool will remove other tools renamed to Home

---

library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss
site-manage/pageorder/tool/src/webapp/content/templates/PageList.html

The previous fix caused any other dropdowns used in tools used as a helper from site-info to be incorrectly positioned.
It’s also the cleaner and more correct fix for the issue in the first place.

SAK-32709 Fix for page order options going offscreen

---

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java

This is 1/2 of the fix for SAK-30793 - it reverts the change for SAK-23076 which caused the date not to advance for repeated events.  The other half is to properly fix SAK-23076 (times end like 1:59 instead of 2:00) - but since the bug is in kernel, it is in under KNL-1536.
These can be applied in any order but both must be in for SAK-23076 and SAK-30793 to be working *at the same time* :)

SAK-30793 - Revert SAK-23076 since KNL-1536 fixes it properly

---

providers/sample/src/java/org/sakaiproject/provider/user/SampleUserDirectoryProvider.java

When running in demo mode the provided users all get a prefix on their display ID of 'display-' to make testing easier, however this breaks functionality in Sakai and shouldn't have been committed.

SAK-32714 Drop display- prefix from demo provided.

---

portal/portal-chat/tool/src/java/org/sakaiproject/portal/chat/entity/PCServiceEntityProvider.java
portal/portal-chat/tool/src/webapp/WEB-INF/applicationContext.xml

When the portal chat code was getting shut down it’s destroy method wasn’t getting called so it wasn’t unregistering itself from the cluster and this combined with the problem of node failure detection not working was causing new nodes not being able to connect to the cluster. Although it shouldn’t be needed it’s cleaner to un-register from the cluster so we’re putting this back in.
This also has the entitybroker registration de-registered.

SAK-32718 Correctly shutdown the portal chat EB

---

basiclti/basiclti-portlet/src/webapp/WEB-INF/sakai/IMSBLTIPortlet.xml

Code uses fa_icon so config needs to match, otherwise you can't configure this properly from the xml.

SAK-32744 FA icon parameter is misnamed in LTI portlet config

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

When samigo.editPubAnonyGrading.restricted is set to true, the Students' Identities section in published settings is NOT editable. This is opposite of what had been documented in default.sakai.properties.

SAM-725 - Anonymous grading property is documented incorrectly

---

dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/SessionEntityProvider.java
entitybroker/core-providers/src/webapp/WEB-INF/applicationContext.xml
kernel/api/src/main/java/org/sakaiproject/user/api/IdPwEvidence.java
kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/UserAuthnComponent.java
kernel/kernel-impl/src/test/java/org/sakaiproject/user/impl/test/AuthenticationCacheTest.java
kernel/kernel-util/pom.xml
kernel/kernel-util/src/main/java/org/sakaiproject/util/BasicAuth.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/IPAddrUtil.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/IdPwEvidence.java
kernel/kernel-util/src/test/java/org/sakaiproject/util/IPAddrUtilTest.java
login/login-impl/impl/src/java/org/sakaiproject/login/impl/LoginServiceComponent.java
podcasts/podcasts/src/java/org/sakaiproject/tool/podcasts/RSSPodfeedServlet.java
reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/ClaimLocator.java
webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java
webservices/cxf/src/java/org/sakaiproject/webservices/SakaiLogin.java
webservices/cxf/src/resources/applicationContext.xml
webservices/cxf/src/test/java/org/sakaiproject/webservices/MockingAbstractWebService.java
webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiLoginLoginTest.java

This implements an optional IP whitelist as a user property for internal authentication (i.e. authentication methods other than container authentication). These methods include:
* Form-based login to /portal/xlogin
* Entitybroker new session creation (POST to /direct/session)
* WebDAV basic auth
* Basic auth for other requests
* Podcasts (internal basic auth)
* SakaiLogin CXF webservice
The IP Whitelist can be exposed as an optional user property in the Admin Tools / User edit page by adding this config to sakai.properties:
user.additional.attribute.count=1
user.additional.attribute.1=ip-whitelist
user.additional.attribute.display.ip-whitelist=IP Whitelist
The IP whitelist is a comma-separated list of IPv4 IP addresses or CIDR netmasks (e.g. 192.168.0.1, 10.0.0.0/8)
Should we support IPv6 …

SAK-32699 IP whitelist for internal user authentication

---

lessonbuilder/tool/pom.xml
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
lessonbuilder/tool/src/test/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducerTest.java

When accessing a URL without an id rather than generating a stack trace
lessonbuilder would throw a 500 error.

LSNBLDR-843 Fix for stack trace parsing bad URL.

---

kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql
kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql
kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql

I didn't see an easy i18n fix for this because it's storing it in the database for this instance. I feel like if the default language of the school was Spanish, they'd want to change this on the !user template.  That's really the easiest way for this fix. 
Also has a db conversion which is now over in https://github.com/sakaiproject/sakai-reference/pull/1
Originally from #3710

SAK-32045 - Change text 'My Workspace' to "Home" in worksite setup

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
lessonbuilder/tool/src/webapp/templates/ShowPage.html
library/src/morpheus-master/sass/modules/_toolmenu.scss
library/src/webapp/js/lessons-subnav.js
portal/portal-impl/impl/src/bundle/sitenav.properties
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/LessonsTreeView.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/LessonsSubnavEnabler.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-addRemoveFeatureConfirm.vm
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm

This PR delivers NYU's lessons subnav behaviour as outlined in https://jira.sakaiproject.org/browse/SAK-32760.
Similar to MathJax, the lessons subnav can be enabled via "Site Info > Manage Tools":
When enabled, lessons subpages are surfaced in the portal tool navigation:
While most behaviour is in the portal to generate the lessons page data as JSON for JavaScript to consume (see `LessonsTreeView.java`), some changes to lessonbuilder were  required.  These include: 
* adding a new `op` to allow an link external to lessons to populate the breadcrumb trail (see `adjustPath` and the new `clear_and_push` directive.
* output of some hidden inputs containing the current lesson page's pageId, top-most pageId and context Id.  This allows the JavaScript to select the current page (or parent of the …

SAK-32760 Add NYU customization to introduce Lessons subpage navigation

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm

In the commit it doesn't actually reference the portal and it looks like everything else is just pushed down, I guess it's the same thing.

SAK-33253 - Move portal javascript variable up before other snippets

---

providers/jldap/src/java/edu/amc/sakai/user/SimpleLdapCandidateAttributeMapper.java

https://jira.sakaiproject.org/browse/SAK-33259
There is a bug in the code when mapping the 'studentNumber' LDAP attribute into the user object's properties. The method SimpleLdapCandidateAttributeMapper.addStudentNumberProperty() adds the property as a list:
```
userEditProperties.addPropertyToList(USER_PROP_STUDENT_NUMBER, studentNumber);
```
Later on, when the student number is requested, it tries to access this user property in CandidateDetailProviderImpl.getNumericId():
```
String studentNumber = user.getProperties().getProperty(USER_PROP_STUDENT_NUMBER);
```
And the implementation of getProperty() will return null because the property is a list rather than a String object:
```
public String getProperty(String name)
{
Object value = m_props.get(name);
if (value instanceof String) …
```

SAK-33259: LDAP student/employee numbers not appearing

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

This allows the tool used to add users to a site to be configured as a
deployment and a per site level through sakai.properties and site
properties. The site property overrides the sakai.properties config. The
property key is:
sitemanage.add.user.tool
When looked up it's also checked that it is a valid helper tool to avoid
situations where the add user helper can't be run.

SAK-32755 Allow config of tool to add users

---

webservices/cxf/pom.xml
webservices/cxf/src/java/org/sakaiproject/rest/HostFilter.java
webservices/cxf/src/java/org/sakaiproject/webservices/SakaiI18n.java
webservices/cxf/src/java/org/sakaiproject/webservices/interceptor/NetworkAddressValidatingInterceptor.java
webservices/cxf/src/java/org/sakaiproject/webservices/interceptor/NoIPRestriction.java
webservices/cxf/src/java/org/sakaiproject/webservices/interceptor/RemoteHostMatcher.java
webservices/cxf/src/resources/applicationContext.xml
webservices/cxf/src/test/java/org/sakaiproject/webservices/RemoteHostMatcherTest.java
webservices/cxf/src/webapp/WEB-INF/web.xml

#This moves the the IP address range filter from the kernel to the web services. The reason for doing this is that it was explicitly setup to just use the web services configuration properties so it didn’t make sense to use as it is anywhere apart from the web services without further refactoring.
This moves the filtering of requests from a servlet filter to a CXF interceptor, this allows us to examine the method that is going to handle the request and so look for annotations on that method.
We couldn’t do this as a JAX-RS filter as that wouldn’t have prevented requests to the non JAX-WS endpoints.

SAK-33249 Support annotations for non-IP restricted WS

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

Noticed that the documentation about the properties for the wysiwyg editor in Sakai was out of date. Hoping this improves it.

SAK-33254 - CK Editor properties documentation need sprucing up

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java

https://jira.sakaiproject.org/browse/SAM-3240
The upper threshold is not obeyed (as advertised). The bug is just that in the determineRandomValuesForRanges() method, some doubles weren't converted to BigDecimal:
```
double minVal = Double.valueOf(delimRange.substring(0, delimRange.indexOf('|')));
double maxVal = Double.valueOf(delimRange.substring(delimRange.indexOf('|')+1, delimRange.indexOf(',')));
int decimalPlaces = Integer.valueOf(delimRange.substring(delimRange.indexOf(',')+1, delimRange.length()));
// This line does the magic of creating the random variable value within the range.
Double randomValue = minVal + (maxVal - minVal) * generator.nextDouble();
// Trim off excess decimal points based on decimalPlaces value
/*BigDecimal bd = new BigDecimal(randomValue);
bd = …
```

SAM-3240: bug with calculated question's upper threshold on converting to scientific notation

---

syllabus/syllabus-app/src/webapp/js/syllabus.js

https://jira.sakaiproject.org/browse/SAK-33295
The title of a Syllabus Item is required, however has the following bugs:
* no required field indicator (asterisk)
* validation is not presented to the user
1) create a Syllabus Item
2) provide some content in the CKEditor, but do not specific a title
3) click either of the save options
4) notice the modal is gone, nothing was created, and no error/warning was presented to the user
There is actually validation and a validation message in place, but immediately after presenting the validation message, the JavaScript code closes the modal. The result is that the user has no opportunity to see the error, no opportunity to rectify the error, and loses all the data they may have entered in the CKEditor.
The solution to this is …

SAK-33295: syllabus item title requirement/validation not visible to user

---

samigo/samigo-app/src/webapp/css/tool_sam.css
samigo/samigo-app/src/webapp/jsf/questionpool/transferPool.jsp

https://jira.sakaiproject.org/browse/SAM-3241
In the Transfer Ownership UI, subpools were previously indented in order to visually distinguish them from another top level pool. This indentation has regressed.

SAM-3241: Transfer Question Pools UI doesn't distinguish (indent) subpools

---

site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java
site-manage/pageorder/tool/src/webapp/content/templates/PageList.html

https://jira.sakaiproject.org/browse/SAK-33303
The "URL" label appears in the Tool Order > Edit Tool Title panel in Site Info even when there is no URL field to edit. Hide the label if we're hiding the corresponding input field.

SAK-33303: Site Info > Tool Order > hide 'URL' label when not needed

---

site-manage/site-manage-group-helper/tool/src/webapp/content/templates/GroupEdit.html
site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html

https://jira.sakaiproject.org/browse/SAK-33304
When you "add"/"update" the form to create a group, the joinable set drop down control is duplicated. This is a result of the spinner function being called twice on click of the 'save'/'update' button.

SAK-33304: Site Info > Manage Groups > Joinable Set drop down is duplicated on add or update

---

assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss

https://jira.sakaiproject.org/browse/SAK-33300
The spinner animation pops up beside the drop down, which pushes the buttons to the right and can cause button(s) to fall to the next line in smaller browser windows.
Relocate the spinner to appear beside the header text ("Viewing x-y of z items").

SAK-33300: assignments paginators' items per page spinner is in an awkward location

---

edu-services/sections-service/sections-api/src/java/org/sakaiproject/section/api/SectionAwareness.java
samigo/samigo-api/pom.xml
samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/EvaluationModelIfc.java
samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/grading/GradingSectionAwareServiceAPI.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SectionActivityMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SectionActivityBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SectionActivityListener.java
samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResultFromSectionActivity.jsp
samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivity.jsp
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/SectionAwareServiceHelperImpl.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/grading/GradingSectionAwareServiceImpl.java

https://jira.sakaiproject.org/browse/SAM-3242
The 'User Activity Report' allows the instructor/maintainer to view submissions by user, and provides a link to the user's submission to facilitate grading and commenting. In the context of an anonymously graded assessment, this link allows the instructor/maintainer to circumvent the anonymity feature.
1) Create and publish an assessment that is graded anonymously
2) Take the assessment as a student/access member
3) As instructor/maintainer, view 'User Activity Report' for the user you took the assessment as in step 2)
4) Click the link to take you to the user's submission for the anonymously graded assessment
5) You can now grade/comment on the 'anonymous' submission, but you know exactly who's submission it is
A solution …

SAM-3242: User Activity Report circumvents anonymous grading

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm

https://jira.sakaiproject.org/browse/SAK-33301
1) Create an assignment
2) Use grading scale, enter points possible
3) Select some settings that you know will produce an error (ex. open date after due date, no title, etc)
4) Save
5) Form refreshes, but focus is immediately put on the points possible field all the way down the screen
This results in a situation where the user is not aware of the error, which is presented at the top of the page. The same kind of problem exists when editing an existing assignment. The solution is to not call SetMaxPoint() if there are alerts/errors at the top of the page.

SAK-33301: don't call SetMaxPoint() if there are alerts/errors at the top of the page

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java

https://jira.sakaiproject.org/browse/SAM-3243
1) create and publish a quiz that's set to push scores/comments to the gradebook
2) submit to the quiz as student/access member
3) as instructor/maintainer go to Total Scores (scores) for the assessment
4) find the row in the table for the student/access member you took the quiz with
5) notice there is a submission, with a grade, but the comment box is disabled and has the placeholder text "Requires student submission", and the "Submitted Date" column is blank
You'll notice the following warning in the logs:
> WARN [http-nio-8450-exec-20] org.sakaiproject.tool.assessment.ui.listener.evaluation.TotalScoreListener.prepareAgentResult Cannot invoke org.sakaiproject.tool.assessment.ui.bean.evaluation.AgentResults.setIsAutoSubmitt …

SAM-3243: Total Scores: comment field disabled for student submissions, submit date column blank

---

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoObserver.java

https://jira.sakaiproject.org/browse/SAM-3244
Stack trace and steps to reproduce in the JIRA.
In SAM-3012 / SAM-2669, the event names utilized in Samigo were refactored in an effort to standardize the format. This caused an unintended NPE being generated in the logs because there is a listener (SamigoObserver.java) that's listening for three specific events that happen on submission of an assessment. This listener is responsible for unpacking the relevant data from the Event, and passing it off to SamigoETSProviderImpl.java to facilitate email notifications.
The problem is that originally, SamigoObserver was listening for "sam.assessmentSubmitted" (as well as two others that aren't relevant for this ticket). This event was only fired in one specific place, which guaranteed that the …

SAM-3244: samigo event name refactor/standardization causing NPE on assessment submission

---

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp

https://jira.sakaiproject.org/browse/SAM-3248
SAM-2721 refactored a lot of Samigo HTML for bootstrap. In commit f726ace, the "Responses" heading was refactored and the class "hide" was added to the `<h2>` element. This was most likely just an oversight. This PR simply removes the class so that the header is visible once again.

SAM-3248: Total Scores > Questions > restore the 'Responses' heading

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java

https://jira.sakaiproject.org/browse/SAM-3246
There are two places in Samigo where the instructor/maintainer can provide grades and comments for a user's submission:
1) the table in the 'Total Scores' tab
2) a student's individual submission grading UI (Total Scores > click on student's name link)
If you have an assessment set to publish grades and comments to the gradebook, using the comment box (at the top of the screen) in the student's individual submission grading UI without updating the grade for the submission, these new/updated comments will not be pushed to the gradebook. This results in comments being out of sync between Samigo and the Gradebook.
1) create and publish an assessment which is set to push grades/comments to the Gradebook
2) take the assessment …

SAM-3246: Individual user-level comments aren't sync'd to the Gradebook

---

master/pom.xml

added xmlgraphics-commons 1.5 to master pom.
This fixes a bug in rwiki, site-manage, and rwiki tools when downloading PDFs and the server's timezone <= GMT -10

SAK-32707 NumberFormatException: For input string: ":0" when generating PDF with timezone <= GMT -10

---

master/pom.xml

Upgrade JavaMail from 1.5.6 to 1.6.0

SAK-33377 - Upgrade JavaMail from 1.5.6 to 1.6.0

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentSupplementItemServiceImpl.java

https://jira.sakaiproject.org/browse/SAK-33382
Saving as draft allows the student to see the model answer, even though they technically haven't submitted.
This is technically a regression introduced in https://jira.sakaiproject.org/browse/SAK-32436 (07c0eff), by removing the check on s.getSubmitted(). Before Earle's Assignments refactor, the JavaDocs for this property indicated it's used to determine draft status:
```
/**
* Get whether this is a final submission.
* 
* @return True if a final submission, false if still a draft.
*/
public boolean getSubmitted();
```

SAK-33382: model answers set to display after submission are visible if the student saves as draft

---

lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDao.java
lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/util/LessonsSubNavBuilder.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
library/src/webapp/js/lessons-subnav.js
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java

This patch updates the lessons subnav to use the lessonbuilder's `isItemAccessible` to take into account all lesson item types when calculating the prerequisites for a page in the menu.
To avoid slow-down of the page load, we've moved this calculation to an EntityProvider that is pinged via AJAX by the lessons subnav JavaScript. The menu items are then greyed out/disabled if any prerequisites apply. Note, as per the current behaviour, if a student is able to click a link before it is disabled, the Lessons tool will bounce the user back to the top level page -- so no harm done, this change just attempts to expose this state to the user in a timely manner.
https://jira.sakaiproject.org/browse/SAK-33349

SAK-33349 Fix prerequisite calculations for the lessons subnav

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueriesAPI.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/AssessmentGradeInfoProvider.java

This solves an issue we found with GradebookNG where a bad HibernateTransaction load would cause the entire transaction to be put into rollback state

SAM-3255 do a simple query to see if assessment id is valid instead of doing a Hibernate load

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java

There is an uncaught exception when evaluting division in
calculated questions where the answer is a non-terminating decimal.
This fixes the issue by setting the rounding mode and number of decimal
places desired.

SAM-3258 BigDecimal divide with no rounding mode causes bug in calc qs

---

content/content-bundles/resources/types.properties
content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourceTypeLabeler.java
content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
content/content-types/src/java/org/sakaiproject/content/types/UrlResourceType.java
kernel/api/src/main/java/org/sakaiproject/content/api/ResourceToolAction.java

First attempt didn't quite cut the mustard, https://github.com/sakaiproject/sakai/pull/4816
As documented in SAK-33264, we discovered that the date pickers were not being initialised within the details sub-form for web links added to the form.  We've fixed that by ensuring these pickers are setup upon cloning of the form elements (see `setupDatePickers`).
@jonespm now the date pickers are behaving themselves, we were also able to restore the 'Add Another Folder' workflow by tinkering making the DOM structure consistent with the web link form DOM.
Delivers https://jira.sakaiproject.org/browse/SAK-31520 and _ALTERNATIVE D_ from https://jira.sakaiproject.org/browse/SAK-33264.

SAK-31520 SAK-33264 Restore 'Add Another Web Link'  and 'Add Another Folder'

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

While duplicating an assignment the position was not copied causing and
NPE in the comparator.
Added the original assignments position when creating the duplicate.

SAK-33414 Assignments duplicating assignment assignments position

---

basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/SiteMembershipsSynchroniserImpl.java

Using ex.printStackTrace() can result in logs ending up in a different place from the rest of the logging setup.

SAK-33418 Switch to use standard loggers.

---

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm

It trims the item name when has more than 25 characters, trimming HTML entities if are present.
The current solution is a really bad practice, this request proposes another approach using the ellipsis, will be good if some expert can throw feedback.
I've tested it and works fine.

SAK-33390 - International characters lost resizing

---

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAggregateJobImpl.java

Site stats stops processing when event_id exceeds 2147483647

SAK-33437 Sitestats treats event_id as Integer

---

content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java

https://jira.sakaiproject.org/browse/SAK-33408
SAK-14625 introduced a drop down control to filter the list on groups or sections. The boolean value that determines if this control is rendered was hard-coded to true. The correct approach is to conditionally render this control based on if the user has one of two permissions (dropbox.maintain or dropbox.maintain.own.groups). If the user doesn't have either of these permissions, it's not appropriate to display the drop down filter.

SAK-33408: Dropbox > Group/Section filter visibility is hard-coded to true; should be based on permissions

---

library/pom.xml
library/src/morpheus-master/sass/modules/editor/_base.scss
library/src/webapp-filtered/editor/ckeditor.launch.js
portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java

Upgrade CK Editor from 4.5.11 to 4.7.3.
The new default skin is moono-lisa instead of moono.
I've tested all the buttons, options and plugins (Except autosave), everything is working as expected.
Autosave should be upgraded from "b88e3878f0c7442a52e542f67e76d97e2ce32f8" to "786318aefed553a62cebbe4cd10b67c3ab266437".

SAK-33438 - Upgrade to CKEditor 4.7.3

---

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementGroupComparator.java
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapperComparator.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/SortedIterator.java

The issues is that although the session state always had AnnouncementWrappers in it and the comparator works fine on an AnnouncementWrapper when re-ordering the comparator is used on a plain AnnouncementMessage.
The problem with the original refactor was that although I applied generics to some of the code I didn’t go far enough which is why I missed the reordering case. A simple fix would be to just drop the generics which would fix the problem but I think in the long run we’re better to try to keep the generics as it makes the code more maintainable and easier to refactor later on.
This adds generics to all the uses of AnnouncementComparator so that we’re sure there aren’t any more cases of the comparator being used on the wrong type. We also rename the Comparator to make it clearer …

SAK-33419 Don’t NPE when re-ordering announcements

---

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementComparator.java

This just drops the generics from the comparator that fixes the issue where a classcast exception was thrown when re-ordering items.

SAK-33419 Simple fix for announcement reordering

---

access/access-impl/impl/pom.xml

The version of commons-fileupload was explicitly set in the access-impl/impl/pom.xml file although would result in it getting used at compile time would result in the newer version getting used at runtime due to the fact that it’s a provided dependency so it uses the shared version from the shared class loader in tomcat.
The used version is defined in master/pom.xml and is currently set at 1.3.3

SAK-33497 Remove conflicting commons-fileupload

---

mailsender/impl/pom.xml

This dependency is no longer used and just increases the size of the
build. This probably remains from when mailsender used to send out email
directly instead of using the kernel's email service.
The activation dependency can also be removed as it isn't directly used
by the code and is correctly pulled in as a trasative dependency.

SAK-33498 Removed unused commons-email dependency

---

kernel/api/src/main/java/org/sakaiproject/time/api/TimeService.java
kernel/api/src/main/java/org/sakaiproject/time/api/UserTimeService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/LocalTzFormat.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/MyTime.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/MyTimeBreakdown.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/UserLocaleServiceImpl.java
kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/UserTimeServiceImpl.java
kernel/kernel-impl/src/main/webapp/WEB-INF/components.xml
kernel/kernel-impl/src/main/webapp/WEB-INF/time-components.xml
kernel/kernel-impl/src/main/webapp/WEB-INF/util-components.xml

This splits out a new API called UserTimeService which is just responsible for getting the user’s timezone at the moment. This allows the main TimeService to be deprecated and any place that uses TimeService to just get the user’s timezone can switch to using UserTimeService.
This also makes the current TimeService more testable as it doesn’t actually need the whole kernel to be running, just mock instances of 2 helpers that can be easily mocked with Mockito (or similar).
This also makes the classes more focused (Single Responsibility Principal).

KNL-1554 Refactor of time service to aid deprecation

---

content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm

Fixes bug found in https://jira.sakaiproject.org/browse/SAK-33264, where the properties div can be expanded and out of sync with the properties toggle after clicking add another folder/link.

SAK-33264 ensure properties is collapsed when adding multiple folders/links

---

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java

Hibernate will throw an exception if there is no current session.

SAK-33515 Wrapped hibernate flush in try catch

---

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js

Disable the Wicket/browser behavior that triggers click on the form's first button after a 'return' keypress within the filter input field.
https://jira.sakaiproject.org/browse/SAK-33410

SAK-33410 'Filter Students' activates the 'Add Gradebook Item' panel on return

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java

Gradebook NG is not usable in locales with comma separator, GBNG-3390 wasn't merged back to 11.x and now differs from Master.
The resolved issues for Master that cannot be merged back to 11.x, must be resolved directly for 11.x.

SAK-33572 - GBNG-3390 - FIX I18N - GradebookNG crashes when you type comma in a grade

---

site/admin-perms-tool/src/main/java/org/sakaiproject/adminsiteperms/service/SitePermsService.java

Rather than just looking for a set list of templates we ask the SiteService what all the known templates are. We then use these template to get an idea of what roles exist in the sites.

SAK-33578 Load the auth templates dynamically.

---

basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm

In order to populate the department dropdown the LTI Admin tool was loading all sites in the system. The fix is to no load this dropdown and just have a text search field. The alternatives would have been to have go directly to the site tables and query the columns there (but then we end up with direct binding across services), or to have added stuff to the SiteService API to load distinct property values for a property key.
Growing the SiteService API would have been the cleanest solution, however I’m not sure the extra complexity is worth it for this feature.

SAK-33564 Don’t load all sites in the system.

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java

I've made the 11.x PR because Master has diverged and it's not affected by this issue.

SAK-33572 - The grades appear with the point as separator, it should use the user's locale

---

content/content-tool/tool/src/webapp/WEB-INF/tools/sakai.dropbox.xml

This prevents people without a dropbox permission from seeing the dropbox tool in the site. Dropbox has an issue where it will allow people who don’t have this permission to have a folder created for them when they access the site, however this folder doesn’t have any of the normal dropbox permissions or display name set.

SAK-14766 Only people with permission see dropbox.

---

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTISubstitutionsFilter.java
basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/SampleLTISubstitutionsFilter.java
basiclti/basiclti-impl/src/webapp/WEB-INF/components-demo.xml

This allows local deployments to customise the LTI substitution
properties that are used for custom property subsitution.

SAK-33561 Support for filter custom properties.

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java

The checkReference method will crash with the '/' character, I think it's not needed. 
There was also missing an update on the attachments list of the new assignment.
Plus I have removed nAttachments parameter from the header, as it wasn't actually used anymore.

SAK-33594 transfer attachments on assignments when importing from site

---

assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java

Putting as commented old values with '.' for clarity.

SAK-33602 solved test problems with not-default decimal character

---

assignment/impl/src/java/org/sakaiproject/assignment/persistence/AssignmentRepositoryImpl.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

The ungraded count was wrongly checking 'graded -> true' cases.
Also, userSubmission should be set to default as true (SAK-29314), otherwise it will always be 0 and the total count won't work.
Finally, looking at the old behavior (11.x for example), I guess we should check the submitted date field for both cases too.

SAK-33593 Solving issues related with in/new submission count

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm

Also, the "No submission" message already appears on a different column (status), so would be redundant here.

SAK-33612 don't show submitted date if there's no submission

---

kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/FormattedTextImpl.java
kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/FormattedTextTest.java

I applied our 11.x patch to master, seems to work OK.

KNL-1567 FormattedText exception for page anchor links when adding target blank

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java

Query didn't handle excepted late allowed cases (and would be a chore to do it inside the query), so we decided to remove some verifications from there and check it all later. Now we think every situation is considered.
But all that logic is a bit tricky, so any kind of suggestions are obviously welcome.

SAM-3313 autosubmit job needs to process excepted late allowed cases

---

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

Talked with Earle and he agreed the hasBeenSubmitted method is not necessary anymore. Submitted field and submitted date cover all cases.
I have also added one test method for the peer assessment dates.

SAK-33657 improve submitted checks and remove useless method

---

kernel/api/src/main/java/org/sakaiproject/user/api/ExternalUserSearchUDP.java
providers/sample/src/java/org/sakaiproject/provider/user/SampleUserDirectoryProvider.java

This allows the SampleUserDirectoryProvider to return users when a search is performed for users. Previously there was no way to search for these users apart from knowing one of the IDs on them.
This makes testing Sakai easier as you can see how it behaves when deployed with a user provider that supports searching.

SAK-33647 Allow searching for sample users.

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages_pt_BR.properties
user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
user/user-tool-prefs/tool/src/webapp/js/manage-hidden-sites.js
user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp

https://jira.sakaiproject.org/browse/SAK-33662
The skin is not truncating the site title in any place.
In Sakai 11/10 the site title was truncated in some places to avoid use too much space.
In Sakai 12/13 this truncate process is completely removed.
See the screenshots in the JIRA ticket.

SAK-33662: abbreviated site title missing in Sakai 11.5+

---

kernel/api/src/main/java/org/sakaiproject/memory/api/ehcache.xml
kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml

There were previously caches defined in the memory service’s ehcache.xml file, but this doesn’t appear to be being used as Hibernate is starting it’s own cache manager. This moves the hibernate caches to a hibernate specific cache configuration and points the caching factory at it.
This also gets rid of the WARN messages at startup about this.

KNL-1572 Load caches for hibernate.

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm

Only show them when inline text is allowed and there's text (ck editor) or there isn't/is draft (message).

SAK-33678 hide ck editor/message in instructor view

---

kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java

When sending a message out we log useful values to aid in debugging. However with the recent re-writing of From: addresses we were logging the original values, rather than the re-written values so the log entries don’t act as a good audit of what got sent.
As we now rely on the replyTo header more because of our re-writing I’ve added that as a header that’s logged as well. This will also help in debugging as it often includes details of the user who performed the action when the from address gets re-written.
Rather than passing in additional values just to be logged we just look directly at the message, this should make it less likely in future that the logged data is different from data used to send the mail.

KNL-1573 Log actual values in the Message

---

lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/ChecklistItemStatus.java
lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
lessonbuilder/components/src/webapp/WEB-INF/components.xml
lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/ChecklistItemStatusId.java
lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/ChecklistItemStatusImpl.java
lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/checklistitemstatus.hbm.xml

The composite ID should be in it’s own class so that it’s equals and hashCode can work correctly. This doesn’t seem to have any affect on Sakai apart from fixing the startup warning about a composite ID class not overriding hashcode() and equals().
This may have caused some caching issues, but I didn’t investigate.

LSNBLDR-910 Split the composite ID into it’s own class

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/renderer/TimerBarRenderer.java
samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp

Basically we have reformatted the process once the end time is reached: the redirection takes place and THEN the message is shown. It makes no sense to throw a timeout on the delivery screen because it was allowing users to change answers during that time.

SAM-3174 avoid students answering during timeout messages

---

assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentAllPurposeItem.java
assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentAllPurposeItemAccess.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

Quite a few different things where needed here: firstly id and hide fields couldn't be null, so we initialized them (as hide has to be updated later, we just put a default value).
Then there was a weird infinite loop:
_at org.sakaiproject.assignment.api.model.AssignmentAllPurposeItem.hashCode(AssignmentAllPurposeItem.java:39)
at org.sakaiproject.assignment.api.model.AssignmentAllPurposeItemAccess.hashCode(AssignmentAllPurposeItemAccess.java:39)
at java.util.AbstractSet.hashCode(AbstractSet.java:126)
at org.sakaiproject.assignment.api.model.AssignmentAllPurposeItem.hashCode(AssignmentAllPurposeItem.java:39)
at org.sakaiproject.assignment.api.model.AssignmentAllPurposeItemAccess.hashCode(AssignmentAllPurposeItemAccess.java:39)
at java.util.AbstractSet.hashCode(AbstractSet.java:126)_
We …

SAK-33681 some changes to add and edit AllPurposeItems

---

assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/EmailUtil.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/sort/AnonymousSubmissionComparator.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_students_details.vm

Taking a substring from the internal id, like it was done before.
Adding the i18n anon string when needed, instead of by default (to avoid adding a resourcebundle entry inside the API).

SAK-33634 generate anonymous id

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/api/SerializableSubmissionAccess.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/impl/AssignmentSubmissionAccess.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm

The appearances from the SubmissionAccess classes can be directly removed. The other references are keeped in case they're used in the future.

SAK-33683 commenting all submission log appearances for the moment

---

mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java
mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SplitEmailAddress.java
mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java

Have better handling of a client attempting to send an email where the FROM address isn’t an email address that we can parse. This may be because it’s empty or it’s not an email address.

SAK-33684 Handle SMTP FROM that isn’t email better

---

assignment/assignment-api/api/pom.xml
assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/ContentReviewResult.java
assignment/assignment-bundles/resources/assignment.properties
assignment/assignment-bundles/resources/assignment_es.properties
assignment/assignment-bundles/resources/assignment_sv.properties
assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
content-review/content-review-api/model/src/java/org/sakaiproject/contentreview/model/ContentReviewItemUrkund.java

As the content-review API does not offer a method to get only one ContentReviewItem by id, we need to get all reports and store them in a cache indexed by ContentId.

SAK-33617 : Content-review-impl Urkund : Include OptOutUrl

---

assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_students_details.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
webservices/cxf/src/java/org/sakaiproject/webservices/Assignments.java

-Solved different peer revision screen errors. Main problem was a check lost after assignments refactor:
...  && userSubmissionsState.get(0) instanceof SubmitterSubmission ...
which was the reason why many state variables where not being initialized.
-Storing submission reference instead of id for PeerAssessmentItem. Easier to retrieve on the places where it's used (doEdit_review).
-Also converted peer open date to Instant (updated unit tests).
-And removed all references to old AssignmentContent class from different velocity templates.

SAK-33748 solved peer revision screen errors and other refactor issues

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

The line "submission.setUserSubmission(true);" was repeated twice (see line 5958).

SAK-33768 update submittee field value

---

jsf/jsf-widgets/pom.xml
jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ScriptRenderer.java
jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/StylesheetRenderer.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/renderer/ScriptRenderer.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/renderer/StylesheetRenderer.java

When **script** tag (sakai:script / samigo:script) and **stylsheet** tag (sakai:stylesheet / samigo:stylesheet) are included in a Jsf tool, the version and the expired time are included to source path according to _portal.cdn.version_ and _portal.cdn.expire_ properties.

SAK-33798: Version all JS/CSS loaded from JSF tools

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java

Ensures any decimal string from the Gradebook service is displayed with a max 2 decimal places.

SAK-33803 force formatGradeForDisplay to max two decimal places

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm

There is a "Create New Site" option in two spots at the top of Sakai: one in "Sites" and one in the account menu. Since the option is site-related, it makes sense to be in Sites and not with your account.
I have removed the option from the account menu:

SAK-33812 Removed the Create New Site option from the Account Menu

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm

https://jira.sakaiproject.org/browse/SAK-33790
The tooltip (full site title) is missing; look the screenshot in the JIRA ticket. It's displaying ${pwd.fullTitle}. Also the breadcrumbs should be using the truncated site title, not the full site title.

SAK-33790: missing tooltip and truncated site title in breadcrumbs for parent/child site scenarios

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java

https://jira.sakaiproject.org/browse/SAK-33821
In the screenshot (JIRA ticket) is an example. Using the title: "This is a sentence Iám happy"
You could replace á with any special character that you want (but in that position).
In html the title is: "This is a sentence I&aacute;m happy"
This size is bigger than 25 (default max) so it's time to cut the title, the default method is get the first 21 characters and add "..." at the end... so the result is:
"This is a sentence I&..."
But this has no sense because & is a fragment of an html entity. The method should use the original title (not the html encoded one) to get the size and decided how to cut and encode after truncate the title.

SAK-33821: site title is truncated after HTML transformation

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java

https://jira.sakaiproject.org/browse/SAK-33822
Every time a grade is sent to the Gradebook, it outputs grades with identifiers to the logs by default (INFO). We've found this to be an issue for two reasons:
1. it can bloat the logs significantly in certain scenarios
2. its leaking user identifiers and grades to the application server logs OOTB, which can be a security concern
It would be more appropriate to change this logger to DEBUG.

SAK-33822: GradebookServiceHibernateImpl.setAssignmentScoreString() logging level change

---

gradebookng/tool/src/webapp/WEB-INF/tools/sakai.gradebookng.xml

https://jira.sakaiproject.org/browse/SAK-33826
The current tool description for GBNG is:
> The next generation gradebook tool for the Sakai CLE
This isn't the best user facing message for several reasons:
* it doesn't explain what the tool does or it's purpose
* some institutions don't call their instance 'Sakai', and users might not know what either or both 'Sakai' or 'CLE' refers to.
This ticket proposes to change the description to:
> For storing, calculating, distributing, and submitting grades

SAK-33826: update the tool description for GBNG

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java

https://jira.sakaiproject.org/browse/SAK-33835
For students, the URL to the Gradebook that they get is:
>` https://<domain>/portal/site/<siteID>/tool/<toolID>/wicket/bookmarkable/org.sakaiproject.gradebookng.tool.pages.StudentPage`
The proposal here is to mount the URL as "/gradebook", so the URL is more user friendly:
> `https://<domain>/portal/site/<siteID>/tool/<toolID>/gradebook`

SAK-33835: GBNG mount the Student page for more friendly/bookmarkable URL

---

user/user-tool-prefs/tool/src/webapp/prefs/editor.jsp
user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp
user/user-tool-prefs/tool/src/webapp/prefs/locale.jsp
user/user-tool-prefs/tool/src/webapp/prefs/noti.jsp
user/user-tool-prefs/tool/src/webapp/prefs/prefUpdatedMsg.jsp
user/user-tool-prefs/tool/src/webapp/prefs/privacy.jsp
user/user-tool-prefs/tool/src/webapp/prefs/refresh.jsp
user/user-tool-prefs/tool/src/webapp/prefs/timezone.jsp

https://jira.sakaiproject.org/browse/SAK-33824
The verification/success message (green bar, "Your preferences have been updated successfully.") is noticeably larger than it is in other tools in Sakai. It also doesn't look good at smaller/mobile screen sizes.
Improvements:
* don't wrap it in `<h3>`
* remove some inline styles
* standardize location of message
* standardize layout of 'Editor' UI

SAK-33824: standardize the verification/success message in Preferences

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.html

https://jira.sakaiproject.org/browse/SAK-33834
Consider the following Wicket markup:
`<a href="javascript:void(0)" id="showAllGradeItems" role="menuitem"><span wicket:message="value:label.toolbar.gradeitemshowall">Show All</span></a>`
This is only sticking the i18n string (label.toolbar.gradeitemshowall) in the 'value' attribute of the span tag. The text that is actually displayed is the hardcoded value of 'Show All'. If you changed the corresponding message bundle value, the text displayed will remain as 'Show All', and only the text in the 'value' attribute will be changed accordingly.
A more appropriate way to do this is to use a <wicket:message> element for the actual text content:
```
<a href="javascript:void(0)" id="showAllGradeItems" role="menuitem" class="button">
<span …
```

SAK-33834: GBNG isn't using i18l strings in certain places

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java

https://jira.sakaiproject.org/browse/SAK-33832
1. Remove a category; do *not* press 'Save' yet
2. Add a new category, give it the exact same name as the one you just removed
3. Click the 'Save' button
4. Notice you get an error stating "Category names must be unique"
If you were to have clicked 'Save' in between the delete and the add, it would work just fine. However, this is not intuitive to end users, and it may seem as though it's a bug in the system.
This problem is half process/user error, half logic error; however we can make an improvement to avoid this, by reversing the logic in the back end method. Process the deletes first, *then* do the adds.

SAK-33832: edu-services prevent unique category naming error

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java

https://jira.sakaiproject.org/browse/SAK-33827
Categories have colours to delineate the different items/columns within the category. Currently, these colours are randomly generated, and change every time you reset/visit the tool.
For users who associate colours with categories, changing the colours may throw them off each time they come to the page. We've received complaints about this, and have modified the behaviour so that the colour generation algorithm is deterministic. In this way, the colour code does not have to be stored anywhere, and the user will always see the same colours for their categories (unless a category is deleted and recreated with the same name).

SAK-33827: make GBNG category colour selection deterministic

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java

https://jira.sakaiproject.org/browse/SAK-33830
On the "Grades" page, there is a message that appears in the top left beside the "Add Gradebook Item" button that says 'All changes saved." This message shouldn't be there by default; it should only appear after a change has actually been made and saved.
Putting it on the page by default can confuse users as to what it's saving, especially in scenarios where nothing has been changed by the user.

SAK-33830: GBNG's "All changes saved" message shouldn't be on the page by deafult

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java

https://jira.sakaiproject.org/browse/SAK-33833
We had an institutional requirement to hide the 'Grade Entry' panel in GBNG's 'Settings' UI from non-admin users. We found that users were flipping these settings without realizing the consequences, which resulted in a lot of support calls.
We implemented this behaviour behind a new sakai.property (gradebook.settings.gradeEntry.hideFromNonAdmins) which defaults to false to preserve OOTB functionality.
For those who wish to hide this setting from end users, but still be able to make the changes with an admin account, simply set the property to true.

SAK-33833: GBNG new sakai.property to control visibility of 'Grade Entry' panel in 'Settings' UI

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UserIdentificationReport.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedRow.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedSpreadsheetWrapper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ProcessedGradeItemDetail.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/ImportWizardModel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/PreviewImportedGradesPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/PreviewImportedGradesPanel.java
gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
gradebookng/tool/src/webapp/styles/gradebook-importexport.css

https://jira.sakaiproject.org/browse/SAK-33840
This PR introduces three new collapsible panels into the Import wizard. Please see the screenshots in the JIRA ticket.
On the "Gradebook Item Import Selection" UI:
* Students found in the Gradebook, but are not present in the imported file (screenshots 1 & 2)
** This panel allows instructors/maintainers to quickly/visually ascertain if the imported file is missing entries.
* Students found in the imported file, but are not members of the Site/Gradebook (screenshots 1 & 3)
** This panel allows instructors/maintainers to quickly/visually identify bogus entries in the selected file
These two panels allow the user to abort the process early in order to add or remove data as necessary in the imported file, rather than moving completely through the …

SAK-33840: New feature: GBNG > Import > "Omissions" and "Preview Grades" panels

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

Can cause cached entity initialization issues for a lack of a session

SAK-33851 Assignment iterating over submissions outside the service

---

citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
citations/citations-tool/tool/src/webapp/vm/citation/_listNestedCitations.vm

The property is 'citations.enable.sections' and is set to default false on Sakai.

SAK-33809: Collapsible citation sections has a number of issues

---

library/src/morpheus-master/sass/modules/tool/resources/_resources.scss

This would be the state of the icons after this PR
It's not a big deal users that never had used Resources but returning users, used to watch a "plus" and a "minus" on the folder, would be less lost on what's empty and what's not.

SAK-33897 - Restore + symbols in folders (regression)

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ProcessedGradeItem.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/ImportWizardModel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
gradebookng/tool/src/webapp/styles/gradebook-importexport.css

https://jira.sakaiproject.org/browse/SAK-33864
This PR contains several changes to the back-end code that performs the Gradebook Import:
* Reduce the amount of logging performed during the saving routine, change the log level appropriately
** Currently an INFO level log message is produced for each grade, and each comment, for each user in each "sheet" that is processed
** For large imports, this equates to a *lot* of logging statements, which contributes to log bloat and probably reduces performance on some level
** It also could be argued that it's a security concern to log grades and user identifiers at INFO level OOTB
* Bulk save grades and comments per assignment/gradebook item
** The current process saves each grade and each comment for each student in each item serially, and waits …

SAK-33864: GBNG > improve performance of Gradebook Import process

---

.gitignore
kernel/component-manager/src/main/java/org/sakaiproject/util/ComponentsLoader.java
kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml
kernel/kernel-private/src/main/java/org/sakaiproject/springframework/orm/hibernate/AddablePersistenceUnit.java
kernel/kernel-private/src/main/java/org/sakaiproject/springframework/orm/hibernate/AdditionalHibernateMappings.java
kernel/kernel-private/src/main/java/org/sakaiproject/springframework/orm/hibernate/SakaiPersistenceUnitManager.java
kernel/kernel-private/src/main/java/org/sakaiproject/springframework/orm/hibernate/impl/AdditionalHibernateMappingsImpl.java

This at this moment doesn't replace Hibernate LocalSessionFactory but allows the ability to simply switch to the EntityManager via a few bean changes. The idea being one could easily switch to running Sakai using the JPA EntityManager.
One nice feature about this change is that there is no change for tools including contrib tools.
At some future point Sakai will run by default using the EntityManager.

KNL-1583 Replace Hibernate SessionFactory with JPA EntityManager

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java

https://jira.sakaiproject.org/browse/LSNBLDR-940
Western recently ran into an issue where somehow a student page's comment section was deleted (every student page has a comment section by default). We haven't been able to identify exact steps to reproduce the ability to delete the comments section as a student, but the result was that trying to navigate to the student page in question would throw an uncaught NPE. The stacktrace would take over the entire portal, meaning the user had no way to reset the tool, or navigate back to the site without either manually entering the URL, or closing and re-opening their browser, etc.
The problem manifests because the ID of the comments section is stored in the student page object. However, when the comments section gets deleted, the ID for it …

LSNBLDR-940: NPE protection for missing comments section on student page

---

library/src/webapp/content/myworkspace_info.html

Why use gender related pronouns here?
By removing them the sentence is shorter and therefore simpler while removing reference to irrelevant user details.
Thank you for the great project by the way.

Remove workspace welcome pronouns

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/CommentValidationReport.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/CommentValidator.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.java
gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml

https://jira.sakaiproject.org/browse/SAK-33836
This PR will implement a sakai.property to allow configuration of the maximum number of characters allowed in a gradebook item comment. The sakai.property will default to 20,000 characters.
This value will be used for the maxlength attribute of the modal form for viewing/editing a single user's comment. It will also be used for a new comment validation routine for the Import process. This comment validation will inform the user up front which students have invalid comments for which gradebook items in the file, allowing them to correct the problem(s) and re-upload the file without having to go all the way through the wizard.
Please see the screenshots on the JIRA ticket for the Import process comment validation error message, the …

SAK-33836: GBNG > allow configuration of max comment length via sakai.properties

---

kernel/api/src/main/java/org/sakaiproject/event/api/UsageSessionService.java

Stumbled across an API interface method with a wrongly paramterized return type.
Looks like this method isn't used anywhere at the moment, everyone seems to still use the unparameterized static cover instead.
https://jira.sakaiproject.org/browse/KNL-1585

KNL-1585: corrected wrong return type of method (collection type erasure)

---

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemTextIfc.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/MatchItemBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/MatchingBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
samigo/samigo-app/src/webapp/jsf/author/preview_item/Matching.jsp
samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatching.jsp
samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMatching.jsp
samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java

https://jira.sakaiproject.org/browse/SAM-1579
* No points taken off if distractors are incorrectly matched. The points are divided by the correct number of matches. ex:
** 6 matches plus 2 distractors = 6 points
** If the student got 3 correct matches, but got one of the distractors wrong, the student still receives 3 points.
* On the questions screen, if the student does not make an entry (left as 'Select'), there is nothing displayed under the student response unless there is a distractor, in which case the distractor alone shows.
* The answer keys for matching questions with distractors are not displayed consistently between the edit screens and the score screens
** If you create an assessment that allows Immediate Feedback (i.e. student can click a Show Feedback link while in process …

SAM-1579: Matching questions with distractors - Incorrect scoring and display of answer keys in several areas

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
samigo/samigo-app/src/webapp/jsf/print/preview_item/MultipleChoiceSurvey.jsp

https://jira.sakaiproject.org/browse/SAM-2024
The answer options to some Survey type questions do not display correctly, e.g. the option *Strongly Agree* shows up as *st_strongly_agree*.
See screenshots in the JIRA

SAM-2024: Samigo > print assessments with survey questions doesn't display answer options properly

---

calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarImporterService.java
calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/ExternalCalendarSubscriptionService.java
calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/ExternalSubscriptionDetails.java
calendar/calendar-api/api/src/java/org/sakaiproject/calendar/cover/CalendarImporterService.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionService.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalSubscriptionDetails.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/CSVReader.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/MeetingMakerReader.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/OutlookReader.java
calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/Reader.java
calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionTest.java
calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/SubscriptionCacheTest.java
calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java

Calendar tool saves info in tool properties.
**externalCalendarSubscriptions**: tool property for older subscriptions, it contains URL of calendar and a name.
**externalCalendarSubscriptionsWithTZ**: tool property for new subscriptions, it so includes the creator and his time zone.
When calendar subscription is loaded, if the component VTIMEZONE is defined with TZID property, all events will move to *calendar's time zone*.
If VTIMEZONE is not defined in the iCal, all events will move to *owner's time zone*. (Owner's TZ is stored in the new tool property).
If VTIMEZONE is not defined and the calendar owner is not known, the events will move to *current user's time zone*. (It works as before).
Additionally this PR incorporates a fix for SAK-33371.

Fix SAK-33451 and SAK-33371: Save the owner of an external calendar and his time zone.

---

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiLogin.java
webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiLoginLoginTest.java

This looks like it's restores the WSDL to be compatible. Were you previously using a POST with these tasks? I'm not sure if it will take a GET anymore or not. 
There should be methods available, loginGET/logoutGET that are the respective GET methods until/unless we deprecate them.

SAK-34007 - SOAP no longer compatible for login methods

---

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp

https://jira.sakaiproject.org/browse/SAM-3212
There is a use case described in the JIRA ticket that requires the retract date to be null/nullable.

SAM-3212: allow retract date to be null

---

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm

https://jira.sakaiproject.org/browse/SAK-34014
1) Start with browser window at max width
2) Start shrinking
3) Notice there seems to be two breakpoints for the 'mobile' width
3a) The first one retains the link, then shrink the browser a little more
3b) Notice the link disappears, along with the 'Transfer Files' tab at the top
This link should never be hidden; there's no way for a user to access this functionality at small browser widths.

SAK-34014: 'Copy Content from My Other Sites' link still disappears at smallest breakpoint

---

library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_dropdowns.scss

Yes, I'm doing this straight against Bootstrap files, but a) this rule is not in Bootstrap 4 and b) I bet our next move will be to Bootstrap 4 and not another Bootstrap 3 revision

SAK-34015 remove bootstrap rule that removes outline on focus

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/portalCSS-snippet.vm

a link to tool_base.css was removed in 11.x.  Adding it back in seems to fix the formatting issue with the joinable sites dialog

SAK-33397 joinable sites dialog is not styled

---

samigo/samigo-app/src/webapp/js/authoring.js

https://jira.sakaiproject.org/browse/SAM-3180
When you author or edit a Multiple Choice question with Partial Credit enabled, the correct answer's % Value field is not being disabled or set to 100. However, if you save the question with any value other than 100 in the correct answer's % Value field, the question saves ok and, as it should, forces the correct answer's % value to be 100.
More details and steps to reproduce in the JIRA.

 SAM-3180: incorrect behavior of Multiple Choice, Partial Credit in question edit UI

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ErrorPage.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ErrorPage.java

https://jira.sakaiproject.org/browse/SAK-33957
Stack traces are currently shown by default in GBNG. There is a comment in GradebookNgApplication.java that implies this behaviour can be changed:
```
// show internal error page rather than default developer page
// for production, set to SHOW_NO_EXCEPTION_PAGE
getExceptionSettings().setUnexpectedExceptionDisplay(IExceptionSettings.SHOW_EXCEPTION_PAGE);
```
However, flipping this value has no effect because ErrorPage.java does not check which value is being used, and dumps the stacktrace into a Wicket label regardless (it also has a comment that this should be configurable "at some point"):
```
// show the stacktrace. This should be configurable at some point
add(new Label("stacktrace", stacktrace));
```
This PR proposes the following …

SAK-33957: GBNG > make display of stack traces configurable

---

samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp

https://jira.sakaiproject.org/browse/SAM-3113
If a test has both a late acceptance date and auto-submit enabled in its Settings, and a student saves but does not submit the test after the due date, but before the late acceptance date, the Scores screen only displays one flag under the student's submission date: "LATE". To be more accurate, it should display both flags: "LATE", and "AUTO-SUBMIT".
More info in the JIRA ticket.

SAM-3113: when a late test is auto-submitted, Scores screen only shows LATE flag

---

samigo/samigo-app/src/webapp/css/tool_sam.css
samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp

https://jira.sakaiproject.org/browse/SAM-3222
In samigo, when you select Settings > Layout and Appearance > Navigation: Linear access to questions with no return to previous pages, the following other layout options should automatically set and disable so they cannot be changed:
* Question Layout should be set to Each Question is on a separate Web page and disabled
* Add checkboxes next to questions so they can be marked for review should be unchecked and disabled
More info and steps to reproduce in the JIRA

SAM-3222: correct behavior of Question Layout Setting when Linear access is selected

---

edu-services/gradebook-service/api/pom.xml
edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookPermissionService.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookPermissionServiceImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java

PR done against trunk (based on previous PR #4396). Fully tested on local and qa server 
(13-SNAPSHOT - https://sakai-trunk.atica.um.es/portal). It works as expected: 'ta' is able to grade. The students and instructors work ok.

SAK-33103: Users with TA role cannot grade students by default in Gradebook - against master - based on PR 4378

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

Consider a Sakai instance configured with the property:
worksitesetup.filtertermdropdowns=true
Ie. this property controls Worksite Setup -> New -> Course Site, so that the displayed courses are filtered to contain only those in which the user has enrolments
Now, consider an instructor who's about to study a course outside their field. Since the user is an instructor in their own field, they would have the site.add.course permission on their user role (E.g. 'registered'); yet they exist in the new roster as a student. Currently the instructor could go into Worksite Setup-> New -> Course Site, and proceed to create the course site in which they are enrolled as a student. That is, the filtertermdropdowns logic looks at their user role, then searches for any enrolments regardless of the …

SAK-33977 - The worksitesetup.filtertermdropdowns property should refine results further

---

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/EventAggregatorTestPerf.java
sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsManagerTest.java

@adrianfish Would you mind to take a look?
I admit this solution is very radical but correct, use the Lessons API instead of events, events are incorrect in duplicated courses because there are no "create" events.

SAK-32104 - Sitestats - Lessons: number of pages is incorrectly calculated

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java
samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp

https://jira.sakaiproject.org/browse/SAM-3210
New sakai.property to control the visibility of the 'Delete' column for submissions in the 'Scores' UI. If set to true, all sites will by default have the column hidden. This can be overridden on a site by site basis by adding a site property of the same name (samigo.removeSubmission.restricted).
See the JIRA for more information.

SAM-3210: new sakai.property to control visibility of the 'Delete' column for submissions in the 'Scores' UI

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/GradeValidator.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedCell.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/PreviewImportedGradesPanel.java

https://jira.sakaiproject.org/browse/SAK-34054
Currently if you try to import a file in a locale that uses comma as the decimal separator, the import will fail.
The front-end validation routines need some touch ups to be compatible with the comma decimal locales.

SAK-34054: GBNG > Import > fix front-end validation for comma decimal locales

---

msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml

When browsing through the statistics UIs in Forums, you'll get a few NPEs resulting from bean properties that haven't been injected. This patch isn't comprehensive, just fixing a few I've encountered while poking around; it may be advisable for someone to go through some of these forums beans and ensure all their properties are injected in faces-config.xml

SAK-34056 - NPEs in Forums' Statistics UIs

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
roster2/src/java/org/sakaiproject/roster/api/SakaiProxy.java
roster2/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
roster2/src/java/org/sakaiproject/roster/tool/RosterTool.java
roster2/src/webapp/WEB-INF/bootstrap.jsp
roster2/src/webapp/js/roster.js

https://jira.sakaiproject.org/browse/SAK-34057
For those institutions that have policy around what information students and/or faculty have access to, this proposed sakai.property allows locking down the "Permissions" widget in Roster to admin users only.
In this way, the administration team can set desired permissions in course/project/etc. site templates, set the sakai.property to false, and be assured that maintainers will not be able to change the default permissions via the widget in the tool.
The sakai.property introduced here is "roster.showPermsToMaintainers", which defaults to "true" to preserve OOTB functionality.

SAK-34057: roster > new sakai.property to control visibility of 'Permissions' widget

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UserIdentificationReport.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java

https://jira.sakaiproject.org/browse/SAK-34061
For consistency, the missing students panel should display both the IDs and the names of the students found in the file who are not members of the site.

SAK-34061: GBNG > Import > Omissions panels > missing students list should display student names from import file as well as IDs

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java

https://jira.sakaiproject.org/browse/SAM-3392
We ran into an issue recently in our production environment where a user was not able to access the Statistics or Export pages of a published quiz. The failure was caused by an uncaught ArrayIndexOutOfBoundsException in HistogramListener.doAnswerStatistics() (stack trace in the JIRA).
After investigation, we found that the cause of this was a specific question in a question pool the quiz was drawing from. The offending question had no type, no question text, and had no answers (or really any information at all); it was a 'shell' of a question.
We were unable to reproduce any situation that would allow us to create such an erroneous question. So we're not sure *how* the question came into existence, but putting in a simple size check allows the …

SAM-3392: ArrayIndexOutOfBoundsException protection in HistogramListener.doAnswerStatistics()

---

assignment/bundles/resources/assignment.properties
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm

https://jira.sakaiproject.org/browse/SAK-34082
When selecting 'Use peer assessment', you'll see the following information message underneath the setting:
> Peer assessment requires a points grading scale and do not allow group assignments.
The message has some grammatical issues, and is more appropriately styled as messageInformation.

SAK-34082: Assignments > update wording and styling of peer review information message

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm

https://jira.sakaiproject.org/browse/SAK-34081
For Attachments Only and Single File Upload assignment types, there is a check on modification of the attachments when a student hits the submission page for a resubmission. It presents a message and disables the Submit button until the attachment list is modified. This check was broken by the assignments refactor, and will always allow resubmission even if there are no changes.

SAK-34081: Assignments refactor regression: resubmission modification check doesn't work

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-34083
If you apply a non-valid grade to submissions, that invalid grade is saved to the database and will remain in the text box.
* in an assignment using a points grading scale, go to the submission list interface
* enter non-numeric characters into the "Apply this grade..." field (as if you were searching for a student, but using the wrong field)
* hit the "Apply" button
* notice the validation message indicating that the value is invalid
* notice the invalid value remains in the text field
* notice the invalid value is persisted even if you log out, clear cache, or log in as another maintainer
The order of operations here needs to be altered: validate the value before saving it.

SAK-34083: Assignments > invalid values are persisted for the default no submission grade

---

content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
content-review/impl/turnitin/src/main/resources/turnitin.properties

I believe this is older @bbailla2 code from TII-157 that didn't make the re-org in 12.0 for some reason.

SAK-34091 code from the TII-157 patch that didnt seem to make the ContentReview re-org

---

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-34076
In it's current form, members of joinable sites will be presented with an "Unjoin" button when they visit the Site Info tool of the given site. When the user clicks the button, the page refreshes and the button is disabled. It's unclear what happened, as there is no messaging to the user. In actuality, there is a message that's supposed to be displayed, but it's not. This PR proposes the following changes:
* rename message bundle keys appropriately
* fix grammar of the message bundle values
* provide a link to the user's Home site in the "success" message
* provide messages for each of the error possibilities
* remove the refreshing behaviour so the messages are are actually seen by the user

SAK-34076: Site Info > improve the 'Unjoin' joinable site process

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp

https://jira.sakaiproject.org/browse/SAM-1384
For multiple submission assessments, there's a _View_ drop-down menu available in the _Scores_ screens to select either *All Submissions* or the *[Recorded Submission/Score]* (the latter button's name depends on the setting for _Recorded Score If Multiple Submissions per User_).  However, if an assessment ONLY allows *1 submission* (as do most assessments), the drop-down menu is not present.  If the instructor chooses *Allow Retake* for a student, the student's second submission cannot be viewed side-by-side with their original submission UNLESS the instructor changes the test settings to allow at least *2 submissions* for ALL students.  Absence of the drop-down for the instructor when a retake has been submitted can be a greater problem for …

SAM-1384: remove restriction that 'View' dropdown should only be shown if quiz allows multiple submissions

---

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-type.vm

https://jira.sakaiproject.org/browse/SAK-34090
In 'Worksite Setup' > 'New', there is a radio button labeled "Build your own site". The intention is that you can choose to create a site from a pre-built template.
In 10.3, this radio button was surrounded by a conditional:
```
#if ($templates.size > 0)
...
#end
```
This conditional was removed in the 11 code base (SAK-25867), causing a regression whereby the radio button will always be displayed, even if there are no templates to build a site from.

SAK-34090: Worksite Setup > New > 'Build your own site' radio button conditional regression

---

user/user-tool-prefs/tool/src/webapp/css/prefs.css
user/user-tool-prefs/tool/src/webapp/prefs/editor.jsp
user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp

https://jira.sakaiproject.org/browse/SAK-34096
In SAK-28975, work was done to standardize the buttons on the various UIs. However, the "Sites" UI was introduced as a replacement for the "Customize Tabs" UI, and a new UI was introduced: "Editor". These two new UIs are missing the primary active buttons.

SAK-34096: Preferences > missing active primary button for 'Sites' and 'Editor' tabs

---

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm

This would be the change
Before:
After:

SAK-34106 - In resources, warning message shows as success

---

library/src/morpheus-master/sass/modules/navigation/_base.scss
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm

https://jira.sakaiproject.org/browse/SAK-34098
For consistency, reinstate the quick tool dropdown for the 'Home' site. This feature was removed in Sakai 11, but I can't think of a good reason for why it was removed. 'Home' is still a site, which contains tools, and just like all other sites users may prefer jumping directly to a tool in the site rather than having to navigate to the site, wait for the site to load everything, and then pick the tool they want.

SAK-34098: Portal > reinstate the quick tool dropdown for the 'Home' site

---

content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
kernel/kernel-util/src/main/java/org/sakaiproject/content/util/IdUtil.java

There were multiple copies of the same method across multiple files in the codebase, although this method is small putting them all the kernel utilities project means new uses can call them and all the existing copies can be removed.

SAK-38304 Consolidate isolateContainingId()/isolateName() methods

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java

I'm thinking we should disable this in all branches by default. 
It sounds like on the list this isn't working.
I always considered this an experimental feature, especially the video part which relies on either setting up our/your own STUN server or hoping the default (Google's) is working right. 
I can still leave this on the experimental properties.

SAK-37348 - Disable portal chat by default

---

library/src/morpheus-master/sass/base/_defaults.scss

https://jira.sakaiproject.org/browse/SAK-34095
Currently has some styling issues:
* there's a weird underline underneath the title
* the "group box" border doesn't go all the way to the right side of the title
See before/after screenshots on the JIRA ticket.

SAK-34095: Improve the styling of the fieldset legend

---

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java

https://jira.sakaiproject.org/browse/SAK-34088
Duplicating forums/topics that are in a draft state creates the duplicates in a published state. This is unexpected for the user and may lead to unwanted publishing of forums/topics.
Duplicated forums/topics should retain the state of the original.

SAK-34088: Duplicate draft forums/topics should duplicate as draft

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java

https://jira.sakaiproject.org/browse/SAK-38431
Some gradebook pages check the user's role and redirect them appropriately if they attempt to visit a page they aren't allowed to access. However, not all pages have these checks, which leads to error messages in some cases. Add checks to all remaining pages that are missing them.
In general:
users with no gradebook permissions are redirected to the access denied page
students are redirected to the student page
TAs are redirected to the grades page

SAK-38431: Add role checks and redirects to all gradebook pages

---

gradebookng/tool/src/webapp/scripts/gradebook-connection-poll.js
gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js

(concurrent edits/server ping) so that the user session lastAccessedTime is not bumped (#3584)
SAK-38438 Moved previous changes to new file locations - David Bauer <dbauer1@udayton.edu>

SAK-38438 re-add auto=true to the GradebookNG AJAX polls 

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
edu-services/gradebook-service/sakai-pack/src/webapp/WEB-INF/components.xml

https://jira.sakaiproject.org/browse/SAK-38440
Currently if a quiz is linked to the Gradebook, and the "Last" option is enabled to send the latest grade to the gradebook (as opposed to "Highest"), if the grade achieved on new attempts is the same as the grade already recorded in the gradebook, the record is not updated. This presents a problem in certain situations where the quiz is a requirement to obtain certification, because the date of completion is not updated in the Gradebook. The result is that users retaking the quiz don't receive an updated certificate with a new expiry date.
There is a related sakai.property (gradebook.externalAssessments.updateSameScore), which when set to true forces the Gradebook record to be updated even if the scores are the same. This resolves the issue …

SAK-38440: edu-services > implement site property to override 'gradebook.externalAssessments.updateSameScore' sakai.property

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java

https://jira.sakaiproject.org/browse/SAK-39928
When students navigate over questions without making changes, there are certain question types that update `SAM_ITEMGRADING_T` entries with nothing more than a new date stamp. In situations where there are a lot of questions in a quiz, with a lot of students taking the quiz at the same time, this can lead to poor performance at the database level. We found that in at least one case this code was responsible for putting full table locks on `SAM_ITEMGRADING_T` in high succession, which resulted in blocking hundreds of connections to the database. These blocking connections had to be killed manually by our DBA for the process to recover.
We identified three specific question types with high usage that exhibit this behaviour: fill in the blank, …

SAK-39928: samigo > minimize redundant UPDATE queries on SAM_ITEMGRADING_T

---

syllabus/syllabus-app/src/webapp/js/syllabus.js

This change was already made in 0249d876 but got (probably accidentally)
reintroduced in 7a8ef643
It removes the scrolling when clicking on the header of a syllabus item
to expand it. This resulted in a determined scrolling to the bottom of
the page when the "expand all" button was used.

SAK-31988 removed scrolling when expanding a syllabus item

---

samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java

https://jira.sakaiproject.org/browse/SAK-39970
The following issues/inconsistencies occur in the Published Copies edit screens:
1) The letters are shown before the numbers, e.g. A:1, B:2, etc. instead of vice versa (numbers ought to come before letters)
2) The None of the Above answers are missing a letter in front of them in the question text, and in the answer key, they show nothing.
3) If there's more than one None of the Above answer, the answer key doesn't show them at all.
Screenshots in the JIRA.

SAK-39970: samigo > published copies > edit > inconsistent display of answer keys and distractors for matching questions

---

basiclti/basiclti-portlet/src/java/org/sakaiproject/portlets/IMSBLTIPortlet.java
lessonbuilder/tool/src/webapp/templates/IFramePage.html
lessonbuilder/tool/src/webapp/templates/ShowItem.html
lessonbuilder/tool/src/webapp/templates/ShowPage.html
web/web-portlet/src/bundle/vm/main.vm

Links in the JIRA if you want to know more:
https://jira.sakaiproject.org/browse/SAK-39946
Basically: browsers hate iframes these days because advertisers abuse them.

SAK-39946 allow trusted iframes to use camera or microphone

---

postem/postem-app/src/webapp/postem/create_gradebook.jsp
postem/postem-app/src/webapp/postem/delete_confirm.jsp
postem/postem-app/src/webapp/postem/verify.jsp

https://jira.sakaiproject.org/browse/SAK-39986
Submitting some forms in postem twice via a double-click action can lead to unique constraint violations. Buttons should be disabled on first click and present the spinner image to indicate processing, as is done in other tools.

SAK-39986: Prevent double-click-induced unique constraint violations in Postem

---

library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
portal/portal-impl/impl/src/bundle/sitenav.properties
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/roleSwitch-snippet.vm

A few explanations:
1) aria-label: submenu isn't descriptive so remove
2) aria-haspopup: only set if we are in mobile mode
3) Try to return focus back to #roleSwitch 
4) aria-label: explain the select box

SAK-38337 explain role switch to assisted users

---

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CategoryScoreData.java
edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGradeInfo.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css
gradebookng/tool/src/webapp/styles/gradebook-grades.css

https://jira.sakaiproject.org/browse/SAK-33108
Basic implementation overview:
The student data sent to the client now has a string of flags to
indicate which cells are marked as dropped (this mirrors the string of
flags used to indicate which cells have comments).
Retrieving the category score now also retrieves a list of gradebook
items that were dropped from the calculation because of the
category's drop highest/lowest settings. This list is used to set the
flags on the student.
When a cell is rendered on the client, it checks the flags and if it
finds the cell was dropped, it is given a particular css class.
When a cell is updated and the category score is recalculated, the drop
state for each cell in that category (for this student only) is
re-evaluated and the cells are redrawn to …

SAK-33108: Provide visual indicators for dropped scores in categories

---

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
basiclti/basiclti-impl/src/bundle/ltiservice.properties
basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
basiclti/web-ifp/src/bundle/iframe.properties
basiclti/web-ifp/src/bundle/vm/edit.vm
basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm

https://jira.sakaiproject.org/browse/SAK-39930
The LTI tool setup interface has settings to "Allow [setting] to be changed", with the options of "Do not allow" and "Allow". However the custom icon setting does not have these corresponding options. This PR implements these options for the custom icon setting, as well as the following changes:
* new behaviour to skip the tool configuration step (when adding the LTI tool to a site manually, through "Manage Tools") if all settings have been set to "Do not allow". This also overrides the behaviour of the "[Show/Bypass] configuration dialog" configuration setting, in that if "Show configuration dialog" is selected the end user will not be presented with the configuration dialog if no settings are able to be configured (all settings have been …

SAK-39930: BasicLTI > extend 'Allow'/'Do not allow' configuration options to the custom tool icon setting

---

kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java

Make ContentItem work without requiring session.parameter.allow
by adding a finer grain regex based on the URI.
session.parameter.allow.bypass=sakai.basiclti.admin.helper.helper

KNL-1590 - Add session.parameter.allow.bypass

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/HistogramScoresBean.java

..the current and previous item progressively
Fixed by clearing the stringbuilder before creating the next item's display string.
I originally wanted to fix this in 11.4/11.x because that's what we use; but it looks like the file hasn't been altered since at least 11.4, so it should be possible to cherry-pick it 1:1 into older branches.

SAK-34181: Statistics / part dropdown list concatenates..

---

kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml

This used to be used to separate file uploads/downloads from using all the connections in the pool, but it isn’t used any more and can be removed.

SAK-40012 Remove the longDataSource

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-39994
In assignments, when you use the "Assign this grade to participants without a grade" feature and assign a decimal value, the grades are applied correctly, but the "Assign this grade..." text field is re-populated with the input value multiplied by 100.

SAK-39994: assignments > assign grade to participants without a grade, decimals multiplied by 100 (display issue)

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSiteRemovalServiceImpl.java
edu-services/cm-service/cm-impl/hibernate-pack/src/webapp/WEB-INF/components.xml
jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSiteRemovalJob.java
kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSql.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSqlDefault.java
kernel/kernel-impl/src/test/java/org/sakaiproject/site/impl/SiteServiceTest.java
kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/BaseDbFlatStorage.java

The Course Site Removal job's default configuration is to unpublish sites.
In our seven years of working on Sakai at Western, it's safe to say that this piece has the... 'least optimal' performance. Once, we ran this in our QA environment and got sidetracked; it completed after 12 days of execution.
A big part of this is that it invokes siteService.save(site) has a lot of slow performing hooks (as once might expect, you're saving a whole site afterall!). These hooks include:
- triggering SiteAdvisors
- deleting all pages, tools, properties, etc., associated with the site, then inserting them all back with any modifications
- handling authz group changes
- notifying ContextObservers to do their own work related to the site modification
- triggering EventTrackingService
These are important …

SAK-39934 - Improvements wrt unpublishing sites with the Course Site Removal job

---

kernel/api/pom.xml
kernel/api/src/test/java/org/sakaiproject/util/RequestFilterTest.java
kernel/api/src/test/java/org/sakaiproject/util/ToolListenerTest.java
master/pom.xml

Please, note that org.powermockito is in BETA. This is due cause there is no stable version that support JDK9 or more.
Also, one unnecesary stubbing has been deleted.
So now, kernel/api tests pass on JDK9

SAK-40004 Updated Mockito Libs

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

SAK-40063: You can't deactivate "Assign Grade Overrides" in a "Group Submission - One submission per group" assignment 
If the new grade is different to the old grade you have to set the new grade. It doesn't matter is g is NULL.

SAK-40063: You can't deactivate "Assign Grade Overrides" in a "Group Submission - One submission per group" assignment 

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/SiteEmailNotificationAnnc.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

description in subject when notifying an announcement via email

SAK-40081 - Allow to decide whether to use title site or short

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm

This is caused because  `value_feedback_text` is null

SAK-40090 - Textarea appears when grading a submission without text and/or unsubmitted

---

library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss

On the create or edit pages for groups in Site Info, there are two multi-select menus for moving participants in and out of a group. If either select menu has participants with short names or no participants at all, the menus collapse to a thin tall box.
My fix changes the width of the menus to take up the full width available in their columns, so they are equal and uniform. I also removed the drop-down arrow used by standard select menus:
It also looks better in the narrow mobile view:

SAK-40111 Fixed the width of the group membership select menus in Site Info

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-40136
ScoringService is not currently compatible with group assignments. Let's hide the user facing icon in these situations.

Assignment > hide scoring component icons for group assignments

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
gradebookng/tool/src/webapp/styles/gradebook-grades.css

https://jira.sakaiproject.org/browse/SAK-39978
Most Sakai tools could benefit from having a welcoming empty state that establishes the tool and suggests next steps for site maintainers. Gradebook, Announcements, Syllabus, Resources, Assignments, Tests & Quizzes, Email Archive, Polls, PostEm, Search, and Sign-up are all good examples of tools needing a default empty state.
When we upgraded to Sakai 11, we created an empty state for our local GBNG because early user feedback showed that the lack of the student listings caused people to think that there were no students enrolled in the site.

SAK-39978: Develop an empty state for Gradebook to better orientate and guide user

---

commons/impl/src/java/org/sakaiproject/commons/impl/PersistenceManagerImpl.java

Updated SQL statements to remove the "AS" keyword for table aliases. This is allowed in mySQL but not in Oracle.

SAK-40151 commons SQL does not work on Oracle

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
simple-rss-portlet/src/main/webapp/WEB-INF/sakai/simple-rss-portlet.xml
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-40210
When you add the News tool to a site, it has a default "URL Channel" of "http://sakaiproject.org/feed". If you leave this default as the link for the feed and go to the News tool (after adding it), you'll get the following error:
>     An error has occurred
>     No data was returned from the remote server. Please ensure the URL added is correct.
as seen in the following screenshot:
This is bad for a default.
The problem seems to be that "http://sakaiproject.org/feed" redirects in a web browser to "https://www.sakaiproject.org/feed" (note the "s" in "https" and the "www." part have been added).
I grepped the Sakai codebase for "http://sakaiproject.org/feed" and replaced it with "https://www.sakaiproject.org/feed" so the defaults would resolve …

SAK-40210 Updated default Sakai Project feed address for the News tool

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/modules/tool/_base.scss

https://jira.sakaiproject.org/browse/SAK-40208
Some tools use .page-header containing a h1 (or h3) tag for displaying the title of the page at the top of the page (below the tools' page tabs).
The spacing of this page header and header texts needs to be tightened up, so the content appears on the screen sooner and so more content can appear on the screen.
Not all tools use the same markup structure, so won't all benefit from this change. However, as tool consistency is rolled out in other tickets, they too will benefit from this change.

SAK-40208 Tightened up default page header spacing around page title

---

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
library/src/morpheus-master/sass/modules/tool/resources/_resources.scss

https://jira.sakaiproject.org/browse/SAK-40222
It can be easy for users to miss the 'Paste' icon when they're not familiar with the UI. Let's add some accompanying text to the icon to help draw attention to it, and also to clarify it's function.

SAK-40222: resources > add accompanying text to the 'Paste' icons

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm

https://jira.sakaiproject.org/browse/SAK-40220
In the table found on the "Assignment List by Student" page in Assignments, there are h4 and h5 tags used inside of the table. It looks like they've been added to help divide up the table of students based on the expanding student assignment list functionality that the table uses.
These section header tags are wrong for two reasons:
1. the content page has an h1 tag, but no h2 or h3 - [header tags should be sequential and form a hierarchy](https://developer.mozilla.org/en-US/docs/Web/Guide/HTML/Using_HTML_sections_and_outlines#Defining_sections)
2. [the markup is invalid](https://stackoverflow.com/questions/11859671/are-h1-html-heading-allowed-inside-a-table-th-or-td-tag)
I have removed the h4 and h5 tags from the markup.

SAK-40220 Removed the h4 and h5 tags from the Assignment List by Students table in Assignments

---

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
content/content-tool/tool/src/java/org/sakaiproject/content/tool/SiteEmailNotificationDragAndDrop.java

https://jira.sakaiproject.org/browse/SAK-40211
The opening line of the current emails sent (when new resources are added or existing resources are updated) is always plural regardless of how many resources were added or updated:
```
Several new resources have been added to ...
```
```
Several resources have been updated in ...
```
This PR changes the behaviour to be plural or singular based on how many resources were added/updated:
```
anewresDnD = A new resource has been added to
anewresDnD.plural = {0} new resources have been added to
anewres2DnD = A resource has been updated in
anewres2DnD.plural = {0} resources have been updated in
```

SAK-40211: resources > improve accuracy of new/updated resources email notification

---

signup/tool/src/bundle/signupConfig.properties

Add default value for signup.default.email.selected (all)
Avoids the WARN message in logs,
26-Nov-2017 23:27:44.522 WARN [http-nio-20013-exec-9] org.sakaiproject.util.ResourceLoader.getString bundle 'signupConfig'  missing key: 'signup.default.email.selected'  from: org.sakaiproject.signup.tool.util.Utilities.getSignupConfigParamVal(Utilities.java:499)

SAK-32655 Default property for signup email notification

---

mailarchive/mailarchive-tool/tool/src/bundle/email.properties

https://jira.sakaiproject.org/browse/SAK-40230
The current message shown in Email Archive implies there will always be multiple aliases:
```
lis.emasen    = Email sent to the following addresses will be archived and sent to participants:
lis.emasen2   = Email sent to the following addresses will be archived:
```
Let's clarify that there could be one, or many:
```
lis.emasen    = Email sent to the following address(es) will be archived and sent to participants:
lis.emasen2   = Email sent to the following address(es) will be archived:
```

SAK-40230: Email Archive > clarify email alias can be one or many

---

lessonbuilder/tool/src/webapp/css/Simplepagetool.css

This fixes the issue for Firefox (wasn't an issue in Chrome). I'm not exactly sure why. Anything 5px and above breaks Firefox alignment for the edit when using multiple columns. I feel like a better fix would involve changing the HTML that Lessons is writing out or changing this use the bootstrap grid for multi column instead of these column hacks.

SAK-37795 - Columns in Firefox show bottom section in its own section

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/base/_defaults.scss

https://jira.sakaiproject.org/browse/SAK-34097
Disabled checkboxes and radio buttons are currently indistinguishable from enabled ones, aside from the icon change when hovering over them. This isn't the most intuitive paradigm. The disabled controls should be visibly different from those that are enabled:
* apply a lighter shade of grey to the checkboxes, radio buttons, and their respective labels
* apply the no-selection icon to both the controls and their respective labels

SAK-34097: Style the disabled checkboxes and radios (and their labels) to distinguish them from enabled ones

---

velocity/tool/src/templates/VM_chef_library.vm

https://jira.sakaiproject.org/browse/SAK-40239
All Velocity tools that make use of the #toolbar macro to display the top menu bar have a styling problem with the "active" tab. See attached screenshot; notice active tab has grey inner background (bug), is clickable (bug), and has hover state styles (bug).

SAK-40239: Velocity > #toolbar macro needs updating for active tab styling

---

kernel/api/src/main/java/org/sakaiproject/javax/PagingPosition.java
velocity/tool/src/java/org/sakaiproject/cheftool/PagedResourceActionII.java

https://jira.sakaiproject.org/browse/SAK-40240
All Velocity tools using PagedResourceActionII which have a table of data, a paginator component and one or more filter components (search, group/section filter, etc.) are susceptible to generating IndexOutOfBoundsExceptions. The logic to validate page number and page size is slightly flawed.
An example can be seen in Assignments:
1. Ensure you have 6 or more students/access users in your site
2. Create a group with only one student/access user
3. In Assignments, create a few bare bones assignments
4. Go to 'Grade Report' (warning, this UI takes a long time to load if you have a lot of users and/or assignments and/or submissions)
5. Use the paginator to scroll to the 2nd page of results (change page size if necessary)
6. Use the filter drop …

SAK-40240: Velocity > fix IndexOutOfBoundsException possibilities in PagedResourceActionII

---

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm

https://jira.sakaiproject.org/browse/SAK-40252
SAK-29342 introduced an 'Unjoin' button for joinable sites, but its location is unfortunate. It's located between the 'Modification date' and 'Modified by' fields which should appear together as they are closely related.
The linked PR makes the following changes:
* Move the 'Unjoin' button to the bottom row of the table on the 'Site Info' landing page
* Change the button text from 'Unjoin' to 'Unjoin this site'

SAK-40252: Site Info > Improve location and language of 'Unjoin' button

---

kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/BasicConfigurationService.java

https://jira.sakaiproject.org/browse/SAK-40249
Currently if you want to load some sakai.properties with either getStringList() or getPatternList(), the sakai.property must be defined as a single property with comma separated values:
```
propertyName=value1,value2,value3
```
If your list of values is really long (long text values, long or numerous regex patterns, etc.), the resulting property can be difficult to read and manage. Although the .count style of defining sakai.properties is "old", it can be really beneficial for situations like these to clean things up:
```
propertyName.count=3
propertyName.1=reallyLongValueWithOrWithoutRegex
propertyName.2=reallyLongValueWithOrWithoutRegex
propertyName.3=reallyLongValueWithOrWithoutRegex
```
It's a relatively minor change to getStringList() …

SAK-40249: Kernel > allow more flexibility in defining sakai.properties loaded with getPatternList() or getStringList()

---

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java

Seems like Lessons was already doing this 
https://stackoverflow.com/a/17027553/3708872
Just not catching this new exception? Maybe this pattern will need to be used more often? I'll defer to the JPA experts. I tested and this is working though to allow for deletion again.

SAK-40264 - Cannot delete item in lessons

---

library/src/morpheus-master/sass/modules/joinpage/_base.scss
library/src/morpheus-master/sass/tool.scss
library/src/webapp/skin/tool_base.css
portal/portal-impl/impl/src/bundle/sitenav.properties
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/join.vm

https://jira.sakaiproject.org/browse/SAK-40254
The information and messaging displayed on the default 'Join Page' is very minimal and should be improved. The linked PR changes the style of the form to match the xlogin form, including using the new logo. See attached screenshots.

SAK-40254: Portal > Improve messaging and styling of the 'Join Page'

---

web/web-portlet/src/bundle/iframe.properties
web/web-portlet/src/bundle/vm/edit.vm

https://jira.sakaiproject.org/browse/SAK-40212
Due to mixed content rules in browsers, the behaviour of the "Open in new window?" option differs if the provided link is either https or http. Provide a brief explanation of this behaviour:
```
Note: Applies only to secure (https://) URLs. A non-secure (http://) URL will always open in a new window.
```

SAK-40212: web content > explain why pop-up behaviour changes for https vs http links

---

assignment/bundles/resources/assignment.properties
assignment/tool/src/webapp/js/assignments.js
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm

https://jira.sakaiproject.org/browse/SAK-40074
Updated the "Overwrite current feedback" message with new wording proposed in SAK-40074.
*Before:*
*After:*

SAK-40074 Assignments: Updated the Overwrite current feedback message with new wording

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/Validator.java

Reworks the generation of the filename for GBNG Custom Export CSVs based on the requests in https://jira.sakaiproject.org/browse/SAK-33385.  Namely, when "All Sections/Groups" is selected, the file will now be `<prefix>-<site id>-ALL.csv` and `<prefix>-<site id>-<group name>.csv` when a filter is applied.
Also, the prefix  and "ALL" used in the filename are now added to the translations so they can be more easily tweaked.

SAK-33385 GBNG include selected group filter in export file name

---

announcement/announcement-tool/tool/src/bundle/announcement.properties
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/MenuBuilder.java
announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-delete.vm
announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm

https://jira.sakaiproject.org/browse/SAK-40223
This PR addresses a number of issues:
* duplicated menu items when viewing an announcement
* missing menu items when on the 'merge' UI
* implement menu item/highlighting for 'delete' and 'edit' UIs
* change button text on list UI from "Update" and "Cancel" to "Remove" and "Clear Selections"

SAK-40223: Announcements > menu tabs incorrect and inconsistent

---

library/src/morpheus-master/sass/base/_responsive.scss
library/src/morpheus-master/sass/modules/_toolmenu.scss

https://jira.sakaiproject.org/browse/SAK-40294
When working on the fix for SAK-40287, I had to add a magic number of 1px to the height calculation because I couldn't find where the 1px was coming from. This bothered me. I have finally found it: it was coming from the height of the #Mrphs-viewport-helpers children.
I've removed the 1px height from these children and removed the magic number from my #toolMenuWrap calculation.

SAK-40294 Library: Removed magic number from calculation

---

library/src/morpheus-master/sass/base/_compass.scss
library/src/morpheus-master/sass/modules/_main.scss
library/src/morpheus-master/sass/modules/navigation/_base.scss

https://jira.sakaiproject.org/browse/SAK-40286
In our SASS files in the Library project, Sakai has a _compass.scss file containing a number of SASS mixins for short-handing CSS properties, particularly browser prefixes.
There are a few issues with some of these mixins:
- vendor prefixes should appear first, so they can be overridden by non-prefixed styles
- the justify-content mixin contains an include for display-flex, while none of the other flex-related mixins have an include (this either causes duplication in the output or improper usage)
- the display-flex mixin requires a parameter to be passed in, but it is not used for the webkit-prefixed style inside the rule
I fixed these issues to improve the output and usage of these mixins.

SAK-40286 Library: Updated the SASS files to fix minor styling and usage issues with the mixins

---

library/src/morpheus-master/sass/modules/_main.scss

https://jira.sakaiproject.org/browse/SAK-40286
The main work for SAK-40286 was already merged in #5771, but after #5773 introduced another instance of the display-flex mixin using a parameter, which breaks the build now that both have been merged.
This fixes that extra case.

SAK-40286 Library: Fixed an extra case of display-flex taking a parameter added in #5773

---

library/src/morpheus-master/sass/modules/tool/calendar/_calendarSynoptic.scss

https://jira.sakaiproject.org/browse/SAK-40286
The main work for SAK-40286 was already merged in #5771, but when #5705 was merged today, it introduced another instance of the display-flex mixin using a parameter, which breaks the build now that both have been merged.
This fixes that extra case.

SAK-40286 Library: Fixed an extra case of display-flex taking a parameter added in #5705

---

master/pom.xml
rubrics/tool/pom.xml

With this, the command `mvn install -DskipTests=true -Dmaven.javadoc.skip=true -B -V` works with no error on JDK8, JDK9 and JDK10.
Tests fails at `sakai-assignment-impl` on JDK9 and JDK10 due an Hibernate incompatibility.

SAK-40004 - Update Maven Plugins

---

signup/api/src/java/org/sakaiproject/signup/model/SignupTimeslot.java
signup/tool/src/bundle/messages.properties

https://jira.sakaiproject.org/browse/SAK-40242
In Sign-up, I changed "a" to "an" as reported in the ticket. Here is the result:

SAK-40242 Sign-up: Changed article in message from a to an

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/modules/_toolmenu.scss
library/src/morpheus-master/sass/modules/navigation/_base.scss
library/src/morpheus-master/sass/modules/quicklinks/_base.scss

https://jira.sakaiproject.org/browse/SAK-40316
Cleaned up Sakai's top bar that contains the account link and the favourited sites. Fixed the following:
- fixed the alignment and spacing of the house icon beside "Home" for the Home site (desktop view)
- improved the hit area of the favourite sites' quick drop-down menu beside a site title (desktop view)
- set a fixed width on the tool icons under the favourite sites' quick dropdown menus (desktop view)
- fixed the alignment and spacing of the favourite sites' quick dropdown menus (desktop view)
- reviewed the colour customization options in SASS to ensure the favourite sites list can be modified properly (desktop view)
- added additional hover and focus states to the favourite sites list and dropdown menus (desktop view)
- aligned the Role …

SAK-40316 Cleaned up the top bar, including spacing and alignment, accessibility and usability

---

assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java

This PR reverts #5745 because we have tested on our multinode servers and Version wasn't been updated when submissions were created so there was still a race condition.
It was only necessary to remove the submissions cache on Assignment Hibernate object.
We were worried about the benchmarks being a lot worse but that's not been the case. I attach two documents for you to see the difference. These documents are in spanish but text is quite simple.
If there are any doubts about this maybe @adrianmticarum  or @juanjmerono can help to clarify them.
Our tester has been @jesusmmp , if you people need anything too
Bulk automatic tests (first column **with** cache, 2nd column **without** it):
Manual tests on some sites from 20 to 200 users (instructor and students)
[Pruebas caché Assignment - …

SAK-40027 (Assignments) Multi node caché issues

---

emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java

Email template service always adds Precedence: bulk which is inappropriate for single-user emails (e.g. password reset links). This can affect how email clients filter the email (e.g. to a non-default folder)
We should only add this if the email is actually being sent to multiple users.

SAK-40351 Only add Precedence: bulk to emails being sent to multiple users

---

chat/chat-api/api/src/java/org/sakaiproject/chat2/model/ChatChannel.java

So we don't have to get all of them from the database every time we get a channel object

SAK-40354 Lazy-load chat channel messages

---

roster2/src/i18n/org/sakaiproject/roster/i18n/ui.properties
roster2/src/java/org/sakaiproject/roster/tool/entityprovider/RosterPOIEntityProvider.java

https://jira.sakaiproject.org/browse/SAK-40366
This PR alters the format of the export file in the following ways:
* removes the 'Group' column from sheet 1
* renames 'sheet1' to 'Roster'
* if groups are present and user has permission to view groups, a second worksheet is added titled 'Groups'
* 'Groups' sheet is a list of memberships per group, and include the same fields that would be included in the 'Roster' sheet (varies depending on selected tab, "Overview" vs. "Enrollment Status")
See screenshots on the JIRA for examples.
Test plan uses separate sites to avoid the caching issue reported in https://jira.sakaiproject.org/browse/SAK-40365.

SAK-40366: Roster > improve format of group membership in export file

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm

https://jira.sakaiproject.org/browse/SAK-40362
When grading an Assignment, Instructors can provide any/all of the following:
1) inline feedback
2) summary comments
3) upload an attachment to return with a grade.
Once the item has been saved and released to the student, the student can view all 3 of these items provided by the Instructor. However - if the student presses Save Draft while working on their Resubmission attempt - when they resume work again on this Resubmission (after previously saving), the screen changes and most of the Instructor feedback information is missing from the page.

SAK-40362: Assignments > instructor feedback not visible in resubmission scenario

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_feedback_attachments.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss

https://jira.sakaiproject.org/browse/SAK-40361
The current state of the student's view grade/submission/feedback UI can become cluttered if all possible sections are present (assignment instructions, assignment attachments, original submission text, original submission attachments, instructor feedback, instructor feedback attachments).
This PR visually distinguishes these sections by giving each "panel" a border. See before and after screenshots on the JIRA.

SAK-40361: Assignments > visually distinguish sections of the students view of returned submission

---

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java

https://jira.sakaiproject.org/browse/SAK-40345
This patch fixes two issues with announcement sorting, one bug and one usability feature:
1.  a bug where the first time clicking on a sorting header, the sort will take any 'overflow' (based on the number of items being viewed) from the top of the list first, making the 'first x items' of a list actually be the _last_ X items, though sorted correctly on-screen
* example: in a list of items named 1-250 (created in ascending order), viewing 200 items, the first click of "modified by" would show items 50-250, correctly sorted by date, while items 1-49 (which should be the earliest and thus on the initial screen) are pushed off to first overflow page.
2. if you were looking at a subset in the middle of the list (say, announcments 21-40 out of …

SAK-40345: Announcements > sort order problems

---

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java

https://jira.sakaiproject.org/browse/SAK-28966
The Reorder Option in Announcements doesn't work properly with drag&drop, if previously it has been another ordering. 
Steps: 
- Create three announcements, for example: 
01 warning
02 warning
03 warning
1- Go to Reorder option.
2- Sort by subject
3- Then, sort by drag&drop
4- Click Update: ERROR, It doesn't keep the last ordering done by drag&drop. 
- If you refresh de page, the ordering appears ok. 
It doesn't happen if you omit the second step, directly going to drag&drop it'll result ok.

SAK-28966: Announcements > Reorder option not persistent on update

---

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
samigo/samigo-app/src/webapp/css/tool_sam.css
samigo/samigo-app/src/webapp/jsf/author/preview_item/Matching.jsp
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/bundle/Messages.properties
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java
samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java

https://jira.sakaiproject.org/browse/SAK-40334
PR addresses the following issues:
1. Distractor choice displayed for questions that do not include a distractor (Published Copies > Edit UI only)
2. No space between the choice label and choice text, ex: A.Choice1 (both Published Copies and Working Copies > Edit UIs)
3. Incorrect choice labels for any Matching question which has two or more consequitive options which use the same choice, which are not at the very end of all options
See screenshots on the JIRA.

SAK-40334 Samigo > more display issues with Matching questions

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/SiteEmailNotificationAnnc.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-39992
Currently if your server has the property set to make Announcement emails 'From' address replyable (`notify.email.from.replyable=true`), when an announcement notification email is sent, the default 'To' address is in the format of: 
```
"[siteTitle] <noreply@[ServerConfigurationService.getServerName()]>"
```
and the 'From' address is in the format of:
```
"[lastName, firstName] <[instructor/maintainerEmail]>"
```
There may be an institutional requirement or preference to control the email address used in the 'To' address, similar to how you can control the 'From' address with the existing `mail.sendfromsakai` sakai.property.
The only configuration option for this is the `notify.email.to.replyable` sakai.property, which when set to true *and* …

SAK-39992: Announcements > new config to make email notification 'To' address match 'From' address if 'From' is replyable

---

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
assignment/bundles/resources/assignment.properties
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
library/src/morpheus-master/sass/base/_compass.scss
library/src/morpheus-master/sass/base/_extendables.scss
library/src/morpheus-master/sass/modules/tool/_table.scss
library/src/morpheus-master/sass/modules/tool/announcements/_announcements.scss
library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
library/src/webapp/js/sakai-table-toolbar/pagerPanelMacro.js
library/src/webapp/js/sakai-table-toolbar/searchFilterPanelMacro.js
library/src/webapp/js/sakai-table-toolbar/viewFilterPanelMacro.js
library/src/webapp/js/spinner.js
site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
velocity/tool/src/templates/VM_chef_library.vm

https://jira.sakaiproject.org/browse/SAK-40248
As a small step of the standardization project known as SWITCH, standardize the view and paging controls found at the top of most tools. Start with a few tools, such as Assignments, Announcements, and Site Info.
Goals of this change:
-    Create standard components, styles, design, and layout for these controls
-    Ensure the layout of these components work across varying screen sizes and toolbar
-    Make the controls easy for developers to use in future table pages
-    Create reusable Velocity components that can be applied to other tools
Scope:
-    Announcements - main page
-    Assignments - all pages with tables
-    Site Info - main page

SAK-40248: Begin the standardization of the toolbar for table controls (e.g. filtering and paging) across tools

---

master/pom.xml

Release 2.10 – 2018-05-30
Type	Changes	By
DateTimeZone data updated to version 2018e.	jodastephen
Handle negative SAVE values in tzdb. Once again, tzdb is the source of problems, with their inability to provide stability. A hack has been added that reverses their latest decision to have negative SAVE values. The hack works so long as a rule set does not mix positive and negative save values.	jodastephen
Add Instant.EPOCH. See #472.	jodastephen
Clarify negative durations. See #465.	jodastephen
Add Instant.ofEpochMilli(). Add Instant.ofEpochSecond(). Fixes #458.	kluever
Add automatic module name for Java SE 9.	jodastephen
Add Kazakh language translations. Fixes #446	jodastephen
Avoid double addition when using lenient chronology. Fixes #432.	jodastephen
Clarify Period.fieldDifference() …

SAK-40416 joda-time 2.10

---

help/help-component/src/bundle/TutorialMessages.properties
help/help-component/src/tutorial/Tutorial.config

https://jira.sakaiproject.org/browse/SAK-32761
I have restored some of the panels of Sakai's introductory tutorial by updating the tutorial's selectors to reflect changes to Sakai's interface for Sakai 12. 
I also updated some of the wording on some of the tutorial panels to reflect the recent interface updates.

SAK-32761 Help: Restored panels to the introductory tutorial and updated the tutorial to match recent updates to Sakai's interface

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java

Gradebook uses two different serialization schemes, depending on the size of the maximum grade that needs to be represented.  The boundary between these schemes (16384) wasn't properly handled: it would attempt to use packed serialization but then throw an error because the value couldn't be represented.

SAK-40434 Fix off-by-one error in isLarge check

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java

https://jira.sakaiproject.org/browse/SAK-40453
There are three overloads on `AssignmentService.getSubmission()`, each of which states that a `PermissionException` can be thrown. However, only two of the three overloads actually perform the permission checking and throw the exception.
Linked PR adds the permission check and exception throw to the remaining method.

SAK-40453: Assignments > missing permission check in AssignmentService.getSubmission(String)

---

library/src/morpheus-master/sass/base/_extendables.scss
library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss

https://jira.sakaiproject.org/browse/SAK-40461
- brightened its default state
- created a disabled state (with better than 5.5:1 contrast)
- removed the down-arrow background image from the multi-select elements

SAK-40461 Library: restyled the select dropdown menu element

---

sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml

https://jira.sakaiproject.org/browse/SAK-40466
The "annc.read" event is missing from the event definition file in SiteStats, even though there is localization support for the event in the message bundles.

SAK-40466: SiteStats doesn't track read events from Announcements

---

roster2/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java

https://jira.sakaiproject.org/browse/SAK-40468
Going to the "Enrollment Status" tab results in an NPE and the loading gif animating indefinitely. This is a regression from SAK-40451. Stacktrace in the JIRA.

SAK-40468: Roster > fix NPE on 'Enrollment Status' UI

---

library/src/webapp/js/spinner.js

https://jira.sakaiproject.org/browse/SAK-40459
In 12 and 19 the JavaScript spin and clone routine is applying a class to inputs of type radio and checkboxes which in effect makes the "checked" state of the cloned elements no longer visible. This can be confusing for the user, as it may look as though their selection(s) have been lost.
This is a regression compared to 11.x.

SAK-40459: Library > JavaScript spin+clone tweak to retain visible checked state of checkboxes and radios

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java

https://jira.sakaiproject.org/browse/SAK-40467
When importing a spreadsheet in GradebookNG, if a row contains a user ID which is not a member of the site AND the row contains a null value for the "Student Name" cell, an NPE will be generated.
This is caused by the reporting algorithm which is responsible for telling the user which entries in the file belong to users who are not members of the site. This algorithm access the row's "Student Name" value and tries to call `.trim()` on it, which generates the NPE if the cell in the file has no value.
The solution is simple: when setting this value, call `StringUtils.trimToEmpty()`.

SAK-40467: GradebookNG > Import > avoid NPE if user missing from site and 'Student Name' cell is empty

---

rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/RenderBean.java

https://jira.sakaiproject.org/browse/SAK-40485
SAK-23566 added read events for the wiki, but there appear to be several problems with the way it was done:
- clicking the Edit tab fires a read event when it should not (this was indicated in code comments as a known issue)
- if the page has any comments, a separate read event is fired for each comment, which is unnecessary since the comments are not being viewed in isolation but rather automatically as part of rendering the parent page
- the event references from SAK-23566 do not match the pattern used by the other event code in the tool
It turns out also that read events were already tracked by the wiki, just disabled by default. As of Sakai 12 (see SAK-21039), it is enabled by default, so we now have duplication of read events.
At this …

SAK-40485: Clean up wiki read events

---

content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java

If there isn’t a gradebook in the current site don’t log a failure to find the gradebook when attempting to sync grades, instead just don’t attempt to do the sync.
Also improved security advisor handling to use correct push/pop.

SAK-40483 Don’t log error when gradebook missing.

---

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml
sitestats/sitestats-bundle/src/resources/Events.properties

https://jira.sakaiproject.org/browse/SAK-40492
Calendar read events are commented out in the SiteStats event definition file. This patch uncomments them so they can be counted.
It also slightly changes the calendar.read event reference to remove the id of the most recently viewed calendar item, which was being added to subsequent events where it was not appropriate. For example, if you visit the calendar with the weekly default view, the calendar.read reference looks like "<site_id>/week". If you view a calendar event, the calendar.read reference looks like this: "<site_id>/description/<cal_event_id>". If you then go back to the weekly view, the reference looks like "<site_id>/week/<cal_event_id>", which makes little sense as the id references a particular event, not a particular week.

SAK-40492: Add calendar read events to sitestats

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java

When checking to see if an item should be visible there was an "always"
advisor pushed to the top of the security advisor stack before getting
the item's groups. This advisor makes it so that group release information
for a resource is ignored which makes the item stay in the list for the student
even though they don't have access to the resource. This fix pops the advisor
before getting the item groups.

SAK-37980 Group visibility issue in Lessons tool

---

library/src/morpheus-master/sass/base/_extendables.scss

https://jira.sakaiproject.org/browse/SAK-40507
As a result of SAK-40461, the select dropdown elements (<select>) with a size of "1" specified in the markup will not display the necessary down arrow.
In this PR, I have made the CSS rule more specific to still avoid multi-size selects without removing them from the applicable dropdowns.

SAK-40507 Fixed missing arrow from some dropdown select elements

---

kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java

I've removed Dropbox condition because it was failing on content tool on sites and My Workspace and, instead of adding the extension, zip file display name was always just the folder name.

SAK-40513 - Content : Missing extension when a folder is zipped

---

admin-tools/src/java/org/sakaiproject/user/tool/PasswordPolicyHelper.java
chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java
chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatMessageEntityProvider.java
chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityUser.java
kernel/api/src/main/java/org/sakaiproject/user/api/User.java
kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
providers/jldap-mock/src/java/edu/amc/sakai/user/UserEditStub.java

SAK-10868 and SAK-39642 added support for context-specific user aliases, that is a display name for a user that can be different in a specific site context.
This supports the "role play" or "user alias" use case, for example for simulation games (. There is a contrib implementation for this (https://confluence.sakaiproject.org/display/RPLAY/Home) in use by UCT and possibly others.
When implemented, it was sufficient to resolve the site context from the tool context, but as more tools have moved to using /direct/ or other REST endpoints for tool data, this no longer works as the tool placement is not available, specifically for chatData in the Chat Tool.
This task adds methods to the User API so that tool- and service endpoints can get a display name for a user for a specific site context …

SAK-40535 Add User API methods for ContextualUserDisplayService

---

providers/component/src/webapp/WEB-INF/unboundid-ldap.xml
providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java

Adds these properties:
allowAuthenticationAdmin (default false)
allowAuthenticationExternal (default true)
allowSearchExternal (default true)
allowGetExternal (default true)
described in unboundid-ldap.xml

SAK-40572 Add 4 additional config options to the unboundid LDAP provider

---

kernel/kernel-util/src/main/java/org/sakaiproject/util/BasicAuth.java

Avoids an unnecessary stack trace being logged

SAK-40571 Don't check basic auth if no Authorization header is present

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java

The issue seems to be due to the `externalAppLoader.getString("sakai.lessonbuildertool.title")` returning `[missing key (mre): org.sakaiproject.localization.bundle.tool.tools sakai.lessonbuildertool.title]`. Perhaps something has changed in that space?
This patch changes the `externalAppLoader.getString` to `this.toolManager.getLocalizedToolProperty`.  This seems to return the localized string most likely to have been used in the externalAppName field. Note, "Lesson Builder" is the hardcoded externalAppName in SimplePageBean.java, so doesn't need any special treatment.

SAK-39943 fix external app icons in gradbookng summary view

---

sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml
sitestats/sitestats-bundle/src/resources/Events.properties
sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventUtil.java

https://jira.sakaiproject.org/browse/SAK-40646
SiteStats was never updated to track the events from GradebookNG. This patch adds support for GradebookNG events while retaining the ability to view historical data for Gradebook Classic events.
To facilitate this, the GradebookNG tool id "sakai.gradebookng" becomes the primary id for the Gradebook in SiteStats, with the Gradebook Classic tool id "sakai.gradebook.tool" being an alternate id, which allows it to be displayed even in sites that only have Gradebook Classic.
As a minor side effect of improving the alternate id handling, the following will now occur:
-    Sites using Overview will have Web Content listed as a tool in SiteStats event if they have no explicit Web Content instances in the tool menu, Overview utilizes a variation of …

SAK-40646: SiteStats no longer tracks Gradebook events

---

assignment/api/src/java/org/sakaiproject/assignment/api/persistence/AssignmentRepository.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java

added check in the count submissions list to get just the count of the submission for the students active in the course
added checking to do the queries in multiple portions if there are more than 1000 people in the course. Oracle can only handle up to 1000 items in the "IN" clause at a time.

SAK-33934 reduce assignment count when person is removed from course

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java

https://jira.sakaiproject.org/browse/SAK-40682
Currently, a call to /direct/membership/site/<siteId>.xml improperly returns JSON instead of XML. It in fact returns JSON regardless of the requested return type.

SAK-40682: EntityBroker > fix wrong return type for membership

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityMember.java

https://jira.sakaiproject.org/browse/SAK-40542
It would be useful to also include first and last name in the membership entity provider, supplemental to the display and sort names.

SAK-40542: EntityBroker > add first and last name to membership provider

---

library/pom.xml
library/src/webapp/editor/elfinder/sakai/js/src/editors.js

This PR should be broken because the webjar libraries need to be populated to sonatype.

SAK-40691 - WebJars: Upgrade codemirror from 5.6.0 to 5.40.2

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/NumberUtil.java
kernel/kernel-util/src/test/java/org/sakaiproject/util/NumberUtilTest.java

`DoubleValidator` and `NumberFormat` have known problems (https://www.ibm.com/developerworks/java/library/j-numberformat/index.html) converting and checking number not in the server locale. 
They pass as valid doubles that shouldn't be as "3,5" or ",2" on an english site because they assume and convert the double to 35 and 2 respectively, it should return a validation or parse error but `NumberFormat` and `DoubleValidator` don't work that way.
"3,5" is converted to 35
"3.5" is converted to 3.5
",2" is converted to 2
So we have modified the way gradebookng checks its valid Double on a common class for all sakai that can be improved

SAK-40563 - Problems with decimal separator character in Gradebook

---

rubrics/tool/src/main/frontend/imports/sakai-rubric-criterion-student.html

An empty selectedValue was being considered as a 0, so it appeared twice. It's better to use a different variable that will match the same cases.

SAK-40312 Rubrics: solving double 0 issue

---

library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js

Indicate that update count ajax request is "auto" meaning it is
not a user request and should not prevent the user's session from
timing out.

SAK-40728 Bullhorn update count prevents portal timeout

---

library/src/morpheus-master/sass/modules/navigation/_base.scss
library/src/morpheus-master/sass/modules/navigation/_skipnav.scss

https://jira.sakaiproject.org/browse/SAK-40643
The new Manage Overview button introduced in SAK-40520 was not designed and positioned to match similar buttons, like the Link and Help buttons in the top of most pages. 
My fix simplifies the implementation and standardizes the look to be consistent with the related buttons. 
Unfortunately, I wasn't able to restructure the markup to be more semantic, so I just focused on the styles.
See https://jira.sakaiproject.org/browse/SAK-40643 for before and after screenshots.

SAK-40643 Library: updated the styles and positioning of the Manage Overview button

---

providers/sample/src/java/org/sakaiproject/provider/user/SampleUserDirectoryProvider.java

https://jira.sakaiproject.org/browse/SAK-40745
While testing and developing Sakai with the demo enrolment data enabled, some of the demo users, like "The Instructor" (instructor), have a first name of "The". This first name is relatively short and doesn't look particularly professional when it appears just as "The" in the top right corner as the Account Menu link.
I propose changing cases of "The" in the demo data to "Sakai" (e.g. "The Instructor" would become "Sakai Instructor").

SAK-40745 Improved the Sakai demo data account first names

---

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java

https://jira.sakaiproject.org/browse/SAK-40749
The queue that is used for scheduling realm refresh tasks is a `HashMap` that has it's values iterated over. The order of a `HashMap` is not intended to be defined, and as of Java 8 is no longer predictable. This causes jobs in the queue to be executed in "random" order. This should to be changed to a `LinkedHashMap`.

SAK-40749: Kernel > realms refresh queue uses a HashMap

---

help/help-tool/src/java/org/sakaiproject/tool/help/HelpJsfTool.java

https://jira.sakaiproject.org/browse/SAK-40748
addressed 2 issues with the help system:
1. conditional anded with an expression which is always true; replace the expression with what appears to be intended
2. add param to ScreenSteps URL to convey doc tag

SAK-40748: Help > fix bug with docId

---

library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/mixins/_tab-focus.scss
library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/base/_defaults.scss
library/src/morpheus-master/sass/base/_extendables.scss
library/src/morpheus-master/sass/modules/_footer.scss
library/src/morpheus-master/sass/modules/_toolmenu.scss
library/src/morpheus-master/sass/modules/navigation/_base.scss
library/src/morpheus-master/sass/modules/tool/_menu.scss

https://jira.sakaiproject.org/browse/SAK-40743
The focus outline in Sakai varies from component to component. The design and colour of the outline is different for buttons than it is for links than it is for radio buttons.
SAK-38356 introduced a Sakai default outline colour for links. SAK-32484 defined a separate design for Bootstrap buttons. SAK-40146 used a different style and colour for the focus of radio buttons and checkmarks.
This fix standardizes all of these cases with central variables. It undoes the Bootstrap override added in SAK-32484 by overriding the behaviour in Sakai's SASS files. My fix also tweaks some of the overlap issues for portal controls, such as the site links and the intra-tool tabs.

SAK-40743 Library: standardized the focus outlines in Sakai, including buttons, links, and form elements

---

polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
polls/impl/src/test/org/sakaiproject/poll/logic/test/PollListManagerTest.java

https://jira.sakaiproject.org/browse/SAK-40777
The event "poll.add" is never fired due to a logic error:
```
if (t.getId() == null) {
newPoll = true;
t.setId(idManager.createUuid());
}
...
...
...
if (newPoll)
externalLogic.postEvent("poll.add", "poll/site/"
+ t.getSiteId() + "/poll/" + t.getId(), true);
else
externalLogic.postEvent("poll.update", "poll/site/"
+ t.getSiteId() + " /poll/" + t.getId(), true);
```
Where `Poll.getId()` is:
```
public String getId() {
if (entityID == null) {
entityID = id + "";
}
return entityID;
}
```
In this situation, `t.getId()` returns a string of `"null"`, and thus never satisfies the condition to flip the `newPoll` boolean to true. The code should be checking for the absence/null value of the actual ID of the poll, not the entity ID:
```
if …
```

SAK-40777: Polls > 'poll.add' event is never fired due to logic error

---

polls/tool/src/java/org/sakaiproject/poll/tool/params/PollToolBean.java

https://jira.sakaiproject.org/browse/SAK-40778
Went to do a SQL query ordered by poll_creation_date of the poll_poll table, realized every poll in every database we have (both MySQL and Oracle) has null values for this field...

SAK-40778: Polls > creation date is never populated

---

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
samigo/samigo-app/src/webapp/css/tool_sam.css

https://jira.sakaiproject.org/browse/SAK-34439
If your quiz includes a *Multiple Choice, Multiple Selection* or *True False* type question, students see the answer options (in *Multiple Choice, Multiple Selection*, this includes the letters for answer options, e.g. *A.*) in *bold* when they take the test and view feedback, even if the instructor did NOT select to make these bold. Answer text should NOT be bold unless specified by instructor.

SAK-34439: Samigo > erroneous bold styling on answers to MC, MS and T/F questions

---

content/content-bundles/resources/types.properties
content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm

https://jira.sakaiproject.org/browse/SAK-40750
Sakai 11 introduced a new feature in which file uploaders can choose for files to be hidden when they are uploaded. However, it is still possible to select email notifications for files uploaded as hidden, meaning that site members could receive notifications for files that they are not permitted to access.
The email notifications dropdown menu should probably be disabled if the option to upload files as hidden is selected.
Screenshots in the JIRA.

SAK-40750: Resources > disable email notification options when uploading hidden files

---

gradebookng/tool/src/webapp/styles/gradebook-grades.css

https://jira.sakaiproject.org/browse/SAK-40756
Fixed the missing icons on the due date form field controls in the Gradebook item add/edit modal by specifying a font-size on the group to override Bootstrap in conjunction with the glyphicon.
Before:
After:

SAK-40756 Gradebook: fixed missing icons for due date on GB item add or edit modal

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java

https://jira.sakaiproject.org/browse/SAK-40798
If you enable Drop/Keep highest/lowest grades for a category and the category contains items with different point values, the field to enter a number to drop/keep on the Settings page is correctly disabled. However, attempting to mouse over the disabled field, the error message is incorrect and misleading:
> 'Drop highest' / 'Drop lowest' cannot be used in the same category with 'keep Highest'.
The same error is displayed regardless of which of the three options you want to enable.
The correct behavior for a category with items having different point values would be to warn you that your category needs to have items with the same point value to drop/keep.

SAK-40798: GBNG > incorrect error message when trying to add drop/keep to a category with items of different values

---

assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java

This change cleans up getSubmitterMap and instead of locking the table
it locks the Assignment until it has added all submissions. This change
is a bit smarter since it will only lock the assignment if a submission
is to be added.

SAK-40817 Assignments regression from SAK-40742

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java

Because the text abbreviation operation was performed after the encode, the integrity of the special character was deteriorating, so when the page has rendered, the text seems distorted.

SAK-40837 - Distorted course names in favorite bar

---

delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/logic/SakaiProxyImpl.java

https://jira.sakaiproject.org/browse/SAK-40857
The delegated access tool, out of the box, does not work for provided LDAP users.

SAK-40857: DelegatedAccess doesn't work for provided LDAP users

---

chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java
chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatMessageEntityProvider.java
chat/chat-tool/tool/src/webapp/js/chatscript.js

Also crucial to this change is not remove users from the `heartbeatMap` if we don't hear from them in 10 seconds. Instead, keep them in the map to make sure messages can be delivered when they reconnect!

SAK-40861 use the browser visibility state to avoid fetches when hidden and to fetch as soon as we are visible again

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java

https://jira.sakaiproject.org/browse/SAK-40886
The retract date check can be bypassed by editing from the Republish UI, resulting in retract earlier than due date.
If you attempt to edit an assessment's settings after clicking *Save Settings and Publish* in _Working Copies_, then you click *Save*, you can bypass the date check where Samigo confirms that the *Late Submission* (aka *Retract*) date is set *after* the *Due Date* for an assessment.  Because autosubmit triggers off the late submission date, this can result in unexpected behavior in the case of an autosubmit test.
This issue was found because an instructor managed to set the *Late Submission* date before the due date; this resulted in an exam being autosubmitted out from under a number of students who were in the process of …

SAK-40886: Samigo > retract date check can be bypassed

---

msgcntr/messageforums-app/src/webapp/css/msgcntr.css

https://jira.sakaiproject.org/browse/SAK-40885
When on a mobile device, viewing a post and trying to click on any of the action buttons is extremely difficult due to how they're squished together and overlapping. For example, it's very easy to erroneously click on 'Delete' when meaning to click on 'Reply...'.
Screenshots in the JIRA.

SAK-40885: Forums > mobile view post UI's action buttons squished

---

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java

https://jira.sakaiproject.org/browse/SAK-40884
Using the grading modal to grade a student's post (in a forum and topic that were not previously associated with a gradebook item), may appear to the user as having lost their data.
In fact, the user data is not actually lost; it is saved the the Gradebook properly behind the scenes. However, upon returning to the same user's post and clicking the 'Grade' button again does not load the previously selected gradebook item and grade/comment which was saved.
Steps to reproduce in the JIRA.

SAK-40884: Forums > grading modal doesn't remember previously entered user data

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm

https://jira.sakaiproject.org/browse/SAK-33281
If you elect to import from site (merge data), and select multiple sites to import from, you'll end up with a list of multiple instances of each tool. For example, if you select three sites to import from and all three have the Assignments tool, you'll end up with three entries for Assignments in the list.
This list was also changed to display the custom configured tool title, if any was configured. This can make it difficult for people to understand what they're importing, as they may not be aware which tools correspond to the custom titles.
These two issues are both regressions compared to 10.x behaviour. Steps to reproduce and screenshots in the JIRA.

SAK-33281: Site Info > import from site shows multiples of each tool

---

rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/macros/SakaiLinkMacro.java

https://jira.sakaiproject.org/browse/SAK-40883
In it's current form, the link macro aborts processing any relative URLs when clicked by the user:
> 04-Nov-2018 11:27:25.370 WARN [https-jsse-nio-8452-exec-5] uk.ac.cam.caret.sakai.rwiki.component.macros.SakaiLinkMacro.execute RWiki URL (//dev.thlib.org) looks invalid so we're removing it from the display.
This PR extends the `link` macro to allow relative URLs.

SAK-40883: Wiki > fix link macro for relative links

---

postem/postem-app/src/bundle/org/sakaiproject/tool/postem/bundle/Messages.properties
postem/postem-app/src/java/org/sakaiproject/tool/postem/PostemTool.java

https://jira.sakaiproject.org/browse/SAK-40882
When uploading a feedback file in PostEm, the instructions clearly state:
> Your feedback file must be saved in .csv format.
> The first column of your file must contain individual usernames.
> The first row of your file must contain headings. 
However, when you upload or link to a file in resources which is not a CSV, the error message is not appropriate:
> Some data in your uploaded file exceeded the 2,000 character limit and was truncated.
> Alert: Each column heading in your uploaded file may not exceed 500 characters.
These errors may not be accurate, as the data in the file may be completely valid. The problem here is that the file type is invalid, and the error message should indicate this to the user to help them resolve the problem. …

SAK-40882: PostEm > incorrect error message when uploading wrong file type

---

library/src/webapp-filtered/editor/ckeditor.launch.js

https://jira.sakaiproject.org/browse/SAK-40879
The `#chef_setupformattedtextareaparams` velocity macro allows passing a named toolbar configuration, like this:
`#chef_setupformattedtextareaparams("contenttext" "" "" "FullNoKaltura")`
However, the code in `ckeditor.launch.js` omitted the code that allowed this parameter to function. It needs to be added back; this is a regression from SAK-30370.

SAK-40879: CKEditor > allow tools to override default toolbar config

---

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java

It's not clear why we should ever get a null event passed here, but it has happened in testing conditions, and so it seems better to just check and ignore it rather than allow the stats update thread to die, requiring it to be re-started.

SAK-40889 Ignore a null event

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_preview_submission.vm
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm

This is a small backward compatibility issue, there are assignments that still don't have all mandatory properties because are too old.
There are similar issues on other tools and I'm going to try to check all nulls on the having log error.

SAK-40874 - Velocity null errors on assignment log

---

kernel/kernel-impl/src/main/java/org/sakaiproject/memory/impl/EhcacheMemoryService.java

This addresses a race condition where a number of request threads are handled just after startup. Several threads try to create the cache at the same time.
It's harmless to return null here because that is checked for in the calling code. The cache has been created by another thread, and will be used by all subsequent threads.

SAK-26580 Ignore cache creation attempt if it already exists

---

pasystem/pasystem-tool/tool/src/webapp/scripts/pasystem.js

This is a bit of a hack, but it's one of the suggestions in 
https://github.com/noelboss/featherlight/issues/231
That issue is still open but they haven't agreed on the best way to fix it yet.  there was a mention of configuring the 'root' and adding a <modals> tag to the end of the body, but someone else disagreed because <modals> may not be cross browser compatible.
So until featherlight gets updated with a fix (or we change pasystem to use some other lightbox lib), will this hack suffice in the meantime?

SAK-40665 PA System pop up does not dim the background

---

kernel/kernel-storage-util/src/main/java/org/sakaiproject/util/StorageUtils.java

To mitigate threads blocking on filesystem access; see JIRA issue for more detailed explanation.

SAK-40891 Use a static DocumentBuilderFactory for StorageUtils

---

reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/NewUserProducer.java

When the forename and surname were set on the user object but weren’t set on the ValidationAccount object the value would be shown in the form but then when submitted it would generate an error saying that the forename was empty.
This was because the value wasn’t set on the bean backing the form and RSF only updates values that are considered too have changed. The 2 ways this can be solved are:
- force the UIInputs to always update the bean. This means setting `mustapply` in the producer and then the default values are re-applied to the bean when the form data is read in even though the new value and the fossil values are the same. This isn’t optimal because we’re fixing it late in the call.
- update the ValidationAccount bean with defaults from the user object if they aren’t set on the …

SAK-40871 Correctly pull through forename/surname.

---

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java

https://jira.sakaiproject.org/browse/SAK-40877
Log errors result from SQL statement errors when `ORDER BY` states a column whose table is not part of the `SELECT`. The sort order results from user choices in the UI.
Stacktrace and steps to reproduce in the JIRA.

SAK-40877: Kernel > inappropriate sort option causes kernel code to create broken SQL statement

---

rubrics/tool/src/main/frontend/imports/sakai-rubric-association.html
rubrics/tool/src/main/frontend/imports/sakai-rubrics-list.html

Solving the bug both for Rubrics and the selector that appears on other
tools. Iron-ajax has 20 as its default size param value.

SAK-40285 Show more than 20 Rubric entries

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp

Add pop-up warning for assessement takers that starting a new attempt will impact their grade.  (Especially if they don't answer any questions.)  Warning only appears if autosubmit is on, and grading is set to "last score" or "average score".  The warning only appears after they've taken the assessment at least once.  Warning explains how their grade will be affected, and offers them a chance to cancel starting a new attempt.  
Warning doesn't apply if autosubmit is off, or if "highest score" is in effect so it doesn't appear.
https://jira.sakaiproject.org/browse/SAK-34145#

SAK-34145 Clarify autosubmit implications for student

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java

The changes included in this PR  https://github.com/sakaiproject/sakai/pull/6113 force us to check if it's a lessons/url submission, instead of just checking it the first time as it was before.

SAK-40914 allow samigo via lessons or url

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/MembershipEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/MembershipEntityProviderTest.java

When getting memberships for the current user the list of sites to return the results for were incorrectly getting filtered so that only the entries where the current user was allowed to view the roster in the site. That should have only been happening when the a non-admin user was looking for the memberships of a different user.

SAK-40943 Always include current user memberships

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java

This was a regression caused by SAK-34820. The assessment id changed
from publishedAssessmentId to publishedId in that ticket.

SAK-40959 Changed assessment id parameter to publishedId

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

Added "resetAssignment" to "doNew_assignment" in order to reset all the
attributes between the creation of an assignment and the creation of
another assignment.

SAK-40668 - Peer options are remembered when you edit an assignment then create a new one

---

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java

This is like the lti13_settings and sha256 fields - there for future use.  I just want it there before Sakai-19.

SAK-40980 - Add LTI 1.1 launch type field for future use

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java

This is only interesting for legacy purposes, as new sites can't be created with spaces on the id.

SAK-40702 wicket tools don't work if site id has a blank space

---

lessonbuilder/tool/src/resources/messages.properties

https://jira.sakaiproject.org/browse/SAK-37654
Fixed some capitalization for components when they appear on the Lessons  Reorder page. 
See SAK-37654 for before and after screenshots.

SAK-37654 Lessons: fixed some capitalization for components when they appear on the Lessons  Reorder page

---

lessonbuilder/tool/src/resources/messages.properties
lessonbuilder/tool/src/webapp/templates/instructions/website.html

https://jira.sakaiproject.org/browse/SAK-41016
I removed the period from the one option that was referenced in the Jira issue and uppercased the words to match the other options. Added a few article words in some options to also match the other options' phrasing.
See before and after screenshots in SAK-41016.

SAK-41016 Lessons: standardized the capitalization and punctuation of the Add Content menu options

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java

Dealing with percentages and precision via String objects is a bad idea and a nightmare (even more if we're adding i18n to the mix), but at least if we are comparing two values I believe we should do it with actual numbers.
I'd rather just add this verification than modifying more logic, but I'm open to suggestions.

SAK-40674 solve wrongly considered concurrent edit in GB

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java

https://jira.sakaiproject.org/browse/SAK-41027
The default tooltip on the disabled input field refers to the point values, rather than the mutually exclusive settings message you should see. There's also a reference to an inconsistently capitalized setting in the mutually exclusive tooltip.
Steps to reproduce in the JIRA.

SAK-41027: GBNG > incorrect default tooltip when toggling mutually exclusive drop/keep settings

---

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content.properties
config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/type/types.properties
content/content-bundles/resources/content.properties
content/content-bundles/resources/types.properties
content/content-tool/tool/src/bundle/dropbox.properties

https://jira.sakaiproject.org/browse/SAK-41054
There are several messages shown to the user which refer to the tool as "Dropbox" or "dropbox", in contradiction to the tool name and other messages which refer to the tool properly as "Drop Box". The linked PR also replaces a few instances of the word "resource" for "item", in reference to uploading items to a user's Drop Box.

SAK-41054: Drop Box > fix inconsistencies in UI messaging when referring to the tool

---

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradebookAssignment.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java

https://jira.sakaiproject.org/browse/SAK-41057
If the instructor has edited an external gradebook item in the Gradebook to remove the "Release to Students" setting, editing the associated quiz/assignment/etc. through the external tool will overwrite the instructor's previous choice to not release the item to the students.

SAK-41057: edu-services > external GB item 'release to students' setting overwritten on update

---

search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java

`03-Dec-2018 11:54:23.359 ERROR [[elasticsearch content indexer default]] org.sakaiproject.search.elasticsearch.SiteElasticSearchIndexBuilder.rebuildSiteIndex An exception occurred while rebuilding the index of 'b125e21b-daf6-4bde-bb99-27ef5a2c086d'
java.lang.NullPointerException
at org.sakaiproject.search.elasticsearch.SiteElasticSearchIndexBuilder.rebuildSiteIndex(SiteElasticSearchIndexBuilder.java:249)
at org.sakaiproject.search.elasticsearch.SiteElasticSearchIndexBuilder$RebuildSiteTask.run(SiteElasticSearchIndexBuilder.java:314)
at java.util.TimerThread.mainLoop(Timer.java:555)
at java.util.TimerThread.run(Timer.java:505)`

SAK-41050 protect against NPE in iterator

---

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js

https://jira.sakaiproject.org/browse/SAK-41061
When student numbers are enabled in the gradebook, updates to the course
grade overwrite the student number column instead of the course grade
column.

SAK-41061: Wrong column for course grade updated when student numbers enabled in gradebook

---

edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseManagementService.java
edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/hibernate/org/sakaiproject/coursemanagement/impl/SectionCmImpl.hbm.xml
edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceFederatedImpl.java
edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceHibernateImpl.java
edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementServiceSampleChainImpl.java
kernel/api/src/main/java/org/sakaiproject/authz/api/GroupProvider.java
providers/allhands/src/java/org/sakaiproject/provider/authzGroup/AllHandsGroupProvider.java
providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProvider.java
providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseOfferingRoleResolver.java
providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/CourseSetRoleResolver.java
providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/RoleResolver.java
providers/cm-authz-provider/src/java/org/sakaiproject/coursemanagement/impl/provider/SectionRoleResolver.java
providers/sample/src/java/org/sakaiproject/provider/authzGroup/SampleGroupProvider.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41026
This PR improves the performance of displaying roster lists in Site Info by creating an overloaded method (in several areas) which takes an extra parameter (the academic session EID). In this way, you can limit what rosters are loaded by the selected academic session, instead of always asking for every roster the user belongs to regardless of the user's selection.
This patch has been running in a large production instance for over 5 years without issue.

SAK-41026: Site Info > Improve performance when displaying roster lists

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41083
When duplicating a course site, an email notification is sent. This email does not populate the course term variable, even if selected by the user in the UI. The result is that the email body and subject line lack the information and seem cut off:
> Official Course Site duplicated site (ID b137ac88-ee6a-4479-b832-865b90c1f55a) was set up by Sakai Instructor (instructor, email instructor@example.edu) on 2018-12-13 18:41:44 for
for..... what?? It should say something like:
> Official Course Site duplicated site (ID b137ac88-ee6a-4479-b832-865b90c1f55a) was set up by Sakai Instructor (instructor, email instructor@example.edu) on 2018-12-13 18:41:44 for Spring 2018

SAK-41083: Site Info > duplicate course site email notification missing course term variable

---

samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java

https://jira.sakaiproject.org/browse/SAK-41093
The current email notification sent out when a user submits a quiz has some inconsistently formatted dates:
> The following assessment submission was recorded by Sakai:
> 
>     Site Title          : Discussion 3 SMPL101
>     Assessment          : due date
> 
>     Student             : 0061 Student (student0061)
>     Submission ID       : 8
>     Submitted on        : 2018-Dec-15 12:23 PM
>     Confirmation Number : 8-17-98871f2b-bbb3-4c6e-b047-446c163792fa-Sat Dec 15 12:23:23 EST 2018
> 
>     Assessment Due Date : 21-Dec-2018
>     Site ID             : 636d17b2-3980-4230-b560-c85e1fcece23
> 
> ---
> This automatic notification message was sent by Sakai (http://localhost:8080/portal)
> Control what email notifications you receive at Home …

SAK-41093: Samigo > format dates consistently in submission notification email

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ReorderProducer.java
lessonbuilder/tool/src/webapp/css/Simplepagetool.css
lessonbuilder/tool/src/webapp/js/reorder.js
lessonbuilder/tool/src/webapp/templates/Reorder.html

https://jira.sakaiproject.org/browse/SAK-41095
When using IE11, the "Reorder" functionality in Lessons is broken. The solution is to replace the Fluid JavaScript reorder with jQuery's, which also results in code reduction. The IE11 specific bug is detailed in the testing steps on the JIRA.

SAK-41095: Lessons > reorder doesn't work in IE11

---

library/src/morpheus-master/sass/modules/tool/forums/_forums.scss

https://jira.sakaiproject.org/browse/SAK-41082
The "Previous Topic" and "Next Topic" buttons can overlap the breadcrumbs at the large and medium screen size breakpoints. It's more easily encountered if the forum and/or topic have long titles. The problem doesn't exist at the small screen size breakpoint because it then gets it's own "row", and the breadcrumbs drop down below the buttons.
See before and after screenshots on the JIRA.

SAK-41082: Forums > previous & next topic buttons can overlap breadcrumbs

---

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-addRemoveFeatureConfirm.vm

https://jira.sakaiproject.org/browse/SAK-41088
This essentially just reverts the changes from SAK-41068 and adds some extra conditionals to render the custom tool title in brackets only if it differs from the original tool title.
Before:
> Announcements
After:
> Announcements (Custom Announcements Tool Title)
Also fixes an issue where instance based tools would display their custom tool title twice, instead of the original tool name with the custom tool name in brackets.
Before:
> Lessons Custom Title (Lessons Custom Title)
After:
> Lessons (Lessons Custom Title)
See screenshots in the JIRA.

SAK-41088: Site Info > Manage Tools > Confirmation page no longer indicates renamed tools

---

assignment/bundles/resources/assignment.properties
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CategoryDefinition.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java

https://jira.sakaiproject.org/browse/SAK-41058
In Gradebook, if you have a category with drop/highest/keep enabled, all items within the category must have the same maximum point value. This rule is enforced when creating gradebook items in Gradebook itself, but can be circumvented through tools which can send grades to the gradebook.

SAK-41058: assignments > can circumvent gradebook category with drop/keep uniform point value validation

---

lessonbuilder/tool/src/webapp/templates/instructions/website.html

https://jira.sakaiproject.org/browse/SAK-41016
As @buckett mentioned in #6311, "Upload Content from ZIP File" should contain an "a" to be "Upload Content from a ZIP File" to reflect the main change for SAK-41016. This additional PR adds the "a" because #6311 was already merged.

SAK-41016 Lessons: Add an "a" to the documentation page to reflect the earlier change

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-41058
A bug was discovered during testing. Non-primitive `Double`s were being compared with `!=` rather than `!<>.equals()`.

SAK-41058 > bug fix for Double comparison

---

library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_variables.scss
library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss
library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics_variables.scss

https://jira.sakaiproject.org/browse/SAK-41136
The reorganization of the Rubrics CSS in SAK-41081 put the Rubrics SASS variables in the Bootstrap project's _variables.scss file. My fix moves these variables to the Sakai SASS files in the Rubrics tool folder as a separate file for organizational consistency.

SAK-41136 Moved the Rubrics SASS variables to the SASS modules

---

library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java

Where a site's ID was numeric, the favorites JS was sending the Site
ID through as an integer rather than a string, causing an exception on
the server side.  Fixed this as follows:
* Have the FavoritesHandler code (server-side) coerce all incoming
Site IDs to Strings.
* Modify the jQuery code to use `.attr()` instead of `.data()` when
retrieving Site IDs off DOM elements.  This avoids any attempt to
coerce the stored values into JS types, which we didn't want
anyway.

SAK-31709 Correctly handle numeric Site IDs

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/UserNotificationProvider.java
site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/UserNotificationProviderImpl.java
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41091
There is a sakai.property to control whether or not site creation notification emails are sent by the system (`site.setup.creation.notification`), which defaults to `true`. Currently, this single property determines if emails are sent to both the user who create the site, and the admin email address.
However, some institutions may want more granular control of this behaviour. For example, institution A may want the email sent to the users who created the sites, but not the admin address. Institution B may want the complete opposite behaviour.
The linked PR here **introduces a second sakai.property (`site.setup.creation.notification.user`)**, which controls if the user creating the site receives the notification email, and the original …

SAK-41091: Site Info > new sakai.property for more granular control of site creation notification emails

---

samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessmentData.java
samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java

Steps:
1) Create a quiz with, say, 3 questions each worth 0.1 points
2) Create a gradebook category that uses at least one of the drop highest / drop lowest / keep highest features
3) Create an item in that gradebook category worth 0.3 points
Edit the quiz's gradebook item, adding it to that category
Symptom:
The point value doesn't match the existing items, so you get a feedback message indicating the point value doesn't match the maximum of 0.3. Cause we all know that 
0.1 + 0.1 + 0.1 = 0.30000000000000004
it's basic arithmetic!
Solution - when calculating the total point value of a quiz, use BigDecimal

SAK-41158 - Point values of gradebook items created from tests & quizzes can have precision errors

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java

There's a NumberFormat in ContextUtil.getRoundedValue(...), which adds grouping separators, I.e. the comma in "1,000". Some of these commas make their way into text fields (scores on the Questions tab for instance); when you submit those text fields validation errors ensue as commas are unexpected. I don't believe there are any other UIs in Sakai that use grouping on grades.
Eliminate the grouping commas by invoking 'setGroupingUsed(false)' on the NumberFormat instance

SAK-41192 - Parsing errors when grading tests & quizzes with 1000+ points

---

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/logmessage/LogMessageJob.java

The logger to use should come from the Job configuration.

SAK-41196 Have the logger come from job configuration.

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java

https://jira.sakaiproject.org/browse/SAK-41209
It may be desirable for an institution to disable the ability for users to invoke the "Set Zero Score for Empty Cells" function, as it can be dangerous and difficult to reverse.
This PR introduces a new sakai.property (`gradebookng.showSetZeroScore`), which controls whether or not the option will appear in the menu. The property defaults to `true` to preserve OOTB functionality.
This may also be a desired interim solution for those who are concerned with related issues, https://jira.sakaiproject.org/browse/SAK-33110 and https://jira.sakaiproject.org/browse/SAK-41154.

SAK-41209: GradebookNG > new sakai.property to disable 'Set Zero Score for Empty Cells'

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java

https://jira.sakaiproject.org/browse/SAK-41223
When importing a spreadsheet which contains columns for externally managed gradebook items, these items cannot be selected during the "Gradebook Item Import Selection" step. It's understood that these items can't be imported because the grades are managed elsewhere, and the rows are coloured differently to visually distinguish them along with having a status of "External".
However, it can be confusing for users that when the click the "Hide items with no changes" button, these external items remain, giving them the impression that maybe they can be imported after all, or maybe there are changes to these items which will be processed by the import. The user would probably be better served if the button extended it's behaviour to also hide the …

SAK-41223: GradebookNG > Import > extend 'hide items with no changes' to external items

---

site-manage/site-manage-participant-helper/src/webapp/content/templates/EmailNoti.html

https://jira.sakaiproject.org/browse/SAK-41142
To avoid a 404 console error, I've removed a link reference to an AddParticipant.css file that doesn't exist in the Sakai code anymore.

SAK-41142 Removed link reference to nonexistent css file in Add Participants process

---

assignment/bundles/resources/assignment.properties
assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm

https://jira.sakaiproject.org/browse/SAK-40080
I've updated the wording and some minor colour and styling issues on the Assignments grading list page for the Resubmissions panel to reflect the changes done SAK-40074 to the twin panel for feedback.
See https://jira.sakaiproject.org/browse/SAK-40080 for the before and after screenshots.

SAK-40080 Assignments: Updated the wording of the Resubmissions option on the grading list page

---

samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp

@bjones86 I've seen you extended the method here:
https://github.com/sakaiproject/sakai/commit/896eff65b1a0a7a42577f5f8cf84863a25aea720
This wasn't working before, because it wasn't even pointing to the .js file that defines it, but I'm wondering if it's right just removing it or not. Thanks!
(All the fields on that screen seem to be properly stored)

SAK-41203 removing code that was throwing error

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties

https://jira.sakaiproject.org/browse/SAK-41234
Amend the current message to indicate removal of external gradebook items must also be done through the external tool:
> Please go to `toolTitleHere` to edit the title, points, and due date, or to remove the item from the Gradebook.

SAK-41234: GradebookNG > improve external item information message

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverrideLogPanel.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeLogPanel.java

https://jira.sakaiproject.org/browse/SAK-41233
Currently the grade log (for both course grades, and grade items) displays only the user's ID who made the change. Depending on the institution/system/user, the user ID may not be helpful or intuitive information for the end user. To better assist the user in determining who actually made changes, let's also provide the user's first and last name. Ex: "John Doe (jdoe99)"
See screenshots in the JIRA.

SAK-41233: GradebookNG > add user's first and last name to grade log entry display

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java

https://jira.sakaiproject.org/browse/SAK-41232
When you elect to do a custom export of the Gradebook, the message to the user states:
> Customized exports can only be imported back into the system if Student ID and Student Name are retained in the first and second columns and all other formatting conventions are followed.
However, the "Student Display ID" option is in between the "Student ID" and "Student Name" options (the two which must be retained as the first and second columns in the file in order to make it compatible with the import function). If "Student Display ID" is selected, it effectively produces a CSV which will not be able to be imported because the "Student Display ID" column will be in the second column. the "Student Display ID" column is also not prefixed with the "#" …

SAK-41232: GradebookNG > improve ability to import a custom exported file

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/CommentValidator.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.java
gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml

https://jira.sakaiproject.org/browse/SAK-41251
You'll get a stack trace when entering grades in the table (see JIRA for actual stack trace). This is a regression caused by #6485 (https://jira.sakaiproject.org/browse/SAK-41222), where it was requested that all `ServerConfigurationService` calls be refactored to use the API rather than the Cover. This is apparently an area I neglected to test.
I also noticed that comment length validation is not properly implemented when adding/editing comments through the grades table. If the comment is too long, clicking the save button does nothing and the logs spit out warnings about message bundle keys not being found. This PR refactors this area to provide a proper feedback message to the user indicating why the comment was not saved.

SAK-41251: GBNG > stack trace when entering grades in table

---

samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
samigo/samigo-app/src/webapp/jsf/delivery/tableOfContents.jsp
samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/AudioRecording.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/CalculatedQuestion.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/ExtendedMatchingItems.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/FileUpload.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/FillInNumeric.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/FillInTheBlank.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/ImageMapQuestion.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/Matching.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/MultipleChoiceMultipleCorrect.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/MultipleChoiceSingleCorrect.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/ShortAnswer.jsp
samigo/samigo-app/src/webapp/jsf/print/preview_item/TrueFalse.jsp

Wanted to check all screens that would display the point value when testing SAK-41192. The student taking the quiz has the point value displayed with a comma.
No user-facing errors and no errors in the logs.

SAK-41217 - Samigo: Questions worth over 1000 points display with a comma in the student view when taking quiz

---

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm

https://jira.sakaiproject.org/browse/SAK-41258
This is a regression caused by the massive SWITCH-ing of site-manage in #5865 (https://jira.sakaiproject.org/browse/SAK-40098). This restores the ability to add a roster once all rosters have been removed from the site. I also fixed a few small messaging issues I noticed while I was testing.
The original permission check was passing `null` into `SiteService.allowAddSite()`, however it made more sense to pass in the actual site ID here.

SAK-41258: Site Info > can't add roster if no rosters are already attached to site

---

library/src/morpheus-master/js/src/sakai.morpheus.i18n.utils.js

- One condition has been added to loggedIn, we check if bullhorns are enabled on server to run proper code.
- Even if bullhorns are enabled translations are not modified as fast to make a call to server on every page so that i18n have been added to sessionStorage so the ajax calls are just made once per session or when user change language.
- PortalCDN has been added to AJAX call so user's browser don't make it between deploys.

SAK-41256 - Millions of request to getI18NProperties with bullhorns disabled

---

samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp

https://jira.sakaiproject.org/browse/SAK-41306
When taking an assessment with an "Honour Pledge", the state of the "Begin Assessment" button is erroneous. It appears like a normal button, in that it's styled as an enabled, active button which gives the user the impression they can click continue without checking the honour pledge checkbox. However, when they click the button, they get an error message saying "Required" beneath the honour pledge checkbox.
The correct behaviour should be that the button should be disabled on load of the page, be enabled when the user checks the box, and disabled again if the use deselects the box.

SAK-41306: Samigo > incorrect button styling for Honour Pledge assessment

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties

https://jira.sakaiproject.org/browse/SAK-41303
It's been reported that users have erroneously input their own institutional passwords into this field, thinking it required their personal password to save the settings. This resulted in students not being able to take said quizzes because they obviously did not know the instructors' password, and the instructor clearly would not distribute their personal passwords to students. This was further complicated in older Sakai installations where there was also a 'Username' field, which may have prompted some browsers to automatically fill in these fields with saved values.
To try to prevent the issue from occurring, and to make the assessment password field less confusing for some users, this PR proposes changing the label to be "Assessment …

SAK-41303: Samigo > further quality password field label for clarity

---

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java

https://jira.sakaiproject.org/browse/SAK-41300
When importing a quiz which was exported with the _Assessment released to_ setting set to "Anonymous", this setting is not preserved. It ends up being released to the entire site when imported.
The behaviour should be as follows:
* If quiz is released to default *Entire Site* in site 1, imported quiz should be released to *Entire Site* in site 2.
* If quiz is released to *Selected Group(s)* in site 1, imported quiz should be released to *Entire Site* in site 2.
* If quiz is released to *Anonymous Users* in site 1, imported quiz should be released to *Anonymous Users* in site 2. *Issue:* Currently, anonymous release assessments are switching to *Entire Site* release.
This bug was introduced in …

SAK-41300: Samigo > importing quiz released to anon users doesn't preserve the setting

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41287
This PR proposes implementing a new sakai.property (`wsetup.defaultSiteVisibility`), which controls the default value selected in the "Site Visibility" section of "Site Access", when creating a new site of any type. The new config option will default to `true` to preserve OOTB functionality.
NOTE: this config will only be taken into effect for site types which you've defined as being able to change this "public" vs. "private" setting by the end user, via the existing sakai.property `site.types.publicChangeable`. The relevant OOTB defaults effectively make course sites always public, and does not give the user the option to change this value for course sites. Therefore, OOTB, this *new* property will only control the default selection for …

SAK-41287: Worksite Setup > new config for default site visibility setting

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java

https://jira.sakaiproject.org/browse/SAK-41264
the *Stop Accepting Now* button in samigo's _Settings_ page on *Published Copies* is not correctly overriding any existing *due* or *late accept* date and immediately retracting the test.
*Stop Accepting Now* inserts a date in the _Late submissions accepted_ > *Yes, until* (aka Retract date) field to perform the override.  If desired, it also should allow you to enable *Autosubmit* at the time you *Stop Accepting*.
If you have a test that previously did NOT have *Autosubmit* enabled, has no due date, and doesn't accept late submissions, you select *Autosubmit*, then *Stop Accepting* it, you get an error: "The latest acceptance date must be set to force submission of saved student work after the due date."  As a result of several other JIRAs, …

SAK-41264: Samigo > 'stop accepting now' not working on tests with 'no late submissions accepted'

---

mailarchive/mailarchive-impl/impl/src/java/org/sakaiproject/mailarchive/impl/SiteEmailNotificationMail.java

https://jira.sakaiproject.org/browse/SAK-41266
It would be very beneficial to include the site title in the subject line of email sent from the Email tool. This helps users distinguish the context of the email they receive.

SAK-41266: Email > include site title in subject line

---

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss

https://jira.sakaiproject.org/browse/SAK-41305
If you create an assessment with a couple File Upload Questions and download student submissions using *Download File Submissions*, random numbers display underneath the check boxes to select questions from which you want to download. See before and after screenshots in the JIRA.
These are probably internal IDs of some sort, but they have no meaning, are confusing to the user and just clutter up the UI. Let's hide them.

SAK-41305: Samigo > Download File Submissions page shows internal IDs for each question

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties

https://jira.sakaiproject.org/browse/SAK-41327
Some students have expressed confusion over the current language displayed to them when starting a quiz. The current wording can give the student the impression that multiple attempts are allowed, even if the instructor has not enabled this setting for the quiz in question.
This PR proposes the following modifications to the messages:
```
- begin_assessment_msg_highest=Answers from previous attempts will not be available within the assessment during subsequent attempts. Your highest score will be recorded.
- begin_assessment_msg_latest=Answers from previous attempts will not be available within the assessment during subsequent attempts. Your latest score will be recorded.
- begin_assessment_msg_average=Your average score will be recorded.
+ …
```

SAK-41327: Samigo > clarify text shown to students when beginning a quiz

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41326
Currently, when sites which contain one or more stealthed tools are duplicated, these stealthed tools are copied into the new duplicate site. This may be undesirable for certain institutions, who would benefit from having a configuration option to control this behaviour.
This PR introduces a new sakai.property (`site.duplicate.removeStealthTools`), which determines if stealthed tools are copied during a site duplication. The property defaults to `false` to preserve OOTB functionality (stealthed tools will be copied to duplicates by default).

SAK-41326: Site Info > new config to prevent stealthed tools being copied to duplicate sites

---

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm

https://jira.sakaiproject.org/browse/SAK-41348
If a user selects to create a course site which does not yet have any rosters for selection (and the continue with no roster button is enabled via sakai.properties), the 'Continue' button is disabled, the "Back' button becomes the primary action button, and the "Continue with no roster" button is displayed to the very right, after the "Back" and "Cancel" buttons.
The linked PR proposes moving the "Continue with no roster" button to be to the right of the "Continue" button, with the "Back" and "Cancel" buttons further to the right. It also makes the 'Continue with no roster" button the primary action button when there are no rosters selectable (instead of the "Back" button becoming primary).

SAK-41348: Worksite Setup > position and primary action for 'continue with no roster' button

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm

https://jira.sakaiproject.org/browse/SAK-41347
The permission "site.del" determines if a user can softly delete a site, and the permission "site.del.softly.deleted" determines if a user can hard delete a previously softly deleted site.
However when a user is in the "View: Softly Deleted Sites" UI, the "Delete" button is present regardless of if the user has the "site.del.softly.deleted" permission. If the user lacks this permission, makes some selections from the table and selects "Delete", they will be presented with an error message indicating they don't have the necessary permissions to perform the action.
This PR introduces more logic to conditionally render the (hard) "Delete" button in the "View: Softly Deleted Sites" UI.

SAK-41347: Worksite Setup > Softly Deleted Sites > display 'Delete' button conditionally based on permission

---

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/content/content.properties

https://jira.sakaiproject.org/browse/SAK-41276
The current wording of the message shown to users when offending content has been stripped by AntiSamy could be slightly confusing to users:
> Your HTML contains tags or attributes that are not permitted and have been removed from your content.
The linked PR proposes updating this text to the following, to reassure users that their valuable content should remain in tact:
> Your HTML contains tags or attributes that are not permitted and have been removed. This change may affect some formatting, but should not affect actual content.

SAK-41276: improve user facing content cleaned message

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-41346
Currently if an instructor tries to delete the only remaining roster attached to a course site (and there are no manually enrolled users with the maintain role), the instructor will receive an error message:
> Alert: The site has to have at least one user with role Instructor.
This PR proposes to change this behaviour so that the user is automatically enrolled as a non-provided maintainer role in the course site so that they are able to delete the last roster attached to a site. This has been reported as a pain point for users, as they have to remember to add a roster before they can remove the last roster. It also allows them to utilize the site without having a roster attached.

SAK-41346: Site Info > allow maintainer to delete last roster in course site

---

admin-su/pom.xml
chat/chat-tool/tool/pom.xml
commons/tool/pom.xml
deploy/pom.xml
feedback/pom.xml
help/help-tool/pom.xml
jobscheduler/scheduler-tool/pom.xml
master/pom.xml
msgcntr/messageforums-app/pom.xml
podcasts/podcasts-app/pom.xml
roster2/pom.xml
roster2/tool/pom.xml
rwiki/rwiki-tool/tool/pom.xml
samigo/samigo-app/pom.xml
signup/pom.xml
signup/tool/pom.xml
simple-rss-portlet/pom.xml
user/user-tool-prefs/tool/pom.xml

I've changed the pom files to remove jstl library from tomcat /lib folder and add it into the tools it's needed (syllabus, rss news, signup and podcasts).

SAK-41010 Remove jstl library from lib and move to tool scope

---

polls/api/src/java/org/sakaiproject/poll/logic/ExternalLogic.java
polls/impl/src/java/org/sakaiproject/poll/logic/impl/ExternalLogicImpl.java
polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
polls/impl/src/java/org/sakaiproject/poll/service/impl/PollVoteManagerImpl.java
polls/impl/src/test/org/sakaiproject/poll/logic/test/stubs/ExternalLogicStubb.java

https://jira.sakaiproject.org/browse/SAK-41394
Events fired by the polls tool do not have a consistent ref format, and are sometimes duplicated or misnamed because the LRS support added to polls creates its own events in addition to the existing polls events.
After this patch:
- all polls event refs will use the same format: poll/site/<site_id>/poll/<integer_poll_id>
- events with LRS support will not fire any additional events, and the LRS events will use a proper poll ref instead of simple strings like "vote" and "edit poll"
- the "poll.edit" event fired by the LRS support code will use the original event name, "poll.update" instead
- the "poll.vote" event will fire once for each selected option (for polls that allow multiple selection), as this is how the LRS support works. This …

SAK-41394: Clean up polls events

---

library/src/webapp/editor/ckextraplugins/contentitem/plugin.js

This is the minimal fix for the problem, but the whole plugin should be
cleaned up. The problem was with multiple editor instances on the page
and some incidental shared state.
The init function registers the ContentItemDialog with the top level
CKEDITOR object for each editor instance. What was happening in this
particular case was that the dialog was overwritten with the binding to
the second instance, for peer assessment, which is hidden. The editor
reference in the onOk callback was not for the actual editor that
invoked the dialog, but the last one initialized.
The error thrown was for the first selection range (range.checkReadOnly)
from insertHtml/insert in editable.js in CKEditor. With the second
editor hidden, the selection range array is empty, so the first item was
undefined. …

SAK-41442 - Fix ContentItem insertion in Assignments

---

samigo/samigo-app/src/webapp/jsf/delivery/assessmentDeliveryTimer.jsp
samigo/samigo-app/src/webapp/jsf/delivery/confirmSubmit.jsp
samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
samigo/samigo-app/src/webapp/jsf/delivery/tableOfContents.jsp
samigo/samigo-app/src/webapp/jsf/shared/removeMedia.jsp
samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js

These are the three errors explained:
1. When you are on an assessment and student tries to save it, the error in the first screenshot appears because there is an undefined variable. DisableSave does not exists and it is unnecessary to keep it. It is needed to change variable loaded by its supossed value because it is undefined too. (first commit in the PR)
2. qtip plugin required images are not loaded (some images are heavier than others) and so we need to wait until all page has loaded (2nd commit)
3. RemoveMedia.jsp is in shared folder and when student tries to delete a file they can't see time variables because routePrefix is not correct, it supposes to be on same URL ("") but it's on "../delivery" because all other jsp assessment files are on "delivery" folder so we unify URL call. …

SAK-41333: Some javascript error on Tests & Quizzes

---

edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementAdministrationHibernateImpl.java

1) Insert users from your SIS that with user EIDs that contain upper case letters. E.g. for Sakora:
1a) In people.csv, define some entries where the student's eid contains uppercase letters
1b) Add the students to a section in sectionMembership.csv
1c) Run Sakora
2) In a course site that uses a section which contains users whose eids contain upper case letters, view, say, the gradebook
Symptom: the students with EIDs containing uppercase characters are not consistently included in the student list
If you query the sakai_realm_rl_gr, you can see the user popping in and out of the site, likely once every time refreshAuthzGroup is invoked.
Note that user EIDs in sakai_user_id_map are always inserted in lower case.
My best guess to the cause is that:
1) RefreshAuthzGroup …

SAK-41228 - User EIDs containing upper case characters inserted into Course Management Tables causes authZ issues

---

webcomponents/pom.xml

The webcomponents "assets" folder won't build if you compile as a root user, tested in a ubuntu distribution.
Source: https://til.codes/npm-install-failed-with-cannot-run-in-wd-2/
Documentation: https://docs.npmjs.com/misc/config#unsafe-perm
This may introduce security concerns.

webcomponents won't build as root user

---

rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js

When grading a forum with Rubrics, the portal variable is not defined in the modal window.
`
sakai-rubrics-language.js:25 Uncaught ReferenceError: portal is not defined
at Function.loadTranslations (sakai-rubrics-language.js:25)
at new SakaiRubricGrading (sakai-rubric-grading.js:13)
at sakai-rubric-grading.js:105
loadTranslations @ sakai-rubrics-language.js:25
SakaiRubricGrading @ sakai-rubric-grading.js:13
(anonymous) @ sakai-rubric-grading.js:105
`

SAK-41459 Grading forums: Portal is not defined in the modal window

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java

Assignments were being counted as having a grade even when excused.
This presented an issue for weighted categories and possibly a display
issue for students that only had excused grades.
Original commit message:
SAKAI-4306 excused grades being counted in course grades
fixed logic that was causing excused grades to still count in course grade.

SAK-41440 Course grade miscalculates when you excuse a grade

---

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java
rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rating.java
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js

Attaching mysql ddbb script in case someone was using an old ddbb (no need
to incorporate it to the official code if it makes the 19release):
```
ALTER TABLE `rbc_criterion` CHANGE COLUMN `description` `description`
LONGTEXT NULL DEFAULT NULL ;
ALTER TABLE `rbc_rating` CHANGE COLUMN `description` `description`
LONGTEXT NULL DEFAULT NULL ;
```

SAK-41488 Rubrics : Allow longer descriptions

---

rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
rubrics/tool/src/main/java/org/sakaiproject/rubrics/RubricsConfiguration.java

Also, unify delete methods that were doing the same into one function
valid for all the elements.

SAK-41018 Rubrics: delete evaluations before deleting association

---

polls/api/src/java/org/sakaiproject/poll/hbm/Option.hbm.xml
polls/api/src/java/org/sakaiproject/poll/model/Option.java
polls/api/src/java/org/sakaiproject/poll/util/PollUtil.java
polls/impl/pom.xml
polls/impl/src/java/org/sakaiproject/poll/logic/impl/PollOrderOptionBackFillJob.java
polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
polls/impl/src/test/org/sakaiproject/poll/logic/test/PollListManagerTest.java
polls/impl/src/test/org/sakaiproject/poll/logic/test/TestDataPreload.java
polls/impl/src/webapp/WEB-INF/components.xml
polls/tool/src/java/org/sakaiproject/poll/tool/entityproviders/PollOptionEntityProvider.java
polls/tool/src/java/org/sakaiproject/poll/tool/entityproviders/PollsEntityProvider.java
polls/tool/src/java/org/sakaiproject/poll/tool/params/PollToolBean.java
polls/tool/src/java/org/sakaiproject/poll/tool/producers/AddPollProducer.java
polls/tool/src/java/org/sakaiproject/poll/tool/producers/PollOptionDeleteProducer.java
polls/tool/src/java/org/sakaiproject/poll/tool/producers/PollOptionProducer.java
polls/tool/src/java/org/sakaiproject/poll/tool/producers/PollVoteProducer.java
polls/tool/src/java/org/sakaiproject/poll/tool/producers/ResultsProducer.java
polls/tool/src/java/org/sakaiproject/poll/tool/validators/OptionValidator.java

https://jira.sakaiproject.org/browse/SAK-41391
Conversion scripts PR: https://github.com/sakaiproject/sakai-reference/pull/49
This bug only affects those who are running with an Oracle database. When creating options for a poll the display of these options (for both instructors and students) may appear in a "random" order, rather than the order in which they were created.
The cause of this bug is that the code is doing an `ORDER BY` clause on the `optionId` column, which is the primary key of the table:
```
public List<Option> getOptionsForPoll(Long pollId) {
Poll poll;
try {
poll = getPollById(pollId, false);
} catch (SecurityException e) {
throw new SecurityException(e);
}
if (poll == null) {
throw new IllegalArgumentException("Cannot get options for a poll ("+pollId+") that does not …
```

SAK-41391: Polls > in an Oracle environment poll options are not displayed in the order they're created

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport.properties
samigo/samigo-app/src/webapp/jsf/qti/chooseExportType.jsp
samigo/samigo-app/src/webapp/jsf/qti/importAssessment.jsp

https://jira.sakaiproject.org/browse/SAK-41328
There is currently a bug in Samigo where if you have a quiz which contains any *Multiple Choice, Multiple Selection* questions that are set to require *All or Nothing* to get the question correct, exporting and importing this quiz into further sites will not retain the *All or Nothing* setting. The resulting imports will have changed this setting to *Correct minus Incorrect* without the user realizing it.
This is a usability issue for instructors, and can affect grading of students if the instructors don't fully vet each imported quiz before publishing. This bug is captured in https://jira.sakaiproject.org/browse/SAK-34222, and seems to be a deficiency in the export file produced.
In the interim, this PR proposes to add warnings in the UIs so …

SAK-41328: Samigo > interim solution for SAK-34222

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties

https://jira.sakaiproject.org/browse/SAK-41304
Instructions in the authoring of *Fill in the Blank* questions describe using a wilcard * to allow entry of any character to count as a valid response.  However, it is not clear that the wildcard means at least one character must be entered there by the student for the answer to be correct.  This can result in unexpected scoring.  This PR proposes to change the wording of the existing instruction:
> Insert an asterisk (*) for one or more wildcard characters.
To the following:
> Insert an asterisk (*) for one or more required wildcard characters.

SAK-41304: Samigo > improve wording of wildcard option in FITB question author screens

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm

https://jira.sakaiproject.org/browse/SAK-41286
When selecting rosters to attach to a course site (either via _Worksite Setup_ when creating a new course site, or _Site Info_ > _Edit Class Roster(s)_), the only information displayed to the user about a given section is it's title. It can be beneficial to give the user more information here to better assist them in making a decision.
At some point in the past, someone already tried to (or thought about) adding the description to the display. We already have code in one of the velocity templates that would spit out this information, if the backing object in Java was populated accordingly. From `chef_site-newSiteCourse.vm` @ line 82:
```
<th colspan="2" title="$!courseObject.eid">
$!courseObject.title $!courseObject.description
#if …
```

SAK-41286: site-info > provide more info when displaying rosters available for selection

---

samigo/samigo-app/src/webapp/js/questionProgress.js

We have several students which uses old browser versions without localStorage in their browsers so they get a JS error and they can't complete an exam.
This fixes that issue.

SAK-41591 - JS Error on Samigo for old android devices and browsers

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

The examples:
```
```
The asterisks don't actually work in this pattern.
Replace these examples with:
```
```

SAK-41617 - default.sakai.properties advertises using asterisks after package names in log.config

---

content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/ContentReviewQueueServiceImpl.java

In ContentReviewQueueServiceImpl.queueContent(...), we throw a QueueException if an item already exists. If you're resubmitting multiple attachments, and some of these attachments already exist, this QueueException will abort the whole process. We should instead aggregate these and then just throw one exception after the valid items have been queued

SAK-41603 - Queuing multiple attachments to the content review service - errors prevent subsequent attachments from being queued

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewList.vm

- These removals are also on the service class. Service class needs it for this process but also for the transferEntities one, so keeping those.
- Also solving calendar vm error log trace.

SAK-40413 Duplicated removals cause log error trace

---

library/src/morpheus-master/sass/modules/tool/_table.scss
library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm

https://jira.sakaiproject.org/browse/SAK-41671
Added a separator to the Worksite Setup > Site List filter controls to better define grouping. 
Please see the before and after screenshots attached in SAK-41671.

SAK-41671 Added a separator to the Worksite Setup > Site List filter controls to better define grouping

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java

https://jira.sakaiproject.org/browse/SAK-41687
[SAK-41222](https://jira.sakaiproject.org/browse/SAK-41222) introduced a new sakai.property to control the ability of instructors/maintainers to change the "Display final Grades to Students" option. However, if an instructor clicks on the "Grade not visible" eyeball icon in the "Course Grade" header cell, an "Edit Release Settings" link still appears in the resulting pop-up. The link takes them to the settings page, where they will not be able to change the setting (in the scenario where the sakai.property is set to false, thus not giving the instructor the option at all in this interface).
The link in the pop-up should be conditionally rendered, according to the value of the sakai.property introduced in …

SAK-41687: GradebookNG > hide 'edit release settings' based on sakai.property

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

https://jira.sakaiproject.org/browse/SAK-41703
Sometime after 12.0, the code in `AssignmentAction.setScoringAgentProperties()` was updated which introduced a regression where the instructor would not see the scoring component icons in the grade submission UI (provided there was a scoring component attached to the assignment/gradebook item).
The following lambda is what introduced the problem:
```
AssignmentSubmissionSubmitter submitter = submitters.stream()
.filter(s -> s.getSubmitter().equals(currentUser)).findAny()
.orElseGet(() -> submitters.stream()
.filter(AssignmentSubmissionSubmitter::getSubmittee).findAny()
.orElse(null));
```
In the student context (where a student is looking at their own submission), the above code's `.filter()` routine would successfully find the studentt's own …

SAK-41703: assignments > fix scoring component icons for instructor view

---

library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
msgcntr/messageforums-app/src/webapp/css/msgcntr.css
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfFlatView.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfPendingMessages.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThread.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThreadBodyInclude.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/printFriendly.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/printFriendlyThread.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyAllAuthoredMsg.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyDisplayInThread.jsp
msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyFullTextForOne.jsp

https://jira.sakaiproject.org/browse/SAK-41713
To address issues with horizontal scrolling in Forums conversations containing posts with non-breaking spaces or posts with large images, this PR fixes a number of layout issues to improve the responsiveness of Forums: 
- images are constrained to the screen width whenever possible
- textual content containing non-breaking spaces don't affect other threaded posts in the conversation
- navigational controls don't cause the table to be larger than the screen
- the various views and pages in Forums takes these factors into consideration
Please see SAK-41713 for some before and after screenshots.

SAK-41713 Forums: improved the responsiveness of conversations particularly for wide content

---

library/src/morpheus-master/sass/modules/tool/signup/_signup.scss
signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp

https://jira.sakaiproject.org/browse/SAK-41422
I've removed the inline styles that was applying a fixed width on the buttons, which limited how much text the button could display and therefore cutting off the buttons' text. 
I added some styles to control the buttons' width and spacing. I assume the original fixed-width was for the buttons to be the same width when they contained different lengths of text. My new styles recreates that functionality while allowing the buttons to be as wide as they need to be for their text.
See before and after screenshots in https://jira.sakaiproject.org/browse/SAK-41422

SAK-41422 Removed the fixed width from the buttons to show entire button text

---

library/pom.xml
library/src/morpheus-master/sass/modules/tool/mycalendar/_mycalendar.scss

https://jira.sakaiproject.org/browse/SAK-41732
Updated libsass dependency to latest (0.2.10-libsass_3.5.3) to fix an issue I've noticed with CSS source map creation. 
The new version detected a compiling issue that the old version ignored, so I resolved that too.

SAK-41732 Updated libsass to 0.2.10

---

delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/jobs/DelegatedAccessSiteHierarchyJob.java

https://jira.sakaiproject.org/browse/SAK-41739
If the `DelegatedAccessSiteHierarchyJob` Quartz job gets interrupted while executing (for example, by a Tomcat restart) it will attempt to auto-relaunch itself when the server comes back up. Unfortunately, it does this too early in the process, before all the Spring beans are injected, and so it fails. This causes an infinite loop, where it will continue failing and trying to auto-relaunch on restart.

SAK-41739: DA > prevent hierarchy job from auto-restarting

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchAccessPage.java

https://jira.sakaiproject.org/browse/SAK-41740
SAK-27769 introduced a new sakai.property to define friendly labels for use when not using the default hierarchy levels. However, some places in the UI are still using the property names, rather than their corresponding labels.
The `sakai.property` "delegatedaccess.hierarchy.site.properties" defines the list of properties, or "levels", when over-ridden:
```
#INFRSTR-257 - Delegated Access                                                                                               
#delegatedaccess.hierarchy.site.properties                                                                                    
#This property allows you to overwrite the default site hierarchy properties expected in a Site.                              
#Example: …
```

SAK-41740: DA > use friendly label for over-ridden hierarcy props

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
content-review/impl/turnitin-oc/README.md
content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

A couple constants are defined:
private static final int TURNITIN_OC_MAX_RETRY_MINUTES = 240; // 4 hours
private static final int TURNITIN_MAX_RETRY = 16;
Following through the retry delay algorithm: 
Σ(retry = 1..16) min(2^retry, 240)
2+4+8+16+32+64+128+240*9=2414 minutes
The delays sum to ~40 hours
In our experience there are situations where Turnitin servers are unresponsive, or a change is required on our side, and the retry automatically corrects it. But in many cases it takes more than 40 hours before these situations are resolved.
Add configuration to modify the behaviour of how we delay between retries

TII-261 - TurnitinOC - retry delay algorithm improvements

---

providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java

With the unboundid LDAP provider using connection pooling, if an LDAP server is unavailable when Sakai starts, then the connection pool is not created and LDAP auth attempts will fail until the app server is restarted, even if the LDAP server comes back online.
This retries creation of the connection pool when an LDAP auth or search request is attempted, if the pool has not already been created.
The method is synchronized and there are some checks to avoid multiple connection pools being created.

SAK-41785 Retry setup of the LDAP connection pool after startup

---

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm

https://jira.sakaiproject.org/browse/SAK-41752
The logic to display the 'Hard Delete' button isn't synchronized properly between the top and bottom action panels. The bottom panel is displaying the 'Hard Delete' button appropriately when the user has the correct permissions. However, the top section does not display this button when it should for non-admin users.

SAK-41752: Worksite Setup > 'Hard Delete' button not displaying in top section when present in bottom section

---

rwiki/rwiki-util/radeox/src/java/org/radeox/macro/IsbnMacro.java
rwiki/rwiki-util/radeox/src/test/java/org/radeox/test/macro/IsbnMacroTest.java

Old 10 digit ISBNS can have an X as the check digit. This fixes the Rwiki ISBN Macro to allow the X character.

SAK-41800 Allow the character X or x in ISBN

---

assignment/bundles/resources/assignment.properties
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

For content review errors, we currently swallow any messages from the content review service, and instead display messages from our own message bundles such as the following:
"An error occurred while submitting this item to the originality checking service."
It can be beneficial to show content-review errors to end users so that they can understand and resolve issues on their own, such as "the submission contains less than 20 words", "the due date has passed", etc.
Add configuration in sakai.properties allowing institutions to display these messages to end users

SAK-41791 - Add configuration to expose content-review errors to the UI

---

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

When attempting to view originality reports for sakai demo student student0008 (El Niño), or student0009 (Ângeolo Haslip), the following JSON is sent to TII:
{"similarity":{"modes":{"all_sources":true,"match_overview":true}},"viewer_default_permissions_set":"INSTRUCTOR","author_metadata_override":{"given_name":"
El","family_name":"Niño"},"viewer_user_id":"some uid","locale":"en"}
The response is a 400 with message "Invalid JSON".
Students without accent characters are fine.
Encode transmissions to TII in UTF-8

TII-264 - TurnitinOC - 'Invalid JSON' response when using special characters

---

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

If you disable your internet connection and run the queue job, the 'last_error' column is populated with your turnitin service url's host name (because a java.net.UnknownHostException is thrown, and the exception message is just the host name). The last_error message should be replaced with something more akin to "Failed to retrieve an originality score from Turnitin"

TII-266 - TurnitinOC - improve error message when retrieving reports while connectivity to TII is down

---

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

Currently in generateSimilarityReport, we have the following line:
indexingSettings.put("add_to_index", true);
We should pull this from the assignment settings

TurnitinOC - add_to_index property should match the assignment setting

---

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

If you upload a password protected pdf (and possibly any password protected format that Turnitin supports), the Turnitin returns the 'CORRUPT_FILE' error. We interpret that for end users as "The uploaded file appears to be corrupt", which is misleading in the password protection scenario

TurnitinOC - CORRUPT_FILE error code - mention password protected files

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/base/_extendables.scss
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm

https://jira.sakaiproject.org/browse/SAK-41866
Created the foundation for a standard set of Sakai message banners for the SWITCH project. Updated one banner in Site Info as an example. Additional subtasks will update the rest of the banners in the coming weeks from a team of SWITCH developers.
See https://jira.sakaiproject.org/browse/SAK-41866 for screenshots of the example banners and for more information.

SAK-41866 Library: Created standard set of Sakai message banners

---

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java

Right now, we're just populating it with info like:
"Submission returned with ERROR status"
The responses / callbacks from TII contain information that can be beneficial for troubleshooting, for instance the error_code attribute in the following callback:
{"owner":"some uid","title":"tinySub2.txt","status":"ERROR","id":"some uid","content_type":"text/plain","page_count":1,"word_count":6,"charact
er_count":19,"error_code":"TOO_LITTLE_TEXT","created_time":"2019-05-15T16:09:21.485Z"}
Populate the lasterror column with this information.

TII-263 - populate contentreview_item's lasterror column with detailed information

---

chat/chat-tool/tool/pom.xml
chat/chat-tool/tool/src/webapp/jsp/prelude.jspf
chat/chat-tool/tool/src/webapp/jsp/roomMonitor.jspf

For this fix to be applied to 12.x, I needed to add some runtime libraries and upgrade taglibs from 1.0.4. I chose 1.1.2 because this is the version already used by the site/admin-prefs tool in 12.x.

SAK-41763: XSS in chat user name - 12.x

---

rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-creator-name.js
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-modified-date.js
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-readonly.js
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-site-title.js
rubrics/tool/src/main/frontend/webcomponents/sakai-rubric.js

Before you look for a the JIRA (https://github.com/sakaiproject/sakai-reference/issues/66)
What this changes: The web components in Rubric generally follow a naming convention to ensure there aren't name collisions later on (nice). But, 3 do not so they should be renamed to ensure consistency:
- site-title
- modified-date
- creator-name
This PR will rename these to ensure this happens. I have more feedback about the components as well as fixes but will wait until I'm able to figure out how to get a JIRA account so I can submit a real issue to start said conversation around some of these issues.

SAK-41899: rubric name space web components as sakai-rubric to at keep a convention

---

site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm
site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_enrolments.vm
site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_joinable.vm

https://jira.sakaiproject.org/browse/SAK-41893
When using the Membership tool to search, all three tabs suffer from a bug whereby the message indicates there are no sites matching your search, when in fact there are sites which match. This affects 'My Current Sites', 'My Official Course Enrolments', and 'Joinable Sites'.

SAK-41893: Membership > inconsistent messaging when searching

---

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/detailed/refresolvers/MsgForumsReferenceResolver.java

https://jira.sakaiproject.org/browse/SAK-41957
Forums uses a single-table inheritance structure to model topics and forums. Internally, Forums service methods will often cast directly to the appropriate subclass. For example, a Topic object is cast to DiscussionTopic.
When these methods are called from SiteStats with the default database setting, Hibernate returns proxy objects instead of the real objects. The proxy objects are for the base class (ie. TopicImpl_$$_jvst4cf_3b), which then cannot be cast to the subclass (DiscussionTopic) and we get a ClassCastException. Interestingly, the same code does not return proxies when called from within Forums, or from SiteStats when it is configured to use an external database.
To get around this problem, this patch unproxies the objects similarly …

SAK-41957: Forums ClassCastException when calling services from SiteStats

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment_honor_pledge.vm

This was the only way to solve this case avoiding changes on the api, while at the same time keeping the map order (LinkedHash from java).
Also as of now a resubmitted status will always mean a submission was made.

SAK-41984 Submission confirmation page: show honor only when due

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/experimental.sakai.properties

Don't appear "Average presence time per visit" because the property is wrong
The bean was changed on SAK-32358 but the property is still on org.sakaiproject.sitestats.api.StatsManage instead of org.sakaiproject.sitestats.api.StatsManage.target 
Check the table sst_presences

SAK-41974: Statistics: Don't appear 'Average presence time per visit' since 11.x

---

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java

As commented on the jira, this is just to prevent the error. A
non-classy-but-maybe-better solution would be to loop through the all
values on TimeZone.getAvailableIDs() and pick the first one that matches
the value.

SAK-42075 Calendar: unable to import ICS file via ICalendar

---

library/src/webapp/content/gateway/about.html
library/src/webapp/content/gateway/about_mn.html
library/src/webapp/content/gateway/acknowledgments.html
library/src/webapp/content/gateway/acknowledgments_mn.html
library/src/webapp/content/gateway/features.html
library/src/webapp/content/gateway/features_mn.html
library/src/webapp/content/gateway/training.html
library/src/webapp/content/gateway/training_mn.html

https://jira.sakaiproject.org/browse/SAK-41891
Small fix-when you aren't logged in to Sakai, the gateway sites (Features, Acknowledgements, etc.) are unstyled because they reference library/skin/default/tool.css instead of /library/skin/morpheus-default/tool.css. This PR fixes those stylesheet links

SAK-41891 Library changed gateway css links to prevent un-styled pages

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java

Old behavior displayed a percent correlated with the new overridden letter grade.

SAK-33996 display the overridden letter course grade with the student's calculated percent next to it. 

---

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/CourseGradeRecord.java

We need to add these for compatibility in GB Classic, only in 12.x

SAK-41295 Course grade miscalculates if there's an Extra Credit category compatibility in GB Classic

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

The presentation tool was part of OSP which isn’t part of Sakai any more. The properties can therefore be removed from the default properties file.

SAK-42148 Remove unused OSP properties

---

commons/tool/src/webapp/WEB-INF/bootstrap.jsp
podcasts/podcasts-app/src/webapp/podcasts/podAdd.jsp
podcasts/podcasts-app/src/webapp/podcasts/podFeedRevise.jsp
podcasts/podcasts-app/src/webapp/podcasts/podMain.jsp
podcasts/podcasts-app/src/webapp/podcasts/podNoResource.jsp
podcasts/podcasts-app/src/webapp/podcasts/podOptions.jsp
podcasts/podcasts-app/src/webapp/podcasts/podRevise.jsp
sections/sections-app/src/webapp/deleteSections.jsp
sections/sections-app/src/webapp/editManagers.jsp
sections/sections-app/src/webapp/editSection.jsp
sections/sections-app/src/webapp/editStudentSections.jsp
sections/sections-app/src/webapp/editStudents.jsp
sections/sections-app/src/webapp/options.jsp
sections/sections-app/src/webapp/overview.jsp
sections/sections-app/src/webapp/roster.jsp
sections/sections-app/src/webapp/studentView.jsp
sitestats/sitestats-tool/src/webapp/html/pages/AdminPage.html
sitestats/sitestats-tool/src/webapp/html/pages/OverviewPage.html
sitestats/sitestats-tool/src/webapp/html/pages/PreferencesPage.html
sitestats/sitestats-tool/src/webapp/html/pages/ReportDataPage.html
sitestats/sitestats-tool/src/webapp/html/pages/ReportsEditPage.html
sitestats/sitestats-tool/src/webapp/html/pages/ReportsPage.html
sitestats/sitestats-tool/src/webapp/html/pages/ServerWidePage.html
sitestats/sitestats-tool/src/webapp/html/pages/UserActivityPage.html

https://jira.sakaiproject.org/browse/SAK-42104
Changed `<h2>` or `<h3>` tags (used as primary page headings) to `<h1>` and added `<div class="page-header">`. Added a header in commons for consistency.

SAK-42104 Switch implemented consistent page headers for Statistics, Section Info, Podcasts, Commons

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java

The 'section membership' header has not got the ignore character ('#') when the instructor exports the gradebook.

SAK-42159: Import error ('Section Membership' field)

---

library/pom.xml
library/src/webapp/editor/elfinder/sakai/elfinder.html

I've requested a deployment in webjars, it may take a while to have this dependency in maven central.

SAK-42197 - Webjars: Upgrade Elfinder from 2.1.48 to 2.1.49

---

library/pom.xml
library/src/morpheus-master/sass/modules/editor/_base.scss
library/src/webapp/js/headscripts.js
portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java

This PR should be broken because 4.12.1 is not populated in maven central yet.

SAK-42205 - Webjars: Upgrade CKEDITOR from 4.11.4 to 4.12.1

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/AccessDeniedPage.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/DeleteItemPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.html
reset-pass/account-validator-tool/src/webapp/component-templates/Messages.html
reset-pass/account-validator-tool/src/webapp/templates/transferMemberships.html
reset-pass/reset-pass/src/webapp/content/templates/form.html
site/admin-perms-tool/src/main/webapp/WEB-INF/jsp/sitePerms.jsp
site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/fragments/common.html
site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/modules.html
site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/search.html

https://jira.sakaiproject.org/browse/SAK-42174
Replaced various banners (info, success, warn, error) in **gradebook**, **site**, **reset-pass**, with new banners created for SWITCH in SAK-41866. Also removed some unnecessary inline styles around/attached to these banners.

SAK-42174 Switch, Gradebookng, Site, Reset-pass: implemented new banner classes

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
samigo/samigo-app/src/webapp/jsf/author/inc/extraCreditSetting.jspf

Getter for lombok automatically creates boolean accessor as isExtraCredit for
the field isExtraCredit instead of getIsExtraCredit or isIsExtraCredit.
When this is referenced in the template as .isExtraCredit it is not found because
neither getIsExtraCredit nor isIsExtraCredit exists. Changing the name of the
field in ItemBean to extraCredit allows Lombok to create the accessor isExtraCredit
which is then found when using .extraCredit in the template.

SAK-42221 SAK-34741 Lombok doesn't like boolean fields starting with is

---

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsManagerTest.java

SiteStats isn’t using the documented default values for display.users.present and presence.events.log, this change has Sitestats match the documentation and the values in the portal.

SAK-42147 Keep default properties inline with docs.

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm

On AssignmentAction initially I was adding a non-electronic check, but finally I'm removing an alert because the message says "The close date of the assignment has passed. You can no longer submit..." but the conditions have nothing to do with the text.
I could handle it differenly if anyone thinks that message is still necessary in there.

SAK-42209 Don't show alert for non-electronic assignments

---

master/pom.xml

The build should be broken because the dependency has not been populated to maven central, I've requested the population.

SAK-42230 - CKEDITOR: Upgrade wordcount plugin from 1.17.4 to 1.17.6

---

master/pom.xml

The build should be broken because the dependency has not been populated to maven central, I've requested the population.

SAK-42231 - CKEDITOR IMAGE2 plugin. Update from 4.11.1 -> 4.12.1

---

library/src/webapp/skin/tool_base.css
msgcntr/messageforums-app/pom.xml
msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java

Commit to allow the deletion of attachments in private messages that were previously saved. 
Minor fix to display file type icon with a proper size.
Minor fix to display the attachment size in a readable way

SAK-42154 - Not able to delete attachment from private message

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

So it seems like the problem here was that the site wasn't available here when the validation failed. I tried to call this with the "true" parameter, however if the site id from this return was actually stored in the state it caused it to save back to the "My Workspace" site and corrupt that site.
So I added a new parameter which will just get the site (from the state) if it exists use the context (which was available) but NOT store it to the state. This got this particular case to proceed through for LTI lookups which needed some type of site.
This seemed like a lower risk fix than changing anything in LTI. I changed the default for 
`protected Site getStateSite(SessionState state) {`
To just call this with a false (even though it previously was true) because calling autoContext false …

SAK-33892 - NPE creating site with LTI tool and extra parameter tool

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm

https://jira.sakaiproject.org/browse/SAK-41980
My jira post has an explanation of the problem (tapping sites menu on mobile changes the page scroll and pulls up the keyboard, which disrupts the mobile experience) and a video demo.
I modified the `<a href="#txtSearch">` link so that the modal would pop up without affecting the scroll of the page and without focusing on the search box (which pulls up a keyboard).

SAK-41980 Portal changed SkipNav link for sites menu

---

library/src/morpheus-master/sass/modules/tool/_table.scss

https://jira.sakaiproject.org/browse/SAK-42319
Cases of the primary action button add using .act adds additional spacing around the buttons. This fix removes the addition spaces. 
See SAK-42319 for some before and after screenshots.

SAK-42319 Fixed button spacing added from .act container in the Sakai table toolbar

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/modules/tool/_menu.scss

https://jira.sakaiproject.org/browse/SAK-42315
The old .instruction class banner appears too often and too prominent. Now that the Sakai banners have been updated in SAK-41866, it is time to make .instruction more subtle.
See SAK-42315 for before and after screenshots.

SAK-42315 Updated .instruction banner class to be visually simpler

---

sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/StrippedStat.java

Adds data to /direct/sitestats/runreport output for the event and Resources file, if applicable.

SAK-42341 Add additional data to sitestats runreport output

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/AnnouncementObserver.java

For non announcement events, this method should not be called

SAK-42348 Announcement event  processing causing ArrayIndexOutOfBoundsException

---

library/src/morpheus-master/sass/modules/_toolmenu.scss

https://jira.sakaiproject.org/browse/SAK-42326
Increased the z-index for the tool name when you hover over the collapsed tool menu, so the tool names can be seen properly and overlap the Gradebook spreadsheet's elements.

SAK-42326 Increased the tool name's z-index to properly overlap Gradebook spreadsheet

---

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm

https://jira.sakaiproject.org/browse/SAK-41976
The tabindex="2" on the Short Description field caused tabbing jump over over the short description field. I've removed the unnecessary tabindex on Short Description, as suggested by Jen in SAK-41976.

SAK-41976 Removed the taborder override from Site Info's Short Description

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm

It seems that there is no longer a showPrevFeedback() method.  Removing the call seems to fix the issue and seems to have no ill side effects.

SAK-42343 Fix previous instructor comments not displaying

---

site-manage/site-manage-tool/tool/pom.xml

https://jira.sakaiproject.org/browse/SAK-42346
When clicking on Site Info > Manage Participants > Printable version, the new tab that opens up displays a stack trace.
This was caused by a library upgrade done in [SAK-41909](https://jira.sakaiproject.org/browse/SAK-41909). Until we upgrade the code in `SiteInfoToolServlet.generatePDF()` to use a newer version of Apache FOP, we need the older version of `xmlgraphics-commons` (v1.5 versus 2.3).

SAK-42346: Site Info > Manage Participants > Printable Version > NoSuchMethodError runtime exception

---

content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm

Override the default with previous behavior: unlimited timeout to upload.

SAK-41204 Dropzone 4.4.0 introduced a default timeout of 30 seconds on uploads.

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties

@jesusmmp mentioned on SAK-37593 that this fixed it. I thought about hard coding this into the validator but some people may not want to override these video files and I also saw they weren't documented so figured I'd add these in there instead of validator.

SAK-37996 & SAK-42387 - Add video files to the default inlines

---

sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/SiteStatsEntityProvider.java

https://jira.sakaiproject.org/browse/SAK-42418
Set the siteID in the report params if it's null so it doesn't try to run the report across all sites.

SAK-42418 Give sitestats /direct/runreport a siteID for system-wide reports

---

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
entitybroker/core-providers/src/test/org/sakaiproject/entitybroker/providers/UserEntityProviderRestrictedViewTest.java
kernel/api/src/main/java/org/sakaiproject/user/api/UserDirectoryService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java

This adds a new user.view.any permission to support the use-case for a webservice account
to be able to look up user information through the /direct/user endpoint, without the account
needing to be admin-equivalent.
This can be achieved at a global level by setting the server configuration property
entity.users.viewall=true, but that applies to all users. The user.view.any permission
can be set for a specific account or group of accounts by creating a special account
type (e.g. "webservice"), creating a user template role (e.g. !user.template.webservice),
and then setting the permission for the .auth role in the template realm.

SAK-42465 Add user.view.any permission to allow global user lookups for webservices

---

edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseManagementService.java
edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/aop/CourseManagementAdministrationAuthzAdvisor.java

Introduces a pseudo permission and reference that can be allowed
in a SecurityAdvisor to enable code to perform CM updates, without
requiring the user session to be set to admin.

SAK-42451 Allow CM services to be used with a SecurityAdvisor

---

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js

This fix which is in master and 19.x is breaking the ease of managing some large gradebooks in 12.x, so it would be ideal to fix this in 12.

SAK-41388: Show all/Hide all in Gradebook breaking

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java

https://jira.sakaiproject.org/browse/SCO-161
Special thanks to @csev for pointers on where and how to accomplish this!
In it's current form, the SCORM Player (specifically the pop-up window generated when launching a module) requires the tool to be embedded in an iFrame. For Sakai 11+ this means that the SCORM tool IDs need to be added to the following sakai.property to ensure that the portal forces the tool into an iFrame, rather than inlining it:
> portal.iframesuppress=:all:sakai.scorm.singlepackage.tool:sakai.scorm.tool
If the SCORM Player tool IDs are not included in the above sakai.property, the result is that the pop-up window generated when launching a module will be wrapped in the portal navigation markup. See the screenshots on the JIRA for an illustration.
The code that decides …

SCO-161: make SCORM Player (contrib) work inline (no iFrames)

---

library/pom.xml
library/src/morpheus-master/sass/modules/editor/_base.scss
library/src/webapp/js/headscripts.js
portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java

This should be broken because the webjar is not in the maven repositories yet.

SAK-42581 WebJars: Upgrade CKEditor from 4.12.1 to 4.13.0

---

master/pom.xml

This should be broken because the webjar is not in the maven repositories yet.

SAK-42582 WebJars: CKEditor image2 plugin upgrade to 4.13.0

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
reset-pass/reset-pass/pom.xml
reset-pass/reset-pass/src/bundle/org/sakaiproject/tool/resetpass/bundle/Messages.properties
reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/UserValidator.java
reset-pass/reset-pass/src/webapp/WEB-INF/applicationContext.xml

https://jira.sakaiproject.org/browse/SAK-42577
SAK-42256 refactored reset-pass so that it would not leak information to the user about whether or not an account exists with the given email address.
However, we didn't notice that as a result of this work there is now a regression in that it doesn't report/validate on a sakai.property to reject attempts for certain account types. Unfortunately, we can't just restore this original functionality because that would be defeating the purpose of hardening the system to not expose undue information to a potential attacker.
To address this regression, we actually need to change the original implementation to be based off a sakai.property like invalidEmailInIdAccountString, which lists domains which are not allowed to use services like New Account, …

SAK-42577: reset-pass > no longer checks invalid account types

---

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookExternalAssessmentService.java
edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java

https://jira.sakaiproject.org/browse/SAK-42613
When working with the `GradebookExternalAssessmentService`, you use the external ID of the gradebook item in question to interact with the service. If the external service does not provide some functionality you require, you need to also utilize the (internal) `GradebookService`.
The `GradebookService` operates primarily on the (internal) ID of the gradebook item in question, rather than the external ID. This is not so problematic if you either know the internal ID already, or if the "name" of the gradebook item corresponds directly with something you already know (for instance in the case of Assignments, the assignment name typically corresponds to the gradebook item name).
However, there could be situations where you only have the external …

SAK-42613: Edu-services > ExternalAssessmentService > add api to retrieve internal id

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java

DeliveryActionListener has a large try/catch block that catches RuntimeException
and then adds an error the error log.
If an exception is caught for an assessment preview, the real error is masked
because the T&Q event logging code attempts to get an assessmentGradingId
which is null (and really there's nothing meaningful to log here since it's a
preview and the event log doesn't log previews).
So we should check for that and throw the real exception earlier before
attempting to update the event log.

SAK-42630 Avoid a possible NPE when catching errors during assessment preview

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm

Added display:none to prevent empty error banner from displaying while uploading files, similar to https://jira.sakaiproject.org/browse/SAK-41516 (https://github.com/sakaiproject/sakai/pull/6706). 
Should fix bugs https://jira.sakaiproject.org/browse/SAK-42248 and https://jira.sakaiproject.org/browse/SAK-42121.

SAK-42248 Fix empty error banner displaying when uploading/importing files

---

lessonbuilder/tool/src/webapp/templates/BltiPicker.html
library/src/webapp/editor/ckextraplugins/contentitem/plugin.js

This doesn't entirely fix the issue mentioned on SAK-42376 as it fixes the content item picker tabbing into the app store, not Lessons. We can either add to this or create a second ticket.

SAK-42376 - Content Picker accessibility - cannot tab into app store

---

lessonbuilder/tool/src/webapp/templates/ShowPage.html
library/pom.xml

Verified in my local environment.

SAK-42653 WebJars: Upgrade fullcalendar from 4.2.0 to 4.3.1 (Oct-2019)

---

library/pom.xml
library/src/webapp/editor/elfinder/sakai/js/src/editors.js

Verified in my local environment.

SAK-42652 - WebJars: Upgrade codemirror from 5.48.2 to 5.49.0 (Oct-2019)

---

master/pom.xml
textarea/elfinder-sakai/pom.xml
textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/scorm/ScormFsItem.java
textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/scorm/ScormSiteVolumeFactory.java
textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml

https://jira.sakaiproject.org/browse/SCO-166
This is also dependant on https://github.com/sakaicontrib/SCORM.2004.3ED.RTE/pull/45
*I'm submitting this as a draft PR because I have major questions below...*
Since the switch to `elfinder`, this is what's necessary to hook up entities to the picker in CKEditor. Although the UI looks much nicer than before, in terms of code implementation it's actually much worse compared to what we had before.
In the old system all you had to do was code your `EntityProvider` and add a tiny string in a message bundle in core Sakai code. Your `EntityProvider` was completely isolated in your tool (even a contrib tool!), and if you didn't deploy that tool to your Tomcat nothing bad would happen. The picker would continue to work with the `EntityProvider`s that …

SCO-166: fix entity linking for SCORM Player

---

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemTypeExtractionStrategy.java

(Old ugly parts of Samigo, open for discussion)
If there's no exact match, itemIntrospectItemType (xml structure) is more reliable than guesses based on searching words on the title.

SAK-42628 T&Qs : wrong t/f question on pool import

---

basiclti/basiclti-portlet/src/webapp/WEB-INF/sakai/IMSBLTIPortlet.xml
site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

Add a tool configuration option that prevents a tool from being duplicated to a new site
When a site is duplicated, tools with this configuration:
<configuration name="allowToolDuplicate" value="false" />
will not be copied to the duplicated site.

SAK-42688 Tool configuration option for duplication

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

https://jira.sakaiproject.org/browse/SAK-42693
Oracle returns BigDecimal instead of Integer for the tool order value, and a ClassCastException
is thrown. This is similar to what happens with the LTI tool id, and
this PR handles it in a similar way.

SAK-42693: classcastexception for LTI toolorder, bigdecimal on oracle

---

calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/Day.java
library/src/morpheus-master/sass/modules/tool/calendar/_calendar.scss
library/src/morpheus-master/sass/modules/tool/calendar/_calendarSynoptic.scss

https://jira.sakaiproject.org/browse/SAK-42695
Fixed some visual and accessibility issues with the recent Calendar UI redesign from SAK-42430, including:
- removed extra side border from the today cell with events in the synoptic calendar
- removed borders from cells of the next and previous months in the synoptic calendar and mini-month view to differentiate from the current month's days
- fixed a few border issues in Week and Day views that caused extra lines to appear or fill in missing lines
- fixed focus states for events in Week and Day views so they appear properly, so all events can be focused on

SAK-42695 Calendar: fixed visual issues with recent UI redesign

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooterExtras.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageBody.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm

https://jira.sakaiproject.org/browse/SAK-42676
I've changed the navigational headings (the headers that the skipnav links go to) from h1 tags to h2 tags, per the recommendations from consultation with the Sakai Accessibility Working Group as described in this article:
https://www.w3.org/WAI/tutorials/page-structure/headings/#main-heading-after-navigation

SAK-42676 Change navigational headings to h2 for page accessibility

---

library/pom.xml
library/src/webapp/js/headscripts.js

This has not been tested yet and should be broken because the artifact is not in the maven repos yet.

SAK-42692 - WebJars: Upgrade mathjs from 6.0.3 to 6.2.3

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java

This is a small improvement over SAK-42680 PR #7485 which eliminated the main regression. 
Move the userId check a little higher, and adds the proper userId when calling the single param method.

SAK-42702 Assignments canSubmit check current user when user is blank

---

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentEventObserver.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
assignment/impl/src/webapp/WEB-INF/components.xml

If a dummy submission doesn't exist then grading observer simply skipped
grading. This prooved unintuituve so a summy submission will be created
if one doesn't exist before saving the grade

SAK-42156 Assignments grading via gradebook doesn't save grades

---

webcomponents/tool/pom.xml

https://jira.sakaiproject.org/browse/SAK-42738
The webcomponents project runs some NPM goals. The "install" goal specifically will modify the following files if the Maven build fails:
* webcomponents/tool/src/main/frontend/package-lock.json
* webcomponents/tool/src/main/frontend/package.json
This can be a problem if you're not aware of the issue and constantly checking if these files were modified after a failed build. The danger is that these unintended modifications can leak into commits if you're not extra careful.
According to some articles online, NPM 5.7.0 introduced the "ci" command as an    "additional way to achieve fast and reproducible builds...", and changing from "install" to "ci" resolves this issue.
References:
* https://stackoverflow.com/questions/45022048/why-does-npm-inst …

SAK-42738: switch from npm install to npm ci

---

library/src/morpheus-master/sass/modules/navigation/_base.scss

https://jira.sakaiproject.org/browse/SAK-42793
When tool names are wider than site titles (e.g. Home), make sure the tool names have enough width in the tool menu by making the menu wide enough for them.

SAK-42793 Fixed site tool names overflowing top submenu

---

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java

Cleaning up code too: "rationale" is not used on matrix survey and "response comment" is not used on any other question.

SAK-42531 T&Qs fix export results for matrix of choices

---

library/src/morpheus-master/sass/modules/navigation/_base.scss

Fixed line-height for longer usernames in the Account Menu.
See https://jira.sakaiproject.org/browse/SAK-42819 for before and after screenshots.

SAK-42819 Fixed the line-height spacing of the username in the Account Menu

---

msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml

Deleted "cascade=all" in the MFR_PVT_MSG_USR_T table, to solve this problem, as we have seen this is the common cause of this type of problems (https://forum.hibernate.org/viewtopic.php?f=1&t=1000252&sid=04fa3e5bfe7f10c0d52a9f6c508de3e4). This "cascade" does not do anything in the table, since there is no FK to other tables, although it is related to tables MFR_MESSAGE_T and CMN_TYPE_T (https://confluence.sakaiproject.org/display/SPANISH/Limpieza+de+la+base+de+datos), currently if we do some update/delete in any of them the others are not affected, reason why the cascade has been eliminated without problems.

SAK-42837 - Messages - Error on log

---

portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/GradeAssignmentBullhornHandler.java

If user doesn't have permissions for this assignment, the url is an empty string which causes an oracle error on our environment since it's interpreted as NULL (the url column having a not null constraint)

SAK-42721: check that assignment url is not empty string

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java

https://jira.sakaiproject.org/browse/SAK-42914
Noticed that the static variable names were swapped on my PR for the original stars contribution (#7441), which prevented the sakai.properties from working properly. I've switched them back and retested the various combinations.

SAK-42914 Fixed the static variables for the starred sites top bar

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm

https://jira.sakaiproject.org/browse/SAK-42769
Changed the ARIA labels to titles to provide more descriptive cues about the stars feature added in #7441.

SAK-42769 Gave the top bar stars hover titles

---

webcomponents/tool/src/main/frontend/sakai-group-picker.js

https://jira.sakaiproject.org/browse/SAK-42925

SAK-42925 Don't render group picker unless i18n is initialised.

---

rubrics/tool/src/main/java/org/sakaiproject/rubrics/security/CustomMethodSecurityExpressionHandler.java
rubrics/tool/src/main/java/org/sakaiproject/rubrics/security/CustomMethodSecurityExpressionRoot.java

https://jira.sakaiproject.org/browse/SAK-42951
Added some proper security. You can only import rubrics from sites where
you are a rubrics.editor, or if you authored the rubric in question.

SAK-42951 Allow site import of other author's rubrics

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/loginImage-snippet.vm

Looks like this was changed from 999 to 0 in https://jira.sakaiproject.org/browse/SAK-40135 but that still makes it a div that has no interaction, just making this -1 to skip over it and onto the actual link.

SAK-43016 - Cannot logout using only KB

---

announcement/announcement-tool/tool/pom.xml
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapper.java
announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapperComparator.java
announcement/announcement-tool/tool/src/test/org/sakaiproject/announcement/tool/AnnouncementWrapperTest.java

This is a first step toward cleaning up AnnouncementAction. It extracts
the AnnouncementWrapper nested class, tidies up the handling of a couple
of entangled constants, removes a few references to TimeService, and
adds a couple of minimal tests to get things moving.

SAK-43102 - Extract AnnouncementWrapper

---

basiclti/basiclti-impl/pom.xml
basiclti/tsugi-util/src/test/org/tsugi/oauth2/OAUTH2ObjectTest.java
cloud-storage/googledrive/impl/pom.xml
cloud-storage/onedrive/impl/pom.xml
gradebookng/tool/pom.xml
help/help-tool/pom.xml
jobscheduler/scheduler-component-shared/pom.xml
jsf2/jsf2-widgets-sun/pom.xml
jsf2/jsf2-widgets/pom.xml
master/pom.xml
msgcntr/messageforums-app/pom.xml
polls/impl/pom.xml
portal/portal-chat/tool/pom.xml
portal/portal-util/util/pom.xml
reset-pass/reset-pass/pom.xml
rwiki/rwiki-impl/rwiki-shared-serializer/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/XHTMLSerializer2.java
search/elasticsearch/api/pom.xml
site-manage/site-manage-impl/impl/pom.xml
syllabus/syllabus-app/pom.xml
tags/tags-impl/impl/pom.xml
tags/tags-impl/impl/src/java/org/sakaiproject/tags/impl/job/TagSynchronizer.java

There were a few modules that would compile with Maven directly, but
throw errors when imported as Eclipse projects. The main two issues were
in the Java EE API and a Jackson coordinate change.
There are two minor code changes that I expect would have broken Maven
builds, but apparently did not. One was a test class/package mismatch
in LTI and the other was some missing method implementations for an XML
class in rwiki.

SAK-43092 - Fix up POMs for Eclipse compatibility

---

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java

This reverts commit 4155a51528cfee9238c91a094372f518084d6ac5.
Based on comments from clients, I believe SAK-41810 was a mistake. I believe there are valid use cases for Gradebook category worth 0%

SAK-43053 Revert "SAK-41810: Error with Extra point if there is a category 0% (#7109)"

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml

This PR addresses an issue where copying a course did not result in LTI content being updated for the new course and using old, and incorrect, links. The PR consists of two commits, one is the work from David Bauer at University of Dayton, and the second is Warpwire's adjustment to handle LTI content in text fields.

SAK-42749 Partial fix for copied course content

---

feedback/pom.xml
kernel/kernel-tim/pom.xml
master/pom.xml
pack/pom.xml

[![mitm_build](https://user-images.githubusercontent.com/1323708/59226671-90645200-8ba1-11e9-8ab3-39292bef99e9.jpeg)](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/@jonathan.leitschuh/want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-1fc329d898fb?source=friends_link&sk=3c99970c55a899ad9ef41f126efcde0e)
- [Update: Want to take over the Java ecosystem? All you need is a MITM!](https://medium.com/bugbountywriteup/update-want-to-take-over-the-java-ecosystem-all-you-need-is-a-mitm-d069d253fe23?source=friends_link&sk=8c8e52a7d57b98d0b7e541665688b454)
---
This is a security fix for …

[SECURITY] Use HTTPS to resolve dependencies in Maven Build

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfoConfirm.vm

Strip calls (to dismiss whitespaces from the start and end of the strings) are required.

SAK-43184 SiteInfo always highlights description on edit

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-43223
The biggest complaint from students that we get at Western is that instructors underutilize the calendar. The option to "Add due date to calendar" is currently unchecked by default. It would be much more helpful for students if we flip the default.
Implement a sakai.property to specify the default for this checkbox:
asn.due.date.to.calendar.default=true (default)

SAK-43223 - New Assignments - Add due date to Calendar should be checked by default

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java

There were 3 suggestions I'd made on the jira. This fix is implementing #3. It will always try to favorite at least portal.default.tabs number of sites the first time someone logs in.
1) Have a another property to always favorite new sites on the first time for a user, no matter if it's the first time logging in ever or the first time since the upgrade when this feature existed.
2) Set some kind of preference on the user when they are created to say they're first time and haven't seen favorites, then when they get around to this favorites logic remove that. Then when it gets around to them remove that.
3) Previous suggestions by Austin (and possibly others?) to have a limit (probably set by property) for the number of sites auto favorite can add on the first time. (Maybe a reasonable …

SAK-41106 - Sites don't appear as auto-favorited before first time login

---

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm

When the preview is shown to students, if the grade hasn't been released yet we need to use a fake submission id.

SAK-43206 Assignments : unfilled rubric preview for unreleased grade

---

site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html

Quick fix, although this tool will be replaced in the soon future (SAK-40672)

SAK-43224 : Empty title alert not being shown on group creation

---

library/src/morpheus-master/sass/modules/tool/_base.scss
sitestats/sitestats-tool/src/webapp/html/pages/UserActivityPage.html

https://jira.sakaiproject.org/browse/SAK-43251
On the User Activity page of the Statistics tool, the page header was duplicated, which caused two lines below the heading. 
I removed the duplicate div and the extra margin. 
See SAK-43251 for before and after screenshots.

SAK-43251 Fixed display issues with the User Activity page header

---

content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm

https://jira.sakaiproject.org/browse/SAK-43233
There is a sakai.property to force selection of a copyright status (`copyright.requireChoice`).  There is also a new sakai.property (introduced in Sakai 12) to display the copyright selection component for the "Web Links (URLs)" resource type (`content.url.rightsdialog`).
If both properties are set to `true`, the copyright selection should be enforced when creating new Web Links; but it is not. If you do not select a copyright status (found within the "Add details for this item" panel), and save it should prompt you to select a copyright status, but it does not.
When editing a Web Link (with both properties set to `true`), the copyright enforcement is enforced.
Enforce copyright status selection on creation of Web Links when both properties …

SAK-43233: Resources > enforce copyright selection for URLs on create if required

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java

https://jira.sakaiproject.org/browse/SAK-43019
Fixed an issue: If you mod one student's rubric, then add an attachment
to another students result, the first student's rubric is lost. This
fixes that.

SAK-43019 Fixed questions view rubric behaviour

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/AnnouncementObserver.java
message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java

https://jira.sakaiproject.org/browse/SAK-43381
Creating, editing and deleting Announcements via Admin Workspace (MOTD) appears to not work for a period of time until the cache is evicted.
This is caused by not building the channel ID for the MOTD (admin workspace) properly in `AnnouncementObserver`, so it effectively clears a non-existent cache in this context.

SAK-43381: admin workspace > announcements > fix cache refresh

---

profile2/tool/src/webapp/css/profile2.css

Font-awesome's own icon class introduced some changes that resulted in a compression of all the texts next to icons in the Profile tool. Even if it's not ideal, the best solution seems to be overriding the 'display' behavior of the component, already on its own css file. The tool adds classes to components from Java too, so it's hard to trace the number of cases, but this should solve all of them.

SAK-43435 Profile2: fix texts next to icons

---

citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
content/content-tool/tool/src/java/org/sakaiproject/content/tool/SiteEmailNotificationDragAndDrop.java
content/content-types/src/java/org/sakaiproject/content/types/FileUploadType.java
content/content-types/src/java/org/sakaiproject/content/types/FolderType.java
content/content-types/src/java/org/sakaiproject/content/types/HtmlDocumentType.java
content/content-types/src/java/org/sakaiproject/content/types/MakeSitePageAction.java
content/content-types/src/java/org/sakaiproject/content/types/TextDocumentType.java
content/content-types/src/java/org/sakaiproject/content/types/UrlResourceType.java
kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BasicContentTypeImageService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DropboxNotification.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/SiteEmailNotificationContent.java
kernel/kernel-impl/src/main/java/org/sakaiproject/content/user/prefs/ContentUserNotificationPreferencesRegistrationImpl.java
kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BaseDigestService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
kernel/kernel-impl/src/main/java/org/sakaiproject/tool/impl/ToolResourceFactory.java
kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/FormattedTextImpl.java
kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/ResourceTest.java
kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java
kernel/kernel-util/src/main/java/org/sakaiproject/util/Resource.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java
webservices/cxf/src/java/org/sakaiproject/webservices/SakaiI18n.java

In this change Resource class was instatiated everywhere with no
real benefit. This change moves to a static implementation.

SAK-43462 Kernel Resource should be less verbose

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-42904

SAK-42904 Missing documentation for property for disabling duplicate email addresses for accounts

---

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
portal/portal-util/util/src/java/org/sakaiproject/portal/util/PortalUtils.java

https://jira.sakaiproject.org/browse/SAK-43259
Providing a working solution for the bug, to get the conversation started about how to manage it. This problem affects not only the case described on the jira's title, but also every url access to tools using moment, and of course the same can happen with other libraries. Adding library versions on more places is far from ideal, but as long as Sakai supports this kind of tool access we have to solve the bugs. Even if that's redesigned we can provide a quick fix first. We can discuss on this PR about adding a headscripts Java component (a similar feature to the headscripts js thing on library). DirecttoolHandler or ToolHandler might be other places where to add it, although the former doesn't cover every possible call and the latter is …

SAK-43259 Lessons: Error when printing and there's a calendar

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java

https://jira.sakaiproject.org/browse/SAK-43519?filter=16773
We should only show rubrics from external tools (not LTI, we're talking
assignments, Samigo, etc) when the tool has released the grade.
Internally maintained gb items can show the rubric button all the time
as it will allow preview by the student.

SAK-43519 Only show external tool rubric when grade released

---

edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SampleDataLoader.java
providers/component/src/webapp/WEB-INF/components-demo.xml

https://jira.sakaiproject.org/browse/SAK-43539
The demo data created when bringing up an instance with `-Dsakai.demo=true` is of great benefit for a multitude of purposes, but most important of all is testing and QA. This data set is used on the nightly servers, where all community testing is performed.
The current demo data creates multiple offerings for multiple terms, and multiple sections within each offering. However, each section is currently limited to 30 students. While this provides a satisfactory test bed for most things, performance and scalability issues are difficult to identify when using small data sets.
To better assist with the discovery and reporting of performance and scalability issues, it would be beneficial to have a few of the provided demo sections contain much …

SAK-43539: add some large sections to demo data

---

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-43561
`default.sakai.properties` is missing documentation of the property added in [SAK-41163](https://jira.sakaiproject.org/browse/SAK-41163).

SAK-43561: documentation for portal.autofavoritableUserTypes

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.html
gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.java
gradebookng/tool/src/webapp/scripts/gradebook-bulk-edit.js

Add additional functionality to the bulk edit modal that allows for
multiple items to be deleted. This feature also fixes the toggle all
for release and include columns.

SAK-43061 Add delete column to bulk edit modal in gbng

---

library/src/morpheus-master/sass/_defaults.scss

Looks like https://github.com/sakaiproject/sakai/pull/8055 accidentally reverted the primary buttons back to uppercase.

SAK-43177 Library remove uppercase default from primary buttons

---

rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemoveAssessmentListener.java

as we now have restoration capabilities in "Trash" tab
This makes Samigo behave like Assignments. Delete a published assessment is no problem as restoration (with submissions) is simple.

SAK-34190 allow deleting a published assessment with submissions 

---

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DefaultFileSystemHandler.java

Switch from Spring FileCopyUtils which returns an int to
commons-io IOUtils.copyLarge which returns long for file length,
to avoid getting an incorrect content length when uploading files
larger than 2G.

SAK-43666 Files over 2G have incorrect file size

---

gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css

I couldn't find any good icons as part of the font this was using so I just picked the Unicode "Scales". At least it's visually different.

SAK-43656 - Gradebook / weighted and extra credit categories use the same icon

---

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
assignment/impl/src/java/org/sakaiproject/assignment/impl/reminder/AssignmentDueReminderServiceImpl.java

Allow add assignment should be checked for each member of the site to
determine if an email reminder should be sent instead of checking the
permission of the current user. Fixes regression in SAK-42667

SAK-43674 Assignment reminder emails will never send

---

kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/UserAuthnComponent.java
login/login-api/api/src/java/org/sakaiproject/login/api/Login.java

It seems this was broken on
https://github.com/sakaiproject/sakai/commit/dd5890f173f61e0ad629f58010bfc4e8e8d8a39d
A more ambitious (future) fix would consist of moving all the messages to a common place where both sides can check them.

SAK-43605 Show message to disabled users on login page

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/validator/FinQuestionValidator.java

Adding a new error message variable in deliveryMessage.properties: When defining a range of values, the value preceding the pipe "|" must be smaller than the value after the pipe!
Assign this new error message to the case when users type in a number before the pipeline "|" greater than that after the pipeline.

SAK-43514: Adding proper error message when using pipeline "|" in numeric response questions

---

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js

https://jira.sakaiproject.org/browse/SAK-43798
If there are empty score cells in the gradebook tool, sorting by course grade will not work correctly. The screenshot shows that sometimes the empty cells whose content are "-" are sorted on the above when sorting by ascending or descending order according to course grade (see screenshot).

SAK-43798: Sorting by course grade doesn't work correctly if there are empty score cells

---

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java

https://jira.sakaiproject.org/browse/SAK-43795
Given the gradebook settings include point grades, display released Gradebook items to students, display assignment statistics to students, display course grade statistics, and no categories: in 20.x and 21.x
When an instructor enters a valid score into a score cell and then deletes the contents in the score cell by clicking the cell once and press "delete" on the keyboard, the score cell becomes empty, but the course grade will be updated as if the score became 0. (See the first screenshot)
This issue only appears in 20.x and 21.x. In 19.x nightly server, if the user does the above actions, the score cell becomes empty and the course grade will be updated as if the score was not set at all, i.e., as if it were "-". (See the second …

SAK-43795: Gradebook: Deleting a score cell will automatically set the cell to be zero

---

access/access-impl/impl/src/java/org/sakaiproject/access/tool/AccessServlet.java

https://jira.sakaiproject.org/browse/SAK-43849
In Resources or Dropbox, selecting "what's this" next to the copyright alert section displays invalid text.
#7839 just missed a few places where `formattedText` needed to be put into the Velocity template's `context`.

SAK-43849: copyright alert demo displays velocity syntax

---

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js

https://jira.sakaiproject.org/browse/SAK-43668
When the instructor uses the grader to grade and allows a resubmission for one student, then moving to grade the next student, the resubmission selection is kept. This is not how the "old" grading interface worked for assignments and I think it will cause errors and confusion for the instructor. In the "old" grading interface, the instructor had to set allow resubmission for each student individually if the option was not already set when creating the assignment.
JIRA Triage agreed this should behave the same as the "old" grading UI.

SAK-43668: Grader WC > allow resubmission checkbox is too sticky

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java

The fake itemgrading should be deleted when a real itemgrading coming from the user is present.
In those type of questions it was not controled producing duplicated itemgradings for the same question that produces grading problems for CQ.

SAK-43598 remove fake itemgrading created in Linear Access to assessment

---

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-preview.js
webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-readonly.js
webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js

This change fixes passing the property "weighted" to rubrics previews/read-only.
Although I don't understand why stopped working after the code style changes requested at the PR.
My main doubt is whats the difference between "." and "?"
"?" works at 
"webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js":142
but it doesn't work at
"webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js":131
Using dot works with my cases.
@adrianfish Can you help me with this?

SAK-43826: Rubrics - Support weighted criterions  (fix previews)

---

library/src/morpheus-master/sass/_defaults.scss
library/src/morpheus-master/sass/modules/_main.scss

as it was causing issues with breakpoints in Sakai 20+ for desktops 1050px+

SAK-43950 no need for col2of2 explicit min-width 

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java

This same issue is also happening in ShowItemProducer

SAK-41806 Lessons is not clearing the return url from session part 2

---

entitybroker/impl/src/java/org/sakaiproject/entitybroker/impl/devhelper/DeveloperHelperServiceImpl.java

There is no need to get the site here, as the transformation from a site id (context) to a site reference is a simple string manipulation for which SiteService already has a method.
Calling getSite() has performance implications as it returns a copy of the site from the site cache (usually).

SAK-44057 Improve entitybroker DHS getCurrentLocationReference

---

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java

The smoker test clicks a lot of links in Sakai , often in someone what random orders.   And with tools that use state a lot, these paths can lead to Null Pointer Errors (NPE).   It is unlikely that these are click paths our users will travel down.  Sometimes the UI even recovers from the NPE and puts something up.
But we might as well fix these rare NPEs so future NPEs (i.e. perhaps a regression) jump out while running a future smoker test.

SAK-44086 - Fix Site Manage NPE(s) Detected by the smoker test

---

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java

The smoker test clicks a lot of links in Sakai , often in someone what random orders.   And with tools that use state a lot, these paths can lead to Null Pointer Errors (NPE).   It is unlikely that these are click paths our users will travel down.  Sometimes the UI even recovers from the NPE and puts something up.
But we might as well fix these rare NPEs so future NPEs (i.e. perhaps a regression) jump out while running a future smoker test.

SAK-44085 Assignments NPE when time params are missing

---

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java

It looks like the `startScheduler `check only occurred when `start()` was running. This was from  `org.springframework.context.Lifecycle`. I added this check to also early not run the the `init()`.
I added a NPE check on the problematic line with a warning as `detail ` has potential to still be null in some conditions otherwise.

SAK-40369 - Intermittent startup failure

---

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooterExtras.vm

This changes the running of updatePresence so that it is run when it exists i.e. after morpheus.scripts.min.js is loaded.
Now the initial code just waits 5 seconds (default) and then tries running the function - this checks in 5 seconds, if it doesn't exist it tries again in another 5 seconds and so forth.

SAK-41140:  Change initial run of updatePresence to be delayed if function doesn't exist yet.

---

library/src/morpheus-master/js/src/sakai.morpheus.update.presence.js

1. The setTimeout handle is not cleared properly and might cause a cascade effect if multiple updatePresence function calls are made.
2. Presence sends out a lot of HTTP requests for each tab open in a browser - this creates unnecessary load on the server.
A more accurate portrayal of activity is when a user is active on the tab that is open in the browser - this reduces the number of presence requests that are sent to the server.

SAK-44071: Update Presence correctly by clearing timer and update active tabs

---

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java

Fixes a regression where reports with WHO_NONE generate a query with userId = '' which doesn't match any users.

SAK-43712 Fix regression in members who have not visited site

---

.gitignore
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java

https://jira.sakaiproject.org/browse/SAK-34512
Adding correct or incorrect feedback text that exceeds 4000 characters causes an exception to be thrown. The result is the loss of user data for the question, and not just the feedback text which exceeded the limit: the question text and answer are also lost, even if you saved them separately.
This affects both Oracle and MySQL.

SAK-34512: Samigo > user data loss when feedback text exceeds 4000 characters

---

library/src/webapp-filtered/editor/ckeditor.launch.js
samigo/samigo-app/src/java/org/sakaiproject/jsf/renderer/RichTextEditArea.java
samigo/samigo-app/src/java/org/sakaiproject/jsf/tag/RichTextEditArea.java
samigo/samigo-app/src/webapp/WEB-INF/samigo.tld
samigo/samigo-app/src/webapp/js/samigo-global.js
samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswer.jsp
samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswerLink.jsp

* I added a new attribute to Samigo to specify the maxCharCount this is passed directly into CKEditor.
* To make changes to CKEditor config in the future a little more flexible I added a method to merge the configs passed in to the default. Previously only a few settings were overridden explicitly. 
I was thinking of just targeting this specific one but I can think of some other ways we might want to make use of this.
* I modified one of the Samigo files to Lombok since it needed it
Any comments appreciated! Thanks!

SAK-39932 - Essay questions display two different maximum character limits

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
lessonbuilder/tool/src/resources/messages.properties
lessonbuilder/tool/src/webapp/css/Simplepagetool.css
lessonbuilder/tool/src/webapp/css/checklist.css
lessonbuilder/tool/src/webapp/js/checklist.js
lessonbuilder/tool/src/webapp/js/show-page.js
lessonbuilder/tool/src/webapp/templates/BltiPicker.html
lessonbuilder/tool/src/webapp/templates/Checklist.html
lessonbuilder/tool/src/webapp/templates/ShowPage.html

These improvements and bug fixes include:
- toggling a css class on section headers based on if the section is open or closed
- Fixing a typo in the polls markup causing styling inconsistencies
- Lowering all of the z-index values for lessons dialogs
- Fixing styling inconsistencies in Checklist feature
- Adding tabindex to the Learning Apps iframe
- Linked checklist items are broken when imported into a new site, but are not
indicated as broken to the user
- Change checklist item duplication to use JSON instead of String manipulation
- Fix date picker when no date is set
- Fix issue with checklist item indexes
- Fix auto select multiple choice on add question load
- Keep subpage group release info on duplication / import
- Fix group releasing LTI items in Lessons

SAK-44151 General small improvements and fixes for Lessons

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
lessonbuilder/tool/src/webapp/js/show-page.js
lessonbuilder/tool/src/webapp/templates/ShowPage.html

https://jira.sakaiproject.org/browse/SAK-43672
When using Lesson's "Questions", editing a saved question populates the text from the rendered HTML rather than the raw saved value. This presents problems with using LaTeX, as the raw text and the rendered text are completely different after MathJax parses it. The result is that it saves correctly the first time, but editing the question populates the rendered text rather than original. People don't notice this and are confused when the save the edit and it breaks the LaTeX that worked initially.
Solution is to dump the raw text to a hidden input and use that to populate the edit rather than the rendered text.

SAK-43672: lessons > use raw question text for edit rather than rendered text

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java

https://jira.sakaiproject.org/browse/SAK-34322
You can change a published quiz's settings to save grades to the Gradebook even when there is an existing gradebook item of the same title. When students submit to this quiz it fails to push the grade to the gradebook due to the duplication.

SAK-34322: samigo > block editing published quiz to send grades to existing gradebook item

---

samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp
samigo/samigo-app/src/webapp/jsf/questionpool/selectQuestionType.jsp

https://jira.sakaiproject.org/browse/SAK-42874
Previously this was suposed to be managed by two different selectOneMenu within the ItemHeadings file, but their selectItems are equal. I also believe the rendered options were a bit strange, I'd say the only important check for this is itemauthor.target == 'questionpool' but I'd like someone else to confirm that, if possible.

SAK-42874 T&Qs remove 'copy from pool' option inside pool menu

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorPartListener.java

https://jira.sakaiproject.org/browse/SAK-42911
The first time you create a question its part has the title "Default", but whenever you create or edit an assesment and you add a part its title label is empty and you need to add one to be able to create the part otherwise you will see the message "Part title cannot be empty".
If you add by default the title "Default" when you are creating the part, you won't need to add one and those titles will not be visible to assessment takers anyway. It makes sense that this works this way.

SAK-42911 Change part titles by default when one is created

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeValidator.java

https://jira.sakaiproject.org/browse/SAK-43610
Adds validation and error messaging when time extension time limit is greater than availability window.
Took the opportunity to reduce code duplication between `ConfirmPublishAssessmentListener`, `SavePublishedSettingsListener`, `AssessmentSettingsBean`, and `PublishedAssessmentSettingsBean` by introducing a new delegate class, `ExtendedTimeValidator`.
Most of the code in this new delegate is just moved from the other classes. I'll denote inline where the new logic lives.

SAK-43610: samigo > time exceptions > add validation to time limit

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeValidator.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/TimeLimitValidator.java

https://jira.sakaiproject.org/browse/SAK-44250
Similar to SAK-43610, there is no validation around the availability window when specifying a time limit for the main quiz settings.

SAK-44250: samigo > settings > add time limit validation

---

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
samigo/samigo-app/src/webapp/css/tool_sam.css
samigo/samigo-app/src/webapp/js/authoring.js
samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf
samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf

https://jira.sakaiproject.org/browse/SAK-42794
Original PR: #7699 
Refactored to use mutually exclusive radio buttons rather than checkboxes, as requested by Sakai UX group. See new screenshots on the JIRA ticket (radios_*.png)
Please use "Rebase and Merge" to preserve authorship of HEC developers' original work.

SAK-42794: implement radio buttons for extended time options

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java

https://jira.sakaiproject.org/browse/SAK-44116
Removing the code in this else block resolves the issue in the ticket. The issue is that when the due date has passed and late submissions are not allowed, this else block runs and the "retractDate == null" test passes and allows the student access if they have been granted a retake.
Since late submissions are not allowed in this scenario, the value of retract date is meaningless and should not be checked anyway. If an instructor wants to allow retakes to be submitted late, they can use availability exceptions for this.

SAK-44116: T&Q: Retake does not respect due date

---

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
samigo/samigo-app/src/webapp/jsf/evaluation/questionScoreItemAttachment.jsp
samigo/samigo-app/src/webapp/jsf/shared/itemAttachmentList.jsp

https://jira.sakaiproject.org/browse/SAK-43730
Note to reviewers:
The attachments that are rendered when students take a quiz are in /jsf/delivery/item/attachment.jsp.
The attachments that are rendered when viewing the Questions tab when grading is jsf/evaluation/questionScoreItemAttachment.jsp, (included from the questionScore.jsp page).
The former loads attachments from an ItemContentsBean, the latter loads attachments from a PublishedItemData instance. The attachments lists consist of the exact same types, and are rendered in the exact same manor, but the EL expressions pointing to these attachments lists differ.
I wanted to eliminate code duplication, so I used tomahawk's 'aliasBean' tags so that both contexts can use the same attachment rendering code. Then I moved the attachment …

SAK-43730 - T&Q: If instructor grades by question, instructor attachments are missing

---

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java

https://jira.sakaiproject.org/browse/SAK-44245
Dave's change effectively hid BaseMessage's m_formattedText field from
the spring wiring in announcements. I'm glad it did, or we'd have had
multiple ways of accessing formatted text in one object graph.

SAK-44245 Don't mask BaseMessage's m_formattedText property.

---

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java

https://jira.sakaiproject.org/browse/SAK-44304
SAK-34512 only addressed the "correct" and "incorrect" feedback fields. "General", and "selection level" feedback needs the same treatment.

SAK-44304 samigo > user data loss when general or selection level feedback exceeds 4000 characters

---

library/src/morpheus-master/sass/_defaults.scss

Still darker than the original green in 20.0 but reverting from the purple which may abruptly disorient users in a .x update.
Related to 
https://jira.sakaiproject.org/browse/SAK-42942

SAK-43179 20.x/Library revert become user banner to darker green to avoid documentation issues

---

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java

https://jira.sakaiproject.org/browse/SAK-42472
This PR changes how short answer questions are marked as correct or incorrect. If the question has no associated correct answers, anything the student submits is now considered to be correct, unless the submission is empty.

SAK-42472: Lessons: Short Answer Question displays red X after student submission

---

site-manage/datemanager/api/src/java/org/sakaiproject/datemanager/api/model/DateManagerUpdate.java
site-manage/datemanager/impl/src/bundle/datemanager.properties
site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
site-manage/datemanager/tool/src/main/resources/Messages.properties
site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/tool_fragment.html

https://jira.sakaiproject.org/browse/SAK-43958
"1) If an instructor uses feedback after a set date, they would still need to go into the test settings to update the feedback date(s), which decreases the usefulness of Date Manager.
2) If an instructor neglects to update the feedback date and those are set in the past, the feedback works as if Immediate Feedback was selected, potentially allowing students to change their answers mid-test. If an instructor doesn't realize that the Feedback Date would have this effect if set before the due date, they may think that setting the due & accept until dates through Date Manager is sufficient."

SAK-43958: date manager > samigo > include feedback on and until dates

---

master/pom.xml

Only updated spring version, I didn't test that this actually fixes the issue but the fix is included.
I didn't update master/21 as that would need a spring 5.x update and isn't related to this issue.

SAK-44072 - Request threads blocked on spring-beans synchronization

---

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties

https://jira.sakaiproject.org/browse/SAK-42923
Some folks like the new behaviour (create groups if they don't exist, use groups if they do exist in destination site), some folks prefer the legacy behaviour (everything imports as released to site).
This PR provides a new sakai.property (`assignment.create.groups.on.import`) to control which behaviour takes place. Default OOTB is the new behaviour (create/use groups in destination site).

SAK-42923 assignments > import > new sakai.property to control group creation

---

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsTypeManager.java
msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsTypeManagerImpl.java
msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java

https://jira.sakaiproject.org/browse/SAK-44305
If a user begins to compose a message, specifies the recipient, and all other fields as necessary, and then saves the draft, upon returning to that draft later on, the user will find that the recipient is no longer listed.
--
For the recipients, this is what is happening:
When you save a message, the recipients are saved to a table and are assigned a recipient type: received, sent, deleted, draft, custom. For a normal message, the TO and BCC users get the "received" type, and the sender gets the "sent" type. When you save a draft, the TO and BCC users are ignored, and the sender gets a "draft" type.
This is important because of how message folders are populated. When you go into the Sent folder, for example, it queries for all messages that …

SAK-44305 Messages > Compose Message > Specify Recipient > Save Draft > Recipient not Saved

---

library/src/morpheus-master/sass/modules/tool/resources/_resources.scss

https://jira.sakaiproject.org/browse/SAK-43971
Removed some old padding from Resources that was causing the breadcrumbs padding to be off.

SAK-43971 Resources - Fixed padding on breadcrumbs
