- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/LastNameComparator.java
Wrong sorting in GradebookNG with names containing accents
> SAK-32145 - Wrong sorting in GradebookNG with names containing accents

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
> SAM-3127 Precision errors in Statistics

- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
> SAM-3104 add a checkmark for correct answers

- reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- reference/library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
Might be a nice/useful addition, hello @bjones86, thoughts?
[JIRA - SAK-31651](https://jira.sakaiproject.org/browse/SAK-31651)
[Video Demo](https://goo.gl/Pjoa7A)
> SAK-31651 - Sticky header

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
- kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
- kernel/api/src/main/java/org/sakaiproject/content/cover/ContentHostingService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
Note that this does not force a unique display id. Folders now function the same as resources.
> SAK-13822 try to increment the folder name similar to resource id creation

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
Basic idea here: hide unimportant columns when you are on tiny screen so table fits on screen.
https://jira.sakaiproject.org/browse/SAK-32143
> SAK-32143 announcements hide unimportant columns from view when on a mobile device

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/SubmissionStatusListener.java
and"Submission Status" tabs when Assessment released to groups
> SAM-3135 Groups Select Input not consistent between "Total Scores"

- samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
> SAM-3140 Regression: Question Pool Properties missing in Edit Question

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
- content-review/contentreview-federated/pack/src/webapp/WEB-INF/components.xml
Upgrade for Assignments tool and Base content-review needed for : https://jira.sakaiproject.org/browse/SAK-32132 (11x) and used with https://github.com/sakaicontrib/urkund-antiplagiarism
> SAK-32132 : Content-review : Urkund Implementation

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
* Modify standard header to ignore # and $ at beginning
* Look for a course grade override before a standard column 
* Look for an ignore column before looking for a standard column
> 3800 more changes. Change order of matching to ignore earlier and look for course grade

- content-review/api/src/main/resources/ContentReviewItem.hbm.xml
- lessonbuilder/hbm/newhbm/org/sakaiproject/lessonbuildertool/checklistitemstatus.hbm.xml
- oauth/dao-hbm/src/resources/org/sakaiproject/oauth/dao/Accessor.hbm.xml
- oauth/dao-hbm/src/resources/org/sakaiproject/oauth/dao/Consumer.hbm.xml
This were emitting WARNINGs in the logs on startup because the references were to the old DTD on sourceforge.
> SAK-32183 Update hibernate mapping DTD.

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
> SAK-32159 hide columns in Assignments table on mobile device

- reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
This patch cannot be merged from master. This is because master is using the sticky header, which makes a function call that cannot be defined just yet on 11.x.
On master, the scroll listener is on ...usernav.js while on 11.x is on toggletools.js
> SAK-32197 - Following toolbar adjust on iframe late load - Follow up for SAK-31465

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/questionpool/QuestionPoolDataIfc.java
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/questionpool/QuestionPoolServiceAPI.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/questionpool/QuestionPoolData.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/authz/integrated/AuthzQueriesFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/questionpool/QuestionPoolServiceImpl.java
- AuthzQueriesFacade.removeAuthorizationByAgentQualifierAndFunction
- QuestionPoolFacadeQueries.getAllPoolsWithAccess
- QuestionPoolFacadeQueries.getSubPoolSize
- QuestionPoolFacadeQueries.getSubPoolSizes
- QuestionPoolFacadeQueries.getCountItemFacades
> SAM-3149 Hibernate 4 fixes for samigo

- calendar/calendar-bundles/resources/calendar.properties
- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java
- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/CalendarBean.java
- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/EventTypes.java
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar.vm
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_revise.vm
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewActivity.vm
- reference/library/src/morpheus-master/sass/modules/tool/calendar/_calendar.scss
- reference/library/src/webapp/schedule/README.txt
Images of the legend and synoptic calendar during testing:
> SAK-32187 Add new event types to the calendar tool.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/convert/DateTimeConverterWrap.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/qti/XMLImportBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/TimeUtil.java
- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
Samigo should now behave like Announcements and Assignments with dates:
* If server is in Eastern, you are in Central timezone (modify Sakai preferences), the times displayed and input into date pickers should be Central times
> SAM-3106 several modifications around date timezone manipulations

- assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/AssignmentSubmission.java
- assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/AssignmentSubmissionEdit.java
- assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/ContentReviewResult.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- content-review/api/src/main/java/org/sakaiproject/contentreview/dao/ContentReviewItem.java
- content-review/api/src/main/java/org/sakaiproject/contentreview/service/ContentReviewService.java
- content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/CompilatioReviewServiceImpl.java
- content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/ContentReviewFederatedServiceImpl.java
- content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/NoOpContentReviewService.java
- content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
- content-review/impl/urkund/src/main/java/org/sakaiproject/contentreview/urkund/UrkundReviewServiceImpl.java
- content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/ContentReviewServiceVeriCite.java
- reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
Use Font-Awesome icons in content review implementations
> SAK-32160 Use Font-Awesome icons in content review implementations

- master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32208
> SAK-32208 MariaDB/J 1.5.8

- profile2/pom.xml
> Twitter4J 4.0.4, library upgrades

- profile2/pom.xml
- sitestats/pom.xml
https://jira.sakaiproject.org/browse/SAK-32207
> SAK-32207 Update sitestats and Profile2 wicket 6.26.0

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/snippets/siteStatus-snippet.vm
> SAK-32210 Add alert styling to deletion message.

- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeStandardHead.vm
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
- profile2/api/src/java/org/sakaiproject/profile2/service/ProfileImageService.java
- profile2/impl/src/java/org/sakaiproject/profile2/service/ProfileImageServiceImpl.java
- profile2/pack/src/webapp/WEB-INF/components.xml
- profile2/tool/pom.xml
- profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileImageEntityProvider.java
- profile2/tool/src/webapp/WEB-INF/applicationContext.xml
- reference/library/pom.xml
- reference/library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
Original work from NYU with some considerable work on standardisation
by myself.
> SAK-32211 Added ability to change picture in portal

- edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementAdministrationHibernateImpl.java
- oauth/dao-hbm/src/java/org/sakaiproject/oauth/dao/HibernateAccessorDao.java
- reference/docs/Hibernate4Upgrade.md
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/authz/integrated/AuthzQueriesFacade.java
> SAK-32227 Hibernate 4 remove remaining getHibernateTemplate().find()

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includePageNav.vm
- reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
Ability to disable the animated tool menu by property
> SAK-32224 - Ability to disable the animated tool menu by property

- user/user-tool/tool/src/webapp/js/userCreateValidation.js
- user/user-tool/tool/src/webapp/js/userEditValidation.js
- user/user-tool/tool/src/webapp/vm/user/chef_users_create.vm
- user/user-tool/tool/src/webapp/vm/user/chef_users_edit.vm
> SAK-32217 Alter timing of password mismatch message on add or edit account pages.

- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/BaseValidationProducer.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/PasswordResetProducer.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/TransferMembershipsProducer.java
- reset-pass/account-validator-tool/src/webapp/templates/transferMemberships.html
> SAK-32216 Add the reset password link to the external user page when

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/HtmlPageFilter.java
> SAK-32228 Set the viewport when the HTML header is added.

- site-manage/site-manage-tool/tool/pom.xml
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/test/org/sakaiproject/site/tool/SiteActionTestTools.java
- site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteTypeUtil.java
Depends on #3881 being merged.
> SAK-32166 Allow import from site on custom site type

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/TemplateUpdateListener.java
> SAM-2962 Can not save automatic submission settings in template as admin

- reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- reference/library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
Change made, see these for pre and post fix:
> SAK-32188 Overlays for mobile view pop-ups working consistently.

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
This was what I wanted to add onto #3989
> SAM-3161 - Improve code for return of getSubPoolSize

- library/src/morpheus-master/sass/base/_responsive.scss
- library/src/morpheus-master/sass/modules/_toolmenu.scss
> SAK-32189 Configurable tools and subsites buttons now full-width on a

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- library/src/morpheus-master/sass/modules/access/_base.scss
- login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/choice.vm
- login/login-tool/tool/src/java/org/sakaiproject/login/tool/SkinnableLogin.java
> SAK-32250 Improvements to the login routing page.

- kernel/api/pom.xml
- master/pom.xml
- site-manage/site-manage-tool/tool/pom.xml
> SAK-32252 - Additional changes for mockito, left in duplicate reference

- library/pom.xml
- login/login-tool/tool/pom.xml
- master/pom.xml
Improvements: https://docs.spring.io/spring/docs/current/spring-framework-reference/html/new-in-4.3.html
> SAK-32273 upgrade spring dependencies to 4.3.6

- kernel/api/src/main/java/org/sakaiproject/event/api/UsageSession.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseUsageSession.java
https://jira.sakaiproject.org/browse/KNL-1490
iPad, iPhone, Adroid.
@deprecated: NetscapeNavigator, Camino
> KNL-1490 iPad, iPhone, Android.

- shortenedurl/pom.xml
https://jira.sakaiproject.org/browse/SAK-32274
> SAK-32274 org.apache.httpcomponents 4.5.3

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
not being removed from GradeBook
> SAM-3163 Comments (from the Tests & Quizzes Total Scores page) are

- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
- basiclti/basiclti-common/src/test/org/sakaiproject/util/foorm/TestFoormJUnit.java
- basiclti/basiclti-impl/src/bundle/email.properties
- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIReportingJob.java
Changes introduced in SAK-30601 broke the LTI additions reporting. But also adds a missing resource bundle that broke it.
> SAK-30510 Bug fixes to LTI additions reporting

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/SubmitTimedAssessmentThread.java
- samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java
Email Notification should filter by group if with the "Assessment
released to" option
> SAM-3077 Email Notification should filter by group

- oauth/pom.xml
- oauth/tool/src/java/org/sakaiproject/oauth/tool/admin/OauthAdminApplication.java
- oauth/tool/src/java/org/sakaiproject/oauth/tool/admin/pages/ConsumerAdministration.java
- oauth/tool/src/java/org/sakaiproject/oauth/tool/admin/pages/ListConsumers.java
- oauth/tool/src/java/org/sakaiproject/oauth/tool/pages/SakaiPage.java
- oauth/tool/src/java/org/sakaiproject/oauth/tool/user/OAuthApplication.java
- oauth/tool/src/java/org/sakaiproject/oauth/tool/user/pages/ListAccessors.java
This puts the OAuth tools back on a supported wicket library again.
> SAK-30806 Upgrade OAuth to wicket 7.6.0

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
also removed the Instance type in favor of the method type call
> SAK-32318 Hibernate 4 cast Long to Integer in query

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/ActivityServiceImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/AuthenticationCache.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/AuthnCacheWatcher.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BasePreferencesService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
https://jira.sakaiproject.org/browse/KNL-1502
> KNL-1502 Cache raw type, memoryService.newCache()

- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
Screenshot before the fix:
Screenshots after the fix:
> SAK-32310 Animate subsites menu when scrolling.

- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/base/_defaults.scss
- library/src/morpheus-master/sass/modules/_main.scss
- library/src/morpheus-master/sass/modules/_toolmenu.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/tool/_base.scss
- library/src/morpheus-master/sass/modules/tool/_menu.scss
This isn't the entire NYU skin.
This is a start at bringing over some of their elements: specifically the sub-tool menu and the shading on the boxes
> SAK-32282 NYU submenu styles and shading

- kernel/kernel-util/src/main/java/org/sakaiproject/util/StringUtil.java
Generate elements comment split, @deprecated comment-lang3
> NOJIRA Generate elemets comment split, @deprecated comment-lang3

- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupListProducer.java
Because of this https://github.com/sakaiproject/sakai/pull/3826#discussion_r105891441
> SAK-27980 Remove wrong Validator.escapeHtml()

- deploy/pom.xml
- master/pom.xml
Also dropping some elasticsearch dependencies as they've been made
optional
> SAK-32273 Additional lib updates due to Spring upgrade

- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/PasswordService.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/user/impl/PasswordServiceTest.java
Use a much better algorithm for storing passwords within the database.
> KNL-1504 Upgrade internal passwords to PBKDF2

- samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
The unified diff on this makes the edit appear odd ... I recommend reviewing in Split mode
> SAM-3174 the jquery-ui dialogs werent being opened as expected after time expired

- admin-tools/src/webapp/vm/user/chef_users_confirm_remove.vm
- admin-tools/src/webapp/vm/user/chef_users_create.vm
- admin-tools/src/webapp/vm/user/chef_users_edit.vm
- admin-tools/src/webapp/vm/user/chef_users_view.vm
https://jira.sakaiproject.org/browse/SAK-32342
> SAK-32342 CSS, js admin-tool/user

- library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
- library/src/morpheus-master/sass/base/_responsive.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
> SAK-32270 Make tools/subsites list scrollable on a mobile screen.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
#4107 
buildGradeMatrix() always sorts by user first even if the sort is for
another column. Additionally, descending sorts are first sorted in
normal order and then reversed (linear time) rather than using a
reverse-order sort to begin this.
This patch will address both issues.
> #4107 Performance improvements for column sorting

- master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32347
> SAK-32347 comons-validator 1.6

- kernel/kernel-impl/src/main/java/org/sakaiproject/config/impl/ConfigurationMBean.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/component-components.xml
This registers a DynamicMBean that exposes all registered configuration through JMX. It also allow creation of new config through JMX and changing of existing configuration.
> SAK-32341 Allow editing of configuration through JMX.

- courier/courier-impl/impl/src/java/org/sakaiproject/courier/impl/BasicCourierService.java
This means that thread is controlled by an executor service which
schedules the thread at a configurable interval.
> SAK-32339 Courier Service maintenance thread terminates vs eternal

- delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
https://jira.sakaiproject.org/browse/SAK-32344
> SAK-32344 gradebook, IdUsedException

- admin-tools/src/java/org/sakaiproject/alias/tool/AliasesAction.java
- admin-tools/src/java/org/sakaiproject/archive/tool/ArchiveAction.java
- admin-tools/src/java/org/sakaiproject/archive/tool/DownloadServlet.java
- admin-tools/src/java/org/sakaiproject/archive/tool/model/SparseFile.java
- admin-tools/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
- admin-tools/src/java/org/sakaiproject/authz/tool/RealmsAction.java
- admin-tools/src/java/org/sakaiproject/memory/tool/MemoryAction.java
- admin-tools/src/java/org/sakaiproject/site/tool/AdminSitesAction.java
- admin-tools/src/java/org/sakaiproject/user/tool/UsersAction.java
Orginezed import
Add default set
raw type
import org.apache.commons.lang.StringUtils; => import org.apache.commons.lang3.StringUtils; 
Kernel cover => Kernel api
> SAK-32343 

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
> SAM-3096 - Time limit exception does not work unless a time limit is set

- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
> SAK-32357 - Catch NPE's and provide more information about why grading

- user/user-tool-prefs/tool/pom.xml
- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
https://jira.sakaiproject.org/browse/SAK-32373
> SAK-32373 time zone: Deprecated, raw type

- delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserEditPage.html
Not perfect but I think it improves things and gets rid of the double scrollbar. Not sure why there's a scroll at the bottom. In any case this component should be replaced soon.
> SAK-30698 - DA screen width does not adjust properly for desktop

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_de.properties
This also resolves the issue regarding adding new gradebookng elements using the german datepicker
#4161
> 4161 GradebookNG: added german translation

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
Also remove a couple of local references.
> SAK-32376 Fix for case sensitive MySQL.

- lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/SimpleChecklistItem.java
- lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDao.java
- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
- lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/SimpleChecklistItemImpl.java
- lessonbuilder/tool/pom.xml
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ChecklistProducer.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ChecklistProgressProducer.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/SimplePageItemUtilities.java
- lessonbuilder/tool/src/resources/messages.properties
- lessonbuilder/tool/src/webapp/css/checklist.css
- lessonbuilder/tool/src/webapp/js/checklist.js
- lessonbuilder/tool/src/webapp/js/checklistDisplay.js
- lessonbuilder/tool/src/webapp/templates/Checklist.html
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Big Jira:
https://jira.sakaiproject.org/browse/LSNBLDR-790
Left it in separate commits to show the individual changes made. (as well as to preserve author attribution)
> LSNBLDR-790 checklist improvements (biggest is linking)

- samigo/samigo-app/pom.xml
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
Appears org.sakaiproject.tool.assessment.ui.bean.questionpool.QuestionPoolBean#filename was never actually used.
> SAM-1261 Remove struts from samigo app

- master/pom.xml
version: 2.10.3 =>  2.10.4
java: 6 =>  8
commons-lang
> SAK-32392 version: 2.10.3 =>  2.10.4

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/ContentReviewServiceVeriCite.java
https://jira.sakaiproject.org/browse/SAK-32363
- Add config field: contentreview.config.show_preliminary_score (TRUE)
- Implemented in VeriCite
> SAK-32363 Content Review - Config to Show/Hide Preliminary Report

- samigo/samigo-app/src/webapp/jsf/delivery/assessmentDeliveryHeading.jsp
I took Shawns advice on SAK-32282 and they do display now, but the left alignment seems a little off here?
> SAM-3176 - Table of contents and Show Feedback buttons no longer display

- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/DateUtil.java
- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/DecoratedChatChannel.java
- chat/chat-tool/tool/src/webapp/jsp/editRoom.jsp
Chat - please use new date picker for consistency
> SAK-27778 - Chat - please use new date picker for consistency

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/BasePage.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportsEditPage.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/util/DateUtil.java
- sitestats/sitestats-tool/src/webapp/html/pages/ReportsEditPage.html
- sitestats/sitestats-tool/src/webapp/script/reports.js
Update sitestats datepicker to use the Sakai jQuery datepicker
> SAK-32205 - Sitestats tool needs date picker update

- master/pom.xml
https://jira.sakaiproject.org/browse/KNL-1515
> KNL-1515 commons-pool 1.6

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
GradebookNG crashes when you type comma in a grade #3930
> GBNG-3930 - GradebookNG crashes when you type comma in a grade #3930

- emailtemplateservice/impl/logic/pom.xml
- emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
- emailtemplateservice/tool/pom.xml
- emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/handler/ModifyEmailHandler.java
- emailtemplateservice/tool/src/java/org/sakaiproject/emailtemplateservice/tool/locators/EmailTemplateLocator.java
emailtemplateservice:
iimport org.apache.commons.lang.LocaleUtils;
import org.apache.commons.lang.StringUtils;
=>
import org.apache.commons.lang3.LocaleUtils;
import org.apache.commons.lang3.StringUtils;
> SAK-32408 commons-lang3.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
With the switch from Apache James to SubEthaSMTP some of the config options and comments need updating.
> SAK-32446 Update default config for SubEthaSMTP

- library/src/webapp/js/lang-datepicker/lang-datepicker.js
- library/src/webapp/skin/tool_base.css
Replace jQuery datepicker icon to use font-awesome
> SAK-32416 - Replace jQuery datepicker icon to use font-awesome

- signup/api/src/java/org/sakaiproject/signup/model/SignupTimeslot.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/CopyMeetingSignupMBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/EditMeetingSignupMBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/UserDefineTimeslotBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/util/Utilities.java
- signup/tool/src/webapp/js/signupScript.js
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
Update SignUp with the new date picker introduced in SAK-23662
> SAK-28415 - Update SignUp datepicker

- syllabus/syllabus-api/src/java/org/sakaiproject/api/app/syllabus/SyllabusData.java
- syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java
- syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/util/DateUtil.java
- syllabus/syllabus-app/src/webapp/syllabus/edit.jsp
- syllabus/syllabus-app/src/webapp/syllabus/edit_bulk.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
- syllabus/syllabus-app/src/webapp/syllabus/read.jsp
Syllabus datepicker should use internationalized versions
> SAK-25369 - Syllabus datepicker should use internationalized versions

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
I tweaked this when testing for SAM-3178 locally, it seems to resolve this.
> SAM-3188 Fix missing param name

- lessonbuilder/tool/pom.xml
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/AbstractParser.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/DefaultHandler.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/Parser.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/PrintHandler.java
This builds on and depends on PR #4210. I can rebase after that is merged
> LSNBLDR-799 - Fixup links on import from package

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
This is adding some config to LSNBLDR-633 so that the feature can be turned on or off.
Default is on.
If this goes back to 11.x, then the property should be set to false and uncommented out.
> LSNBLDR-633: Adding config for lessonbuilder.show.set.owner

- library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- library/src/morpheus-master/js/src/sakai.morpheus.utils.js
- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/base/_responsive.scss
- library/src/morpheus-master/sass/modules/more-sites/_base.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/tool/_base.scss
- library/src/morpheus-master/sass/modules/tool/syllabus/_syllabus.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- syllabus/syllabus-app/src/webapp/js/syllabus.js
- syllabus/syllabus-app/src/webapp/syllabus/css/jqueryui-editable.css
- syllabus/syllabus-app/src/webapp/syllabus/delete_confirm.jsp
- syllabus/syllabus-app/src/webapp/syllabus/edit_bulk.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
This PR delivers the following JIRAs:
- https://jira.sakaiproject.org/browse/SAK-32443
- https://jira.sakaiproject.org/browse/SAK-32414
- https://jira.sakaiproject.org/browse/SAK-32430
- https://jira.sakaiproject.org/browse/SAK-32431
- https://jira.sakaiproject.org/browse/SAK-32420
- https://jira.sakaiproject.org/browse/SAK-32433
- https://jira.sakaiproject.org/browse/SAK-32418
> Another round of NYU morpheus changes

- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/Topic.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/AnonymousManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/AreaManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DefaultPermissionsManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DummyDataHelper.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/EmailNotificationManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ForumScheduleNotificationImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MembershipManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsTypeManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsUserManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/PermissionManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/RankManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/SynopticMsgcntrManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/ForumEntityProviderImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/ForumMessageEntityProviderImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/ForumTopicEntityProviderImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/MessageForumsEntityContentProducer.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/SynopticMsgcntrItemEntityProviderImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/entity/TopicEntityProviderImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/exception/AccessDeniedException.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/exception/LockedException.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/jobs/UpdateSynopticMessageCounts.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
- msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-32444
impl: cover => api; serializable class; Organize Imports
> SAK-32444 impl: cover => api; serializable class; Organize Imports

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookInformation.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradingType.java
- edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Gradebook.hbm.xml
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradableObject.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Gradebook.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
because of final grade mode #3451
> SAK-32451 trying to reconcile changes between master and 11.x

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/DoubleComparator.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
Order the custom grade scales by value instead of key.
> GBNG-4200 - Custom Grade Scales not Sorted Properly

- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/BasePage.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MySearch.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ConfirmedFriends.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/RequestedFriends.html
as the control should get tabbed not the text
CC: @mclare
> SAK-31621 remove tabindex from profile page spans 

- library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- library/src/morpheus-master/sass/modules/more-sites/_base.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
> SAK-32466 turn Sites and Organize Favorites into links so they get tab focus

- velocity/tool/src/java/org/sakaiproject/cheftool/Configuration.java
- velocity/tool/src/java/org/sakaiproject/cheftool/EnumerationIterator.java
EnumerationIterator: @Deprecated, raw
> SAK-32493 EnumerationIterator: @Deprecated, raw

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookFrameworkServiceImpl.java
> Make "Letter Grade" and "Percentage" the default final grade release selections

- gradebookng/tool/src/webapp/styles/gradebook-grades.css
> Fix Section/Group Dropdown and 'Showing [x] Students' text vertical alignment

- velocity/tool-api/src/java/org/sakaiproject/cheftool/api/MenuItem.java
- velocity/tool/pom.xml
- velocity/tool/src/java/org/sakaiproject/cheftool/AlertImpl.java
- velocity/tool/src/java/org/sakaiproject/cheftool/NewPagedResourceAction.java
- velocity/tool/src/java/org/sakaiproject/cheftool/PagedResourceAction.java
- velocity/tool/src/java/org/sakaiproject/cheftool/PagedResourceActionII.java
- velocity/tool/src/java/org/sakaiproject/cheftool/PagedResourceHelperAction.java
- velocity/tool/src/java/org/sakaiproject/cheftool/VelocityPortletStateAction.java
- velocity/tool/src/java/org/sakaiproject/cheftool/VmServlet.java
- velocity/tool/src/java/org/sakaiproject/cheftool/menu/MenuDivider.java
- velocity/tool/src/java/org/sakaiproject/cheftool/menu/MenuEntry.java
- velocity/tool/src/java/org/sakaiproject/cheftool/menu/MenuField.java
- velocity/tool/src/java/org/sakaiproject/cheftool/menu/MenuImpl.java
- velocity/tool/src/java/org/sakaiproject/util/FileItem.java
- velocity/tool/src/java/org/sakaiproject/util/ParameterParser.java
https://jira.sakaiproject.org/browse/SAK-32501
> SAK-32501 raw, collections4, serial version ID

- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/DifferentRoleProducer.java
- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/SameRoleProducer.java
Minor changes to introduce some spaces in the fillCompnents methods for the SameRoleProducer and DifferentRoleProducer classes.
> SAK-32510: Correct spacing for usernames in Site Info Add Participants

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Edit a site removes the configured skin
> SAK-32505 - Edit a site removes the configured skin

- content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/ContentReviewServiceVeriCite.java
- content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/client/api/DefaultApi.java
- content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/client/model/ExternalContentUploadInfo.java
https://jira.sakaiproject.org/browse/SAK-32478
ContentReview implementation VeriCite to always encrypt uploads.
> SAK-32478 ContentReview VeriCite to use encryption when uploading

- edu-services/gradebook-service/api/pom.xml
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/Assignment.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CategoryDefinition.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CourseGrade.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradeMappingDefinition.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookInformation.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradingScaleDefinition.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/PermissionDefinition.java
- edu-services/gradebook-service/hibernate/pom.xml
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/AbstractGradeRecord.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Comment.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/CourseGradeRecord.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradableObject.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradeMapping.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Gradebook.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradebookProperty.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradingScale.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Spreadsheet.java
- edu-services/gradebook-service/impl/pom.xml
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookPermissionServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
import org.apache.commons.lang.* => import org.apache.commons.lang3.*
https://jira.sakaiproject.org/browse/SAK-32514
> SAK-32514 Gradebook commans-lang3

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/roleSwitch-snippet.vm
Delivers https://jira.sakaiproject.org/browse/SAK-32481
> SAK-32481 remove superfluous skip label that didn't have a translation

- .circleci/config.yml
This uses CircleCI. It saves up to 3 minutes to test time. And also fix some travis issues
https://jira.sakaiproject.org/browse/SAK-32524
> SAK-32524 CircleCI

- polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java
e.printStacktrace() can end up in a different location to the logging and so gets detached from any other logs at the time. Also added a few generics and update to foreach loops.
> SAK-32525 Use logger instead of e.printStacktrace().

- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/pom.xml
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/AbstractMembershipContainerCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/AbstractNamedCourseManagementObjectCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/AbstractPersistentCourseManagementObjectCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/CrossListableCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/impl/pom.xml
- edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SiteTitleAdvisorCMS.java
- edu-services/scoring-service/impl/src/java/org/sakaiproject/scoringservice/impl/ScoringServiceImpl.java
- edu-services/sections-service/sections-impl/integration-support/pom.xml
- edu-services/sections-service/sections-impl/sakai/impl/pom.xml
- edu-services/sections-service/sections-impl/sakai/impl/src/java/org/sakaiproject/component/section/sakai/SectionManagerImpl.java
- edu-services/sections-service/sections-impl/sakai/model/pom.xml
- edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseImpl.java
- edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseSectionImpl.java
- edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/MeetingImpl.java
- edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/ParticipationRecordImpl.java
- edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/SectionEnrollmentsImpl.java
- edu-services/sections-service/sections-impl/standalone/pom.xml
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/AbstractPersistentObject.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/CourseImpl.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/LearningContextImpl.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/MeetingImpl.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/ParticipationRecordImpl.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/SectionEnrollmentsImpl.java
- edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/UserImpl.java
Raw type
serial version ID
commons-lang3
> SAK-32530 edu-services

- citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
> SAK-32507: Include citationCollectionId in stacktrace to fix broken lists

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Prevent assignments from being switched from individual to group assignments which can cause problems.
> SAK-32064 Prevent assignments from being switched from individual to group assignments

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
- webservices/cxf/src/java/org/sakaiproject/webservices/Assignments.java
A new web service to increment all dates (release, due, accept until, etc.) for an assignment by the same amount of days and hours.
> SAK-32529 - Add web service to increment all dates for assignment

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/rsf/producers/BeginAssessmentProducer.java
- samigo/samigo-app/src/webapp/WEB-INF/requestContext.xml
PR against master instead of 11.x
> SAM-3178 Force "direct" links to redirect to Login servlet

- kernel/api/src/main/java/org/sakaiproject/entity/api/EntityTransferrer.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/EntityTransferrerRefMigrator.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/LinkMigrationHelperImpl.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/LinkMigrationHelperImplTest.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportDefEntityProducer.java
To check I understand how it works I wrote some simple tests of LinkMigrationHelper and added JavaDoc to the EntityTransferrerRefMigrator. I also updated some part of SiteAction that were calling the EntityTransferrer.
> SAK-32536 Tests of LinkMigrationHelper to check behaviour

- master/pom.xml
https://jira.sakaiproject.org/browse/KNL-1528
> KNL-1528 MariaDB connector/j 1.5.9

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp
> SAM-3131 re-do fill-in-the-blank accessibility

- library/src/webapp/editor/ckextraplugins/sakaipreview/plugin.js
Delivers https://jira.sakaiproject.org/browse/SAK-32533
> SAK-32533 fix js error when using CKEditor sakaipreview plugin in source mode

- content-review/impl/vericite/pom.xml
- master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32543
> SAK-32543 joda-time 2.9.9

- library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMultipleChoiceSingleCorrect.jsp
> SAM-2610 multiple-choice questions should be wrapped in a fieldset and use a legend. Answers should use labels.

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Refines the techniques for disabling the controls after the assignment is posted.
> SAK-32565 Fix Peer Assessment issues from SAK-32064

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
- samigo/samigo-app/src/webapp/jsf/author/publishAssessment.jsp
Add average score to Samigo's publication notification which goes
out to students.
> SAM-3205 Add average score to Samigo pub Noti

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
This PR is for Sakai 11.x.  Not Trunk!  (I hope I do this right.)
> SAK-32565 Assignments Peer Review Fix for Sakai 11.x

- polls/api/pom.xml
- polls/api/src/java/org/sakaiproject/poll/model/Poll.java
- polls/impl/pom.xml
- polls/tool/pom.xml
- polls/tool/src/java/org/sakaiproject/poll/tool/entityproviders/PollsEntityProvider.java
- polls/tool/src/java/org/sakaiproject/poll/tool/producers/ResultsProducer.java
- polls/tool/src/java/org/sakaiproject/poll/tool/validators/OptionValidator.java
- reset-pass/account-validator-impl/pom.xml
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/reset-pass/pom.xml
- reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/UserValidator.java
import org.apache.commons.lang.StringEscapeUtils; => import org.apache.commons.lang3.StringEscapeUtils;
delete pom.xlms: <dependency>
<groupId>commons-collections</groupId>
<artifactId>commons-collections</artifactId>
> SAK-32557    commons-lang3,  delete:commons-collections

- content-review/impl/compilatio/pom.xml
- content-review/impl/turnitin/pom.xml
- content-review/impl/urkund/pom.xml
- emailtemplateservice/impl/logic/pom.xml
- hierarchy/impl/pom.xml
- reset-pass/account-validator-impl/pom.xml
- rwiki/rwiki-impl/impl/pom.xml
- rwiki/rwiki-tool/tool/pom.xml
- rwiki/rwiki-tool/tool/src/test/uk/ac/cam/caret/sakai/rwiki/bean/test/RenderBeanTest.java
- search/search-impl/impl/pom.xml
- signup/impl/pom.xml
- signup/pom.xml
Upgrade to the latest version of easymock.
> SAK-32594 Upgrade easymock to 3.4

- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactory.java
Simple actual fix, but also cleaned up some overly verbose logging of not found collections in second commit.
> SAK-32588 Allow uploads without dots in name

- calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/css/cal.css
- library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_variables.scss
- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/modules/bullhorn-alerts/_base.scss
- library/src/morpheus-master/sass/modules/tool/_menu.scss
@payten let me know if you have any preferred color changes
I made changes with http://webaim.org/resources/contrastchecker/  ... nothing picked by hand
> SAK-32591 make color contrast WCAG 2 compliant

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
These are fairly straightforward. A "menuitem" must exist inside a role="menu".
> SAK-32595 role=menuitem must be contained within a role=menu

- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityUser.java
The display ID wasn’t being correctly set even when it was present.
> SAK-32542 Fix for display ID appearing as EID.

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/CollectionAccessFormatter.java
- library/src/morpheus-master/sass/access.scss
- Reverted previous functionality
- Added FA icons via SCSS
> SAK-32372 : Access Servlet doesn't use font awesome icons

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Part of the commit in LSNBLDR-64 that addressed the import of the Custom CSS setting isn't actually there.
> LSNBLDR-818 Custom stylesheet setting isn't carried over on import

- msgcntr/messageforums-app/src/webapp/css/msgcntr_statistics.css
This is only affecting to 11.x because of the changes on master of `nav class="Mrphs-toolTitleNav Mrphs-container--toolTitleNav"`
> SAK-30986 Statistics & Grading - Grading by Topic - Increase Padding

- library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
@mclare can you review this video showing the new functionality: https://jira.sakaiproject.org/secure/attachment/47547/tabbing.webm
> SAK-31616 lock focus inside the modal and add role=dialog to the dialog

- library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
My main question for @mclare: should a right arrow key inside the tabs just move focus or should it simulate a focus() + click()?
> SAK-32600 keyboard arrow navigation for tabs in Sites dialog

- content/content-bundles/resources/types.properties
- content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
> SAK-32606 make Resources-Upload-Overwrite use a fieldset like Availability

- web/web-impl/impl/src/java/org/sakaiproject/web/impl/WebServiceImpl.java
This is a five year old bug. I will make comments on the ticket rather than here.
> SAK-21867 duplicate web content items not added to site

- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/entity/UserPrefsEntityProvider.java
The tools collapsed state is now controlled by a server preference, not
a cookie. As you switch between tools there is no more glitching in and
out of the tool menu.
> SAK-32389 Tool menu toggling now stored on server.

- signup/tool/src/webapp/js/signupScript.js
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
Link to user defined timeslots does not appear when adding a new
meeting.
Copy & Modify works fine.
> SAK-32635 - Link to user defined timeslots does not appear

- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm
Also change text of second instruction.
Post fix screenshots:
> SAK-32034 Ensure instruction only displayed if required.

- CODE_OF_CONDUCT.md
- CONTRIBUTING.md
Acknowledge the Apereo Welcoming Policy as the project's "code of conduct" and thereby pick up 25% more [community](https://github.com/SakaiProject/sakai/community) points.
> Acknowledge Apereo Welcoming Policy

- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/SitePresence.java
- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/SitePresenceTotal.java
- sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/SitePresenceTotalImpl.java
- sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/hbm/SitePresenceTotalImpl.hbm.xml
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
Split into 2 commits so it's easier to see the cleanups/docs from the actual fix/change.
> SAK-31760 Make sure we never have null last visit time.

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Assignments / points not displayed to students
> SAK-32589 - Assignments / points not displayed to students

- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
This got removed and then added back to just 11 but never made it onto master. There are still some problems with it, but this gets it working again.
> SAK-32238 Add back the JS for subsites flout.

- roster2/src/java/org/sakaiproject/roster/api/RosterData.java
- roster2/src/java/org/sakaiproject/roster/api/SakaiProxy.java
- roster2/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
- roster2/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java
- roster2/src/webapp/js/roster.js
included as a property : roster.display.pageSize (default 10)
> SAK-32109 : Roster / not showing full list until scrolling

- master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32670
> SAK-32670 poi

- basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
Thanks Matt - This also fixes SAK-32686
> SAK-32685 - Improve A11Y for LTI insert form

- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- library/src/morpheus-master/sass/modules/_toolmenu.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
CC: @adrianfish @Johnson-Mickey 
This is related to the second commit in https://jira.sakaiproject.org/browse/SAK-32389
> SAK-32687 fix aria-pressed state issues

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
> 4575 - Apply fix for GBNG to create a gradebookid when it doesn't exist

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
- gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
There are also commits for the 11.3 and 11.4 branches.
> SAK-32633 gradebook regexps

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
https://jira.sakaiproject.org/browse/SAK-32706
> SAK-32706: protect against NPE in My Official Enrolments

- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/time/impl/test/BaseTimeServiceTest.java
This is the correct fix for SAK-23076 - and once the wrong fix for SAK-23076 is reverted in the commit for SAK-30793, then both SAK-23076 and SAK-30793 will be fixed at the same time (i.e. the fix for one won't break the other)
> KNL-1536 - Fix duration()

- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
See also SAK-31956 (duplicate)
> SAK-32665 - Allow LTI Tools in !user

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
> SAK-32389 - Have to protect the variable in VM so no error when logged

- kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
> SAK-32569 - Stealth gradebook for Sakai 12

- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- lessonbuilder/tool/src/webapp/js/show-page.js
This has a 'conversion script' which should sync up all poll data too because if the record isn't created when the question is created there won't be a record there. I didn't get that fixed to sync up in the code. There's a method here syncQRtotals but it doesn't look like it actually deals with the counts at all and I tried to change some code here and ended up with database concurrency issues so didn't have the time to spend on it. This was the conversion (for MySQL) which maybe we'll just put in the script files and could use a little more comparison testing. I guess it's nice to just have if this works.
```
DELETE FROM lesson_builder_qr_totals;
INSERT INTO lesson_builder_qr_totals (questionId,responseId,respcount) select questionId, multipleChoiceId, sum(correct) from …
```
> LSNBLDR-840 - Lessons - "Add Question" - Show Poll Results Does Not Work

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/ContextMappingDAO.java
Please read the JIRA [SAK-32673](https://jira.sakaiproject.org/browse/SAK-32673) for more info.
Here is one posible solution for Spring/Hibernate problem.
The logic problem will be solved in this other JIRA [SAK-31935](https://jira.sakaiproject.org/browse/SAK-31935)
> SAK-32673 : Create forum/topic not working with open+close dates

- roster2/src/webapp/WEB-INF/bootstrap.jsp
- roster2/src/webapp/js/roster.js
roster.display.officialPicturesByDefault was overriding the permission
> SAK-32374 Honour official photo permission correctly

- master/pom.xml
lang3 3.6
beanutils 1.9.3
digester 2.1
https://jira.sakaiproject.org/browse/SAK-33255
> SAK-33255 lang3 3.6, beanutils 1.9.3, digester 2.1

- basiclti/tsugi-util/src/test/org/tsugi/basiclti/BasicLTIUtilTest.java
Sorry - I checked in a unit test that was sensitive to timezone
> SAK-33260 - Fix the build

- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
> SAK-32770 - set a default tool_consumer_instance_guid 

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
… when categories are enabled.
Fixes https://jira.sakaiproject.org/browse/SAK-33268
> SAK-33268 fix gradebookng item not able to be saved with counted=true 

- portal/portal-service-impl/impl/pom.xml
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
- portal/portal-service-impl/impl/src/webapp/WEB-INF/components.xml
Also simplified some of the spring beans!
> SAK-33272 Bullhorns needs to flush Hibernate session before launching a new thread

- master/pom.xml
https://jira.sakaiproject.org/browse/SAK-33278
> SAK-33278 spring 4.3.10

- site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages.properties
This corrects a run-on sentence in the hide tool warning.
> SAK-33298 Correct run-on sentence in hide tool warning.

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-32765
Duplicated topic needs to copy over the settings for postAnonymous and revealIDsToRoles from the original.
> SAK-32765: anonymous topic settings are not retained on import/site duplication

- user/user-tool-prefs/tool/src/webapp/js/prefs.js
- user/user-tool-prefs/tool/src/webapp/prefs/editor.jsp
- user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp
- user/user-tool-prefs/tool/src/webapp/prefs/locale.jsp
- user/user-tool-prefs/tool/src/webapp/prefs/noti.jsp
- user/user-tool-prefs/tool/src/webapp/prefs/timezone.jsp
https://jira.sakaiproject.org/browse/SAK-33302
The buttons in Preferences have their own non-standard button disabling behaviour. Replace with the centralized disable & spin technique for all form buttons.
> SAK-33302: apply centralized clone & spin technique to form buttons in Preferences

- assignment/tool/pom.xml
https://jira.sakaiproject.org/browse/SAK-33316
> SAK-33316 ${sakai.poi.version}

- master/pom.xml
because of issues observed in samigo. SAK-33255 is where the update was originally made.
> SAM-3251 reverting beanutils update 

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
Drop box / Always send email notifications does not send email
> SAK-27864 - Drop box / Always send email notifications does not send email

- signup/tool/src/bundle/messages.properties
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/CopyMeetingSignupMBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/EditMeetingSignupMBean.java
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
Signup new meeting validation error resets the dates
> SAK-33330 - Signup new meeting validation error resets the dates

- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/CopyMeetingSignupMBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/EditMeetingSignupMBean.java
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
Resolved a blocker bug due to incorrect variable binding when editing or
copying a signup meeting.
> SAK-33330 - Resolved a blocker bug due to incorrect variable binding.

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
I know there are some whitespace changes these files need to have better formatting!
- Student Submission Confirmation View
- fixed attachment rendering in student submission confirmation
- template formatting
- removed extraneous context keys
> SAK-33365 Assignments Student Submission Confirmation template fixes

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- kernel/component-manager/src/main/java/org/sakaiproject/component/locales/SakaiLocales.java
Include Italian in the supported languages list
> SAK-33364 - Include Italian in the supported languages list

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- removed FormattedText Cover
- getMaxGradePointDisplay now uses getGradeDisplay
- Added unit tests for getGradeDisplay
> SAK-33317 Assignments grade point display improvements

- master/pom.xml
- fixed in mariadb-java-client 2.1.0
> SAK-33373 Maria JDBC Unknown prepared statement handler

- calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java
- kernel/api/src/main/java/org/sakaiproject/db/api/SqlService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/ClusterEventTracking.java
Must test with rewriteBatchedStatements=true on your JDBC conn string!
> KNL-1540 write events using prepared statement batching

- signup/pom.xml
- signup/tool/pom.xml
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/DownloadEventBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/EventWorksheet.java
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/WorksheetStyleClass.java
> SAK-33346 Signup .xlsx

- jsf/jsf-spreadsheet/pom.xml
- jsf/jsf-spreadsheet/src/java/org/sakaiproject/jsf/spreadsheet/SpreadsheetDataFileWriterXlsx.java
- sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/RosterBean.java
- usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/Export.java
SpreadsheetDataFileWriterXl: @Deprecated
SpreadsheetDataFileWriterXlsx: add
usermebership-tool: Export
sections/sections-app backingbean/RosterBean.java 
not gradebook classic
> SAK-33378 Jsf xlsx

- lessonbuilder/tool/src/webapp/css/Simplepagetool.css
> LSNBLDR-863 Fix so embedded announcements follow the set colour scheme.

- site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages.properties
Ungrammatical warning sentence in Organize Tools
> SAK-31987 - Ungrammatical warning sentence in Organize Tools

- assignment/tool/src/java/org/sakaiproject/assignment/tool/RedirectingAssignmentEntityServlet.java
equals was causing a class cast exception.
> SAK-33395 Assignments RedirectingAssignmentEntityServlet.MySecurityAdvisor equals

- jsf/jsf-spreadsheet/src/java/org/sakaiproject/jsf/spreadsheet/SpreadsheetDataFileWriterXls.java
- jsf/jsf-spreadsheet/src/java/org/sakaiproject/jsf/spreadsheet/SpreadsheetDataFileWriterXlsx.java
deprecated Poi 3.18
.setFillBackgroundColor(HSSFColor.BLUE_GREY.index); =>setFillBackgroundColor(IndexedColors.BLUE_GREY.getIndex());
> SAK-33386 deprecated Poi 3.18

- config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/tool/tools.properties
> SAK-32762 Rename Plugin Tools to External Tools

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
https://jira.sakaiproject.org/browse/SAK-33283
> SAK-33283: Gradebook Import/Export tab does not display

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentServiceConstants.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- add unit test for duplicating an assignment
- move duplicate logic into service
> SAK-33318 Assignments duplicate assignment fix

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderAccessService.java
There is some discussion on the JIRA: https://jira.sakaiproject.org/browse/LSNBLDR-791
> LSNBLDR-791 allow PDF to open from embedded Lessons page

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
Site Language does not need size="5"
> SAK-33421 - Site Language does not need size="5"

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/EmailUtil.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- Added EmailUtil organizing email methods to that class
> SAK-33424 Assignments submission notifications

- samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java
> SAM-3271 send to all instructors if there are no group instructors

- library/pom.xml
- library/src/morpheus-master/sass/modules/editor/_base.scss
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
Upgrade the CKEditor to the latest maintenance release
> SAK-33409 - Upgrade the CKEditor to the latest maintenance release (4.5.7 -> 4.5.11)

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
List, Collect raw type
public ..
Generate Element Comment
> AssignmentService API raw type

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-importexport.css
Delivers https://jira.sakaiproject.org/browse/SAK-33385
> SAK-33385 add ability to filter custom export by section/group

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Delivers https://jira.sakaiproject.org/browse/SAK-33448.
> SAK-33448 ensure column filter dropdown menus are not repositioned onscroll

- textarea/FCKeditor/connector/src/java/org/sakaiproject/connector/fck/FCKConnectorServlet.java
@ottenhoff A small change here based on your suggestion.  Thanks!
> SAK-32346 (2)

- library/src/morpheus-master/sass/base/_extendables.scss
Syllabus buttons are unreadable
> SAK-33329 - Syllabus buttons are unreadable

- delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/logic/ProjectLogicImpl.java
- delegatedaccess/impl/src/webapp/WEB-INF/components.xml
scheduledInvocationManager.createDelayedInvocation(Time @deprecated
=> scheduledInvocationManager.createDelayedInvocation(Date.toInstant(
memoryService.newCache( => memoryService.getCache(
> SAK-33507 DelegatedAccess use Instant vs deprecated TimeSerivce

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
Regression from SAM-3254 - feedback link does not work for students
> SAM-3290 - Regression from SAM-3254 - feedback link does not work for students

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Delivers https://jira.sakaiproject.org/browse/SAK-33528
> SAK-33528 Fix JavaScript errors when columns are hidden

- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/MyTime.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/time/impl/test/TimeRangeTest.java
Simple tests of the behaviour of TimeRange.
> KNL-1565 Added tests for TimeRange

- site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/SiteManageConstants.java
- site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/SiteManageService.java
- site-manage/site-manage-impl/impl/pom.xml
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
- site-manage/site-manage-impl/impl/src/webapp/WEB-INF/components.xml
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
The previous threaded approach for copying/importing tool data was improved upon.
Create new SiteManageService (with the idea of removing logic from the tool layer, SiteAction).
> SAK-33524 SiteManageService improvment to tool copy/import

- calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java
- kernel/api/src/main/java/org/sakaiproject/db/api/SqlService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
This reverts commit 1d747e436afa867712a57eb0f3ef763e696145a5 and 10477d424074c7b970560c00d9c44ef5b3f3e793.
> Revert "KNL-1541 - setUserSecurity should use batched updates (#4886)"

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
Gradebook decimal separator inconsistency.
Tested in en_US, es_ES, fr_FR and sv_SE
> SAK-32562 - Gradebook decimal separator inconsistency

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
Cannot enter a grade in percentage using comma as decimal separator
> SAK-33530 - Enter grades using comma as decimal separator

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionAreaBean.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionForumBean.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionTopicBean.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ForumScheduleNotificationImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/SakaiUserPreferencesManagerImpl.java
- msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
1)  TimeService => UserTimeService (Impl)
2) scheduledInvocationManager.createDelayedInvocation( (Instant)
3) TimeService => org.sakaiproject.api.app.messageforums.UserPreferencesManager (Tool)
> SAK-33542 - Remove deprecated TimeService from Forums

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
- gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
- gradebookng/tool/src/test/resources/grades_import_i18n.csv
Import grades doesn't work with locales that use comma as decimal separator
> SAK-33521 - Import grades doesn't work with locales that use comma as decimal separator

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentSupplementItemServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/sort/AssignmentComparator.java
- assignment/impl/src/webapp/WEB-INF/components.xml
Time now = timeService.newTime() => Instant now = Instant.now();
> SAK-33588 AssignmentSupplementItemServiceImpl Deprecated Time 

- assignment/impl/src/webapp/WEB-INF/components.xml
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
There were two different cases of error, with two different reasons.
With new submissions, there was a problem with the EntityManager injection (EmaulUtil class).
For old submissions (badly saved, I guess), there was a NPE thrown by the lastmodified date.
> SAK-33567 Solving two errors when student tries to submit a file

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- The students submission status date to appear localized.
- In the students submission view grade the grade scale was showing "Points (max 5000)" should be "Points (max 50.00)"
> SAK-33597 Assignments improved getSubmission

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Detected cases on grade and submission screens.
> SAK-33569 hide no attachments message from student's view

- kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
- kernel/api/src/main/java/org/sakaiproject/content/api/GroupAwareEdit.java
- kernel/api/src/main/java/org/sakaiproject/content/api/GroupAwareEntity.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/AbstractContentResource.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/MockContentEntity.java
https://jira.sakaiproject.org/browse/KNL-1568
> KNL-1568 GroupAwareEdit & GroupAwareEntity: Time -> Instant

- library/src/webapp/editor/ckextraplugins/audiorecorder/plugin.js
> SAK-30004 - remove audiorecorder placeholder image creation

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
it because the info is redundant with help
> LSNBLDR-886 - The Tips button points to a useless html page, just remove

- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
Fix Reset Selection behavior by calling same JS function as onSubmit. Possible refactoring opportunity down the road.
https://jira.sakaiproject.org/browse/SAM-3311
> SAM-3311 -- Reset Selection Wipes ImageMap / HotSpot Answers

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
> SAK-33668 Assignments allowAddSubmissionCheckGroups with 0 groups

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
Solving a bug for extended service on published assessments.
> SAM-3268 avoid creating empty exceptions and reset update button

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
Submitted grades through Forums not saved in Gradebook
Cannot assign gradebook item through Forums grading dialog
> SAK-33620 Submitted grades through Forums not saved in Gradebook. SAK-33622 Cannot assign gradebook item through Forums grading dialog

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Delivers https://jira.sakaiproject.org/browse/SAK-33369:
> SAK-33369 show the assignments in gradebookng when there are no students

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentServiceConstants.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/js/assignments.js
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Moved all references to "group" and "site" to use the Assignment.Access enum for consistency.
> SAK-33679 Assignment ability to add group assignments gradebook

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EntityBrokerEventRegistry.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventRegistryServiceImpl.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
Forums (msgcnt), Sitestats, portal
> SAK-33688 .newCache => .getCache; Cache => Cache<k, v>

- lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/Assignment2Entity.java
- lessonbuilder/tool/opt-src/java/org/sakaiproject/lessonbuildertool/service/MnemeEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/ForumEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonsAccess.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/MnemeEntity.java.disabled
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
newCache(String) => getCache(String)
Cache => Cache<k, v>
covers => api
> LSNBLDR-914 newCache(String) => getCache(String)

- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonsAccess.java
Signed-off-by: Miguel Pellicer <mpellicer@entornosdeformacion.com>
> SAK-31796 - Fix a problem with UDS imports

- endorsed/i18n/src/main/java/org/sakaiproject/endorsed/i18n/spi/SakaiLocaleServiceProviderUtil.java
I'm not able to reproduce the problem in my local :( 
SAK-31796 should be the problem so I've reverted the change in endorsed. This PR probably resolves it, would be good if someone could confirm the solution.
> SAK-33728. Revert logger change from SAK-31796

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Magic 100x performance improvement as user goes through long assessment
> SAM-3325 avoid query count increasing as user advances through an assessment

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
> SAK-33724 - Disable bullhorns by default for the Sakai 12.0 release

- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-impl/src/bundle/ltiservice.properties
Be nice if this conversion bit could make it into Sakai 12
> SAK-33772 - Add fields for LTI 1.3 support

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
The onlymodification is on the first line: showing a warn instead of filtering code inside the 'if'.
All the other changes are just a big tabulation.
> SAK-33793 enabling submit as student feature for instructors

- samigo/samigo-app/src/webapp/jsf/author/item/tags.jsp
The tags selector needs this code to display the right translation.
> SAM-3338 Link to the right i18n folder for the tags javascript selector

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Ensures GradebookNG JavaScript works with browsers that do not implement 'findIndex'.
> SAK-33771 Fix GradebookNG in IE11

- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- library/src/morpheus-master/sass/modules/_toolmenu.scss
Submenu is shown floating on mobile below subsites toggler link
> SAK-33696 - Subsites don't show at all on mobile

- master/pom.xml
> SAK-33874 - Update minor versions for Sakai shared libraries

- content-review/api/src/main/resources/ContentReviewItem.hbm.xml
database camelcase to upper case
> SAK-33894 Change case on ContentReviewItem column names

- assignment/api/src/java/org/sakaiproject/assignment/api/conversion/AssignmentConversionService.java
- assignment/api/src/java/org/sakaiproject/assignment/api/conversion/messages.properties
- assignment/api/src/java/org/sakaiproject/assignment/api/conversion/messages_es.properties
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/Assignment12ConversionJob.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/Assignment12ConversionJobValidator.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/AssignmentConversionServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/README.md
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentConversionTest.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- Increase the limits of the woodstox parser
- component renames
- move regex predicates as class members
- job is now configurable
> SAK-33882 Assignment conversion increase limits

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
@frasese Would you mind to take a look? Thanks
> SAK-33876 (11.x) - Urkund missing link in the student's view

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
@frasese could you take a look? Thanks
> SAK-33876 - Urkund missing link in the student's view

- basiclti/basiclti-impl/src/bundle/ltiservice.properties
> SAK-33772 - Fix error in strings

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
We got this local fix on SAKAI 11.4 and also tested fix on sakai trunk
> SAK-33850 Making sure create site from archive is cancelled

- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
When you browse as instructor or student through tabs and do some actions navigation fails and send you to a history tab instead remain in same tab.
> SAK-33829 - Calendar tabs does not respect last tab used

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/cm/README.md
- jobscheduler/scheduler-component/src/webapp/WEB-INF/cm-components.xml
- Also removed an MembershipProcessor processor from the CM job
> SAK-33915 CM SIS CSV Loader Documentation

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/api/src/java/org/sakaiproject/assignment/api/persistence/AssignmentRepository.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
Submitted/Ungraded submission counts in the assignments list are not correct for non-electronic assignments
> SAK-33888 - Submitted/Ungraded submission counts in the assignments list are not correct for non-electronic assignments

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- changed the default to import as draft
- create new groups if existing groups don't exist already
- logic to properly import group assignments
> SAK-33924 Assignments import group assignments

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
Note that the link is not available when logged in as the admin user as this user does not have the calendar tool.
> SAK-32537 Add calendar link to user drop-down menu.

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_feedback_attachments.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Besides solving the refactor issue, I thought it was a good idea to extract to a different file a portion of code which is used on four different places, which is a nightmare to keep updated.
> SAK-33939 solved issues when showing feedback attachments to students

- kernel/kernel-impl/pom.xml
- kernel/kernel-impl/src/main/java/org/sakaiproject/config/impl/StoredConfigService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- cleaned up logging in StoredConfigService
> KNL-1586 Remove icu4j lib and use java 8 time

- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
- library/src/webapp/js/lessons-subnav.js
various details were wrong in the subnav code:
* didn't check for group access
* didn't check prereq quite right
* slightly wrong way of getting top level pages
> LSNBLDR-952; fix lessons subnav

- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
> LSNBLDR-952; cleanup low-level code; use canSeeAll rather than site.upd to see all pages

- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
> SAK-33960 Instructor is not able to see assignments of his group

- msgcntr/messageforums-app/src/webapp/js/forum_movethread.js
https://jira.sakaiproject.org/browse/SAK-31475
The modal window generated when electing to move conversations between topics/forums has some display issues. See the JIRA for screenshots.
> SAK-31475: Forums > move thread modal has display issues

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAM-3378
As requested on core team list.
> SAM-3378: document samigo.email.autoSubmit.errorNotification props in default.sakai.properties

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-33986
As requested.
> SAK-33986: document content.default.notification in default.sakai.properties

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/AssignmentConversionServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_students_details.vm
- webservices/cxf/src/java/org/sakaiproject/webservices/Assignments.java
- updated conversion to remove null/empty values
- there maybe other properties that need to be cleaned up but the following are addressed
- new_assignment_check_anonymous_grading
- prop_new_assignment_add_to_gradebook
> SAK-33950 Assignments updated logic for storing null/empty valued props

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- also removed MemoryService as it was unused
> SAK-33988 Assignments method getHttpAccess has no tx advice

- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/navigation/_breadCrumbs.scss
- library/src/morpheus-master/sass/modules/navigation/_skipnav.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm
The "Tool" word width was harcoded on CSS, this PR modifies the behaviour and adapts to every language not just english.
> SAK-33985 - Portal: Page reset link in conflict with the tool list (Mobile)

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
also updated AssignmentServiceConstants references as its now implicit
> SAK-34016 Assignment gradebook integration regression

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
https://jira.sakaiproject.org/browse/SAM-3275
Steps to reproduce and screenshot in the JIRA.
> SAM-3275: Published Copy > Settings > Save > doesn't warn if GB title conflict exists

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
https://jira.sakaiproject.org/browse/SAK-34012
> SAK-34012: cannot convert grade entry from points to percentages as instructor

- library/src/webapp/js/sakai-recorder.js
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
Lessons
If the placement is null just the tool link. Seems to work for both ways
taking direct and via lessons. Also fixed a CKEDITOR variable issue
taking via the link
> SAM-3182 - Test & Quiz Audio question fails to display when deployed via

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- library/src/webapp/js/headscripts.js
- site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/SiteManageConstants.java
- site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties
- site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages_es.properties
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/WEB-INF/requestContext.xml
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/css/GroupList.css
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html
This PR also includes a global function to allow loading libraries with the CDN version, independently of the tool and the framework used.
> SAK-34034 filtering members by group on siteinfo group management

- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
Once we added SameSite, the required POST back fails
due to the lack of a session cookie.  So we add the sakai.session
in the callback URL.
Unless KNL-1590 is installed, the following is also required
to make this work:
session.parameter.allow=true
> SAK-34032 - Add sakai.session to return url

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
https://jira.sakaiproject.org/browse/SAM-3218
See JIRA for more info and steps to reproduce.
> SAM-3218: leaving null due date but setting past retract date creates erroneous submisisons

- library/src/webapp-filtered/editor/ckeditor.launch.js
> SAK-34099 - CKEditor: Disable Summary option in Table Properties dialog

- tool/tool-tool/su/src/java/org/sakaiproject/tool/su/SuTool.java
- tool/tool-tool/su/src/webapp/su/main.jsp
https://jira.sakaiproject.org/browse/SAK-34069
> SAK-34069: Become User: View info is broken

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
> SAK-34107 - In resources, problems restricting visibility to subfolders

- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
> SAK-34087 - Preferences: When you hide a site it does not dissapear

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
The event is fired in the service - amended to contain the LRS
statement.
> SAK-39938 Removed extra submit event from AssignmentAction.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbStudentGradeInfo.java
- providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
This fixes regressions from SAK-33849 and SAK-32608
> SAK-39954 Gradebook CandidateDetailProvider regression

- chat/chat-tool/tool/src/webapp/jsp/room.jsp
Accessibility tip: don't use placeholder instead of a real label
> SAK-38347 make chat message label persistent and visible

- chat/chat-tool/tool/src/bundle/chat.properties
- chat/chat-tool/tool/src/webapp/jsp/room.jsp
- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
Not sure if you want to add a spinner @bjones86 ... This change removes onchange form submission to use an explicit Submit button
> SAK-38334 use Submit buttons instead of onchange

- chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java
- portal/portal-chat/tool/src/java/org/sakaiproject/portal/chat/entity/PCServiceEntityProvider.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PresenceHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- presence/presence-api/api/src/java/org/sakaiproject/presence/api/PresenceService.java
- sitestats/sitestats-impl/pom.xml
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
... with PresenceService.PRESENCE_SUFFIX
> SAK-39995 Replace magic string "-presence'

- library/src/morpheus-master/js/src/sakai.morpheus.short.url.js
- library/src/morpheus-master/sass/modules/tool/_base.scss
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageBody.vm
I've tested with aXe thanks to @ottenhoff and now it doesn't give any a11y issue on "Edit" link (now button)
> SAK-34093 - Ensure links that spawn dialogs indicate the fact

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/js/authoring.js
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
> SAK-39988 Assessment Settings: Better UI to select groups

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
This input value has been change from 'group' to 'GROUP' in tool but it hasn't been modified on the JS call yet
> SAK-40010 - Javascript toogle Group Submission is not working

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers https://jira.sakaiproject.org/browse/SAK-33343 by appending a "+" button to the existing "Create" button.
> SAK-33343 Allow 'create another' from the create grade item dialog

- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/base/_extendables.scss
> SAK-38356 - Ensure keyboard focus is indicated visually

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Better hide all the row that only the checkbox
> SAK-40016: Allow resubmision options appears for Non-electronic Submission Type when click label 'Allow Resubmission'

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/ImportQuestionsToAuthoring.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
https://jira.sakaiproject.org/browse/SAK-38439
The performance of copying questions from a question pool to a quiz is a little sluggish. In our testing, using a question pool of 25 questions, it took an average of ~19000 ms to copy all 25 questions from the pool to a quiz. The larger the number of questions imported, the longer it takes.
After the PR is applied, this same process using the same site, same quiz, and same 25 questions from the question pool reduced the processing time to an average of ~2800 ms.
> SAK-38439: Samigo > improve performance when copying questions from pool to quiz

- admin-tools/pom.xml
- admin-tools/src/java/org/sakaiproject/user/tool/UsersAction.java
- assignment/impl/pom.xml
- assignment/impl/src/java/org/sakaiproject/assignment/impl/SpreadsheetExporter.java
- assignment/tool/pom.xml
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- deploy/pom.xml
- gradebookng/tool/pom.xml
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- jobscheduler/scheduler-component-shared/pom.xml
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/cm/processor/BaseCsvFileProcessor.java
- kernel/kernel-impl/pom.xml
- kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/BasicConfigurationService.java
- lessonbuilder/tool/pom.xml
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- master/pom.xml
- profile2/impl/pom.xml
- profile2/impl/src/java/org/sakaiproject/profile2/conversion/ProfileConverter.java
- signup/tool/pom.xml
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/DownloadEventBean.java
- site-manage/site-manage-group-section-role-helper/tool/pom.xml
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
I tested this on the admin user import, worked great. Will add more testing to the test plan. This adds a lot of features that we could take advantage of but looks like minimal changes were needed.
> SAK-40025 - Update to opencsv 4.1

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java
SAK-40067: The averaged peer review grade is rounded down
> SAK-40067: The averaged peer review grade is rounded down

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Appears "Pass" or "Fail" when override a student's grade instead of the translation to different languages
> SAK-40061: Appears "Pass" or "Fail" when override a student's grade instead of the translation to different languages

- assignment/bundles/resources/assignment.properties
- assignment/bundles/resources/assignment_es.properties
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
SAK-40089: Group Grade text is hardcoded
> SAK-40089: Group Grade text is hardcoded

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
SAK-40064: Grades that have been overrided don't match with grades in Grade Report
> SAK-40064: Grades that have been overrided don't match with grades in Grade Report

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
SAK-34027: Error editing an assignment with Grade Scale Points after form validation error
> SAK-34027: Error editing an assignment with Grade Scale Points after form validation error

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
SAK-33852: Validation errors during add/edit assignment change some values
> SAK-33852: Validation errors during add/edit assignment change some values

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GbEvent.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GbRole.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/EventHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
Delivers https://jira.sakaiproject.org/browse/SAK-40103.
This PR aims to add many of the events previously generated by Gradebook Classes to GradebookNG.  It also adds a few new events based on some of the new features available in the tool.
The `EventHelper` serialises the data to match the `ref` originally generated by Gradebook Classic where possible.
> SAK-40103 Add event tracking to the GradebookNG tool

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
Also, catching occurrences of null placements on Rubrics to avoid screen errors.
> SAK-40177 NPE when linking test with rubrics on Lessons

- assignment/impl/src/java/org/sakaiproject/assignment/impl/conversion/AssignmentConversionServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentConversionTest.java
- assignment/impl/src/test/resources/sitegrp_asn.xml
- assignment/impl/src/test/resources/sitegrp_asn_content.xml
- assignment/impl/src/test/resources/sitegrp_asn_submission0.xml
- assignment/impl/src/test/resources/sitegrp_asn_submission1.xml
> SAK-40148 Assignments conversion for group assignments with SITE access

- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedAssessment.hbm.xml
Create sequence. It is a low risk change.
> SAK-40182: Duplicate use of oracle sequence in Samigo

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/EnrolmentsHandler.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_enrolments.vm
https://jira.sakaiproject.org/browse/SAK-40243
In Membership > My Official Course Enrolments, the table headers are clickable where the intention is to sort the table by the given column. However, the sorting doesn't work; the page is refreshed but the data (order) in the table remains unchanged.
> SAK-40243: Membership > My Official Enrolments > fix table sorting

- calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarService.java
- calendar/calendar-api/api/src/java/org/sakaiproject/calendar/cover/CalendarService.java
- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/PDFExportService.java
- calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/PDFExportServiceTest.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
We have added a new param for the PDF print view with the option matching ListView table order option
> SAK-33712 - Order events in calendar and print version doesn't match

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
SAK-40127: Instructor is not able to remove reviews in a peer assesment
> SAK-40127: Instructor is not able to remove reviews in a peer assesment

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/FirstNameComparatorGbUser.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- providers/component/src/webapp/WEB-INF/candidate-details.xml
- providers/component/src/webapp/WEB-INF/components.xml
- providers/userdetail/src/java/org/sakaiproject/user/detail/FallbackDetailProvider.java
Also addressed issue with CandidateDetailProvider - Student Number not
appearing in export
> SAK-40241 GradebookNG incorrect columns in custom export

- kernel/kernel-private/src/main/java/org/sakaiproject/springframework/orm/hibernate/AddableSessionFactoryBean.java
Replace Deprecated functions of Hibernate 4.X in favour of the supported functions
> SAK-40004 - Replace org.hibernate.dialect.function

- signup/impl/src/bundle/emailMessage.properties
- signup/impl/src/bundle/emailMessage_es.properties
- signup/impl/src/java/org/sakaiproject/signup/logic/SignupMeetingServiceImpl.java
Updated SignupMeetingServiceImpl.java with i18n capabilities
> SAK-40283 On signup, Calendar event create has hardcoded language strings

- content/README.md
- content/content-copyright/README.md
https://jira.sakaiproject.org/browse/SAK-39953
README's for content and content-copyright.
> SAK-39953: Resources > add README documentation for copyright options

- jobscheduler/pom.xml
- jobscheduler/scheduler-api/src/java/org/sakaiproject/api/app/scheduler/SchedulerManager.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/TriggerWrapperImpl.java
- jobscheduler/scheduler-component/pom.xml
- jobscheduler/scheduler-component/src/resources/event-log-purge.xml
- jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
- jobscheduler/scheduler-utils/pom.xml
- jobscheduler/scheduler-utils/src/java/org/sakaiproject/scheduler/util/AutoProvisionJobs.java
- jobscheduler/scheduler-utils/src/resources/sample.xml
> SAK-40327 Better auto provisioning of jobs/triggers.

- roster2/src/handlebars/navbar.handlebars
- roster2/src/webapp/js/roster.js
https://jira.sakaiproject.org/browse/SAK-40364
The HTML structure and some classes need to be updated to conform to the navBar used in all other Sakai tools; active tab has gray inner background (bug), is clickable (bug), and has hover state styles (bug).
This isn't as straight forward as with other tools because of Handlebars...
> SAK-40364: Roster > navBar needs updating for active tab styling

- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
- webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiScriptFindSitesByTitleTest.java
SAK-40258: Added method findSitesByTitle() in /sakai-ws. This is to get all site IDs for which the criteria fully or partially matches the title, description or skin.
> SAK-40258: Added method findSitesByTitle() in /sakai-ws.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
@payten not sure if this is best approach .....
> SAK-40431 strip line breaks from gradebook item name

- admin-tools/src/webapp/vm/user/chef_users_edit.vm
This reverts commit 8ae7605f4d114aaf9cb89f4af1eccfd001d642f2.
> SAK-34102 Revert "update chef_users_edit (#5701)"

- basiclti/basiclti-tool/src/webapp/vm/lti_content_delete.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
@josecebe and @mpellicer can you take a look? Seems like missing merge from 
https://jira.sakaiproject.org/browse/SAK-32360
> SAK-32360 11.x merge fixes

- basiclti/tsugi-util/pom.xml
- basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Constants.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13ConstantsUtil.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13JacksonUtil.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13JwtUtil.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/BaseJWT.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/BasicOutcome.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/Context.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/Endpoint.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchLIS.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchPresentation.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/ResourceLink.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/ToolPlatform.java
- basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13JJWTTest.java
- basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13ObjectTest.java
- basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13PKITest.java
This is the first of many code bits - this is new LTI 1.3 code and tests for that code.  It is low-risk.
> SAK-40474 Add Unit Tests and Utility Code for LTI 1.3

- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- master/pom.xml
- oss-parent/pom.xml
- pom.xml
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/Editor.java
- simple-rss-portlet/pom.xml
- userauditservice/pom.xml
> SAK-40417 Cleanup maven javadoc plugins

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
Refer to JIRA for stacktrace information. SAK-33087.
> SAK-33087 added nullcheck for when grade record doesnt exist

- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- basiclti/basiclti-impl/pom.xml
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_view.vm
- basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchPresentation.java
I am tired and hungry and going to Karaoke.
> SAK-40488 Initial commit of LTI 1.3 Launch

- podcasts/podcasts-api/src/java/org/sakaiproject/api/app/podcasts/PodcastService.java
- podcasts/podcasts-app/src/java/org/sakaiproject/tool/podcasts/podHomeBean.java
- podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/PodcastComparator.java
- podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/PodcastPermissionsServiceImpl.java
- podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/PodcastServiceImpl.java
- podcasts/podcasts-impl/src/webapp/WEB-INF/components.xml
org.sakaiproject.time.api.TimeService => org.sakaiproject.time.api.UserTimeService
ContentResource.getReleaseTime() => ContentResource.getReleaseInstant()
ContentResource.getProperties().getTimeProperty => ContentResource.getProperties().getInstantProperty
> SAK-40471 Podcast Time => Instant

- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
It can be the case that users don’t have the site.upd permission on My Workspace (My Home), this means that when they visit an LTI tool that attempts to patch it’s content it fails because they aren’t allowed to update the LTI tool.
This uses the DAO method which doesn’t do permission checks so it works for people without site.upd permission.
> SAK-40482 LTI copying doesn’t need site.upd

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Adds consistency to assignment attachments view fragement
> SAK-40386 Assignments macro to handle showing assignment attachments

- kernel/kernel-common/src/main/config/log4j.properties
The [JIRA](https://jira.sakaiproject.org/browse/SAK-40519) has links. 
This is a giant performance boost.
> SAK-40519 change Hibernate log to remove constant showWarnings calls

- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
- basiclti/basiclti-tool/src/webapp/vm/lti_content_delete.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/BltiExport.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
@josecebe @mpellicer I don't think the 11.x merge here was done correctly. I'm starting to see regressions from this.
https://jira.sakaiproject.org/browse/SAK-40487
This is a really, really difficult merge to get right because of how the code was re-formatted.
> SAK-40487 revert SAK-32360 from 11.x

- edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseManagementAdministration.java
- edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementAdministrationHibernateImpl.java
to remove some Hibernate calls when possible
> SAK-40518 add new addOrUpdateSectionMembership method signature 

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
Expected for the work in SAK-40489
> SAK-40494 add ajax=true to default bypass query list

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- if assignmentIds are null or empty return an empty List
- corrects the SQL grammar syntax issue when there are no assignments
> SAK-40277 eduservices improve getGradingEvents

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
minor change where if the gradebook has no grade and assignments has a grade (in the case of saving but not releasing) then use the grade in assignments.
> SAK-40546 Assignment submission grade if none in gradebook

- chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java
@ern This is related with Rubrics and JPA, would you mind to take a look?
Thanks! I've tested this changes and works fine.
> SAK-40491 Cannot delete chat messages

- library/pom.xml
- mailsender/tool/pom.xml
- master/pom.xml
- samigo/samigo-app/pom.xml
- simple-rss-portlet/pom.xml
This optimizes a little bit the deploy time and also supports the latest JDKs
> SAK-40004 - Maven War Plugin Updated

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentSupplementItemServiceImpl.java
- switch to AssignmentReferenceReckoner to get Assignment reference vs Entity creation
- simplify method
> SAK-40570 Assignment Model Answer showTo causing autoboxing NPE

- providers/jldap-mock/pom.xml
- providers/jldap-mock/src/java/edu/amc/sakai/user/UserEditStub.java
jldap-mock: org.apache.commons.lang.builder.* => org.apache.commons.lang3.builder.*
> SAK-40576 jldap-mock: lang3 builder

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
Big performance boost in course with many categories and items.
> SAK-40603 limit cells that get redrawn after each score item save.

- basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/LaunchJWT.java
- basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/NamesAndRoles.java
- basiclti/tsugi-util/src/java/org/tsugi/oauth2/objects/AccessToken.java
- basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13JavaTest.java
This is the initial implementation.
> SAK-40616 LTI 1.3 Names and Roles Service

- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSitePage.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageOverview.vm
When manage overview was originally written it used index 64 in SiteAction.
However, that index was taken in master and it needed to be changed to 65.
Also, fixed a couple of bugs with saving and canceling changes.
> SAK-40642 Manage overview bug fixes

- webjars/ckeditor-image2/pom.xml
> SAK-40624 Update version of ckeditor image2 in pom

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
- master/pom.xml
- search/search-impl/impl/pom.xml
- search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/PoiContentDigester.java
- search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/XLContentDigester.java
Tika 1.19 & poi 4.0.0
search: poi 3.17
> SAK-40715 Tika 1.19 & poi 4.0.0

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ToolItemRubricAssociation.java
The new method in ToolItemRubricAssociation will be used by all the other duplication cases (assignments, samigo..).
> SAK-40555 Rubric settings not kept for duplicated forums

- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/modules/access/_base.scss
- library/src/morpheus-master/sass/modules/more-sites/_base.scss
- library/src/morpheus-master/sass/modules/timeout-alert/_base.scss
https://jira.sakaiproject.org/browse/SAK-40323
Restyled the session timeout message to stand out better by adding a shadow and increasing the contrast of the portal mask. 
See https://jira.sakaiproject.org/browse/SAK-40323 for before and after screenshots.
> SAK-40323 Library: Restyled the session timeout to stand out better

- lessonbuilder/tool/src/webapp/js/folder-picker.js
This reverts commit 999fd9d16dbc51d911c4574239e15714da4e9e3d.
CC: @jesusmmp @mpellicer
> SAK-40515 Revert "SAK-40381: Lessons - Add Resources Folder with a sites with UTF-8 characters is shown wrong (#5843)"

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/Assignment.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookExternalAssessmentService.java
- edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradableObject.hbm.xml
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradebookAssignment.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/GradebookIfc.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java
- webservices/cxf/src/java/org/sakaiproject/webservices/Assignments.java
- Also introduced Lombok to the affected classes to reduce boilerplate
- this change introduces api changes
> SAK-40687 eduservices Add new EXTERNAL_DATA column

- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/EventWorksheet.java
https://jira.sakaiproject.org/browse/SAK-38441?attachmentOrder=desc 
The link is supposed to be an internal Excel document link, not a link to a file:// url.
> SAK-38441 Fix multiple event spreadsheet export

- signup/tool/src/webapp/js/newMeetingStep1.js
Check that radioUnlimitedAttendee element exists before trying to get its property.
> SAK-40764 Fix missing Location and Category fields in Signup Add screen

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
PR to fix "Cast Exception". (Low risk).
> SAK-40760: Another ClassCastException related to number of retakes

- kernel/api/src/main/java/org/sakaiproject/messagebundle/api/MessageBundleProperty.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/messagebundle/impl/CachingMessageBundleServiceImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/messagebundle/impl/MessageBundleServiceImpl.java
- kernel/kernel-impl/src/main/webapp/WEB-INF/messagebundle-components.xml
- kernel/kernel-impl/src/test/java/spring-hibernate.xml
Also fixes these minor issues:
- index SMB_SEARCH is too long
- TimerTask cleanup
> SAK-40839 MessageBundleService remove the use of HibernateDaoSupport

- common/pom.xml
Please do not merge this issue, it needs a discussion about some dependencies.
> SAK-40852 - Update some dependencies

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- rubrics/tool/src/main/frontend/imports/sakai-rubric-criterion-grading.html
- rubrics/tool/src/main/frontend/imports/sakai-rubric-grading-comment.html
- rubrics/tool/src/main/frontend/imports/sakai-rubric-grading.html
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreAttachmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ParameterUtil.java
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
- It requires to pass a new parameter (evaluatedItemId) all around the Rubrics structure to difference between users on the same screen.
- Each Rubric grading is a modal component, cloned the first time its called (a workaround to make CKeditor editable and avod ids clashing).
> SAK-40166 Allow rubric grading in Questions screen (Samigo)

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/TimedAssessmentRunnable.java
Also add ThreadLocal cleanup since threads are reused by SES
Logging clean up
Cover clean up
> SAK-40867 Samigo Timed Assessment move session logout to finally

- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
This is a PR against 12.x as the code in master has changed significantly.
> SAK-40863 12.x -- fix use of pushAdvisor in basiclti code

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
Very low risk PR. Thanks yun_fan@unc.edu
> SAK-40864: Regression: Questions tab and calculated questions: It shows wrong answers despite the answers are right

- rubrics/tool/src/main/frontend/imports/sakai-rubric-grading-comment.html
Making the id of each instance unique, allowing multiple instances of the same question and also cloing them.
This got lost at some point, but belonged to https://github.com/sakaiproject/sakai/pull/6168
> SAK-40899 Rubrics CKeditor on T&Q questions screen

- samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
Rubrics options will appear for these types:
- Short answer.
- Audio recording.
- File upload.
> SAK-40174 Only allow Rubrics for T&Qs manually graded questions

- signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java
Fix wrong capitalization in participant and wait lists
> SAK-40939 - Signup - Wrong capitalization in participant/wait lists

- basiclti/basiclti-blis/src/java/org/sakaiproject/lti/entityprovider/LTIEntityProvider.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiBLTIUtilTest.java
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
Second try at an independent PR
> SAK-40954 - Encrypt the private keys whilst at rest

- basiclti/README_13.md
- basiclti/basiclti-impl/src/bundle/ltiservice.properties
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
Also add a readme and clean up a message.
> SAK-40994 - Fix auto-set of allow radio buttons

- master/pom.xml
MariaDB j 2.3.0
Mysql j 5.1.47
> SAK-40993 MariaDB j & MySQL j

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbStudentGradeInfo.java
I have added the value to "studentDisplayId" so that the import does not fail.
> SAK-41015: Add studentDisplayId value

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapperComparator.java
> SAK-40999 - Errors sorting announcements with null values in date attributes

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentBeanie.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ContentsDeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/SectionContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ActionSelectListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/UpdateAssessmentQuestionsOrder.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SaCharCountListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreAttachmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
- refactor to use generics to solve the class cast issue
> SAK-40605 Samigo class cast on update order button for published assessments

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScorePagerListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/ResetQuestionScoreListener.java
...when grading questions and sorting by group
> SAK-40770 Samigo: Score value not updated (HARD)

- lessonbuilder/tool/src/webapp/js/show-page.js
Shown title by default, that field will be hidden if user selects a file, respecting the rest of the functionality added by SAK-37391
> SAK-38434 Lessons: specify URL title

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java
I tried to solve this in a way that will support different Locales
> SAK-40736 Wrong grade display with >999 values

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateOrganize.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyAllAuthoredMsg.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyFullTextForOne.jsp
https://jira.sakaiproject.org/browse/SAK-40998
Fix issue that was letting students see forums and topics they shouldn't see on the Forums view.
> SAK-40998 Hide forums/topics student has no permissions in

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
@ern Please take a look at this, thanks!
> SAK-41034 make findSubmissionForUser method Transactional to avoid crash

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
Also removed unused variables, updated some loops and reorganized code.
> SAK-39960 remove answer button breaks navigation

- reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/FormProducer.java
When you try to reset your password and that email doesn't exist as a user you get an error message (which is good) and a message as if all has been ok and a mail was sent to that email (which is wrong)
> SAK-41035 - Reset password shows both messages: Error and ok

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
> SAK-40897 "Save forum and add topic" redirection wasn't working

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
Updating last PR #6352 checking with isEmpty()
> SAK-41049: Some null errors in velocity on assignments

- gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css
https://jira.sakaiproject.org/browse/SAK-41060
> SAK-41060: Drop highest/lowest info labels not aligned with other labels in category header

- signup/api/src/java/org/sakaiproject/signup/hbm/SignupTimeslot.hbm.xml
- signup/api/src/java/org/sakaiproject/signup/logic/SignupMeetingService.java
- signup/api/src/java/org/sakaiproject/signup/model/SignupAttendee.java
- signup/impl/src/java/org/sakaiproject/signup/logic/SignupMeetingServiceImpl.java
- signup/impl/src/webapp/WEB-INF/components.xml
- signup/tool/pom.xml
- signup/tool/src/bundle/messages.properties
- signup/tool/src/bundle/messages_es.properties
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/DownloadEventBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/EventWorksheet.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/AttendeeWrapper.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupUIBaseBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/OrganizerSignupMBean.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/AddAttendee.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/AddWaiter.java
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/organizer/action/RemoveWaiter.java
- signup/tool/src/webapp/css/signupStyle.css
- signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
Commit to register and show the date and time in which a student signed
up to event. This information is also shown in exported Excel files.
Order in both Inscription (by name) and Waiting (by list_index) lists is
not modified.
> SAK-41021 - Date/Time screens for Signup events: confirmed and waitlisted

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
https://jira.sakaiproject.org/browse/SAK-40826
> SAK-40826 modify category calculations based on whether user can see non-released items

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java
- lessonbuilder/tool/src/webapp/templates/ShowItem.html
I've added the namespaced CSS to the tools added by Lessons as iframe. As long as this tools are added based on just their URL itself, tool name is not accessible from Lessons Tool.
> SAK-40979 - Wrong CSS styles in Forums from Lessons

- .mvn/wrapper/MavenWrapperDownloader.java
- .mvn/wrapper/maven-wrapper.properties
- README.md
- mvnw
- mvnw.cmd
This will download a copy of maven into `~/.m2/wrapper/` if you don't have a copy of maven to use. This makes it simpler for people to get started with mvn/sakai.
> SAK-40946 Add maven wrapper to Sakai

- config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/siteemacon/siteemacon.properties
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/SiteEmailNotificationDragAndDrop.java
https://jira.sakaiproject.org/browse/SAK-41055
`IndexOutOfBoundsException` generated when uploading a file to the top-level folder in Drop Box and enabling email notifications for the upload. Steps to reproduce in the JIRA.
> SAK-41055: Drop Box > IndexOutOfBoundsException when uploading to top-level folder with email notification

- content/content-bundles/resources/content.properties
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
https://jira.sakaiproject.org/browse/SAK-41092
Users have expressed some desire to have more options in the "Highlight individual Drop Boxes with recent changes" drop down. It's trivial to address this request.
> SAK-41092: Drop Box > add more highlight options

- message/message-api/api/src/java/org/sakaiproject/message/api/MessageHeader.java
- message/message-api/api/src/java/org/sakaiproject/message/api/MessageHeaderEdit.java
- message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
MessageHeader: Instant getInstant();
MessageHeaderEdit: setInstant(Instant instant);
> SAK-41085 @deprecated Time => instant

- signup/tool/src/java/org/sakaiproject/signup/tool/downloadEvents/EventWorksheet.java
- signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
Changes for rendering purpouses
> SAK-41084 - Clicking on the meeting title displays a stack trace

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementWrapperComparator.java
Commit to fix the compare method with String variables.
> SAK-41124 - Errors sorting announcements with null values in string attributes

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
... hide move right for the rightmost.
> SAK-40644 Hide move left for leftmost gb item and

- lessonbuilder/tool/src/webapp/js/show-page.js
Considering the sloppy way the html was being generated, I wanted to fix the bug avoiding lines duplication and unnecessary if/else cases. Let me know if anybody thinks this could be improved.
> SAK-41116 Don't wipe out item name for file uploads on Lessons

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Icons won't appear on the initial screen.
> SAK-41174 Solve performance problem in Samigo related to Rubrics

- rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/RWikiServlet.java
- rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/service/impl/PopulateServiceImpl.java
> SAK-41179 Check create permission in the site wiki before attempting to create subspace default pages

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
> SAK-41198 Don't hide the target site's top level folder

- calendar/calendar-tool/tool/src/webapp/velocity.properties
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewWeek.vm
Looks like the idea here was good but the logic was incorrect, tested on a lot more calendar events
> SAK-41194 - Calendar: Week view not displaying calendar table correctly

- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewDay.vm
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
> SAK-40977 - Events not appearing in calendar with day view

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java
Regression caused by SAK-40605
> SAK-41350 Show Rubrics tab when grading students

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CategoryDefinition.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
- gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css
This reverts commit e4798a5b738a7f85656bba3d23b09094240e3abc from 12.x
> Revert "SAK-33109 display total points of category (#6146)"

- reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.java
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/impl/jobs/CheckAccountsJob.java
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/impl/jobs/CheckValidations.java
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
CheckStyle: public void setvalidationReceived => public void setValidationReceived
Lombok account-validator-impl @Setter
> SAK-41351 AccountValidator ValidationLogic clean up

- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewWeek.vm
I hope it's okay to remove that second vector stuff.  It seemed kind of weird and unnecessary.  And why was it only on page 1 and 3?
> SAK-41323 Calendar remove extraneous code while building the Weekly view

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
> Instructor sees "Sections you are a member of" instead of just "Sections"

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- jobscheduler/scheduler-api/src/java/org/sakaiproject/api/app/scheduler/JobBeanWrapper.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutoRun.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutowiredJobBeanWrapper.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutowiringSpringBeanJobFactory.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/JobBeanWrapperRegistrar.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/JobDetailWrapperImpl.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SpringJobBeanWrapper.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SpringStatefulJobBeanWrapper.java
- jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java
- samigo/samigo-pack/src/webapp/WEB-INF/components.xml
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/AutoSubmitAssessmentsJob.java
- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiJob.java
Can be configured with:
startSchedulerDelayMinutes@org.sakaiproject.api.app.scheduler.SchedulerManager=5
> SAK-41389 Job Scheduler delay starting jobs until sakai startup completes

- basiclti/basiclti-blis/src/bundle/blis.properties
- basiclti/basiclti-blis/src/bundle/blis_eu.properties
- basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
- basiclti/basiclti-tool/src/bundle/ltitool.properties
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
- basiclti/basiclti-tool/src/webapp/vm/lti_content_insert.vm
- Use the same approach everywhere we need to know whether this is a 1.1 or 1.3 launch.
- Flow breakage in the CKEditor integration due to features added between 12 and 19.
- Typo in OIDC path isoidc -> imsoidc
- window.close link fails does not work after new window opened from ckeditor page returns.
> SAK-41404 - Fix small issues in Sakai 19 with LTI 1.1 and LTI 1.3

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
This is another version of #6570, only merge one of them.
> SAK-41362: Checkmark assignments only works on English language

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
Move the loop checking code above the getCalendarReferences() call since that would trigger more looping.
Add a null check to prevent NPE
> SAK-40350 Calendar subscribing to itself can loop

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading.js
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
SAK-41464 Fixed Forums rubric grading
SAK-41470 Fixed attribute name
> SAK-41465 Fixed override selector

- calendar/calendar-impl/impl/pom.xml
- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
- calendar/calendar-summary-tool/tool/pom.xml
- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/CalendarBean.java
- calendar/calendar-tool/tool/pom.xml
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventEntityProvider.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- chat/chat-impl/impl/pom.xml
- chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java
- chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatMessageEntityProvider.java
- chat/chat-tool/tool/pom.xml
- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/DecoratedChatChannel.java
- citations/citations-impl/impl/pom.xml
- citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/BaseCitationService.java
- citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/NestedCitationValidator.java
- common/archive-impl/impl2/pom.xml
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/ArchiveService2Impl.java
- common/common-composite-component/pom.xml
- common/common-composite-component/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonManagerImpl.java
- commons/api/pom.xml
- commons/api/src/java/org/sakaiproject/commons/api/datamodel/Comment.java
- commons/impl/pom.xml
- commons/impl/src/java/org/sakaiproject/commons/impl/CommonsSecurityManagerImpl.java
- commons/tool/pom.xml
- commons/tool/src/java/org/sakaiproject/commons/tool/entityprovider/CommonsEntityProvider.java
calendar, chat, citations, common, commons,
> SAK-41467 commons-lang => commons-lang3

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-association.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-creator-name.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-site-title.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-manager.js
- webcomponents/src/webapp/sakai-i18n.js
https://jira.sakaiproject.org/browse/SAK-41437
Fixed site title and creator name under Edge
> SAK-41459 Fixed translation loading delay

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
https://jira.sakaiproject.org/browse/SAK-41479
> SAK-41479 Adjusted height and margins for criteria

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css
Makes the section and student number column widths property
configurable
> SAK-41380 Adjusted width of gb sections column

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-edit.js
https://jira.sakaiproject.org/browse/SAK-41485
> SAK-41485 Use server supplied new rubric title

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
https://jira.sakaiproject.org/browse/SAK-41486
> SAK-41486 Rubrics: Reorder ratings not saved correctly

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
https://jira.sakaiproject.org/browse/SAK-41492
> SAK-41492 Untranslated string in Rubrics student comment

- samigo/samigo-app/src/webapp/jsf/shared/removeMedia.jsp
- samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
Javascript error when a student is removing a uploaded file and time remaining is out
> SAK-41483: Test & Quizzes: Javascript error when a student is removing a uploaded file and time remaining is out

- roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://jira.sakaiproject.org/browse/SAK-33429
> SAK-33429 Set and unset email correctly in roster

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
Issues addressed are:
- Comments were never being saved
- jQuery Dialogue and CKEditor performance issue
- confusing button labels
> SAK-41436 Rubrics Samigo comments not being saved

- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- gradebookng/tool/src/webapp/styles/gradebook-shared.css
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-preview-button.js
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswer.jsp
https://jira.sakaiproject.org/browse/SAK-40310
> SAK-40310 Adding rubric preview back in for students

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SectionActivityListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/util/ContextUtil.java
- Extracting common method to order maps by value
- Adding eid to avoid confusion, like requested
> SAK-40020 Students with the same name don't appear in exceptions list

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-button.js
https://jira.sakaiproject.org/browse/SAK-41529
> SAK-41529 If no tool association can be found, hide the rubric button

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-button.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics.js
https://jira.sakaiproject.org/browse/SAK-41532
> SAK-41532 Readded instructor override for hidden rubric

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-student.js
https://jira.sakaiproject.org/browse/SAK-41529
> SAK-41529 Re-added assignment tool graded item support

- samigo/samigo-app/src/webapp/js/samigo-global.js
Ids formatting changed with the jsf update
> SAK-41534 Matrix survey allow one answer per column fix

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- rubrics/impl/src/main/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-41566
> SAK-41566 Cache the has associated rubric call

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-41590
> SAK-41590 Add Sakai property to enable column resizing in Gradebook

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
Disable CKEditor launch for criteria with no comments.
> SAK-41481 Enable rubric comment pointer for active comments.

- library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-app/pom.xml
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
Hard version for SAK-41562, will save a lot of tears of the future visitors of PrivateMessagesTool.java, and it reduces the technical debt.
Soft version of this PR available here #6717
> SAK-41562 Forums problems sorting private messages

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-preview-button.js
https://jira.sakaiproject.org/browse/SAK-41620
> SAK-41620 Added test for association being defined

- content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
Responses from Turnitin are not currently logged. They will be needed for troubleshooting
> TII-256 - Log responses from Turnitin in the TurnitinOC Provider

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
Besides tabulation, there are two changes:
- Avoid checking wrong assignment reference.
- Set access type group.
> SAK-41624 Solve issue with lessons, assignments and groups

- content-review/impl/dao/src/main/java/org/sakaiproject/contentreview/dao/ContentReviewItemDao.java
The distinct Hibernate projection was not returning unique siteIds
> SAK-41337 fix the grouping so we get unique site ids

- portal/portal-api/api/pom.xml
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/BullhornData.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/BullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AbstractBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AddAssignmentBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AnnouncementsBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/CommonsCommentBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendConfirmBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendIgnoreBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendMessageBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendRequestBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendStatusBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/GradeAssignmentBullhornHandler.java
- portal/portal-impl/impl/src/bundle/bullhorns.properties
- portal/portal-service-impl/impl/pom.xml
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
- portal/portal-service-impl/impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-41633
> SAK-41633 Refactor bullhorns event handlers

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/CommentsProducer.java
Page permissions shouldn't be checked if anonymous setting is true
> SAK-41607 Lessons : anonymous comments are showing user

- chat/chat-tool/tool/pom.xml
- jsf2/pom.xml
- master/pom.xml
- msgcntr/messageforums-app/pom.xml
- samigo/samigo-app/pom.xml
This is not tested yet, set WIP label.
> SAK-41647 Upgrade JSF to 2.3.9

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Includes more cleanup and logic updates of PrivateMessagesTool.java
> SAK-41569 Messages / Advanced search date range end date issue

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-41628
> SAK-41628 Console errors when entering grade for student

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
It might be preferable to create a specific method for this, let me know if I should do it that way.
> SAK-41640 Cancel button should go back to list

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
https://jira.sakaiproject.org/browse/SAK-41642
> SAK-41642 setGroups expects group references, not ids

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.java
https://jira.sakaiproject.org/browse/SAK-41637
> SAK-41637 Disable uncalculable items during bulk edit

- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java
> SAK-40947 Signup : pass current start date to custom timeslots

- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MySearch.java
Small cleanup in MyPrivacy too.
> SAK-41664 Profile2: Issues with IconWithClueTip component

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
The issue was in the query logic, you need at least one field to search by date and that's not correct.
> SAK-41570 Messages / Advanced search error

- library/src/morpheus-master/sass/modules/connection-manager/_base.scss
Adjust diff settings in Github to see the real changes.
> SAK-41684 fix background as background-image was not overriding

- commons/tool/src/webapp/WEB-INF/templates/comment.hbs
- commons/tool/src/webapp/WEB-INF/templates/post.hbs
- commons/tool/src/webapp/js/commons_utils.js
- library/src/morpheus-master/js/src/sakai.morpheus.connection-manager.js
- library/src/morpheus-master/js/src/sakai.morpheus.profile.popup.js
- library/src/morpheus-master/sass/modules/connection-manager/_base.scss
- library/src/morpheus-master/sass/modules/profile-popup/_base.scss
- library/src/templates/connection-manager-searchresult.hbs
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/profile-popup.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/connection-manager.vm
Also, improved portal profile popup and tool integrations. Made it
all more consistent.
> SAK-41727 Improved styling on ConnectionManger

- library/pom.xml
- library/src/morpheus-master/sass/modules/editor/_base.scss
- library/src/webapp/js/headscripts.js
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
This should be broken while populating the webjar library in the maven repos.
> SAK-41729 - WebJars: Upgrade CKEDITOR from 4.11.3 to 4.11.4

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
https://jira.sakaiproject.org/browse/SAK-40899
> SAK-40899 Give rubric comment popovers unique ids

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
https://jira.sakaiproject.org/browse/SAK-41741
> SAK-41741 Made student rubric comment view ids unique

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
- samigo/samigo-app/src/webapp/js/samigo-global.js
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://jira.sakaiproject.org/browse/SAK-41506
> SAK-41506 Fixed point finetuning in Samigo questions view

- README.md
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Corrected spelling nexprev, 2 files
> SAK-40908 Corrected spelling nexprev

- site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupImportStep1.html
SAK-41764 : We want to replace a hard-coded label with a property.
> SAK-41764 - internationalize some hard coded strings in Group Bulk Import

- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
that contains a private LTI tool. The new behavior copies the LTI tool
while the old behavior was an NPE
> SAK-41721 this fixes the scenario where an admin user duplicates a site

- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
Just removing the initial check for null, the other changes are just indentation.
> SAK-41750 Sitestats: fix report NPE (who -> custom)

- samigo/samigo-app/src/webapp/jsf/index/mainIndex.jsp
Tests & Quizzes tool returns all submission list in the course when asked to open with student profile. If there is no problem with this few students, there is a problem with a certain number of students (such as 200 and greater) with serious performance problems and some students cannot take the exam.
> SAK-41701 - Performance problem in Tests & Quizzes tool

- lessonbuilder/api/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDao.java
- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/PagePickerProducer.java
https://jira.sakaiproject.org/browse/SAK-41723
Top level page order should be the same as the order of the Lessons
tools in the tool menu
> SAK-41723 Ensure correct order of top level pages

- basiclti/tsugi-util/src/java/org/tsugi/pox/IMSPOXRequest.java
This was originally reported in tsugi-util  https://github.com/tsugiproject/tsugi-util/pull/4
> SAK-41782 - Accept all possible proper mimetypes for XML

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-41854
> SAK-41854: default properties for SAK-40018

- content-review/impl/turnitin-oc/README.md
- content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
It currently returns true; i.e. it accepts all files.
Bryan Holladay has listed the DEFAULT_ACCEPTABLE_FILE_EXTENSIONS, and DEFAULT_ACCEPTABLE_MIME_TYPES; they just need to be compared against
> TII-269 - TurnitinOC - implement isAcceptableContent

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Also, ensure that add due to calendar option is checked if the calendar
event has been imported.
> SAK-40339 Made master checkbox trigger option link

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm
Also, added help icon to merge data screen.
Also, changed help icon to pointer cursor.
> SAK-40339 Fixed case of null announcement id

- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
> SAK-41917: Poor description in column titles in assignment lists

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AnnouncementsBullhornHandler.java
Also, fixed bullhorn alert around missing site tool
Also, moved some components.xml stuff into annotations
Also, set the checkbox for announcements
> SAK-40339 Fixed missing channel error

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java
- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/bundles/resources/assignment.properties
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment_honor_pledge.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
I'd like to be reviewed not only the code and functionalities, but also the default messages shown and the related properties. Thanks!
> SAK-41821 Assignments : student progress bar and confirmation screen

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
Also included accessibility aria label for adding feedback attachments
button
> SAK-41926 Assignments scaled point resulting in error during grading

- msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/permissions/addGroupsUsers.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
- podcasts/podcasts-app/src/webapp/podcasts/podAdd.jsp
- podcasts/podcasts-app/src/webapp/podcasts/podDelete.jsp
- podcasts/podcasts-app/src/webapp/podcasts/podFeedRevise.jsp
- podcasts/podcasts-app/src/webapp/podcasts/podOptions.jsp
- podcasts/podcasts-app/src/webapp/podcasts/podRevise.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
so any tool needs to use a different accesskey
> SAK-41985 accesskey c is reserved for the portal 'jump to content' 

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Also fix issue preventing updates on stored scores (69.225 in database not matching 69.22 from UI)
> SAK-42001 round student scores when scaling the item grade points. 

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Solved error on log
3-Jun-2019 02:55:53.116 ERROR [http-nio-20113-exec-7] org.sakaiproject.tool.assessment.services.GradingService.getLastSubmittedAssessmentGradingByAgentId 
java.lang.NullPointerException
at org.sakaiproject.tool.assessment.facade.AssessmentGradingFacadeQueries.getLastSubmittedAssessmentGradingByAgentId(AssessmentGradingFacadeQueries.java:1055)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
> SAK-41923: Gradebook: Error on log when an assessment with last score is marked required on lesson builder

- sitestats/server_wide_stats.md
https://jira.sakaiproject.org/browse/SAK-41974
Supplemental to #7032
> SAK-41974: property name change in documentation

- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
- msgcntr/messageforums-app/src/webapp/js/forumTopicThreadsSorter.js
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
Remove duplicate button and translate button.
> SAK-42018: Remove duplicate button and translate button

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
I would like someone more test this one before merge. Thanks!
> SAK-42017: Too much time while loading gradebookNG

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
> SAK-42084: Remove condition

- mailarchive/mailarchive-impl/impl/src/java/org/sakaiproject/mailarchive/impl/BaseMailArchiveService.java
Tested locally with telnet/smtp
> SAK-41717 second part of fix also clean the plain-text sent by mail client

- library/src/morpheus-master/js/src/sakai.morpheus.footer.js
- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/modules/_footer.scss
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/bundle/sitenav_ca.properties
- portal/portal-impl/impl/src/bundle/sitenav_es.properties
- portal/portal-impl/impl/src/bundle/sitenav_eu.properties
- portal/portal-impl/impl/src/bundle/sitenav_tr_TR.properties
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm
https://jira.sakaiproject.org/browse/SAK-41988
To address accessibility issues outlined in SAK-41988, I have converted my custom footer info panel to use a Bootstrap Popover. 
Please see SAK-41988 for updated screenshots.
> SAK-41988 Changed the footer info popover from a custom panel to a Bootstrap Popover to address accessibility issues

- admin-tools/src/webapp/vm/archive/chef_archive-batch.vm
- admin-tools/src/webapp/vm/archive/chef_archive.vm
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm
- mailarchive/mailarchive-tool/tool/src/webapp/vm/mailarchive/chef_mailbox-List.vm
- roster2/tool/src/handlebars/overview.handlebars
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
Standardized buttons by changing main action buttons from colorless to blue.
https://jira.sakaiproject.org/browse/SAK-42037
> SAK-42037 Switch standardized primary and secondary buttons

- citations/citations-tool/tool/src/webapp/vm/citation/_listNestedCitations.vm
- citations/citations-tool/tool/src/webapp/vm/citation/import_citations.vm
- content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_select.vm
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsPanel.html
- rubrics/tool/src/main/frontend/webcomponents/sakai-item-delete.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-list.js
- samigo/samigo-app/src/webapp/jsf/author/createAssessment_title.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/downloadFileSubmissions.jsp
https://jira.sakaiproject.org/browse/SAK-42050
Changed primary action buttons to blue.
> SAK-42050 ﻿Resources, Gradebook, Tests and Quizzes, Rubrics standardizing primary action buttons

- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
- web/web-portlet/src/java/org/sakaiproject/portlets/PortletIFrame.java
- web/web-tool/tool/src/java/org/sakaiproject/web/tool/IFrameAction.java
I missed a few changes in vm files by accident :)
> SAK-42105 Configuration for browser feature policy in iframes part 2

- msgcntr/messageforums-app/src/webapp/css/msgcntr.css
- msgcntr/messageforums-app/src/webapp/js/forum.js
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
Commit to show the "Mark as read" icon and update unread messages count
in the conversation.
> SAK-42096 - Mark as read message icon not displaying in forums

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
> SAK-41929 - Rubrics forums: Preview doesn't work in some cases

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
Avoid to set 0% to a weighted category.
> SAK-41810: Error with Extra point if there is a category 0%

- content/content-tool/tool/src/bundle/helper.properties
- content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
Current resource picker:
Resource picker after the changes:
> SAK-42170 Resource picker:  UI improvements

- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-42131
> SAK-42131 Add later gb item rubric associations to cache

- polls/tool/src/webapp/templates/voteAdd.html
- polls/tool/src/webapp/templates/votePolls.html
- syllabus/syllabus-app/src/webapp/syllabus/edit_redirect.jsp
Standardized primary headers in Syllabus, Web content, Messages, Polls -> JIRA link https://jira.sakaiproject.org/browse/SAK-42103
> SAK-42103 Creating consistent page headers for Syllabus, Web content, Messages, Polls

- citations/citations-servlet/servlet/src/webapp/vm/compact.vm
- citations/citations-tool/tool/src/webapp/vm/citation/new_resource.vm
- msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfCompose.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfMessageReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfMessageReplyThread.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfMsgRevise.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumSettings.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/moveThreadPicker.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/topic/dfTopicSettings.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgHpView.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
- signup/tool/src/webapp/signup/newMeeting/assignStudents.jsp
- signup/tool/src/webapp/signup/newMeeting/step2.jsp
- signup/tool/src/webapp/signup/signupMeetings.jsp
Changing banners based on extendables file. JIRA link: https://jira.sakaiproject.org/browse/SAK-42123?filter=-1
> SAK-42123 standardizing banners for SWITCH in MessageCenter, Signup, and Citations

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
https://jira.sakaiproject.org/browse/SAK-42167?filter=-1
> SAK-42167 Announcement add check for #notify to prevent errors in MOTD

- profile2/tool/src/java/org/sakaiproject/profile2/tool/components/IconWithClueTip.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.java
Looks like some code that was never cleaned up back from issues
SAK-30866
and
SAK-38386
> SAK-41888 - Profile: Stacktraces in Wicket Debug Mode

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
Error messages must be thrown by gradebookng-tool
> SAK-41863: Gradebook: Some exceptions are hardcoded in English

- lessonbuilder/tool/src/webapp/templates/AssignmentPicker.html
- lessonbuilder/tool/src/webapp/templates/BltiPicker.html
- lessonbuilder/tool/src/webapp/templates/Checklist.html
- lessonbuilder/tool/src/webapp/templates/CommentGradingPane.html
- lessonbuilder/tool/src/webapp/templates/FolderPicker.html
- lessonbuilder/tool/src/webapp/templates/ForumPicker.html
- lessonbuilder/tool/src/webapp/templates/LtiImportItem.html
- lessonbuilder/tool/src/webapp/templates/PagePicker.html
- lessonbuilder/tool/src/webapp/templates/Preview.html
- lessonbuilder/tool/src/webapp/templates/QuestionGradingPane.html
- lessonbuilder/tool/src/webapp/templates/QuizPicker.html
- lessonbuilder/tool/src/webapp/templates/Reorder.html
- lessonbuilder/tool/src/webapp/templates/ShowItem.html
- lessonbuilder/tool/src/webapp/templates/ShowPage.html
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
https://jira.sakaiproject.org/browse/SAK-42122
Replaced various banners in rsf, lessonbuilder, and portal with new banners created for SWITCH in SAK-41866. Also removed some unnecessary inline styles attached to the banners.
> SAK-42122 Implementation of standardized banners in Portal, RSF, and Lessonbuilder

- admin-tools/src/webapp/vm/memory/chef_memory.vm
https://jira.sakaiproject.org/browse/SAK-42055
Changed file so that the memory site in home will only have one primary button instead of two.
> SAK-42055 admin-tools: Standardizing buttons

- lessonbuilder/tool/src/webapp/templates/BltiPicker.html
- library/src/webapp/js/headscripts.js
Make the height be 80% of the viewable window.
Make the background partially opaque.
> SAK-42243 - Make lessons LTI modals prettier.

- basiclti/basiclti-portlet/src/webapp/edit.jsp
- basiclti/basiclti-portlet/src/webapp/editreset.jsp
- basiclti/basiclti-tool/src/webapp/vm/lti_content.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_content_config.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_content_delete.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_content_insert.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_error.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_link_add.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_link_remove.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_test.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_delete.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_system.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_view.vm
- basiclti/basiclti-tool/src/webapp/vm/lti_top_refresh.vm
- basiclti/web-ifp/src/bundle/vm/edit.vm
- basiclti/web-ifp/src/bundle/vm/main.vm
- chat/chat-tool/tool/src/webapp/jsp/deleteRoomConfirm.jsp
- chat/chat-tool/tool/src/webapp/jsp/deleteRoomMessagesConfirm.jsp
- chat/chat-tool/tool/src/webapp/jsp/editRoom.jsp
- chat/chat-tool/tool/src/webapp/jsp/room.jsp
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-association.js
https://jira.sakaiproject.org/browse/SAK-42177
Replaced various banners in rubrics, basicLTI, and chat with new banners created for SWITCH in SAK-41866. Also removed some unnecessary inline styles attached to the banners.
> SAK-42177 Implementation of standardized banners in Rubrics, BasicLTI, and Chat

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
- site-manage/site-manage-impl/impl/src/webapp/WEB-INF/components.xml
Also in this PR is some updated logic during import in SiteManage:
- use try catch with security advisor
- import will clear state from thread
> SAK-42234 Forums Replace data during forum import caused InvalidDataAccessApiUsageException

- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://jira.sakaiproject.org/browse/SAK-42263
Regression introduced by https://jira.sakaiproject.org/browse/SAK-34741
Stack trace produced when going to the 'Questions' tab for any published quiz. Steps to reproduce and copy of the stack trace in the JIRA.
> SAK-42263: samigo > published quiz > scores > questions > bug report

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- calendar/calendar-bundles/resources/calendar.properties
- calendar/calendar-bundles/resources/calendar_es.properties
- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/CalendarBean.java
- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/EventSummary.java
- calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/calendar.jsp
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- calendar/calendar-util/util/src/java/org/sakaiproject/util/CalendarUtil.java
With this commit, information is added to the calendar event for an assignment to show the open date
> SAK-42215 - Lack of information in calendar event for assignment

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Commit to stop using 'grade_no_submission_default_grade' property
> SAK-40353 - Rare behaviour when applying a grade major than maximum grade

- roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
The issue is complex and I have doubts about this PR and the solution, I think having the problem is better than the solution.
> SAK-42137 - Name pronunciation feature: Profile & Roster cache issues

- library/pom.xml
- profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileLogicImpl.java
- profile2/tool/pom.xml
- profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.html
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.java
This has not been tested on a real IOS device with Safari, waiting for testing results.
According to W3CSchool, Safari supports WAV as mime-type.....
https://www.w3schools.com/html/html5_audio.asp
> SAK-42273 - Profile: Update name pronunciation to support Safari / iOS

- announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/AnnouncementObserver.java
- announcement/announcement-impl/impl/src/webapp/WEB-INF/components.xml
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
This commit adds a cache for announcement that improves performance accessing to messages.
> SAK-42188 - Improve Announcement performance

- admin-tools/src/bundle/sites.properties
- admin-tools/src/webapp/vm/sites/chef_sites_edit_tool.vm
> SAK-42320 - Admin tools: Better UI to select a tool for a page

- admin-tools/src/webapp/vm/sites/chef_sites_edit.vm
Updated classes to bootstrap
Before:
After:
> SAK-42355 - Admin Workspaces sites radio button spacing

- lessonbuilder/tool/src/webapp/templates/BltiPicker.html
https://stackoverflow.com/questions/1202079/prevent-jquery-ui-dialog-from-setting-focus-to-first-textbox
> SAK-42268 - Move focus out of iframe dialog

- rubrics/api/src/main/bundle/org/sakaiproject/rubrics/bundle/Messages.properties
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-readonly.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-readonly.js
Add translation for rubric criterion titles (SAK-41965)
> Add translation for rubric criterion titles (SAK-41965)

- library/src/morpheus-master/sass/modules/more-sites/_base.scss
If true, then make the last button ("On") appear activated with the background color.
> SAK-42402 portal auto favorite button displaying opposite

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- library/src/webapp/js/view-preferences.js
- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/entity/UserPrefsEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-33439
Persist hidden gradebook item columns in session storage and on the
server as a user preference. That way you can move between machines
and keep your item choices.
> SAK-33439 Persist gradebook item column choices

- library/src/webapp/js/headscripts.js
- samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
We need to do this as lessons hosts the settings page in an iframe.
Portal's copy of moment.js is therefore not available.
> SAK-42030 Added moment.js to samigo settings page

- commons/tool/pom.xml
- commons/tool/src/java/org/sakaiproject/commons/tool/CommonsTool.java
- commons/tool/src/webapp/WEB-INF/bootstrap.jsp
- gradebookng/tool/pom.xml
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/chart/BaseChart.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java
- library/src/webapp/js/headscripts.js
- profile2/tool/pom.xml
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/BasePage.java
- roster2/tool/pom.xml
- roster2/tool/src/java/org/sakaiproject/roster/tool/RosterTool.java
- roster2/tool/src/webapp/WEB-INF/bootstrap.jsp
Roster
Gradebook
Profile2
Commons
> SAK-42467 Add portalCDNQuery to any js downloads

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- library/src/morpheus-master/sass/modules/pager/_base.scss
- library/src/morpheus-master/sass/modules/topbar-search/_base.scss
- library/src/morpheus-master/sass/tool.scss
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- search/search-impl/impl/src/java/org/sakaiproject/search/entitybroker/SearchEntityProvider.java
- webcomponents/bundle/src/main/bundle/pager.properties
- webcomponents/bundle/src/main/bundle/search.properties
- webcomponents/tool/src/main/frontend/sakai-element.js
- webcomponents/tool/src/main/frontend/sakai-pager.js
- webcomponents/tool/src/main/frontend/sakai-search.js
https://jira.sakaiproject.org/browse/SAK-42443
> SAK-42443 Added search icon and bar to navbar

- assignment/bundles/resources/assignment.properties
- assignment/impl/src/java/org/sakaiproject/assignment/impl/reminder/AssignmentDueReminderServiceImpl.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java
- kernel/api/src/main/java/org/sakaiproject/time/api/UserTimeService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/serialize/impl/conversion/ConversionTimeService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/UserTimeServiceImpl.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/serialize/impl/test/MockTimeService.java
- kernel/kernel-util/src/main/java/org/sakaiproject/util/ResourceLoader.java
Adds a new method to UserTimeService to fetch a preferred timezone for userId.
Also generally improve the email and debug logging.
> SAK-42466 send the Assignment reminder email with user's time zone included

- assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
> SAK-41275 Assignment remove NonUniqueResultException from submission

- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java
- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsMessageManager.java
- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/PermissionLevelManager.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-component-impl/pom.xml
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/PermissionLevelManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/OpenForum.hbm.xml
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/Topic.hbm.xml
- New code to export/import messages from forums (until this PR just forums and discussions were exported/imported).
- Existing code adapted to JPA EntityManagerFactory.
> SAK-42257 - Problems archiving message forums

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
> SAK-41269: accessibility: gradebook with categories: Move Left/Move Right should not be available when you can't move the item in that direction.

- library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
- library/src/morpheus-master/sass/modules/bullhorn-alerts/_base.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/BullhornData.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/BullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/BullhornService.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/BullhornAlert.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AddAssignmentBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AnnouncementsBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/CommonsCommentBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendConfirmBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendIgnoreBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendMessageBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendRequestBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendStatusBullhornHandler.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/GradeAssignmentBullhornHandler.java
- portal/portal-impl/impl/src/bundle/bullhorns.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-42498
> SAK-42498 Merge bullhorns together

- msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/PrivateMessageManager.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Commit to return a Message object when saving a message instead of having void methods.
> SAK-42257 Messages in forums are not exported when archiving a site, part 2

- roster2/tool/src/webapp/WEB-INF/bootstrap.jsp
- roster2/tool/src/webapp/js/roster.js
https://jira.sakaiproject.org/browse/SAK-42540
> SAK-42540 Make roster.js a module so it can use static imports

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.java
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- library/src/webapp/js/view-preferences.js
https://jira.sakaiproject.org/browse/SAK-42463
> SAK-42463 view-preferences.js is now imported oldee style

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/webapp/js/saveForm.js
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
When the autosave timer is thrown, we check if the assessment is in past Date (due Date
or Retracted Date).
If the autosave timer is bigger than due Date or Retracted Date minus current time and date
we show an alert: "You have {minutes} and {seconds} left" (milliseconds transform to 
minutes and seconds from auto save timer property).
In other case we show an alert: 
"The time allowed for this assessment has expired. Your answers will be automatically submitted momentarily." and submit the assessment.
> SAK-34725: Submit the answers when the time is over for non-timed assessments.

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- library/src/webapp/js/view-preferences.js
https://jira.sakaiproject.org/browse/SAK-42459
> SAK-42459 Return null from preferences js if not set

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-42552
> SAK-42552 Extended column hiding persistence to category columns

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
Possible to add same exception in unpublished/published assessment
> SAK-42560: Error on log when adding exceptions. UI is wrong

- library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
- msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
Commit to add the rol and group information of the message author to the message detail view.
Several visual issues in the messages list page fixed. Minor clean and refactoring of the code.
> SAK-42557 - Add group info to message detail view

- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- library/src/webapp/js/view-preferences.js
- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/entity/UserPrefsEntityProvider.java
- user/user-tool-prefs/tool/src/webapp/WEB-INF/applicationContext.xml
https://jira.sakaiproject.org/browse/SAK-42552
Also, removed mutex from backend service. Properties are now checked
for currency, before obtaining a edit lock.
> SAK-42552 Batched preference updates

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/reminder/AssignmentDueReminderServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
- assignment/impl/src/webapp/WEB-INF/components.xml
Previously permissionCheckWithGroups would check permissions against the
current user. This is now improved and will check accordingly if a user
is specified or not. canSubmit will now properly return the right answer
if a user is specified.
> SAK-42380 Assignment canSubmit will properly check permissions

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://jira.sakaiproject.org/browse/SCO-161
Forgot about the completion page, this is the last of it! See #7385 for reference
> SCO-161: make SCORM Player (contrib) work inline (no iFrames)

- entitybroker/api/src/test/org/sakaiproject/entitybroker/util/TemplateParseUtilTest.java
Should have put this in the original PR on #7418
> Adding a quick test for SAK-42559

- library/pom.xml
- library/src/webapp/editor/elfinder/sakai/elfinder.html
Verified in my local environment:
> SAK-42583 - WebJars: Upgrade Elfinder to 2.1.50

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumsFilePickerServlet.java
Commit to check whether all the requirements are met or nor before dispatching a URL to access a private message. If requirements are not met, then redirect to main page of Private Messages tool.
> SAK-42631 - Error trying to access to a Private Message via URL

- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/report/ReportManager.java
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportManagerImpl.java
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/ReportManagerTest.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/SiteStatsEntityProvider.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportsEditPage.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/providers/ReportsDataProvider.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ActivityWidget.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/ResourcesWidget.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/VisitsWidget.java
The line on ReportManagerImpl is what actually fixes the problem, but as I was researching it I discovered the user selector is managed in a different way than other multiple ones on the same page (events, tools). So I decided to standardize it and remove all the unnecessary code too.
> SAK-42572 Solve ClassCastException on Sitestats

- signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
Avoid double click "Add a new timeslot."
> SAK-42662: Double click in Sign-up -> Server goes down

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
As it says in the "SAK-32035" you have to add these properties for the JGroups communication
> SAK-40937: add new properties for JGroups communication

- common/common-composite-component/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonManagerImpl.java
- common/impl/src/java/org/sakaiproject/component/common/edu/person/InetOrgPersonImpl.java
- common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.hbm.xml
- kernel/kernel-common/src/main/config/log4j.properties
Supposedly this was a workaround for supporting a byte array in Oracle however in investigating I have not found any evidence suggesting oracle doesn't support byte[]. In order to turn a caching for this table we need to remove the blob type in favor of a byte array. If there is an issue in oracle we should look at fixing it so that it does work.
> SAK-41216 Enable caching for Sakai Person

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-edit.js
Navigation with tab-enter has been repair
> SAK-42091 - Instructor: Manage Rubrics - cannot use keyboard-only or screen reader to access Edit Rubric Popup

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumsFilePickerServlet.java
Commit to add pages that require info in backing bean (reply, reply all and forward) to the checkUrlRequirements.
> SAK-42677 - Problems with copy paste of URL's

- assignment/impl/src/java/org/sakaiproject/assignment/impl/reminder/AssignmentDueReminderServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Removing useless old method too
> SAK-42667 Assignments: don't send reminder to instructors

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
The previous implementations (for all the question types with variable number of answers) were really faulty, only working if old answers size < new answers size.
> SAK-42116 T&Qs : update answers when editing published items

- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ExtendedTime.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeQueriesAPI.java
This PR does nothing, just cleans up the spacing in the files related to the extended time feature.
> NOJIRA: T&Q Extended feature, spacing cleanup

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/instructor_new_edit/assignto_section.vm
> SAK-41709 Assignments disable group changes if there are submission for

- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
@ern Could you please review this? I know you changed the part for doing the permission checks, but getting the current user id is still needed for getting the submission. Let me know if you think this is fine. Thanks!
> SAK-42680 Users can always resubmit returned assignments

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-42711
> SAK-42711: Stack trace when clicking on student with no submission

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- help/help-component/src/bundle/TutorialMessages.properties
- help/help-component/src/tutorial/Tutorial.config
- library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/base/_extendables.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/navigation/_navigation_mixins.scss
- library/src/morpheus-master/sass/modules/tutorial/_base.scss
- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSitesNav.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
https://jira.sakaiproject.org/browse/SAK-42642
This PR adds star links to sites in the top bar. This is adapted from a local feature that was originally created by my colleague that we've had in our Sakai instance since 2017 for Sakai 11. 
I've also update the tutorial to describe the functionality and I've simplified a bunch of the existing styling for that top bar.
See the SAK-42642 for some screenshots.
> SAK-42642 Add favourite sites stars and functionality to the top bar

- commons/tool/src/webapp/WEB-INF/templates/permissions.hbs
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- roster2/tool/src/handlebars/permissions.handlebars
- webcomponents/tool/src/main/frontend/sakai-i18n.js
- webcomponents/tool/src/main/frontend/sakai-permissions.js
https://jira.sakaiproject.org/browse/SAK-42731
> SAK-42731 Renamed sakai-tool-permissions to sakai-permissions

- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/SiteEntityProvider.java
- entitybroker/core-providers/src/java/site.properties
- webcomponents/bundle/src/main/bundle/group-picker.properties
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/package-lock.json
- webcomponents/tool/src/main/frontend/package.json
- webcomponents/tool/src/main/frontend/sakai-group-picker.js
https://jira.sakaiproject.org/browse/SAK-42730
> SAK-42730 Move grader to use sakai-group-picker

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-42732
This adds visual indicators to show when feedback, private notes, or the
rubric have been populated.
> SAK-42732 Add visual indicators to grader

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-edit.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-comment.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js
https://jira.sakaiproject.org/browse/SAK-42090
> SAK-42090 Associated labels for fields properly

- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-42752
> SAK-42752 Moved resubmit block to below grading components

- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
Only real change is at bottom (line 150)
> SAK-42756 after timer submits for user take them back to main page

- samigo/samigo-app/src/webapp/jsf/author/item/attachment.jsp
> SAK-42751 - Improve layout when there are no attachments

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-41849
> SAK-41849 Make rubric ratings persist when attaching files

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-association.js
https://jira.sakaiproject.org/browse/SAK-41776
> SAK-41776 Check for empty state details in rubric association

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-student.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-comment.js
https://jira.sakaiproject.org/browse/SAK-42361
> SAK-42361 Handle undefined as rubric comment

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
https://jira.sakaiproject.org/browse/SAK-41849
> SAK-41849 Make sure comments are updated between attachments

- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
Moving duplicated code to shared service
> SAK-34486 Rename duplicated assessments when importing

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
https://jira.sakaiproject.org/browse/SAK-42783
> SAK-42783 Fix disappearing rubrics when attaching/removing

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionForumBean.java
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
- rubrics/api/src/main/bundle/rubrics.properties
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-association.js
https://jira.sakaiproject.org/browse/SAK-41931
> SAK-41931 Force forums to use same rubric as gb item

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
- samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecording.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecordingAnswer.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/submissionStatus.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
- samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/copyPoolTree.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/movePoolTree.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/subpoolsTreeTable.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/transferPoolConfirm.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/transferPoolTree.jsp
- samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivity.jsp
- samigo/samigo-app/src/webapp/jsf/template/templateIndex.jsp
> SAK-42799 convert date to user's preferred time zone as instructor

- library/src/morpheus-master/sass/modules/tool/_table.scss
See https://jira.sakaiproject.org/browse/SAK-42818 for before and after
> SAK-42818 Fixed button margins to prevent page jitter for Sakai table controls

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/webapp/js/saveForm.js
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
Second attempt at autosave failure warning. There are fewer changes this time.
> SAK-40627 show error to user if autosave fails

- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewWeek.vm
Delete condition added in SAK-33755.
Before:
After:
After the change, events from Assignment, Calendar and Google continue to look good
> SAK-41386 - Delete condition added in SAK-33755

- calendar/calendar-summary-tool/tool/src/webapp/WEB-INF/tools/sakai.summary.calendar.xml
Plus solving wrong tab format, removing old comments
> SAK-42286 Manage overview: calendar summary as widget

- library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js
- library/src/morpheus-master/sass/base/_icons.scss
- library/src/morpheus-master/sass/modules/_toolmenu.scss
This PR has been created as a PR template for the new icon.
> SAK-40829 Library: Remove all cases of fa-leanpub

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/StartInsertItemListener.java
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
Also cleaned up code on related java file
> SAK-42865 T&Qs : 'copy from pool' option appears twice

- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java
> SAK-42814 Signup title is not initialized

- commons/impl/src/java/org/sakaiproject/commons/impl/SakaiProxyImpl.java
https://jira.sakaiproject.org/browse/SAK-42859
> SAK-42859 Commons improved error logic getSitePermissionsForCurrentUser

- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java
https://jira.sakaiproject.org/browse/SAK-42262
> SAK-42262 Add proposed maxlength to tool title on Pageorder

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-42753
> SAK-42753 Make rubric evaluations work with Sakai grader

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
https://jira.sakaiproject.org/browse/SAK-42139
> SAK-42139 Messages / default sort order should be date instead of label 

- samigo/samigo-app/src/webapp/jsf/questionpool/selectQuestionType.jsp
https://jira.sakaiproject.org/browse/SAK-42884
> SAK-42884 T&Q : Cancel button not working

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-40425
> SAK-40425 fix sorting on the content review column

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-button.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-student-preview-button.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-utils.js
https://jira.sakaiproject.org/browse/SAK-42827
Also, add some aria attributes.
> SAK-42827 Make rubric button tabbable.

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Also, extracting related common code to a macro
> SAK-42644 Show Supplement items on instructor's student view

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm
https://jira.sakaiproject.org/browse/SAK-42342
Added aria-describedby to the footer's server details panel link, as advised.
> SAK-42342 Changed footer's server details panel to use aria-describedby

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
https://jira.sakaiproject.org/browse/SAK-42539
> SAK-42539 Gradebook screen real estate

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/shared/PersonBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ActionSelectListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SaCharCountListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/shared/RemoveMediaListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/web/session/SessionUtil.java
- samigo/samigo-app/src/webapp/jsf/delivery/confirmSubmit.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/questionProgress.jspf
- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/tableOfContents.jsp
- samigo/samigo-app/src/webapp/jsf/shared/removeMedia.jsp
The changes are mostly in the jsp file and in the SubmitToGradingActionListener. I couldn't keep myself from cleaning up the code a bit, reduced the DeliveryBean class in more than 1500 lines and 20kb. Still far from perfect but definitely a bit more light and readable...
Guess I could make simpler PRs for the backport.
> SAK-42658 T&Q : show submitted files on confirmation screen

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Simplified the getTools method and added Generics where missing
> SAK-42926 Site Manage add default tool selections for new site

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
HashMap.values.field can't be managed by this version of h:dataTable
> SAK-42658 Backport to 12.x (2)

- library/src/morpheus-master/folder-structure.md
- library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- library/src/morpheus-master/sass/_defaults.scss
- library/src/morpheus-master/sass/base/_extendables.scss
- library/src/morpheus-master/sass/base/_material-defaults.scss
- library/src/morpheus-master/sass/modules/_toolmenu.scss
- library/src/morpheus-master/sass/modules/navigation/_base.scss
- library/src/morpheus-master/sass/modules/navigation/_navigation_mixins.scss
- library/src/morpheus-master/sass/modules/navigation/_skipnav.scss
- library/src/morpheus-master/sass/modules/swapped-view/_base.scss
- library/src/morpheus-master/sass/modules/tool/_base.scss
- library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
- library/src/morpheus-master/sass/modules/topbar-search/_base.scss
- library/src/morpheus-master/sass/tool.scss
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
https://jira.sakaiproject.org/browse/SAK-42889
I've left all the settings off, I think this is ready for discussion. JIRA update tomorrow w/ screenshots.
From Tuesday's demo, I pulled the navIntraTool-as-material (tool tabs) out as I couldn't design something I was pleased with and didn't want to hold the rest of the work up.
> SAK-42889: Library - enable material design elements

- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-42907
> SAK-42907 Test for existing properties on grader dummy submissions

- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-42937
> SAK-42937 Only load gradable when i18n has loaded

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- library/src/morpheus-master/sass/modules/grader/_base.scss
https://jira.sakaiproject.org/browse/SAK-42940
> SAK-42940 Don't send draft submissions to the grader

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
- library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- library/src/morpheus-master/sass/modules/_toolmenu.scss
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageBody.vm
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
- webcomponents/tool/src/main/frontend/sakai-maximise-button.js
https://jira.sakaiproject.org/browse/SAK-42539
> SAK-42539 Move maximise button to tool header

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java
Commenting code as it could be interesting in case hard deletion is
added in the future
> SAK-42943 T&Q : don't remove attachments on soft deletion

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Also limited the use of the deprecated TimeService
> SAK-42770 Assignment use users TZ when creating a new assignment

- library/src/morpheus-master/sass/modules/tool/_base.scss
https://jira.sakaiproject.org/browse/SAK-42970
> SAK-42970 Hide maximise button when on mobile

- library/src/morpheus-master/sass/modules/tool/_base.scss
- webcomponents/tool/src/main/frontend/fa-icon.js
- webcomponents/tool/src/main/frontend/sakai-maximise-button.js
https://jira.sakaiproject.org/browse/SAK-42969
> SAK-42969 Maximise button same colour as help button

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
- assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
https://jira.sakaiproject.org/browse/SAK-42977
Also fixed in this PR is an anonymous identity leak: when the instructor clicks on one of the reviewer's assessments, it identifies to the instructor who submitted the assignment when it should not
> SAK-42977: assignments > edit > anon & allow students to see review settings not reflecting saved values

- msgcntr/messageforums-app/src/webapp/jsp/compose.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
The expected error message is already there, but it was being nullified by a previous automatic validation.
> SAK-40901 Messages: Error message displayed with empty subject

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html
- library/src/morpheus-master/sass/modules/tool/_elements.scss
- library/src/morpheus-master/sass/tool.scss
https://jira.sakaiproject.org/browse/SAK-42981
See Jira issue for before and after screenshots.
> SAK-42891 Styled Gradebook Settings panels as expandable

- content/content-tool/tool/pom.xml
- kernel/api/pom.xml
- kernel/api/src/main/java/org/sakaiproject/conditions/api/Condition.java
- kernel/api/src/main/java/org/sakaiproject/conditions/api/Rule.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/conditions/impl/BaseRule.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/conditions/impl/NullPredicate.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/conditions/impl/ResourceReleaseRule.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java
https://jira.sakaiproject.org/browse/SAK-42008
> SAK-42008 Kernel: commons-collection => commons-collection4

- search/elasticsearch/api/pom.xml
- search/elasticsearch/util/pom.xml
https://jira.sakaiproject.org/browse/SAK-42986
> SAK-42986 Readded the elasticsearch-util message bundle

- library/src/morpheus-master/sass/modules/topbar-search/_base.scss
https://jira.sakaiproject.org/browse/SAK-42987
> SAK-42987 Made search results sit under user dropdown

- announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/Entity.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/EntityManager.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/EntityProducer.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/EntityManagerComponent.java
- message/search-adapters/impl/src/java/org/sakaiproject/search/component/adapter/message/MessageContentProducer.java
- search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/SiteElasticSearchIndexBuilder.java
- search/search-api/api/src/java/org/sakaiproject/search/api/EntityContentProducer.java
https://jira.sakaiproject.org/browse/SAK-43002
> SAK-43002 Indexed announcement results now have portal urls

- basiclti/web-ifp/src/java/org/sakaiproject/portlets/SakaiIFrame.java
https://jira.sakaiproject.org/browse/SAK-43005
> SAK-43005 Only set LTI tool title if supplied

- library/src/morpheus-master/sass/modules/portal-search/_base.scss
- library/src/morpheus-master/sass/tool.scss
- webcomponents/bundle/src/main/bundle/search.properties
- webcomponents/tool/src/main/frontend/sakai-element.js
- webcomponents/tool/src/main/frontend/sakai-pager.js
- webcomponents/tool/src/main/frontend/sakai-search.js
https://jira.sakaiproject.org/browse/SAK-43036
> SAK-43036 Fixed index error in portal search pager

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/assignment_macros.vm
https://jira.sakaiproject.org/browse/SAK-42980
See ticket in jira for details
> SAK-42980 - Assignment submission list - comparator has errors when sorting by content review

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/AssessmentGradingData.java
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/grading/GradingServiceAPI.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AnswerBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/attachment.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-42901
> SAK-42901 Lock portions of mcq items if submissions exist

- assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/impl/pom.xml
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentContentProducer.java
- assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
- assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java
- assignment/impl/src/webapp/WEB-INF/components.xml
- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- kernel/api/src/main/java/org/sakaiproject/entity/api/Reference.java
- master/pom.xml
- samigo/samigo-impl/pom.xml
- search/README.md
- search/elasticsearch/impl/pom.xml
- search/elasticsearch/util/pom.xml
- search/search-api/api/src/java/org/sakaiproject/search/api/EntityContentProducer.java
https://jira.sakaiproject.org/browse/SAK-43023
> SAK-43023 Search enable Assignments

- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43074
> SAK-43074 Fixed fa-icon console error in grader

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
https://jira.sakaiproject.org/browse/SAK-42901
> SAK-42901 Allow editing of draft samigo assessment items.

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
https://jira.sakaiproject.org/browse/SAK-43056
> SAK-43056 Prevent 'restricted roles' from being removed in Site Info.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
https://jira.sakaiproject.org/browse/SAK-43107
> SAK-43107 Only check for submissions in assessments, not pools.

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
https://jira.sakaiproject.org/browse/SAK-41487
> SAK-41487 Enforce a non empty points value in rubrics

- commons/api/src/bundle/commons.properties
- commons/api/src/java/org/sakaiproject/commons/api/CommonsConstants.java
- commons/api/src/java/org/sakaiproject/commons/api/CommonsManager.java
- commons/api/src/java/org/sakaiproject/commons/api/CommonsReferenceBuilder.java
- commons/api/src/java/org/sakaiproject/commons/api/CommonsReferenceReckoner.java
- commons/api/src/java/org/sakaiproject/commons/api/PersistenceManager.java
- commons/api/src/java/org/sakaiproject/commons/api/QueryBean.java
- commons/api/src/java/org/sakaiproject/commons/api/datamodel/Comment.java
- commons/impl/pom.xml
- commons/impl/src/java/org/sakaiproject/commons/impl/CommonsContentProducer.java
- commons/impl/src/java/org/sakaiproject/commons/impl/CommonsManagerImpl.java
- commons/impl/src/java/org/sakaiproject/commons/impl/CommonsSecurityManagerImpl.java
- commons/impl/src/java/org/sakaiproject/commons/impl/PersistenceManagerImpl.java
- commons/impl/src/webapp/WEB-INF/components.xml
- commons/tool/src/java/org/sakaiproject/commons/tool/CommonsTool.java
- commons/tool/src/java/org/sakaiproject/commons/tool/entityprovider/CommonsEntityProvider.java
- commons/tool/src/webapp/WEB-INF/templates/single_post.hbs
- library/src/morpheus-master/sass/modules/portal-search/_base.scss
- portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/CommonsCommentBullhornHandler.java
- webcomponents/bundle/src/main/bundle/search.properties
- webcomponents/tool/src/main/frontend/sakai-search.js
https://jira.sakaiproject.org/browse/SAK-43055
> SAK-43055 Search enable Commons

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
https://jira.sakaiproject.org/browse/SAK-43123
> SAK-43123 Add check for feedback set size

- rubrics/tool/src/main/frontend/webcomponents/sakai-item-delete.js
https://jira.sakaiproject.org/browse/SAK-43129
> SAK-43129 Fix error when deleting criterion row

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://jira.sakaiproject.org/browse/SAK-43143
> SAK-43143 Disable the publish site confirmation modal by default

- library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- webcomponents/tool/src/main/frontend/sakai-i18n.js
> SAK-43144 fix uncaught TypeError by checking for existence of portal user

- library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss
- rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/CriterionOutcome.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rating.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-rating-edit.js
- samigo/samigo-app/src/webapp/js/samigo-global.js
https://jira.sakaiproject.org/browse/SAK-41175
> SAK-41175 Allow floating point numbers in rubrics points

- library/src/morpheus-master/sass/base/_material-defaults.scss
https://jira.sakaiproject.org/browse/SAK-43177
> SAK-43177 Library remove uppercase transform from material buttons

- library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-43148
> SAK-43148 Library restore browser default border to <select>

- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/timeout.vm
https://jira.sakaiproject.org/browse/SAK-43203
> SAK-43203 Portal style session keepalive button as primary

- library/src/morpheus-master/sass/modules/_toolmenu.scss
https://jira.sakaiproject.org/browse/SAK-43133
> SAK-43133 Library increase font size on left tool menu

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-association.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
https://jira.sakaiproject.org/browse/SAK-43202
Also, fixed style scoping on sakai-rubric-criteria-grading.js
> SAK-43202 Only add item id on existing associations

- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/UserLocale.java
- signup/tool/src/webapp/signup/attendee/addSignupAttendee.jsp
- signup/tool/src/webapp/signup/attendee/editComment.jsp
- signup/tool/src/webapp/signup/attendee/signupMeeting.jsp
- signup/tool/src/webapp/signup/download/downloadSelections.jsp
- signup/tool/src/webapp/signup/newMeeting/assignStudents.jsp
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/newMeeting/step2.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
- signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
- signup/tool/src/webapp/signup/signupMeetings.jsp
https://jira.sakaiproject.org/browse/SAK-43118
> SAK-43118 Remove timezone from signup meeting dates.

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScoreAttachment.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp
https://jira.sakaiproject.org/browse/SAK-43019
> SAK-43019 Stop attachments breaking rubric in question view

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonSubmission.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
- lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
https://jira.sakaiproject.org/browse/SAK-37753
> SAK-37753 Fix assignment complete checks in lessons

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java
https://jira.sakaiproject.org/browse/SAK-43089
> SAK-43089 Added setter for roundedTotalAutoScore

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties
@dnhutchins I believe your SAK-42179 commit introduced this new key ... what do you have as the translation?
> SAK-43226 missing key match_match

- webcomponents/tool/src/main/frontend/sakai-permissions.js
https://jira.sakaiproject.org/browse/SAK-43249
> SAK-43249 Document the permissions webcomponent

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ImportQuestionsToAuthoringFromSearch.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/attachment.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml
- samigo/samigo-import/src/java/org/sakaiproject/importer/impl/handlers/SamigoPoolHandler.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedItemFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/PublishedItemService.java
This PR also reverted the following recent fixes as the root of this
issue was traced back to SAK-42116
Reverts SAK-43107 SAK-43123 SAK-42901 SAK-42853 SAK-42858 SAK-42116
> SAK-43088 Samigo set cascading with orphan removal for Item's

- library/src/webapp/js/lang-datepicker/lang-datepicker.js
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/BasePortalHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
https://jira.sakaiproject.org/browse/SAK-42959
> SAK-42959 Default lang-datepicker to user's local timestamp

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/RubricsService.java
- rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
- rubrics/tool/src/main/frontend/webcomponents/sakai-item-delete.js
NOTE: Parameters order on deleteRubricAssociation method was wrong in the service declaration.
> SAK-43112 Recover rubrics with softly deleted assignments

- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
This was a regression caused by SAK-43088
> SAK-43265 Samigo Import Assessment creates duplicate questions

- site-manage/datemanager/api/src/java/org/sakaiproject/datemanager/api/DateManagerService.java
- site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
> SAK-43272 Fix parsing of date picker dates

- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43270
> SAK-43270 Added submitters image to Sakai Grader

- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-grading.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-readonly.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-preview.js
- rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-student.js
https://jira.sakaiproject.org/browse/SAK-43222
> SAK-43222 Support i18n decimal separators in Rubrics.

- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-42158
> SAK-42158 Remove updateEntity from UserEntityProvider

- content/content-tool/tool/src/java/org/sakaiproject/content/entityproviders/ContentEntityProvider.java
- kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
- kernel/kernel-impl/pom.xml
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- library/pom.xml
- library/src/morpheus-master/sass/modules/grader/_base.scss
- webcomponents/bundle/src/main/bundle/document-viewer.properties
- webcomponents/bundle/src/main/bundle/grader.properties
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-43072
> SAK-43072 Add document preview to grader

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-manageParticipants.vm
https://jira.sakaiproject.org/browse/SAK-43314
This is an alternative approach for #7958 see discussion on the JIRA ticket.
> SAK-43314: site info > manage participants > show/hide credits column dynamically

- providers/unboundid/pom.xml
I've set the PR to "work in progress" because I don't have a local LDAP right now to test it, I'm planning to test it the next week. Meanwhile, feel free to comment.
> SAK-43346 - Update unboundid-ldapsdk 5.0.0

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- webcomponents/tool/src/main/frontend/grader/sakai-gradable-data-mixin.js
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-43321
> SAK-43321 Only show the profile image if we have a user id

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/tool/src/webapp/vm/assignment/chef_assignments_options.vm
- library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
- webcomponents/bundle/src/main/bundle/grader-toggle.properties
- webcomponents/tool/src/main/frontend/grader/grader-toggle.js
- webcomponents/tool/src/main/frontend/sakai-view-preferences.js
https://jira.sakaiproject.org/browse/SAK-43199
> SAK-43199 Added toggle to switch graders

- kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiLogin.java
https://jira.sakaiproject.org/browse/SAK-43317
> SAK-43317 Set the session cookie in the ws login response

- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/GalleryImageEdit.html
That line was introduced by https://jira.sakaiproject.org/browse/SAK-26775 but no longer seems necessary
> SAK-43355 Profile2 : console error on Gallery

- search/search-impl/impl/src/java/org/sakaiproject/search/entitybroker/SearchEntityProvider.java
- webcomponents/bundle/src/main/bundle/search.properties
- webcomponents/tool/src/main/frontend/sakai-search.js
https://jira.sakaiproject.org/browse/SAK-43352
Added suggestions, like the current search tool
Added a no results block
Added icons and title for Resources and Wiki
> SAK-43352 Portal search improvements.

- msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
https://jira.sakaiproject.org/browse/SAK-43024
> SAK-43024 Forums / Automatically create multiple topics for group issue

- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step1.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/wizard.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-40672
> SAK-40672 - Auto Groups Javascript refactor and some minor UI fixes

- site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/GroupController.java
- site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/MainController.java
- site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/util/UserComparator.java
https://jira.sakaiproject.org/browse/SAK-43277
> SAK-43277 - Group Manager: Create New Group: Members are in no particular order

- assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Fixed a bug in 2fd7dd2566ecf5ceb3e650dc8f9571e2b9bd228c
> SAK-43199 Move new grader toggle to more prominent place

- samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/downloadFileSubmissions.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/evaluationSubmenu.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/exportResponses.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/submissionStatus.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://jira.sakaiproject.org/browse/SAK-43324
> SAK-43324 - T&Q - Inconsistent display of tab options in Scores screens

- site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/AutoGroupsController.java
- site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/form/AutoGroupsForm.java
- site-manage/site-group-manager/src/main/resources/Messages.properties
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html
- site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html
https://jira.sakaiproject.org/browse/SAK-43273
> SAK-43273 - Group Manager - Manually added users are not a selectable option when auto-forming groups

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
- delegatedaccess/impl/src/webapp/WEB-INF/components-demo.xml
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/job/SeedSitesAndUsersJob.java
Also adds a property to set whether the eid should be used as the password for the seed sites and user job. The default is false which uses random passwords.
> SAK-43382 DA add email address to datest user

- assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
- gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
- webcomponents/bundle/src/main/bundle/group-picker.properties
- webcomponents/bundle/src/main/bundle/permissions.properties
- webcomponents/tool/src/main/frontend/grader/sakai-grader.js
- webcomponents/tool/src/main/frontend/sakai-group-picker.js
- webcomponents/tool/src/main/frontend/sakai-permissions.js
- webcomponents/tool/src/main/frontend/sakai-submission-messager.js
- webcomponents/tool/src/main/java/org/sakaiproject/webcomponents/permissions/PermissionsEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-43339
> SAK-43339 Added group picker to permissions component
