- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchIndexBuilder.java
- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java
- search/elasticsearch/impl/src/resources/org/sakaiproject/search/elastic/bundle/mapping.json
- search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
- search/search-api/api/src/java/org/sakaiproject/search/api/SearchService.java
SAK-28202 Add indexed field to indicate the state of whether a document 
was indexed. Previously it depended on whether the content field had valid
data but some ECP's didn't produce the appropriate content.
> SAK-28202 Add indexed field to hold the documents indexed state

- search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java
see https://jira.sakaiproject.org/browse/SAK-27715
Its a super small change but enables a lot of better architectures.  Especially if we want to start doing things like indexing sakai events into ES.  You really don't want ES embedded in Tomcat once you start really using it at any scale, but for smaller installations, it certainly more cost effective.  But this little gem gives people flexibility.
> SAK-27715 support ability to make sakai nodes client only to ES

- message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
Ideally this local cache would be removed like the other one, but just clearing it out for the moment seems to be fixing this pretty significant issue.
> SAK-28955 - Announcement email sent immediately without subject or body

- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiConfiguration.java
- webservices/cxf/src/resources/applicationContext.xml
This service allows lookups and sets of the config values in sakai, as well as runtime adjustment of the log configuration which is handy for debugging in dev and in production. The config stuff is useful for scripts that might want to check config, or external tools that help manage config, or adjust things at runtime.
Some examples:
Set logging to DEBUG
http://localhost:8080/sakai-ws/rest/configuration/adjustLogLevel?sessionid=3141ae2f-3065-4782-b614-13627f2b92d6&packageName=org.sakaiproject&level=DEBUG
Get a property
http://localhost:8080/sakai-ws/rest/configuration/getProperty?sessionid=3141ae2f-3065-4782-b614-13627f2b92d6&propName=auto.ddl
You can even get the @ style properties:
http://localhost:8080/sakai-ws/rest/configuration/getProperty?sessionid=3141ae2f-3065-4782-b614-13627f2b92 …
> SAK-28957 add config service

- user/user-tool-prefs/tool/src/webapp/prefs/tab.jsp
The main preferences page has buttons at the top and bottom of the form. The ones in the bottom of the form are not wrapped in a div with a class of "act".
This poses a problem for institutions that styles the primary action buttons based on this structure (.act input.active[type="submit|button|reset"]).
The attached patch simply changes the parent div of the bottom buttons to apply the "act" class (and remove some unnecessary formatting).
> SAK-28975: preferences missing active primary button at bottom of form

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/entityproviders/ForumsEntityProviderImpl.java
The Forums Feed returns the drafted forum info to the site instructor (Who is not the super user) and when  he did not created the forum. The Forum UI was doing this but now that logic is changed to Such that Forums Feed also flow the same behavior.
https://jira.sakaiproject.org/browse/SAK-28074
@bkirschn @dovek please review
> SAK-28074 Changing the Forum feed permission logic

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
Contributed patch from KNL-1055, tested this out by making the recommend change to ResourcesAction. No longer a bug report that locks up resources, just makes it so you can't have more than 100 of the same file.
```
-       public static final int MAXIMUM_ATTEMPTS_FOR_UNIQUENESS = 100;
+       public static final int MAXIMUM_ATTEMPTS_FOR_UNIQUENESS = 3;
```
> KNL-1055 - 101st proposal of same uploads fails with Bug Report screen

- delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/logic/ProjectLogicImpl.java
SAK-28988 Delegated Access: Concurrent hashmaps throw NPE when storing null values
> SAK-28988 Delegated Access: Concurrent hashmaps throw NPE when storing null values

- roster2/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
SAK-28989 Roster2: DA users can't view groups because of permission check
> SAK-28989 Roster2: DA users can't view groups because of permission check

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
This ticket builds on SAK-26069 which improves the Import from Site feature to automatically provision existing tools.
This ticket will provide the following features:
1. Tools will be sorted alphabetically instead of the site order
2. Only the tools that are actually in the original site will be shown, not all tools that are available for import
> Enhance Import from Site to automatically add any missing tools - part 2

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
If the anonymous user accesses the WebDAV page then a NPE would be thrown as the EID for the anonymous user is null.
> SAK-28994 No NPE when anonymous access WebDAV page

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/site-manage-tool/tool/src/bundle/sitebrowser.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteBrowserAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitebrowser/chef_sitebrowser_list.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitebrowser/chef_sitebrowser_simpleSearch.vm
https://jira.sakaiproject.org/browse/SAK-28997
* create sakai.property (sitebrowser.termsearch.display) that controls what the user sees in the Site Browser search dropdown (course radio button), in the message at the top of the results, and in the table of results
* can be set to: "eid", "title", or "description" (title is default)
* remove blank search terms in the results message/improve wording of results message
Currently, you can get a results message in the following format:
'No sites found that match your search for "course sites", "" and "<termSelected>" Academic Term.'
The logic behind these messages has been changed to not display empty quotes when no search string is provided, and to handle singular/plural.
> SAK-28997 improve user experience for Site Browser (gateway tool)

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
This fixes the issue because the UserDirectoryService returns  (empty string) for the anonymous user were as the SessionManager returns null for the anonymous user.
> SAK-27961 Don't throw NPE when anonymous user accesses announcements.

- chat/chat-tool/tool/src/java/org/sakaiproject/chat2/tool/ChatTool.java
The deleting of users is expected to happen and chat shouldn't fill the logs with errors when it comes across a message posted from a user who no longer exists.
> SAK-28996 Don't log error when a user can't be found.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
https://jira.sakaiproject.org/browse/SAK-29000
Site Info -> Edit Rosters -> Add Roster
The authorization fields are not actually required and can create roster attachment issues (waiting for authorization).
This introduces a sakai.property (site.addroster.authorizationrequired) to control whether or not these fields are visible to the user. Default is true (original functionality). Only when set to false are the fields not visible to the user.
> SAK-29000 Create sakai.property to show/hide authorization fields when adding roster(s) to a course site

- reference/library/src/webapp/js/lang-datepicker/lang-datepicker.js
The new datetime picker in Sakai 10 by default only allows intervals of 5 minutes to be selected. Some tools (eg evaluations) put the current time into some datetime fields but don't do any rounding.
To cope with this the datetime picker has some extra code to round the displayed datetime to the nearest interval. There are 2 problems with this rounding however:
- It doesn't update the internal hidden field with the rounded value so if the user doesn't change the value of the field a value will be submitted that isn't rounded to 5 minutes.
- The rounding done by the Sakai code will round across days but the internal timepicker rounding always keeps the date the same. Eg 1st Jan 1990 23:59 gets rounded to 2nd January 1990 00:00 rather than 1st Jan 1990 23:55
The solution is just to let the …
> SAK-27906 Use the date picker’s internal rounding.

- kernel/kernel-util/src/main/java/org/sakaiproject/util/ResourceLoader.java
By making the service locators non-static subclasses can be created for tests which change how the dependencies are found.
> KNL-1298 Allow subclasses of ResourceLoader for easier testing.

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
If used to be the case that when ical subscriptions were enabled they would just return the ical for the current site. In another issue this got changed so that they returned the calendar entries for all sites what are displayed in the calendar (including merged ones). However with this change the permission check would fail on the current site due to only one of the unlock methods being aware of getExportEnabled(). In this fix we make all permission checks aware of getExportEnabled() which allows the public iCal feed to work again.
> SAK-28986 Fix public ical subscriptions.

- .travis.yml
- master/pom.xml
This means our build output becomes reasonable again and we can cache our m2 repository so that builds are a little faster on travis-ci.org
> INFRSTR-310 Allow the build to work with travis-ci.org

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java
- calendar/calendar-impl/pack/src/webapp/WEB-INF/components.xml
Removed the threadlocal and added a cache. findCalendar is called around 20 times per page load so this should be effective.
One thing to consider is the cache config, at the moment its a very basic cache, this may need tuning, either in code defaults or via sakai.properties.
> SAK-26085 CalendarService depends on a Threadlocal for lookup, should be changed to a cache

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp
- msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
I have removed the "FormattedText.processFormattedText" against the message titles since the message titles are never displayed with the JSF tag "escape=false". Therefore, there is never an instance where the title is display unescaped. This is standard for the Forums messages. I tested with titles like:
"/><script>alert('xss')</script></a>
<script>alert('xss')</script>
"/></a><script>alert('xss')</script>
> SAK-25284 Special characters in message subject do not display correctly

- reference/library/src/webapp/js/caps-lock-checker.js
- reference/library/src/webapp/skin/neo-default/tool.css
https://jira.sakaiproject.org/browse/SAK-29035
caps-lock-checker.js changes styles inline with javascript which is bad practice. The javascript should only change the CSS class on the element, and the actual styles should be in a stylesheet.
Also, the spacing in the .js file is inconsistent, and there are some instances of the 'evil' equality operators rather than the 'good' twins.
> SAK-29035 caps-lock-checker.js changes styles inline with javascript which is bad practise

- reference/library/src/webapp/js/headscripts.js
https://jira.sakaiproject.org/browse/SAK-29037
In headscripts.js, the setMainFrameHeight() method calls setMainFrameHeightNow() which has code that sets the iframe height, but only to a max of 32760.
Sometimes content requires more height than this, which results in ugly/unfriendly double scroll bars.
> SAK-29037 setMainFrameHeight() has arbitrary maximum height

- reference/library/src/webapp/skin/neo-default/tool.css
- samigo/samigo-app/src/webapp/css/tool_sam.css
Samigo -> Published Copies tab:
The 'Active' and 'Inactive' links beside the 'View' text display the insert cursor rather than the hand cursor.
> SAM-2477 active/inactive links display as insert cursor rather than hand cursor

- gradebook/app/ui/src/bundle/org/sakaiproject/tool/gradebook/bundle/Messages.properties
The new wording will expressly declare what will happen when you click the Continue button.
> SAK-29048: Clarify wording on the Set Ungraded Items to Zero page

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-util/src/main/java/org/sakaiproject/util/Web.java
- kernel/kernel-util/src/test/java/org/sakaiproject/util/WebTest.java
When a file is downloaded we supply an old ISO-8859-1 filename for old browsers (IE8) and a good UTF-8 filename for modern browers. We also no longer encode spaces as plus in downloaded files but leave them alone in the UTF-8 version.
> SAK-12034 Allow non ISO-8859-1 in download names.

- user/user-tool/tool/src/java/org/sakaiproject/user/tool/UsersAction.java
different approach to populating the dropdown for Account User Types. We have been using this approach for some time now. With this patch you are assured that the user types in the dropdown are valid user types as they are based on the !user.template.<type> realm and a restart is not required.
> SAK-28026 - build user type list from user template realms

- msgcntr/messageforums-app/src/webapp/css/msgcntr.css
- msgcntr/messageforums-app/src/webapp/js/sak-10625.js
Adding back in the javascript to remove all onclick events from all anchors. Also adding new css for pointer-events which seems to prevent the links from being hit a lot better.
I refactored the if case a litle better. I'm not sure if returning true or false from this method makes any difference.
> SAK-29053 - Double-clicking reply in forums triggers multiple tabs error

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
This setTimedAssessment method will be skipped if the instructor "started" the assessment before
the student gets their chance.
> SAM-2475 avoid NPE when instructor overrides a student score before student begins the assessment.

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- reference/library/src/webapp/js/headscripts.js
I was thinking about this again and saw this suggestion on http://stackoverflow.com/a/23794555/3708872
It's not the ideal fix since it disables the problem rather than really fixing why it's happening but it looks like it works in all modern browsers I tested (IE11, Chrome, Firefox). We might have avoided it in the past because history management was not compatible with IE9 [1] but we aren't supporting IE9 really anymore (I don't think?). It might need testing in IE9 and some workaround because it would possibly cause a javascript error. I was thinking of putting up an alert box or something too rather than the non action, maybe that would be useful? 
This is really just a quick idea that has application in a few places where there are serious problems when hitting the back button, such …
> SAK-23247 - When grading students if you press the back button some of

- mailarchive/mailarchive-james/james/src/java/org/sakaiproject/james/SakaiMailet.java
You need to included the context in the List-ID: header as the id is just the channel ID (e.g. main) which isn’t unique across the whole service.
> SAK-27978 Correctly generate mailing list IDs.

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/logmessage/LogMessageJob.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/logmessage/Messages.properties
- jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
The is a simple quartz jobs that allows an administrator to write an arbitrary message into the logs. This can be used for regular timestamping of the log files or for debugging the logging configuration.
> SAK-29086 Quartz job to log messages.

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/questionpool/QuestionPoolItemIfc.java
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/questionpool/QuestionPoolServiceAPI.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
- samigo/samigo-archive/sam-handlers/src/java/org/sakaiproject/importer/impl/handlers/SamigoPoolHandler.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/questionpool/QuestionPoolItemData.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/questionpool/QuestionPoolServiceImpl.java
You currently cannot add questions to a question pool (I've tried several types but not all).
On the first attempt, you don't get a bug report on the UI. It just transfers you to the author index and appears like nothing happened. The question is not added to the question pool.
On the second attempt, you'll get the attached stack trace.
This is directly related to the DDL changes in SAM-2242; however there is a bunch of code laying around that assumes the IDs to be Strings, but they've been changed to ints.
> SAM-2496: can't add questions to question pools

- site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/UserNotificationProvider.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/UserNotificationProviderImpl.java
- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java
Allows login text and site urls in site member notification email
templates. This doesn't change the actual templates, just injects the
values if the placeholders are there.
> SAK-22252 Allows login text and site urls in site member notification email

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
https://jira.sakaiproject.org/browse/SAM-2499
When creating questions using the CKEditor, the editor adds a paragraph tag around the question text.
When the question text is displayed in the Questions table in Question Pools, the markup is removed, but the sort order is not correct. Behind the scenes, it is taking into account the markup and any leading/trailing whitespace in the question text when determining the sort order.
Adding manual leading/tailing whitespace in the CKEditor will also affect the sort order.
When viewing the table, leading/tailing whitespace for questions created with the basic (text area) editor is stripped for display in the UI, but questions created with the CKEditor do not get the whitespace striped for the UI.
> SAM-2499: Whitespace from CKEditor affects question text sorting and display in Question Pool's questions table

- reset-pass/account-validator-tool/src/webapp/js/accountValidator.js
- user/user-tool/tool/src/webapp/js/userCreateValidation.js
- user/user-tool/tool/src/webapp/js/userEditValidation.js
- user/user-tool/tool/src/webapp/js/userValidationCommon.js
https://jira.sakaiproject.org/browse/SAK-29099
Currently, the password validation algorithm makes a REST call for every keystroke entered by the user. If the user types quickly, this can result in lost keystrokes due to the latency of the REST call.
Our solution to this is to track the length of the input password. If the length has not changed since the last REST call, don't make another one. By doing so, it eliminates un-necessary calls to the REST service and improves the reliability of the algorithm so that keystrokes are not lost.
The linked PR/patch also addresses some minor JavaScript syntax errors.
> SAK-29099: password validation for users tool and reset-pass makes too many queries, which can result in lost keystrokes

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-29135
portal.mathjax.website.url was part of the initial MathJax feature, however it was removed during one of the revisions.
The sakai.property remains and should be removed.
> SAK-29135: remove unused mathjax property from sakai.properties

- basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Adds the ability to set an imsti.rolemap property that is a list of comma-separated values of the form sakairole:ltirole. This can be used to map sakai roles to lti roles for the lti launch and membership service.
> SAK-24185 Allow custom role mapping per placement

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfillrole/BackFillRoleJob.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfillrole/Messages.properties
- jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
This quartz job allows an administrator to create a new role in the template (!site.template or !site.template.course) then run the job which will add the role to all sites that don’t have it already.
Configuration allows it to be limited to one site, one role. It also allows reporting to configured as they job can take a while on a large install.
> SAK-29123 Quartz job to backfill role from template.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java
This changes allows a deployment to disable functions of the Page Order Helper tool.
> SAK-29144 Allow hidden/disabled to be enabled/disabled.

- kernel/pom.xml
Turns on source jar generation by default so that mvn eclipse:eclipse automatically links it up in other projects.
> KNL-1332 Add source generation by default

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ContentsDeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
- samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/reviewAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Following the steps in https://jira.sakaiproject.org/browse/SAM-2495 you can easily see several places in Samigo where 10 digits of decimal precision will display to the student or instructor.
This PR modifies both student and instructor view.  I also remove any custom rounding methods and just depend on MathUtils
> SAM-2495 need to round doubles to two decimals in a consistent way

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java
The config poh.uneditables is a comma separated list of tools IDs that should be editable. By default it’s empty.
> SAK-29145 Don’t allow some tools to be re-named.

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
When the site type was empty it should have been falling back to the default site type for getting the list of tools but this wasn’t working because the default type was being set to empty.
The call to ServerConfigurationService was getting back an empty string and therefore not falling back to the defaultSiteType tool registration parameter.
> SAK-28187 Fix Edit Tools when Site type is empty.

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
This was discovered by people testing on MySQL nightly trunk hosted at AWS which uses Ubuntu and standard MySQL 5.6 install.  I also modify to use JDBC prepared statement with parameters instead of concatenation.
> SAM-2492 need to refer to MySQL table name in correct case and fix parametized JDBC insert

- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIRoleMapperImpl.java
If a launch is from a trusted consumer, just return the user's site
role rather than mapping the lti role.
> SAK-29150 Return site role if trusted consumer.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java
I saw this error quite a bit in the logs.
https://jira.sakaiproject.org/browse/SAM-2511
My instinct is that the getString returns a null or empty string when unset.
> SAM-2511 a more sane way of grabbing the samigo.questionScore.answerText.length property

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
instead of just getting counts for pools that user is owner of.
https://jira.sakaiproject.org/browse/SAM-2514
Bug introduced when I sped up the counts in https://jira.sakaiproject.org/browse/SAM-2463
> SAM-2514 Need to get all counts for pools that user has access to 

- gradebook/app/ui/src/webapp/assignmentDetails.jsp
- gradebook/app/ui/src/webapp/instructorView.jsp
https://jira.sakaiproject.org/browse/SAK-29157
On the gradebook item page (entering grades for a specific gradebook item), tabbing off the last grade input text field puts the focus on the 'Gateway' link at the bottom of the page rather than the 'Save' button, which would be the expected behaviour.
If the user doesn't notice that the focus is not on the save button, they will hit enter and be transferred to the Gateway page. They will effectively lose all information they've input on the gradebook item page.
This is caused by the save and cancel buttons (both on the top and bottom of the form) having a tabindex=9998 and 9999 respectively. This essentially makes it so that the user would have to tab through every clickable control on the page before they would get focus on these buttons. …
> SAK-29157: tab order in certain gradebook UIs can lead to loss of user's data

- authz/authz-tool/tool/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
If a realm being edited doesn’t have any permissions of users against it then it can be removed as it’s not granting anything.
> SAK-29155 Cleanup empty realms when no longer needed.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
It looks like all of the content both questions and answers was being converted to plaintext by the pdf processor. This was in the original commit so I don't know why this was happening. I moved it to a method and left the option in here so old behavior could be preserved, but it just returns the text-as is. In some limited testing images and most HTML is coming up as expected. This would need more testing as I think some HTML tags could cause a problem and we might need to pass this through something like jsoup so that only valid HTML is returned rather than everything, but removing everything I think isn't right.
In addition if you're running the server in SSL you will get an SSL exception with a self signed certificate or one that isn't in the truststore, so you have a have an …
> SAM-2502 - Inline images in print pdf do not display

- kernel/api/src/main/java/org/sakaiproject/entity/api/ContentExistsAware.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/report/ReportDefEntityProducer.java
This ticket builds on SAK-26069 and SAK-28993 which improves the Import from Site feature to automatically provision existing tools.
This ticket will provide the following features:
1. Tools that have names in the sites that have been selected for import, that are different to the standard name for the tool will be shown next to the tool name. This is so that the user can make an informed decision about including that tool, when they might know it by a different name.
2. Only tools that contain content will be listed for import. An entity interface will be added that tools can implement that allows them to explicitly say whether or not they have content. There is no point showing a tool for import if it has no content. The initial candidate for this is SiteStats but it can be extended to …
> SAK-29159 Enhance Import from Site to automatically add any missing tools - part 3

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://jira.sakaiproject.org/browse/SAK-29164
The sakai.property worksitesetup.filtertermdropdowns (default = false) determines if the term drop downs should be filtered to only terms which the user has (instructor) section enrollments.
The same behaviour should be expected when an instructor is adding roster(s) to an existing course site via Site Info -> Edit Class Roster(s) -> Add Roster(s).
> SAK-29164: course site -> add rosters should use existing term filtering if sakai.property set to true

- authz/authz-tool/tool/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
- authz/authz-tool/tool/src/webapp/js/authz.js
- authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions.vm
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
This introduces new permissions that can control what permission changes are allowed. Superusers aren’t limited at all in what changes they can make.
There are 3 ways of restricting permission changes:
Add Only - For roles defines permissions that can only be added (but not removed).
e.g. These properties say that content.read can only be added for access and maintain roles:
realm.add.only.roles=access,maintain
realm.add.only.access=content.read
realm.add.only.maintain=content.read
Frozen - For roles defines permissions that cannot be changed (not added or removed).
e.g. These properties say that you can’t change content.delete.own for access role.
realm.frozen.roles=access
realm.frozen.access=content.delete.own
Whitelist - For roles defines permissions complete set of editable …
> SAK-29156 Allow permission changes to be limited.

- samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
https://jira.sakaiproject.org/browse/SAM-2518
There are some inconsistencies in the markup for the Event Log page:
1. messages list is above the navIntraTool actionToolBar
- when it's above the toolbar, it creates a gap which looks bad; it should be below the toolbar
- if there are no messages, the element should not be rendered
2. page title is centred, which contrasts all other Samigo interfaces where the title is left aligned
> SAM-2518 inconsistent markup in samigo -> event log

- samigo/samigo-app/src/webapp/jsf/author/assessmentHeadings.jsp
- samigo/samigo-app/src/webapp/jsf/event/eventLogHeadings.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp
- samigo/samigo-app/src/webapp/jsf/questionpool/sharePool.jsp
- samigo/samigo-app/src/webapp/jsf/template/templateHeadings.jsp
https://jira.sakaiproject.org/browse/SAM-2519
Most other tools, such as Resources and Gradebook, indicate which page you're on by applying a class to the menu item that the user is currently on. Samigo kind of does this too, but it's not consistent with the other tools.
The linked PR adds 'class="current"' to the span in the navIntraTool bar when you're on the given page. This helps institutional branding that targets the 'current' class.
> SAM-2519 indicate current page in samigo like other tools

- samigo/samigo-app/src/webapp/jsf/event/eventLogHeadings.jsp
https://jira.sakaiproject.org/browse/SAM-2520
The sakai.property samigo.showAssessmentTypes controls whether the user sees the drop down for assessment type creation and the assessment types/templates menu button.
The event log page does not respect this sakai.property, and will display a menu link for the assessment types UI, giving the user access to this interface regardless of the sakai.property.
The linked PR simply implements the existing check from the other headers in the event log headers.
> SAM-2520 samigo -> event log page doesn't respect sakai.property to hide assessment types

- dashboard/hbm/src/java/org/sakaiproject/dash/dao/JobRunImpl.hbm.xml
- dashboard/pack/src/webapp/WEB-INF/components.xml
Remove org.sakaiproject.dash.dao.SessionFactory to use org.sakaiproject.springframework.orm.hibernate.GlobalSessionFactory.
Adding org.sakaiproject.springframework.orm.hibernate.impl.AdditionalHibernateMappingsImpl to load custom hbm file.
Change auto-import to false to avoid name collision with SiteStats JobRunImpl.
> DASH-340 Use the normalized way to load local hbm files in dashboard

- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/UserFinderOrCreatorImpl.java
Trusted consumers can now supply the sakai eid as the primary means of
user lookup.
> SAK-29154 Lookup LTI user by eid if provided

- reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.java
- reset-pass/account-validator-impl/src/bundle/validate_requestAccount.xml
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/account-validator-tool/src/bundle/org/sakaiproject/accountvalidator/bundle/messages.properties
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/ClaimLocator.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/RequestAccountProducer.java
- reset-pass/account-validator-tool/src/webapp/WEB-INF/requestContext.xml
- reset-pass/account-validator-tool/src/webapp/css/requestAccount.css
- reset-pass/account-validator-tool/src/webapp/templates/requestAccount.html
- user/README.md
- user/user-tool/tool/pom.xml
- user/user-tool/tool/src/bundle/admin.properties
- user/user-tool/tool/src/java/org/sakaiproject/user/tool/UsersAction.java
- user/user-tool/tool/src/webapp/js/userCreateValidation.js
- user/user-tool/tool/src/webapp/tools/sakai.createuser.xml
- user/user-tool/tool/src/webapp/vm/user/chef_users_create.vm
https://jira.sakaiproject.org/browse/SAK-28184
To ensure that users are creating accounts using their real email addresses, the New Account tool should be configurable to send an email with a link to activate their account.
Also, when we add unofficial participants through Site Info, the user eids match their email addresses. For consistency, the New Account tool should have configuration to similarly force the eid to match the user's email address.
Finally, it would be handy to display instructions in the tool. But note that institutions may have multiple instances of this tool to serve different purposes (eg. to create users with different account types), so the instructions should be configurable in the tool properties.
> SAK-28184 new account tool should email users a link to activate their accounts

- samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
and click begin assessment
So this moves the code to the central jQuery page and then adds a check to the blockUI code to make sure that we're not waiting for the user to approve the honor pledge.
> SAM-2526 student receives blockUI when they don't accept honor pledge

- kernel/api/pom.xml
- kernel/api/src/main/java/org/sakaiproject/hikaricp/jdbc/pool/SakaiBasicDataSource.java
- kernel/deploy/shared/pom.xml
- kernel/kernel-component/src/main/webapp/WEB-INF/db-components.xml
- kernel/kernel-impl/pom.xml
- kernel/pom.xml
This PR adds support for HikariCP. This could for sure use some testing, but it starts up without any warnings. There is some cleanup still but it's seems to be a great first (or in my case about sixth) pass
Some notes
* I had to turn off autocommit as that default to on and there's warnings if that is on. I think I'll just move that property into the XML since it's identical to Hikari so a slight re-factor.
* I believe that just setting registerMBeans has Hikari register them, previously on the tomcat driver we had to explicitly do that. I have not tested the mbeans
* It has compatibility with all of the old properties (url@ driverClassName@ etc), but I think to set the hikariCP properties we'll need to add them with defaults to the bean here.
* I only tested this with MySQL, same driver …
> KNL-1333 - Adding support for hikaricp

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java
There is duplicate SQL for getting a resultset of all users and their role in a realm. This is useless duplication and can go.
getSelectRealmRoleGroup4Sql() is the same as getSelectRealmRoleGroup2Sql with just the table aliases being different.
> KNL-1338 Remove duplicate SQL for all grants.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- user/user-tool/tool/src/bundle/admin.properties
- user/user-tool/tool/src/java/org/sakaiproject/user/tool/UsersAction.java
https://jira.sakaiproject.org/browse/SAK-29182
The existing sakai.property invalidEmailInIdAccountString defines a list of domain names that are not allowed in guest accounts, which is useful for preventing accidental creation of guest accounts for users (based on email address) that already have an external account (based on user name).
When the New Account tool has the tool property force-eid-equals-email set to true (introduced in SAK-28184), the tool is essentially doing exactly what the sakai.property descibes, and as such it should respect the property if it's set.
This introduces a new sakai.property (user.email.invalid.domain.message) to provide a customizable, paramaterized error message which is presented to the user when in the event that they attempt to use an email address …
> SAK-29182 new account tool should respect invalidEmailInIdAccountString sakai.property

- calendar/calendar-util/util/pom.xml
- calendar/calendar-util/util/src/java/org/sakaiproject/util/CalendarUtil.java
- calendar/calendar-util/util/src/test/org/sakaiproject/util/CalendarUtilTest.java
The schedule tool would fail when the clocks went forward as there wasn't a 01:00:00 time on that day. The tool would however recover the next day. I've left this as 2 commits so it's easy to see the bug (checking out the first commit) and the fix separately.
> SAK-29214 Cope with time changes (clock going forward)

- kernel/api/src/main/java/org/sakaiproject/db/api/SqlReader.java
- kernel/api/src/main/java/org/sakaiproject/db/api/SqlService.java
This means when reading stuff from the database you can say what type will be returned and so know you won’t get classcast exceptions and it also makes the code easier to read as types are already present.
> KNL-1340 Add Generics to SqlRead and SqlService.

- common/import-parsers/blackboard_6/impl/pom.xml
The blackboard parser was incorrectly depending on an old version of Spring and commons-logging. It should be pulling these versions from master.
> SAK-28032 Depend on master spring and common-logging versions

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
- samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp
https://jira.sakaiproject.org/browse/SAM-2530
The only action this button applies to is deleting question pools, and should thus be named 'Delete' appropriately.
> SAM-2530 update button on question pool list should be named appropriately

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/GeneralMessages.properties
https://jira.sakaiproject.org/browse/SAM-2531
You'll get these warnings in the logs every time you hit the Event Log page in Samigo:
2015-03-31 15:02:22,746 WARN http-bio-8080-exec-5 org.sakaiproject.util.ResourceLoader - bundle 'org.sakaiproject.tool.assessment.bundle.GeneralMessages' missing key: 'a_assessment' from: org.sakaiproject.util.ResourceLoader.get(ResourceLoader.java:164)
2015-03-31 15:02:22,748 WARN http-bio-8080-exec-5 org.sakaiproject.util.ResourceLoader - bundle 'org.sakaiproject.tool.assessment.bundle.GeneralMessages' missing key: 'a_pool' from: org.sakaiproject.util.ResourceLoader.get(ResourceLoader.java:164)
> SAM-2531 missing message bundle keys in Samigo creating log bloat

- announcement/announcement-tool/tool/src/bundle/announcement.properties
https://jira.sakaiproject.org/browse/SAK-29233
Unnecessary log bloat:
015-04-06 14:40:43,689 WARN http-bio-8080-exec-5 org.sakaiproject.util.ResourceLoader - bundle 'announcement' missing key: 'gen.draft' from: sun.reflect.GeneratedMethodAccessor456.invoke(Unknown Source)
Even though this is only referenced once and from within an HTML comment, the Velocity engine will still try to resolve 'gen.draft' because it's not a Velocity comment, and thus has to be output in the resulting HTML.
> SAK-29233 missing message bundle key in announcements

- master/pom.xml
This prevents the surefire plugin from stealing focus on OS X.
Developers can set JAVA_TOOL_OPTIONS='-Djava.awt.headless=true' 
environmental variable but this requires more setup by each developer.
> SAK-29228 Make tests run headless by default

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-type.vm
When building the list of site templates a user can choose, only include templates if the user can create sites of that type.
> SAK-29232 Hide templates of type a user can't add

- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/AssignmentPeerAssessmentServiceImpl.java
When a student is grading another student submission in a peer assessment assignment the score is recorded in the db but the calculated score average is missing the last commited result.
What it's happening here is that process saves and retrieves rows in the same thread process and in some cases it has no time to store it to the db before the list is gotten.
Flushing must prevent that cases.
> SAK-29236 Peer assessment assignments average score misses the last record sometimes

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_uploadAll.vm
https://jira.sakaiproject.org/browse/SAK-29240
On either interface, when you click 'Select All', then deselect one of the options, the 'Select All' checkbox is not deselected.
> SAK-29240 download/upload all 'select all' checkbox should be deselected after deselecting option(s)

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
https://jira.sakaiproject.org/browse/SAM-2401
Took the approach of using Criteria and Disjunction to handle the possibility of triggering an ORA-01795 error (maximum number of expressions in a list is 1000).
> SAM-2401 issue on published assessment -> scores -> questions on Oracle after SAM-2192

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/SortType.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Assignment.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookManagerHibernateImpl.java
Add a SortType enum class and deprecate the strings in the internal Assignment class, but leave them in as they are used in the GB tool and has its own sorting. Wire up the sorting for the service.
https://jira.sakaiproject.org/browse/SAK-29248
> SAK-29248 Add API method to allow retrieving a sorted list of gradebook assignments

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
When this alert appears on saving an assignment, site owners tend to ignore it. Only later they contact us when TII reports fail to be generated:
"Alert: The assignment was saved, but Turnitin information was unable to be updated. Please try saving again."
Strengthen the wording so that they do something about it.
> SAK-29250 Strengthen wording of Turnitin alert

- portal/portal-charon/charon/src/webapp/scripts/chat.js
Removed from portal chat exclusive code for neoportal. Now all reference are just for Morpheus
> SAK-29252 - Remove portal chat backward compatibility with neoportal

- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
Rather than printing to the console the logging framework should be used so that all the log messages end up in the same place and they can be easily filtered.
> SAK-29258 When handling exception use log framework.

- authz/authz-tool/tool/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java
This shouldn’t have been removed during the initial work as it stops someone changing permissions with a GET.
> SAK-28084 Add back in the check it’s not a GET.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
The default in the code is false (not to show stack traces to users), but 
it is currently documented as false. This updates the documentation to
follow the code.
> portal.error.showdetail is incorrectly documented.

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
getBasicInfoOfLastOrHighestOrAverageSubmittedAssessmentsByScoringOption
method to use the agentId passed in method parameters instead of doing a
fresh lookup to find the current user
> SAM-2541 use agentId passed instead of looking up current user logged in

- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/StatsUpdateManager.java
- sitestats/sitestats-api/src/java/org/sakaiproject/sitestats/api/StatsUpdateManagerMXBean.java
- sitestats/sitestats-impl/src/bundle/site-stats-components.xml
- sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/SiteStatsMetricsEntityProvider.java
Done in 2 commits so it's clear which was just correcting a typo in a method name and which actually adds the JMX support.
> SAK-29257 Allow sitestats update manager to be monitored over JMX

- .travis.yml
- kernel/kernel-impl/src/test/java/org/sakaiproject/tool/impl/SessionComponentRegressionTest.java
- master/pom.xml
With a local build of reflect-utils this builds and starts up for me (with tests) using Java 8.
Entitybroker works (quick rough test).
These are basically the changes @jonespm suggested in email.
> SAK-25903 Upgrade to Java 8.

- kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupService.java
- site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteParticipantHelper.java
Non-assignable roles, such as .anon and .auth, are now hidden during
participant addition.
> SAK-29269 Hide non-assignable roles

- master/pom.xml
Now that there's a released version we should use that to improve the stability of the build and reduce the number of checks for artifacts maven makes.
> SAK-25903 Update to released reflectutils.

- samigo/samigo-app/src/webapp/css/tool_sam.css
https://jira.sakaiproject.org/browse/SAM-2545
The new Event Log UI in Samigo was introduced in Sakai 10. The control bar has some styling issues, mainly the controls are not centered in the control bar.
> SAM-2545 improve styling of event log control bar

- kernel/pom.xml
- master/pom.xml
This looks like it produces a nearly complete javadoc. There are a few errors during the generation so I'm adding <failOnError>false</failOnError> so we could look into those and fix them, but I didn't see too many. There are a lot of warnings too.
Also upgraded to the latest version.
> SAK-29286 - Fix javadocs for java 8

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
Error message for permissions was set, but not alerted.
I change it to invoke the addAlert method with the error message.
When message is not set, I set the message "alert.unknown".
> SAK-29263: Errors in the content tool (Resources) are not displayed in UI

- kernel/api/src/main/java/org/sakaiproject/content/api/ContentFilterService.java
- kernel/kernel-component/src/main/webapp/WEB-INF/content-components.xml
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentFilterServiceImpl.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderAccessService.java
- lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
When content is served through /access/content it can be modified on the fly be filters. One existing filter is a HTML top/tailer that adds on a header/footer to a HTML fragment. Content served through /access/lessonbuilder wasn’t getting processed in the same way.
To fix this I extracted out a service to the filter definitions are common across the whole service and exposed the collection of filters as a service so that tools outside the kernel can call it.
> LSNBLDR-485 Have content served through lessons wrapped.

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
https://jira.sakaiproject.org/browse/SAK-29312
If you submit on behalf of a student, the assignment list by student view will only show that there is a submission for the user, rather than saying it was submitted on behalf of the student. To avoid confusion for users, it will now say "by <submitting user> (on behalf of <student>)". Also applies to the maintainer's list of submissions for a given assignment.
There are two lines swapped in AssignmentAction to keep track of the submitting user. Previously, the 'submitting user' would always be overwritten by the user being submitted for.
> SAK-29312 show message making it clear that instructor submitted on behalf of student

- kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/ToolConfigurationService.java
ToolConfigurationService was missing JavaDoc about one of it's private members.
> Add Javadoc to m_toolsRequired.

- reference/library/src/webapp/js/headscripts.js
The second argument to openWindow() is the name of the window that should
be opened, however at the moment it’s called title which is very misleading
as it is actually the window name and not the title.
https://developer.mozilla.org/en-US/docs/Web/API/Window/open
> Use more accurate variable name for window name.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/AttachmentAction.java
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/FilePickerAction.java
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesConstants.java
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
- kernel/kernel-component/src/main/webapp/WEB-INF/content-components.xml
- rights/rights-impl/pack/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-29332
The current code has the following bugs:
1) if using the drag and drop upload and the site quota is set to unlimited, any file over the 1MB threshold will be reported as putting the user over the site quota
2) the code checks the deprecated siteQuota@... property, but not the new one (content.quota). This is the only remaining occurrence of the old siteQuota@... property. It should just be removed from both the default.sakai.properties and the referencing code
3) the code retrieves the quota and file size limit sakai.properties without providing default values. The result is that if these properties aren't set, the default limits will never be enforced
4) the advertised default value for site quota in default.sakai.properties is not respected …
> SAK-29322 upload resources using drag and drop does not obey file size and site quota limits properly

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
Despite having the correct permissions (site.visit.softly.deleted), users cannot see a list of softly deleted sites in Worksite setup therefore cannot restore them. This fixes the issue.
> SAK-29161 Now users can see a list of softly deleted sites in Worksite setup

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
It will be used 'buildTree' instead of 'buildTreeCopy'.
> SAM-2547 Copying questions to shared pool fails

- roster2/src/webapp/js/roster.js
This is related to SAK-29208, to avoid using timeout to detect missed scrollbar to load more pages, now it's working properly no matter what load time you have for roster members, @adrianfish could you please check this out?
> SAK-29308 Improve scroll detection to load more pages

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
If we're using Single Uploaded File Only, we don't want to submit inline attachments from the previous submission. 
Currently, our code grabs the nonInlineAttachments, and then checks if we're using Single Uploaded File Only. It would be more efficient to first check if we're using Single Uploaded File Only, and then grab the nonInlineAttachments, so we won't be grabbing nonInlineAttachments if we don't need to on other submission types.
> SAK-29339: Reduce calls to getNonInlineAttachments when resubmitting

- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
There are a couple blocks in BaseAssignmentService that do important tasks, and should an exception be thrown, it currently does nothing. Add logging in the catch statements.
> SAK-29346: Add logging to some important swallowed exceptions in BaseAssignmentService

- assignment/assignment-bundles/resources/assignment.properties
The message is:
allowResubmission.select.student = Allow resubmisison from
These labels have a class on them called 'skip', which pushes the labels offscreen to the left. So they don't display visually, but I believe they are picked up by screen readers.
> SAK-29352: Checkboxes to allow individual students to resubmit have Iabels that read 'resubmisison'

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
The Single Uploaded File Only special case: 
1) Instructor creates an assignment that accepts multiple attachments, allows resubmissions 
2) Student submits multiple attachments 
3) Instructor changes the submission type to Single Uploaded File Only 
4) Student attempts to resubmit 
Currently the student can only select from their previous files or upload a new file. But they cannot select a file from their workspace or site like in the other submission types. 
Add this behavior to the special case.
> SAK-29348: Single Uploaded File Only special case should allow you to select a file from workspace or site

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfilltool/BackFillToolJob.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfilltool/Messages.properties
- jobscheduler/scheduler-component/src/webapp/WEB-INF/backfill-tool.xml
- jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
This quartz job allows you to add a specific tool ID to to a selected set of sites, if the tool already exists in the site then it isn’t added.
> SAK-29354 Add job to backfill a tool into sites.

- content/content-tool/tool/src/java/org/sakaiproject/content/entityproviders/ContentEntityProvider.java
Updated pull request based on previous comments:
- minor formatting changes (github seems to introduce these)
- Add setCopyrightAlert()
- Change existing code to use setVisible() & setHidden()
> SAK-29118 add copyright alert to content feed

- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/JoinHandler.java
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/join.vm
https://jira.sakaiproject.org/browse/SAK-29359
When visiting a joinable site you are not a member of, a page appears asking if you would like to join. However, with certain properties enabled, joinability can be limited by account type. If a user tries to join but doesn't have the right account type, they will just hit Site Unavailable.
Linked PR will present a message to users that they will not actually be able to join the site, with an option to return to My Workspace. The PR will also adjust the behaviour of the "No thanks" option to direct the user to My Workspace instead of Site Unavailable.
> SAK-29359: Join site page doesn't consider account type limitations

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/webapp/js/studentViewSubmission.js
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
We've had at least one student who erroneously clicked cancel and believed they submitted their assignment. 
We need a prompt upon clicking cancel if: 
1) It's a new submission and the inline-text is non-empty or they uploaded at least one attachment 
2) It's a resubmission and the inline-text has changed or the list of attachments is not identical to their last submission.
> SAK-29356: Prompt students when they cancel out of a non-empty assignment submission

- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
In Sakai 10+, getContentHandler() tries to parse numberofgrades, and if the attribute doesn't exist, it logs it at WARN. However, in Sakai instances prior to Sakai 10, the numberofgrades attribute didn't exist. This results in log bloat when submissions prior to Sakai 10 are accessed. Reduce the log level to debug.
> SAK-29370: Reduce log bloat due to 'numberofgrades' parsing when attribute doesn't exist

- assignment/assignment-tool/tool/src/webapp/js/studentViewSubmission.js
Clicking cancel without making changes triggers a javascript error, preventing you from proceeding with the cancel
> SAK-29371: Fix javascript errors resulting from SAK-29356

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
The checking of the 'samigo.autoSubmit.enabled' property is needed to assure that the autosubmit feature is enabled.
> SAM-2523:Checks autosubmit property in sakai.properties before setting retractDate to dueDate

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
EDIT_ASSESSMENT constant has been created for the navigation rules. In cancelPool method, if a part exists, it would navigate to edit assessment page (the previous).
The part would be set to null after copying or cancelling, in order to navigate from question pools keep working as expected.
> SAM-2557 Cancel in copy to pool returns to question pool list instead of previous page

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
The conversion from Assignment bean to Assignment DTO in the gradebook service exposes the extra credit flag. However the conversion from DTO back to bean when updating the assignment does not include the extra credit flag so you can never update this flag. This PR restores balance in the universe.
> SAK-29395 allow extra credit flag to be updated

- providers/component/src/webapp/WEB-INF/jldap-beans.xml
- providers/jldap/src/java/edu/amc/sakai/user/AttributeMappingConstants.java
- providers/jldap/src/java/edu/amc/sakai/user/JLDAPDirectoryProvider.java
- providers/jldap/src/java/edu/amc/sakai/user/LdapAttributeMapper.java
- providers/jldap/src/java/edu/amc/sakai/user/LdapConnectionManagerConfig.java
- providers/jldap/src/java/edu/amc/sakai/user/SimpleLdapAttributeMapper.java
The JLDAP User Directory Provider now supports searching by authentication ID.
Although this class implements the methods out of the interface by default the
method doesn’t do anything. You need to enable AID searching.
> SAK-26124 Add support for searching by AID to LDAP.

- .mvn/jvm.config
Maven 3.3.1 allows MAVEN_OPTS to effectively come from the project source code. This means that developers have one less thing to configure when setting up their build.
On most developer machine the heap space options shouldn’t be needed as typically the JVM will limit it’s heap to 1/4 of physical memory, but it’s worth setting because some people may be compiling under VMs with much more limited memory constrains.
The permgen options aren’t included here as they are no longer supported under JDK 8 which is now required for master.
> SAK-29284 Use features in Maven 3.3.1 to reduce setup.

- calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewList.vm
When viewing a Schedule's events in list form, the site said event originates
from is displayed always. This change only displays the origin site when
viewing events from other sites. Thus when viewing a schedule's list of events within a site, the From: $CurrentSite is hidden.
> SAK-29277 Hide Event's orgin when in the same site.

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java
I have done the same at the second column that the first one, ask if the tool is alowed to the participant's rol.
To reproduce the issue, you need a page that has Double Column Layout. The problem is only present in the tools from the second column. Those tools should have a permission in the 'Function required' configuration.
Then, one of the site participants has a role without a permission that is used for one of the tools as 'Function required'.
When accessing the site, the user gets the error showed in the screenshot
with title "HOME" has a Double Column Layout. One participant of the site with rol that don´t have permissions of function required in a tool in the second column
> SAK-29388 Error in pages that contains double Column Layout

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
Changed the link for the add assignment to match up with the others and perform a submit on the page. Looks like it fixes the bug and improves the error message returned if you try to submit without leaving. You have to hit the add button twice, but that's how all the buttons work.
> SAK-29260 - Assignment decimal point moved on scoring

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
1. As instructor, create an assignment
* Accept Inline and Attachmnents or Attachments Only
* Allow resubmissions
2. As a student, submit to this assignment with a couple attachments
3. After submitting, view your submission.
* Notice at the bottom: "You may resubmit if you modify this submission."
* Click cancel - you are immediately redirected to the assignment list
4. View your submission again
* Remove an attachment. Notice the message "Don't forget to save or submit"
* Click cancel; notice the prompt
5. Remove all attachments.
Symptom: It behaves like 3), but it should behave like 4)
> SAK-29418: In an assignment resubmission, removing all attachments should be considered a modification

- citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/BaseCitationService.java
The problem with copying/duplicating a reading list is that BaseCitationService.set(BasicCitationCollection) is called from both checkForUpdates() (which  reloads the BaseCitationCollection fresh from the database) and also from copy(BasicCitationCollection) (which is supposed to genuinely copy a BaseCitationCollection in the database). But set(BasicCitationCollection) never saves any new CITATION_CITATIONs because the citations are always explicitly set to temporary=false, i.e., they are already saved in the db (line 3223).
This change passes through 'temporary=true' to the set(BasicCitationCollection) method when it is called from the copy(BasicCitationCollection) method (and therefore saves CITATION_CITATIONs) and 'temporary=false' otherwise.
> SAK-21872: Citations copy/duplicate doesn't work as expected.

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/entityproviders/StrippedReportDef.java
Reports defined earlier may not contain from/to dates so before copying
them we should check they aren’t null (to prevent NPE). The copying of
null fields is fine in other places.
It’s not practical to update the DB to ensure all fields are always defined.
> SAK-29407 Don’t fail where params undefined.

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
If an assignment accepts Single Uploaded File Only, the student's options are 'Submit' and 'Cancel', yet it prompts "Don't forget to save or submit!". It should simply say "Don't forget to submit!" in this case.
> SAK-29429: Single Uploaded File Only says 'Don't forget to save or submit!', but there is no save option

- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/AbstractNamedCourseManagementObjectCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/CourseOfferingCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/EnrollmentSetCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/SectionCmImpl.java
- master/pom.xml
Titles and descriptions will be inherited as follows:
CanonicalCourse -> CourseOffering -> EnrollmentSet -> Section
Inheritance will only happen if title/description is null or empty.
> SAK-29417: Inherit title and descriptions in Course Management

- portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/SiteNeighbourhoodServiceImpl.java
- portal/portal-service-impl/pack/src/webapp/WEB-INF/components.xml
This allows a tool running in the error site to know the URL that the user was having problems accessing, rather than have all the URLs just include the error site ID.
A simpler option would have been to use the Sakai session but this would have meant error handling wouldn't have with multiple windows and it would have bloated the size of the session.
> SAK-29355 Keep “bad” URL in error site.

- kernel/api/src/main/java/org/sakaiproject/content/api/FileSystemHandler.java
- kernel/api/src/main/java/org/sakaiproject/exception/ServerOverloadException.java
- kernel/kernel-component/src/main/webapp/WEB-INF/content-components.xml
- kernel/kernel-impl/pom.xml
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSql.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlDefault.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DefaultFileSystemHandler.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/util/StorageConverter.java
- kernel/pom.xml
Thanks to OpenCollab ZA for the patch.
This makes way for filesystems other than local (or mapped) disk, such
as OpenStack Swift.
A new interface is added, FileSystemHandler, along with extracting the
default file implementation. I made a few fixes to update the patch and
clean up a few stylistic things to fit into the kernel code better, but
there are no name or design changes.
All tests are passing and I have verified that DB and the local file backend are working as usual. The next step will be to test out the alternate backend implementation for Swift and verify if OpenCollab has made any adjustments since this patch was supplied.
> KNL-1268 - Extract content file operations to support multiple backends

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
User profile image display in navigation along with username and display
only image in mobile view to help utilize the space. ( only works when
the profile tool is deployed in workspace)
> SAK-29424: User profile image display in navigation

- dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
to make sure no one thinks we are trying to represent an md5-based checksum the way Amazon S3 does it
See: trac.cyberduck.io/ticket/8798
> SAK-29338 put a prefix on our DAV etag 

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Hi @jonespm,
This PR delivers the behaviour as discussed with @jeffpasch from NYU:
-  In Assignments, when "Are submissions for a group?" is checked, the option of "display to site" should be grayed out, and "Display to selected groups" should be automatically selected.
- Then, if "Are submissions for a group" is unselected, "Display to selected groups" should remain selected (because assignments requiring individual submission can still be made visible to only certain groups), but "display to site" should then be ungrayed.
This patch introduces some Javascript to the new/edit assignment form to deliver the above behaviour.
Is there a process to ensure this change is backported to 10.x?  I'm happy to provide a compatible patch.
Thanks,
Payten
> SAK-29439 - Assignment tool: Limit assignment visibility options for assignments with group submission

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/InitMimeTypes.java
I thought this might have been a deprecated method, but seems like it was just a missing initial slash when trying to initialize the mime.types. http://stackoverflow.com/a/536260
Weird error though. Maybe could use some better debug messages. The only thing that was coming up up is.
2015-05-27 03:33:57,619  WARN localhost-startStop-1 org.sakaiproject.tool.assessment.ui.servlet.InitMimeTypes -
> SAM-2569 - File upload type isn't working

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
The getGradingEventsForStudent method which returns a list of grading events for a student, currently exists only in the gradebook tool. To use this outside of the gradebook it needs to be present in the API.
> SAK-29455 add API method to get grading events

- assignment/assignment-impl/pack/src/webapp/WEB-INF/components.xml
Peer review submisions are not assigned to students, to solve that transaction control is now applied to AssignmetPeerAssessmentService to ensure data is saved when submission are assigned to students to be graded
> SAK-29450 : Transaction control is now applied to AssignmetPeerAssessmentService

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
1) Create assignment, set the accept until date in the past (or in the future and wait for it to pass)
2) View the submissions, don't grade
3) As as a student, view the assignment
Symptom: Beside the assignment title, it says in red "- Submitted". This is false.
The isUserSubmission property is not being respected.
> SAK-29430: Assignment falsely appears to be submitted when accept until date has passed and instructor viewed submissions

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
The assessment is not available if retract date is in the past although the current date is between start date and due date. 
This PR solves the issue taking into account the retract date only when the instructor wants to accept late submissions once past the due date. 
The full behaviour is the next (it has not been modified):
When due date has passed and the retract date has not passed yet, the assessment will be available in this cases:
+ If late submission are handled:
- The first submission 
or 
- When a retake has been granted
+ If late submission are not handled:
- Only when a retake has been granted
> SAM-2562: Retract date is taken into account only when late submissions are accepted

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties
https://jira.sakaiproject.org/browse/SAM-2579
The 'Update' button on the edit question pool UI somehow got it's message bundle removed, so it now says:
"[missing key (mre): org.sakaiproject.tool.assessment.bundle.QuestionPoolMessages.update]"
The same warning message is produced in the logs. This is not reproducible on the 10.x nightly server, but is reproducible on the nightly trunk server.
> SAM-2579 update button on question pool edit UI generates missing resource bundle key message/warning

- edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseManagementAdministration.java
- edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/Enrollment.java
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/hibernate/org/sakaiproject/coursemanagement/impl/EnrollmentCmImpl.hbm.xml
- edu-services/cm-service/cm-impl/hibernate-impl/hibernate/src/java/org/sakaiproject/coursemanagement/impl/EnrollmentCmImpl.java
- edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseManagementAdministrationHibernateImpl.java
- reference/docs/conversion/sakai_11_mysql_conversion.sql
- reference/docs/conversion/sakai_11_oracle_conversion.sql
Changes are backwards compatible, so any code that's updating enrollments without dropDate will still work as expected.
> SAK-29432 Add dropDate field to Enrollment

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
- content-review/content-review-api/public/src/java/org/sakaiproject/contentreview/service/ContentReviewService.java
- content-review/contentreview-federated/impl/src/java/org/sakaiproject/contentreview/impl/ContentReviewFederatedServiceImpl.java
Currently, any type of file can be submitted to an assignment. If content-review is enabled, there are only a few types of files that can be accepted by the content-review service. 
All attachments submitted to a content-review enabled assignment should get content-reviewed. Do this by limiting the file types that are accepted. Inform users which types of files are accepted before they upload. 
Make the content-review service API provide the file types that are accepted.
NB: This should not be merged until TII-157's revised patch is applied (or else https://source.sakaiproject.org/contrib/turnitin/trunk/ will break due to content-review API changes)
> SAK-27587: When content-review is enabled, block attachment if they are not acceptable with the content-review service

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Steps:
1) As instructor, set up an assignment that uses a content-review service
2) Submit on behalf of a student
Symptom:
If you view the attachments' originality reports in the content-review service (Turnitin / Vericite) or if you query the contentreview_item table, you'll see the originality reports are associated with the instructor rather than the student.
> prepareInlineForContentReview associates the submission with the instructor on the TII side

- reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/FormProducer.java
- reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/UserValidator.java
- reset-pass/reset-pass/src/webapp/WEB-INF/applicationContext.xml
In reset-pass, enter an email address associated with an account type that is not included in the sakai property:
accountValidator.accountTypes.accept
You will get the following feedback message:
"You cannot use this service to reset your password"
Ideally this message should direct users to their institution's identity management services.
We've opted to make this message configurable on a per-tool instance basis. If we had used sakai.properties, the message would be uniform across all reset-pass instances, but sometimes there are multiple reset-pass instances targeted to different users.
If the tool configuration is not present, it should revert to the message bundle.
The tool property will match the message key, namely "wrongtype"
> SAK-29508: When using reset-pass with an account type that is not accepted, the feedback message should be configurable

- syllabus/components/src/webapp/WEB-INF/components.xml
- syllabus/syllabus-api/src/java/org/sakaiproject/api/app/syllabus/SyllabusData.java
- syllabus/syllabus-api/src/java/org/sakaiproject/api/app/syllabus/SyllabusManager.java
- syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusManagerImpl.java
- syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
Currently if you use the Admin Workspace -> Site Archive, the syllabus body HTML will be part of the XML export but the attachments will not be included.
> SAK-20621 add syllabi attachments to site archive export

- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
Tool Categorization should use dynamic page property "sitePage.pageCategory" instead of using static toolorder.xml to categorize pages while rendering. This feature is enabled by setting property "portal.toolcategories.dynamic" to true.
> SAK-29484: Tool Categorization using dynamic property

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
The change fixes the issue reported in SAK-18631 and make sure the grade item from assignment is deleted from gradebook once the assignment is changed not to associate with gradebook.
> Fix assignment was not deleted from gradebook issue SAK-18631

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- profile2/api/src/java/org/sakaiproject/profile2/logic/SakaiProxy.java
- profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java
- profile2/impl/src/java/org/sakaiproject/profile2/logic/SakaiProxyImpl.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/BasePage.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MySearch.java
- profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewProfile.java
Messaging, Privacy, Preferences, Online Status, and my Kudos are now individually able to be hidden.
Messaging depends on Connections, so if connections are disabled, so is messaging. 
A global property, profile2.menu.enabled (default true), was created which overrides all the sub-menu items:
- profile2.gallery.enabled
- profile2.connection.enabled
- profile2.messaging.enabled
- profile2.search.enabled
- profile2.privacy.enabled
- profile2.preference.enabled
That is when profile2.menu.enabled is false, all the other values are ignored.
~~Sorry about all the whitespace changes. :disappointed_relieved:~~
NOTE: I fIxed the merge issues which caused build to fail from PR https://github.com/sakaiproject/sakai/pull/549
> SAK-29408 Profile2: Now able to hide sub-menu & social items in profile

- syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
If Syllabus redirect url points to a resource from the site, when
duplicating that url needs to be changed to point the same resource from
the destination site.
> SAK-29532 Update Syllabus redirect URL to new site id when copying a site if needed

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-29541
In developing a 10.x patch for SAK-29314, I discovered a small bug that eluded me during previous testing. The reference to the next/previous ungraded submission is being over-written during a loop rather than being preserved.
> SAK-29541 next/previous ungraded assignment submission navigation buttons not calculating submission reference properly

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
https://jira.sakaiproject.org/browse/SAK-29548
Currently the default value of the search fields is actually a value, rather than a placeholder. This is annoying for the users, who have to manually clear out the placeholder text before typing their desired search value.
Also, having the default as a value text requires server side code to detect and abort actually searching for the default text.
This PR turns the default text into a true HTML5 placeholder attribute text.
> SAK-29548 make search field default text into true placeholder text

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
This is to avoid generate null value as site id.
> SAK-29547 deal with null value of site id parsed from site root collection reference

- basiclti/basiclti-docs/resources/docs/sakai-api-test/lms.php
- basiclti/basiclti-docs/resources/docs/sakai-api-test/util/OAuth.php
- basiclti/basiclti-docs/resources/docs/sakai-api-test/util/lti_util.php
- basiclti/basiclti-util/src/java/net/oauth/OAuth.java
- basiclti/basiclti-util/src/java/net/oauth/signature/HMAC_SHA256.java
- basiclti/basiclti-util/src/java/net/oauth/signature/OAuthSignatureMethod.java
- basiclti/basiclti-util/src/java/org/imsglobal/basiclti/BasicLTIUtil.java
This should be back ported to 10.x - it is independent of Sakai's LTI functionality as it is just library code.
> SAK-29561 - Upgrade BasicLTIUtil and tests to support SHA256 signing

- reference/library/pom.xml
Build is broken in windows because an error with JRuby and font-awesome compass generation.
> SAK-29564 Build error on windows in reference/library

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/pom.xml
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/Portal.java
- portal/portal-charon/charon/src/webapp/scripts/portalscripts.js
- portal/portal-impl/impl/pom.xml
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
Now that we have a responsive portal, things like:
PREFER_MAXIMIZE
SAKAI_NAV_MINIMIZED
portal.add.mobile.link
sakai:maximized-url
portal.allow.auto.minimize / portal_allow_auto_minimize
portal.allow.minimize.navigation
Also remove code/data in portalscripts.js that were just there for OSP portal in SAK-20576 that are now obsolete and can be removed.
> SAK-29553 Removing obsolete mobile and OSP related code from portal

- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
Unpublished, softly deleted sites dont appear in the list of Softly Deleted sites in Worksite setup
> SAK-29369 - Unpublished, softly deleted sites dont appear in the list of Softly Deleted sites in Worksite setup

- kernel/deploy/common/pom.xml
If you activate the mysql maven profile (mvn -P mysql install sakai:deploy) when deploying Sakai into Tomcat the MySQL JAR will be copied into place. This makes it easier for new developers as there’s one less step to get a working copy of Sakai up.
It’s disabled by default as we can’t bind or distribute the JAR due to license conflicts.
> KNL-1364 Allow deploy of the MySQL Connector/J JAR

- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
- msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/Topic.hbm.xml
This is an issue with the MYSQL Optimizer where a bad plan is cached
and performance is greatly affected. It is generally not a good idea
to override a DB's optimzer but this issue has created enough problems
to warrant its addition.
> SAK-24944 Mysql Optimizer bug in forums

- reference/library/src/morpheus-master/sass/modules/tool/chat/_chat.scss
Portal chat bar was hidden by portal chat panel when it is visible. This panel should be on the bar not overlapping.
> SAK-29575 Changes in SASS to to show portalchat panel header on the chat bar instead of overlapping

- pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Banner.java
- pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/MissingUuidException.java
- pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Popup.java
- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/PASystemImpl.java
- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/banners/BannerStorage.java
- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/popups/PopupStorage.java
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/forms/BannerForm.java
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/forms/PopupForm.java
Previously, modifications to an existing popup would not persist.
Modified the call to .getUUID to throw an exception if a UUID value was
missing where one was expected, and modified callers to deal with this.
The tool should fail more loudly in the future, while the code that
integrates with the portal should swallow errors and log to avoid
interrupting the user's session.
> SAK-29584 Ensure that a UUID is passed through when updating a popup.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- edu-services/cm-service/cm-api/api/pom.xml
- edu-services/cm-service/cm-impl/hibernate-impl/impl/pom.xml
- edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SiteTitleAdvisorCMS.java
- edu-services/cm-service/cm-impl/hibernate-pack/src/webapp/WEB-INF/components.xml
- kernel/api/src/main/java/org/sakaiproject/authz/cover/AuthzGroupService.java
- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/api/src/main/java/org/sakaiproject/site/api/SiteTitleAdvisor.java
- kernel/api/src/main/java/org/sakaiproject/site/cover/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/site/impl/SiteServiceTest.java
- portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalSiteHelper.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/JoinHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/ToolHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/WorksiteHandler.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/DefaultSiteViewImpl.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
- site-manage/site-manage-tool/tool/src/bundle/membership.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockSiteService.java
- user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
https://jira.sakaiproject.org/browse/SAK-29138
There has been an ongoing request at our institution to put the current user's section/roster name into the course site tab rather than the actual site's name. When site's are crosslisted, it can become confusing for users to determine which site they need to navigate to in order to complete an assignment, test, etc.
If the student is in section/roster 005, but the course site's name is of section/roster 001 of the same course, it may not be obvious to the user that they are indeed the same site. This can result in missed assignments, etc., as well as frustration for the professor(s) dealing with answering student inquiries regarding this.
The linked PR introduces a sakai.property to control this behaviour. Default is set to 'false'; only if …
> SAK-29138: add option to use student's roster title instead of site title

- portal/portal-charon/charon/src/webapp/scripts/chat.js
- portal/portal-charon/charon/src/webapp/scripts/videocall.js
That prevents from executing videocall methods on IE that were causing errors.
> SAK-29586 Force to disable video chat when using IExplorer

- reset-pass/account-validator-tool/src/bundle/org/sakaiproject/accountvalidator/bundle/messages.properties
When you use the transfer memberships form, the button reads 'Activate your account and log in'. The account is actually being discarded, and your memberships are transferred to the account you are logging in with. Make the button text reflect this.
> SAK-29605: Button text on TransferMemberships form is inaccurate

- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
Some 'softly deleted' translation keys are duplicated
> SAK-29611 - Some 'softly deleted' translation keys are duplicated

- external-calendaring-service/impl/src/test/org/sakaiproject/calendaring/mocks/MockSakaiProxy.java
/tmp was assumed to to be somewhere to create temp files but on Windows this doesn’t exist so the tests were failing. Switched to use the standard way of finding the tmp directory with the system property which works everywhere.
> SAK-29596 Fix external-calendar tests on Windows

- lessonbuilder/tool/pom.xml
The problems is that project.build.directory is a full path to the build directory and on windows this includes the drive letter. This causes the maven eclipse plugin to fail. Switching to sakai.build.directory which is just a relative path means this always works.
> LSNBLDR-507 Fix mvn eclipse:eclipse on windows

- reset-pass/account-validator-tool/src/webapp/css/newUser.css
- reset-pass/account-validator-tool/src/webapp/css/passwordReset.css
- reset-pass/account-validator-tool/src/webapp/css/requestAccount.css
- reset-pass/account-validator-tool/src/webapp/css/transferMemberships.css
Currently, long email addresses will stretch the account validation forms, and it breaks our styles. Address this with css
> SAK-29608: Allow long email addresses to wrap around on account validation forms

- reset-pass/account-validator-tool/src/webapp/css/newUser.css
- reset-pass/account-validator-tool/src/webapp/css/passwordReset.css
- reset-pass/account-validator-tool/src/webapp/css/requestAccount.css
- reset-pass/account-validator-tool/src/webapp/css/transferMemberships.css
In account validation, some font-sizes were set explicitly while we were using neo skin, but morpheus has enlarged the font sizes and this has change the size of ems, resulting in alignment issues and inconsistencies.
Address these.
> SAK-29613: Adjust styles in Account Validation forms for Morpheus

- reset-pass/account-validator-impl/src/bundle/acknowledge_passwordReset.xml
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/account-validator-tool/pom.xml
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
- reset-pass/account-validator-tool/src/webapp/WEB-INF/requestContext.xml
It's good practice to send an ack email after a successful password reset. Make reset-pass send out an email such as the following:
"Your password in ui.service has been changed successfully. If you did not change your password, please contact mail.support"
> SAK-29614: Send an acknowledgement email after a successful password reset

- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
https://jira.sakaiproject.org/browse/SAK-29635
"Joinable set titles should be trimmed, you can currently have two sets called 'Set1' and 'Set1 '."
> SAK-29635 joinable set names are not trimmed

- site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/impl/SiteManageGroupHandler.java
- site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/rsf/GroupEditProducer.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java
https://jira.sakaiproject.org/browse/SAK-29645
"When creating/editing a group with invalid data (duplicate group name, etc), the page refreshes with the appropriate feedback message, but any changes the user made to the form fields are discarded. The result is empty form fields for a new group, or the previously saved data for an existing group.
After validation failure, the user's input should be preserved so they don't have to key it all out again."
> SAK-29645 opportunities for lost user (input) data when creating/editing/saving an 'invalid' group

- user/user-tool/tool/src/webapp/css/sakai-user-tool.css
- user/user-tool/tool/src/webapp/vm/user/chef_users_create.vm
The New Account tool has a tool configuration property called 'create-blurb'. This allows the administrator to configure the tool with introductory text / html that is site specific. However, the width of the containing fieldset is a bit small. This should be widened to accommodate wide introductory text / html.
> SAK-29638: User tool fieldset width is limiting on create-blurb content

- usermembership/tool/src/bundle/org/sakaiproject/umem/tool/bundle/Messages.properties
- usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/SiteListBean.java
- usermembership/tool/src/webapp/usermembership/css/usermembership.css
- usermembership/tool/src/webapp/usermembership/js/usermembership.js
- usermembership/tool/src/webapp/usermembership/sitelist.jsp
https://jira.sakaiproject.org/browse/SAK-29637
Please see the screenshots on the JIRA ticket.
"Add the ability to bulk toggle a users' membership status (active/inactive) via the User Membership tool.
This allows administrators the ability to change a users' membership across the board or in selective sites via the User Membership tool. Currently, the admin would have to visit each site and flip them manually, or use web services."
> SAK-29637: add ability to User Membership to bulk change status

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportsEditPage.java
Sitestats: Confirmation message does not appear when saving a custom
report. (FeedbackPanel)
> SAK-29669 - Sitestats: Confirmation message does not appear when saving a custom report. (FeedbackPanel)

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
SORT_BY_NONE means none and null means SORT_BY_SORTING , i.e. the specified order. wtf.
> SAK-29685 Make sort order consistent and clear 

- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-blis/src/java/org/sakaiproject/lti2/LTI2Service.java
- basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
- basiclti/basiclti-docs/resources/docs/sakai-api-test/tp.php
- basiclti/basiclti-impl/src/bundle/ltiservice.properties
- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/LTI2Constants.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/LTI2Messages.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/LTI2Servlet.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/LTI2Util.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/ToolProxy.java
- basiclti/basiclti-util/src/java/org/imsglobal/lti2/ToolProxyBinding.java
As we go forward with ContentItem and other LTI 2.x services, we will
need to increasingly look at the ToolProxy and ToolProxyBinding structures
so this pulls that utility code into two new classes and refactors the rest
of the code to use those utility classes.
> SAK-29328 - Major refactor of LTI2 utility code to allow toolproxy inspection

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeAnalytics.vm
per Google:
"The USER_ID value should be a unique, persistent, and non-personally identifiable
string identifier that represents a user or signed-in account across devices."
> SAK-29665 modifying to send internal Sakai user id instead of eid 

- samigo/samigo-app/src/webapp/css/tool_sam.css
On the Samigo preview view there is a message presented on the top and bottom of the page in grey stating "Assessment Preview - This is an example student view of this assessment ". The color set for this item is web grey (#808080).
Standard web grey does not contrast enough to be WCAG compliant. Removed the color definition all together so the message inherits the standard page colour (black by default).
The message could be made a more distinctive colour but the fact that it's at the top and bottom of the page and bordered already makes it pretty distinct.
See https://jira.sakaiproject.org/browse/SAK-29703
> SAK-29703 Remove grey for Samigo preview message

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
- reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
- reference/library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js
SAK-29714 : Removing JQuery mobile js which is added to provide handle swipe event in mobile view to open tool and sites drawers,  due to conflict with JQuery UI it is breaking other functionality around sakai.
> SAK-29714 : Removing JQuery mobile js to fix the errors due to conflict with JQuery UI

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
https://jira.sakaiproject.org/browse/SAK-29719
Add API method to get visible course sections and groups for the current user. This applies the permission filtering that is configured in gradebook.
This is already inside the gradebook and needs to be exposed as an API so it can be used elsewhere, particularly in subsequent permission calls that require this list.
> SAK-29719 add API method to get viewable sections and groups

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://jira.sakaiproject.org/browse/SAK-29720
The submission list for an anonymous assignment can be filtered by group. This allows you to infer identities by controlling group membership. This filter should be hidden/not rendered for anonymous assignments.
> SAK-29720 group filter can reveal identities for anonymous assignments on the instructor submission list UI

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-29713
When the instructor or the student views an assignment submission, there is a submission history (introduced in Sakai 10).
If instructor01 submits on behalf of student01, the history displays something like:
"Fri Jul 17 16:47:20 EDT 2015 Jane Smith (student01) submitted"
It should reflect that the instructor submitted on the student's behalf. The linked PR will change the format of the history message:
"Fri Jul 17 16:47:20 EDT 2015 John Doe (instructor01) submitted on behalf of Jane Smith (student01)"
However, it should be noted that these strings are generated at the time of submission and then saved in the XML of the submission object in the database, rather than being generated on the fly. Due to this limitation, this fix will only work …
> SAK-29713 assignment submission histories should reflect whether the instructor submitted on behalf of the student

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
SiteAction now checks two properties, sitemanage.grant.anon/auth to determine whether anon and
auth roles are permitted.
> SAK-29695 Hide/show Additional Access elements

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-29730
1) set sakai.property to use two (or more) decimal places: assignment.grading.decimals=2
2) create a new assignment graded by points
3) go to grade a student
4) enter a grade with more decimal places than you set the sakai.property to
5) save
6) notice the warning at the top of the page repeats itself:
"Alert: Please use only 2 decimal place(s) for the grade field. Please use only 2 decimal place(s) for the grade field."
> SAK-29730 too many decimal places warning is shown twice

- kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
- site-manage/site-manage-participant-helper/src/bundle/org/sakaiproject/site/tool/participant/bundle/sitesetupgeneric.properties
- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java
- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/AddProducer.java
- site-manage/site-manage-participant-helper/src/webapp/WEB-INF/requestContext.xml
https://jira.sakaiproject.org/browse/SAK-29711
"There is code behind the "Add Unofficial Participants" feature to disallow adding unofficial participants whose email addresses end with with any of the "invalid" domain suffixes defined in sakai.properties.
However, the property it obeys has been removed from default.sakai.properties (invalidNonOfficialAccountString), and there is now a new one that is being referenced from a few other tools (invalidEmailInIdAccountString).
The linked PR alters the code in site-manage to reference this newer property, rather than the old one that is no longer present in default.sakai.properties, so that all the tools are obeying a single property for invalid domain suffixes."
> SAK-29711 add unofficial participants allows emails addresses with invalid domains to be invited to a site

- site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages.properties
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageDelProducer.java
- site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageEditProducer.java
https://jira.sakaiproject.org/browse/SAK-29737
When in Site Info -> Page Order, if you try to delete a tool that somehow has a null page ID, you will get the hardcoded text from the markup file, rather than the actual error message that should be displayed ("A valid 'page ID' is required").
We're not sure how the page IDs are null, but we have seen this happen in production. I have been able to recreate the scenario using a debugger to make the page ID null to satisfy the code path to generate the error message.
The problem is two fold:
1) it's populating a UIOutput component instead of a UIMessage component; this subsequently fails to find the text of the given message bundle key. This results in an NPE in the logs and the hard-coded text from the markup file being displayed to the end …
> SAK-29737 dummy text appears to user on Site Info -> Page Order

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- content/content-impl-providers/impl/src/java/org/sakaiproject/content/providers/BaseEventDelayHandler.java
- content/content-types/src/java/org/sakaiproject/content/types/FileUploadType.java
- kernel/api/src/main/java/org/sakaiproject/hikaricp/jdbc/pool/SakaiBasicDataSource.java
- kernel/api/src/main/java/org/sakaiproject/tomcat/jdbc/pool/SakaiBasicDataSource.java
- kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
- kernel/component-manager/src/main/java/org/sakaiproject/component/impl/SpringCompMgr.java
- kernel/component-manager/src/main/java/org/sakaiproject/util/ComponentsLoader.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/UsageSessionServiceAdaptor.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/FormattedTextImpl.java
- providers/jldap/src/java/edu/amc/sakai/user/JLDAPDirectoryProvider.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/job/SeedSitesAndUsersJob.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
By logging exceptions using ERROR, we can use log4j.properties to send exceptions to a centralized exception reporting system like Sentry.
> SAK-29663 log exceptions using ERROR instead of WARN

- kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java
- kernel/api/src/main/java/org/sakaiproject/site/cover/SiteService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockSiteService.java
- user/user-tool/tool/src/java/org/sakaiproject/user/tool/UsersAction.java
https://jira.sakaiproject.org/browse/SAK-29570
"Unenrollment message does not appear or is not accurate if all/some of the user's memberships are in unpublished sites.
This makes use of the new SelectionType.MEMBER introduced in KNL-1023."
> SAK-29570 enrollment check for user deletion misses unpublished sites

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_uploadAll.vm
https://jira.sakaiproject.org/browse/SAK-29745
go to Assignments
create an assignment
click the Grade link from the table for that assignment
click the Download All link or the Upload All link
click the Cancel button
You'll get the following message:
You have chosen to download student submissions. If you encountered a problem downloading all submissions, click on the following link:
Download all link
This is wrong because you've cancelled. The message appears when you click Download as expected, but it shouldn't when you click Cancel (especially Cancel from the Upload page).
> SAK-29745 clicking the 'cancel' button on the assignments 'download all' or 'upload all' still displays the link to download

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-impl/pack/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-29757
When a student gets a notification that their assignment has been graded it looks like this:
> Site Title: Project Site 017B
> Site ID: d3e634a6-73cc-4194-8c71-bbfeb5bdc74f
> 
> Your submission to assignment "Asn B" has been corrected. Please go to Project Site 017B to view details.`
Provide a link to the assignments tool in the site, and change the strange phrase "has been corrected" to "has been graded".
These changes also apply to the emails when resubmissions are allowed, and the email a student gets to notify them that a grade has been released.
> SAK-29757 assignment's grading notification emails need some improvements

- cloud-content/pack/src/webapp/WEB-INF/components.xml
- pom.xml
The cloud-content Spring beans require configuration to work and spring will create then even if they are not used by any other beans. To prevent them being created and failing the startup we set them to be lazily inited.
> SAK-29519 Mark the cloud content beans as lazy.

- kernel/component-manager/src/main/java/org/sakaiproject/component/api/ComponentManager.java
- kernel/component-manager/src/main/java/org/sakaiproject/component/cover/ComponentManager.java
- kernel/component-manager/src/main/java/org/sakaiproject/component/impl/SpringCompMgr.java
This means you don’t have to cast when supplying a class to the component manager that you would like an instance of.
> KNL-1373 Add generics support to the ComponentManager.

- usermembership/tool/src/webapp/usermembership/css/usermembership.css
- usermembership/tool/src/webapp/usermembership/js/usermembership.js
- usermembership/tool/src/webapp/usermembership/sitelist.jsp
https://jira.sakaiproject.org/browse/SAK-29762
The middle menu options, "Set Selected to Inactive/Active" can be slow and thus would benefit from disable controls and activating a spinner.
The spinner will be overlayed on the button, rather than being an element in the DOM.
> SAK-29762 user membership -> site list -> action menu needs spinners

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
https://jira.sakaiproject.org/browse/SAK-29758
In a site where you have a mix of both anonymous and regular assignments:
1) go to Assignments -> Grade Report
2) type the name/id/email of any student in the list into the filter text box
3) click the 'Find' button
4) form submits, page refreshes, filter is not applied and the filter text box is now gone
The problem is that the code to determine if there's an anonymous assignment (and conditionally not render the filter and group selection) is only checking the assignments on the current page. It should rather be checking the entire collection of submissions for all assignments.
> SAK-29758 assignments -> grade report -> filter by name/id/email doesn't work in mixed (anonymous and regular assignments) scenarios

- authz/authz-tool/tool/src/webapp/css/authz.css
- authz/authz-tool/tool/src/webapp/js/authz.js
- authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions.vm
https://jira.sakaiproject.org/browse/SAK-29759
In the permissions helper UI, the "Undo Changes" link should be a button; links perform navigation to a new interface whereas buttons perform an action on the current page.
> SAK-29759 Permissions helper -> 'Undo Changes' link should be a button

- master/pom.xml
The codehaus plugin repository isn’t needed any more and currently it’s causing build problems, so we should just drop it.
> SAK-29768 Remove unused codehaus plugin repository.

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
References to question pool item ids were changed from String to Long in 10.5. Line 472 tries to get from the hash using Long item id, but it was inserted as a String, so no questions were being added to the QuestionPool.
> SAM-2601: Questions do not copy when copying question pool

- usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/SiteListBean.java
https://jira.sakaiproject.org/browse/SAK-29773
If you have a non-provided student in a provided site (added manually rather than in the roster), the User Membership tool will fail to flip the user to active/inactive. It will rather remove the enrolment for that site for the user.
The problem is with the provided check only checking if the site has a provider ID, rather than checking if the user is provided in the realm.
> SAK-29773 user membership active/inactive toggle has problems with non-provided students in provided sites

- assignment/assignment-tool/tool/src/webapp/js/assignments.js
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-29777
Currently in some browsers, when the button is disabled, you can still click on it and get an animation of sorts. This is because the 'active' class is still applied on the button.
The JavaScript to enable/disable the button based on assignment selection should also be adding/removing the 'active' class from the button as well.
> SAK-29777 assignment list 'remove selected' button should not have class='active' when disabled

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java
If the charset which zip used is not UTF-8, Sakai cannot expand it in content tool. This patch will allow administrator to add extra charsets in sakai.properties.
There is a test zip file in the according JIRA ticket.
> KNL-1221 Add support for expanding zip file which is not encoded with

- usermembership/tool/src/webapp/usermembership/sitelist.jsp
https://jira.sakaiproject.org/browse/SAK-29794
1) Select All
2) Deselect All
3) Manually select any number
4) Use any of the actions
5) Nothing happens because the backing bean thinks nothing is selected.
The problem is that the value attribute isn't being updated on click of the actual checkbox. When the form is loaded for the first time, all the checkboxes have a value="true". The select all/deselect all/invert selection JavaScript functions update the checked and value attributes accordingly. So you deselect all, and all the checkboxes have value="false". Then you go and manually select any number, but their value attribute remains false. So when you go to perform any of the actions, the backing bean thinks that none of the items are selected.
Adding some simple JavaScript to the …
> SAK-29794 manual selection of checkboxes in user membership -> sitelist.jsp doesn't work

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-29780
Deleting an assignment gives an error like:
> Alert: Can not find the assignment '/assignment/a/130370e6-a421-4dba-bf32-06df27a38820 /78fed328-2108-4ed7-9901-91f67bdf69dd'. Can not find the assignment '/assignment/a/130370e6-a421-4dba-bf32-06df27a38820/78fed328-2108-4ed7-9901-91f67bdf69dd'.
And leaves you on the delete page. The assignment is, however, deleted. A side effect of this bug is that assignments associated with gradebook items will not remove the gradebook item when the assignment is removed. It will leave orphaned gradebook items which cannot be deleted from the Gradebook tool.
The problem is the algorithm responsible for deleting all the data related to an assignment. It ran in the following order:
1 delete calendar events …
> SAK-29780 error when deleting assignments

- assignment/assignment-tool/tool/src/webapp/js/assignments.js
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-29804
On the assignment list and assignment list by student you can effectively click links such as the grade, edit, student expand (list by student). This has the effect of duplicating the cloned controles (list by student) until the page is reloaded. On the main assignment list page, it has the effect that you're not sure where you'll be taken. Maybe it's the last thing you clicked? Maybe not. A simple solution is to update the JavaScript algorithm to 'disable' a set of links limited by the name attribute.
> SAK-29804 assignments -> update disableControls JavaScript to include links by name attribute

- site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/impl/SiteManageGroupHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
https://jira.sakaiproject.org/browse/SAK-29803
If you create a group and then create another, the second group is pre-populated with the previous group's members.
memberList needs to be re-initialized in the resetParams() function.
> SAK-29803 group membership is too sticky when creating new groups

- site-manage/site-manage-group-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroup/rsf/GroupListProducer.java
- site-manage/site-manage-group-helper/tool/src/webapp/content/js/util.js
- site-manage/site-manage-group-helper/tool/src/webapp/content/templates/GroupList.html
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupListProducer.java
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/js/util.js
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupList.html
https://jira.sakaiproject.org/browse/SAK-29802
If you select all, uncheck one box, then select all again, then select none, the Remove Checked button is still enabled.
If you press the button, you get a missing key error:
[missing key (mre): org.sakaiproject.site.tool.managegroupsectionrole.bundle.Messages Please choose at least one group to be deleted.]
> SAK-29802 group list select all/none is buggy; missing key error when click remove with no groups selected

- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/WEB-INF/requestContext.xml
https://jira.sakaiproject.org/browse/SAK-29776
Improve the performance by cutting out the CMS and UserDirectoryService calls in favour of using the realm. This reduces code and eliminates the dependency on the CMS.
> SAK-29776 improve performance of auto groups by roster

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookPermissionServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
From: https://github.com/steveswinsburg/gradebookNG/issues/196
Category subtotal percentages (within the subtotal columns/student summary/student view and when calculated in the Course Grade) are reflecting null values, calculating them as 0's.
E.g., A category contains two items, each worth 100 pts. Student receives a 90/100 on one item, with no value supplied to the second. Category subtotal should display as 90% (90/100), but is instead displaying as 45% (90/200).
GB1 ignores null values in order to give subtotal/course grade calculations based solely off of entered grades.
https://jira.sakaiproject.org/browse/SAK-29845
> SAK-29845 course grade calc error

- rwiki/rwiki-model/src/java/uk/ac/cam/caret/sakai/rwiki/model/RWiki.hbm.xml
- shortenedurl/api/src/java/org/sakaiproject/shortenedurl/hbm/RandomisedUrl.hbm.xml
These indexes will all cause stacktraces when starting Sakai with auto.ddl enabled. It's impossible to put an index on a 4000 char column in MySQL:
"By default, an index key for a single-column index can be up to 767 bytes. "
http://dev.mysql.com/doc/refman/5.6/en/innodb-restrictions.html
> SAK-26327 remove indexes that are impossible because of column length

- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
Just added predictable order, cannot reproduce failure over 150 tests run
> SAK-29226 - Intermittent test failures in sitestats

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookPermissionService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookPermissionServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/AssignmentDetailsBean.java
- gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookDependentBean.java
- gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/OverviewBean.java
- gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/RosterBean.java
- gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/ViewByStudentBean.java
The methods `getCategoriesForUser` and `getCategoriesForUserForStudentView` accept a category type parameter but it is unused.
There is also a bunch of commented out code associated with it. This will be removed to make this API simpler to use and easier to modify.
> SAK-29866 Remove unused categoryType param from GradebookPermissionService API calls

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GraderPermission.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
The addition of the view_course_grade permission needs the other permission checks to be tweaked so that they specifically test for the permission they desire.
This is because the methods getPermissionsForUserAnyCategory and getPermissionsForUserAnyGroup check for any category/group that have null values, and assume that the user has permission, however the view_course_grade permission check explicitly sets null values for its fields as it doesn't apply to a specific category or group.
So this change will adjust those two methods to check for the view and grade permission explicitly. The permission checks where categories/groups are specified are unaffected.
> SAK-29867 Correct the view course grade permission check to not conflict with existing permission checks

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
This is only a problem when
1. admin using Worksite Setup tool within !admin site;
and 
2. there is at least one LTI tool with siteId associated with it.
> SAK-29859 avoid NPE error when there is a LTI tool with site id associated with it

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
I don't feel like this log message is very useful in a normal case anymore and on the demo it creates a lot of useless messages currently when the DelegatedAccessSampleDataLoader (and some of our other jobs) manipulates the roles on nightlies when demo is true.
> KNL-1256 - Lower BaseAuthzGroup logging level

- reference/library/src/webapp/editor/ckeditor.launch.js
This commit has two changes. This makes the re-position code happen after calling the "onShow" of the method (which some actually re-position the plugin) and it also positons the dialog only 25% of the height of the box, which was sometimes a problem when maximizing the dialog in some places. This is all just a temporary hack for iFrames that hopefully can go away in 11.
> SAK-29830 - CKEditor plugins aren't working full screen

- samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
The retract date enabled/disabled behaviour has been unified in both cases (working and published copies)
> SAM-2616 Retract date is disabled when late submission are not accepted

- sitestats/pom.xml
- sitestats/sitestats-impl/pom.xml
The newer(standard) maven plugins seem to work fine, and surefire will show the stack trace by default of the failed test on the console. This means when the CI server fails you can see where it failed.
> SAK-29226 Use the standard maven plugins.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
This had a problem where it had
if (oldItem != null && !oldItem.equals(newItem) ||
//Check all the maps
fibMap.get(oldItem.getPublishedItemId()) != null
oldItem was null, but it still went through to check oldItem.getPublishedItemId()
This splits up those two checks better. It was failing while taking the assessment.
> SAM-2241 - Problem with delivery on mark for review

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
The old logic of getting siteId via while loop might cause endless loop for those ids with format of '/usr/' or '/my', which are valid entity request format.
> SAK-29814 get site id only from site collection id

- .travis.yml
travis-ci.org is currently still using maven 3.2 which doesn't read the .mvn folder for JVM options.
JVMs typically limit themselves to 1/4 of the available memory which on travis-ci is 3Gb so we're only getting about 768MB of available heap which is causing intermittent build failures.
> NOJIRA Increasing our memory to maven.

- reference/library/src/webapp/editor/ckeditor.launch.js
The CKEditor autosave feature invalidates the users saved cache by using
a jquery selector that identifies when a successful operation occurs.
> SAK-29838 Update ckeditor autosave invalidation selector

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
Okay, it seems like the problem here was there was this code that was adding all of the mark for review items into the add set. It was even adding in the "special" items adding as a duplicate that it shouldn't have when it called an "addAll" here. 
This was a fix way back on SAM-1301 but it seems like it didn't account for the special case of rationales. I've tested this locally (also SAM-1301) and looks to work as expected.  I also added back in the change to SAM-2185.
> SAM-2241 - Third try at this, seems like this is finally it

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
The current method to get the category average is geared around an instructor. It doesn't work for a student due to the call to get the assignment list form the categorydefinition, and fails permission checks.
This ticket will add a new method to allow a student to get this info.
https://jira.sakaiproject.org/browse/SAK-29891
> SAK-29891 Add API method to get category average scores as a student

- kernel/kernel-impl/pom.xml
- master/pom.xml
- search/search-impl/impl/pom.xml
Tika is deploying asm-debug-all, should not have asm and asm-debug-all
deployed
Couple other jars that should have been set to provided.
> SAK-28001 Remove duplicate asm jars from being deployed

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionMessageBean.java
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forumsOnly/dfForums.jsp
Because of the performance issues (SAK-29654) with the new Forum Ranks feature that we got in Sakai 10 (SAK-24854), we had to create a property to disable the Ranks system to avoid our database from crashing under the hundreds of thousands of queries per hour and the millions of CPU-intensive buffers each hour attribute to the Ranks feature.
However, because of the lack of time over the summer, we decided to implement this property in two phases:
Phase 1 - disable the Ranks page from the UI so that instructors and maintainers cannot add Ranks (this ticket)
Phase 2 - disable the Ranks feature throughout the code (SAK-29936)
This ticket will contain the patch for Phase 1.
> SAK-29934: Add sakai.property to disable Forums Ranks feature - Phase1: disabling the Ranks page

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
https://jira.sakaiproject.org/browse/SAK-29823
After stepping through the code in debug mode, the properties are actually loaded properly. The problem is the implementation in the velocity template.
Whoever updated the property and loading code didn't check the velocity template to see how it was implemented to obey the property. The conditional was effectively the opposite of what it needs to be:
> #if (!$!existingSite || $!siteTitleEditable)
The code shouldn't care if the site exists already or not, we want it to obey the property regardless. Also, it shouldn't be rendering the input field if the site title is NOT editable; it should only render it if it IS editable:
> #if ($siteTitleEditable)
> SAK-29823 site type title not editable sakai.property not being obeyed

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java
A simple patch to reset the file list after the D&D upload has finished.
> SAK-29829 - Drag&Drop notifications are not rightly cleaned up.

- reference/library/src/webapp/skin/tool_base.css
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
https://jira.sakaiproject.org/browse/SAK-29949
The message you receive when making a site joinable:
"Important: People who join your site can access the materials on your site. Sites with sensitive materials should not be made joinable."
This message is using the "messageValidation" class, which now makes it look like an error. In our institution's flavour of Sakai, we changed this to the "messageWarning" class, but this class was removed from reference's tool_base.css for whatever reason.
The linked PR reintroduces this class to tool_base.css, and changes the class on the element in chef_site-siteInfo-editAccess.vm.
> SAK-29949 joinable site setting information message is using the wrong style class

- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/js/info.js
- samigo/samigo-app/src/webapp/jsf/author/authorIndex.jsp
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_noHeader.jsp
https://jira.sakaiproject.org/browse/SAM-2634
Currently in trunk, if you release a test/quiz to any number of groups, the 'Release To' column appears blank. The markup to show/hide the groups the quiz is released to is there, but because of the introduction of the '.collapse' class in morpheus-default/tool.css, it is hidden (display=none). Changing class names in sam_tool.css will rectify this regression.
Another regression introduced by morpheus is setting the default list style for ol's and ul's to none:
ol, ul {list-style: outside none none;}
We have to override this in sam_tool.css so that we can have bullet-ed lists again.
The second issue is the style class being used when the group(s) have been deleted, to inform the maintainer that the quiz is effectively useless. Currently it …
> SAM-2634 release to groups messaging issues in Samigo

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/ifc/GradebookServiceHelper.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
With this modification, grader's comments are also sent to Gradebook tool besides scores. 
Students will see these comments in the associated item of Gradebook tool. 
Comments will be sent automatically if the option to send to Gradebook is selected, as currently happens with scores.
> Changes to send comments to Gradebook automatically. SAM-1597

- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
The problem is caused when ToolManager.getCurrentPlacement() is null.
> SAK-29950 Internal Server Error when click over All site files

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
This will be beneficial for anyone who needs to report on grades across multiple gradebook items for multiple students with performance in mind.
Method definition:
/**
* This method gets grades for multiple gradebook items with emphasis on performance. This is particularly useful for reporting tools
* @param gradebookUid
* @param gradableObjectIds
* @param studentIds
* @return a Map of GradableObjectIds to a List of GradeDefinitions containing the grade information for the given
* students for the given gradableObjectIds. Comments are excluded which can be useful for performance.
* If a student does not have a grade on a gradableObject, the GradeDefinition will be omitted
* @throws SecurityException if the current user is not authorized with gradeAll in this  gradebook
* or cannot grade a …
> SAK-29933: Add getGradesWithoutCommentsForStudentsForItems to GradebookService

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java
The basic idea is that advisors do ancillary tasks: e.g., insert a privacy record into a separate table. But the advisor should never be able to throw an error (e.g., a Hibernate constraint error) that will cause the entire save to fail.
> KNL-1385 wrap calls to advisors in try/catch to avoid an advisor preventing a save

- common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java
The setCacheable is nice for performance, but it doesn't invalidate when updated..... It only invalidates when stale. This can result in constraint errors.
> SAK-29973 dont set query to be cacheable because no invalidation

- kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
Note that the issue has been shown and the patch tested in Sakai 10, as we don' have a sakai 11 system with separate content hosting domain.
> KNL-1384; fix clickjack protection for separate content domain

- config/configuration/bundles/pom.xml
Changed the pom.xml for config folder.
Added specific delimiter $ and removed '@' from the list and defaultdelimiter is set to false
> SAK-29980 Fixed the sakai build for the config module.

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/CollectionAccessFormatter.java
In the collectionAccessFormatter , it was previously checking hidden attribute value for each of the child items. I've moved the line setting css, above the for loop iteration of the members. So it now sets inactive based on root and not on each of its members.
For the scenario where there is a folder which is not hidden but which has one of its child item visible, I've again checked the visibility inside the for loop and set the visibility only if the child items visibility is explicitly set to hidden
> SAK-29833 Setting inactive class based on root element's availability

- syllabus/syllabus-app/src/bundle/org/sakaiproject/tool/syllabus/bundle/Messages.properties
- syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/entityproviders/SyllabusEntityProvider.java
- syllabus/syllabus-app/src/webapp/js/syllabus.js
- syllabus/syllabus-app/src/webapp/syllabus/css/syllabus.css
- syllabus/syllabus-app/src/webapp/syllabus/edit.jsp
- syllabus/syllabus-app/src/webapp/syllabus/edit_bulk.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main.jsp
- syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
- syllabus/syllabus-app/src/webapp/syllabus/read.jsp
https://jira.sakaiproject.org/browse/SAK-29988
This PR introduces the following usability improvements:
* add/change buttons on Add Item and Bulk Add Item to be explicit regarding published status (Instead of one button obeying the sakai.property, there are now three buttons for each UI; Add and Publish, Add, and Cancel)
* will still fall back to sakai.property if the 'published' parameter is not included in the REST call
* change occurances of the word 'Post' to 'Publish' for consistency across interfaces
* add the prefix 'DRAFT - ' to the non-editable portion of a draft item's title, to visually reinforce the idea that the item is not published (this is how other tools handle this as well, such as Assignments, Announcements and Forums)
While I was in the project/files, I fixed up some …
> SAK-29988 Usability improvements for Syllabus

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
- msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/RankManagerImpl.java
- msgcntr/messageforums-components/src/webapp/WEB-INF/components.xml
Because of the performance issues (SAK-29654) with the new Forum Ranks feature that we got in Sakai 10 (SAK-24854), we need to create a property to disable the Ranks system to avoid our database from crashing under the hundreds of thousands of queries per hour and the millions of CPU-intensive buffers each hour attribute to the Ranks feature.
However, because of the lack of time over the summer, we decided to implement this property in two phases:
Phase 1 - disable the Ranks page from the UI so that instructors and maintainers cannot add Ranks (SAK-29934)
Phase 2 - disable the Ranks feature throughout the code (this ticket)
For this ticket, create a property (or replace/reuse the property from SAK-29934) that disables all of the Ranks feature code from Forums for institutions that don't …
> SAK-29936: Add sakai.property to disable Forums Ranks feature - Phase 2 - disabling the feature in code

- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
https://jira.sakaiproject.org/browse/SAK-30002
Some parts of the joinable sets UIs do not trim user input. For example, you can enter " 1" for number of groups or number of users per group when generating groups for a joinable set, and you will get a validation error.
Solution is to StringUtils.trimToEmpty() all user input fields.
> SAK-30002 joinable sets UI doesn't trim some user inputs

- reference/docs/conversion/sakai_11_mysql_conversion.sql
- reference/docs/conversion/sakai_11_oracle_conversion.sql
- site-manage/site-manage-impl/impl/src/bundle/notifySiteCreation.xml
- site-manage/site-manage-impl/impl/src/bundle/notifySiteCreationConfirmation.xml
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
https://jira.sakaiproject.org/browse/SAK-30000
There are too many instances of the site ID in the two site creation notification emails (sitemanage.notifySiteCreation, sitemanage.notifySiteCreation.confirmation). For the majority of users, they don't care or even know what the site ID is. The relevant information is the site title.
The linked PR addresses this issue, as well as some grammatical errors in the templates. I've left a single occurrence of the site ID in the message body for troubleshooting purposes, etc. I've switched out the domain in favour of the ui.service for better readability, but will fall back to the domain if ui.service is not set in sakai.properties. Also, cleaned up ETSUserNotificationProviderImpl.java a bit while I was in there.
Existing instances will need to …
> SAK-30000 site creation notification emails should use the site title instead of the site ID

- assignment/assignment-bundles/resources/assignment.properties
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
While this looks like it's low risk, I haven't been able to test it. I've tested the change in 10, but the way this message is generated changed between 10 and 11. I spent a couple of hours trying to get Turnitin running on 11 and failed. But we'll have to do it for production.
> SAK-30001; assignment create/update doesn't show Turnitin errors in UI

- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverExtendedMatchingItems.jsp
A minor change to show the crossmark instead of a blank space.
From now on, the behaviour will be:
* If the response is correct shows the checkmark
* If the response is incorrect shows the crossmark
* If there is no respones shows nothing
> SAM-2605 Show crossmark in EMI questions

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
NPE found for SAM-1408 patch contribution. The Assessment retractDate threw a NullPointerException caused by a line of code added from that patch contribution that was not necessary and needed anymore.
> SAM-1408 Fixed NPE discovered during testing

- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
By default we now disable the collection thread as it can cause tests to fail intermittently, tests can still re-enable it on a per-test basis, but most test don’t need it.
> SAK-29226 Fix intermittent sitestats test failures.

- .travis.yml
When building with travis-ci you can't see the build output in the web if it's more than 4MB. To reduce the ammount of output but still get progress indicators so the build doesn't timeout we change the logging setup. Now errors are show but much less info level logging is shown.
> Make the travis log under the 4MB limit.

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookFrameworkService.java
- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradingScale.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookFrameworkServiceImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- webservices/cxf/pom.xml
- webservices/cxf/src/java/org/sakaiproject/webservices/SakaiGradebook.java
- webservices/cxf/src/resources/applicationContext.xml
SAK-29825 New service to set the gradebook grading scales. 
This time without the SQLService, only using the edu-services/gradebook services. 
Sample call:
http://SERVERNAME/sakai-ws/rest/gradebook/createOrUpdateGradeScale?sessionid=THESESSIONID&scaleUuid=27&scaleName=newscale&grades={eee,bbb,ccc}&percents={69,31,12}&updateOld=true&updateOnlyNotCustomized=true
updateOld=true updates the old values in the actual gradebooks. It depens of updateOnlyNotCustomized=true if it updates all of them or only the ones that has never been customized by instructors.
updateOld false only update the scale definition, but not the actual gradebooks.
> SAK-29825 New service to set the gradebook grading scales.

- site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/CreateJoinableGroupsProducer.java
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/css/GroupList.css
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/js/util.js
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/CreateJoinableGroups.html
https://jira.sakaiproject.org/browse/SAK-30023
Maintainers need a way to tell who has not yet joined a group in a given Joinable Set. This PR introduces a new section in the "Edit" Joinable Set UI for exactly this purpose.
It is a collapsable/expandable div with a triangle disclosure, showing all users who have not yet joined a group in this set in the format of "<lastName>, <firstName> (<loginID>)"
> SAK-30023 create a view for Joinable Sets to see which users haven't joined a group yet

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- roster2/src/java/org/sakaiproject/roster/api/SakaiProxy.java
- roster2/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
- roster2/src/java/org/sakaiproject/roster/tool/RosterTool.java
- roster2/src/webapp/WEB-INF/bootstrap.jsp
- roster2/src/webapp/js/roster.js
A new sakai.property has been added, roster_view_connections,
which when false will hide the Connections button in the roster
view. The property's default is true, though it will be false
if profile2.connections.enabled is also false (also see
SAK-29267 & SAK-29408).
Jira ticket: https://jira.sakaiproject.org/browse/SAK-29549
> SAK-29549 Now able to hide connections in roster

- master/pom.xml
1.4.3 Fixes SMP-26 which means new deploy directories aren’t created automatically.
> Upgrade to the newer Sakai maven plugin.

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentHostingComparator.java
- kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/SortTest.java
This should fix the error in resources related to item sorting. If the priorities on a resource or collection is null then you can run into a situation where a > b, b > c, and c > a. The solution is to treat null priority as 0. This will cause these items to sort to the top which we think is appropriate because the only way the priority can be null on a resource is if it was created before priorities were introduced.
> KNL-1083: Content Hosting comparators are incompatible with java 7

- kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/SortTest.java
When there isn’t a priority sort check we fallback to sorting by display name.
Upgrade to newer jUnit to get the `assertArrayEquals(Object[], Object[])`
> KNL-1083 Additional test for fallback to display name.

- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm
https://jira.sakaiproject.org/browse/SAK-30074
In the Edit Rosters main screen, the 'Update' button should be renamed to 'Remove Selected', as all you can do with the button is remove selected rosters from the site.
Also, the button should be disabled by default, and should only be enabled when at least one roster has been selected from the list.
> SAK-30074 site info -> edit class roster(s) -> 'update' button issues

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/entityprovider/AnnouncementEntityProviderImpl.java
When the entityproducer is creating the list of announcements, It converts the attachments to the DecoratedAttachment class calling the constructor only with 2 parameters.
The constructor can be invoked with 5 parameters to have all the information of the attachment available.
> SAK-30042 Include missing properties when creating DecoratedAttachment in entityproducer

- reference/library/pom.xml
Sorry, I forgot the "SAK-30098" in the commit message.
> SAK-30098 Sakai build broken due to autoprefixer-rails gem.

- kernel/component-manager/src/test/java/org/sakaiproject/util/ComponentBuilder.java
The test would finish and then the directory would get deleted, then the next test would start up and it would use the same directory location (recreating it). Then the finalize() method on the first test would be called and this would remove the directory which was now being used by the second test.
The other option would have been to have had all the tests use a different directory, but removing the finalize() is a sensible thing todo as it could cause confusion in the future. In my tests even when a test failed I was still seeing the directory get cleaned up, it's only if the caller doesn't call tearDown() that the directory would remain.
> KNL-1396 The finalize() call would break tests.

- signup/api/src/java/org/sakaiproject/signup/hbm/SignupMeeting.hbm.xml
- signup/api/src/java/org/sakaiproject/signup/hbm/SignupTimeslot.hbm.xml
There is a problem related with LONG oracle data type. Meeting tables must have CLOB data type, instead.
If the tables don't exist starting up the server with this patch will create the tables correctly. But, if the tables already exist, it will be needed convert LONG's to CLOB
> SAK-30078 Signup fails on Oracle

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
Previously this would throw an NPE when a randomized item had no
instruction text.
Also clarifies the logic around which item types can and can't be
randomized, as SAM-1816 corrected a bug with calculated questions that
stemmed from a complicated boolean, and NYU hit a similar case locally
with the "hotspot" question type in the same piece of code.
> SAM-2674 When shuffling items, cope with blank instructions

- samigo/samigo-app/src/webapp/jsf/delivery/isRetracted.jsp
- samigo/samigo-app/src/webapp/jsf/delivery/noLateSubmission.jsp
This pattern is used in a number of places already in Samigo. Changing the display to include the time zone as well as changing the pattern to include the actual time that the item is due.
> SAM-2356 - Incorrect due date displayed

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
- samigo/samigo-app/src/webapp/css/tool_sam.css
- samigo/samigo-app/src/webapp/js/questionProgress.js
- samigo/samigo-app/src/webapp/jsf/delivery/questionProgress.jspf
Three main features were requested for the question progress panel
within Samigo. These features were:
1. Collapsible Parts
2. Supporting Linear Assessments
3. Configurable icons
1. Collapsible parts
In Samigo, the question progress (qp) side panel's parts are now
collapsible. By default, the current part's questions are shown.
Clicking on the part title in the question progress panel will show
or hide that part's questions via a sliding animation. As some parts
are now hidden, the total number of questions within a part is shown
in the part title. There is an arrow indicator which points to the
right when the part is collapsed and points down when expanded.
2. Supporting Linear Assessments
The question progress panel is now displayed for linear assessments.
The navigation ability and …
> SAM-2630 Question progress improvements.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeService.java
This is a bug fix for extended time retractDate setting. The original patch contribution used the entire site's retractDate value (if it had a value). otherwise the entire Site's dueDate value was used. The fix makes use of the extendedTime sections's retractDate value, if it does not have a value, the extendedTime's dueDate will be used (NOT the entire Site's retractDate/dueDate value)
> SAM-1408: retractDate setting update for extended time

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/FileSelectorPanel.java
In the upgrade to Wicket the code was changed to only look in the URL parameters, the jQuery File Tree plugin sends the directory in the POST body and so it was being ignored. Switching to look in both URL parameters and the POST body is how it used to work, and fixes the issue where you can’t browse resources when generating a report.
> SAK-29727 Get directory from POST body.

- providers/jldap/src/java/edu/amc/sakai/user/JLDAPDirectoryProvider.java
- providers/jldap/src/java/edu/amc/sakai/user/LDAPJSSESecureSocketFactory.java
- providers/jldap/src/java/edu/amc/sakai/user/LDAPSimpleSocketFactory.java
- providers/jldap/src/java/edu/amc/sakai/user/LdapConnectionManagerConfig.java
- providers/jldap/src/java/edu/amc/sakai/user/SimpleLdapConnectionManager.java
This makes sure that you have sensible timeouts when connecting to LDAP. This is especially useful when you have multiple LDAP servers as if one goes down you want to retry again, rather than waiting 60 seconds for the pool object creation timer to fire.
> SAK-30112 Good timeouts when connecting to LDAP.

- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupAutoCreate.html
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html
https://jira.sakaiproject.org/browse/SAK-30151
* JavaScript error for group name in use doesn't post back to the server; leaves spinner and all controls disabled
* On adding regular group or auto group, controls are duplicated
These places make the spinner call in the jQuery validation methods, so the call in the onclick is not necessary.
> SAK-30151 A few bugs with the new spinner used in the Manage Groups interfaces

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-30152
The spinner that appears when you click any of the links for an assignment ("Edit", "Duplicate", "View Submissions", "Grade") presents a spinner beside the links. This spinner is injected, and causes the content in the table to shift to the right to make room for this.
Avoid this 'bouncing' effect by using the pre-allocated spinner technique.
> SAK-30152 Fix some bouncing caused by injecting a spinner; replace with pre-allocated spinner

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/snippets/siteStatus-snippet.vm
When viewing just the contents of the page (without the surrounding site and page navigation) you always get the message saying a page is unpublished when it isn’t. When in the context of a page I’m not sure that want to be seeing this message anyway so I’ve just made it that it doesn’t incorrectly show the message on page URs.
A good example of the page to test with is the features page on the gateway site.
http://localhost:8080/portal/page/!gateway-300
http://localhost:8080/portal/site/!gateway/page/!gateway-300
> SAK-30155 Only show unpublished when it is.

- lessonbuilder/tool/src/webapp/css/Simplepagetool.css
This change is to allow CSS to change the font size, without turning the icons into weird shapes. Currently this change won't normally be visible, but if a site adjusts font size in a custom CSS, it will break the UI without this change.
> LSNBLDR-546; make icons work even if font size changed

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-settings.css
Fixes up #1408 
Hide columns via javascript via the various checkbox/radio button callbacks.
Set a default hiding strategy on load as well.
Lay out the category options horizontally.
> #1408 hide columns in category table depending on options

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
While I was in there I also found a bug whereby a programmatic change of input wasn't triggering an "onchange" event. For example, when a [0-9] key is pressed we use jQuery to set the value on the input e.g. $input.val(newValue).  In IE or Chrome this does not mark the input as 'changed'.  To resolve this we now trigger a custom javascript event and bind to this in Wicket.
Delivers #1492.
> 1492: fix external tools showing an input rather than a readonly label

- samigo/samigo-api/pom.xml
- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/MediaData.java
- samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/grading/MediaData.hbm.xml
- samigo/samigo-pack/src/webapp/WEB-INF/components.xml
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/MediaContentConverter.java
* Rename media property to dbMedia to separate database and content
hosting handling
By changing the Hibernate mapping for the media column to the dbMedia
property, we can allow getMedia to encapsulate the behavior of using
content hosting or the database. The new dbMedia property is public, so
it can still be used directly (by the DAO). When saving, any media bytes
set are saved to CHS and the dbMedia property is set to null. This will
remove the file from the database row. Subsequent reads will find that
field is null and look for the file in CHS. The previous interface and
behavior are preserved for client code.
* Add batch media conversion
The conversion runs on startup when triggered with
`samigo.convertMedia = true` in sakai.properties (or by another property
mechanism). This uses …
> SAM-2685 - Save audio uploads to content hosting

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1469.
And also clean up styling of the 'X' close link so it doesn't have an underline.
> 1469: add missing close links to popovers and restyle close link

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GbCategoryType.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
Delivers the student view fix for #1487.
Add a new enum to wrap up the category types so we don't have to use the explicit ints.
Add a method to get the currently configured category type. This is because a student cannot access gradebook settings so the earlier fix actually broke for a logged in student.
Change the student grade summary panels to use this new approach
> Suppress category info in student view when categories disabled

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Delivers #1473.
Only have the guard around the iteration of the assignments to get the grades if user is a student, otherwise get it regardless. This forms part of the workflow for dynamic updates of category scores and was preventing them from being updated, even if instructor.
> Fix category subtotal so that it now dynamically updates

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
Delivers #1529
Edit Item Details menu reinstated for external items and the fields that cannot be edited are disabled.
**Requires #1556 to be merged first.**
> #1529 edit details for external items

- assignment/assignment-tool/tool/src/webapp/js/assignments.js
- assignment/assignment-tool/tool/src/webapp/js/studentViewSubmission.js
- assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_assignment.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_reorder_assignment.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_uploadAll.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_preview_submission.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://jira.sakaiproject.org/browse/SAK-30185
I've discovered that returning false inside a method call from an onclick is not functionally equivalent to returning false in the onclick itself. This is causing some strange behaviour in certain browsers in certain conditions.
The solution is to remove the 'returnFalse' parameter from the 'submitForm' JavaScript function, and instead return false explicitly in the onclick where required.
> SAK-30185 JavaScript regression in assignments

- msgcntr/messageforums-components/src/webapp/WEB-INF/components.xml
Every time an anonymous ID is inserted into the database, it is immediately rolled back.
> SAK-30188 - Rollbacks prevent anonymous IDs from persisting in forums

- samigo/samigo-app/src/webapp/js/extendedTime.js
Working solution bug fix for the scenario explained below:
"Auto population of Extended times seems to have a bug, that imho, seems like a blocker priority because of the following use case:
Instructor creates an exception with dates, and updates the due date and retract date, but not the available date. All the date times look correct (in the web page) but, when you save the quiz, the time component on fields, the ones not updated by instructor, revert to midnight. Therefore an exam will be released to one or more students (whoever is in the exception group), earlier than is intended.
This is only not a problem if the available date is in the past, then it doesn't matter (but seems like an less common scenario)."
> SAM-1408: Auto population of Extended times bug fix

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
Fixes bug [SAK-30054](https://jira.sakaiproject.org/browse/SAK-30054). Gets rid of the ?panel parameter for the tool-reset link.
If the tool is resetting itself, why specify a panel? Shouldn't it just reload the tool itself?
> SAK-30054 Get rid of the panel param for tool-reset

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
The `updateAssignment` method has a hard restriction on not allowing edits on external assignments. This is because some fields (title, due date, total points) cannot be changed in the `GradebookService` as they would then be out of sync with the external application that manages that assignment.
External tools currently use the `GradebookExternalAssessmentService` methods however there doesn't appear to be a reason why the external assessment can't just be managed through the normal service method and those fields filtered out from the edit.
It also simplifies dependencies and means the service can handle the logic of what to update rather than each application having to manage this.
See also:
* GradebookNG PR #1529
* https://jira.sakaiproject.org/browse/SAK-30202
> SAK-30202 allow limited updates of external assignments through the GradebookService API

- kernel/api/src/main/java/org/sakaiproject/event/cover/NotificationService.java
- kernel/kernel-util/src/main/java/org/sakaiproject/util/EmailNotification.java
Note Announcements are normally marked as drafts except when using the
property import.importAsDraft=false
> SAK-30200 Announcement email notification during site import duplicate.

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
String parameter was being added in place of an array parameter. Mysql
doesn't support array types, so we can't use statement.setArray here.
Should be safe to simply append the array to the query string since it's
generated from a List<Long>.
> SAM-2692: Can't transfer more than one question pool at a time

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditPublishedSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
To avoid the unintentional addition of spaces at the beginning and at the end in the username and password in the security settings.
> SAM-2599 Trim user and password in the security settings

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
I added alternatives to:
turnitin.allowStudentView.default
turnitin.option.exclude_quoted
alt:
contentreview.allowStudentView.default
contentreview.option.exclude_quoted
This is because we shouldn't have to tell our users to set "turnitin" properties for Sakai to adjust VeriCite properties.
> SAK-29997 Add VeriCite option to set whether to exclude quotes for an assignment

- citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
'Electronic'.
when a citation is added using 'Sakai Resource Picker' it will always have a url
therefore setting it's media type as 'electronic' instead of 'unknown'.
> SAK-30228 Citation with a link to a file in Resources will be of type

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameCellPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Hi @steveswinsburg.  I've introduced GbModalWindow, an extension of ModalWindow, which adds the ability to set a `componentToReturnFocusTo` and allow multiple `WindowClosedCallback` to be set on the window (by default only allows the one and sometimes we have multiple).  
It also includes generic Javascript hooks to ensure date pickers and any modal masks are hidden upon closing any of the windows and other properties previously defined for all instances i.e.
```
setMaskType(MaskType.TRANSPARENT);
setResizable(false);
setUseInitialHeight(false);
```
> 1603: Set focus inside a wicket modal open show and then return focus logically

- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1607.
Introduces sort icons for sortable header links and also makes the cell focus outline consistent between Chrome, Safari and Firefox (Firefox previously showed a dotted line rather than a coloured border).
> 1607: Improve usability for sorting and cell focus (firefox)

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
Move the collection of the 'total points earned' inside the block that tests if the `total points possible` and `number of assignments` should be calculated so that we don't get incorrect `total points earned` vs `total points possible`.
Delivers #1590.
> #1590 Fix the calculation of the category subtotals when an item is not included in course grade calcs

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ActionSelectListener.java
- samigo/samigo-app/src/webapp/jsf/author/authorIndex.jsp
- samigo/samigo-app/src/webapp/jsf/author/authorIndex_noHeader.jsp
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
https://jira.sakaiproject.org/browse/SAM-2690
When editing a published quiz, selecting 'Preview' or 'Print' will generate a stack trace (see the JIRA). This bug is caused by the code introduced in SAM-2533, coupled with the introduction of the ability to edit published assessments.
More info in the JIRA.
> SAM-2690 IllegalArgumentException when clicking 'preview' or 'print' while editing a published assessment

- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1471 (namely to even out the spacing between the blockquote and surrounding text).
> 1471: add some padding to the comment notification blockquote

- samigo/samigo-app/src/webapp/js/extendedTime.js
Hi Steve
I noticed something different with my local datetime Locale settings... it made use of South Africa's datetime settings. After I retested on trunk after your last merge, I noticed that the Sakai nightly trunk build, had "am"/"pm" in the date input fields. My local Sakai deployment did not have that, once I updated my laptop to make use of United States Locale, mine showed the am/pm as well. I build in some logic that caters for this, and also the set a default value properly.
> SAM-1408 Updated default date value

- chat/chat-tool/tool/src/webapp/css/chat.css
Just got rid of some CSS here. It had the chat messages being incorrectly indented.
> Fix for SAK-30232. Chat messages correctly displayed now.

- content/content-bundles/resources/content.properties
- content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
- content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Introduce 'Jump to Resource' for admin user as a helper to quickly navigate to a particular collectionId.
This is a little feature that was added to the Resources tool that has been very helpful for NYU Sakai administrators.   
See https://jira.sakaiproject.org/browse/SAK-30085.
> SAK-30085 Add direct location search to Resources for admin

- content/content-bundles/resources/types.properties
“Make Site Page” is confusing because it’s not a term users see in Sakai. Web Content is something see elsewhere in the interface.
> SAK-30244 Change label from “Make Site Page”

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
…so the grading schema is updates correctly when changed more than once in the session.
Delivers #1628.
> 1628: updated the configuredGradeMappingId once the model is 'saved'

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
Delivers #1353 with a basic statistics summary, like this:
I understand the issue describes some sort of graph representation... perhaps we can add that as a nice to have outside of this requirement, which may be to just show the hard data?
> 1353: Add a basic grade statistics popup

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1560 and fixes a bug whereby the extra credit checkbox wasn't disabled when it should be.
> 1560: disabled checkbox label styles

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
There is a bug in the import from site code when using the 'replace' option in conjunction with '`site.setup.import.addmissingtools=true`
The feature is intended to both add missing tools and import the content at the same time, which is what happens if the Import from Site option "Merge" is chosen.
However, if the "Replace" content option is chosen in the Import from Site tool, then the Instructor only gets the missing tool added and must invoke the Import from Site tool a second time to import actual content.
This fix resolves the problem and ensures the tool lists are in sync.
> SAK-30299 fix bug where the replace feature was not migrating content

- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/commentedit.jsp
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/commentnew.jsp
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/edit.jsp
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/presencechat.jsp
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/macros.vm
- rwiki/rwiki-tool/tool/src/webapp/scripts/stateswitcher.js
- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
This includes a previous CSS change for getting the buttons in the RWiki editor to appear, as well as a change in the id of the rwiki textareas to prevent conflicting ids with the rest of sakai since tools are no longer being embedded in iframes.
The main issue with the handlers attached to the buttons was that the id of the textarea was set to "content" which is used elsewhere in the morpheus portal, causing a conflict. Thus, changes were being made to the wrong element.
Essentially, this change makes the functionality of the editor buttons (i.e. bold, italic, etc) work again.
> [SAK-30260] RWiki Editor Button Fix

- portal/portal-util/util/src/java/org/sakaiproject/portal/util/ByteArrayServletResponse.java
This also makes forwardResponse work in case someone sets a content length > 2 GB.
> SAK-30310; make gradebook 2 work inline

- samigo/samigo-pack/src/webapp/WEB-INF/components.xml
Before Spring 4 you could specify a bean was a singleton, in Spring 4 this attribute is no longer valid and should be dropped.
> SAM-1947 Fix for pre Spring 4 syntax.

- reference/library/pom.xml
This fixes an edge case build error with JRuby versions < 1.7.23 (versions 1.7.20, 1.7.21, & 1.7.22 affected).
See Jira for the build error debug log.
> SAK-30318 Upgrade to JRuby 1.7.24

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includePageNav.vm
- reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
Also requires a property change in sakai.properties. Defaults to true for now. I added back in logic to:
* Display a site-icon
* Allow the system to specify if it wants to allow them in the first place using a property.
portal.siteicon.allow=***
> SAK-29458 Fix for Icon URL is ignored / not displayed. Added code to display icon back.

- providers/jldap/src/java/edu/amc/sakai/user/SimpleLdapConnectionManager.java
We need to be careful to pass the right SocketFactory when constructing
a new LDAPConnection--otherwise we end up with a non-SSL socket trying
to connect to an SSL server, and the whole thing falls apart.
> SAK-30319 Fix LDAPS authentication hang

- basiclti/basiclti-blis/pom.xml
- basiclti/basiclti-common/pom.xml
- basiclti/basiclti-impl/pom.xml
- basiclti/basiclti-pack/pom.xml
- basiclti/basiclti-portlet/pom.xml
- basiclti/pom.xml
There was basically a bad entry in the dependency management section that meant that versions had been introduced for all the tsugi-util dependencies. Fixing this meant we could drop the versions that were causing the maven build warnings.
> SAK-30321 Cleanup Maven build warnings.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
We believe the original message was confusing to the users because it wasn't clear what happened. Longsight has been running with this wording change since 2.8.
> SAM-1239 - Change wording of data discrepancy message

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThreadBodyInclude.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsList.jsp
- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
If the user’s name had a ‘ in it then it would break the JavaScript that was used to activate the link and cause the tool to stop working. The users name doesn’t actually need to passed, just the ID and so we can just drop all the code that passes the users name.
> SAK-27971 Fix links to stats with user’s name has “‘“

- citations/citations-tool/tool/src/webapp/vm/citation/create.vm
- citations/citations-tool/tool/src/webapp/vm/citation/edit.vm
previously we were checking if checked attribute for the checkbox
is null or not which could be either true of false, so as per
the logic checkbox was not getting unchecked.now using 'ischecked'
> SAK-30181 Fixed the checkbox for 'use this link as title' in citations.

- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
While working in CalendarAction.java, I noticed that a constant (SECOND_PAGE_START_HOUR) was being used improperly for an unrelated value.
If a developer were to modify the constant for its intended purpose, it could result in early termination of the loops that create the calendar views.
My patch simply replaces the use of the constant with the literal value in this case of the loop to avoid the above situation.
> SAK-30329: Improper use of a constant in Calendar creation code

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/select/SelectAssessmentBean.java
- samigo/samigo-app/src/webapp/jsf/select/selectIndex.jsp
This is a quick fix to allow for a school to disable the warning because it doesn't correctly detect if only minor changes are made (See SAM-1029). I don't think that issue will be resolved anytime in the short term.
> SAM-1331 - Property to disable warning of modification to edited quiz

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
Some checkboxes went invisible with morpheus styles. The "border:none" in html style made them not visible if they were not selected.
> SAK-30114 Removed some styles writen directly in the html to make them visible again

- user/user-tool/tool/src/webapp/js/userCreateValidation.js
If you tab through the fields on a new account page on the !gateway site then the create user button correctly appears, but if you click with the mouse it always thinks the email address is invalid because it’s validator never gets called. Here we pre-check if we need to validate the email.
> SAK-30080 Activate create button when using mouse.

- gradebook/app/business/src/java/org/sakaiproject/tool/gradebook/business/impl/GradebookManagerHibernateImpl.java
getTotalPointsInternal now does not add in the points possible from an
extra credit Category to the total points possible. Thus, Extra Credit
Categories (in both Categories & 'Categories & Weighting' types) does
not affect the total points possible.
> SAK-30153 Gradebook Total Points takes into account Extra Credit categories

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1422.
Hi @steveswinsburg.  I implemented "Set Zero Score..." as per the original Gradebook rather than a "Set *arbitrary* Score..." as it didn't really make sense when different grade items have different point totals.  
Unless the it was meant to be a "Set Percentage for Empty Cells" whereby the user could define a percentage and we turn that into a corresponding point value for each item?  But then we'd need to worry about the extra credit values.  The other setungraded displays a popup when an EC value is detected and that would tricky to nigh too hard.
I've also brought across the verbiage from the old Gradebook... it's wordy but tells an accurate story.
Also included a few CSS tweaks for the dropdowns and a sneaky IE11 patch for the student filter.
> 1422: Set Zero Score for Empty Cells

- samigo/samigo-app/src/webapp/css/tool_sam.css
Update so that the clickable area for a multiple choice question answer does not include white space which causes inadvertent changes by students when using touch screens or clicking in the whitespace for whatever reason.
With touchscreen laptops this is becoming a serious problem.
> SAM-2556 - Update tool_sam.css

- archive/archive-tool/tool/src/bundle/admin.properties
- archive/archive-tool/tool/src/java/org/sakaiproject/archive/tool/ArchiveAction.java
- archive/archive-tool/tool/src/java/org/sakaiproject/archive/tool/DownloadServlet.java
- archive/archive-tool/tool/src/webapp/vm/archive/chef_archive.vm
- common/archive-api/src/main/java/org/sakaiproject/archive/api/ArchiveService.java
- common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/ArchiveService2Impl.java
When you manually create a site archive it would just create a folder. Now we give the user the option of creating a ZIP. This also means it shows up in the archives to download.
Also fixed here:
- an unclosed input stream.
- not returning when an error occurs downloading the file and rely on the container to not send back the actual data.
- better path normalisation to ensure people only download files our of the archive.
- Assume archive folder is relative to sakai.home unless an absolute path is given.
> SAK-29606 Allow manual archive to create ZIPs.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
Delivers #1353 - but doesn't include the graph (still awaiting confirmation of what the graph should be).  But does include the reformatting of the number statistics to round to 2 decimal places, inline the total points, include the percentage and drop the variance.
> 1353: reformat the grade item statistics popup

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateCourseGradeDisplayPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateCourseGradeDisplayPanel.java
Delivers #1368 by adding an "Update Course Grade Display" menu option in the Course Grade column and exposing the display settings within new dialog.
I haven't implemented a preview yet.  I was thinking we should centralise all formatting of the course grade to a single component or helper as we display the course grade in several different contexts (instructor and student summary dialogs, student page, settings previews and the course grade column). Does that seem reasonable?  Maybe something along the lines of this https://github.com/payten/sakai/commit/72658e2acb54b37c168a92967b97c55d3d6b31c9 (but with some smarts added to buildGradeMatrix so the Course Grade column can use it efficiently too).
> 1368: add dialog for updating the course grade display

- edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/VersionedExternalizable.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/BaseEntityProducer.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/GradebookEntityProducer.java
- edu-services/gradebook-service/impl/src/java/org/sakaiproject/tool/gradebook/facades/sakai2impl/XmlImportable.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/framework/GradebookNgContextObserver.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/framework/GradebookNgEntityProducer.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
- gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
Delivers #1587 
See #1587 for a bunch of test cases that I worked through.
* Enhances the existing GradebookNgEntityProducer to implement EntityTransferrer so we can handle migrations.
* Reuses the same logic as the old Gradebook in terms of migrating data, however doesn't go back and forth with XML as that was just ridiculous.
* A new backend service method has been added which takes in the shared DTOs and unpacks them into the new site.
* Added error handling so we don't throw exceptions everywhere like the old Gradebook does.
* Cleaned up a bunch of the old Gradebook EntityProducer code, removed redundant stuff and deprecated a lot of the over engineered crap. Hopefully that can be deleted one day :dancer:
> 1587 Add support to migrate GradebookNG between sites

- basiclti/basiclti-blis/pom.xml
- basiclti/basiclti-common/pom.xml
- basiclti/basiclti-impl/pom.xml
- basiclti/basiclti-pack/pom.xml
- basiclti/basiclti-portlet/pom.xml
- basiclti/pom.xml
- basiclti/tsugi-util/pom.xml
- lessonbuilder/tool/pom.xml
This leaves the packagename org.tsugi but changes the pom.xml to revert the group is to org.sakaiproject.basiclti and the artifactid to basiclti-util
> SAK-30308 - Change the groupid and artifact id back

- providers/jldap/src/java/edu/amc/sakai/user/LDAPJSSESecureSocketFactory.java
This was making 2 connections to the LDAP server and throwing one of them away without closing it.
> SAK-30112 Don’t needlessly leak connections.

- gradebookng/tool/src/webapp/scripts/gradebook-settings.js
Category sort disableSelection call was disabling ability to focus any input field in the Settings category table in Firefox. Boo.
> 1389: unable to focus input fields in category table

- kernel/deploy/common/pom.xml
This enables you to build with an oracle profile `mvn -Poracle install sakai:deploy` which as long as you have setup your credentials in your maven settings file will download the ojdbc7 jar. There are details on how to configure maven on: https://blogs.oracle.com/dev2dev/entry/how_to_get_oracle_jdbc
> KNL-1411 Add an Oracle JDBC JAR profile.

- usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/SiteListBean.java
https://jira.sakaiproject.org/browse/SAK-30361
We've had a few one-off reports of an NPE and a constraint violation exception being thrown by the bulk change status algorithm.
Although we haven't been able to reproduce this reliably, it's trivial to introduce a few extra catch() blocks to handle these specific exceptions.
> SAK-30361 user membership bulk change status needs more exception handling code

- cloud-content/impl/pom.xml
- cloud-content/impl/src/main/java/coza/opencollab/sakai/cloudcontent/BlobStoreFileSystemHandler.java
- cloud-content/impl/src/main/java/coza/opencollab/sakai/cloudcontent/SwiftFileSystemHandler.java
- cloud-content/pack/src/webapp/WEB-INF/components.xml
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- kernel/api/src/main/java/org/sakaiproject/content/api/FileSystemHandler.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/AbstractContentResource.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DefaultFileSystemHandler.java
Don't proxy large files into JVM memory to deliver them to user.... two main things here:
a) Write to a temp file if the blob asset is too large.
b) Send the user a direct link to the asset (usually a pre-signed, temporary link) instead of forcing the asset to be proxied by the Sakai JVM
> SAK-30325 send user direct link instead of proxying data from s3/swift

- reference/library/src/webapp/editor/ckeditor.launch.js
I made one opinionated change here: I remove the ability for the tool "config" variable to override height and width. I think it's bad (legacy) behavior to allow the tool to define hard-coded values. The tool should define a container and the ckeditor will fill that container. Hard-coded values present serious usability issues for small-screen devices.
Nice and tiny editor for your tiny-screen device:
CC: @botimer and @jonespm
> SAK-30370 present the ckeditor basic toolbar config to a user on a small device

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradebookSpreadsheetFixedTables.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradebookSpreadsheetFixedTables.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
First pass at delivering #1753.  The aim was to improve the client-side factors contributing to page load and page scroll performance.
Here's a breakdown of the techniques to do so... for scroll render performance:
- remove animations where possible
- move all non-necessary actions from the scroll event critical path
- simplifying the fixed header HTML
- cache element widths used in fixed column/header calculations
- move toolbar from scrollable container so it doesn't need to be positioned/rerendered and change the fixed columns to the position: fixed rather than absolute
- move all render actions into a single scroll handler, wrapped with a call to window.requestAnimationFrame() to ensure that the minimum amount of redraws per scroll event are invoked
To improve page load times: 
- move …
> 1753: improve javascript and scroll performance

- signup/api/src/java/org/sakaiproject/signup/hbm/SignupMeeting.hbm.xml
- signup/api/src/java/org/sakaiproject/signup/hbm/SignupSite.hbm.xml
- signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupMeetingsBean.java
because join is a multiplier:
for example (meetings x sites x groups x waiting list) = lots of rows returned by one query. 
Also see if we can avoid looping through every meeting to answer simple question of whether user has permission to update or delete.
> SAK-30352 use fetch strategy of select instead of join 

- reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js
A user's favorite list might contain sites that no longer exist, or for which access has been revoked. Handle these gracefully.
> SAK-30387 Handle missing sites

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Hi @steveswinsburg,
Okidokes.. take 2.
I had a go at fixing #1832 by slightly tweaking the inner loop that sets GbGradeEntry.gradeable. Now we reset categoryOk and groupOk for each permission rather than for each grade entry.
So basically, for a TA with these permissions:
The see a mixture of editable and readonly cells:
Hoping that looks ok!
> 1832: fix GbGradeEntry.gradeable so TAs can VIEW and GRADE based on their permissions

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
Delivers #1699. This fixes the issue whereby large scores were converted to scientific notation upon becoming a string.  The string is then passed through the backend where we will rely on the service to validate the score.
> 1699: ensure large scores are not converted into scientific notation

- reference/library/src/morpheus-master/js/src/sakai.morpheus.usernav.js
- reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
* While the "More sites" drawer modal is up, don't allow the page behind it to scroll
* Reposition the arrow on the user dropdown to point at the user's name
* Allow the user to click anywhere on the page to dismiss the user dropdown
> SAK-30426 Further changes to favorites and the user dropdown

- emailtemplateservice/api/src/java/org/sakaiproject/emailtemplateservice/service/EmailTemplateService.java
- emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
- kernel/api/src/main/java/org/sakaiproject/user/api/UserDirectoryService.java
- kernel/api/src/main/java/org/sakaiproject/user/cover/UserDirectoryService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
- reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/logic/ValidationLogic.java
- reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.hbm.xml
- reset-pass/account-validator-api/src/java/org/sakaiproject/accountvalidator/model/ValidationAccount.java
- reset-pass/account-validator-impl/pom.xml
- reset-pass/account-validator-impl/src/bundle/validate_newUser.xml
- reset-pass/account-validator-impl/src/bundle/validate_userIdUpdate.xml
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/account-validator-tool/src/bundle/org/sakaiproject/accountvalidator/bundle/messages.properties
- reset-pass/account-validator-tool/src/bundle/org/sakaiproject/accountvalidator/bundle/messages_en_GB.properties
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
- reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/producers/NewUserProducer.java
- reset-pass/account-validator-tool/src/webapp/js/accountValidator.js
- reset-pass/account-validator-tool/src/webapp/templates/newUser.html
- sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeUserDirectoryService.java
- user/user-tool/tool/pom.xml
- user/user-tool/tool/src/bundle/admin.properties
- user/user-tool/tool/src/java/org/sakaiproject/user/tool/UsersAction.java
- user/user-tool/tool/src/webapp/vm/user/chef_users_edit.vm
should be prompted to change their username.
Adding newUserID for template when status is userId updation.When the
account status is userIdUpdation then get the user from the newly added
method in base user directory.
Overloaded the method CreateValidationAccount to have extra field for
newEmailAddress.
In Accounts tool checks if the email address already exists . If the userId
is different from email address it sends out validation link.
Check for the locks and commit user object with new emailId.
New method is added into EmailTemplateService for Accounts to use when user
changes email address.
In EmailTemplateServiceImpl have separated the common logic from
'sendRenderedMessage' into a separate method called 'sendEmailToUsers'
which can be used by the new 'sendMessage' method.
> SAK-30144 When user changes their email address in Accounts tool they

- help/help-component/src/bundle/TutorialMessages.properties
- help/help-component/src/java/org/sakaiproject/component/app/help/TutorialEntityProviderImpl.java
- help/help-component/src/tutorial/Tutorial.config
- help/help-component/src/webapp/WEB-INF/components.xml
- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/modules/tutorial/_base.scss
- reference/library/src/morpheus-master/sass/tool.scss
- reference/library/src/webapp/js/jquery/qtip/tutorial.js
For the main Sakai tutorial, we have updated the following:
- rewrote all of the content on each tutorial panel to be more concise
- fixed the font size and styling to make it more readable
- fixed the styling of the tutorial panel itself
- changed the tutorial colour to make it stand out
- fixed positioning of all of the panels to point to the correct items
- added new content for specific new Morpheus features (e.g. breadcrumbs)
- fixed wording and positioning for narrow view, so the tutorial is mobile-friendly
- the content's wording of the tutorial now sources the Sakai instance name from sakai.properties
- fixed an issue where launching the tutorial from the Account Menu would not close the menu
- reduced the total number of tutorial panels to streamline the user experience
Please …
> SAK-29166: tutorial re-styling, re-wording, and re-configuration for Morpheus

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://jira.sakaiproject.org/browse/SAK-30450
Put the non-truncated string in the tool tip for the tab.
> SAK-30450 regression: the title attribute should show the long version in site tabs

- textarea/elfinder-sakai/pom.xml
- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/assignment/AssignmentFsItem.java
- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/assignment/AssignmentSiteVolumeFactory.java
- textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
Added Assignments in the elfinder.Displaying assignments for the current
user in a particular site thus logged in user can see assignments which they
have permissions for. Closed and indraft assignments are not shown.
> SAK-30159 Adding elFinder support to Assignments.

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
Delivers #1699.
Changes were mostly in the service:
- avoid scientific notation in `getAssignmentScoreString` by using a DecimalFormat instead of toString.
-  introduce a regex to satisfy the new score rule to match "##########.##" where the integer is maximum of 10 integers in length and maximum of 2 decimal places
I presume these changes should go in the service?  Happy to move them to the tool if that's preferred.
Also updated the error message to contain the new rule. Left deliberately wordy so somebody might suggest something better :panda_face:
> 1699: add validation for large scores and fix concurrent use error

- kernel/kernel-impl/pom.xml
- kernel/pom.xml
- master/pom.xml
ehcache 2.6.6 is no longer in the maven2 repo: "Could not find artifact net.sf.ehcache:ehcache:jar:2.6.6 in central (http://repo1.maven.org/maven2)"
If you have a tool that defines this dependency using the version from master:
<dependency>
<groupId>net.sf.ehcache</groupId>
<artifactId>ehcache</artifactId>
<version>${sakai.ehcache.version}</version>
</dependency>
The build will fail. Updated version to latest in maven2 repo. Open to suggestions if this is not the appropriate fix and/or version.
> SAK-30483 ehcache 2.6.6 no longer in maven repo

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java
Delivers #1369.
Headers are now set on the modal and not on the panel (accessibility thang).
> 1369: fix exception due to "headers" not being set

- reference/library/src/morpheus-master/sass/base/_icons.scss
I've made some changes and updates to the tool icons in Morpheus to make them more unique and applicable to the tool. Some of the tool icons were used for other tools too (e.g. fa-user and fa-gear were used a lot); some implied the wrong association (e.g. Drop Box with [Dropbox](https://www.dropbox.com/)).
I've updated tool icons for the following core tools:
- Aliases
- Assignments
- Become User
- Create User
- Drop Box
- Gradebook
- GradebookNG
- News
- Online
- Podcast
- Polls
- PostEm
- Resources
- Realms
- Sign-up
- Syllabus
- Tests & Quizzes
Please see the following screenshots from common sites comparing the former icons (on the left) and my changes (on the right).
**In a course or project site (changes on the right):**
**In Administration Workspace (changes on the right):**
**On …
> SAK-30474 Made changes to some of the tool icons for Morpheus

- kernel/kernel-util/src/main/java/org/sakaiproject/util/SiteEmailNotification.java
If a user is a member of the global review realm and has the content.all.groups permission then they get all notification message even if they aren't actially a member of the site. This prevents non-site members from ever getting a notification.
> KNL-1419 Only send notifications to site members.

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/moresites.vm
- reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
* Add display: none to the sites drawer element when it's offscreen
* Don't put the sites drawer into the DOM unless the user's logged in
* Restore the label on the search box but mark it `sr-only` to make it visible only to screen readers
> SAK-30469 Fixes for favorites drawer accessibility

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
and invalid score message.  Also show both these messages when a service error is encountered e.g.
Delivers #1699.
> 1699: update set score error message 

- samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/AssessmentGradingData.java
There is a setter for the grading attachment list on
AssessmentGradingData, which wraps an underlying HashSet. When copying,
for example, from AgentResults, where there are no attachments, the
HashSet constructor on the null value throws an
InvocationTargetException, which obscured the problem. This change
creates a new, empty set if null is passed to this setter.
> SAM-2717 - Handle copy of null grading attachments

- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
This is a small change to fetch any grading attachments for just the one
call used in the submission status view. This view does a
BeanUtils.copyProperties from the AssessmentGradingData, so the
uninitialized proxy fails because it is iterated outside the session.
Rather than trying to open the session in the view, this applies a
single fetch.
A more aggressive approach would be to mark the collection
as eager, however, this may cause other places that do not use the
attachments to do lots of additional loading. Here, we know that the
collection is traversed, so fetching is the best answer.
If there is need for optimization, a new DAO signature that explicitly
fetches grading attachments would be appropriate. If there are many
places that need the fetch, the added signature should be to …
> SAM-2724 - Fetch grading attachments eagerly

- textarea/FCKeditor/connector/src/bundle/org/sakaiproject/connector/fck/Messages.properties
https://jira.sakaiproject.org/browse/SAK-30518
This is simply a UI string for the SCORM heading when you click 'Browse Server' via the link tool in CKEditor.
The actual entity linking is implemented in https://jira.sakaiproject.org/browse/SCO-129
> SAK-30518 support for SCORM module entity linking via CKEditor

- basiclti/basiclti-api/src/bundle/org/sakaiproject/lti/impl/LTIReportingJob.properties
- basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
- basiclti/basiclti-impl/pom.xml
- basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIReportingJob.java
- basiclti/basiclti-pack/src/webapp/WEB-INF/components.xml
This allows simple reporting on instances of an LTI tool being added to sites.
If you have a centrally provisioned tool this allows a support person to get a regular email when a new instance of the tool is added.
> SAK-30510 Provide quartz job to report on LTI Tools

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
This approach addresses multiple consistency issues with "accept until"
dates for assessments. The changes are:
* When saving an assessment with "Yes, accept until" selected, but with
no date entered, set it to "No, not after due date"
* Treat assessments with "Yes, accept until" with no date the same as
asssessments with "No, not after due date" for "active" calculations
* Reflect this slightly different active/inactive status in the
authoring list (authorIndex)
* Reflect the adjusted status on the assessment list for students
(selectIndex)
This also addresses some of SAM-2738 (not considering feedback).
> SAM-2725 - Improve "accept until" date handling

- kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
This was intended as a way to get most of the benefits of a separate content hostname via Content-Security-Policy. It’s a nice idea, but it doesn’t work. The problem is that it causes PDF files not to be displayed. And it also causes plugins not to work in HTML files, if HTML is set to be displayed.
The problem it was trying to fix is really only present in Lessons by default, since /access/content downloads HTML by default rather than displaying it.
We need a more complex fix, that can’t be done in RequestFilter, because it depends upon content type, which isn’t known in RequestFilter until it’s too late.
This patch reverts the RequestFilter patch. Once it’s been accepted, I’ll consider a fix in Lessons for /access/lessonbuilder, which is where the actual issue is.
> KNL-1422: revert KNL-1402, can't download PDF or use plugins

- .gitignore
- reference/library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-30571
The default style for the dropdown menus (select) in forms is using a light gray colour (#777777), which is not appropriate and makes the options seem disabled. This PR changes the colour to $text-color.
> SAK-30571: font colour for dropdown menus in forms is too light

- reference/library/src/morpheus-master/sass/modules/tool/_menu.scss
- site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_joinable.vm
https://jira.sakaiproject.org/browse/SAK-30569
Classes 'viewNav' and 'searchNav' were at some point removed from tool_base.css, which defined how these elements are displayed.
> SAK-30569 membership -> my current sites: search box and buttons should be right aligned on the page

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/HeaderFlagPopoverPanel.java
Delivers #1366.
We now show the Set Score for null cells menu action for TAs when they can edit scores within that category.  If they try this it breaks... see #1376.  At least the menu options is there!
> 1366: update TA access to various menus in the table

- signup/tool/src/webapp/css/signupStyle.css
With the colour removed the text is black.
This 'si' style is used in 2 other places - when you copy a meeting and when you modify a meeting.  In both cases, the text was invisible because of this style so removing it helped these cases as well.
> SAK-30570: Remove white(ish) colour from text that was making it invisible

- kernel/kernel-common/src/main/config/log4j.properties
- site/sakai-message-bundle-manager-tool/pom.xml
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/applicationContext.xml
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/spring-mvc-servlet.xml
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/fragments/common.html
- site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/fragments/menus.html
Also adjust the log4j configuration to filter these log messages
```
WARN
com.github.dandelion.datatables.thymeleaf.processor.el.TdElProcessor -
Only cells containing plain text are supported, those containing HTML
code are still not!
```
> SAK-30582 Message Bundle Manager thymeleaf upgrade to spring 4

- jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ToolBarItemRenderer.java
- jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ToolBarRenderer.java
https://jira.sakaiproject.org/browse/SAK-30585
https://docs.google.com/document/d/18XDuDF4xNsEF0F-5D7s7eWc9qEXSxPbJj0vpI9mlb3M/edit?pref=2&pli=1
Preferences-2: Styling of tabs is different...and odd.
This actually affects all JSF tools that utilize the custom tags sakai:tool_bar and sakai:tool_bar_item.
The problem is that it's doing the default rendering for the 'current' toolbar item, which wraps the text in an anchor and gives it the extra 'box'. The current item should not be rendered as a link, just text within the `<span class="current">`.
> SAK-30585 fix HTML structure of navBar for all JSF tools

- user/user-tool-prefs/tool/src/webapp/css/prefs.css
- user/user-tool-prefs/tool/src/webapp/prefs/locale.jsp
- user/user-tool-prefs/tool/src/webapp/prefs/timezone.jsp
https://jira.sakaiproject.org/browse/SAK-30597
https://docs.google.com/document/d/18XDuDF4xNsEF0F-5D7s7eWc9qEXSxPbJj0vpI9mlb3M/edit?pref=2&pli=1
Preferences-3: Time zone menu is out of position and has an odd arrow on it. The issue with the arrow displaying affects all browsers, but is more evident in IE. The positioning has been fixed since the creation of this document, and is no longer an issue.
Preferences-4: Languages menu is out of position and has an odd arrow on it. The issue with the arrow displaying affects all browsers, but is more evident in IE. The positioning has been fixed since the creation of this document, and is no longer an issue.
The solution to this is to set "background: none" for the select tags, which tells the browsers to not display the drop down arrow.
> SAK-30597 preferences multi-row selects (time zone and languages) still shows the drop down arrow

- samigo/samigo-app/src/webapp/jsf/template/templateEditor.jsp
Previously the page was not being built correctly resulting in a
poorly formatted layout and missing save / cancel buttons. This change
fixes that issue.
> SAM-2783 Fix Assessment Template Settings Page

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm
When viewing a published assignment, this change shows that an
assignment is released to the Entire Site (when it is). Previously,
there would be a label "For" with an empty value when an assignment
is released to the Entire Site.
> SAK-30619 Add "Entire Site" to Assignment View

- samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
https://jira.sakaiproject.org/browse/SAM-2784
In Tests & Quizzes, when you add a part and select 'Random draw from question pool', it can take a while until the page reloads with a populated dropdown. It's very noticeable for users who have a lot of question pools. Add a spinner.
> SAM-2784 selecting 'random draw from question pool' needs a spinner

- syllabus/syllabus-app/src/webapp/js/syllabus.js
- syllabus/syllabus-app/src/webapp/syllabus/main.jsp
The problem was a mix of the title(s) not being defined in the .js file AND in the main.jsp file.
> SAK-29304 Fix for missing labels in Syllabus

- reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
The toggle button in the tool menu lacked distinction from the tools in the menu.
I've made the following changes:
- added subtle differences to the look of the button to make it visually distinct from the tools in the tool menu
- moved the arrow icon out of the vertical alignment of the tool icons in the menu
- added a slight animation to show the change to the icon's orientation between the two states
- gave the button a hover state for mouse users
- made the button slightly larger for touch users
- fixed alignment issues of the icon caused by rotating the arrow
See my "before" and "after" screenshots below for visual representation of the changes.
**Tool menu maximized**
Before:
After:
**Tool menu minimized**
Before:
After:
> SAK-30606 Styled the tool menu toggle button to work for mouse and finger

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
This move ensures that the ckeditor scripts are loaded prior to the
content of the page.
> SAK-30169 Move portal contents to after ckeditor

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java
Fixes the bug found in #1369 to hide the revert link until it's needed.
> #1369 hide the revert link until there is a value to actually revert

- reference/library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-30576
https://docs.google.com/document/d/18XDuDF4xNsEF0F-5D7s7eWc9qEXSxPbJj0vpI9mlb3M/edit?pref=2&pli=1
Preferences-1: update and cancel buttons are too close to the text of the item above
This is caused by the removal of the 'act' class from tool_base.css, which provided "padding: 1em 0". This class is used heavily across the code base (mostly on p and div tags), especially in velocity tools.
> SAK-30576 update and cancel buttons are too close to the text of the item above

- syllabus/syllabus-app/src/webapp/syllabus/css/jqueryui-editable.css
Got rid of the inline-block css rule for the buttons for End Date.
Also, someone **needs** to redo the form for entering dates. Having 6 unlabeled dropdown menus for putting in dates is extremely unintuitive.
If no one objects, I'd like to replace it with a date-picker type control.
@ottenhoff @ncaidin Thoughts on the date picker? Just for reference sake, I'll create a JIRA to track it before I start.
> SAK-30583 Fix buttons for End Date box.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.html
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Which will allows a user reset the cell to the previous score when they hit an validation/save error.
Delivers #1380 partially:
Still to do, refactor the service to return more meaningful information regarding invalid scores.
> 1380: implement revert score

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-update-ungraded.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1376.
This PR adds the section/group dropdown list to the set score modal form and updates the businesService API to take the group and only apply the action to students within that group.
I've also added a confirmation popup which alerts the user to the score and group, and also includes the previous extra credit message (if score is greater than the assignment points).
> 1376: add section awareness to Set Score for Empty Cells

- kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml
- kernel/kernel-impl/src/main/resources/antisamy/low-security-policy.xml
instead of making Sakai institutions customize their AntiSamy policies
> KNL-1426 allow Sharestream and Kaltura LTI URLs

- reference/library/src/webapp/js/headscripts.js
This is another instance of needing to load jquery UI css. Like the previous one, this raises QA issues. I'm checking into master, because the core team agreed on this approach. But I'm going to leave it to the 11 master whether to accept it for 11. If it's not accepted, I can do a patch that fixes just this one specific tool, and use that just for 11.
> LSNBLDR-601; load jquery UI css when loading js

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
https://jira.sakaiproject.org/browse/SAM-2801
The new email notification feature for Tests & Quizzes adds radio buttons to the settings but does not provide a default. This presents an error to the user if they do not select one before saving their settings.
Pre-select the "No" option to default to the current state (Samigo sends no emails to the instructor). If instructors want to be inundated with submission emails they should opt-in to this behaviour.
Cleaned up the files while I was in there, mostly removing un-necessary boxing/unboxing, redundant if/else statements. The actual change of note here to implement the default selection is the following:
`private String instructorNotification = Integer.toString( SamigoConstants.NOTI_PREF_INSTRUCTOR_EMAIL_DEFAULT );  // Default is 'No - I …
> SAM-2801 samigo email notification needs a default value

- assignment/assignment-tool/tool/src/webapp/css/assignment.css
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- reference/library/src/morpheus-master/sass/base/_icons.scss
This also resolves SAK-30184 Don't show anything in the column "for" in
"Assignment List" when the assignment is for several groups
> SAK-30639 Peer assessment information is offset by a column

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/SubmitTimedAssessmentThread.java
- samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
- samigo/samigo-impl/pom.xml
- samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java
- samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/bundle/EmailNotificationMessages.properties
- samigo/samigo-pack/src/bundle/template-assessmentAutoSubmission.xml
- samigo/samigo-pack/src/bundle/template-assessmentSubmission.xml
- samigo/samigo-pack/src/bundle/template-assessmentTimedSubmission.xml
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
https://jira.sakaiproject.org/browse/SAM-2805
* The submission information page does not tell the student they will receive an email receipt. This page has been updated to tell tell the student if they should expect an email receipt based on their current setting in Preferences (either immediate, digest, or none). It also informs them where to change the setting.
* The submission information page gives the student a confirmation number that is not included in the email for comparison/verification. The email templates and substitution values have been updated to include this information.
* As the same email templates are used for sending receipts to students AND notifications to instructors, the last sentence in these templates is inaccurate in the context of Instructor notifications. This …
> SAM-2805 improvements for Samigo submission email receipts and notifications

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
I can't tell what broke this, if it's in edu-services or here, but if the name in the gradebook didn't exactly match it couldn't grade against it.
> SAK-30428 - Unable to grade in the forums tool

- site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css
The group display heading text is now black (previously, when expanded it was white).
> SAK-30768 Fixup group display in site info

- assignment/assignment-tool/tool/src/webapp/js/studentViewSubmission.js
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://jira.sakaiproject.org/browse/SAK-30842
Clicking Cancel during an assignment submission where you have started to enter information prompts you with an are you sure confirmation. However, both buttons are disabled. Sometimes the confirmation panel is not displayed at all.
> SAK-30842 fix JavaScript for cancelling student submission and presenting confirmation dialogue

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
Delivers #1376.
Also fixed "Set Score for Ungraded" menu option not displaying for TAs with GRADE access to an assignment when categories are disabled.
> [1376] Add TA rules for filtering the group select list when setting ungraded scores

- sitestats/sitestats-tool/src/webapp/css/sitestats.css
- sitestats/sitestats-tool/src/webapp/html/widget/Widget.html
> SAK-30248 Font for stats label text is white.

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
When Site Info is used as a helper for site creation the site type setup
has to be done later on in the wizard workflow.
> SAK-30837 Must have site types before helper mode init.

- site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java
For systems that don’t use displayId the EID is returned instead by the `getDisplayId()` call.
> SAK-30832 Display user's displayId when multiple found.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
- samigo/samigo-app/src/webapp/js/authoring.js
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/editPart.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/audioRecording.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/extendedMatchingItems.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/shortAnswer.jsp
- samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
There are 3 competing features in samigo:
- Partial credit
- Negative Points
- Minimum Points
It would appear that these features were not meant to be used together,
in this change the negative points feature is disabled when on of the other 2
features is enabled.
> SAM-2731 Negative points feature was always disable

- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
- rwiki/rwiki-util/radeox/src/java/org/radeox/filter/ListFilter.java
This also resolves SAK-30750 bullet points appear outside of page area
> SAK-30751 <ol> bullet points are misaligned and missing their numbers

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Small enough to not require a JIRA? Found this in some local work when merging to 11 and it's easy to push tidy ups like this back now.
> Small refactoring to use Collections.

- lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/SimplePageItemImpl.java
This change removes protection against unreasonably long names. There will be an additional Jira to make sure the UI never generates very long names automatically. Of course if the user adds a 255 char name manually, we'll do it. See the Jira for testing instructions.
> LSNBLDR-609; allow long names of items

- content/content-bundles/resources/types.properties
Changed "web site" to "website". This displays in the Upload page of the Resources section.
> SAK-30896: "Web site" should be "website" in Resources Upload page

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgSettings.jsp
Removed the `layout="block"` that was causing the troubles
> SAK-30821 - `Activate messages` option in Messages Settings is not working

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
as pre-Sakai 11 wont have this metadata. So set a default if it doesn't exist.
Bug seemed to be introduced in #1853
> SAM-2781 fix issue with new QUESTIONS_ORDERING metadata 

- entitybroker/utils/src/java/org/sakaiproject/entitybroker/util/servlet/DirectServlet.java
There are some other calls to req.getPathInfo in entitybroker (And elsewhere) and I'm not sure if those are problematic either. I guess if any call tries to call this and dereference it without a null check it could be an issue.
> SAK-30890 - /direct results in an error page

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
A brief explanation was added to default.sakai.properties to inform
users how to migrate existing samigo media files out of the database.
> SAM-2842 Add documentation for samigo.convertMedia

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
... show the group title as a label instead. if a TA has any permissions, assume restricted access so show 'Available Sections/Groups' as the all groups title instead.
Fixes #2297
> 2297 if a TA only has one group, don't show the dropdown, 

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-duplicate.vm
https://jira.sakaiproject.org/browse/SAK-26254
The duplicate button will now be pressed when the enter key is clicked instead of the cancel button.
> SAK-26254 Duplicate site button now has focus

- reference/library/src/webapp/js/spinner.js
https://jira.sakaiproject.org/browse/SAK-31019
The spinner algorithm was creating the new element as a type of button erroneously in certain situations. The fix is to create the new element of the same type as the original, except if the original type is 'submit'.
> SAK-31019 create input element of original type when applying spinner

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-reorder.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_reorder_assignment.vm
- reference/library/src/morpheus-master/sass/modules/tool/announcements/_announcements.scss
- reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
- reference/library/src/webapp/skin/tool_base.css
This also solves SAK-31016 Reorder screen (Announcements)- display issues with column headers, due date text
> SAK-30996 Reorder screen - display issues with column headers

- user/user-tool-prefs/tool/src/bundle/user-tool-prefs.properties
- user/user-tool-prefs/tool/src/webapp/prefs/hidden.jsp
Introduces a new `hidden_instructions` I18N key that will need
localization.
> SAK-30952 Show instructions for the hidden sites preference

- gradebook/app/ui/src/webapp/css/gradebook.css
I think this is enough, background-color of the rows could be better but i think is not a priority right now. With this change it´s easy to see to wich category belongs each gradebook item.
> SAK-30638 Shading of items is confusing in student view of grades

- citations/citations-api/api/src/java/org/sakaiproject/citation/api/CitationService.java
- citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/BaseCitationService.java
- dav/dav/pom.xml
- dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
This is really two related changes to allow a reading list to be copied by webdav.  When you drag a reading list from one webdav client to another (e.g., in an attempt to copy it from one site to another), the doContent() method in DavServlet.java is first called, then the doPut() method.  I'm putting the resourceType in the session in the doContent() method (which might say that it's a reading list we're dealing with) and then in the doPut() method I'm reading this value and if it's a reading list, then I'm adding various properties to it to make it a reading list like adding '/citation' in the URL for accessing it and adding the CITATION_COLLECTION and CITATION_CITATIONs that accompany it.
> SAK-29427: Add properties to it if webdav-copying a reading list

- mailsender/tool/src/webapp/content/js/mailsender.js
subtle change in jquery, requires quotes in selectors of form [id="foo"]. Apparently they used to be optional.
> SAK-30631; Ajax not working, displays link rather than calling it

- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/macros.vm
> SAK-30749 Link & help icons are not on same line as tool tabs

- citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
electronic.
Previous fix got overridden because of the reimplementation of citations
Picker to use Resources's Picker Helper.
> SAK-30228 Citation with a link to file in FilePicker will be of type

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
Delivers #2381.
I've fixed this in the GradebookNG panel by not bothering to ask the service for a category average when the category is `null`.
It turns out `private Double calculateCategoryScore(String studentUuid, Long categoryId, List<AssignmentGradeRecord> gradeRecords)` returns average of all categorised assignments when `categoryId` is null.  My guess is that nobody ever hits this endpoint with `null`, but I was hesitant to jump in and patch it.  I'm happy to explore a patch if you think it's worthwhile?  
... this seems to fix the service:
```
--- a/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
+++ b/edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.j …
```
> 2381: if no category, then don't ask the service for the category average

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
Delivers #2272.  Fixes a bug in my code which picks out permissible groups for a TA user.
> 2272: if categories are disabled, then we only need to check the group scope when evaluating TA permissions

- gradebook/app/ui/src/webapp/js/gradebook.js
https://jira.sakaiproject.org/browse/SAK-31073
JavaScript fix to test for `undefined` as well as `null`
> SAK-31073 ability to add categories or categories and weighting information not available

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1701.  I've introduced a new less obtrusive message container for notifying users of "Saving...", "Saved" and "Errors were detected." messages. This is different to the standard session feedback component is tied to the grade editing only.  It looks like this:
> 1701: add less obtrusive message for saving..., saved, and when there's an error setting a score value

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-addRemoveFeatureConfirm.vm
https://jira.sakaiproject.org/browse/SAK-31137
Change the buttons to type="submit"
> SAK-31137 spinner not being applied to add/remove tool confirmation page's buttons

- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/CalendarBean.java
1. In a site's calendar, subscribe to an institutional calendar via the Merge External Calendars tab (see https://jira.sakaiproject.org/browse/SAK-12852 and calendar.external.subscriptions.* properties in https://qa11-oracle.nightly.sakaiproject.org/sakai/sakai.properties)
2. From the Home tool in the site, click on the day of an external event in the synoptic calendar
3. You should see the event, and there should be a link. Visit the link. Note: the data provided in https://weblearn.ox.ac.uk/access/content/public/misc/oxdate.ics does not appear to have text for the link, so you will have to use your browser's developer tools to edit the html and provide text for the link. The link appears between "Academic Calendar -" and "(worksite)". Perhaps a separate ticket should be created to put …
> SAK-31150 - Clicking on full details link for external calendar item in synoptic calendar leads to site unavailable

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
With changes in kernel.properties the default skin is now `morpheus-default` and not `default`
> The default skin is now `morpheus-default`

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1361. Namely:
- show the sort arrows when course grade is sorting
- ensure other sorts are being applied when course grade is sorting (slightly refactored so setting a sort order clears the sort order for other columns)
- removed extra padding on the course grade header cell
- tinker with the CourseGradeComparator to use the grade letter (or more accurately the index of the grade letter within the gradebook's grade scale) and then by the points earned by the student.  No padded strings needed.. I was in a JavaScript mindset and Java comparators rulez.
> 1361: course grade sorting things

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-reorder.vm
- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
1. future-dated announcements (greyed-out) do no properly appear in a well-formed row
2. something about #1 above causes content in the next row to start under the end date in the 1st row and wrap around to a newline, causing the data to be mismatched with column headings
> SAK-31180 Reorder screen - Wrong format for future-dated announcements

- kernel/pom.xml
Changes in 2.4.6
* Added Oracle SQL error code 61000 (exceeded maximum connect time) to evict connections
when it is encountered.
* issue 621: fix NPE in shutdown if invoked during initialization.
* issue 606, 610: housekeeper thread was running before all class members were
initialized, causing an unrecoverable exception and disabling idle connection
retirement (maximumLifetime still applied).
> KNL-1434 - Update hikaricp to 2.4.6

- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/base/_defaults.scss
- reference/library/src/morpheus-master/sass/base/_extendables.scss
- reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
… for all tools. Also remove margin for bootstrap input-append and btn-groups so they display as expected.
Delivers #1858, #2176 and ~~tinkers with SAK-30481~~ SAK-31187.
As `btn-default` is currently used by basiclti, pasystem and gradebookng tools, I've moved the btn-default styling from the resource specific stylesheet and to the more general extendables stylesheet.
I've also added some styles to ensure `btn-link` buttons, currently used by content and gradebookng tools, also renders more like their bootstrap counterpart.
> SAK-31187,1858,2176: Add morpheus styles for btn-default and btn-link

- reference/library/src/morpheus-master/sass/modules/tool/chat/_chat_variables.scss
I've modified the header color. I've tried to change every single place that colour was showed but Sakai has become a dark dark place to browse.
> SAK-30562 - Portal chat header colour contrast too low

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
This is a change to the gradebook service... If student has a comment but no grade add an empty grade definition with the comment so comments are always returned in the grade matrix.
Delivers #2143.
> 2143: Ensure comments are returned even if student doesn't have a grade

- reference/docs/conversion/sakai_10_6-10_7_oracle_conversion.sql
SAK-30667: Polls fails on Oracle migrated database
> SAK-30667: Polls fails on Oracle migrated database

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Being able to select the "Mark Unread" or "Mark Read" buttons even when not every selected message would be affected seems like expected behavior and seems to be the standard in other applications. Instead, this change fixes the bug of being able to remark already unread or read messages and break the UI counter.
> SAK-31106 Can Mark same message as read multiple times

- login/login-tool/tool/pom.xml
- login/login-tool/tool/src/java/org/sakaiproject/login/filter/SakaiCasAuthenticationFilter.java
- login/login-tool/tool/src/webapp/WEB-INF/xlogin-context.cas3.xml
The changes are based in the AuthenticationFilter original class from 3.4.1 client:
https://github.com/apereo/java-cas-client/blob/cas-client-3.4.1/cas-client-core/src/main/java/org/jasig/cas/client/authentication/AuthenticationFilter.java
By default Sakai will keep using CAS2 protocol to allow people update without change anything, CAS3 only works for CAS servers v4. I've added a new cas3.xml file to show you how to use CAS3 protocol in case you have a CAS v4 server available.
> SAK-31198 Upgrade CAS Client to allow new CAS 4 servers.

- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/msgHeader.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
- msgcntr/messageforums-app/src/webapp/jsp/privateMsg/topNav.jsp
- reference/library/src/morpheus-master/sass/base/_defaults.scss
This also solves:
SAK-30929 In folder, "subject" text is slightly too large, "Check All"
column too wide
SAK-30930 Viewing messages on mobile is messy
> SAK-30926 Formatting of "Previous Folder / Next Folder" buttons is off

- reference/library/src/morpheus-master/sass/modules/tool/signup/_signup.scss
- signup/tool/src/webapp/css/signupStyle.css
- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/copyMeeting.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
There are a few issues still (Padding.png):
1. the + icon and Other Sites needs padding
2. "Open meeting..." wraps all the way back to the radio buttons, should
wrap to the beginning of the text
3. Open meeting, Single slot, and Multiple slot don't need * icons
(Available to gets a * because ONE of the options MUST be selected, but
not all of them)
4. The number of slots setup is inconsistent with other parts of Sakai
> SAK-31099 Padding/spacing in "add" screen

- reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
... including an icon visible in the righthand corner of the tool menu item.
Delivers [SAK-30315](https://jira.sakaiproject.org/browse/SAK-30315) so that invisible tools will look like this:
> SAK-30315: add styles for invisible tools 

- authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions.vm
https://jira.sakaiproject.org/browse/SAK-31203
A typo was introduced in SAK-30069, changing "viewRealmIds" to "viewRealmId", which is not in the context.
Thanks again to @buckett for finding this.
> SAK-31203 typo in authz tool

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
.. rather than the pointsEarned, as pointsEarned includes extra credit scores which doesn't match the course grade display string.
I've changed the sorting algorithm to first sort on the index of the letter grade within the grading scheme and then by the calculated score.   
Delivers #1361.
> 1361: sort course grade by the letter and then calculatedGrade

- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/css/GroupList.css
- site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupAutoCreate.html
- site-manage/site-manage-link-helper/src/bundle/link.properties
- site-manage/site-manage-link-helper/src/webapp/vm/sakai_link.vm
- site-manage/site-manage-participant-helper/src/webapp/content/templates/Confirm.html
- site-manage/site-manage-participant-helper/src/webapp/content/templates/DifferentRole.html
- site-manage/site-manage-participant-helper/src/webapp/content/templates/SameRole.html
- site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
- userauditservice/tool/src/webapp/eventLog.jsp
This also solves SAK-31024 Participant list "view x - y of z items"
dropdown appears centered
SAK-31030 Mobile - Auto Groups - table of user roles has extra column
SAK-31031 Link to Parent Site - link/help buttons overlap text
SAK-31032 Mobile - User Audit Log table messy
SAK-31033 Mobile - Import From Site table has extra column
> SAK-31027 Tablet view - Edit Class Roster(s) table shows extra column

- reference/library/src/morpheus-master/sass/modules/tool/signup/_signup.scss
- signup/tool/src/webapp/css/signupStyle.css
- signup/tool/src/webapp/signup/download/downloadSelections.jsp
- signup/tool/src/webapp/signup/organizer/userDefTsBlocks.jsp
- signup/tool/src/webapp/signup/signupMeetings.jsp
This also solves
SAK-31214 CustomTimeslots not responsive
SAK-31215 Extra space at the top of the meeting list
> SAK-31213 Check boxes and radio buttons align incorrectly

- assignment/assignment-tool/tool/src/webapp/css/assignment.css
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_options.vm
- reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
This also solves 
SAK-31007 Options screen - "Please choose the display option for the
assignment grading page" text is too large
SAK-31003 Mobile - Grade - "Navigate Submissions" formatting issues
> SAK-31002 Blue info box and "viewing x-y of z items" box on same line

- citations/citations-tool/tool/src/webapp/js/new_resource.js
External citation search tools no longer open due to a minor issue in the js that binds the onclick event.
> SAK-31217: Fix bug with savecite clients

- reference/library/src/webapp/js/jquery/qtip/tutorial.js
The tutorial uses JQuery selectors to position the QTip panel.
The problem was when using this selector for the Sites panel
.Mrphs-skipNav__menu:visible .Mrphs-skipNav__menuitem--worksite a
.Mrphs-skipNav__menu was hidden before but now it´s visible but outside of the viewport. This was modified due to accesibility changes in https://jira.sakaiproject.org/browse/SAK-29771
So, what i did is add two new conditions to check if the element it´s outside the viewport to jump to the next Tutorial panel.
You can see the file with the JQuery selectors and properties for the panel here 
https://github.com/sakaiproject/sakai/blob/master/help/help-component/src/tutorial/Tutorial.config
> SAK-30900 Tutorial stops after Step 2

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
- gradebookng/tool/src/webapp/styles/gradebook-print.css
Delivers #2284 with some compromises...
Hi @steveswinsburg, @kyleblythe, @jeffpasch,
Unfortunately it's not going to be easy to duplicate the behaviour from the Gradebook Classic with JavaScript client-side sorting.  I actually found the GB1 sorting quite confusing when assignments where within their category groupings - I don't think there's a logical way to outer sort those categories when focusing on ordering the items within the grouping 😕 
Instead, I've applied the tablesorter jQuery plugin to the table, which works lovely when categories are disabled and otherwise allows sorting of the assignments within their category.  To offer something more useful to students, I've added a "Group by Category" button that allows the student to disable the grouping and sort the assignments as a …
> 2284: student grade summary sorting

- reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
of screen with white space at bottom
This also solves SAK-30937 "Add" in Folder/item missing top padding
> SAK-30934 Mobile - Clicking on dropdown causes dropdown to appear at top

- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/ClusterEventTracking.java
- Switch from an eternal thread to ScheduledExecutorService
- updated logging messages
- use Throwable to catch IO Errors
> KNL-1436 When ClusterEventTracking thread dies events stop being processed.

- calendar/calendar-bundles/resources/calendar.properties
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventEntityProvider.java
Extends #2557 and adds the same behaviour to the `/direct/calendar/my` provider and a bit of a refactor for common bits.
> SAK-31206 allow /direct/calendar/my events to be filtered by date range

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Only allowing super users, like I said on the ticket instructors should only be able to submit for the groups they belong to.
> SAK-29041 allow superusers to submit as group

- reference/library/src/morpheus-master/sass/base/_extendables.scss
Hi @juanjmerono.  This PR continues on the work done in https://jira.sakaiproject.org/browse/SAK-31187.  It'd be great to have the Morpheus team give it a once over. Thanks!
I've refactored sakai_button_color slightly so it shares padding/margin etc with sakai_button but still maintains it's custom background gradients...  Plus we also force button.btn-primary to use sakai_button_color so bootstrap buttons style as native Sakai color buttons which will fix the discrepancies reported in GradebookNG.
Also delivers #1858.
> SAK-31187 fix primary and secondary button size differences

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
- samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/AuthoringHelper.java
- webservices/cxf/src/java/org/sakaiproject/webservices/TestsAndQuizzes.java
This spelling error was creating sam.asessment.revise events instead of sam.assessment.revise events. Several other instances were in comments and one was in an abortProcessingException.
> SAM-2893 replaced spelling errors of asessment with assessment

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java
So this looks like it's working better but I can't tell if it's 100% correct yet (needs more testing)
Basically some commits on SAM-1408 (#915) looks like it broke functionality that persisted data that was in the assessment settings value map and switched it with the another map. This seemed like it resulted in nothing getting saved for a number of values in Samigo. 
Also the code to set the correct deadline wasn't being run and it had hardcoded hasTimeLimit which was completely incorrect because this value and others weren't set anymore.
I'll test some more to make sure SAM-1408 still works but I think this is going to result in a number of critical and blockers eventually being resolved.
> SAM-2856 - Various problems with timed assessments and due dates

- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
.. despite the polled changes JSON being accurate.   This bug was introduced with the performance patches.
Delivers #1840.
> 1840: fix the concurrent message not displaying correctly

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
Previously, no matter what params were set in the GradeDefinition object, the current user and current date and time would be used to set the grade object. Now, if those params are set, it will use them instead, but default to the current user and date if not found.
> SAK-31218 use grader ID and date from grade definition, if it exists

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/AccessDeniedPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/AccessDeniedPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
Delivers #1839 and will need some serious scenario testing.
1. If TA and no permissions, show message instead of GB
2. If roleswapped to TA, show message instead of GB.
3. Don't throw an exception if the lists mismatch, just filter it down. Achieves an identical outcome, user still cannot see grade if they don't have permissions.
> Bugfix/1839 TA permission fixes

- reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
> SAK-31289 Label does not wrap when text too long in Permissions

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemAuthorBean.java
I believe this issue was only that calling this version of addCollection was returning a ContentCollection rather than a ContentCollecitonEdit which was closing the edit. So it possibly was just a bug here. I'm not sure what was going on with this? Calling setPubView on the service worked, but it also was supposed to be in a hidden collection so that was fixed too.
> SAM-2745 - Hotspot question doesn't save image

- reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
- samigo/samigo-app/src/webapp/jsf/author/confirmEditPublishedAssessment.jsp
- samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
This also solves SAM-2912 Warning panel when editing a published
assesment overlaps with the navbar
> SAM-2911 Bullets do not display in Multiple Choice Answers to Students

- reference/library/src/webapp/editor/ckeditor.launch.js
Permission error while accessing the user workspace folder: Small typo
in the variable name
> SAK-31115 Permission error while accessing the user workspace folder

- portal/portal-impl/impl/pom.xml
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/BufferedContentRenderResult.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeStandardHead.vm
- portal/portal-render-impl/impl/src/java/org/sakaiproject/portal/render/iframe/IFrameToolRenderService.java
In Sakai 11+, tools can only be rendered inline (ie without iframes) if they are on a page on their own.
The portal creates a special URL directly to the tool `/portal/site/SITE_ID/tool/TOOL_ID` which treats these tools differently to tools that are on a page with other tools, and tries to render them inline, without an iframe.
When there are multiple tools on a page (which get a URL of the form `/portal/site/SITE_ID/page/PAGE_ID`), the PageHandler figures out what tools are in each column on that page and renders them within an iframe.
This contributed patch allows any tool to declare that it is able to be rendered inline and gives the portal a final chance to render that tool inline. If it can be rendered inline, its header content will be aggregated into the main HTML `<head>` section, …
> SAK-31321 Allow tools to be rendered inline when in a multi column layout

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Delivers #1336.
- Fixes categorized drag-and-drop sorting.  This was due to a bug in the service handling the udpate.. we needed to pre-sort the assignments by their category sorting rather than their "standard" sort order.
- Fixes uncategorized drag-and-drop sorting. This was due to the JavaScript not trusting the order in which the headers were rendered on the page.  Wicket renders the headers in the correct order so the JavaScript doesn't need to.  I've updated the JavaScript to completely trust the HTML and not try and re-order based on what it thinks should be the correct order (especially as this order changes as the user drags and drops things around).
> 1336: Fix issue with drag-and-drop reordering

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
published assessments
During some test we had problems saving published assessments settings from SAKAI 10.x in SAKAI 11. This new property "Display Score" did not exists in SAKAI 10 so i might be a good idea to use StringUtils.isNotBlank (just like it´s done when you save the settings for a unpublished assessment)
Saving settings in an unpublished assessment
`
if (StringUtils.isNotBlank(assessmentSettings.getAssessmentFormat())) {
control.setAssessmentFormat(new Integer(assessmentSettings.getAssessmentFormat()));
}`
Saving settings in an published assessment
`if (assessmentSettings.getDisplayScoreDuringAssessments() != null) {
control.setDisplayScoreDuringAssessments(new Integer(assessmentSettings.getDisplayScoreDuringAssessments()));
}`
IMO both should use StringUtils.isNotBlank
This …
> SAM-2918 Use StringUtils.isNotBlank when Saving Display score option in

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
Delivers #2686.
Namely:
- fix export showing on all import wizard pages
- show custom export in a modal
- original button is not affected by the custom options
- CUSTOM_EXPORT_COLUMN_PREFIX appended to custom (course grade) columns
@steveswinsburg I've added a static constant `CUSTOM_EXPORT_COLUMN_PREFIX` which you might be able to reuse when filtering columns in the import.
> 2686: Custom export options take 2

- jobscheduler/scheduler-tool/pom.xml
- jsf/jsf-tool-sun/pom.xml
- jsf/myfaces-tool/pom.xml
- samigo/samigo-app/pom.xml
- textarea/FCKeditor/connector/pom.xml
- textarea/calendar/pom.xml
xml-apis - This is defined in the master pom with a version so all the versions can be dropped and we can just pull in the version from master.
jdom - The package is different so just updated, also fixed indentation to match surrounding lines.
> SAK-31356 Fix maven warnings about relocations

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java
The gradebookservice can return -1 under certain conditions. This is now handled in the business service and formatter. Also, if we end up with null values, exclude those from being turned into strings in the UI and return the dash instead.
Delivers #2141
> #2141 prevent null/null and 0/-1 from being displayed in the course grade

- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactory.java
The elfinder code returns the time since epoch in seconds and date.getTime() returns the time since epoch in milliseconds which resulted in incorrect times.
> SAK-31340 Wrong time shown in elfinder on files.

- feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
- feedback/src/java/org/sakaiproject/feedback/tool/entityproviders/FeedbackEntityProvider.java
- feedback/src/java/org/sakaiproject/feedback/util/Constants.java
- feedback/src/java/org/sakaiproject/feedback/util/SakaiProxy.java
- feedback/src/webapp/WEB-INF/bootstrap.jsp
- feedback/src/webapp/WEB-INF/templates/home.handlebars
- feedback/src/webapp/js/feedback.js
This is a revert of the PR here: https://github.com/sakaiproject/sakai/pull/2220.
SAK-30715 has been superseded by SAK-31184
> Revert SAK-30715: Use mail.support for boxes 2+3 if no technicalAddress

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbAjaxButton.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbAjaxLink.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverrideLogPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/DeleteItemPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeLogPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/HeaderFlagPopoverPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.java
Delivers #2791, #1915.
Introduce `GbAjaxButton` and `GbAjaxLink` to offer some kind of double-click handling for each.
- `GbAjaxButton` disables the button on click and re-enables upon complete.
- `GbAjaxLink` introduces a link channel so if another request of the same type comes through it is ignored (http://apache-wicket.1842946.n4.nabble.com/How-to-prevent-a-concurrent-click-on-ajax-links-AjaxFallbackLink-td4660226.html)
- Also disable all inputs on a modal as it is closing, just in case it takes a moment for the modal to close.
> 2791: Add handling for double clicks on Wicket ajax components

- reference/library/src/morpheus-master/js/src/sakai.morpheus.session.js
- reference/library/src/morpheus-master/sass/modules/timeout-alert/_base.scss
If you are on a long page in Sakai and near the bottom (or just further down than the height of your screen) when the session timeout dialog appears, the page just goes dark - the message remains at the top of the page out of sight.
This patch makes the dialog always appear in the middle of the screen, so the user will always know what's going on. I've also centred things a bit better in the dialog. Works on wide (desktop) and narrow (mobile) views.
> SAK-31363 Positioned timeout dialog to appear in the centre of the screen no matter where on the page you've scrolled

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
Previously, the student and instructor each defined their own tables within the panels.  These tables were pretty much identical and it was only the mechanisms to get the table data that differed.  I've refactored these two panels to share a single table panel `GradeSummaryTablePanel`, so we only need to make future changes once!
I've also changed the table panel to use a `LoadableDetachableModel` for the model in the hope that it doesn't serialise all the grade data.. it doesn't need to as the panel can hit the service each time to grab the latest data.
Ultimately, this PR delivers #2671, which was to allow the 'Group by Category' feature to be available on both student and instructor views.  I store the 'Group by Category' state on the session `GradebookUISettings` so it is retained as …
> 2671: Match up behaviours of instructor grade summary view with student view

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ErrorPage.java
Fixed #2666 
To test, in GradebookPage.java, replace
`throw new RestartResponseException(StudentPage.class);`
with
`throw new RuntimeException();`
and then login as a student.
> #2666 log any stack trace that results in the ErrorPage being shown

- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactory.java
When creating a new folder from elfinder it would be passed in without a trailing slash (unless the user added it). The ContentHostingService would copy with this and add the trailing slash, however the data returned to the client would be incomplete (missing mime type) because we were looking up the details based on the wrong id.
> SAK-30903 Make sure that new folders appear.

- emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
- reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java
- reset-pass/account-validator-pack/src/webapp/WEB-INF/components.xml
- site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
- site-manage/site-manage-impl/pack/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-31383
SAK-31381 moved the loading code into the EmailTemplateService, where it belongs. This PR will remove the duplicate code from site-manage and reset-pass in favour of the centralized approach.
Cleaned up the files while I was working in them.
> SAK-31383 remove duplicated email template loading code from site-manage and reset-pass

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #2745:
- bold overridden course grades in the grade table column
- show the mapping course grade percentage rather than the calculated course grade percentage
> 2745: course grade override styling and display string changes

- help/help-component/src/bundle/TutorialMessages.properties
- help/help-component/src/java/org/sakaiproject/component/app/help/TutorialEntityProviderImpl.java
- help/help-component/src/tutorial/Tutorial.config
- reference/library/src/morpheus-master/sass/modules/tutorial/_base.scss
- reference/library/src/webapp/js/jquery/qtip/tutorial.js
Just a few minor updates to the tutorial:
Point the "Breadcrumb" modal to breadcrumb itself. Currently it's pointing to an empty space on the bar, which feels a bit like it's pointing at nothing. (image1)
Point the help modal to the help button for MOTD. It feels odd for it to be low on the screen and not at the first instance of the help button that user would see. (image2)
At the end of the tutorial, add an "Ok, Got it." button for quitting the tutorial, in the same position that the "Next" link/button appears in previous steps of the tutorial. This just feels smoother and more intuitive – vs figuring out you need to click the small X in the upper right to get out of this. (image3)
> SAK-31353 Minor updates to tutorial

- textarea/elfinder-sakai/pom.xml
- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/ReadOnlyFsVolume.java
- textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactory.java
Currently search isn’t working well do disable it in elfinder. This also disabled Zip Download in newer versions of elfinder and disables modifications in the ReadOnly volumes.
> SAK-31343 Disable search for elFinder.

- samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
screen
The label and dropdown for "Font size" were shown on separate lines
depending on screen size.
> SAM-2934 Option overlaps with Link/Help buttons in the Print assesment

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
> SAK-31339 Announcement reorder screen displays incorrectly if Display

- samigo/samigo-app/src/webapp/jsf/template/templateEditor.jsp
about:blankRemoved blank scrolling space below the footer/bottom of the page
> SAM-2933 Footer misplaced in "Edit Assessment Type"

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Delivers #2783.
Settings page now prevents user from setting up drop/keep highest/lowest if the categories assignment points differ.
Add/edit page now prevents changing the points if the category for the assignment is configured with drop/keep highest/lowest and has points that differ.
> #2783 Implement restrictions when using Drop Highest / Drop Lowest / Keep Highest

- reference/library/src/morpheus-master/sass/modules/tool/sitestats/_sitestats.scss
- reference/library/src/morpheus-master/sass/tool.scss
- sitestats/sitestats-tool/src/webapp/css/sitestats.css
- sitestats/sitestats-tool/src/webapp/html/components/SakaiNavigationToolBar.html
- sitestats/sitestats-tool/src/webapp/html/pages/ReportDataPage.html
This also solves
SAK-31077 Mobile - subpages - "viewing x - y of z" dropdown appears in
table, extra column
SAK-31080 Mobile - Preferences not responsive
> SAK-31076 Mobile - Table is not fully responsive

- signup/tool/src/webapp/signup/newMeeting/step1.jsp
- signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
For signup begin/end dates we allowed values up to 99999 but only allow enough space to display values up to 99 or 999 (depending on the page). This allows the full value to be displayed. We could have limited this to a smaller number of characters but then existing values wouldn’t display.
> SAK-31394 Make the UI match the limitations.

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
When duplicating a site remove all the provider groups even if the site isn't a course one.
> SAK-30839 Remove provider groups for all sites.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Delivers #2912.
I think this is the fix @steveswinsburg... it does assume that consumers of the `getCourseGrade` can handle both `null` and an empty `CourseGrade`.
> 2912: Fix NPE as courseGrade can be null if there are no released grade items

- assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/DbAssignmentService.java
Improve the loading time
Note when testing:
If you create a new assignment, visit the 'Grades' page before visiting the 'Grade Report' tab - the first time you view grades, dummy submission objects are created for all the assignments, so it will be slow no matter what. This ticket is only concerned with speeding up the retrieval of the submission objects on the Grade Report tab
> SAK-31130 - improved performance for retrieving submissions on the Grade Report tab of Assignments

- kernel/api/pom.xml
- kernel/api/src/main/java/org/sakaiproject/event/api/LearningResourceStoreService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseLearningResourceStoreService.java
Adding the mbox_sha1sum, account object (user's EID + Sakai instance URL), and OpenID identifiers to the xAPI Actor statement object:
```
"actor": {
"objectType": "Agent",
"name": "Joe Mama",
"mbox": "mailto:jmama@awesome.edu",
"mbox_sha1sum": "mbox_sha1_encoded",
"openid": "myOpenId",
"account": { "name": "jmama", "homePage": "https://awesome.edu" }
}
```
(BONUS: Also cleaned up the logging for org.slf4j) :)
> KNL-1446 adding LRS actor identifiers for xAPI statements

- kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
On MySQL if the packet is too large it would just silently fail, this attempts to provide a helpful error when we can guess at what the problem might have been.
> KNL-1445 Better logging when packet too large.

- user/user-util/src/java/org/sakaiproject/user/util/ConvertUserFavoriteSitesSakai11.java
Also added a `db.properties` parameter to let people with more exotic
setups provide an explicit path to their database configuration.
> SAK-31423 Broaden the search to find properties files in other standard locations

- config/configuration/bundles/pom.xml
This includes the currently checked out SHA by default in the version information.
> SAK-31442 Include the git SHA in build.

- calendar/calendar-summary-tool/tool/src/java/org/sakaiproject/tool/summarycalendar/ui/MenuBean.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Change the default configuration in sakai 11.0 so that the option for
users to generate a private URL for a calendar is enabled by default,
create an additional property: ical.public.secureurl.subscribe
> SAK-31413 Calendar - update default configuration for private url

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseExternalCalendarSubscriptionService.java
- calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
Change the default configuration in sakai 11.0 so that the option for
maintainers to subscribe to external calendars is enabled by default
> SAK-31414 : Calendar change, subscribe to external calendars is enabled by default

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
This means that if you enable .anon or .auth access to sites maintainers can only grant a limited set of permissions by default.
> SAK-31096 Limit permissions to .anon/.auth by default

- gradebook/grades-rest/pom.xml
- kernel/kernel-component/pom.xml
- master/pom.xml
- simple-rss-portlet/pom.xml
- site/admin-perms-tool/pom.xml
- site/sakai-message-bundle-manager-tool/pom.xml
This means if we want to deploy SNAPSHOT artifacts we don’t include all the bundles which are very large. Quick local test shows it’s about 94MB for a full build.
> SAK-31449 Quick way to skip deployment of components/webapps

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm
- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/base/_extendables.scss
- reference/library/src/morpheus-master/sass/base/_responsive.scss
- reference/library/src/morpheus-master/sass/modules/_main.scss
- reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_breadCrumbs.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_skipnav.scss
There are a number of issues with the alignment and positioning of the items in the top bar. They should be vertically centred across the bar to present balance. I have gone through the topNav bar piece by piece and fixed the positioning, spacing, and sizing to make everything centred, equal, and balanced. 
I also fixed an issue with the colours of the sites across the top to fix accessibility contrast issues and ambiguity of the selected site. 
Here are the before and after screenshots:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
Before:
After:
**Please note: the Tools Menu in the mobile view, the All Sites drawer in both views, and the …
> SAK-31470 Re-styled the positioning and layout of the topNav bar and associated views

- announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm
only ONE announcement is set as a Draft
> SAK-31450 'Announcements View' shows ALL announcements grayed out when

- reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
- reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
[Video Demo](https://goo.gl/JtZP1S)
[JIRA](https://jira.sakaiproject.org/browse/SAK-31466)
> SAK-31466 - Following menu if tools do not overflow view port and auto adjustable width tabs

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/snippets/skipNav-snippet.vm
- reference/library/src/morpheus-master/sass/modules/navigation/_skipnav.scss
To fix the issue that was identified in SAK-31467 when the property `accessibility.url` is set, I've hidden the skipnav list item that appears, similar to how we hide the Content quick link. I had to change a bit of the markup to achieve this by making it comply with the other list items.
> SAK-31467 Hid the Go-to-accessibility link in mobile view

- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
I've noticed a small regression in my styles for SAK-31470 when I merged it with the variables written for SAK-31402: there is a 2px-height difference for the link of a selected site in the topNav bar:
This causes the sites at the top to bounce around when you switch from site to site. 
I have fixed this issue in this simple PR by setting the value of the border:
(Relies on SAK-31470 and SAK-31402.)
> SAK-31482 Fixed the height difference of selected sites in the topNav bar

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MathJaxEnabler.java
https://jira.sakaiproject.org/browse/SAK-31481
Core Team decision was to have this as one of the highlighted features of Sakai 11. As such, it should be enabled in sakai.properties by default.
> SAK-31481 turn on MathJax support by default

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
Edit details page in resources scrolls to the top when URL is selected
on Edit Details page
> SAK-31169 - Edit details page in resources scrolls to the top when URL is selected

- access/access-tool/tool/pom.xml
- common/ddl/pom.xml
- entitybroker/tool/pom.xml
- jsf/jsf-widgets-sun-depend/pom.xml
- jsf/myfaces-widgets-depend/pom.xml
- master/pom.xml
- oauth/api/pom.xml
- oauth/dao-hbm/pom.xml
- oauth/dao-memory/pom.xml
- oauth/dao-server-config/pom.xml
- oauth/impl/pom.xml
- oauth/pack/pom.xml
- oauth/pom.xml
- oauth/tool/pom.xml
- simple-rss-portlet/pom.xml
oauth - this was at 1.2-SNAPSHOT
simple-rss-portlet  - this was at 1.2.3-SNAPSHOT
Also marked the oauth-api as provided and set a version in the master pom so it doesn’t get deployed in other versions.
Put jsf dependency names onto one line to make them easier to parse.
> SAK-31493 Harmonise maven project versions

- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm
Users can’t be looked up by display ID so use the internal ID instead.
> SAK-31508 Use the internal ID for Profile URL.

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
This refactors the existing code so that the security advisors are all retrieved from one place in the code and the checks the configuration option announcement.merge.visibility.strict and if unset then users of a merged site are allowed to see the announcements even if they aren’t members of that site.
> SAK-31342 Allow merging permission configuration

- reference/docs/conversion/sakai_11_mysql_conversion.sql
- reference/docs/conversion/sakai_11_oracle_conversion.sql
This was originally developed under SAK-29582 but it didn’t include a conversion script.
> SAK-31496 Increase LTI column sizes.

- reference/docs/conversion/sakai_11_oracle_conversion.sql
These changes were already in the Oracle upgrade scripts and so don't need to be increased
> SAK-31496 (Undo Oracle) Increase LTI column sizes.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
- samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp
This also solves SAM-2980 Double checkmark displayed in Statistics
> SAM-2979 Statistics for Calculated Questions not showing the right data

- pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/AcknowledgementType.java
- pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Banner.java
- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/acknowledgements/AcknowledgementStorage.java
Otherwise we fail when the Turkish locale is set.
> SAK-31562 Use Locale.ROOT when normalizing case for enumerations

- delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/jobs/DelegatedAccessSiteHierarchyJob.java
Previous handling of the last run date created a small window where
updates could be missed.
I also snuck a `volatile` keyword into the `semaphore` definition.  I've never seen this cause problems, but thought I'd fix it since I was in there anyway.
> SAK-31479 Capture updates made while the SiteHierarchyJob runs

- jobscheduler/scheduler-api/pom.xml
- jobscheduler/scheduler-api/src/java/org/sakaiproject/api/app/scheduler/JobBeanWrapper.java
- jobscheduler/scheduler-component-shared/README.beanjobs.md
- jobscheduler/scheduler-component-shared/pom.xml
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutowiredJobBeanWrapper.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutowiringSpringBeanJobFactory.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/ConnectionProviderDelegate.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/JobBeanWrapperRegistrar.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/ScheduledInvocationJob.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SpringJobBeanWrapper.java
- jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
- jobscheduler/scheduler-test-component-shared/pom.xml
- jobscheduler/scheduler-test-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/AutowiredTestJob.java
- jobscheduler/scheduler-test-component/src/webapp/WEB-INF/components.xml
- kernel/deploy/shared/pom.xml
- master/pom.xml
This means you can just register a class with the job scheduler and then quartz will create an instance when it needs to and have spring autowire any dependencies.
> SAK-31584 Allow auto wiring of Quartz Jobs.

- portal/portal-util/util/src/java/org/sakaiproject/portal/util/ToolUtils.java
new property 'portal.experimental.auto.reset' can be added for a site to
reset all tools on the site at each navigation operation.
In 'getPageUrl' method site properties are checked for new parameter
CONFIG_AUTO_RESET, if it's set then each tool on the site will have reset
url.
> SAK-31389 Added a site property, when set,will reset tools for the site

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportColumn.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedGradeWrapper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ProcessedGradeItemStatus.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
- gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/helpers/TestImportGradesHelper.java
This delivers a few fixes.
1.  Part of #1396 - allow import of gradebook items without points.
2. Fixes #3100, error message box should now be cleared between steps.
3. Fixes #2796, any type of column should be ignored if it starts with a #. Also the error messages are more granular.
> Allows items to be imported with no points specified

- reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
The Actions menu is just as active as on a non-hidden folder - unlike the folder (or file) it is not different from any other Actions menu
> SAK-31606 Button text is hard to see on hidden folders

- .travis.yml
Artifacts that are part of our own build shouldn't be cached. This should make the travis caches small but also help us detect build issues that would fail against a clean repository.
> Don't cache artifacts from our own build.

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MathJaxEnabler.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
[JIRA - SAK-31639](https://jira.sakaiproject.org/browse/SAK-31639)
> SAK-31639 - Site-Manage - MathJax not automatically enabled is system-level is on, on site creation

- samigo/samigo-app/src/webapp/js/samigo-global.js
- samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
https://jira.sakaiproject.org/browse/SAM-2996
When answering a matrix of choices question using forced ranking, if you fill in all the columns and then try to change one, you get a pop-up alert telling you this is not allowed (in 10.x). However, it clears the user's previous (valid) selection for the column in question in this scenario, and the user may not notice this. This can result in the user submitting the question without realizing one of their answers/selections had been cleared out.
In 10.x, this bug clears out the user's previous choice in the given row. In 11.x+, this has actually gotten worse. You are no longer even given the message stating that this is not allowed (regression), and the JavaScript code not only clears the user's choice for the given row, but also their …
> SAM-2996 user data is lost when violating rules in a matrix of choices question

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Also use aria-hidden on presentation tables, as text in table still read by screenreader  when role='presentation' alone.
Delivers #2655.
> 2655: Add gradebook grades table caption and target to screen readers

- oauth/dao-hbm/src/resources/org/sakaiproject/oauth/dao/Accessor.hbm.xml
- reference/docs/conversion/sakai_12_mysql_conversion.sql
- reference/docs/conversion/sakai_12_oracle_conversion.sql
This makes the oauth code use VARCHARs rather than INTs for it’s enums as it makes the database more readable and helps to prevent problems when enums are changed.
This is also needed as we currently have this setup from our 10.x OAuth deployment and migrating to INTs seems like a backwards step.
> SAK-31641 Switch to VARCHAR rather than INTs for enum.

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- oauth/dao-hbm/pom.xml
- oauth/dao-hbm/src/ddl/hibernate.cfg.xml
- reference/docs/conversion/sakai_11_0-11_1_mysql_conversion.sql
- reference/docs/conversion/sakai_11_0-11_1_oracle_conversion.sql
On upgrade installations we weren’t creating the OAUTH_* tables, this meant that the oauth functionality would fail.
This uses the old hibernate3:hbm2ddl maven plugin to get the same DDL statements and needs editing to run on different schemas but this is just here as a reference as it shouldn't be needed again.
> SAK-31603 Correctly setup OAuth for upgrades.

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-31649
The intention of these filters is to force the browser to only display file types that the Content Review Service accepts. Unfortunately, OS/browser support for the 'accept' attribute on a file picker is sporadic at best.
For instance, on Linux/Chromium, the default filter selected only shows .txt and .html files. Only after selecting the 'All Files' filter can you see the rest of the file types that the CRS accepts.
In Windows/IE, the default filter is "Custom Files", and only shows you *.odt, *.ps, *.htm, *.htm (yes it's repeated), *.pdf, *.ps (again, repeated), and *.txt. The other filter options are:
* "HTML", which shows you *.html and *.htm
* "Pictures", which shows you *.gif, *.jpg, *.jpeg and *.png (this filter is useless in terms of …
> SAK-31649 disable file picker file type filters in Assignments for submissions

- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityGroup.java
There's a missing return statement that will result in an exception being raised whenever addMember is called.
> SAK-31653: missing return statement in EntityGroup.java

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/DeleteItemPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/HeaderFlagPopoverPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameColumnHeaderPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
Delivers #3116.
This fixes a Firefox bug, whereby navigating the GradebookNG tool and returning to the Grades sepreadsheet causes all subsequent POST requests to fail with a 302 redirect.
To fix, set mount points for the 4 GradebookNG pages, so the base page is always consistent.  Secondly, use the class variant of setResponsePage to navigate to those mount points.
I haven't set a milestone yet.. 11.2 so we can get some reasonable testing in?
> 3116 fixes Firefox form POST issues

- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
If the $logo-width is larger than $tool-menu-width then the logo gets trimmed off and $logo-width isn’t respected.
> SAK-31655 Respect $logo-width when wider than tools

- .travis.yml
Because settings.xml defines a bunch of repos that aren't updated, we should just remove it before the build starts
> Remove settings.xml so it doesn't interfere with builds

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/backfilltool/Messages.properties
The documentation said to set it to true to include user sites in the list when it should have been false.
> SAK-31662 Fix docs on Backfill Tool Quart job.

- profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java
This works because HttpServletResponse.sendRedirect(String) accepts relative requests and makes them absolute. Browsers natively support protocol relative requests so it shouldn't be a problem there.
> SAK-26702 Make Gravatar protocol relative

- portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/SiteNeighbourhoodServiceImpl.java
If aliases are disabled we would still look in the DB for any aliases. This is wrong and we should only be looking when aliases are enabled.
> SAK-31670 When aliases disabled don’t query DB.

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
https://jira.sakaiproject.org/browse/SAM-3002
When answering a matrix of choices question, if you partially fill out your answers, click 'Save' (or 'Next' or 'Previous'), then fill out more answers and 'Save' again, your original answers will be lost and only the 'new' answers will be preserved.
The same behaviour can be seen using the next and previous buttons. Anything you saved (or was inherently saved when using next and previous), will be lost the next time you save (or do next or previous). This process can be repeated infinitely, until or unless you press the 'Reset Selection' link.
The end result is user data loss which the user may not be aware of. This can be catastrophic in the case of a final exam or such.
The problem here is that the code is removing all old answers, and only …
> SAM-3002 unexpected behaviour with matrix of choices after saving which results in user data loss

- user/user-util/src/java/org/sakaiproject/user/util/ConvertUserFavoriteSitesSakai11.java
When the favourites conversion fails if there isn’t a DB connection, rather that getting a message about not being able to connect to the database you will get a NullPointerException, this fixes it and keeps the underlying error.
> SAK-31684 Give good error when converting favourites.

- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/PASystemImpl.java
- pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/handlebars/ForeverTemplateCache.java
We ignore timestamp changes on the files as we're inside a JAR in a component so we never need to check for newer files.
> SAK-31675 Add a cache for the PA System templates.

- entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/UserEntityProvider.java
For example, ask for the membership of a site with one orphaned user (user that no longer exists in LDAP):
https://sakai.example.edu/direct/membership/site/c7788b6d-e30b-4aae-b87e-1433d104e5dd.json
This will bomb with 
HTTP Status 400 - Cannot execute custom action (site): Illegal arguments: Could not find user with eid=id=660de1f0-297c-4306-a945-484de8d2a4da or id=660de1f0-297c-4306-a945-484de8d2a4da (rethrown)
> SAK-31690 dont throw an error if user does not exist

- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://jira.sakaiproject.org/browse/SAK-29738
Added resetPaging(state) to search method to for the results pages to start at page 1 instead of whatever results page the user had been on previously.
> SAK-29738 Fix Worksite Setup search results paging

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SpringJobBeanWrapper.java
- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SpringStatefulJobBeanWrapper.java
When you wrap a job that you expect to be stageful in a non-stateful wrapper.
> SAK-31700 Log if wrong wrapper is used for quartz

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
Fixes convertGradePointsForUpdatedTotalPoints not converting percentage grades correctly.  It needed to use the percentage value of the grade rather than the raw grade points earned.
Delivers #3210.
> 3210: fix for percentage grade conversions when assignment points change

- kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/HtmlPageFilter.java
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
- portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MathJaxEnabler.java
Ideally this should be extracted out so that tools/plugins can contribute to the scripts, but to get it working we’re just putting the MathJax code in the kernel.
This also fixes a but where a site local skin wasn't getting picked up.
> KNL-1234 Enable MathJax on content in resources.

- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/PASystemServlet.java
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/handlers/BannersHandler.java
- pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/views/banner_form.hbs
Output the known list of hosts so that they can autocompleted by browsers that support them, This doesn’t stop people from typing in hosts that don’t exist in the dropdown but helps prevent mistypes of existing hosts. The in browser autocomplete doesn't work after the first hostname has been entered but it's a simple solution for the most common case of a message for a specific host.
The <datalist> element is supported in most popular browser on the desktop apart from Safari. When it isn't supported it's just ignored so it doesn't break anything.
http://caniuse.com/#feat=datalist
> SAK-31682 autocomplete suggestions for hosts (PA Tool).

- kernel/kernel-common/src/main/config/log4j.properties
Any thoughts? I guess we could go more specific if some things should stay warn, but most things seem pretty nice.
Maybe the stuff in org.springframework.beans is a little noisy and redundant? I feel like it's all useful for helping to identify problems though.
> KNL-1455 - Change default log level of org.springframework to INFO

- samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
This change makes it so that when you are on the Published
Copies tab and edit an assessment, you are brought back to that
tab.
> SAM-3007 Samigo, return to the published tab

- msgcntr/messageforums-app/src/webapp/css/msgcntr.css
Removed the padding for the markAsRead icon as it causes the
button to be too small which makes it look odd in comparison to the other button.
> SAK-31711-2 Remove padding MarkAsRead Icon

- mailsender/tool/src/java/org/sakaiproject/mailsender/tool/producers/fragments/UsersProducer.java
The mailsender tool doesn't escape a recipient's internal user ID before using it in an EL path expression.
This results in an Exception and emails not being sent when e.g the user ID is an email address (== a String containing at least one dot, which will then be interpreted if not escaped)
This patch uses RSF's [PathUtil.buildPath(String[])](https://source.sakaiproject.org/release/rsf/ponderUtil/uk/org/ponder/beanutil/PathUtil.html#buildPath%28java.lang.String[]) method instead of String concatenation to escape the user ID.
[https://jira.sakaiproject.org/browse/SAK-24332?filter=15819](https://jira.sakaiproject.org/browse/SAK-24332?filter=15819)
> SAK-24332 Error message when a user/role/group id contains a space or period (mailsender)

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
Delivers #3049.
Hi @steveswinsburg,  as the `DownloadLink` isn't an ajax-link, I couldn't find a straight forward way to reset the form checkboxes.  I think we could refactor it to be an AjaxLink that invokes the download with JavaScript by setting the browser location (kinda like this https://cwiki.apache.org/confluence/display/WICKET/AJAX+update+and+file+download+in+one+blow). Any ideas?
I think it's ok to retain the form's state after clicking export, as it makes it clear to the user what they previously selected upon reopening it after a download .. 😵
> 3049: hide the custom export dialog after invoking download

- samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
- samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoLRSStatements.java
This also moved all of the LRS_Statement generation code into it's own util class because it seemed to make sense to me having it all together since it will make it easier to fix bugs there or add new detail.
The way this was updated, every Samigo code that wants to send to XAPI just needs to add this result generation onto the end of it's newEvent from the changes on https://jira.sakaiproject.org/browse/KNL-1451.
These events needs a lot more data than can be captured by the event alone (like various information about scoring) so it needs to generate it and send it along, rather than figuring it out afterward. 
Some of the other refactoring here changed the cover to the non-cover (because I didn't update the coverin KNL-1451) and this should be changed in all of Samigo, but seems like it …
> SAM-2997 - Additions to samigo xapi for score changes

- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
https://jira.sakaiproject.org/browse/SAK-31724
When adding rosters, link to find arbitrary rosters should not be controlled by require authorization sakai.property (wsetup.requireAuthorizer), as it's already controlled by two other properties (wsetup.skipManualCourseCreation or wsetup.skipCourseSectionSelection).
> SAK-31724 when adding rosters, link to find arbitrary rosters should not be controlled by require authorization sakai.property

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm
Added new sakai property : sitemanage.tools.groups.expanded
All groups IDs listed in this property, will be expanded by default.
Valid IDs : systoolgroups.lti and systoolgroups.ungrouped
Signed-off-by: Miguel Carro Pellicer <mcarro@entornosdeformacion.com>
> SAK-30371 : Plugin tools -> option to have expanded by default

- dav/dav/src/webapp/WEB-INF/web.xml
If you specify a limited number of http-methods then tomcat warns on startup that unlisted methods will be allowed through without any security constrains applied to them.
All the methods in DavServlet were in the list so applying the security constraint to all methods won’t change the behaviour.
The error that would appear in the logs was: 
For security constraints with URL pattern [/*] only the HTTP methods [HEAD MKCOL POST PROPFIND LOCK COPY OPTIONS PUT DELETE MOVE GET PROPPATCH UNLOCK] are covered. All other methods are uncovered.
> SAK-31740 Don’t specify http methods, apply to all.

- kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderAccessService.java
There are a fair bit of formatting changes here, but they now match the kernel formatting more closely. Because this code is mostly copied from kernel, it makes sense to share formatting so a simple diff can be used in the future.
> LSNBLDR-720 resync LessonBuilderAccessService with kernel changes

- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/examples/_customization_example_reversed.scss
Locally at Oxford we've got our own changes to the Sakai default skin and these are in a customisations file. By default this customisation file in pulled in at the end of the _defaults.css file so you can override any of the variables in _defaults.css. As an example in _defaults.scss there is a primary colour defined as:
$primary-color: #2a94c0 !default;
we then in our customizations file re-define the primary colour to be:
$primary-color: #002147;
the problem is that if this primary colour is referenced anywhere else in _defaults.scss our re-define doesn't work because the value is already copied into the new variables, as an example:
$tool-menu-current-color: $primary-color !default;
here the tool menu current color will be the standard Sakai one, rather than our Oxford one. The …
> SAK-31656 Override defaults first in SCSS skin.

- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
When triggering a document scroll, ensure this is off the critical path as any errors will stop the cell from being initialised.
Delivers #3315.
> 3315 fix cells not being editable after a score is changed

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
1. As instructor create a non-electronic assignment whose Open Date is in the past, and the Due Date / Accept Until are both in the future
2. Go to the assignment's "View submissions" link
3. As a student view the assignment
Symptom: Student sees alert message is "The close date of the assignment has passed. You can no longer submit to this assignment."
Note: Step 2 creates dummy submission objects for the instructor to grade; if you skip step 2, you'll get the appropriate message:
"This assignment does not accept online submissions. Contact your instructor for additional instructions."
> SAK-31752 - wrong error message appears to students for non-electronic submissions

- site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
- site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
- site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Added Search input and clear search in the chef_site-siteInfo-list.vm.
If search word is in session state then Participant List is filtered for
the search term in each Participant's displayName and displayId.
Corrected the position of search box in the participant's table.
Have added new variable to STATE_SITE_PARTICIPANT_LIST in SiteAction class
to save the original site members list. Search is case insensitive.
> SAK-31705 Added 'Search Users' facility to site-info.

- jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/NavigableEventLogListener.java
When logging a job execution that had an exception with it, if there isn’t a cause the listener would fail to run completely. The simple fix is to just check before attempting to use look at the cause.
> SAK-31776 Don’t fail to log when no cause for quartz.

- basiclti/basiclti-tool/src/webapp/vm/lti_tool_system.vm
The 10 option in the list of tools installed in the system had a typo in it.
> SAK-31779 Correct typo in Basic LTI admin tool.

- basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
- basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
In Sakai 10 maintainers in a site could add an LTI tool to their site one or more times, in Sakai 11 this is only available to the admin user in the administration workspace. This adds it back and controls it with a property, which defaults to true, to stop maintainers adding multiple tools add:
lti:allow_maintainer_add_tool_site=false
to sakai.properties.
> SAK-31767 Allow maintainers to add LTI tools.

- content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
Because there are no frames anymore for most tools this won't find the frame. I believe the error that was thrown was causing other problems on the page and doesn't seem necessary.
> SAK-31520 - In Resources add another web link doesn't work

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.html
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Including a slight refactor of the setting of the cell's CSS classes.  Now we specify a 'base' CSS class which will allow the doubling up of classes e.g. an external score that is also extra credit.  Then style these doubled-up scores accordingly, with both icons.
Delivers #3006.
> 3006 show both "readonly" and "extra credit" icons when applicable

- roster2/src/java/org/sakaiproject/roster/tool/RosterTool.java
This means the user gets an alert saying they must be logged into use the roster tool. A better fix would be to actually have the message displayed in the page, but there’s lots of startup that needs to happen to get a handlebars template to render and some of these chunks need to have the user logged in.
Allowing anonymous access to the roster tool also needs access to the profile tool and both of them currently have lots of checks which would need to be carefully removed.
This change should stop users seeing an ugly stack trace and if we consider it important we can look at allowing anonymous access to the roster in the future.
> SAK-31774 Allow the roster front page to render (anon)

- reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
Simple fix to make the text of the reload message appear on one line:
Before:
After:
> SAK-31678 Fixed reload message when starring sites so it appears on one line

- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/modules/tool/_base.scss
- reference/library/src/morpheus-master/sass/modules/tool/_menu.scss
Standardized the colour of the toolTitleNav links to match the navIntraTool tabs and to address the accessibility of links' text colour contrast with their background colours; also removed link underlines from these tabs and buttons.
**Before:**
**After:**
**Before (hover state on Student View):**
**After (hover state on Student View):**
> SAK-31811 Standardized the colour of the toolTitleNav links to fix colour contrast

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
- gradebookng/tool/src/webapp/styles/gradebook-grades.css
Refactor cell styling code to ensure save notification displays always (even when extra credit), extra credit and comment flags are displayed after a revert and popover is hidden and doesn't become sticky.
Delivers #3348.
> 3348 fix cell styling not consistent after revert of change

- master/pom.xml
One of our plugins requires Maven 3.1.1 and having the requirement for the whole project makes the build fail earlier.
> SAK-31792 Require Maven 3.1.1 minimum

- reference/library/src/morpheus-master/sass/_defaults.scss
I have changed the primary blue used throughout Morpheus to meet WCAG Level A requirements. 
The former colour code for the primary blue in Sakai was #2a94c0, but was not high enough contrast on white. I changed this to a slightly darker blue (#247fa6), which passes the contrast ratio with white of 4.51:1. 
~~I also removed the primary-color-shadow variable and its one use case to avoid confusion.~~
*Before:*
*After:*
> SAK-31613 Changed primary blue used in Morpheus meet WCAG colour contrast requirements

- reference/library/src/morpheus-master/sass/_defaults.scss
- reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
Introduced a darker alternative blue to appear on grey and satisfy colour contrast requirements to fix the link colour contrast in the User menu for WCAG and accessibility. 
The links are now a slightly darker blue that can be used elsewhere in Sakai when the blue appears on grey.
**Before:**
**After:**
> SAK-31612 Fixed link colour contrast in User menu

- portal/portal-impl/impl/src/bundle/sitenav.properties
- portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
https://jira.sakaiproject.org/browse/SAK-31736
Since SAK-27488, admins using the Become User feature are not logged out of Sakai when using the log out link, but are instead returned to their original admin session.
There is potential here for someone clicking log out once and forgetting to log out a second time, leaving an admin session open for anyone with access to their computer, particularly if they are accustomed to the old behaviour.
This patch will replace the "Log Out" text with "Return to <admin username>" to make it clear that they will not log out of Sakai but rather return to their prior admin session.
> SAK-31736: Become User - Remind admins that 'logging out' returns them to the admin session they were in

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
Delivers #3369, maybe? 
I've added `format.date` and `format.datetime` to the Gradebook I18n properties.  This gets pulled into the FormatHelper and date picker. 
The datepicker has its own ideas for date formats defined in `lang-datepicker.js`.  I assume we just duplicate that values for each language as required?
Things work as expected if I add a `GradebookNgApplication_fr_CA.properties` translation file with:
```
format.date = yyyy-MM-dd 
format.datetime = yyyy-MM-dd HH:mm
```
Is that the best we can do?
> 3369 allow date format to be set via gradebook I18n resources

- portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeSitesNav.vm
If Home/My Workspace is not going to have any tools to display as a pop-up, it should have aria-haspopup="true"
> SAK-31620 Ensure ARIA roles valid

- master/pom.xml
Our QA testing for Sakai 11 and so far for Sakai 12 (currently master) has been on 8.0.32 but the pom.xml has 8.0.20 .
> SAK-31823 Update Master POM Tomcat version to reflect current supported

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://jira.sakaiproject.org/browse/LSNBLDR-736
All lessons event refs are in the following format:
"/lessonbuilder/[page|item|comment]/ID"
The middle chunk of the ref determines what type of object the event is referring to; either a SimplePage, SimplePageItem, or SimplePageComment.
However, there is a problem in the code for the "lessonbuilder.read" events. These events can refer to either a SimplePage or a SimplePageItem, however the code always builds the event ref with the "/page/" identifier.
Due to the way IDs are used in Lessons, it becomes impossible to determine if this event refers to a SimplePage or a SimplePageItem, because the IDs for both are just incrementing integers. So you could very well have both a SimplePage and a SimplePageItem with the same ID.
There is code …
> LSNBLDR-736 lessons event ref for event type lessonbuilder.read is ambiguous

- providers/jldap/src/java/edu/amc/sakai/user/SimpleLdapAttributeMapper.java
We have multiple attributes mapped to the same key in LDAP which results in Sakai requesting them twice, although this shouldn’t result in any problems this tidies it up so we just request it once.
> SAK-31825 Don’t request the same attribute twice.

- simple-rss-portlet/pom.xml
- simple-rss-portlet/src/main/java/au/edu/anu/portal/portlets/rss/SimpleRSSPortlet.java
This allows multiple copies of the tool to startup inside the webapp, but also allows statistics about the cache to be seen in the Memory tool in the administration workspace.
> SAK-31704 Use central cache in news tool.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
Delivers #3210.  Not sure if this is the best approach, but it was worky!  The goal was to put the score from the database and what we think is the database score in the same format so a fair comparison can be made.
> 3210 ensure stored scores with more than 2 decimal places don't cause a concurrent edit error when in percentage mode

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java
I found this in GBNG using Settings -> Percentages
CC: @steveswinsburg @payten
> SAK-31859 avoid gradebook percentage calcs divide by zero

- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java
- kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlMySql.java
- kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockAuthzGroupService.java
that can cause terrible MySQL query performance in sites with 150+ groups.
Primary change is towards bottom of PR look for getSelectRealmRoleUserIdSql. I remove the sub-select as it's unnecessary, can cause bad performance, requires 1+ temporary tables, and is confusing.
> KNL-1475 remove the unnecessary sub-select from getUsersIsAllowed

- announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
This is attempt to fix patch from Stanford here:
https://jira.sakaiproject.org/browse/SAK-23316
The logic from that patch just seems wrong so I change variable name to try to be more clear. 
I found this while debugging performance and found an admin-user was loading 1300+ sites every time they logged in because of My Workspace -> Synoptic Announcements.
Reviews appreciated
> SAK-31857 dont load hidden sites from preferences when loading synoptic announcements

- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java
- samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
"Active" status when it shouldn´t
Warning added if the user publish the assessment with Retract Date and no
Due Date
> SAM-2985 Assessment published with no due date and retract date has

- assignment/assignment-tool/tool/src/webapp/css/assignment.css
- assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_group_error.vm
Implement Kyle suggestions for assignment icons.
This removes the icon for normal assignments. Icon now only used to indicate group submissions.
I use aria-hidden on the fontawesome icon.
CC: @kyleblythe
> SAK-31756 use FA for visual indicator of non-normal assignments

- .gitignore
The .gitignore file contains stuff from an unresolved conflict. This should be removed.
> SAK-31894 .gitignore has garbage in it

- sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/PreferencesPage.java
https://jira.sakaiproject.org/browse/SAK-31898
In Sitestats, go to Preferences, then click cancel. Nothing happens; it just clears out changes made to the form. The button should abort changes and redirect you back to the Overview page.
> SAK-31898 sitestats -> preferences -> cancel button behaviour unintuitive

- pasystem/pasystem-tool/tool/src/webapp/stylesheets/pasystem.css
The PA tool doesn’t currently render correctly on a mobile and until this is fix it should all be hidden on a mobile so that it doesn’t interfere. with the normal use of the interface. In the future we want to fix the PA announcements so they work well on a mobile.
> SAK-31773 Disable last bits of PA on mobile.

- reference/docs/conversion/sakai_11_1-11_2_mysql_conversion.sql
- reference/docs/conversion/sakai_11_1-11_2_oracle_conversion.sql
- site-manage/site-manage-group-section-role-helper/pack/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/RoleGroupEventWatcher.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java
- site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java
- site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteConstants.java
- site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteGroupHelper.java
Use the provider for packing/unpacking of the provider IDs. The main change for this fix is in SiteManageGroupSectionRoleHandler where we use the GroupProvider rather than the SiteGroupHelper for packing the IDs.
Added generics to RoleGroupEventWatcher as I was looking at what the code was doing, not other changes in that file.
I inlined the `getProviderString(List<String>)` call as it’s only used once and wanted to make it clearer which call should be used in which place.
The packing (and unpacking) that should be used is
`GroupProvider.packId()` for `Group.setProviderGroupId()`
`SiteGroupHelper.pack()` fot `SiteContants.GROUP_PROP_ROLE_PROVIDERID`
> SAK-31905 Use the GroupProvider when packing/unpacking.

- reference/docs/conversion/sakai_11_mysql_conversion.sql
changed type of two cols from illegal varchar size to mediumtext; 
added 'if exists' to a 'drop index' which didn't exist in our 10.5 DB
( https://jira.sakaiproject.org/browse/SAK-31680 )
> SAK-31680 fix for two issues in Sakai 11 mysql conversion script

- lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://jira.sakaiproject.org/browse/LSNBLDR-740
When Lessons fires off a read event for SimplePageItem objects, it creates the event ref in the following format:
`/lessonbuilder/item/<ID>`
However, the ID it's sticking in there is retrieved via the getSakaiId() method. This method returns something other than the actual item ID.
In testing, I've found that typically it is an integer value of the actual ID minus 1. For example, if the item's ID is 401901, the value returned from getSakaiId() is 401900.
When searching through the code, it seems this field could also be used for storing an entity reference to some other object (maybe a quiz or an assignment).
However, for the purposes of events and resolving the event reference in question, we don't care about the entity reference that …
> LSNBLDR-740 lessons read events for SimplePageItem objects utilizes the wrong ID

- entitybroker/utils/src/java/org/sakaiproject/entitybroker/util/servlet/DirectServlet.java
This broke because parts[2] now contained the login (and parts.length ==3)
I just changed it to always look at the last value which should be /login (or well something not /login)
I think if you have an eb direct and it ends in /login this is isn't a case to worry about like nobody is going to have /direct/announcement/login. I guess it could be changed to be exactly 2 or 3?
> SAK-31922 - /direct/login no longer works

- site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
… in the Selected Tools panel after a tool is selected.  Tool link items have a different number of preceding whitespace, so `trim()` the `text()` to be sure we're sorting on letters.  Also patch reordering of the Home item to the top (The id seemed to have changed).
Delivers https://jira.sakaiproject.org/browse/SAK-31839
> SAK-31839 Fix alpha ordering on Manage Tools page

- calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java
This PR uses ical4j’s recurring event support to create individual events for recurring events.  
This currently has some caveats, but any support for recurring events may be better than none, and perhaps it's a starting point for better support.  Known caveats:
1. It creates individual events on the Sakai calendar, it does not attempt to translate ical recurring patterns (and corresponding exceptions) to Sakai's recurring event models.
2. Ical4j's recurring event method requires a time range, so right now it arbitrarily only considers events six months in the past and 12 months in the future.
3. Ical4j seems to handle exceptions to recurrence well with one known exception.  If an individual occurrence has its summary and/or description changed, but not the time, it will be duplicated on …
> SAK-11486 Basic support for recurring events

- reference/docs/conversion/sakai_11_mysql_conversion.sql
- reference/docs/conversion/sakai_11_oracle_conversion.sql
https://jira.sakaiproject.org/browse/SAK-31936
The conversion script fails to update the template on case sensitive MySQL instances because the table name is not in upper case. The convention is to use the case in which the table was originally created.
Thanks to @smarquard for identifying this issue.
> SAK-31936 site creation notification email update conversion script fails on case sensitive MySQL instances

- assignment/assignment-api/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/sort/AssignmentComparator.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/sort/AssignmentSubmissionComparator.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/sort/UserComparator.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/sort/UserIdComparator.java
- assignment/assignment-impl/impl/src/test/org/sakaiproject/assignment/impl/AssignmentComparatorTest.java
- assignment/assignment-impl/pack/src/webapp/WEB-INF/components.xml
- kernel/api/src/main/java/org/sakaiproject/user/api/User.java
When exporting a spreadsheet from the assignments tool anonymous users were displayed without their anonymous ID. This changes it so they are still exported but the user appears multiple times in the spreadsheet, once with their full name and once for each assignment submitted under an anonymous ID.
The comparators were also extracted out into type safe classes as there was one comparator that dealt with multiple types. This could be improved but needs more refactoring outside just assignments.
The results are also sorted by ID for the anonymous ones so that you can't see who an anonymous user is by comparing the lists of anonymous and non anonymous users.
When reading through code I also added generics and constants where I was updating it.
I extracted the code out into another class as …
> SAK-31920 Don't export anonymous users in spreadsheet

- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
https://jira.sakaiproject.org/browse/SAK-30756
Tool tips were displaying but the underlying text would bleed through, making the tool tip's text unreadable. Solution was to add z-index to tool tip container. Screen shots in the JIRA ticket.
> SAK-30756 fix tooltips in wiki

- rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages.properties
https://jira.sakaiproject.org/browse/SAK-12370
"Mouse-over text in Wiki for the "link to resource" button should read "link to resource" not just "link""
> SAK-12370 improve tool tip messages for some buttons

- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- rwiki/rwiki-impl/impl/src/java/uk/ac/cam/caret/sakai/rwiki/component/service/impl/RWikiObjectServiceImpl.java
- rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/service/impl/CommandServiceImpl.java
- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/commandComponents.xml
https://jira.sakaiproject.org/browse/SAK-21039
"At the moment rwiki can generate read events, but these aren't turned on by default.
Can I suggest we turn them on by default so that everyone gets good wiki reporting in site stats. I believe content read events are on by default and the quantity of events generated there is far more than rwiki is likely to ever generate."
> SAK-21039 make wiki read events generated by default

- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
https://jira.sakaiproject.org/browse/SAK-21985
"Not sure whether this is officially classified as a 'feature' but in my mind it's a bug. Wiki tables now span the whole width of the page which makes them look pretty awful. see screenshot"
> SAK-21985 wiki tables should not be 100% width at all times

- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
https://jira.sakaiproject.org/browse/SAK-30753
"the top row of a table should be rendered in bold on a grey background. The text isnt in bold"
> SAK-30753 wiki table headings should be bold

- rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
https://jira.sakaiproject.org/browse/SAK-30584
Pop-up is hidden under existing content. The problem being that the default navPanel CSS defines overflow as hidden.
> SAK-30584 fix recently visited popup display issues

- msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
The "Delete Topic" button on the Topic page in Forums has confused several users into deleting entire topics accidentally, and all of the conversations along with them.  This PR removes that button.  There are other, safer, clearer ways to delete topics already.
> SAK-31941 Remove confusing Delete Topic button

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
- content-review/contentreview-federated/pack/src/webapp/WEB-INF/components.xml
This pull request is to help with the merge of compilatio content-review implementation in Sakai 11, it just adds to Assignments the compilatio options as other antiplagiarism solution does. Also adds the commented option in content-review base.
> SAK-31949 Compilation content-review implementation

- msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
From what I can see the problem here is some old code from 2005 in setSelectedForumForCurrentTopic. It did a check if selectedforums != null and returned but in this case for some reason the selectedForum wasn't null but it was the wrong forum from a previous request. In the regular forums workflow selectedForum is ALWAYS null so I don't even see the point of this, and it seems to be not even always doing what you'd expect a setter to do. 
It seems to me like this is the best fix. An alternate might be to see why the selectedForum isn't reset. selectedTopic is always reset by this code in resetTopicById and I think it's expecting the forum to set along with the topic.
> SAK-25289 - Breadcrumbs trail incorrect when accessing forum topics

- lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
https://jira.sakaiproject.org/browse/LSNBLDR-753
Events are not generated when creating or updating comments. We get a create and update event on creation of a comments section, but these are actually 'item' event refs. There should be 'comment' event refs generated when any user submits a comment to any comment section.
When we create a comments section, we effectively get two events (lessonbuilder.create and lessonbuilder.update), with a ref as follows:
```/lessonbuilder/item/<itemID>```
Where the itemID is the ID of the comments section 'item'. When any user posts a comment to a comments section, there should be a lessonbuilder.create with an event ref like the following:
```/lessonbuilder/comment/<commentID>```
Which would allow interested parties to resolve the author, the time of …
> LSNBLDR-753 lessons does not generate events for creating or updating comments

- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
... (concurrent edits/server ping) so that the user session lastAccessedTime is not bumped and the session can timeout naturally.
Delivers #3563.
> 3563 add auto=true to the GradebookNG AJAX polls 

- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
- assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/sort/AnonymousSubmissionComparator.java
- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
When displaying lists of submitters involving anonymous assignments we have to make sure we sort by the anonymous ID and not the user's sortname so we don't leak information about who has what result.
Ideally we would clean up all the comparators here, but that's lots of work and won't be easy to merge back to 11.x
> SAK-31948 Don't order anonymous assignments by sortname.

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Delivers #3580.  The Wicket jQuery loads in the <head> but $PBJQ and Bootstrap is loaded at the end of the page. We need Bootstrap to be loaded and integrated with the jQuery that Wicket (and our custom JavaScript) uses, so pull in Bootstrap at the top of the page.
> 3580 fix Bootstrap popovers and dropdown menus in GradebookNG tool

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
- gradebookng/tool/src/webapp/scripts/gradebook-settings.js
The reported js error was due to jQueryUI sortable not being attached to Wicket's jQuery.  Plus also fixed an error if the course grade had not been released and the categories enabled changes.
Delivers #3602.
> 3602 fix js errors on GradebookNG settings tab 

- reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
Maven making the compressed JS has done a wrong optimization. We had before `_subHeight` (it was failing too) this code
`var _top   = ( $PBJQ("#toggleSubsitesLink").length > 0 )?(-1 * ( $PBJQ('#toolMenu').height() - $PBJQ("#toggleSubsitesLink").position().top ) ):0;`
And maven compress it to this failing code:
`var c=(-1*($PBJQ("#toolMenu").height()-$PBJQ("#toggleSubsitesLink").position().top));`
`var b=($PBJQ("#toggleSubsitesLink").length>0)?c:0;`
We need to check `toggleSubsitesLink` exists before figure out its position
> SAK-31723 - Subsites position is not in right position

- edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
This causes any assignment which is uncategorized (that is a null
category) to not be included in the category grade calculation.
This resolves #3616 .
> 3616-Uncategorized GB Items should not be counted

- gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
Caused by the change to the bootstrap version.  We need to pull in bootstrap ahead of the portal, so update the bootstrap import to v3.3.7 so it's all worky.
Delivers #3580.
> 3580 fix javascript error in GradebookNG

- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Within the GradebookNG tool if one where to turn "Group by Category" on
(when categories where enabled) and then to turn off Categories, if the
user where to scroll right then the fixed header would have an
extraneous row on it. This change causes the row to only be added when
group by category is enabled.
Resolves #3651
> 3651 In GradebookNG prevent erroneous row added

- calendar/calendar-summary-tool/tool/src/webapp/WEB-INF/web.xml
- chat/chat-tool/tool/src/webapp/WEB-INF/web.xml
- config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
- gradebook/app/sakai-tool/src/webapp/WEB-INF/web.xml
- help/help-tool/src/webapp/WEB-INF/web.xml
- jobscheduler/scheduler-tool/src/webapp/WEB-INF/web.xml
- jsf/jsf-tool/pom.xml
- jsf/jsf-tool/src/java/org/sakaiproject/jsf/util/JsfTool.java
- msgcntr/messageforums-app/src/webapp/WEB-INF/web.xml
- podcasts/podcasts-app/src/webapp/WEB-INF/web.xml
- postem/postem-app/src/webapp/WEB-INF/web.xml
- samigo/samigo-app/src/webapp/WEB-INF/web.xml
- sections/sections-app/src/webapp/WEB-INF/web.xml
- signup/tool/src/webapp/WEB-INF/web.xml
- site-manage/site-association-tool/tool/src/webapp/WEB-INF/web.xml
- syllabus/syllabus-app/src/webapp/WEB-INF/web.xml
- tool/tool-tool/su/src/webapp/WEB-INF/web.xml
- user/user-tool-admin-prefs/admin-prefs/src/webapp/WEB-INF/web.xml
- user/user-tool-prefs/tool/src/webapp/WEB-INF/web.xml
- userauditservice/tool/src/webapp/WEB-INF/web.xml
- usermembership/tool/src/webapp/WEB-INF/web.xml
We are experiencing problems with some users due to SAK-25677. Requests spend too much time to complete (ViewState size is really big). This change allow us to switch SAVING_STATE_METHOD in Samigo (or others) to "server", just with a new property in sakai.properties.
> SAK-29126 Add a property to control JSF State in sakai.properties

- gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Within the GradebookNG tool, there is a fixed column which appears only
once scrolled to the right. Clicks on elements within that column (i.e.
student name / the row itself) would not be passed through to the actual
element where the event is processed. This fixes that so that the
clicks are passed through correctly, for example: allowing one to
access the student overview panel when scrolled to the right.
This would resolve #3631
> 3631 Improve link passthrough in GradebookNG

- sitestats/sitestats-api/src/config/org/sakaiproject/sitestats/config/toolEventsDef.xml
https://jira.sakaiproject.org/browse/SAK-32005
Prior to SAK-21039 you had to flip a sakai.property to make the system generate wiki.read events. As a result, statistics was never made aware of the event, and even if you turn generation of that event on, statistics won't include it in reports because it doesn't know the event type exists.
Make statistics recognize the wiki.read event, as it's now generated by default OOTB.
> SAK-32005 make stats aware of wiki.read events OOTB

- rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/macros.vm
https://jira.sakaiproject.org/browse/SAK-20077
If the user doesn't have the permission to comment, why show them the links? This action is controlled by the rwiki.update permission.
> SAK-20077 users without rwiki.update permission can't comment, but still see links to generate new and edit existing comments

- kernel/api/src/main/java/org/sakaiproject/messagebundle/api/MessageBundleProperty.hbm.xml
Reducing some column lengths in SAKAI_MESSAGE_BUNDLE allows Sakai to start up with a mysql utf8mb4 database.
> SAK-31937 Reduce column lengths to support mysql utf8mb4

- assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Particular zip files created on certain Ubuntu distributions did not upload correctly into Assignments Upload All feature.
This switches to java.util.Zip and also removes custom code for copying the input stream in favour of  Files.copy. This change has been run in production at UCT for a while in Sakai 10.x.
> SAK-29928 Switch to java internal zip and Files.copy methods

- mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SplitEmailAddress.java
- mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SplitEmailAddressTest.java
Some mail systems protect FROM envelope addresses by signing them using BATV, this means that the FROM address can no longer be directly used to check who the sender is. This change strips out any private BATV signatures from the local part. We could try to be more generic and strip out more BATV possible tags but then we run the risk of stripping something we shouldn’t.
Doing it this was allows us to still do envelope time rejection but not reject BATV signed messages.
Supported formats are:
prvs=2987A7B7C7=me@example.com
me+prvs=2987A7B7C7@example.com
> SAK-32068 Extract local part from BATV addresses.

- reference/library/src/morpheus-master/sass/modules/_main.scss
https://jira.sakaiproject.org/browse/SAK-32084
The message that appears when JavaScript isn't enabled for Sakai isn't styled in Morpheus.
I have recreated the fixed red box that floats at the bottom of the browser window similar to how it did in Sakai 10. Works in the narrow mobile view too.
See the before and after screenshots for details.
**Before:**
**After:**
> SAK-32084 Styled the no-JS message for Morpheus

- user/user-tool/tool/src/webapp/vm/user/chef_users_edit.vm
Simple change to have the Cancel button on the right of the buttons and save in the left, as it is usual in forms.
> SAK-32086 Change Cancel button to the right in the User Creation Form

- login/login-tool/tool/src/bundle/auth.properties
- login/login-tool/tool/src/bundle/auth_en_GB.properties
https://jira.sakaiproject.org/browse/SAK-32085
The xlogin screen (when you type your password wrong) still says "Login required" and "Invalid login", and the button is still "Login". See SAK-29728 for reasoning behind the switch from "login" to "log in".
https://jira.sakaiproject.org/browse/SAK-29728
> SAK-32085 xlogin screen still uses 'login' instead of 'log in'

- calendar/calendar-util/util/pom.xml
- calendar/calendar-util/util/src/java/org/sakaiproject/util/CalendarUtil.java
- calendar/calendar-util/util/src/test/org/sakaiproject/util/CalendarUtilTest.java
Previously in the Calendar tool, the month name would be displayed
incorrectly when it was the 31 day of a month. This was resolved
by using the new Java 8 YearMonth object.
> SAK-31944 Fix Calendar tool Month display name

- reference/library/src/morpheus-master/sass/base/_responsive.scss
Move the :after pseudo class so that the arrow pointing at the tool menu is displayed for a mobile sized screen.  Add an overflow property so that the arrow is actually shown.
> SAK-31953 Pointer arrow now showing for mobile tools menu.

- providers/jldap/src/java/edu/amc/sakai/user/JLDAPDirectoryProvider.java
This covers the situation where the ldap provider is unwilling to authenticate because of some enforced rule by the ldap server.
> SAK-32078 Handle authentication exception when ldap provider is unwilling

- portal/portal-charon/charon/src/webapp/scripts/chat.js
This was causing an undefined error when a connection had been removed
while chat was loaded.
> SAK-32010 Added test for missing connection in currentConnectionsMap

- assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
Content review is disabled for all options after selecting NON-ELECTRONIC submissions.
This was fixed in master, for some reason wasn't merged in 11.x
> SAK-32117 - Content review is disabled for all options after selecting NON-ELECTRONIC submissions

- calendar/calendar-impl/impl/pom.xml
The old avalon dependency is very outdated now and our newer version of apache fop pulls in a much newer version.
> SAK-32120 Remove explicit avalon dependency

- kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
Properties on root collection are persisted on dupe / import / whatnot.
> KNL-1494 Copy Root Collection Properties

- mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java
This tests BATV from addresses in a full SMTP transaction.
> SAK-32068 Add BATV test with SMTP.
