assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java
https://jira.sakaiproject.org/browse/SAK-43341
=> SAK-43341 Use supplied siteId in gradebook sync

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43349
=> SAK-43349 Use user id and "anonymous" in anon Grader

common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.hbm.xml
This PR is related to https://github.com/sakaiproject/sakai-reference/pull/57
=> SAK-41812 - Profile name pronunciation. Better use of DB space

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-43401
=> SAK-43401 Fixed anonymous id in Grader

library/src/morpheus-master/sass/_defaults.scss, library/src/morpheus-master/sass/base/_material-defaults.scss, library/src/morpheus-master/sass/modules/navigation/_base.scss, library/src/morpheus-master/sass/modules/portal-search/_base.scss
https://jira.sakaiproject.org/browse/SAK-43426
=> SAK-43426 add !default to material scss definitions

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43397
=> SAK-43397 Fixed pass/fail in Grader

webcomponents/tool/src/main/frontend/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-43321
=> SAK-43321 Moved showPhoto check to sakai-grader.js

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js, webcomponents/tool/src/main/frontend/sakai-submission-messager.js
https://jira.sakaiproject.org/browse/SAK-42850
=> SAK-42850 Don't close messager dialog from event. Unreliable.

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, library/src/morpheus-master/sass/modules/grader/_base.scss, webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43350
=> SAK-43350 Added peer review icon and info to Grader

webcomponents/tool/src/main/frontend/sakai-i18n.js
https://jira.sakaiproject.org/browse/SAK-43430
=> SAK-43430 Cache i18n promises to reduce server requests

syllabus/syllabus-app/src/webapp/syllabus/edit.jsp, syllabus/syllabus-app/src/webapp/syllabus/read.jsp
https://jira.sakaiproject.org/browse/SAK-43383
=> SAK-43383 Syllabus console error

webcomponents/tool/src/main/frontend/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43320
=> SAK-43320 Render HTML entities in Grader site title

content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
Maybe the multiselect bits on sakai_properties_scripts.vm could be moved to a different function (similar to setupDatePickers), but it would be a bit messy anyway.
=> SAK-43028 Resources : Group settings when creating multiple folders

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43432
=> SAK-43432 Make new grader retract grades when saving

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java, msgcntr/messageforums-app/src/webapp/jsp/compose.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://jira.sakaiproject.org/browse/SAK-42963
=> SAK-42963 Messages : empty body validation

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
https://jira.sakaiproject.org/browse/SAK-43307
=> SAK-43307 Only show rubric to student if grade released

site-manage/site-group-manager/src/main/resources/Messages.properties, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step1.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import_confirmation.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
https://jira.sakaiproject.org/browse/SAK-43275
=> SAK-43275 Group Manager: Text prompt is difficult to read: Suggest font styling changes

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm, library/src/morpheus-master/sass/base/_defaults.scss, library/src/morpheus-master/sass/modules/grader/_base.scss, library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-element.js
https://jira.sakaiproject.org/browse/SAK-43337
=> SAK-43337 Validate points entry in grader

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/RubricsService.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
https://jira.sakaiproject.org/browse/SAK-43110
=> SAK-43110 show rubric button when in lessons -> samigo

rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubric-grading-comment.js, rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubric-grading.js, rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubric-student-comment.js
https://jira.sakaiproject.org/browse/SAK-43455
=> SAK-43455 Make the grading and student rubrics kb accessible

kernel/kernel-util/src/main/java/org/sakaiproject/util/comparator/UserSortNameComparator.java, kernel/kernel-util/src/test/java/org/sakaiproject/util/comparator/UserSortNameComparatorTest.java
Can specify if nulls should be high or low default is high
Includes unit tests
=> SAK-43478 Kernel make UserSortNameComparator null safe

kernel/kernel-impl/src/main/java/org/sakaiproject/db/impl/BasicSqlService.java
https://jira.sakaiproject.org/browse/SAK-40892
Please, we need some opinions. Thanks!
=> SAK-40892: Nested SqlService calls can lead to pool connection deadlock under certain conditions

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
https://jira.sakaiproject.org/browse/SAK-42833
=> SAK-42833 Added active class to assessment buttons

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.html, gradebookng/tool/src/webapp/scripts/gradebook-chart.js, gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-42252
=> SAK-42252 Messages broken on student view

syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java, syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/entityproviders/SyllabusEntityProvider.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/FixPublicSyllabusAttachmentsJob.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SiteEmailNotificationSyllabus.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusManagerImpl.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java, syllabus/syllabus-impl/src/webapp/WEB-INF/components.xml
=> SAK-43499 Deprecated utils.FormattedText => api.FormattedText

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubric-grading.js, samigo/samigo-app/src/webapp/jsf/evaluation/rubricModal.jsp, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43477
=> SAK-43477 Added author id to evaluation persistence

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
https://jira.sakaiproject.org/browse/SAK-43515
=> SAK-43515 Reduce the number of times calculated questions are processed

samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://jira.sakaiproject.org/browse/SAK-43522
=> SAK-43522 Added evaluated-item-owner-id to Samigo student view

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-settings.js
https://jira.sakaiproject.org/browse/SAK-43502
=> SAK-43502 GB: Modifying grading schema or using enter button throws user out of the settings page

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm
=> SAK-43547  Assignments: Use SWITCH banner when grading an assignment

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm, library/pom.xml, library/src/webapp/js/headscripts.js, webcomponents/bundle/src/main/bundle/date-picker-wc.properties, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-date-picker.js, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-43560
=> SAK-43560 Move sakai-date-picker to use Flatpickr

rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubric-grading-comment.js
https://jira.sakaiproject.org/browse/SAK-43520
=> SAK-43520 Make sure to destroy all criterion ckeditors

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
https://jira.sakaiproject.org/browse/SAK-43257
=> SAK-43257: Assignments: expanding the assignment instructions causes the page to reload

assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, library/src/morpheus-master/sass/modules/grader/_base.scss, library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43473
=> SAK-43473: Assignment: Info peer icon should be with cursor: pointer

polls/tool/src/webapp/templates/votePolls.html
https://jira.sakaiproject.org/browse/SAK-43569
=> SAK-43569 - Polls / attempting to sort columns on main page displays 404 error

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://jira.sakaiproject.org/browse/SAK-42641
=> SAK-42641 - Rubrics may not be deleted when the users that delete the sites are different.

rubrics/api/src/main/bundle/rubrics.properties, rubrics/api/src/main/bundle/rubrics_ca.properties, rubrics/api/src/main/bundle/rubrics_es.properties, rubrics/tool/src/main/frontend/webcomponents/js/sakai-rubrics-manager.js
https://jira.sakaiproject.org/browse/SAK-43579
=> SAK-43579 - Rubrics: Ability to search rubrics and shared rubrics

library/src/webapp/js/headscripts.js, webcomponents/tool/src/main/frontend/js/sakai-date-picker.js
https://jira.sakaiproject.org/browse/SAK-43572
Also set position to auto
=> SAK-43572 Sakai Date Picker Add confirmDate plugin

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
https://jira.sakaiproject.org/browse/SAK-43190
=> SAK-43190 Reinstate rubric icon in forums tool

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43576
=> SAK-43576 Set release status as "return" in grader

jobscheduler/scheduler-component-shared/src/test/java/org/sakaiproject/component/app/scheduler/ScheduledInvocationTest.java, kernel/api/src/test/java/org/sakaiproject/util/ToolListenerTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/authz/impl/SakaiSecurityTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/WrappedContentResourceTest.java, mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java, mailsender/api/src/test/org/sakaiproject/mailsender/AttachmentExceptionTest.java, mailsender/api/src/test/org/sakaiproject/mailsender/MailsenderExceptionTest.java, mailsender/api/src/test/org/sakaiproject/mailsender/model/ConfigEntryTest.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ComposeLogicImplTest.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ConfigLogicImplTest.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ExternalLogicImplTest.java, master/pom.xml, providers/cm-authz-provider/test/org/sakaiproject/coursemanagement/impl/provider/CourseManagementGroupProviderTest.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java, textarea/elfinder-sakai/src/test/org/sakaiproject/elfinder/sakai/content/ContentSiteVolumeFactoryTest.java
=>
import org.mockito.junit.MockitoJUnitRunner;
=> SAK-43551 Deprecated: import org.mockito.runners.MockitoJUnitRunner;

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
https://jira.sakaiproject.org/browse/SAK-43113
=> SAK-43113 Clean up ItemGradingData in Samigo

roster2/tool/src/java/org/sakaiproject/roster/api/RosterMemberComparator.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/webapp/js/roster.js
https://jira.sakaiproject.org/browse/SAK-43087
=> SAK-43087 Change load order in roster.js

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43575
=> SAK-43575 Make sure resubmit is not enabled if set at zero

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
https://jira.sakaiproject.org/browse/SAK-43660
=> SAK-43660 Make portal search honour seach.enable

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
https://jira.sakaiproject.org/browse/SAK-41505
=> SAK-41505 Added direct memberships to GB sections columns

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-43661
New property: assignment.usegraderbydefault=true|false
=> SAK-43661 Added property to default grader check to off

basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
This only showed up when I actually made a mistake between two Internet connected servers.  Thankfully a reasonably easy fix.
=> SAK-43715 - Transport cookie to error dialog

basiclti/tsugi-util/pom.xml, basiclti/tsugi-util/src/java/org/tsugi/basiclti/ContentItem.java, basiclti/tsugi-util/src/test/org/tsugi/contentitem/ContentItemTest.java
https://jira.sakaiproject.org/browse/SAK-43717
=> SAK-43717 Unescape the data param returned from content link

samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecording.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/item/displayFileUpload.jsp
SAK-43631 Samigo: Do not display question's attachment
=> SAK-43631 Samigo: Do not display question's attachment

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/api/pom.xml, kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/content/api/FileConversionService.java, kernel/api/src/main/java/org/sakaiproject/content/api/repository/FileConversionQueueItemRepository.java, kernel/api/src/main/java/org/sakaiproject/content/hbm/FileConversionQueueItem.java, kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/FileConversionServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/converters/LoolFileConverter.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/repository/FileConversionQueueItemRepositoryImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/components.xml, kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml, kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml, kernel/kernel-impl/src/main/webapp/WEB-INF/messagebundle-components.xml, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/FileConversionServiceTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/FileConversionServiceTestConfiguration.java, webcomponents/tool/src/main/frontend/js/fa-icon.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-43541
=> SAK-43541 Add optional converter for attachments

gradebookng/tool/pom.xml
Reverts sakaiproject/sakai#8260
=> Revert "SAK-43720 update versions (webjars & etc)"

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java, mailarchive/mailarchive-impl/impl/src/java/org/sakaiproject/mailarchive/impl/BaseMailArchiveService.java, mailsender/impl/src/java/org/sakaiproject/mailsender/logic/impl/ExternalLogicImpl.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ExternalLogicImplTest.java
Mark user mutable permissions
Co-Authored-By: Francisco Saez Segura <francisco.saez.segura@gmail.com>
=> SAK-43724 Fix permissions widget for instructors

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
https://jira.sakaiproject.org/browse/SAK-43776
=> SAK-43776 Improved Ignite Network Configuration

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://jira.sakaiproject.org/browse/SAK-43786
=> SAK-43786 Kernel configure Ignite caches to favor reads

deploy/pom.xml, kernel/kernel-impl/pom.xml, master/pom.xml
https://jira.sakaiproject.org/browse/SAK-43804
=> SAK-43804 Kernel update apache ignite to 2.8.1

webcomponents/tool/pom.xml, webcomponents/tool/src/main/frontend/.gitignore, webcomponents/tool/src/main/frontend/.storybook/main.js, webcomponents/tool/src/main/frontend/.storybook/manager.js, webcomponents/tool/src/main/frontend/.storybook/preview.js, webcomponents/tool/src/main/frontend/.storybook/sakaiTheme.js, webcomponents/tool/src/main/frontend/js/sakai-course-card.js, webcomponents/tool/src/main/frontend/js/sakai-i18n.js, webcomponents/tool/src/main/frontend/js/sakai-icon.js, webcomponents/tool/src/main/frontend/js/sakai-options-menu.js, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/stories/sakai-course-card.stories.js, webcomponents/tool/src/main/frontend/stories/sakai-icon.stories.js, webcomponents/tool/src/main/frontend/stories/sakai-options-menu.stories.js
https://jira.sakaiproject.org/browse/SAK-43737
=> SAK-43737 Added sakai-course-card component

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_ca.properties, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
The message itself is also clarified.
=> SAK-40517. Changes to show linear access message only when this option is selected.

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java
https://jira.sakaiproject.org/browse/SAK-43781
=> SAK-43781: define system property elsewhere in case ical import is disabled

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-group-picker.js
https://jira.sakaiproject.org/browse/SAK-43827
=> SAK-43827 Allow grade replacement in new grader

rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-readonly.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-preview.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-student.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-grading-button.js
https://jira.sakaiproject.org/browse/SAK-43222
(cherry picked from commit d015a8290b83af7266608bc746e1e1335950514b)
=> SAK-43222 Support i18n decimal separators in Rubrics. (#7942)

samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMatching.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemText.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
Followup on #8261 from testing.
It looks like the java.util.ResourceBundle was used in these classes and I couldn't swap to the Sakai one without introducing a class cast exception. So I just left this as the string and do the resource translation in the JSF.
=> SAK-34123 - Samigo Grade By Question still showing "None of the Above"

kernel/api/src/main/java/org/sakaiproject/email/api/Attachment.java, kernel/api/src/main/java/org/sakaiproject/email/api/AttachmentSizeException.java, kernel/api/src/main/java/org/sakaiproject/email/api/EmailService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java, mailsender/api/src/bundle/mailsender.properties, mailsender/impl/src/java/org/sakaiproject/mailsender/logic/impl/ExternalLogicImpl.java
https://jira.sakaiproject.org/browse/SAK-42763
=> SAK-42763 Bubble attachment exception in mailsender

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, mailarchive/mailarchive-subetha/pom.xml, mailarchive/mailarchive-subetha/src/bundle/sakaimailet.properties, mailarchive/mailarchive-subetha/src/bundle/sakaimailet_es.properties, mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java, mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java, mailarchive/mailarchive-subetha/src/webapp/WEB-INF/components.xml, msgcntr/messageforums-api/pom.xml, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es_ES_Pearson.properties, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/SynopticMsgcntrManager.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/PrivateMessageManager.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/SynopticMsgcntrManagerImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
SAK-42856: Provide a way to reply private messages from external mail
=> SAK-42856: Provide a way to reply private messages from external mail

msgcntr/messageforums-app/src/webapp/js/messages.js, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
https://jira.sakaiproject.org/browse/SAK-33643
=> SAK-33643 Move form id to avoid duplicate js code.

msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://jira.sakaiproject.org/browse/SAK-43880
=> SAK-43880 Extend SAK-33242 solution to other forms.

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
https://jira.sakaiproject.org/browse/SAK-43879
=> SAK-43879 Samigo - clicking MCSC answer labels don't select their radio buttons

lessonbuilder/tool/pom.xml, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/PrintHandler.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/cc/QtiImport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/AssignmentExport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AjaxServer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/ForumEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ReorderProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml, lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
SimplePageBean cover => api
Web.escapeJavascript => commons-text  StringEscapeUtils.escapeEcmaScript
https://jira.sakaiproject.org/browse/SAK-43895
=> SAK-43895 Deprecated utils.FormattedText => api.FormattedText

webcomponents/tool/pom.xml, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-43147
=> SAK-43147 Populate score field on evaluation intial load

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PresenceHandler.java
https://jira.sakaiproject.org/browse/SAK-43902
=> SAK-43902 dont relogin on a /portal/presence/ fragment

basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java
I am going to write me a minivan!
=> SAK-42491 - Trim text fields in the Foorm layer

basiclti/basiclti-common/src/java/org/sakaiproject/util/foorm/Foorm.java, basiclti/basiclti-tool/src/bundle/ltitool.properties, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/basiclti-tool/src/webapp/vm/lti_tool_view.vm, library/src/webapp/js/headscripts.js
Please review for accessibility of these new buttons.
=> SAK-43886 - Add copy buttons to LTI 1.3 values

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
https://jira.sakaiproject.org/browse/SAK-43923
More info in the JIRA. Exact steps not yet identified. PR is just a basic data guard.
=> SAK-43923: calendar > basic data validation saving default view

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java, basiclti/tsugi-util/src/java/org/tsugi/basiclti/BasicLTIUtil.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/ForumEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/JForumEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java
Note that the case of DBLTIService.java was wrong (it was Db)
=> SAK-40044 - Pass description and name to LTI for launch

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
=> SAK-44000 - Make key pattern in hasAssociatedRubricMap consistent

basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java, basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-common/src/java/org/sakaiproject/lti13/LineItemUtil.java, basiclti/basiclti-common/src/java/org/sakaiproject/lti13/util/SakaiLineItem.java, basiclti/basiclti-tool/pom.xml, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/tsugi-util/src/java/org/tsugi/ags2/objects/LineItem.java, basiclti/tsugi-util/src/java/org/tsugi/basiclti/BasicLTIUtil.java, basiclti/tsugi-util/src/java/org/tsugi/basiclti/ContentItem.java
=> SAK-43890 - Support LineItem

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
I don't know this code but this seems like a big error in 20.x and master.
CC: @bgarciaentornos and @ern
=> SAK-43787 fix student confirmation page not showing attachments

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
This is another addition where the return link was missing the clearAttr param
=> SAK-41806 Lessons not adding clearAttr param to return link

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
=> SAK-43709 - Change length of keyset_url and remove tool_kid

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java, assignment/api/src/resources/assignment.properties, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java, assignment/impl/src/webapp/WEB-INF/components.xml, assignment/tool/pom.xml, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_view_launch.vm, basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java
Sakai-21 only unless you add data columns.
=> SAK-44019 - Add LTI Assignment type

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/LTICustomVars.java
Begin the forward-post of the LTI 2.0 stuff that was removed.
=> SAK-44047 - Bring back substitution parameters

assignment/tool/pom.xml, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/DeepLinkResponse.java
Also fix a small bug in SAK-44019 along the way
=> SAK-44043 Add Assignment related subsititution variables

samigo/samigo-app/src/webapp/jsf/evaluation/item/displayAudioRecordingAnswer.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/item/displayFileUploadAnswer.jsp
This method was removed from the API but seems like it's fine to just check it here. 
It looks like this style didn't work at one time but I tested this without any issues.
=> SAK-44058 - SAMIGO: Error when clicking Question tab with a File Upload question

library/src/morpheus-master/sass/_defaults.scss, library/src/morpheus-master/sass/base/_extendables.scss, library/src/morpheus-master/sass/themes/_base.scss, library/src/morpheus-master/sass/themes/_dark.scss, library/src/morpheus-master/sass/themes/_light.scss, library/src/morpheus-master/sass/tool.scss
https://jira.sakaiproject.org/browse/SAK-43978
~~**Has build errors. Please don't merge.** Please add work in progress label~~
~~I wanted to put a WIP PR out there to generate discussion around this approach for light and dark theming.~~
Ready for approval and merging.
=> SAK-43978 - Library - expanded hsl color palette

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
=> SAK-44098 null check to fix Assignment edit regression introduced by LTI Assignment Types

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://jira.sakaiproject.org/browse/SAK-44080
Add the locally configured sections to the list of user sections
=> SAK-44080 Sections Column displays None for Non Provided Sections

presence/presence-tool/tool/src/java/org/sakaiproject/presence/tool/PresenceTool.java
This removes the functional use of /courier/ URLs from the portal presence tool,
eliminating end-user requests to /courier/... which serve no purpose, because
requesting the presence list itself also serves to establish the user's presence in a site,
and the morpheus js refreshes the presence anyway.
Complete cleanup left for SAK-39977, including removal of scheduleUpdate() from headscripts.js
which is referenced from some other places too (JSF widgets).
Should be mergeable back to 20.x
=> SAK-44066 Remove courier from portal presence

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/EmailUtil.java, assignment/impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-44104
=> SAK-44104 Use entityproducer api to get assignment url

library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js, library/src/morpheus-master/sass/base/_defaults.scss, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-render-engine-impl/impl/src/test/org/sakaiproject/portal/charon/test/MockCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm, webcomponents/bundle/src/main/bundle/maximise-button.properties, webcomponents/tool/src/main/frontend/js/sakai-maximise-button.js
https://jira.sakaiproject.org/browse/SAK-44013
=> SAK-44013 Give visual feedback when in maximised tool mode.

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
This pull request is for [SAK-44118](https://jira.sakaiproject.org/browse/SAK-44118)
=> SAK-44118 - remove pop-up whenever there is valid input in numeric input field

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-44006
If there's submitted text, show that by default. If not, show the first
attachment by default.
=> SAK-44006 Show the first submission attachment by default

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
SAK-43766: "Hide Items" doesn't work for categories in Gradebook
=> SAK-43766: "Hide Items" doesn't work for categories in Gradebook

presence/presence-tool/tool/src/java/org/sakaiproject/presence/tool/PresenceToolAction.java
Set the initial view correctly again
=> SAK-39977 Restore correct operation of the Online tool

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java, basiclti/basiclti-impl/src/bundle/ltiservice.properties, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java
All content items can have custom parameters - as it should be.
=> SAK-44179 - Remove the allowcustom checkbox feature

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
sakaiId is saved NULL on ORACLE and empty on MySQL.
=> SAK-44204: ORACLE - Lessons - Can't embed videos as iframe

content/content-bundles/resources/content.properties, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java, content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
https://jira.sakaiproject.org/browse/SAK-30942
You can currently create web links with no URL and no name, resulting in things titled like "__________________20200214165155" which take you to a 404 for obvious reasons.
This PR implements some basic validation and error messaging.
=> SAK-30942: resources > no validation or error messaging when creating web links

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/DelegatedAccessApplication.java, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
https://jira.sakaiproject.org/browse/SAK-44099
These came to light due to Chuck's smoke testing script.
=> SAK-44099: make some wicket links bookmarkable

samigo/samigo-app/pom.xml, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
https://jira.sakaiproject.org/browse/SAK-44218
Some environments present JSTL stack trace when attempting to begin a quiz. More details in the JIRA. We don't need to use this lib, let's just remove it.
=> SAK-44218: samigo > remove jstl

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, kernel/api/src/main/java/org/sakaiproject/content/api/ContentResource.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-44183
=> SAK-44183 Let grader preview images

portal/portal-impl/impl/src/bundle/sitenav.properties
https://jira.sakaiproject.org/browse/SAK-42133
Change suggested by Tiffany.
=> SAK-42133: portal > add keyboard instructions for organize favourites

kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-44201
=> SAK-44201 Task creation should merge entities

kernel/kernel-impl/src/main/java/org/sakaiproject/messagebundle/impl/CachingMessageBundleServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/messagebundle/impl/MessageBundleServiceImpl.java, kernel/kernel-impl/src/test/java/org/sakaiproject/messagebundle/impl/test/CachingMessageBundleTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/messagebundle/impl/test/CachingMessageBundleTestConfiguration.java, kernel/kernel-impl/src/test/java/org/sakaiproject/messagebundle/impl/test/MessageBundleTest.java
CachingMessageBundleServiceImpl.getBundle should never return a null
=> SAK-44143 Kernel CachingMessageBundleServiceImpl.getBundle regression

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-43782
=> SAK-43782 Grader feedback comment updates correctly

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://jira.sakaiproject.org/browse/SAK-44150
Keyboard users are unable to select this text for copy/paste. Suggestion from accessibility expert is to add a copy to clipboard button.
=> SAK-44150: samigo > add button to copy published assessment url to clipboard (a11y)

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/SectionAwareServiceHelperImpl.java
=> SAK-43104 Samigo allow user with permission assesment.grade.any to grade

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-43853
=> SAK-43853 Ensure resubmit date is valid in grader

library/src/morpheus-master/sass/modules/navigation/_base.scss
https://jira.sakaiproject.org/browse/SAK-43266
=> SAK-43266: Correct capitalize "Enter access View"

portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AddAssignmentBullhornHandler.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/BullhornServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-43033
=> SAK-43033: Bullhorns: Group assignments displaying twice

samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://jira.sakaiproject.org/browse/SAK-43000
Menus that are open will have arrows pointing down, and are highlighted. Menus that are closed will have arrows pointed to the right - unhighlighted. Expand and collapse all buttons will consistently open / close / highlight
=> SAK-43000 Give assessment settings expand/collapse all functions consistent icons and highlighting

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
=> SAK-44217 fix issue where Samigo GB item was being re-created every time assessment re-saved

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
Reverts sakaiproject/sakai#8511
https://jira.sakaiproject.org/browse/SAK-34322
Original PR caused a regression, and no longer able to reproduce the original stated issue.
=> Revert "SAK-34322: samigo > block editing published quiz to send grades to existing gradebook item"

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://jira.sakaiproject.org/browse/SAK-44150
Feedback from Jen Bethmann indicated the original text was not satisfactory, so I've implemented her suggestion.
=> SAK-44150: samigo > further qualify copy to clipboard button label for screen readers

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAggregateJobImpl.java, sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
This also removes the CR line-endings from components.xml, so view without whitespace changes to see the actual change.
=> SAK-44261 Use the stateful quartz wrapper for the SiteStats aggregation job

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-44006
=> SAK-44264 Only warn if a grader user is not found

library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js, library/src/morpheus-master/sass/base/_defaults.scss, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
https://jira.sakaiproject.org/browse/SAK-44293
I agree with Adam's comment on the original ticket SAK-44013, make the whole
full screen message clickable and do away with the max button in the
message.
=> SAK-44293 Make full screen message clearer and clickable

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
=> SAK-44171 Lessons tool does not display Resource folder displayname

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeValidator.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/TimeLimitValidator.java
https://jira.sakaiproject.org/browse/SAK-44297
=> SAK-44297 samigo > exception with no start date causes NPE

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/TimedAssessmentRunnable.java
CC: @dnhutchins  have you ever seen this error?
=> SAK-44314 fix IndexOutOfBoundsException with EventLogData on abandoned timed assessment

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-44081
=> SAK-44081 Select current pass/fail grade in new grader

webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-44186
=> SAK-44186 Only update document viewer if i18n present

kernel/kernel-impl/src/main/java/org/sakaiproject/alias/impl/DbAliasService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
StringUtil.trimToZero => (commons-lang3) StringUtils.trimToEmpty
=> SAK-44317 StringUtil.limit => (commons-lang3) StringUtils.abbreviate

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/SchedulerManagerImpl.java
I moved the cleanup job part to run outside of the init, later right before the scheduler is actually started. I wanted to do this in the original change but it didn't seem as necessary but it's still hitting some jobs during startup that it doesn't need to. 
There might be a *better* fix for this problem, but this should also fix this as well.
=> SAK-44258 - NPE with SamigoETSProvider in startup with samigo autosubmit quartz job

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, webcomponents/tool/src/main/frontend/js/grader/grader-toggle.js
https://jira.sakaiproject.org/browse/SAK-43661
=> SAK-43661 Add property to force grader toggle to default to off

webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-44331
=> SAK-44331 Initialise previewableAttachments in grader

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-44001
Quizzes submitted via the time out pop up, or quizzes submitted by the auto submit job which are submitted after the due and/or late acceptance date are not marked as late.
=> SAK-44001 samigo > late submissions auto submitted by job or at due/late date not marked as late

webcomponents/tool/src/main/frontend/js/rubrics/sakai-item-delete.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js
https://jira.sakaiproject.org/browse/SAK-44332
=> SAK-44332 Update to rubrics sortablejs to dashboard version

webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-43390
=> SAK-43390 Switch previewed documents correctly in new grader

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-44226
=> SAK-44226 Use sort name in new grader

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-44103
=> SAK-44103 Improve submitted attachments list in new grader

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
Depends on #8598 as currently is
=> SAK-44302 - Reduce ignite logging

library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
https://jira.sakaiproject.org/browse/SAK-44355
=> SAK-44355 Test for fullscreen markup before attaching js

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
https://jira.sakaiproject.org/browse/SAK-44395
=> SAK-44395 Only check for rubric associations once for student buttons

content/content-impl-providers/impl/src/java/org/sakaiproject/content/providers/BaseEventDelayHandler.java, kernel/api/src/main/java/org/sakaiproject/event/api/EventDelayHandler.java, kernel/api/src/main/java/org/sakaiproject/event/api/EventTrackingService.java, kernel/api/src/main/java/org/sakaiproject/event/cover/EventTrackingService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseEventTrackingService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/EventTrackingTest.java, kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockEventTrackingService.java
EventDelayHandler:
String createDelay(Event event, Time fireTime);
+ String createDelay(Event event, Instant fireTime);
String createDelay(Event event, String userId, Time fireTime);
+ String createDelay(Event event, String userId, Instant fireTime);
EventTrackingService:
delay(Event event, Time fireTime):
+ void delay(Event event, Instant fireTime);
=> SAK-44338 Event: Time => Instant

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/EvaluationRepository.java, rubrics/tool/src/main/java/org/sakaiproject/rubrics/security/CustomMethodSecurityExpressionRoot.java
https://jira.sakaiproject.org/browse/SAK-44125
=> SAK-44125 Stop show/hide rubrics setting rubrics.editor

library/src/morpheus-master/sass/modules/grader/_base.scss, webcomponents/bundle/src/main/bundle/file-picker.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader-file-picker.js
https://jira.sakaiproject.org/browse/SAK-44074
=> SAK-44074 Allow removal of files from picked list in grader

portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AddAssignmentBullhornHandler.java
I have made a solution to fix this jira issue. It can be integrated into Master.
Thank you very much.
=> SAK-44425 Draft assignments are displayed in Bullhorns notifications

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/BeanDateComparator.java
I attempted to fix this by using a custom ConvertUtils DateConverter routine to override the default BeanUtils routines but had absolutely zero luck after several hours.
=> SAK-43921 fix broken submittedDate sorting.

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsTypeManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsTypeManagerImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Reverts sakaiproject/sakai#8606
https://jira.sakaiproject.org/browse/SAK-44305
There were objections on the ticket with regards to how this was implemented.
=> Revert "SAK-44305 Messages > Compose Message > Specify Recipient > Save Draft > Recipient not Saved"

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://jira.sakaiproject.org/browse/SAK-44371
Error currently displayed:
> editStudentResults:j_id_jsp_482064350_61:0:j_id_jsp_482064350_66:0:adjustedScore: Validation Error: Value is not of the correct type
New error message:
> You must enter a real number to adjust the score for this question.
=> SAK-44371 samigo > provide custom error message for invalid adjusted score value

assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java, gradebookng/tool/src/webapp/scripts/gradebook-saverubric.js, msgcntr/messageforums-app/src/webapp/js/forum.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, samigo/samigo-app/src/webapp/js/samigo-global.js, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-43646
=> SAK-43646 Only persist rubric evaluations when hosting tool saves

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/BasePortalHandler.java, portal/portal-util/util/src/java/org/sakaiproject/portal/util/PortalUtils.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java, samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
https://jira.sakaiproject.org/browse/SAK-44422
=> SAK-44422 Setup portal.locale js var for by url test sessions

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
https://jira.sakaiproject.org/browse/SAK-44061
=> SAK-44061: SAMIGO - Error while saving without From(Required) 'Feedback will be displayed to the student on specific dates'

msgcntr/messageforums-app/src/webapp/jsp/dfCompose.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfMessageReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfMessageReplyThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfMoveThreads.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfMsgRevise.jsp
https://jira.sakaiproject.org/browse/SAK-33976
=> SAK-33976 forums > remove redudant and incorrect word count when authoring/editing posts

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://jira.sakaiproject.org/browse/SAK-43796
Drafts should not appear in the instructor's list of student submissions. They aren't included in the "count", and if you click on the draft you aren't able to see the draft's contents anyway.
=> SAK-43796 assignments > submission list > don't display drafts

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
=> SAK-44413 document the preference for the RemoteIpValve over the force.url.secure property

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationEdit.html
SAK-43941 Profile: name pronunciation not saved
=> SAK-43941 Profile: name pronunciation not saved

library/src/morpheus-master/sass/modules/tool/_table.scss, webcomponents/tool/src/main/frontend/js/sakai-permissions.js
Removing inline style, fixing indentation
Initially I pointed it to the wrong jira (see https://github.com/sakaiproject/sakai/pull/8709)
=> SAK-44494 Fix mobile display for table

msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-44432
=> SAK-44432 - Added missing init method to the MembershipManagerImpl bean

library/src/webapp/js/sakai-recorder.js, samigo/samigo-app/src/webapp/jsf/author/audioRecordingPopup.jsp
It looks like the property causing this issue is not even used anywhere, so we can remove the references altogether
=> SAK-44498 T&Qs : avoid stack trace

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
https://jira.sakaiproject.org/browse/SAK-29425
1) bug fix for when no posts in site
2) fix duplicate message bundle key
Hide whitespace for a cleaner diff. File is tabs, I didn't notice this in the original PR.
=> SAK-29425 bug fix for 0 posts total

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
https://jira.sakaiproject.org/browse/SAK-29425
=> SAK-29425 math error

library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-44523
=> SAK-44523 Defined border for select drop-down menus

samigo/samigo-app/src/java/org/sakaiproject/jsf/util/SamigoJsfTool.java
https://jira.sakaiproject.org/browse/SAK-44049
Hi,
It was a problem with session variable.
I've made a fixing setting this variable when Tests and Quizzies start.
The problem happens in sakai 22.x, 21.x, 20.x, 19.x.
Thanks.
=> SAK-44049 Test and quizzes - redirects to Lessons

announcement/announcement-api/api/src/bundle/announcement_es.properties, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementActionState.java
Modifying some Spanish translations that were a bit surreal
=> SAK-44461 Announcements : selector not getting values

library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_forms.scss
SAK-44507 Low color contrast for exception text
=> SAK-44507 Low color contrast for exception text

profile2/tool/src/webapp/css/profile2.css
The style of the item was commented.
=> SAK-44174 Profile: The font of the time of publication

kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
https://jira.sakaiproject.org/browse/SAK-44492
=> SAK-44492 Removed JSF state override for forums

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java, samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
https://jira.sakaiproject.org/browse/SAK-44547
=> SAK-44547 Move locale setup into delivery bean constructor

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java
Please see description: https://jira.sakaiproject.org/browse/SAK-44532
Regression caused by: https://github.com/sakaiproject/sakai/commit/0b9d28b85062a7d6358c57bd0accedcdf9904a8b#diff-be390a19db9bd25a62515c17e11a06599ccc4a11744d6d98a9c9ad70315c8050R911
=> SAK-44532: Error when try adding a student on a blocked section/group

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44564
=> SAK-44564 Let lit-element do the points input update

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java, samigo/samigo-app/src/webapp/js/saveForm.js, samigo/samigo-app/src/webapp/jsf/delivery/getTimerProgress.jsp, samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
=> SAK-44553 handle scenario where tab is backgrounded and XHR syncing submission status is missing

lessonbuilder/tool/src/webapp/css/Simplepagetool.css
https://jira.sakaiproject.org/browse/SAK-44093
=> SAK-44093 lessons breadcrumb navigation

site-manage/site-group-manager/src/main/resources/Messages.properties, site-manage/site-group-manager/src/main/resources/Messages_es.properties, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-43531
=> SAK-43531 Manage Groups: Improve the empty state

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
https://jira.sakaiproject.org/browse/SAK-43838
=> SAK-43838 Only remove items from a pool if we need to

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/PrivateMessage.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/PrivateMessageImpl.java
Bugs fixes for SAK-42856: Provide a way to reply private
=> SAK-44397: Bugs fixes for SAK-42856: Provide a way to reply private

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/assesment/service/GradingServiceTest.java
=> SAK-44579 matching unicode FIB needs help when user input from Mac is HTML-encoded

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/webapp/js/samigo-global.js, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
Reverts sakaiproject/sakai#8710
This is preventing students from taking quizzes, and has intermittent issues for instructors creating and editing quizzes.
=> Revert "SAK-44504 Add multiple assessment protection to client"

library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-item-delete.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-rating-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating
SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating
=> SAK-43760 Rubrics: Can not use keyboard-only to edit criterion or rating

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java, samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
https://jira.sakaiproject.org/browse/SAK-44552
... or if negative marking has been selected
=> SAK-44552 Disable min points if partial credit selected

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/LTICustomVars.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
Adds new property: 'msgcntr.unrestricted.group.perms'
=> SAK-44132 Add Sakai property to disable group permission locking in Forums

kernel/kernel-impl/src/main/java/org/sakaiproject/messagebundle/impl/MessageBundleServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-44550
=> SAK-44550 Message bundle manager throws error

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
SAK-44597 Rubrics: Error in console sorting rubrics
=> SAK-44597 Rubrics: Error in console sorting rubrics

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
https://jira.sakaiproject.org/browse/SAK-44577
=> SAK-44577 Private messages - Error creating new folder

signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java
https://jira.sakaiproject.org/browse/SAK-44582
=> SAK-44582 SIGNUP - Signup isn't available for students

kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/FormattedTextTest.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java
https://jira.sakaiproject.org/browse/SAK-44632
=> SAK-44632 question stripping should not unescape escaped-HTML or it will distort display

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/AssignmentExport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/CCConfig.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/CCExport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/ForumsExport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/LessonsExport.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/SamigoExport.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-43916
=> SAK-43916 Fix issues with cc export

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-44555
=> SAK-44555 T&Qs : minimum points on unanswered questions

content/content-bundles/resources/content.properties, content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
https://jira.sakaiproject.org/browse/SAK-30942
This regressed since original contribution, discovered during QA testing.
=> SAK-30942 content > fix validation for web links

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties
SAK-44626 Lessons Add Dates to Assignment Links
=> SAK-44626 Lessons Add Dates to Assignment Links

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorActionListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacade.java
=> SAK-44648 only show "late" text to instructor when past due but still active

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
=> SAK-44652 provide warning when instructor grades students in multiple tabs

content/content-tool/tool/src/webapp/WEB-INF/tools/sakai.dropbox.xml, kernel/api/src/main/java/org/sakaiproject/tool/api/ToolManager.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tool/impl/ToolComponent.java, kernel/kernel-impl/src/test/java/org/sakaiproject/tool/impl/ActiveToolComponentTest.java, site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java, sitestats/sitestats-tool/src/webapp/WEB-INF/tools/sakai.sitestats.xml
https://jira.sakaiproject.org/browse/SAK-43149
=> SAK-43149 Fix the handling of OR required functions, in page order

samigo/samigo-app/src/webapp/jsf/delivery/noLateSubmission.jsp
=> SAK-34249 dont POST on the Return button so the student can take 

site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/JoinableSetController.java
https://jira.sakaiproject.org/browse/SAK-44670
=> SAK-44670 Joinable Set: Group numbers should start at 1

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-44685
=> SAK-44685 Update OpenCVS 5.3

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-44624
=> SAK-44624: SAMIGO - Student response column on Question tab is not update when Regrade and Republish

content-review/impl/turnitin-oc/README.md, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
https://jira.sakaiproject.org/browse/SAK-44666
=> SAK-44666 Turnitin OC: Student changes to the similarity exclusions are saved in the viewer

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
https://jira.sakaiproject.org/browse/SAK-44700
=> Announcements > Add > Availability > "Hide" label isn't connected to its radio button

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java, webcomponents/tool/src/main/frontend/js/sakai-home-dashboard.js
https://jira.sakaiproject.org/browse/SAK-44688
Also, fixed the grades controller. Was throwing exceptions into the
logs when a user didn't have grading permissions in a site.
=> SAK-44688 Display a MOTD message in the home dashboard

dashboard/README.md
https://jira.sakaiproject.org/browse/SAK-44710
=> SAK-44710 Updated the dashboard's readme.

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/webapp/js/saveForm.js, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/getTimerProgress.jsp, samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
=> SAK-44627 use timer to see if user has navigated to another assessment

assignment/api/pom.xml
https://jira.sakaiproject.org/browse/SAK-43805
=> SAK-43805 Assignment add conversion i18n bundles

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44727
=> SAK-44727 Add test for this.evaluation being present

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/EvaluationRepository.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/ToolItemRubricAssociationRepository.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-item-delete.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-preview-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
https://jira.sakaiproject.org/browse/SAK-44726
... and improve some of the rest endpoint names
=> SAK-44726 Clean up rubrics missing method

samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
CC: @dnhutchins are you willing to review?
=> SAK-44735 allow timerbar to work inside external iframe

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
@ern I can't use directly org.sakaiproject.util.comparator.UserSortNameComparator because this comparator is for User class and my class is Submitter, so I can't do this:
submitters.sort(new UserSortNameComparator());
The error:
The method sort(Comparator<? super GradeSheetExporter.Submitter>) in the type List<GradeSheetExporter.Submitter> is not applicable for the arguments (UserSortNameComparator)
What would be the correct way to do this?
=> SAK-43678 Assignments: Incorrect order in name column when downloading spreadsheet [XLSX]

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, mailarchive/mailarchive-subetha/src/bundle/sakaimailet.properties, mailarchive/mailarchive-subetha/src/bundle/sakaimailet_es.properties, mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/PrivateMessageManager.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-44638
Bugs fixes for [SAK-42856](https://jira.sakaiproject.org/browse/SAK-42856): Message destination error
=> SAK-44638: Bugs fixes for SAK-42856: Message destination error

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradingEventStatus.java, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradingEvent.hbm.xml, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradingEvent.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/bundle/src/main/bundle/gradebookng_es.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbGradeLog.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeLogPanel.java
[SAK-41502](https://jira.sakaiproject.org/browse/SAK-41502): Excusing an individual grade should be reflected in score's
Database changes: https://github.com/sakaiproject/sakai-reference/pull/90
=> SAK-41502: Excusing an individual grade should be reflected in score's

lessonbuilder/tool/src/webapp/css/Simplepagetool.css
https://jira.sakaiproject.org/browse/SAK-43919
I have removed the style class that caused that.
Thank you.
=> SAK-43919 Lessons: Delete button doesn't align with other buttons

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
https://jira.sakaiproject.org/browse/SAK-44486
=> SAK-44486 Forums - email notification is sent to users who didn't participate in conversation

.github/workflows/maven.yml, sitestats/sitestats-impl/pom.xml
Add profile to setup test exclusions and add StatsUpdateManagerTests
=> SAK-44746 GithubActions test exclusions

site-manage/site-manage-api/api/src/java/org/sakaiproject/sitemanage/api/SiteManageConstants.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-44113
=> SAK-44113 Fix order of gradebook, calendar and assignment imports

samigo/samigo-app/src/webapp/js/samigo-global.js
We don't need that because now we haven't got iframe.
Similar to: https://github.com/sakaiproject/sakai/pull/8845
=> SAK-44743: SAMIGO - No need recalculate height when editor HTML is shown

library/src/morpheus-master/sass/modules/grader/_base.scss, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-44745
=> SAK-44745 Improve the styling of the new grader

samigo/samigo-app/src/webapp/js/saveForm.js
… (instead of on the page load)
=> SAK-44730 re-add the counter variable so that auto-save only fires a POST after XX seconds

content/content-bundles/resources/types.properties, content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm
https://jira.sakaiproject.org/browse/SAK-44768
Move the copyright instructions into the copyright section where they belong.
=> SAK-44768 Move Copyright Message under Copyright Status

signup/impl/src/java/org/sakaiproject/signup/dao/SignupMeetingDaoImpl.java
This solves ClassCastException
=> SAK-44771 Hibernate rowCount was changed in recent major upgrade. 

webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44585
=> SAK-44585 Min attribute breaks validation of rubric

samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
CC: @dnhutchins submitNoCheck seems like the logical thing to do here to submit without any checks and to get out of the assessment.
=> SAK-44776 use the submitNoCheck hidden button like auto-save does to submit at end

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
=> SAK-44816 - fix small error in earlier JIRA

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
https://jira.sakaiproject.org/browse/SAK-44571
=> SAK-44571 Check availability of sakai resources in lessons

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
This needs review by @bjones86 as it fixed an NPE introduced on 10-Dec-2020
85a13aebb34 (Brian Jones                 2020-12-10 20:11:03 +0000 4963)
=> SAK-44825 Lessons title dialog can produce an NPE

basiclti/basiclti-tool/src/bundle/ltitool.properties, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/basiclti-tool/src/webapp/vm/lti_import_return.vm, basiclti/docs/IMPORTLOR.md, basiclti/tsugi-util/src/java/org/tsugi/basiclti/ContentItem.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/DeepLinkResponse.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/LtiImportItemProducer.java
This won't work without PR  #8916
=> SAK-44809 - Fix Content Item Import for CC

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java
@adrianfish. Same problem: https://github.com/sakaiproject/sakai/pull/8432/files
=> SAK-44744: SAMIGO - Wrong export when formulas includes more than one comma on a calculated question

edu-services/sections-service/sections-impl/sakai/impl/src/java/org/sakaiproject/component/section/sakai/SectionManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-44841
=> SAK-44841 get users with permission to display gradebook section info properly

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
I switched this to CompareToBuilder. It looks like the anonymous check really isn't needed here anymore doing it this way as the sortName will be blank.
=> SAK-44840 - Assignments / grade report missing student record if same name as another student

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-42371
=> SAK-42371 Saving rubric comment triggers draft save.

library/src/webapp-filtered/editor/ckeditor.launch.js
https://jira.sakaiproject.org/browse/SAK-44815
=> SAK-44815 library fixes ckeditor dark mode bug in Firefox

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SiteTitleAdvisorCMS.java, kernel/api/src/main/java/org/sakaiproject/site/api/Site.java, kernel/api/src/main/java/org/sakaiproject/tool/api/ToolManager.java, kernel/component-manager/src/main/java/org/sakaiproject/component/api/ServerConfigurationService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/BasicConfigurationService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tool/impl/ToolComponent.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/PagePickerProducer.java, podcasts/podcasts-api/src/java/org/sakaiproject/api/app/podcasts/PodcastPermissionsService.java, podcasts/podcasts-api/src/java/org/sakaiproject/api/app/podcasts/PodcastService.java, podcasts/podcasts-impl/src/java/org/sakaiproject/component/app/podcasts/PodcastPermissionsServiceImpl.java, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm, rubrics/api/src/main/bundle/rubrics.properties, rubrics/tool/src/main/webapp/WEB-INF/tools/sakai.rubrics.xml, sections/sections-app/src/java/org/sakaiproject/tool/section/facade/sakai/AuthzSakaiImpl.java, site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java, site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/rsf/PageListProducer.java, site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js, web/web-impl/impl/src/java/org/sakaiproject/web/impl/WebServiceImpl.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
https://jira.sakaiproject.org/browse/SAK-44728
=> SAK-44728 Make locked and visible less confusing.

assignment/api/src/resources/assignment.properties, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
https://jira.sakaiproject.org/browse/SAK-33701
=> SAK-33701 Assignments add submission log

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-44850
=> SAK-44850 Set sortName to displayName when anon grading

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-44613
=> SAK-44613 Only apply min score if partial credit not on

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44585
=> SAK-44585 number type on rubric input breaks html validation

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/SiteManageServiceImpl.java
This was identified by Andrea whilst testing 44810 (Resourcelink.id.history) - but it really was an issue with this JIRA (Content.id.history)
=> SAK-44865 - Bug fix saveSite messes up when import is in thread

basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
Reopening to address issues raised by Andrea
=> SAK-44811 Catch errors inside iframes

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonsAccess.java, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
Also cleaned up this file with Lombok. Stuck with dao variable since it was used in over 10 places places, so not sure the value of updating it to be simplePageToolDao?
=> SAK-44877 - Lessons: getPrerequisiteDataForSubNav NullPointerException

providers/component/src/webapp/WEB-INF/unboundid-ldap.xml, providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java
and better defaults for health checks
CC: @austin48
=> SAK-44925 unboundid use synchronous mode 

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
https://jira.sakaiproject.org/browse/SAK-44910
=> SAK-44910 Trigger render response as soon a group changed

webservices/cxf/pom.xml, webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiReport.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/MockingAbstractWebService.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiReportCSVTest.java
https://jira.sakaiproject.org/browse/SAK-44946
=> SAK-44946 WebService SakaiReport change csv lib to opencsv

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-44833
=> SAK-44833 Discussions Anonymous reply ClassCastException TopicImpl$HibernateProxy

gradebookng/bundle/src/main/bundle/gradebookng.properties
https://jira.sakaiproject.org/browse/SAK-44950
=> SAK-44950 Added missing aria-label in Gradebook's Bulk Edit panel

lessonbuilder/tool/src/webapp/js/show-page.js
https://jira.sakaiproject.org/browse/SAK-44862
=> SAK-44862 Escape unallowed subpage title regex correctly

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
Avoiding anonymous submissions
=> SAK-44931: Error when clicking Download Spreadsheet [XLSX] from Grade Report

kernel/api/pom.xml, kernel/api/src/main/java/org/sakaiproject/tasks/api/UserTaskAdapterBean.java, kernel/api/src/main/java/org/sakaiproject/time/api/InstantToMillisJsonSerializer.java, kernel/api/src/main/java/org/sakaiproject/time/api/MillisToInstantJsonDeserializer.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks.js
https://jira.sakaiproject.org/browse/SAK-44960
=> SAK-44960 Fixed Task saving

kernel/kernel-impl/pom.xml, master/pom.xml, search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/PoiContentDigester.java, search/search-impl/impl/src/java/org/sakaiproject/search/component/adapter/contenthosting/XLContentDigester.java
=> SAK-44998 Update Apache Poi 5.0.0

lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml
https://jira.sakaiproject.org/browse/SAK-45004
=> SAK-45004 Lessons Reorder NPE with missing showPageProducer

library/src/morpheus-master/sass/base/_defaults.scss
https://jira.sakaiproject.org/browse/SAK-44976
See SAK-44976 for before and after screenshots.
=> SAK-44976 Library - added missing dropdown arrow to certain select dropdown menus

msgcntr/messageforums-app/src/webapp/css/msgcntr.css
https://jira.sakaiproject.org/browse/SAK-44997
See SAK-44997 for before and after screenshots.
=> SAK-44997 Discussions - Added space to forum reply

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44889
=> SAK-44889 Make rubrics point override trigger draft save

assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
https://jira.sakaiproject.org/browse/SAK-44959
This also fixes the Save and the Save and Release behaviour in both
classic and ng grader. Save sets the rubric to draft, Save and Release
sets it to released.
=> SAK-44959 Assignment -> Release Grades sets rubrics to released.

lessonbuilder/tool/pom.xml, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/test/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBeanTest.java
https://jira.sakaiproject.org/browse/SAK-44994
=> SAK-44994 Lessons Print/View All protect infinite recursion

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-45015
=> SAK-45015 Default criteria pointoverride to empty

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, assignment/tool/src/webapp/WEB-INF/applicationContext.xml, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ToolItemRubricAssociation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/EvaluationRepository.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/ToolItemRubricAssociationRepository.java, rubrics/impl/pom.xml, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/ItemService.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-44879
=> SAK-44879 Allow marking rubric associations active

webcomponents/tool/pom.xml, webcomponents/tool/src/main/frontend/.eslintrc.js, webcomponents/tool/src/main/frontend/.gitignore, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json
https://jira.sakaiproject.org/browse/SAK-45020
=> SAK-45020 Added eslint to the webcomponents build

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-45023
This can arise if you remove a submission user from your LDAP, for instance.
=> SAK-45023 Don't return submitterless submissions in new grader

webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-panel.js
https://jira.sakaiproject.org/browse/SAK-45019
=> SAK-45019 Moved widget panel to use auto-fill grid layout

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
Slight refactor to use logic that exists earlier in this class.
=> SAK-45013 Forums: Duplicating stopics stacktrace

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePageNav.vm
https://jira.sakaiproject.org/browse/SAK-45035
=> SAK-45035 Make sure web content and lti launch in tab.

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradingEvent.java
https://jira.sakaiproject.org/browse/SAK-45021
=> SAK-45021 EduServices Hibernate pojo requires a noargs constructor

webcomponents/tool/src/main/frontend/.eslintrc.js
https://jira.sakaiproject.org/browse/SAK-45034
=> SAK-45034 Webcomponents do not compile on windows

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webcomponents/tool/src/main/frontend/js/coursedashboard/sakai-course-dashboard.js
https://jira.sakaiproject.org/browse/SAK-45042
=> SAK-45042 Don't escape site description for dashboard

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
Calculations with constants with [] should work on the preview.
http://mathparser.org/mxparser-tutorial/built-in-constants/
=> SAK-44989: SAMIGO - Calculted Questions: Problems with constants

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/TimedAssessmentRunnable.java
=> SAK-45010 no need to check on timedAG when syncing time

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/PermissionLevelManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-44992
=> SAK-44992 Discussions NPE while saving forum settings

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp, samigo/samigo-app/src/webapp/jsf/author/createAssessment_title.jsp, samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
https://jira.sakaiproject.org/browse/SAK-43136
* Changed background colours of the panels on the Add Assessments page
* Fixed headings, labels, and spacing on the Add Assessments page
* Fixed heading on the Trash page
* Fixed some CSS in tool_sam.css
See SAK-43136 for before and after screenshots.
=> SAK-43136 Replaced primary color with standard bg color for Samigo Create page plus additional visual and layout tweaks

msgcntr/messageforums-app/src/webapp/jsp/dfCompose.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/topic/dfTopicSettings.jsp
https://jira.sakaiproject.org/browse/SAK-44986
=> SAK-44986 Topic: toggle arrow for view/hide full description reversed

site-manage/datemanager/tool/src/main/resources/Messages.properties, site-manage/datemanager/tool/src/main/resources/Messages_ar.properties, site-manage/datemanager/tool/src/main/resources/Messages_de_DE.properties, site-manage/datemanager/tool/src/main/resources/Messages_fr_FR.properties, site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-44860
=> SAK-44860 Incorrect word usage in Date Manager confirmation message.

gradebookng/tool/src/webapp/scripts/gradebook-saverubric.js, msgcntr/messageforums-app/src/webapp/js/forum.js, samigo/samigo-app/src/webapp/js/samigo-global.js
https://jira.sakaiproject.org/browse/SAK-45086
=> SAK-45086 Save grade in gb/t&q/discussions now releases the rubric

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, webcomponents/tool/src/main/frontend/.eslintrc.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-45113
=> SAK-45113 Fixed unlimited resub issue with new grader

site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
=> SAK-44134 resolve issue with locked calendar event caused by bad DateManager edit

library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics_variables.scss
https://jira.sakaiproject.org/browse/SAK-45022
=> SAK-45022 Make hover on rubrics grading lighter

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webcomponents/tool/src/main/frontend/js/widgets/sakai-widget-panel.js, webcomponents/tool/src/main/frontend/stories/data/course-dashboard-data.js, webcomponents/tool/src/main/frontend/stories/styles/sakai-styles.js
https://jira.sakaiproject.org/browse/SAK-45087
=> SAK-45087 The tasks widget should only be in the home dashboard

assignment/api/src/java/org/sakaiproject/assignment/api/persistence/AssignmentRepository.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/RangeAndGroupsDelegate.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
https://jira.sakaiproject.org/browse/SAK-41263
=> SAK-41263 Assignments improved group locking updates

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-45124
This returns the control flow for this method back to how it was before SAK-44305, at the expense of some code duplication I was originally trying to avoid.
The bug with the SAK-44305 flow exists because there is a method in the middle (getForwardingEnabled) that returns a boolean but also populates the recipient list as a side effect. This fix causes the method to return before getForwardingEnabled is called if the message is a draft, like it used to.
=> SAK-45124 Message saved as draft gets sent

gradebookng/bundle/src/main/bundle/gradebookng.properties
https://jira.sakaiproject.org/browse/SAK-45100
=> SAK-45100 resolve AutoLabel.CSS stacktrace

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
@csev I'm not sure the best way to test this ... tips?
=> SAK-45138 send given_name and family_name on LTI 1.3 POST

webcomponents/tool/src/main/frontend/.eslintrc.js
https://jira.sakaiproject.org/browse/SAK-45141
=> SAK-45141 Added some more rules to webcomponents eslint

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rating.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria-readonly.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-rating-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://jira.sakaiproject.org/browse/SAK-45137
Also, prevent nulls in the title and points columns of rbc_rating and do
some eslint cleanup.
=> SAK-45137 Make sure rating points is always a Number

mailarchive/mailarchive-subetha/src/bundle/sakaimailet.properties, mailarchive/mailarchive-subetha/src/bundle/sakaimailet_es.properties, mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
Broken links on messages tool received from a mail client.
=> SAK-44902: Broken links on messages tool received from a mail client.

library/src/morpheus-master/sass/modules/navigation/_base.scss, library/src/morpheus-master/sass/themes/_dark.scss
https://jira.sakaiproject.org/browse/SAK-45142
=> SAK-45142 Library link color contrast

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
I don't have a test plan or way to reproduce this, just seems like this is how it should be working?
=> SAK-44199 - Sitestats: StatsUpdateManagerImpl.doUpdateSitePresencesObjects Exception

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
Error in sending mails without subject
=> SAK-45017: Error in sending mails without subject

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, library/src/morpheus-master/sass/modules/grader/_base.scss, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-gradable-data-mixin.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-44684
=> SAK-44684 Allow draft submissions to be viewed in grader

library/src/morpheus-master/sass/modules/tool/mbm/_mbm.scss, library/src/morpheus-master/sass/modules/tool/oauthadmin/_oauthadmin.scss
https://jira.sakaiproject.org/browse/SAK-45012
Fixing two darkmode bugs (screenshots in the above Jira).
=> SAK-45012 Dark mode Bugfixes for OAuth and MBM

library/src/morpheus-master/sass/base/_bootstrap-defaults.scss
https://jira.sakaiproject.org/browse/SAK-45152?filter=-1
=> SAK-45152 Library fix bootstrap small text color for dark mode

library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-45151?filter=-1
=> SAK-45151 Library adjust sakai-banner icon color to increase contrast

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Evaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rubric.java
https://jira.sakaiproject.org/browse/SAK-45174
=> SAK-45174 Rubrics JPA 2.2 data model updates

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Evaluation.java
https://jira.sakaiproject.org/browse/SAK-45194
=> SAK-45194 Make rbc_evaluation.status nullable, but with RELEASED default

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeDeliveryService.java
Ensure extended time service is set to the correct published assessment before
checking exam delivery dates
=> SAK-34249 Extended time dates pulled from wrong published assessment

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-45200
=> SAK-45200 New grader cancel button should reset inputs.

kernel/kernel-util/src/main/java/org/sakaiproject/util/MapResourceBundle.java
https://jira.sakaiproject.org/browse/SAK-45201
=> SAK-45201 Check for null parent in MapResourceBundle

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
https://jira.sakaiproject.org/browse/SAK-45215
=> SAK-45215 Incorrect url used for evaluation in student button

library/src/webapp/editor/ckextraplugins/templates/default.js
https://jira.sakaiproject.org/browse/SAK-44835?filter=-1
=> SAK-44835 library fix typo in ckeditor template

jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/PagerRenderer.java
Discussed this on the core call to remove the show all.
=> SAK-45132 - Remove option for view all

portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/AddAssignmentBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendConfirmBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendIgnoreBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendMessageBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendRequestBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/FriendStatusBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/GradeAssignmentBullhornHandler.java, portal/portal-api/api/src/java/org/sakaiproject/portal/beans/bullhornhandlers/RemoveAssignmentBullhornHandler.java
https://jira.sakaiproject.org/browse/SAK-45237
=> SAK-45237 Check for existing bullhorn alert when grading all

library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm
https://jira.sakaiproject.org/browse/SAK-44838?filter=-1
=> SAK-44838 site-manage update remove lessons tool to use font-awesome

library/src/morpheus-master/sass/modules/tool/_menu.scss
https://jira.sakaiproject.org/browse/SAK-45147?filter=-1
=> SAK-45147 library remove tool tab bleed on multiline tabbed screens

library/src/morpheus-master/sass/themes/_dark.scss, library/src/morpheus-master/sass/themes/_light.scss, library/src/webapp/skin/tool_base.css
https://jira.sakaiproject.org/browse/SAK-45149?filter=-1
=> SAK-45149 library hightlight color contrast issues in dark mode

jsf/jsf-widgets/pom.xml, jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ViewRenderer.java, velocity/tool/src/java/org/sakaiproject/cheftool/VelocityPortletPaneledAction.java, velocity/tool/src/templates/VM_chef_library.vm
https://jira.sakaiproject.org/browse/SAK-45256
=> SAK-45256 Add userTheme to tool markup <html tags

jsf/jsf-widgets/pom.xml, jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ViewRenderer.java, jsf2/jsf2-widgets/pom.xml, jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/renderer/ViewRenderer.java, velocity/tool/src/java/org/sakaiproject/cheftool/VelocityPortletPaneledAction.java, velocity/tool/src/templates/VM_chef_library.vm
https://jira.sakaiproject.org/browse/SAK-45256
=> SAK-45256 fix this for the jsf2 folder too

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-43368
=> SAK-43368 Ensure that setting evaluatedItemId triggers render

library/src/morpheus-master/sass/base/_bootstrap-defaults.scss
https://jira.sakaiproject.org/browse/SAK-45169?filter=-1
=> SAK-45169 Library update Bootstrap wells for dark theme

library/src/morpheus-master/sass/base/_extendables.scss
https://jira.sakaiproject.org/browse/SAK-45204?filter=-1
Used the same fix from https://github.com/sakaiproject/sakai/pull/5916
=> SAK-45204 Library change user language background image

kernel/README.md, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/README.md, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
Also Kernel documentation has been added
=> SAK-45298 Ignite add data regions to configuration

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties
Invalid characters:
https://github.com/sakaiproject/sakai/blame/master/samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java#L3608
=> SAK-45280: SAMIGO: Character & is forbidden as separator on FIB questions

jsf/jsf-widgets/src/java/org/sakaiproject/jsf/renderer/ViewRenderer.java, jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/renderer/ViewRenderer.java, library/src/morpheus-master/sass/modules/tool/calendar/_calendarSynoptic.scss, library/src/morpheus-master/sass/modules/tool/calendar/_calendar_variables.scss, library/src/webapp/content/myworkspace_info.html, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/webapp/jsp/synoptic/synMainLite.jsp
https://jira.sakaiproject.org/browse/SAK-45196
=> SAK-45196 Made adjustments to Overview synoptic tools to render properly in dark mode

library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/AddFriend.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/ConfirmFriend.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/IgnoreFriend.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/QuickMessageTo.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/RemoveFriend.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/windows/RemoveWallItem.html
I have deleted the modalWindowButtons class from the htmls because it was not in any file.
Also I fixed some indentation issues.
=> SAK-45263  Add/Confirm Connection pop-up needs resized

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/GradeReportTest.java
https://jira.sakaiproject.org/browse/SAK-44717
=> SAK-44717 Added date and late fields to the grade report

msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgEx.jsp
…d search options have been selected
=> SAK-44848 - Messages: Compose page doesn't load after certain advanced search options have been selected

samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
I forgot adding & here as forbidden character
=> SAK-45281: SAMIGO: Field Markers should be replace on the Mutually exclusive example

samigo/samigo-app/src/webapp/js/samigo-global.js
A preview of the result (sorting by points)
---
=> SAK-44178 T&Q: Questions in question pools not sortable

site-manage/site-manage-impl/impl/src/bundle/UserAuditService.properties, userauditservice/tool/src/java/org/sakaiproject/userauditservice/tool/UserAuditEventLog.java, userauditservice/tool/src/webapp/eventLog.jsp, userauditservice/util/src/java/org/sakaiproject/userauditservice/util/UserAuditRegistrationUtil.java
=> SAK-44497 audit log should use database-stored username instead of looking up user info

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/assesment/service/GradingServiceTest.java
https://jira.sakaiproject.org/browse/SAK-45351
=> SAK-45351: SAMIGO: Characters <> should be forbidden as separator on FIB questions

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
Avoid multiple tooltips
https://jira.sakaiproject.org/browse/SAK-45378
=> SAK-45378: SAMIGO - Problems with tooltips on Numeric Response questions

kernel/kernel-impl/src/main/java/org/sakaiproject/entity/impl/EntityManagerComponent.java, kernel/kernel-impl/src/test/java/org/sakaiproject/entity/impl/test/EntityManagerComponentTest.java
This should be combined with CLOG-211 to solve notification clog problems.
=> SAK-45091: Some tools don't respect user notification preferences

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ProcessedGradeItem.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/RubricsService.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-45421
=> SAK-45421 Make rubrics work with csv gb item import

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties
https://jira.sakaiproject.org/browse/SAK-34395
MG told me how to do this so if it's wrong... Just capitalizing one word
=> SAK-34395 Change capitalization

rubrics/tool/src/main/frontend/webcomponents/rubrics-element.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria-readonly.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criteria.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-preview.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-criterion-student.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubric-modified-date.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-language.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-list.js, rubrics/tool/src/main/frontend/webcomponents/sakai-rubrics-shared-list.js
https://jira.sakaiproject.org/browse/SAK-45436
=> SAK-45436 Added locale logic to rubrics element

library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.css, library/src/webapp/editor/ckextraplugins/audiorecorder/audiorecorder.html, library/src/webapp/js/sakai-recorder.js, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/delivery/item/audioObject.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
=> SAK-33621 part II making audio recorder work when multiple questions on one page

samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
https://jira.sakaiproject.org/browse/SAK-45427
Change the selector to an ID instead of a properties' value.
=> SAK-45427: SAMIGO: Honor pledge doesn't work when using web browser's translation

user/user-tool-admin-prefs/admin-prefs/pom.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/META-INF/context.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/WEB-INF/beans.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/WEB-INF/faces-config.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/WEB-INF/web.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/prefs/edit.jsp, user/user-tool-admin-prefs/admin-prefs/src/webapp/prefs/list.jsp
Related, this tool is dumb and should probably be removed!  You have to manually add it via the sites tool.  Not really sure why anyone would want to use it.  But, hey, it's now up-to-date as far as jsf is concerned!
=> SAK-45439 - jsf upgrade for user admin prefs

rubrics/api/src/main/bundle/rubrics.properties, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
https://jira.sakaiproject.org/browse/SAK-44879
=> SAK-44879 Prevent switching rubric if evaluations exist

master/pom.xml
[INFO]   junit:junit ......................................... 4.13.1 -> 4.13.2
[INFO]   org.mockito:mockito-core .............................. 3.4.4 -> 3.9.0
[INFO]   org.powermock:powermock-api-mockito2 .................. 2.0.7 -> 2.0.9
[INFO]   org.powermock:powermock-module-junit4 ................. 2.0.7 -> 2.0.9
=> SAK-45454 Update test master

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, kernel/api/src/main/java/org/sakaiproject/content/api/ContentResource.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
https://jira.sakaiproject.org/browse/SAK-44183
(cherry picked from commit d1f604f7a1b30b5bd30adacca92156ac9600a3c2)
=> SAK-44183 Let grader preview images (#8521)

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CourseGrade.java, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradeRecord.hbm.xml, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/CourseGrade.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/CourseGradeRecord.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/TestGradebookNgBusinessService.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/tool/panels/TestCourseGradeOverridePanel.java
Gradebook: Problem when overrides grades
=> SAK-43022: Gradebook: Problem when overrides grades

samigo/samigo-app/src/webapp/jsf/author/item/extendedMatchingItems.jsp
The fix for SAK-41964 broke adding or editing EMI questions. This fixes it.
=> SAK-41964 Fix regression from incorrect syntax in EMI question type

portal/portal-charon/charon/src/webapp/styles/portalstyles.css
https://jira.sakaiproject.org/browse/SAK-45266
=> SAK-45266 fixing hardcoded CSS in portal for Dark Mode

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/README.md
https://jira.sakaiproject.org/browse/SAK-45389
=> SAK-45389 Added markdown docs for the file conversion service

library/src/morpheus-master/sass/modules/tool/syllabus/_syllabus.scss, syllabus/syllabus-app/src/webapp/syllabus/delete_confirm.jsp
https://jira.sakaiproject.org/browse/SAK-45301?filter=-1
=> SAK-45301 Syllabus edit-delete confirm screen updates

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, library/src/morpheus-master/bootstrap-sass-3.3.7/assets/stylesheets/bootstrap/_forms.scss, library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, samigo/samigo-app/src/webapp/jsf/qti/chooseExportType.jsp
https://jira.sakaiproject.org/browse/SAK-45308?filter=-1
=> SAK-45308 Library update help-block and remove use of text-warning

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, citations/citations-servlet/servlet/src/webapp/vm/compact.vm, emailtemplateservice/tool/src/webapp/templates/preview_email.html, library/src/webapp/skin/tool_base.css
https://jira.sakaiproject.org/browse/SAK-45312
=> SAK-45312 Update highlightpanel for darkmode

library/src/morpheus-master/sass/modules/tool/dropbox/_dropbox.scss, library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
https://jira.sakaiproject.org/browse/SAK-43972?filter=-1
=> SAK-43972 Resources/Dropbox make actions button padding consistent

library/src/webapp/skin/tool_base.css
https://jira.sakaiproject.org/browse/SAK-43984?filter=-1
=> SAK-43984 syllabus form alignment

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorFrontDoorMessages.properties
https://jira.sakaiproject.org/browse/SAK-43988?filter=-1
=> SAK-43988 Samigo add space for alignment

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
https://jira.sakaiproject.org/browse/SAK-45461?filter=-1
=> SAK-45461 Samigo update submission download all button markup

library/src/morpheus-master/sass/modules/multiselect/_base.scss
https://jira.sakaiproject.org/browse/SAK-45497?filter=-1
=> SAK-45497 Messages select2 styling for dark mode

library/src/morpheus-master/sass/modules/tool/_table.scss
https://jira.sakaiproject.org/browse/SAK-45458?filter=-1
=> SAK-45458 Samigo assessment list

library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss, library/src/morpheus-master/sass/themes/_dark.scss, library/src/morpheus-master/sass/themes/_light.scss
https://jira.sakaiproject.org/browse/SAK-45311?filter=-1
=> SAK-45311 Assignments progress bar contrast

library/src/morpheus-master/sass/themes/_dark.scss, library/src/morpheus-master/sass/themes/_light.scss, webcomponents/tool/src/main/frontend/js/calendar/sakai-calendar.js, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/stories/data/calendar-data.js, webcomponents/tool/src/main/frontend/stories/styles/sakai-styles.js
https://jira.sakaiproject.org/browse/SAK-45499
=> SAK-45499 Updated to latest lion/calendar

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
https://jira.sakaiproject.org/browse/SAK-45558
=> SAK-45558 Kernel invalid discovery address when range = 1

webapi/src/main/java/org/sakaiproject/webapi/controllers/ForumsController.java
https://jira.sakaiproject.org/browse/SAK-45291
=> SAK-45291 Set siteUrl on forums webapi json

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
(cherry picked from commit 935465d8d2a4560fb96ce75e39ef40c74158a9ca)
Please preserve commit authorship
=> SAK-45075 lessons - fix subpage renaming

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, rubrics/api/pom.xml, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/AuthenticatedRequestContext.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/EvaluatedItemOwnerType.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Evaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/EvaluationRepository.java, rubrics/api/src/test/java/org/sakaiproject/rubrics/api/test/EvaluationRepositoryTests.java, rubrics/api/src/test/java/org/sakaiproject/rubrics/api/test/RubricsTestConfiguration.java, rubrics/api/src/test/java/org/sakaiproject/rubrics/api/test/SpelContext.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java, rubrics/tool/src/main/java/org/sakaiproject/rubrics/security/JwtTokenUtil.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js
https://jira.sakaiproject.org/browse/SAK-41604
=> SAK-41604 Add group support to rubrics

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/RankManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-45208
=> SAK-45208 Forums: fix remove ranks

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, kernel/api/src/main/java/org/sakaiproject/content/api/persistence/FileConversionQueueItem.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/FileConversionServiceImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml
https://jira.sakaiproject.org/browse/SAK-45575
=> SAK-45575 Only convert attachments from assignment submissions

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-45305
=> SAK-45305 Check for inactive members in new grader

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
https://jira.sakaiproject.org/browse/SAK-45481
=> SAK-45481 Preserve rubric associations while attaching files

assignment/api/src/resources/assignment.properties, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-45346
I've added the required text for the feedback button in assignment.properties.
=> SAK-45346 Incorrect text on button to add feedback in an assignment.

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
https://jira.sakaiproject.org/browse/SAK-43829
=> SAK-43829 - Forums: Create new forum without a title causes confusing error message

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-44921
=> SAK-44921 Assignments: hide due date from student view when due

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-45561
=> SAK-45561: Assignment: Description for event added to Calendar missing time zone for due date

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-reorder.vm
https://jira.sakaiproject.org/browse/SAK-44804
=> SAK-44804 Announcements: reorder missing fields

content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
https://jira.sakaiproject.org/browse/SAK-45554
=> SAK-45554 Check links when clicking remove

jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java
https://jira.sakaiproject.org/browse/SAK-45133
=> SAK-45133 Show more jobs on filter events list

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
https://jira.sakaiproject.org/browse/SAK-45254
=> SAK-45254 Change display order of the reset selection and rationale

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
https://jira.sakaiproject.org/browse/SAK-44583
I'm not particularly keen on using the hardcoded string, but it's used elsewhere and a refactor (as desirable as it is) would take longer...
=> SAK-44583 Limit lockdown on load when due

assignment/api/src/resources/assignment.properties, assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/GradeReportTest.java
This PR makes the Grade Report in Excel consistent with the UI, also supports the new feature introducied in SAK-44717
=> SAK-45391 - Assignment Grade Report: Make the report consistent with UI

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/api/src/main/java/org/sakaiproject/content/api/FileConversionService.java, kernel/api/src/main/java/org/sakaiproject/content/api/persistence/FileConversionQueueItem.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/FileConversionServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/README.md, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/FileConversionServiceTestConfiguration.java
https://jira.sakaiproject.org/browse/SAK-45580
=> SAK-45580 Allow file conversion to be disabled with submission enabled

library/src/morpheus-master/sass/base/_extendables.scss, library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss, library/src/morpheus-master/sass/modules/tool/sitesetup/_sitesetup.scss, library/src/webapp/skin/tool_base.css, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm, velocity/tool/src/templates/VM_chef_library.vm
https://jira.sakaiproject.org/browse/SAK-45567
See SAK-45567 for before and after screenshots.
=> SAK-45567 Update Site Creation banner message to standard success banner

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
https://jira.sakaiproject.org/browse/SAK-45288
=> SAK-45288 Changed forums widget name to Discussions

samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf, samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf
[https://jira.sakaiproject.org/browse/SAK-45511](https://jira.sakaiproject.org/browse/SAK-45511)
=> SAK-45511 Add time limit labeling in Test & Quizzes' Exceptions settings

kernel/api/src/main/java/org/sakaiproject/content/api/persistence/FileConversionQueueItem.java, kernel/api/src/main/java/org/sakaiproject/springframework/data/PersistableEntity.java, kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepository.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/UserTask.java, kernel/kernel-private/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepositoryImpl.java
https://jira.sakaiproject.org/browse/SAK-45584
=> SAK-45584 SpringCrudRepositoryImpl persists if entity is new

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
https://jira.sakaiproject.org/browse/SAK-45586
Fix NPE in GradesController.
=> SAK-45586 Handle no MOTD being set in home dashboard

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/controller/executors/SakaiTmbCommandExecutor.java
https://jira.sakaiproject.org/browse/SAK-45594
=> SAK-45594 ELFinder NPE in ICC_Profile

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
https://jira.sakaiproject.org/browse/SAK-45531
Course grade override should show either exact percentage override or calculated percentage
=> SAK-45531: Course grade override should show either exact percentage override or calculated percentage

kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java, lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/simplepagegroup.hbm.xml
Tests are currently broken, this will not be as easy as it looks like.
=> SAK-45565 - Rename MySQL8 reserved words

library/src/morpheus-master/sass/base/_extendables.scss, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
https://jira.sakaiproject.org/browse/SAK-43640
=> SAK-43640 T&Q: Style retract message

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookInformation.java, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Gradebook.hbm.xml, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Gradebook.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BasePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentCompareGradesPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentCompareGradesPanel.java, gradebookng/tool/src/webapp/styles/gradebook-grades-comparison.css
Hi, I've uploaded some previews of this feature in the JIRA
=> SAK-44967 Allow students to see the grades of their classmates

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ListItem.java
=> SAK-45569 Set sakai.content.resourceLimit default to 5000

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-40330
=> SAK-40330 Assignment Allow TA with grade to update submission

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/DiscussionForumManager.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/UIPermissionsManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-44985
=> SAK-44985 Discussions topic and forum cache invalidation

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/README.md
https://jira.sakaiproject.org/browse/SAK-45630
Added more documentation
=> SAK-45630 Ignite configure MessageQueueLimit, Collision, and Checkpoint

lessonbuilder/tool/src/webapp/js/show-page.js
https://jira.sakaiproject.org/browse/SAK-44955
=> SAK-44955 Lessons: edit page invalid chars

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
https://jira.sakaiproject.org/browse/SAK-45352
=> SAK-45352: SAMIGO > Fill in the Blank > Warning for Forbidden Characters

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
(cherry picked from commit 574b2a1e08f46b5082495b2523e4b931297f7e53)
=> SAK-45628 site info > don't remove stealthed lti tools when manage tools list is edited

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
(cherry picked from commit cc335364bc092238a5a757313383da4df173e7a4)
=> SAK-45628 NPE protection

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
https://jira.sakaiproject.org/browse/SAK-45651
=> SAK-45651 Samigo Question answer not being updated after changing

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java
https://jira.sakaiproject.org/browse/SAK-45651
=> SAK-45651 Samigo Revert Equals and Hashcode changes from ItemGradingData

lessonbuilder/hbm/src/java/org/sakaiproject/lessonbuildertool/simplepageitem.hbm.xml
This is paired with https://github.com/sakaiproject/sakai-reference/pull/123
=> SAK-45565 - Lessons: GROUP is a MySQL8 reserved word

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties
https://jira.sakaiproject.org/browse/SAK-45647
=> SAK-45647 the DateFormatter needs to be timezone adjusted

webcomponents/tool/src/main/frontend/package.json
https://jira.sakaiproject.org/browse/SAK-45607
=> SAK-45607 Added static file mount for storybook-resources

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-45666
=> SAK-45666 Samigo Statistics NumberFormatException parsing assessment id

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/WEB-INF/applicationContext.xml, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/DbCalendarServiceSerializationTest.java, kernel/api/src/main/java/org/sakaiproject/time/api/UserTimeService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/serialize/impl/conversion/ConversionTimeService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/BasicTimeService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/UserTimeServiceImpl.java, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/serialize/impl/test/MockTimeService.java, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://jira.sakaiproject.org/browse/SAK-45669
=> SAK-45669 Format grader dates using user preferences

kernel/api/src/main/java/org/sakaiproject/messaging/api/BullhornAlert.java, kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/MessagingServiceImpl.java, library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/controllers/EventsController.java
https://jira.sakaiproject.org/browse/SAK-44681
=> SAK-44681 Bullhorn dates now honour user preferences

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-45686
=> SAK-45686 Fixed NPE causing missing submission in new grader

library/src/morpheus-master/compile-skin.md
https://jira.sakaiproject.org/browse/SAK-45682?filter=-1 
Discussed on 20210622 core call not to fix this behavior but document it better for 20.x. It is refactored in 21+
=> SAK-45682 Library documentation update

library/src/morpheus-master/sass/modules/tool/chat/_chat.scss, library/src/morpheus-master/sass/modules/tool/chat/_chat_variables.scss
https://jira.sakaiproject.org/browse/SAK-45187
=> SAK-45187 Adjusted the colours of the portal chat and portal presence so they appear in the skins

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
=> SAK-45393 - Matching with none of the above loses student answer on regrade and republish

entitybroker/impl/pom.xml, entitybroker/impl/src/java/org/sakaiproject/entitybroker/impl/external/SakaiExternalIntegrationProvider.java
https://jira.sakaiproject.org/browse/SAK-45736
=> SAK-45736 EntityBroker from unbalanced quote results in unsent email

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://jira.sakaiproject.org/browse/SAK-45507
=> SAK-45507 Assignment improve the use of the submission status

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
=> SAK-34477: Get curly brackets as text in a Fill in the Blank

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemoveAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemovePublishedAssessmentListener.java
https://jira.sakaiproject.org/browse/SAK-45770
Minor. Merge asap. Thanks!
=> SAK-45770: SAMIGO: Change publisedAssessmentId to publishedAssessmentId

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/util/LessonsSubNavBuilder.java
https://jira.sakaiproject.org/browse/SAK-45758
=> SAK-45758 Column was renamed and there was an unchaged reference

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Equal weight categories allow any points
=> SAK-43994 fix assignment gb category logic with equal-weight categories

chat/chat-impl/impl/src/java/org/sakaiproject/chat2/model/impl/ChatManagerImpl.java, common/common-composite-component/src/java/org/sakaiproject/component/common/type/TypeManagerImpl.java, common/privacy-comp-impl/src/java/org/sakaiproject/component/privacy/PrivacyManagerImpl.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookExternalAssessmentServiceImpl.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
=> SAK-45811 Deprecated Query setString, setBoolean => setParameter

samigo/samigo-app/src/webapp/js/saveForm.js
This ONLY avoid force submitting
=> SAK-45522: samigo: Remove SAK-34725 behavior of forcibly submitting untimed assessments when auto-submit is NOT enabled

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java, samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
https://jira.sakaiproject.org/browse/SAK-45534.
You cannot parse html-level languages ​​with infinite nests with regular expressions.
Review @davidpbauer
=> SAK-45534: SAMIGO: Solving problems of calculation pattern

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
Secure resources don't work for Calculated Question and Matrix of choices
=> SAK-45537: secure content wrapper missing for two question types

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
1.deprecated: Query.setBoolean( => setParameter
2. HashSet h = new HashSet(); =>  Set h = new HashSet<>();
=> SAK-45851 Hibernate5 deprecated: Query.setBoolean( => setParameter

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/EditablePanelList.java
Fixed the checkbox saving, based this solution on https://github.com/sakaiproject/sakai/commit/b8837398a32b4cf3de3b66b7760f61fe93d36d7e
I'd say that tool's a bit faulty though and there might some be more issues on that logic.
=> SAK-39987 DA - tool restrictions checkboxes not being saved

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss, webcomponents/bundle/src/main/bundle/grader-toggle.properties
https://jira.sakaiproject.org/browse/SAK-45122
=> SAK-45122 Moved grader toggle to top right

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Resolved Jira [https://jira.sakaiproject.org/browse/SAK-45883](url)
=> SAK-45883: Recurring error "ERROR: org.sakaiproject.velocity.util.SLF4JLogChute.log"

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
https://jira.sakaiproject.org/browse/SAK-45737
=> SAK-45737: SAMIGO: Improving performance on calculated questions

assignment/api/src/resources/assignment.properties, assignment/api/src/resources/assignment_es.properties, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
Referenced [https://jira.sakaiproject.org/browse/SAK-45693](url)
=> SAK-45693: Bulk grading of unsubmitted and ungraded assignments

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/WEB-INF/faces-config.xml, msgcntr/messageforums-app/src/webapp/jsp/dfMsgRevise.jsp
https://jira.sakaiproject.org/browse/SAK-45832
=> SAK-45832 Discussions improved stale object handling

samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/ItemContentProducer.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/PublishedItemContentProducer.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/QuestionElasticSearchIndexBuilder.java, samigo/samigo-pack/src/webapp/WEB-INF/components.xml
HashSet h = new HashSet(); => Set<?> h = new HashSet<>();
The method  private from the type is never used local
=> SAK-45865 Remove use of Static Cover in *ContentProducer

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewList.vm
Also performed some CalendarAction cleanup.
=> SAK-45769 - Calendar: List of Events is missing the date for each event

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/EagerIgniteSpringBean.java, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://jira.sakaiproject.org/browse/SAK-45914
=> SAK-45914 Ignite Data Region Memory tuning for hibernate_l2_region

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java, assignment/api/src/resources/assignment.properties, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/js/videoRecorder.js, assignment/tool/src/webapp/vm/assignment/assignments_display_video_submission.vm, assignment/tool/src/webapp/vm/assignment/assignments_record_video_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm, library/pom.xml, library/src/webapp/js/headscripts.js, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.java, webcomponents/tool/src/main/frontend/js/sakai-document-viewer.js
This feature is present in our roadmap, the implemetation is more a proof of concept than a final version because it can be improved a lot.
I'd like this being merged as is before the code freeze, in order to begin testing in nightlies, and provide refinements or improvements in separate work packages.
Thanks
=> SAK-45751 - Assignments: Support video submissions

profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileLogicImpl.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/entityprovider/ProfileEntityProvider.java, profile2/util/src/java/org/sakaiproject/profile2/util/messages.properties
Hi, this is a small change, here are some previews:
---
---
=> SAK-45887 Add name pronunciation to Forum/Messages profile blurb

profile2/tool/src/webapp/css/profile2-profile-entity.css
Hi, just a small UI fix, similar to SAK-45889
---
---
=> SAK-45886 Discussions: Viewing user profile has profile icon repeating in background

profile2/tool/src/webapp/css/profile2-profile-entity.css
Hi, just a small UI fix, here are some previews of the result
---
---
=> SAK-45889 Forums: View profile has vertical text

roster2/tool/src/java/org/sakaiproject/roster/api/SakaiProxy.java, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java, roster2/tool/src/java/org/sakaiproject/roster/tool/entityprovider/RosterSiteEntityProvider.java, roster2/tool/src/webapp/js/roster.js
https://jira.sakaiproject.org/browse/SAK-45755
=> SAK-45755 Roster issue finding by name with group or role filter

library/src/webapp/js/sakai-message-broker.js
https://jira.sakaiproject.org/browse/SAK-44265
=> SAK-44265 Only connect EventSource if user is logged in

admin-su/src/webapp/WEB-INF/web.xml, calendar/calendar-summary-tool/tool/src/webapp/WEB-INF/web.xml, help/help-tool/src/webapp/WEB-INF/web.xml, jobscheduler/scheduler-tool/src/webapp/WEB-INF/web.xml, signup/tool/src/webapp/WEB-INF/web.xml, syllabus/syllabus-app/src/webapp/WEB-INF/web.xml, user/user-tool-admin-prefs/admin-prefs/src/webapp/WEB-INF/web.xml, user/user-tool-prefs/tool/src/webapp/WEB-INF/web.xml, usermembership/tool/src/webapp/WEB-INF/web.xml
=> SAK-45902 JSF2 disable verifyObjects param for production environment

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/PDFExportService.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/PDFExportServiceTest.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_view.vm
This should be rebased after #9446
=> SAK-45768 Calendar print params should be done in the client side

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/webapp/styles/gradebook-shared.css
Hi, small UI change (points value)
Before: 
---
After
---
=> SAK-45862 Mobile / gradebook / point value box

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/js/video-recorder.js, assignment/tool/src/webapp/vm/assignment/assignments_record_video_submission.vm
This doesn't resolve the problem but doesn't hardcode the mimetype in the backend.
=> SAK-45933 - Assignments Video Recorder: Set the mimetype in the client.

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
…ow external tools to be listed in main list of tools
=> SAK-45947 new property site-manage.useExternalToolsGroup to allow external tools to be listed in main list of tools

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
https://jira.sakaiproject.org/browse/SAK-45961
low-risk
=> SAK-45961 Removing whitespace before Forum settings button

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-45269
2 problems here: url encoding and reference prefix.
=> SAK-45269 Grader: remove attachments with special characters in name

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
https://jira.sakaiproject.org/browse/SAK-45858
Added headers to Statistics and Grading view in Discussions tool
=> SAK-45858: Discussions (Forums) > Statistics and Grading > Table Missing Column Headers

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
https://jira.sakaiproject.org/browse/SAK-45855
Add column header and text property for header of statistics of a students forum post.
=> SAK-45855: Discussions > Statistics > Student View > Messages Authored table lacks a column heading

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
https://jira.sakaiproject.org/browse/SAK-45960
low-risk
=> SAK-45960 Delete Topic button is missing when 'Display Subject Only'

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
https://jira.sakaiproject.org/browse/SAK-45854
Make to discussion posts in statistics render for the author (student)
=> SAK-45854: Discussions > Statistics > Student View > Clicking any link in the "Subject" column returns an empty page

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyDisplayInThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyFullTextForOne.jsp
https://jira.sakaiproject.org/browse/SAK-45856
DEPENDING ON SAK-45854 (Pull #9549)
Enable printing pages for students
=> SAK-45856: Discussions > Statistics > Student View > Print Buttons do not work

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConditionalCache.java, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://jira.sakaiproject.org/browse/SAK-45974
=> SAK-45974 Kernel Ignite add conditional caches

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
Add space before and colum after "Rationale"
=> SAK-45697: Samigo > Require Rationale > Questions tab > Instructor Display Formatting Changes Needed

samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
https://jira.sakaiproject.org/browse/SAK-45835
=> SAK-45835 Samigo: Hide "Scores" option when no submission

kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://jira.sakaiproject.org/browse/SAK-45996
=> SAK-45996 Kernel ignite and orm cache stategies should match

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/js/eventInfo.js, samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
https://jira.sakaiproject.org/browse/SAK-46001
In previous versions, there was some (fake) placeholder text indicating to search by user ID or name. In 20+, this information is missing.
=> SAK-46001 samigo > include input example for Event Log search

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java
https://jira.sakaiproject.org/browse/SAK-45752
=> SAK-45752 T&Q: Statistics incorrect for "None of the above" answers

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Click first site rather than unselect, builds off previous commit
=> SAK-45826 - When creating a new site, there is no longer a default selected

webcomponents/bundle/src/main/bundle/grades.properties, webcomponents/bundle/src/main/bundle/grades_ca.properties, webcomponents/bundle/src/main/bundle/grades_es.properties, webcomponents/tool/src/main/frontend/js/grades/sakai-grades.js
Adding some translations so it can be verified on QA
=> SAK-45982 Dashboard: Course/Assignment is hardcoded

site-manage/datemanager/impl/src/bundle/datemanager.properties, site-manage/datemanager/impl/src/bundle/datemanager_ca.properties, site-manage/datemanager/impl/src/bundle/datemanager_es.properties, site-manage/datemanager/impl/src/bundle/datemanager_tr_TR.properties, site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
- Show error on right row
- Feedback end can be empty.
=> SAK-46009 Dates manager: issues with Samigo feedback dates

library/src/webapp-filtered/editor/ckeditor.launch.js
https://jira.sakaiproject.org/browse/SAK-46024
=> SAK-46024 ckeditor file upload drag and drop bug

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
https://jira.sakaiproject.org/browse/SAK-46048
If you attempt to hide more than 1,000 sites in an Oracle environment, this action will fail. Symptoms are that all starred sites will disappear from the top bar, and the sites drawer will appear completely empty, along with the following stack trace in the logs (attached to JIRA).
This has gone through 3 rounds of QA, and is currently running in production at Western.
Thanks to @ern for this patch. Please use rebase+merge to preserve his authorship.
=> SAK-46048 hiding more than 1000 sites breaks in Oracle

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://jira.sakaiproject.org/browse/SAK-46054
=> SAK-46054 Assignments > Turnitin help link has target blank without noreferrer protection

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://jira.sakaiproject.org/browse/SAK-46014
=> SAK-46014 - Can't activate user when no maintain user is already active

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria-readonly.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-preview.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-45923
=> SAK-45923 RUBRICS: (i18n) Weight criterions appears with points instead of comma

help/help-tool/pom.xml, help/help-tool/src/webapp/TOCDisplay/main.jsp, help/help-tool/src/webapp/main.jsp, help/help-tool/src/webapp/search/main.jsp, help/help-tool/src/webapp/tableOfContents/main.jsp
Not 100% sure if this is the right dependency but it works after this change.
=> SAK-46061 - Help tool no longer works (22)

library/src/webapp/js/headscripts.js, site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/modified.html, site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/modules.html, site/sakai-message-bundle-manager-tool/src/main/webapp/WEB-INF/templates/search.html
I believe it's desirable to include them on every datatables reference instead of creating another case in the headscripts file.
=> SAK-45740 MBM : next page buttons

rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/command/SaveCommand.java
https://jira.sakaiproject.org/browse/SAK-46031
1. In any site that contains the Wiki tool, add a comment to any page
2. After the page finishes reloading, refresh the page (using your browser's refresh option, not the tool reset)
3. Your browser may warn you that you need to "resend data", or something similar. Allow it to do so.
4. Notice that your comment is now duplicated
5. You can repeat this as many times as you want, duplicating each time the page is refreshed
We can fix this by employing the POST-Redirect-GET (PRG) pattern:
Instead of the response after form submission responding with the same form data, redirect the response to the original page's URL so that on subsequent manual page refreshes the user is just submitting a GET for the page, rather than the …
=> SAK-46031 wiki > refreshing the page after posting a comment erroneously duplicates the comment

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
This allows the import from site code to properly create a new content-review assignment.
=> SAK-45983 move the code that creates a content review assignment into service

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
=> SAK-46038 do not send published announcement when importing published assignments

kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteStopNodeAndExitHandler.java, master/pom.xml
https://jira.sakaiproject.org/browse/SAK-46089
=> SAK-46089 Ignite upgrade to 2.10.0

calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarService.java, calendar/calendar-api/api/src/java/org/sakaiproject/calendar/cover/CalendarService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/PDFExportService.java, calendar/calendar-impl/impl/src/test/org/sakaiproject/calendar/impl/PDFExportServiceTest.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-tool/tool/src/webapp/js/sakai-calendar.js
Doesn't fix the problem but improves the logic because now it's done in the backend.
=> SAK-45768 - Calendar: Print view only displays the hours 8am - 5pm

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm, lessonbuilder/tool/src/webapp/css/Simplepagetool.css, library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, library/src/morpheus-master/sass/base/_extendables.scss, library/src/morpheus-master/sass/base/_jquery-ui-defaults.scss, library/src/morpheus-master/sass/modules/button/_base.scss, library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss, library/src/morpheus-master/sass/modules/tool/messages/_messages.scss, library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss, library/src/morpheus-master/sass/themes/_dark.scss, library/src/morpheus-master/sass/themes/_light.scss, library/src/webapp/skin/tool_base.css, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/msgHeader.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp, webcomponents/tool/src/main/frontend/js/announcements/sakai-announcements.js, webcomponents/tool/src/main/frontend/js/forums/sakai-forums.js, webcomponents/tool/src/main/frontend/js/grades/sakai-grades.js, webcomponents/tool/src/main/frontend/js/sakai-button.js, webcomponents/tool/src/main/frontend/js/sakai-dialog-content.js, webcomponents/tool/src/main/frontend/js/widgets/sakai-dashboard-widget.js, webcomponents/tool/src/main/frontend/js/widgets/sakai-grades-widget.js
https://jira.sakaiproject.org/browse/SAK-45683
Incorporates
https://jira.sakaiproject.org/browse/SAK-45608
https://jira.sakaiproject.org/browse/SAK-45763
https://jira.sakaiproject.org/browse/SAK-45788
https://jira.sakaiproject.org/browse/SAK-43209
https://jira.sakaiproject.org/browse/SAK-45546
https://jira.sakaiproject.org/browse/SAK-45548
https://jira.sakaiproject.org/browse/SAK-45585
https://jira.sakaiproject.org/browse/SAK-45620
https://jira.sakaiproject.org/browse/SAK-45653
https://jira.sakaiproject.org/browse/SAK-45664
https://jira.sakaiproject.org/browse/SAK-45665
https://jira.sakaiproject.org/browse/SAK-45709
https://jira.sakaiproject.org/browse/SAK-46046
=> SAK-45683 Dark theme fixes

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-preview-button.js
https://jira.sakaiproject.org/browse/SAK-43289
=> SAK-43289 Rubrics indicator icon doesn't use tool icon

library/src/webapp-filtered/editor/ckeditor.css
https://jira.sakaiproject.org/browse/SAK-46152
=> SAK-46152: Body text within CKEditor needs margin

usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/UserListBean.java, usermembership/tool/src/webapp/usermembership/js/usermembership.js, usermembership/tool/src/webapp/usermembership/sitelist.jsp, usermembership/tool/src/webapp/usermembership/userlist.jsp
Deleted by mistake https://github.com/sakaiproject/sakai/pull/9731, the PR was approved.
=> SAK-45634 - User membership: Needs to constrain search size

samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
See https://github.com/sakaiproject/sakai/pull/9656
=> SAK-45074 Samigo : add missing library for previous commit

library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic.scss, webcomponents/bundle/src/main/bundle/conversations.properties, webcomponents/tool/src/main/frontend/js/conversations/reactions-mixin.js
https://jira.sakaiproject.org/browse/SAK-46062
=> SAK-46062 Made lightbulb and key emojis higher contrast

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criterion-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://jira.sakaiproject.org/browse/SAK-45922
=> SAK-45922 Rubrics and Grader i18n: When grading an assignment with comma it appears with point

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/projections/InlineCriterion.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://jira.sakaiproject.org/browse/SAK-45941
=> SAK-45941 RUBRICS: Total weight shouldn't be more than 100%

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://jira.sakaiproject.org/browse/SAK-45882
=> SAK-45882 GRADER - Checked grading always appear checked when navigating between students

samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
https://jira.sakaiproject.org/browse/SAK-45310
=> SAK-45310 Samigo: Hot spot question fails to save and throws a stack trace if too much text is entered in the alt text field

gradebookng/bundle/src/main/bundle/gradebookng.properties
=> SAK-45852: gradebook: Improve text of "Hide Item" menu option to make it clearer

library/src/morpheus-master/sass/modules/navigation/_breadCrumbs.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm
https://jira.sakaiproject.org/browse/SAK-40324
Hi, this is my proposal to fix this issue
---
Proposal 
---
Problem
=> SAK-40324 Subsite name is shown over Tools button in mobile view

library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss
https://jira.sakaiproject.org/browse/SAK-45773
My proposal for solving this is to show a horizontal scroll like this
---
Proposal
---
Problem
=> SAK-45773 Date manager / overlapping text on mobile

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradePointsMapping.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/LetterGradeMapping.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/LetterGradePlusMinusMapping.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/PassNotPassMapping.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
https://jira.sakaiproject.org/browse/SAK-44932
Hi, this is related to this [PR](https://github.com/sakaiproject/sakai-reference/pull/130),
It's necessary to run that script to update the database values
=> SAK-44932 Lack of internationalitzation in Gradebook Settings: Grade type

webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://jira.sakaiproject.org/browse/SAK-46066
=> SAK-46066 Use sak banners to show instructor and group visibility

webcomponents/tool/src/main/frontend/.eslintrc.js, webcomponents/tool/src/main/frontend/js/conversations/sakai-topic.js
https://jira.sakaiproject.org/browse/SAK-46209
=> SAK-46209 Downgrade dot notation eslint rule to "warn"

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/templates/ShowPage.html
**Change status images to fa icons**
This affects links to assessments that are marked as required and questions in the lessons tool
Also added title attribute to icon to show what it means. 
(This is invisible for screen-readers, which is wanted! It will be read at another place, that's  why the alt attribute got removed before form the image)
=> SAK-37445 Bring Required Indicators in line with Font Awesome Use

site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
Based on @ottenhoff 's solution for https://github.com/sakaiproject/sakai/pull/9067
=> SAK-46211 Date manager: issue with locked announcement

library/src/morpheus-master/sass/_defaults.scss, library/src/morpheus-master/sass/base/_defaults.scss
https://jira.sakaiproject.org/browse/SAK-46228
=> SAK-46228 Library change scroll-behavior to smooth

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MathJaxEnabler.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
https://jira.sakaiproject.org/browse/SAK-46227
Just removing a property which would override what the user selected
=> SAK-46227 MathJax on site creation

samigo/samigo-app/src/webapp/css/timerbar.css
https://jira.sakaiproject.org/browse/SAK-45731
Change progressbar background to fix color contrast issue
=> SAK-45731: Samigo Accessibility > Timer > Color Contrast Issues

reset-pass/reset-pass/src/main/java/org/sakaiproject/resetpass/controller/MainController.java, reset-pass/reset-pass/src/main/resources/Messages.properties, reset-pass/reset-pass/src/main/resources/Messages_ca.properties, reset-pass/reset-pass/src/main/resources/Messages_es.properties, reset-pass/reset-pass/src/main/webapp/WEB-INF/templates/form.html, reset-pass/reset-pass/src/main/webapp/WEB-INF/templates/fragments/common.html
- Bug fix on `processAction()`: two mails were sendend when `siteManage.validateNewUsers`=false.
- UI improvements: element disposition and button activation.
- Format and messages.properties fixes.
Jira - [SAK-46233](https://jira.sakaiproject.org/browse/SAK-46233)
=> SAK-46233 Reset-pass: bug fix and UI improvement.

content/content-bundles/resources/content.properties, content/content-bundles/resources/types.properties
https://jira.sakaiproject.org/browse/SAK-46036 original PR #9613
=> SAK-46036 missing msg bundle keys

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
**Format "add subpage" dialog and correctly bind the combobox to the label
- Fix "for" of label with wrong id reference
- Apply bootstrap form CSS classes
- Move "Choose Page" link (functionaly) into a button "Pick a Page"
- Hide button color selection when buttons are not checked; Instead of gray label and a info text.
- Give "Create" button some color
=> SAK-45815: Lessons / Accessibility / add subpage dialog

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
Remove check-mark and X icons at survey questions feedback
=> SAK-45907: T&Q: Survey questions feedback formatting is off 

site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
For announcements and resources. Also sort issue with locked resources.
This is a bit dependant on https://github.com/sakaiproject/sakai/pull/9793 so will rebase after that one is merged
=> SAK-46212 Date manager: properly manage only open or end dates

library/pom.xml, library/src/morpheus-master/sass/modules/editor/_base.scss, library/src/webapp-filtered/editor/ckeditor.launch.js, library/src/webapp/editor/ckextraplugins/sakaidropdowntoolbar/plugin.js
https://jira.sakaiproject.org/browse/SAK-45844
=> SAK-45844 Library ckeditor sakaidropdowntool plugin

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/HistogramListener.java, samigo/samigo-services/pom.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
Most of the changes are just tabbing (the whole file is messed up though). The main changes I've introduced are the delegate calls, which is what's being done on the other listeners where calculated answers are... calculated.
=> SAK-45875 SAMIGO - Statistics for calculated and point value is 0

library/src/webapp/js/headscripts.js, podcasts/podcasts-api/src/bundle/org/sakaiproject/api/podcasts/bundle/Messages.properties, podcasts/podcasts-app/src/java/org/sakaiproject/tool/podcasts/podHomeBean.java, podcasts/podcasts-app/src/webapp/WEB-INF/faces-config.xml, podcasts/podcasts-app/src/webapp/podcasts/podListen.jsp, podcasts/podcasts-app/src/webapp/podcasts/podMain.jsp
Super cheap and useful feature!
=> SAK-46269 Podcasts: Ability to listen audio files.

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://jira.sakaiproject.org/browse/SAK-46267
Change error to warn.
Tag with low-risk
=> SAK-46267: ERROR: org.sakaiproject.lessonbuildertool.service.LessonBuilderEntityProducer.makePage

library/src/morpheus-master/sass/modules/grader/_base.scss, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
Hi, here's a preview of the result:
---
With submission
---
Without submission
=> SAK-45876 GRADER - No eye icon appears when grading a student with no submission when clicking Save and Release to Student

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/UIPermissionsManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-46282
This was a regression from SAK-44985
=> SAK-46282 Discussions slow performance

kernel/kernel-util/src/main/java/org/sakaiproject/util/NumberUtil.java, kernel/kernel-util/src/test/java/org/sakaiproject/util/NumberUtilTest.java
https://jira.sakaiproject.org/browse/SAK-46284
=> SAK-46284 Kernel NumberUtilTest throws NoSuchBeanDefinitionException

lessonbuilder/tool/src/webapp/templates/ShowPage.html
Move buttons to make them more responsive
- Moved buttons to new place
- Reused CSS form buttons on the bottom
=> SAK-45931: Lessons > Mobile View > Some Buttons not Responsive

search/elasticsearch/util/src/java/org/sakaiproject/search/elasticsearch/BaseElasticSearchIndexBuilder.java
https://jira.sakaiproject.org/browse/SAK-46293
=> SAK-46293 Search properly close elasticsearch client and index workers

search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
https://jira.sakaiproject.org/browse/SAK-46297
=> SAK-46297 Search elasticsearch automatic http port detection

content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/BaseContentReviewService.java
https://jira.sakaiproject.org/browse/SAK-46274
=> SAK-46274 Turnitin: originality report links for files containing plus signs causes 404

profile2/api/src/java/org/sakaiproject/profile2/model/UserProfile.java, profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoEdit.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoEdit.java
https://jira.sakaiproject.org/browse/SAK-46256
=> SAK-46256 Profile: Error trying to set Birthday

conversations/impl/pom.xml, conversations/impl/src/main/java/org/sakaiproject/conversations/impl/repository/TopicReactionTotalRepositoryImpl.java
https://jira.sakaiproject.org/browse/SAK-46317
=> SAK-46317 Add data-jpa dependency back into conversations

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
- Restore automatic checking of anonymous grading (Was removed when resolving merge conflicts with [SAK-46173](https://jira.sakaiproject.org/browse/SAK-46173)) 
- Adapt info text to new language of [SAK-45903](https://jira.sakaiproject.org/browse/SAK-45903) 
- Removed the cow
=> SAK 46331: Some problems in assessment settings

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java, samigo/samigo-app/src/test/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBeanTest.java
https://jira.sakaiproject.org/browse/SAK-46330
=> SAK-46330 Samigo use spring @Autowired vs javaee @Resource

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/templates/ShowPage.html, library/pom.xml
Super cheap PDF viewer for Lessons that works fine in Android and iOS devices.
=> SAK-46237 Lessons: Unable to view embedded pdf on mobile devices

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/SearchQuestionBean.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/ItemContentProducer.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/PublishedItemContentProducer.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/search/QuestionElasticSearchIndexBuilder.java, samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/entity/impl/ItemEntityProviderImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
This also fixes other elasticsearch issues within samigo and some queries using a deprecated format (see https://jira.sakaiproject.org/browse/SAK-46262).
At the moment elasticsearch is throwing lots of exceptions after the upgrade (there are a couple new jiras for those), so I'm leaving it as a draft as I might have to rebase/retest this afterwards.
=> SAK-46262 T&Q: elastic search NPE after importing to question pool

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
Could be handled differently but replicating exception patterns on the file
=> SAK-46180 Dashboard : error for admin with no worksite setup

commons/api/src/java/org/sakaiproject/commons/api/CommonsManager.java, commons/api/src/java/org/sakaiproject/commons/api/PersistenceManager.java, commons/impl/pom.xml, commons/impl/src/java/org/sakaiproject/commons/impl/CommonsManagerImpl.java, commons/impl/src/java/org/sakaiproject/commons/impl/PersistenceManagerImpl.java, commons/tool/src/java/org/sakaiproject/commons/tool/entityprovider/CommonsEntityProvider.java
Conditions were reversed on the getLike method
=> SAK-46185 Commons : like feature not working

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Change assessmentSettings bean reference to publishedSettings
=> SAK-46342: Samigo: Published assessment settings reference assessmentSettings

announcement/announcement-api/api/src/bundle/announcement.properties, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm
https://jira.sakaiproject.org/browse/SAK-45797
=> SAK-45797 Announcements: Warn that Email Notifications require a published site

content-review/impl/turnitin-oc/pom.xml, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java, content-review/pack/src/webapp/WEB-INF/turnitin-oc.xml
https://jira.sakaiproject.org/browse/SAK-46273
=> SAK-46273 Turnitin > files over 100mb should be rejected before attempted submission

msgcntr/messageforums-app/src/webapp/js/forum_movethread.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/moveThreadPicker.jsp
…icate forum to original forum topic
=> SAK-46241 Discussions move forum conversation from clone to original

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://jira.sakaiproject.org/browse/SAK-46359
=> SAK-46359 Filter out null feedback attachments for grader

samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp
https://jira.sakaiproject.org/browse/SAK-46354
Bad order
=> SAK-46354: SAMIGO: Due Date/Time order for student on published assessments don't work

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Open 'About this Assessment' accordion first -> Setting 'accordionPanel' to 0 will do that
=> SAK-46364: T&Q: Availability and Submissions should be the default section to open

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Reintroduce 'Stop accepting Now' button
=> SAK-46376: T&Q: Stop Accepting Now button missing

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-46379
=> SAK-46379 Update Apache Tomcat 9.0.54

content/DropBox.md, content/README.md, content/content-tool/tool/src/java/org/sakaiproject/content/tool/DropboxAuthz.java, content/content-tool/tool/src/java/org/sakaiproject/content/tool/DropboxHelper.java, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ListItem.java, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java, content/content-tool/tool/src/webapp/WEB-INF/tools/sakai.dropbox.xml, kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DropboxAuthzHandler.java, kernel/kernel-impl/src/main/webapp/WEB-INF/content-components.xml
Centralize the Drop Box authorization logic, improve its performance, increase the granularity / clarity of the Drop Box permissions, and document the intended behaviour of the new permissions.
Conversion script:
https://github.com/sakaiproject/sakai-reference/pull/128
=> SAK-46030 - Improve Drop Box authorization

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://jira.sakaiproject.org/browse/SAK-44930
=> SAK-44930 Turnitin options should not be displayed when alert appears when posting an assignment

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessageDirect.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java
https://jira.sakaiproject.org/browse/SAK-46368
These lines:
selectedTopic = getSelectedTopic();
message = this.saveOrUpdateMessage(message, false, toolId, userId, context, true);
are not related to the problem but should be on this way to avoid future problems.
=> SAK-46368 Discussions link to topic not available

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorImportExport.properties, samigo/samigo-app/src/webapp/jsf/qti/chooseExportType.jsp
This is resolving an incorrect fix in https://sakaiproject.atlassian.net/browse/SAK-45472
=> SAK-46488 fix re-ordered export that had JavaScript dependencies on order

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://sakaiproject.atlassian.net/browse/SAK-46467
=> SAK-46467 Make sure to select the given rating, even when overridden.

assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java, assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmission.java, assignment/api/src/java/org/sakaiproject/assignment/api/model/AssignmentSubmissionSubmitter.java, content-review/api/src/main/resources/ContentReviewItem.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Category.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Comment.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradableObject.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradeMapping.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Gradebook.hbm.xml, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Spreadsheet.hbm.xml, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Evaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rubric.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ToolItemRubricAssociation.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/FavoriteColChoices.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/grading/GradingData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/grading/MediaData.hbm.xml
Relationated with [SAK-46157](https://sakaiproject.atlassian.net/browse/SAK-46157)
=> SAK-46157: fix issues with oracle conversion scripts

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AuthorBean.java, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
https://sakaiproject.atlassian.net/browse/SAK-46501
=> SAK-46501 Samigo - Add property to select the default sorting column in assessment list view

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/BltiPickerProducer.java
https://sakaiproject.atlassian.net/browse/SAK-44695
=> SAK-44695 - Remove extraneous output

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
All the other calls to this method are already under these checks.
=> SAK-46470 Assignments : avoid wrong calls showing log warn

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/GenericCalendarImporter.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/CSVReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/IcalendarReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/OutlookReader.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/Reader.java
See solution applied to Icalendar -> https://github.com/sakaiproject/sakai/commit/784b6dae7d44f8a603f297544e3380be42687fb1#diff-9a3ea3a6ec14e6da301f6177b9f05ef23e48ccb3af42ccf5f8e78c9701c8bcee
I had started a bigger refactor moving common code and changing Dates to LocalDate/LocalTime but this is actually enough.
=> SAK-46141 Calendar / import from CSV off by 1 hour

samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Set prevValue and don't hide help text
=> SAK-46498: Reopen - Samigo > Create/Edit > Settings > User selections lost/changed silently

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-common/src/java/org/sakaiproject/lti13/util/SakaiDeepLink.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/objects/DeepLink.java
This is a soon-to-be released LTI feature
=> SAK-46508 - LTI - send new accept_lineitem property

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
https://sakaiproject.atlassian.net/browse/SAK-46507
=> SAK-46507 Save and close rubric comment editor on blur

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-46514
=> SAK-46514: GROUP is hardcoded on Site Info Tool

entitybroker/core-providers/pom.xml, entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/IgniteEntityProvider.java, entitybroker/core-providers/src/webapp/WEB-INF/applicationContext.xml
https://sakaiproject.atlassian.net/browse/SAK-46526
=> SAK-46526 EntityBroker add Ignite endpoint for accessing cluster info

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
…er sending the last submission try
=> SAK-46515 Assignments allow students to view all instructor feedback revisions 

.github/workflows/maven.yml, .github/workflows/server.yml, webcomponents/tool/src/main/frontend/js/sakai-i18n.js
1) Builds Sakai and deploys to Tomcat
2) Spins up a MySQL server
3) Runs Cypress browser test suite
4) Checks the number of queries run against MySQL for oddities
5) Opens up an HTTPS tunnel to do human testing against the PR if necessary
=> SAK-46481 GitHub actions spin up server and run browser tests on every PR 

basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java
Thanks to Biraj Dhakal for bring this to our attention on the dev list.
=> SAK-46538 - LTI Pass client_id and lti_deployment_id to the oidc_login

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46545
=> SAK-46545 Assignments > Participant member of 2 or more groups is not shown in submissions list

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Attachment validation has recently been added to more places, so it makes sense to include the video check in there (previously it was just on one spot as it doesn't allow preview or save as draft).
=> SAK-46415 Assignments : can't submit video recordings

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Also Pass/Fail on another screen
=> SAK-46242 Assignments : Checkmark Color

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html
https://sakaiproject.atlassian.net/browse/SAK-46474
=> SAK-46474 Gradebook : add message about disabled option

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/delivery/TimedAssessmentGradingModel.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/queue/delivery/TimedAssessmentRunnable.java
check the ExtendedTime to see if an instructor gave the student more time to finish.
=> SAK-45667 before timer-submitting a student assessment,

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/IgniteEntityProvider.java, kernel/kernel-impl/src/main/java/org/sakaiproject/ignite/IgniteConfigurationAdapter.java
https://sakaiproject.atlassian.net/browse/SAK-46578
=> SAK-46578 Ignite add info about number of nodes in the cluster

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/AreaManagerImpl.java
Replace cdfm_discussion_forums with cdfm_discussions, beacuse cdfm_discussion_forums is gone
=> SAK-46582: Discussons: missing key: 'cdfm_discussion_forums'

webcomponents/bundle/src/main/bundle/permissions-wc.properties, webcomponents/tool/pom.xml, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js, webcomponents/tool/src/main/frontend/js/sakai-permissions.js, webcomponents/tool/src/main/java/org/sakaiproject/webcomponents/permissions/PermissionsEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-46576
=> SAK-46576 Permissions rest endpoint now checks realm.upd

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
https://sakaiproject.atlassian.net/browse/SAK-46603
=> SAK-46603 Rubrics: Only fire a comment updated event once

webcomponents/tool/src/main/frontend/js/conversations/sakai-conversations-settings.js, webcomponents/tool/src/main/frontend/js/sakai-toggle.js
https://sakaiproject.atlassian.net/browse/SAK-46599
Adds a new property, labelled-by, to allow labelling with another
element
=> SAK-46599 Add checkbox role to sakai-toggle

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessageDirect.jsp
https://sakaiproject.atlassian.net/browse/SAK-46606
=> SAK-46606: Discussions link to topic not available

assignment/api/src/java/org/sakaiproject/assignment/api/ContentReviewResult.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java
Avoid expensive lookups by retaining the computed score in a HashMap.
=> SAK-46592 improve speed of sorting by ContentReview score.

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java
https://sakaiproject.atlassian.net/browse/SAK-46325
=> SAK-46325 Kernel authz throwing permission exception for site realms

assignment/api/src/java/org/sakaiproject/assignment/api/model/TimeSheetEntry.java
https://sakaiproject.atlassian.net/browse/SAK-46641
=> SAK-46641 Assignment @ToString should exclude submitter

assignment/api/src/java/org/sakaiproject/assignment/api/model/TimeSheetEntry.java
https://github.com/sakaiproject/sakai/pull/10050
=> SAK-46610 Assignment TimeSheetEntry adjust comment length for Oracle

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-46680
=> SAK-46680 Upgrade log4j2 to 2.15.0

assignment/api/src/java/org/sakaiproject/assignment/api/model/TimeSheetEntry.java
https://sakaiproject.atlassian.net/browse/SAK-46679
SCRIPTS
https://github.com/sakaiproject/sakai-reference/pull/144
=> SAK-46679 Oracle COMMENT is a reserved word

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-46680
=> SAK-46680 upgrade Log4J to v2.16.0

jsf2/jsf2-widgets/src/java/org/sakaiproject/jsf2/renderer/PagerRenderer.java
Reapplying fix from SAK-45132 to jsf2
=> SAK-46675 - Job Scheduler: Show all crept back in the drop-down

library/src/morpheus-master/sass/modules/tool/chat/_chat.scss
=> SAK-46472 Chat messages box post style causes low readability with dark theme

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
https://sakaiproject.atlassian.net/browse/SAK-46690
=> SAK-46690 Discussions: Use right ckeditor webjar in dfMsgGrade

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-46680
=> SAK-46680 Upgrade log4j2 to 2.17.0

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java, gradebookng/tool/src/webapp/scripts/gradebook-cancelrubric.js, gradebookng/tool/src/webapp/scripts/gradebook-savecancelrubric.js, gradebookng/tool/src/webapp/scripts/gradebook-saverubric.js, samigo/samigo-app/src/webapp/js/samigo-global.js, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/sakai-portal-utils.js, webcomponents/tool/src/main/frontend/test/sakai-portal-utils.test.js
=> SAK-45987 Fix cancel behaviour with rubric evaluations

library/src/webapp/skin/tool_base.css
https://sakaiproject.atlassian.net/browse/SAK-46653
=> SAK-46653 Assignments Dark Theme student view of the assignment

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java, basiclti/basiclti-blis/src/java/org/sakaiproject/lti13/LTI13Servlet.java, basiclti/basiclti-common/pom.xml, basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiKeySetUtil.java, basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiKeySetUtilTest.java, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/tsugi-util/src/java/org/tsugi/lti13/LTI13Util.java, basiclti/tsugi-util/src/test/org/tsugi/lti13/LTI13UtilTest.java
Mostly utility code and unit tests.
=> SAK-46134 - Switch from per-tool to a single global KeySet

webcomponents/tool/src/main/frontend/js/sakai-dialog-content.js
https://sakaiproject.atlassian.net/browse/SAK-46745
=> SAK-46745 Dashboard: Change layout cancel button from chips

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreListener.java
https://sakaiproject.atlassian.net/browse/SAK-46743
UserSortNameComparator should be used instead of String sort.
Here were resolved another sorting problems on other tools
https://github.com/sakaiproject/sakai/pull/8002/files
=> SAK-46743 Samigo sorting is wrong on submissions

assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/RubricGradePanel.java, gradebookng/tool/src/webapp/scripts/gradebook-cancelrubric.js, gradebookng/tool/src/webapp/scripts/gradebook-savecancelrubric.js, gradebookng/tool/src/webapp/scripts/gradebook-saverubric.js, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml, msgcntr/messageforums-app/src/webapp/js/forum.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ReturnedCriterionOutcome.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ReturnedEvaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/ReturnedEvaluationRepository.java, rubrics/impl/src/main/webapp/WEB-INF/components.xml, rubrics/tool/src/main/java/org/sakaiproject/rubrics/RubricsRepositoryRestConfiguration.java, samigo/samigo-app/src/webapp/js/samigo-global.js, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/sakai-portal-utils.js, webcomponents/tool/src/main/frontend/test/sakai-portal-utils.test.js
=> SAK-45987 Rubrics: Fix cancel behaviour while grading

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/ViewableFilter.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/DbAnnouncementService.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/entityprovider/AnnouncementEntityProviderImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-46750
=> SAK-46750 Dashboard: Only show MOTD if viewable by user

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://sakaiproject.atlassian.net/browse/SAK-46422
=> SAK-46422: ERROR: org.sakaiproject.lessonbuildertool.service.LessonBuilderEntityProducer.transferAttachmentFiles

assignment/impl/src/java/org/sakaiproject/assignment/impl/GradeSheetExporter.java
https://sakaiproject.atlassian.net/browse/SAK-46620
=> SAK-46620 Assignments > Grades are in 14 digits precision in the export_grades_bulk_download excel file

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://sakaiproject.atlassian.net/browse/SAK-46521
=> SAK-46521 Lessons section title is hardcoded

library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss, library/src/morpheus-master/sass/themes/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-46594
=> SAK-46594 Lessons adjust subpage button colors for WCAG AA

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-45948
=> SAK-45948 Rubrics: moved rubric criterion comment to bootstrap

gradebookng/tool/pom.xml, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BasePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46567
=> SAK-46567 Set correct evaluated_item_owner_id for group assignments

kernel/api/src/main/java/org/sakaiproject/user/api/UserDirectoryService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/emailtemplateservice/impl/EmailTemplateServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
https://sakaiproject.atlassian.net/browse/SAK-46740
=> SAK-46740 ETS: convert user references to user ids in send

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/ViewableFilter.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/DbAnnouncementService.java, message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java, webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java
https://sakaiproject.atlassian.net/browse/SAK-46774
This also reverse date sorts on the combined list of announcements.
=> SAK-46774 Limit the announcements widget to the last 10 days

kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://sakaiproject.atlassian.net/browse/SAK-46776
=> SAK-46776 Ignite add ttl for cached objects

content/content-metadata/impl/pom.xml, content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/logic/JsonMetadataParser.java, content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/mixins/ListMetadataTypeMixin.java, content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/mixins/MetadataTypeMixin.java, content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/GroupMetadataType.java, content/content-metadata/impl/src/java/org/sakaiproject/content/metadata/model/ListMetadataType.java, content/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-46790
=> SAK-46790 Resources upgrade content-metadata jackson lib to v2

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-44372
=> SAK-44372 Grader: stop validator swallowing tab

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://sakaiproject.atlassian.net/browse/SAK-44028
=> SAK-44028 Assignments: Bulk download creates 0-byte zip

webapi/src/main/java/org/sakaiproject/webapi/controllers/DashboardController.java
https://sakaiproject.atlassian.net/browse/SAK-46750
=> SAK-46750 Dashboard: Make sure latest MOTD is retrieved

library/src/webapp/js/headscripts.js
https://sakaiproject.atlassian.net/browse/SAK-46804
=> SAK-46804: ERROR 404 Library - lang.js

library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
https://sakaiproject.atlassian.net/browse/SAK-42085
Also, switch to buttons. Semantic web and all that jazz :)
=> SAK-42085 Rubrics: show add rating button all the time, like on mobile

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-46802
=> SAK-46802 SiteInfo: refresh group membership modal on info page

site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46584
=> SAK-46584 Calendar - Can not modify own events if remove 'edit all events' permission

signup/api/src/java/org/sakaiproject/signup/logic/SignupUser.java, signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46758
=> SAK-46758 Sorting is wrong on Sign-up

library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyBusinessDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyBusinessDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyContactDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyContactDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInterestsDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInterestsDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStaffDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStaffDisplay.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStudentDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStudentDisplay.java, profile2/tool/src/webapp/javascript/profile2.js
Objectives for _My profile_ section
- Make button visibility consistent: After saving or canceling changes, it wasn't visible when focused using the tab key.
- Enhance the way info is provided to secreen reader.
Check [SAK-46486](https://sakaiproject.atlassian.net/browse/SAK-46486) for more details.
I've also formatted the code, so I'll highlight the relevant changes.
=> SAK-46486 Profile: Improve Accessibility for Edit Buttons

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-46803
=> SAK-46803 Sorting by grade is not working correctly when user locale use a comma as decimal separator

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
I changed the text for the alert message as suggested by Tiffany to improve the understanding.
=> SAK-46655 Discussions: Improve text of alert message for open/close date validadation

sections/sections-app/src/webapp/options.jsp
I've included the buttons and labels in a panelGrid to make it responsive.
=> SAK-46295 Section Info > Options > Improve Text Wrapping around Radio Buttons

rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46824
=> SAK-46824 Rubrics: Update active flag in site import

search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/ElasticSearchTest.java
https://sakaiproject.atlassian.net/browse/SAK-46834
=> SAK-46834 Search elasticsearch port randomization during tests

library/src/morpheus-master/sass/modules/tool/conversations/_conversations.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-add-topic.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-conversations-settings.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-conversations-tag-manager.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-post.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic-list.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic-summary.scss, library/src/morpheus-master/sass/modules/tool/conversations/_sakai-topic.scss, library/src/morpheus-master/sass/modules/tool/conversations/_statistics.scss, webcomponents/tool/src/main/frontend/js/conversations/sakai-add-topic.js
https://sakaiproject.atlassian.net/browse/SAK-46813
=> SAK-46813: Conversations: Missing namespace on all scss files

webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/.eslintrc.js, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
=> SAK-45987 Rubrics: Cancel a rubric, update the tool's points

kernel/kernel-impl/src/main/java/org/sakaiproject/time/impl/UserTimeServiceImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/time-components.xml
https://sakaiproject.atlassian.net/browse/SAK-45919
Important regression from: https://github.com/sakaiproject/sakai/pull/9401
=> SAK-45919 Assignments dates appear in the user preference language instead of site language

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
…ld make it fail when revieweng the question on total scores view
=> SAK-46772 Samigo Total Scores View fails when reviewing calculated questions with repeated formula

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/CourseGrade.java, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradeRecord.hbm.xml, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/CourseGradeRecord.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/ExcuseGradeAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/GradeUpdateAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestFormatHelper.java
https://sakaiproject.atlassian.net/browse/SAK-46686
https://github.com/sakaiproject/sakai-reference/pull/145
New implementation for this one that was reverted here:
https://github.com/sakaiproject/sakai/pull/10070
=> SAK-46686 Reimplementing showCalculatedGrade=false

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
=> SAK-45987 rubrics: Don't release cancelled evaluations

site-manage/datemanager/tool/src/main/java/org/sakaiproject/datemanager/ThymeleafConfig.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/config/GroupManagerConfiguration.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/config/GroupManagerThymeleafConfig.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/form/JoinableSetForm.java, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step1.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/wizard.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
https://sakaiproject.atlassian.net/browse/SAK-46811
Also, this commit fixes a load of unscoped selectors that can select
all of the matches on the entire document, including form submit
buttons.
=> SAK-46811 GroupManager: Test for missing checkbox

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemoveAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RemovePublishedAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp, samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java
I've added the option to create tasks for students on a site when you configure tests on samigo. These tasks are automatically updated or deleted when yo do such things on the settings of the test.
=> SAK-45052 Add Tests & Quizzes to Tasks widget

lessonbuilder/tool/src/webapp/templates/ShowPage.html
=> SAK-46843: Lessons: Typo in aria attribute of Questions status icons 

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-46801
=> SAK-46801 SiteInfo: Ensure info group table has the right columns

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/experimental.sakai.properties
[SAK-46686](https://sakaiproject.atlassian.net/browse/SAK-46686)
For testing
=> SAK-46686: Reimplementing showCalculatedGrade=false

library/src/morpheus-master/sass/modules/portal-search/_base.scss, webcomponents/bundle/src/main/bundle/search.properties, webcomponents/tool/src/main/frontend/js/sakai-search.js
https://sakaiproject.atlassian.net/browse/SAK-46838
=> SAK-46838 wcsearch: Show spyglass icon after first search

master/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-46864
=> SAK-46864 Update SLF4J 1.7.35

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java
[https://sakaiproject.atlassian.net/browse/SAK-46863](https://sakaiproject.atlassian.net/browse/SAK-46863)
=> SAK-46863 Samigo make cell style reusable fixing incorrect dates

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, rubrics/api/src/main/bundle/rubrics.properties, rubrics/api/src/main/bundle/rubrics_ca.properties, rubrics/api/src/main/bundle/rubrics_es.properties, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/RubricsService.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/logic/RubricsServiceImpl.java, rubrics/tool/pom.xml, rubrics/tool/src/main/java/org/sakaiproject/rubrics/RubricsApplication.java, rubrics/tool/src/main/java/org/sakaiproject/rubrics/controller/GeneratePdfController.java, rubrics/tool/src/main/java/org/sakaiproject/rubrics/controller/MainController.java, rubrics/tool/src/main/resources/templates/index.html, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-pdf.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-readonly.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-list.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-shared-list.js
SAK-44926 Export Rubrics on PDF
Be able to export a rubric on pdf.
With this new option, rubrics can be downloaded in pdf format both blank and graded.
=> SAK-44926 Export Rubrics on PDF

conversations/impl/src/main/java/org/sakaiproject/conversations/impl/ConversationsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46844
=> SAK-46844 Conversations: clear sorted stats cache on realm.upd

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp
question or not to use different converters.
=> SAK-46845: render different outputText tag depending if this is a Survey

edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/SiteTitleAdvisorCMS.java
Consider these sakai.properties:
```
portal.use.sectionTitle=true
portal.use.sectionTitle.preferredCategory=LEC
```
If the properties are set in this manner, and a user has only non-preferred category enrolments, the title from SAKAI_SITE is displayed. Even though the user does not have enrolments in the preferred category, we should still display one of their enrolled sections' title.
=> SAK-46859 - When displaying the site title, fallback to a non-preferred category section title if a preferred category section title is not present

calendar/calendar-api/api/src/java/org/sakaiproject/calendar/api/CalendarService.java, calendar/calendar-bundles/resources/calendar.properties, calendar/calendar-bundles/resources/calendar_es.properties, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_revise.vm
I added the option to create tasks when creating/updating events in the calendar. Tasks are also updated and removed if required, when doing so in the calendar.
=> SAK-45055 Add option in Calendar to create Tasks from events

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/ExportResponsesBean.java
[https://sakaiproject.atlassian.net/browse/SAK-46863](https://sakaiproject.atlassian.net/browse/SAK-46863)
=> SAK-46863_2: Samigo make cell style reusable fixing incorrect dates

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/webapp/js/studentViewSubmission.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_estimate.vm, kernel/kernel-impl/src/main/java/org/sakaiproject/timesheet/impl/TimeSheetServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-46812
=> SAK-46812 Assignments students can insert a timesheet without a comment

sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/OptionsBean.java, sections/sections-app/src/webapp/js/sections.js, sections/sections-app/src/webapp/options.jsp
Primary fix is in sections.js and pertains to where the user is redirected after selecting options.
Other changes are simple refactoring, using better method names, better logging.
=> SAK-46749 fix options checkbox selections.

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
Also, added console.debug to all methods in sakai-rubric-grading.js
=> SAK-45987 rubrics: cancel evaluation and don't set total points

library/src/trinity/src/sass/tool.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeFooter.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeLoginNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includePageBody.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includePageNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includePageWithNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeSiteHierarchy.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeSitesNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/moresites.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/site.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/snippets/header-snippet.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/snippets/skipNav-snippet.vm
https://sakaiproject.atlassian.net/browse/TRINITY-17
Initial conversion of the Morpheus portal into the Trinity portal to make the page usable. Not the final form.
=> TRINITY-17 Initial conversion of morpheus portal into trinity portal

kernel/api/src/main/java/org/sakaiproject/timesheet/api/TimeSheetEntry.java
https://sakaiproject.atlassian.net/browse/SAK-46916
Also a PR for the sakai conversion script has to be merged https://github.com/sakaiproject/sakai-reference/pull/149
=> SAK-46916 ORACLE Timesheet index name is too long

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/api/src/resources/assignment.properties, assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/grader/submission.js
This makes the existing allow extension feature in Assignemnts
available in Sakai Grader in the same way it exists in the classic
grader view.
=> SAK-46809 Assignments Add allow extension to Sakai Grader

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_estimate.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_preview_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
https://sakaiproject.atlassian.net/browse/SAK-46911
=> SAK-46911 Assignments Disable worklog on a site still shows elements of worklog

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://sakaiproject.atlassian.net/browse/SAK-41593
=> SAK-41593: Lessons Automatic Checklist links don't import-imported Checklist doesn't work

kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql, kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql
Added Dashboard page & tool to user template.
=> SAK-46891 Make Dashboard visible by default for users

library/src/morpheus-master/sass/modules/portal-search/_base.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-manager.js, webcomponents/tool/src/main/frontend/js/sakai-search.js
https://sakaiproject.atlassian.net/browse/SAK-46915
=> SAK-46915 WCSearch: Enable up/down arrows on search results

library/src/trinity/config/.stylelintrc.json, library/src/trinity/src/sass/tool.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includePageNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeSiteHierarchy.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/trinity/includeSitesNav.vm
https://sakaiproject.atlassian.net/browse/TRINITY-17
Revisions of fixes for #10233
=> TRINITY-17 Revisions to initial conversion of morpheus to trinity portal

common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/ArchiveService2Impl.java, common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteZipper.java
https://sakaiproject.atlassian.net/browse/SAK-45064
=> SAK-45064 SiteInfo: Ensure all unzip dirs are created

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm, library/src/webapp/skin/tool_base.css
https://sakaiproject.atlassian.net/browse/SAK-43240
=> SAK-43240 Assignments Missing button "or select files from 'Home' or site" when reviewing peer assignments

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://sakaiproject.atlassian.net/browse/SAK-46801
Removed an unused js function, too.
=> SAK-46801 SiteInfo: Fixed view membership link

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java
https://sakaiproject.atlassian.net/browse/SAK-46774
=> SAK-46774 WCAnnouncements: release date ordering fix

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://sakaiproject.atlassian.net/browse/SAK-46925
=> SAK-46925 Assignments Setting assignment's due and accept submits until in the past autochecks the estimate time

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://sakaiproject.atlassian.net/browse/SAK-46894
=> SAK-46894 rubrics: stop comment popover obscuring trigger icon

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ReturnedCriterionOutcome.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/ReturnedEvaluation.java
=> SAK-45987 Tests & Quizzes: When grading by question, cancelled rubric is still saved
