samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/webapp/jsf/delivery/discrepancyInData.jsp
https://jira.sakaiproject.org/browse/SAK-44383
Usage of samigo has increased drastically due to the pandemic. As an extension, more instructors are delivering quizzes using the published assessment URL. Due to other issues, it can be quite easy for students to get click happy and/or become impatient and refresh the page before it finishes loading. The result is that the students are taken to the "Data Discrepancy" page.
In a normal situation, this Data Discrepancy page provides the user with a button to return to the samigo landing page (quiz listing UI). However, in the case of a quiz delivered by published URL, this button does not appear (nor should it in this case, the instructor intended for the user to take a specific quiz, not give them the option to take other quizzes in the site …
=> SAK-44383 samigo > provide return link on DD UI for URL delivered quizzes

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/stats/CourseGradeStatistics.java
Average course gpa was calculated incorrectly as a percentage. This
maps the grade labels from the schema to a gpa value when entered in
the format "Grade (gpa)" e.g. "A (4.0)". And then calculates the average
course gpa based on the gpa values taken from the map or n/a if the
labels are not formatted correctly. This used when the grade schema is
set to Grade Points.
=> SAK-44373 Fix average gpa calculation in course grade statistics

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/confirmSubmit.jsp, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/saveForLaterWarning.jsp, samigo/samigo-app/src/webapp/jsf/delivery/tableOfContents.jsp
https://jira.sakaiproject.org/browse/SAK-44377
Changed the banners that appear when previewing an assessment to the standard Sakai banners and removed some unused Samigo banners.
=> SAK-44377 Updated Samigo assessment preview banners

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
Addresses when the retract time elapses before the timed quiz duration, the user currently gets "Assessment no longer available." This fix saves the user's work, submits, then sends them to the submission confirmation screen.
Please review critically.
I've accommodated ExtendedTimeDeliveryService.getRetractDate(), but I haven't considered extended time limits, and I'm uncertain how to test them. The bit in checkBeforeProceed() might need some treatment for instance
=> SAK-44155 - T&Q: Timed quiz with due date and late allowed, displays wrong screen on timer expire/late time

lessonbuilder/tool/src/resources/messages.properties, lessonbuilder/tool/src/resources/messages_es.properties, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Hi,
I've made a solution for this issue: to validate de characters of the subpage title. This way the links from the left pannel do not cause errors.
This patch should be merged with sakai 21.x, 20.x and 19.x
Thank you in advance.
=> SAK-43998 Pipe or back slash in Lesson sub page name error

assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java, assignment/impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-44416
#8415 removed the bean definition for `AssignmentSiteFsVolume`, thus removing the ability to entity link to assignments. This needs to be restored.
=> SAK-44416 restore ability to entity link to assignments

polls/api/src/java/org/sakaiproject/poll/hbm/Option.hbm.xml
https://jira.sakaiproject.org/browse/SAK-44420
Accompanying conversion script PR: https://github.com/sakaiproject/sakai-reference/pull/94
We used to have protection against this on the Java side:
```
public Boolean getDeleted() {
return (deleted == null) ? Boolean.FALSE : deleted;
}
```
However this was removed during some lombokification in https://jira.sakaiproject.org/browse/SAK-40814. This results in an NPE being thrown when accessing the Polls tool in a site which has `null` for this field in the database.
I'd prefer to leverage database constraints and default values to resolve this rather than adding the Java code back.
=> SAK-44420 NPE when poll_option.deleted is null

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://jira.sakaiproject.org/browse/SAK-43299
If you have a lot more sections than groups, or vice versa, the sections of the accordion are equal heights, using the maximum content height. This results in a lot of whitespace in the section that doesn't have as much content.
This PR changes the jQuery widget to make each section uniquely sized, based on the content of each rather than the max of all.
=> SAK-43299 site info > make accordion sections the size of their content

samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemText.java
There is a similar pattern in `ItemText.java` but the distractor never displays there as this is only during grading so I don't think correct/incorrect is applicable.
=> SAK-44452 - None of the above isn't checked when it is the answer on grading Questions

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties
https://jira.sakaiproject.org/browse/SAK-44382
The Forums Watch option is often overlooked, and users who want to enable notifications do not understand its purpose.
https://jira.sakaiproject.org/browse/FARM-2
=> SAK-44382 forums > rename 'watch' to 'notifications'

library/src/morpheus-master/sass/modules/tool/forums/_forums.scss, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
https://jira.sakaiproject.org/browse/SAK-29425
Use case: Instructor would like for information displayed in the table on the Statistics page in Forums (msgcntr) to also display on each individual student's page.
=> SAK-29425 forums > add percent read and num authored to individual statistics UI

kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml
Many sequences were not being created in Oracle via auto.ddl.
In Hibernate 5.3 the setting hibernate.id.new_generator_mappings is set to true by default.
This makes the old way of defining a sequence using generator class="native" not work. Instead,
this should be updated to class="org.hibernate.id.enhanced.SequenceStyleGenerator" and sequence
parameter is now called sequence_name.
=> SAK-44207 Update sequence definition in hbm.xml files for Hibernate 5

userauditservice/tool/src/java/org/sakaiproject/userauditservice/tool/UserAuditEventLog.java
Managing also action user separately, it will show 'n/a' in the source column.
=> SAK-44458 Audit : show user id in the logs when skipping removed

rwiki/rwiki-tool/tool/src/webapp/WEB-INF/command-pages/edittoolbar.jsp, rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/macros.vm, rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
Previously the tool tips were only present on a 5x5px transparent GIF contained within the button, resulting in people not being aware of what the buttons do until they try to use them.
=> SAK-44388 rwiki > improve tool tips

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionMessageBean.java
https://jira.sakaiproject.org/browse/SAK-25024
Users routinely have name mis-spellings corrected and changed. Users can also have their eid changed during the course of enrolment at an institution (marriage, divorce, etc). With the current behaviour in Forums, the only way to "fix" the "Authored By" in a forum, is editing directly in a DB.
=> SAK-25024 forums > use UserDirectoryService to resolve author names dynamically

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Rubric.java
https://jira.sakaiproject.org/browse/SAK-44262
rbc_rubric and rbc_criterion were not getting automatically created in Oracle
because the columnDefinition configuration there previously was not compatitble.
This removes that property and instead sets the default values with PrePersist
JPA annotation.
=> SAK-44262 Fix rubrics table creation in Oracle

content/content-tool/tool/src/webapp/WEB-INF/tools/sakai.dropbox.xml
The values should be separated by commas and not by pipes "|".
This way, the logic can read the different values in the file SitePageEditHandler.java
in the line:
return new ArrayList<>(Arrays.asList(StringUtils.split(functions, ',')));
And the permissions are correctly processed.
Thank you.
=> SAK-43149 Drop Box - "Lock" icon incorrectly displays in Tool Order

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
https://jira.sakaiproject.org/browse/SAK-44510
`IndexOutOfBoundsException` produced when editing a calculated question with more than 26 variables and formulas (combined).  This question type was likely never tested with insane amounts of variables and formulas. This does not affect the initial save of the question, nor does it affect students taking the question, nor grading of the question.
Problem code in question is in `ItemAddListener.preparePublishedTextForCalculatedQuestion()`:
```
for (CalculatedQuestionAnswerIfc curVarFormula : list) {
String match = curVarFormula.getMatch();
Long curSequence = curVarFormula.getSequence();
boolean isCorrect = curSequence.equals(sequence);
String choiceLabel = AnswerBean.getChoiceLabels()[curSequence.intValue()];
boolean foundAnswer = false;
for …
```
=> SAK-44510 samigo > fix editing questions with > 26 variables+formulas

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria-readonly.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-edit.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://jira.sakaiproject.org/browse/SAK-44406
If we set the title, or the weighting, all we need to know is that it
worked, we don't need the whole rubric JSON back. Thus, we avoid a
rancid bug in Spring Data Rest.
=> SAK-44406 Use the rubric PATCH return code, instead of the body

content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java, kernel/kernel-util/src/main/java/org/sakaiproject/content/util/ZipContentUtil.java
It seems the STATE_HOME_COLLECTION_DISPLAY_NAME attributte had a wrong value since the early times, probably not used elsewhere though
=> SAK-44477 File naming when compressing top-level folder

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
Hi;
There is a fixing of an issue in lessons, related to groups, in sakai 21.x that has not been applicated to 20.x and 19.x.
The method isItemVisible of the java class SimplePageBean lacks the the code of the snippet below.
This arrangement should be applied to 20 and 19.
For this reason I request that this commit be merged in sakai 20 and 19.
Thank you very much in advance.
=> SAK-44378 Lessons : group visibility not working for external tool

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/menu/forumsMenu.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
https://jira.sakaiproject.org/browse/SAK-40409
Via the _Forums_' *Statistics and Grading* screen, instructors/project site administrators can access individual participants' posting statistics.  The page for a specific user includes all messages the user posted (with the subjects linked to access those posts in context) and a list of messages the user marked as Read.  There's also an option to jump to a page showing the Full text of all posts the student authored.
This information is not available to students/members, and often students are assigned to post a certain number of times each week or respond to a certain number of posts.  Each site participant should be able to access their own view of the page containing their individual statistics.
=> SAK-40409 forums > allow students to access their own stats

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
https://jira.sakaiproject.org/browse/SAK-44520
Editing a closed quiz with extended time entries to change unrelated settings (feedback, send to gradebook, etc.) is blocked by extended time validation (because the extensions due dates are now in the past).
When I originally developed SAK-43610, I enforce validation in 4 spots:
1. When adding an extended time entry to a draft quiz (validate single entry)
2. When adding an extended time entry to a published quiz (validate single entry)
3. When saving a draft quiz (validate all entries)
4. When saving a published quiz (validate all entries)
Due to the design of the extended time interface, you must click the "save" button for the extension entry before clicking the "save" button of the quiz itself. If you save the quiz before the extension …
=> SAK-44520 samigo > dont validate extended time entries on save of quiz

lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java
This change is only for Sakai 20 and 19 as this is solved in 21 with
Apache Ignite
=> SAK-44527 Lessons Remove findItemsOnPage from QueryResultsCache

assignment/api/src/java/org/sakaiproject/assignment/api/model/Assignment.java
This allows Oracle to search this field from a query something not allowed
when using type CLOB
=> SAK-43947 Assignment ASN_ASSIGNMENT_PROPERTIES.VALUE to varchar 4000

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/ToolItemRubricAssociationRepository.java
This is only for 20.x and 19.x as this is not an issue in distributed cache environment
=> SAK-44394 Rubrics Disable ToolItemRubricAssociation query cache

library/src/morpheus-master/sass/modules/tool/oauthadmin/_oauthadmin.scss, library/src/morpheus-master/sass/tool.scss, oauth/tool/src/java/org/sakaiproject/oauth/tool/pages/SakaiPage.java, oauth/tool/src/resources/org/sakaiproject/oauth/tool/admin/pages/ConsumerAdministration.html, oauth/tool/src/resources/org/sakaiproject/oauth/tool/admin/pages/ListConsumers.html, oauth/tool/src/resources/org/sakaiproject/oauth/tool/pages/SakaiPage.html
Greetings;
I have been working on creating styles for this tool.
I will write down the tasks performed.
In the first place I have eliminated the console error that was produced when trying to load a non-existent file "style.css".
Second, I have formatted the tool's tabs for easier navigation.
And thirdly, I have created styles for the "Add a consumer" view.
I have followed the style of the "Admin Site Perms" tool as it was similar.
The new "css" are in a new file included in the "Library" module; the file is called "_oauthadmin.scss".
Regarding other changes that imply tasks, not styling, in the logic of this tool, another tour ticket can be opened.
Any comment and opinion for improvement will be well received.
Thank you very much.
=> SAK-43909 Update oAuth admin styling and rights

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java
The way it's being saved right now, the value can't ever be null. But if it is false with no discount, then it means no option was selected (or the discount would have no effect).
I researched a bit about the possibility of storing an actual null but it could create regression errors and I feel it doesn't make sense for such a specific case.
=> SAK-44280 T&Qs : Fix MCSC default settings on edit

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
https://jira.sakaiproject.org/browse/SAK-42265
There's no warning about the implications of deleting a Draft quiz, namely, that you can't duplicate/export/reuse published copies.
=> SAK-42265 samigo > improve text of warning confirmation when deleting quizzes

portal/portal-util/util/src/java/org/sakaiproject/portal/util/URLUtils.java
A lot of error 500 on the log when session timeout related to message of the day because Request is null
=> SAK-44578: Error 500 when session timeout

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/AssignmentEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties, lessonbuilder/tool/src/resources/messages_ar.properties, lessonbuilder/tool/src/resources/messages_de_DE.properties, lessonbuilder/tool/src/resources/messages_fr_FR.properties
https://jira.sakaiproject.org/browse/SAK-42266
If an instructor links an assignment into a lesson, but the assignment is not yet open, the link is grey. There is only a hover tool-tip which says "Item is not available", which can easily be missed or not discovered at all.
Let's add the open date in parenthesis beside the assignment title if it's not open for submission, so that the student quickly understands why they can't click the link.
=> SAK-42266 lessons > add open date to assignment links which are not yet open

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
https://jira.sakaiproject.org/browse/SAK-44530
Problem: If a student doesn't fill some answers on a calculated question, later the matching of student's answers with right answers is wrong
Solution: We need add that blank answers to do a right matching.
=> SAK-44530: SAMIGO - Error on points on calculated question when a student doesn't fill some answer

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ConfirmedFriends.html
https://jira.sakaiproject.org/browse/SAK-44563
Following the instructions in jira I've removed the "Create worksite" button for any user.
=> SAK-44563 Profile: "Create Worksite" button should not appear

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java, kernel/kernel-impl/src/main/webapp/WEB-INF/authz-components.xml
https://jira.sakaiproject.org/browse/SAK-44598
Question for @smarquard : is there a use case for not promoting a user to their proper CMAPI role?
=> SAK-44598 allow promotion of users to provided despite role matching

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://jira.sakaiproject.org/browse/SAK-41500
Group awareness within Lessons for embedded calendars does not work.
To replicate:
Create a site with Lessons and Calendar
Create a group in the site
Within Lessons, embed the calendar
Edit the calendar item and select the option to release it to group and save
Edit the calendar item again and you'll see the group option is no longer checked.
Logging in and viewing the Lesson as someone not in the group will still show the embedded calendar.
=> SAK-41500 - Lessons - group awareness not working for calendar items

providers/component/src/webapp/WEB-INF/unboundid-ldap.xml, providers/unboundid/src/java/org/sakaiproject/unboundid/UnboundidDirectoryProvider.java
https://jira.sakaiproject.org/browse/SAK-44657
When a user is deleted in LDAP/AD and not also cleaned up in the Sakai database, Sakai will constantly ask the LDAP provider(s) for the deleted user. It cannot be cached normally, because LDAP doesn't return the user details and thus a `User` object cannot be created for storage in the cache.
This can present performance problems on your LDAP server(s) (and consequently may slow down your Sakai nodes) if Sakai is querying constantly for either a lot of deleted users, or the same deleted users repeatedly. In one such instance, our Sakai instance was bombarding our LDAP server with over 75,000 requests per hour.
One solution to this is that when a user record is deleted in LDAP/AD, it must also be cleaned up in Sakai. However, this may not be …
=> SAK-44657 providers > add negative cache

providers/component/src/webapp/WEB-INF/jldap-beans.xml, providers/jldap/src/java/edu/amc/sakai/user/JLDAPDirectoryProvider.java, providers/jldap/src/test/edu/amc/sakai/user/JLDAPDirectoryProviderTest.java
https://jira.sakaiproject.org/browse/SAK-44657
This is for 20.x exclusively, as JLDAP was removed in 21. See #8802 for more details.
=> SAK-44657 providers > add negative cache (20.x JLDAP)

lessonbuilder/tool/src/webapp/js/commentGrading.js, lessonbuilder/tool/src/webapp/js/comments.js, lessonbuilder/tool/src/webapp/js/commonGrading.js, lessonbuilder/tool/src/webapp/js/questionGrading.js, lessonbuilder/tool/src/webapp/templates/CommentGradingPane.html, lessonbuilder/tool/src/webapp/templates/QuestionGradingPane.html, lessonbuilder/tool/src/webapp/templates/ShowPage.html
https://jira.sakaiproject.org/browse/SAK-37763
If there are numerous students in the site, only the first and last student grades are updated when pressing "Update Points".
The root cause of the issue is that multiple RSF AJAX calls are being made at the same time and after the first one, the rest get queued. However, the queue can only hold one item so any additional requests added to it will overwrite the previous one. This results in only the first and last requests being sent to the server.
This issue was identified and fixed for comment grading many years ago. Because the logic for doing grading was copied and pasted between the comment grading and question grading, the problem existed in two places but was only fixed in one.
This PR applies the comment grading fix to the question …
=> SAK-37763 Update points in grading pane of lessons tool

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
https://jira.sakaiproject.org/browse/SAK-44674
Steps to reproduce not identified. We saw an instance in our production environment where an item on a student page had a non-null, blank string (" ") for the width field. Given the following code, it presents opportunities for a `NumberFormatException` when parsing the blank String to a `Double`.
```
String widthSt = i.getWidth();
Length width = null;
if (mmDisplayType == null && simplePageBean.isImageType(i)) {
// a wide default for images would produce completely wrong effect
if (widthSt != null && !widthSt.equals("")) 
width = new Length(widthSt);
} else if (widthSt == null || widthSt.equals("")) {
width = new Length(DEFAULT_WIDTH);
} else {
width = new Length(widthSt);
}
...
...
...
Double h = new Double(width.getOld()) * 0.75;
``` …
=> SAK-44674 lessons > non-null, blank width or height causes Fatal Internal Error on student pages

reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java
It is not used anywhere in the code and the "accountvalidation.validated" event makes it redundant anyway.
=> SAK-44672 Remove unused user property

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
After revise the issue carefully, I think that this a typo, a minor error. There's no other mention to sakai.announement in the project, but many to sakai.announcements.
Thank you.
=> SAK-44027 default.sakai.properties help.hide typo

rubrics/api/src/main/bundle/rubrics.properties, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Evaluation.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/EvaluationStatus.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/repository/EvaluationRepository.java, webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-comment.js
https://jira.sakaiproject.org/browse/SAK-42371
Adding these stati means we can use the evaluation backend as the
cache for the evaluation as we switch between tools and their helpers.
=> SAK-42371 Added DRAFT and RETURNED status to rubric evaluation

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/readers/CSVReader.java
I'm leaving this as a draft at the moment because I don't love the calls to `getTimeService()` and I also don't love having to use this syntax. This appears to fix the bug though.
I believe the typical intention of an import and also `newTimeRange `is to not have the end time included in the range. It's possible the other imports may also have this problem. 
IcalendarReader, OutlokReader and MeetingMakerReader all use the same version of `newTimeRange`.
=> SAK-43378 - Fix CSV reader so event end times are not included

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://jira.sakaiproject.org/browse/SAK-43044
"A student sent an email to an instructor where the subject appeared blank. Since there was no text in the subject line, the instructor could not open and read the message. I was able to reproduce this by having a space in the subject line. That appeared to count as "not blank" for the subject check, but can't be clicked on by the recipient."
User input should be trimmed when entering the system, as this prevents various issues that could occur later on, including the problem above. This PR trims the input for subject and message body using the setters that JSF calls when mapping the input field values from HTML back to Java.
This PR also cleans up the reply all page, as it was actually using variables for the forward page instead of its own …
=> SAK-43044 Messages can be sent, can't be read, with single space in subject

kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml, kernel/kernel-impl/src/main/resources/antisamy/low-security-policy.xml
The paragraph regexp is too complex for long img alt text which includes linebreaks. This uses a simpler regexp for alt text.
However, I'm not totally sure whether it's ok to simplify to this extent and this should be reviewed to see if there's anything that actually should not be permitted in alt text, in which case an intermediate regexp may be required that's simpler than paragraph but more complex than anyWithPara.
=> SAK-44702 Long img alt text with linebreaks can cause StackOverflowError

site-manage/datemanager/tool/src/main/java/org/sakaiproject/datemanager/ThymeleafConfig.java, site-manage/datemanager/tool/src/main/java/org/sakaiproject/datemanager/tool/MainController.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/config/ThymeleafConfig.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/MainController.java
When the applications with Thymeleaf DateManager and GroupManager were initialized when the server was started, they took the default language of the platform, of the operating system of the machine. So, what I have done is to allow that when the entry point of these two applications is accessed, the language of the user session indicated in preferences is taken. This way it works properly.
I do the pull request with the changes.
Please merge with Sakai 21.x and 20.x.
Thank you.
=> SAK-44353 Group Manager and Date Manager do not change idiom

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
Use CKEditor's "startupFocus" property to put the cursor in the editor when it loads. There is a caveat to this property, as it places the cursor at the beginning of the text even if there is already text in the editor. There is an option to put the cursor at the end by setting startupFocus = "end" instead of "true", but this causes unwanted behaviour in Firefox (such as inserting blank lines at the beginning of the text and scrolling it offscreen), and it does not appear to work at all in Chromium.
=> SAK-44573 When adding comments to a rubric, automatically set focus to text box

samigo/samigo-services/pom.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
commons-text not deployed to lib/ .... so just use older StringEscapeUtils for now *only* in 19.x
=> SAK-44579 fix dependency because commons-text not in 19.x/lib

msgcntr/messageforums-app/src/webapp/js/forum.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp
This PR addresses two problems:
1. Forums sets the student on the saved rubric based on the message author of the currently selected message. When grading by topic, there is no selected message so the student is not set.
2. In Firefox, the event handler to save the rubric is called when the button is clicked, but the PATCH request never makes to the server. I'm unsure why this doesn't work, but adding the save call to the onclick attribute of the button does work. I did try removing the onclick attribute entirely but that still did not allow the event handler to function properly.
=> SAK-44400 Students can't view graded forum rubric in Gradebook

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties
https://jira.sakaiproject.org/browse/SAK-44754
If a Student Content item is added to a page and configured to be for groups instead of individual users, adding content for that group and then deleting the group results in a NPE that renders the entire page containing the student content tool inaccessible.
The fix for this issue will check for null groups and present a message to the user indicating the group no longer exists, while retaining access any content from the deleted group (the instructor may chose to delete the content later if this is desired). The following additional changes are made for consistency:
- deleted users will also now present a message indicating such
- page titles that match the name of the page owner will no longer be surrounded by parentheses (ie. a student …
=> SAK-44754 Lessons > Fix NPE on student content when group is deleted and related improvements

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-44767
If you delete an assignment, then go to Trash and restore or permanently remove the assignment, the sort order when you return to the assignment list is alphabetical which differs from the default order (i.e. sorted by due dates, etc.).
=> SAK-44767 Sort order is alphabetical after restoring or permanently deleting an assignment

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-44640
If an instructor deletes an assignment connected to Gradebook tool with submissions and released grades and then restores it, the related item in Gradebook does not reappear.
=> SAK-44640 assignments > recreate gradebook item when restoring assignment from trash

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
https://jira.sakaiproject.org/browse/SAK-44770
f you set a custom tool title via Site Info > Tool Order, then view the page settings in the Lessons tool itself, the Lessons modal does not reflect the new tool title set in Tool Order. It instead displays the original name, stored in the Lessons Page object. This can lead to user data loss opportunities, if the user saved the modal without realizing that they're actually reverting the tool title.
=> SAK-44770 lessons > page settings does not reflect custom tool title from ToolConfiguration

library/src/morpheus-master/sass/_defaults.scss, library/src/morpheus-master/sass/base/_defaults.scss, library/src/morpheus-master/sass/modules/connection-manager/_base.scss, library/src/morpheus-master/sass/modules/editor/_base.scss, library/src/morpheus-master/sass/properties.scss, library/src/morpheus-master/sass/themes/_custom.scss, library/src/morpheus-master/sass/themes/_dark.scss, library/src/webapp-filtered/editor/ckeditor.css, library/src/webapp-filtered/editor/ckeditor.launch.js, library/src/webapp/editor/ckextraplugins/sakaipreview/plugin.js, library/src/webapp/editor/ckextraplugins/templates/default.js, portal/editor-tool/tool/src/java/org/sakaiproject/editor/EditorServlet.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-util/util/src/java/org/sakaiproject/portal/util/CSSUtils.java
https://jira.sakaiproject.org/browse/SAK-44562 - several screenshots included on the JIRA
This enables dark theme support in ckeditor, but what it **also** does is set ckeditor to inherit the theme variables set in light mode as well. Overall, CKeditor fits in with Sakai's ui more closely and adapts to the themes set in the skin.
A new `skinname/properties.css` file is now generated from `library/src/morpheus-master/sass/properties.scss` which can be used by CKeditor or other parts of the app. It only contains the css custom properties and not the entire skin in an effort to reduce potential conflicts and download size.
`library/src/webapp-filtered/editor/ckeditor.css` contains CSS that affects HTML written by ckeditor or the user.
The `CKEDITOR.skin.chameleon` function is included in our …
=> SAK-44562 library / portal - ckeditor support dark theme

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_view_assignment.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-44778
When an assignment is released to selected groups, the groups are listed on the main assignments page. They used to be sorted alphabetically, they no longer are.
Regarding sorting outside of the stream operations, the compiler doesn't like the type of the AssignmentComparator so it doesn't allow the sort in the stream itself, so I had to do it separately.
=> SAK-44778 Regression: Assignment List > Selected Groups no longer sorted

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/js/authoring-emi.js
https://jira.sakaiproject.org/browse/SAK-44781
There are some remaining usages of the class `messageSamigo` for extended matching items. Lets replace them with the standardized `sak-banner-error`.
=> SAK-44781 samigo > remove uses of messageSamigo class in favour of standardized sak-banner-error

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
https://jira.sakaiproject.org/browse/SAK-44782
The "New Forum" UI does not have a primary action button. Make the "Save" button the primary action.
=> SAK-44782 forums > new forum > add primary action button

library/src/morpheus-master/sass/base/_extendables.scss, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
https://jira.sakaiproject.org/browse/SAK-44783
When editing a Joinable Set there are 2 primary action buttons present in the UI. There should only be one primary action for a given form.
=> SAK-44783 site info > manage groups > edit joinable set > only 1 primary action button per form

kernel/api/src/main/java/org/sakaiproject/user/api/PreferencesService.java, library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, library/src/morpheus-master/sass/base/_extendables.scss, library/src/morpheus-master/sass/modules/navigation/_base.scss, library/src/morpheus-master/sass/modules/theme-switcher/_base.scss, library/src/morpheus-master/sass/themes/_dark.scss, library/src/webapp-filtered/editor/ckeditor.launch.js, library/src/webapp/editor/ckextraplugins/sakaipreview/plugin.js, login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm, portal/portal-charon/charon/src/webapp/scripts/themeswitcher.js, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-render-engine-impl/impl/src/test/org/sakaiproject/portal/charon/test/MockCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/join.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/login.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/portalCSS-snippet.vm
https://jira.sakaiproject.org/browse/SAK-44447
The dark theme preference is now saved as a user preference. If the user preference doesn't exist yet or the user isn't logged in, we check for OS theme preference. If that doesn't exist, we default to light mode for Sakai. 
Also cleaned up some unneeded code. 
Still a work in progress.
=> SAK-44447 Save dark theme to server with user pref plus detect OS theme

library/src/webapp/editor/ckextraplugins/sakaipreview/plugin.js
This had a few fixes here to the Javascript.
First I changed the preview both selection and non to return HTML. editable().getHtml() looked to work better.
Then I had to change the iframe to use the html5 srcdoc instead of the encoded src string. T[his is supported by all modern browsers.](https://caniuse.com/iframe-srcdoc). src had length and other limitations that made this really not work well with this already long text.
=> SAK-44839 - CKEditor 4 preview can't handle apostrophes or HTML

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf, samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://jira.sakaiproject.org/browse/SAK-44798
* Added consistent spacing between labels and inputs on the Samigo Settings page
* Fixed labels that weren't linked properly to their inputs
=> SAK-44798 Fixed spacing and linking between inputs and labels in Samigo settings

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://jira.sakaiproject.org/browse/SAK-44873
See the ticket for full description of the issues.
Regarding the change to the .vm:
Here is the original from Sakai 11 where the message would appear:
```
#if( $siteRelease )
$tlang.getString("gen.viewallgroupssections")
#elseif( $groupTitleList.size() > 0 )
```
And in Sakai 12+:
```
#if($assignment.TypeOfAccess == "SITE")
$tlang.getString("gen.viewallgroupssections")
#elseif($assignment.TypeOfAccess == "GROUP")
```
Following these is an #else that displays the warning message.
The new #elseif might look equivalent to the old one, but it is not, and as a result the #else is now unreachable.
=> SAK-44873 Multiple issues with assignments released to deleted groups

library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-43868
Also removes the expand/collapse animation because it becomes slow and choppy as the amount of data in the groups table grows
=> SAK-43868 Site Info - Groups: Triangle beside locked tool does not change for expand/collapse

jobscheduler/scheduler-test-component/src/webapp/WEB-INF/components.xml
Was just using the wrong resource bundle for this bean.
=> SAK-44898 - Configurable job name and description not being translated

.github/workflows/maven.yml, kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTestConfiguration.java
@ern looks like 0170595cf4f48413922dffe26bdb04410c1bb359 broke the TaskServiceTest. 
I researched this a bit.
* Added the missing beans in the `TaskServiceTestConfiguration` that were recently added
Then it was still failing so
* I switched the assertion to use `assertEquals `to display what was actually failing and improved some of the messages.
But it was still showing the old value. I noticed there was a code change
https://github.com/sakaiproject/sakai/blob/df030150d6815c2c72a09d3f918632aa34b6fa71/kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java#L120
And this Test had
https://github.com/sakaiproject/sakai/blob/df030150d6815c2c72a09d3f918632aa34b6fa71/kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTest.java#L60
So I …
=> SAK-44805 - Fixing up TaskServiceTest

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/css/Simplepagetool.css, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html, library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Section and column break item id is needed in javascript to remove the
section or column. This was added to the href of the link but should instead
be added to a data attribute on the link.
=> SAK-44557 Remove section and column merge link id from href

lessonbuilder/tool/src/webapp/css/Simplepagetool.css, lessonbuilder/tool/src/webapp/css/checklist.css, lessonbuilder/tool/src/webapp/templates/Checklist.html, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Improve the styling of the name and description form fields in the
edit dialog and on the checklist page by adding spacing and making
them wider.
=> SAK-44905 Clean up name and description form field styling

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/detailed/refresolvers/LessonsReferenceResolver.java
https://jira.sakaiproject.org/browse/SAK-44939
Traversing Lessons Hierarchies needs to take into account hierarchies that maybe recursive.
Large strings have been noticed while analyzing the heap, see JIRA ticket.
=> SAK-44939 Sitestats User Activity and lessons pages that are recursive

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
When a mail is sent with the option "Send a copy to all recipients" checked, and the recipient has forwarded the emails to it's client, the recipient receives two copies.
=> SAK-44903: Mail duplication

library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
https://jira.sakaiproject.org/browse/SAK-44856
WIP: Will also try and remove some of the $manageTools-panel-border variables
=> SAK-44856 Dark theme background fix within Manage Tools

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradingEvent.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
When modifying the final grade of a user, it produces a null error in the "IS_EXCLUDED" field of the "GB_GRADING_EVENT_T" table in the ORACLE database.
=> SAK-44978: Error when modifying the final grades in ORACLE

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/AutowiringSpringBeanJobFactory.java, jobscheduler/scheduler-test-component-shared/pom.xml, jobscheduler/scheduler-test-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/TestConfigurableJob.java
The fix here seemed to be to disable dependency checking in the new method added in SAK-44246. I tested that SAK-44246 still passes fine with this.
Also changed the logging in Configurable Job Test to info, as I figured if someones actually running this test they'll want to see what it outputs.
=> SAK-44890 - Problem running Quartz job "Configurable Job Test"

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm, portal/portal-charon/charon/src/webapp/scripts/themeswitcher.js, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/DefaultSiteViewImpl.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm, user/user-tool-prefs/tool/src/bundle/user-tool-prefs.properties, user/user-tool-prefs/tool/src/bundle/user-tool-prefs_tr_TR.properties, user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java, user/user-tool-prefs/tool/src/webapp/prefs/theme.jsp, user/user-tool-prefs/tool/src/webapp/prefs/toolbar.jspf
https://jira.sakaiproject.org/browse/SAK-45006
This changes the controlling sakai.property of the dark theme to a generic "sakai.themes" property separate of the existing "sakai.theme.switcher", which just controls the dark theme toggle visibility in the account menu.
This new "sakai.themes" property controls whether the JavaScript is enabled, whether the Preferences tab exists, and whether themes will display. 
Themes are enabled by default, but the theme switcher in the account menu is disabled by default. 
This also removes the "Auto" option from the Preferences page, which doesn't work with the current theme implementation and intention. 
A new option to detect users' OS dark mode can be enabled using "portal.themes.autoDetectDark=true", which is disabled by default.
=> SAK-45006 Control dark theme with a property separate of the theme toggle

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, gradebookng/bundle/src/main/bundle/gradebookng.properties, webapi/pom.xml, webapi/src/main/java/org/sakaiproject/webapi/controllers/GradesController.java
https://jira.sakaiproject.org/browse/SAK-45039
This change results in the grades api endpoint asking assignments or
samigo for the number of submissions and graded, when the GB assignment
is externally maintained.
=> SAK-45039 Improve number of submission in grades widget

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js
I had this idea of just saving the original name as a data-* attribute. 
This seems to work as expected now. This also could have been another inside a hidden tag on the page. 
I left in a check to see if it was undefined and set it to the text default as I'm not 100% sure this is set on every page and will work, but might not be necessary.
=> SAK-45127 - Editing a link to an assignment in Lessons duplicates the open/close information in title

samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
Please merge. Sorry, I did a mistake when copying the patch from our instance to 22.x
=> SAK-45135: SAMIGO: Wrong question's order on instructor view when Continuous numbering between parts

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderAccessService.java, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
Explicitly set userdirectoryservice, usertimeservice, and authzgroupservice
in simplepagebean when accessed from lessonbuilderaccessservice to prevent
NPEs and returning a 404 when attempting to load the embedded image.
=> SAK-45119 Fix embedded images with prereqs not showing to students

library/src/morpheus-master/sass/base/_jquery-ui-defaults.scss
Changes light and dark mode sliders to use the button-primary styles.
https://jira.sakaiproject.org/browse/SAK-45183?filter=-1
=> SAK-45183 Library datepicker sliders contrast

feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java, feedback/src/webapp/WEB-INF/bootstrap.jsp
Simple fix to include Google's recaptcha script only if recaptcha is enabled and used.
https://jira.sakaiproject.org/browse/SAK-45315
=> SAK-45315 feedback-tool: don't load recaptcha script if disabled

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
Also fixes: SAK-43976 - Menu Navigation in Statistics & Grading (dfStatisticsListByTopic) is not working
Issue was that these needed to be in the form component and were outside of it.
=> SAK-43977 - Menu navigation in Topic is not working

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
For questions that missing on the XML this tag
```
<qtimetadatafield>
<fieldlabel>MARKERS_PAIR</fieldlabel>
<fieldentry>{}</fieldentry>
</qtimetadatafield>
```
=> SAK-34477: Get curly brackets as text in a Fill in the Blank

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/CCExport.java
Should be the same as V1.1: https://github.com/sakaiproject/sakai/blob/master/lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/CCExport.java#L522
=> SAK-45417: LESSONS: Deleting language=en-US from IMS V1.3

rwiki/rwiki-tool/tool/src/webapp/styles/wikiStyle.css
Screenshots for before and after are available on Jira: https://jira.sakaiproject.org/browse/SAK-45158
This doesn't fix all of the hardcoded values, but fixes dark mode readability for crucial components
=> SAK-45158 rWiki fixing background and text visibility in dark mode

library/src/morpheus-master/sass/base/_jquery-ui-defaults.scss
Not my preferred solution but I didn't want to rip out this specific icon and leave the rest failing contrast.
They were using url("images/ui-icons_777777_256x240.png").
=> SAK-45485 jquery-ui change background image to increase icon contrast 

lessonbuilder/tool/src/webapp/templates/ShowPage.html
[/lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java#L4245-L4245](https://github.com/profmikegreene/sakai/blob/6c209ab8b6c3d6d539342597ee8516c8c0d5926a/lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java#L4245-L4245) Also contains that icondrop id. Can that line be deleted as well?
=> SAK-45486 lessons replace more tools gif with font awesome

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
Move the check for allowing a new submission (finalising a draft submission) before the check for allowing a resubmission of a submitted submission.
Fixes regression from SAK-45336
=> SAK-45527 fix late submission check

roster2/tool/src/handlebars/members_cards.handlebars
Copying here the comment I added to the jira https://jira.sakaiproject.org/browse/SAK-45264:
I'd say there are a couple issues here. First there's a discrepancy between the permissions across the tool: on some places last visit and number of visits are tied to the same permission check (see RosterSiteEntityProvider), but on the page rendering side they aren't connected in that way. That means the value isn't filled but the field is shown.
And the second problem I find is the visit count is never displayed, even with the right permissions. I think I'm going to address both on one PR, but this might need some discussion.
=> SAK-45264 Roster: fix site visits visibility

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
https://jira.sakaiproject.org/browse/SAK-45370
Convert non-greedy regular expression pattern for a calculated question
calculation to possessive version to avoid backtracking that can cause
stackoverflow errors or CPU load that brings down the system.
=> SAK-45370 Update calc q regex to avoid catastrophic backtracking

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, content/content-tool/tool/src/java/org/sakaiproject/content/entityproviders/ContentEntityProvider.java, content/content-tool/tool/src/webapp/WEB-INF/applicationContext.xml, kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/entity/api/ResourceProperties.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, library/src/webapp-filtered/editor/ckeditor.launch.js, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
This adds a new endpoint that allows members of a site to upload a file
to resources whether or not they have permission to do so. Those without
permission will have their file sent to a folder called by default
student-uploads. Those with permission to add a resource will be have theirs
sent to instructor-uploads.
This endpoint is diabled by default and can be enabled by setting the sakai
property content.direct.upload.enabled=true. Additionally, the direct-upload
folder names can be overriden in sakai.properties.
This new endpoint integrates with the CKEditor to provide drag and drop embedding
and image upload capabilities.
=> SAK-44785 Add "direct-upload" endpoint to content entity provider

rubrics/api/src/main/bundle/rubrics.properties, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
When modifying graded rubric from adjust to default, scores and cells do not match. Issue a
warning informing the user.
=> SAK-41588 Show warning if switching from adjusted scores

content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_select.vm
I've tried to find out why it was added in the first place but not sure I understand it (see https://jira.sakaiproject.org/browse/SAK-13259)
=> SAK-44758 Remove empty column from filepicker

library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
I've added a margin between the label and input, defining its font-weight as normal, since the text in the searchbar appeared in bold (but not the outline).
I've applied these changes at the .scss as it is part of the DataTables plugin and I can't modify it.
=> SAK-43995 Messages: Quick Search box is inconsistent with Search for text box

content/content-tool/tool/src/java/org/sakaiproject/content/tool/ListItem.java
Collections like /content/user/ don't have associated contexts, so the siteId check was returning null rather than !admin.
Check for the number of path elements instead.
=> SAK-33610 Check for top-level content collections

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
I'm not really an expert on this... but it seems working.
Maybe with only setting the epsilon with a small number could be enough...
but Mariusz Gromada (Mathparser's creator) recommend us using
mXparser.disableUlpRounding() before the calculate call.
https://mathparser.org/probability-theory/why-this-formula-gives-approximation-of-e/
@austin48, pls, could you check this one? Thanks!
=> SAK-44703: Samigo calculated questions do not evaluate large E expressions correctly

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
https://jira.sakaiproject.org/browse/SAK-43746
Hi, everyone;
I have revised the issue and added an alert when the text os over 80 characters.
When the text is pasted or written and exceeds 80 characters, the banner appears and is hide when the character are less than 80:
"The short description text has been trimmed because has exceeded the maximum 80 characters."
Thank you.
=> SAK-43746 No warning message displays when an instructor enters a short description for a site with more than 80 characters

portal/portal-charon/charon/src/webapp/scripts/themeswitcher.js
I just protected the other darkThemeSwitcher's with a check. Not sure if you see a better way of handling this.
=> SAK-45639 - setAttribute error when dark theme switcher is disabled

edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/Gradebook.hbm.xml
This is paired with https://github.com/sakaiproject/sakai-reference/pull/121
=> SAK-44967 - Oracle: Column names should use less than 30 characters

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/FileConversionServiceImpl.java
I haven't tested, but does this seem correct?
Here is the call from Assignments for reference:
`contentHostingService.addAttachmentResource(resourceId, siteId, "Assignments", contentType, fileContentStream, props);`
=> SAK-45691 re-do the way FileConversionService creates attachment names

kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/test/java/org/sakaiproject/email/impl/test/EmailServiceTest.java, mailarchive/mailarchive-subetha/pom.xml, mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java, mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java
The version we're using is from
I tried to update to the latest 6.0.0 but it looks like they changed some dependencies on jakarta.mail and doesn't seem to be working with the version we have in master, so just went back a version. There was also an open PR for this so might not be completed.
[Data](https://github.com/davidmoten/subethasmtp/commit/a5376e0dc00779a4f436b04088e17a8e7ca74246) got changed to support a string value of the return. It only suggests returning "OK message received" or null which will just return 250 OK. So there might be better returns we can use here but it seemed to be working okay.
=> SAK-44938 - Update subetha in mailarchive to newer fork

library/src/morpheus-master/sass/modules/_toolmenu.scss
https://jira.sakaiproject.org/browse/SAK-44733
=> SAK-44733 LESSONS - Bad style on tool bar navigation if there are some subpages on lessons and subpage navigation is enable

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Solved this issue by removing the `placeholder` class, as it just overrides the `disabled` color with `color: var(--sakai-text-color-dimmed)`.
It had no effect in the _div_ that contains the checkbox.
=> SAK-45685 T&Q: Settings / Layout and Appearance - color text unmatched

syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/entityproviders/SyllabusEntityProvider.java, syllabus/syllabus-app/src/webapp/js/syllabus.js
Using a better way to get fckeditor content so it can be submitted.  The old way seemed to be getting additional markup that we don't want.
Also, there was an issue actually saving the new syllabus data.  Possibly related to changes that came in with SAK-44784?
=> SAK-45605 - fix syllabus ckeditor parsing and saving

sections/sections-app/src/webapp/inc/globalMessages.jspf
All the success banners affected have been upgraded to `sak-banner-success` through this single file. 
Jira: [SAK-45715](https://jira.sakaiproject.org/browse/SAK-45715)
=> SAK-45715 Section Info: Modify success banner style

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
https://jira.sakaiproject.org/browse/SAK-45224
We have 2.7.9 in our production instance from 3 months ago and no problems have been detected.
=> SAK-45224: Upgrading Mathjax to v.2.7.9

library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
This fake button is not accessibility-friendly and provides little value to sighted users. Just use your backspace key.
=> SAK-45728 remove clear filter button

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
Hi @csev, this is untested, I'm just looking for guidance. Is this where it should go? 
Schools like Duke, want to use this for LTI:
`custom_person_address_timezone=$Person.address.timezone`
=> SAK-45733 allow substitution of user timezone

library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss
Titles correctly aligned by removing the `<legend>` label.
=> SAK-41584 Fix text indentations on Site Info > Manage Access page

msgcntr/messageforums-app/src/webapp/css/msgcntr-qtip.css, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp
Hi, this is a small UI change
Instead of adding a back button, I opted to maintain consistency with Forums/Discussions and use the same tooltip behavior
Here is a preview:
---
=> SAK-45888 Messages: Viewing the sender's profile doesn't have a way to return to message aside from Back button

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Just a small change, that line was there since 2009.
It was causing the "flashy" behavior, where the page loaded with the checkbox activated and after that the js deselected it
Here is a GIF showing the bug
---
=> SAK-45826 When creating a new site, there is no longer a default selected

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswer.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverShortAnswerLink.jsp
samigo.studentRichText has been removed, so the current behaviour is always samigo.studentRichText=true
Removing property: Core team
https://jira.sakaiproject.org/browse/SAK-45453
https://github.com/sakaiproject/sakai/pull/9233/files
=> SAK-45453 Samigo remove samigo.studentRichText property

msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/menu/forumsMenu.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfFlatView.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfPendingMessages.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsList.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByAllTopics.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsUser.jsp
Replace occurecnces of Forums in breadcrumps with Discussions
I didn't just change the value of the propertue **cdfm_discussion_forums** because **cdfm_discussion** already exists and when all occurences of "Forums" are replaces this propertie can be deleted together with others.
=> SAK-45930: Discussions > Any Topic > "Forums" shows as breadcrumb

gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
https://jira.sakaiproject.org/browse/SAK-41655
This doesn't work because it is using the full student list in the original order to determine the prev/next students. This PR changes this so it uses the list of students as they are currently displayed.
=> SAK-41655 Gradebook: Sorting and filtering students distorts next/previous logic for Grade Summary

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeDeliveryService.java
https://jira.sakaiproject.org/browse/SAK-45993
If a quiz does not allow late submissions, is closed, yet has granted an extension to a student, that student will be able to take the quiz through the normal Samigo interface, but not through a direct URL. The student will instead receive a misleading "late submissions not allowed" error page.
Typically this will happen when the user is not logged in when they hit the URL. This is because an ExtendedTimeDeliveryService object is created before the current user is known, and not replaced after the user is known because the object already exists.  This PR makes sure the object is replaced if the user was unknown at the time.
=> SAK-45993 Samigo: Students receive late submissions not allowed message with extensions when taking quiz through URL

samigo/samigo-app/src/webapp/jsf/qti/chooseExportType.jsp
https://jira.sakaiproject.org/browse/SAK-45472
Make Content Packaging the default for selecting assessment export types and move it to the first place of the radio buttons
Also format the label as a label
=> SAK-45472: samigo: More intelligent default for export

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoLRSStatements.java
https://jira.sakaiproject.org/browse/SAK-45999
If you try to apply a negative score to students using either the "Adjustment" column for those with submissions, or the "Apply This Score" component for those without submissions, you'll notice a stack trace go through the logs and you'll be punted back to the assessment list UI.  Stack trace is like:
> Caused by: java.lang.IllegalArgumentException: score raw (-0.5) must not be less than min (0.0)
>         at org.sakaiproject.event.api.LearningResourceStoreService$LRS_Result.setRawScore(LearningResourceStoreService.java:947)
>         at org.sakaiproject.event.api.LearningResourceStoreService$LRS_Result.setScore(LearningResourceStoreService.java:975)
>         at org.sakaiproject.event.api.LearningResourceStoreService$LRS_Result.<init>(Learn …
=> SAK-45999 samigo > adjustment/'apply this score' functions throw stack trace with negative values

samigo/samigo-app/src/webapp/css/tool_sam.css
https://jira.sakaiproject.org/browse/SAK-45998
Edit a part and select random draw from pool. You are presented with some text fields to enter a number of questions to draw and the points values for these questions. The text fields are not wide enough to fully display more than about 3 characters. This presents a problem even if your points values are relatively small because they are rendered with decimal points when you go back to edit them. If you entered, for example "10" for the points value, you would only see "10." with a cut-off 0 after the decimal point. The fields should be resized to display 2 digits on either side of the decimal, so 5 characters in total. This should be enough to cover most realistic scenarios while still not looking too strange for single-digit values.
See …
=> SAK-45998 Samigo > Points values are cut off in the random draw from pool interface

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java
https://jira.sakaiproject.org/browse/SAK-46004
When an assessment is released to a specific group of students and a student who is not in that group accesses the assessment directly (typically, using a direct URL), the student will receive an "Access Denied" message. Getting this error message is not logged in the Event Log like other errors are (e.g. "Password Access Error"), but it would be helpful if it was.
=> SAK-46004 Samigo: Access Denied occurrences don't appear in Event Log

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
https://jira.sakaiproject.org/browse/SAK-46003
If a calculated question cannot be parsed, it can lead to an index out of bounds exception that can prevent students from taking the quiz and instructors for seeing the scores, even if only one question is affected, an there is no way for a user to figure out what the problem is. This happened to Western a few times during our upgrade from Sakai 11 to Sakai 20, because the underlying parser changed in Sakai 12 and some questions that were valid in 11 were no longer valid in 20.
To better handle this and allow students and instructors to still use the quiz to whatever degree remains possible, an error message can be substituted for the question text when it cannot be parsed. With this message, it is easy to identify the problem question(s) and …
=> SAK-46003 ArrayIndexOutOfBounds when calculated question cannot be parsed

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
https://jira.sakaiproject.org/browse/SAK-46002
If an assessment is released to multiple groups, and a user is in more than one of those groups, they are limited in the amount of times they are able to submit to the assessment, regardless of the amount listed. For example, if the quiz allows 2 submissions and the student is in more than one group the quiz is released to, they will only be able to take the quiz once.
What is happening is there is a query that counts your single submission once for each group that you are in due to the way it is joining tables. Essentially it joins sam_assessmentgrading_t to sam_authzdata_t on assessment id. If the quiz is released to multiple groups, that means there is a row in sam_authzdata_t for each group, and each group gets joined against the one …
=> SAK-46002 Assessment Attempts Are Limited When User is in Multiple Groups

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-45809
Assignment items created with a Resubmission quantity will seemingly reduce the quantity by -1.
As an example, instructors which create an assignment that allows for one resubmission might assume that students will have an opportunity to input an initial submission as well as one additional submission for a total of 2 submissions. Current behavior allows for only one in these circumstances.
Similarly, in assignments with 2 resubmissions, students are only provided with the initial submission + 1 resubmission.
--------------------
The code to decrement the resub count is being run on the first submission.
The problem lies with this if statement:
`if (submission.getSubmitted() && submission.getDateSubmitted() != null)`
dateSubmitted is always …
=> SAK-45809 Resubmission count always -1 from expected

samigo/samigo-app/src/webapp/js/questionProgress.js, samigo/samigo-app/src/webapp/jsf/delivery/assessmentDeliveryHeading.jsp
https://jira.sakaiproject.org/browse/SAK-44845
Easy to trigger DD error by getting click-happy on the ToC and Show Feedback tabs.
Using the same method Sam did in SAK-44248 is not appropriate here, as it blocks the transfer to the TOC page and displays a pop-up message saying "use the next links..."
Instead, I created a new JavaScript method that simply disables the link and sets pointerEvents to none so that it cannot receive further clicks after the first one.
=> SAK-44845 samigo > ToC and Show Feedback tabs give opportunity to trigger data discrepancy error

kernel/kernel-impl/src/main/webapp/WEB-INF/db-components.xml, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://jira.sakaiproject.org/browse/SAK-45997
We discovered this while investigating a support inquiry where a student had 2 submissions to a quiz that was set to record the highest attempted score. In one of the student's attempt, the `submitteddate` and the `finalscore` were both `NULL`. In an Oracle environment this forced the `NULL` score to the top of the query, so that in effect the student got a zero for the quiz instead of their original non-zero attempt.
According to my research:
> Oracle treats NULLs the same way as PostgreSQL. Specifically, Oracle's documentation states that "if the null ordering is not specified, then the handling of the null values is NULLS LAST if the sort is ASC, NULLS FIRST if the sort is DESC." In effect, Oracle considers NULL values larger than any …
=> SAK-45997 Oracle and MySQL treat null differently when ORDER BY used

samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp, samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp
https://jira.sakaiproject.org/browse/SAK-46012
When using the random draw from pool option in a quiz, the questions are supposed to all have the same value. For most question types, the points value is locked down, but for calculated and matrix of choices questions, it can be edited. This should not be possible.
This PR adds the disabled condition to these question types to match the rest of the types.
=> SAK-46012 Points for calculated and matrix questions can be changed if drawn from pool

site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-46007
Used the same approach as in other areas to deal with lessons cyclical hierarchy: keep track of the item IDs we see and bail if we encounter one we've already processed.
=> SAK-46007 stackoverflow caused by DateManagerServiceImpl.addAllSubpages

content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
https://jira.sakaiproject.org/browse/SAK-46015
The following have been preserved as INFO:
* `log.info("Turnitin report queue run completed: " + success + " items submitted, " + errors + " errors.");`
* `log.info("Turnitin submission queue completed: " + success + " items submitted, " + errors + " errors.");`
* `log.info("Turnitin webhook received: " + success + " items processed, " + errors + " errors.");`
All other current INFO level debug messages were changed to ERROR or DEBUG as appropriate.
Also took the opportunity to update to modern logger style without string concatenation, and some diamond operators along the way.
=> SAK-46015 TII webhook logging too verbose

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
We're applying the changes at gradeRecord level because that's where the dropped status is checked, plus in case categories are turned on again it would pick up from where it was in a straightforward way.
Also I had to set the "Object" parameter (just as the method before it), as Gradebook is in the hibernate package while the service is in the api.
=> SAK-45720 Gradebook: category drop settings remain applied

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/questionpool/QuestionPoolServiceAPI.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ImportQuestionsToAuthoringFromSearch.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemRemoveListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/entity/impl/ItemEntityProviderImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/questionpool/QuestionPoolServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-46011
When you try to access a question pool item there's a stacktrace being thrown. In fact, creation generates an exception too, but the item is created in the pool:
`org.sakaiproject.tool.assessment.services.QuestionPoolService.getPoolIdsByItem Parameter value [11] did not match expected type [java.lang.Long (n/a)]`
The problem is that at some point in time the database column in question was a varchar, and now it's a number, but the application code was never updated, still using Strings everywhere. This then surfaced as an issue when setString() was changed to setParameter() in SAK-45813. I'm guessing setString() used to do some internal conversion, because it worked fine when I changed it back locally.
While we could just do a quick …
=> SAK-46011 Samigo : can't navigate question pool items

kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java, kernel/api/src/main/java/org/sakaiproject/site/cover/SiteService.java, kernel/api/src/main/java/org/sakaiproject/tool/api/ToolManager.java, kernel/api/src/main/java/org/sakaiproject/tool/cover/ToolManager.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tool/impl/ToolComponent.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MenuBuilder.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/event/EventRegistryServiceImpl.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/SiteStatsTestConfiguration.java, sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
https://jira.sakaiproject.org/browse/SAK-46016
If you deselect the "Only list tools available in this site" option in Preferences, all the tools in the system will be shown, including stealthed tools.
This PR introduces 2 new service methods, one of which was lifted out of `SiteAction`.
=> SAK-46016 statistics reveals the existence of stealthed tools

samigo/samigo-app/src/webapp/jsf/delivery/passwordAccessError.jsp
https://jira.sakaiproject.org/browse/SAK-46018
When a student enters the wrong password for a quiz they are taken to an error page with a Return button. This returns them to either the quiz list (if taken through Samigo), or their Home site (if taken via URL). Intuitively, the "Return" button should return them to the previous page so they can try entering the password in again.
=> SAK-46018 Samigo wrong password page returns student to Home rather than assessment Begin page

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/webapp/jsf/delivery/discrepancyInData.jsp
https://jira.sakaiproject.org/browse/SAK-46005
The "Return" button/link found at the bottom of the Data Discrepancy page uses a generic message key. If we were to customize this through MBM, we would affect all of the other cases of that key in Samigo. Since the DD page has unique keys for the rest of its text, make the following keys for the "Return" link (pub.ass.url) and button (Tests & Quizzes):
* data_discrepancy_button: "Return to assessment list"
* data_discrepancy_link: "Return to assessment"
=> SAK-46005 samigo > make data discrepancy 'return' link/button text configurable

rubrics/api/src/main/java/org/sakaiproject/rubrics/logic/model/Criterion.java
https://jira.sakaiproject.org/browse/SAK-45940
Currently, criterions are cloned even if its sum of weights is greater than 100, saving this in database. Now, the cloned criterion's weight is set to zero.
=> SAK-45940 RUBRICS: You can save a weighted rubric with more than one criterion with 100%

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-editToolGroupFeatures.vm
https://jira.sakaiproject.org/browse/SAK-41363
The "Re-use material..." feature has many issues, most of which have never been addressed. According to T&L, this feature is rarely used and even more rarely is it recommended to be used. T&L supports removing this feature entirely.
At Western, we have already removed this feature. The linked PR introduces a message displaying at the top of the page where the component used to live:
> Please use the Site Import page in Site Info to import content from existing sites once this site has been created.
This message can likely be removed after a few major versions have been released.
=> SAK-41363 remove 're-use material...' from site creation process

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties
https://jira.sakaiproject.org/browse/SAK-46027
As an admin when hard deleting you are presented with the following warning:
> Deleting a site removes the entire site's content and is not recoverable - no one else will be able to access the deleted site. If you are trying to remove yourself from the site, use the Membership tool in your Home to unjoin the site.
> 
> NOTE: You chose Hard Delete so these sites will have their tool content purged from the system.
The information about removing yourself from the site should also be presented to the maintainer when they elect to softly delete a site. Currently, they see the following message:
> This site will be 'softly deleted' but will remain accessible to you via the "View softly deleted Sites" option in the Worksite Setup tool which is …
=> SAK-46027 soft delete warning does not provide info on how to remove yourself from the site

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
https://jira.sakaiproject.org/browse/SAK-46028
The UI to select rosters has a sorting issue: the sections within each set are sorted, but the sets themselves are not. Instead, they appear in the order they are retrieved from the database. Example screenshot can be seen on the JIRA ticket.
This PR sorts the sets alphabetically. It also addresses an issue in the Add Roster UI, where the drop down produces two spinners (one on the drop down itself, and one beside it), by retaining only the overlay spinner.
=> SAK-46028 site info > sort section sets alphabetically

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties
https://jira.sakaiproject.org/browse/SAK-46029
Instructors at our institution have found the random draw from pool settings to be somewhat unclear. The following change addresses these concerns:
"Correct answers are worth ___ point(s)" becomes "Drawn questions are scored out of ___ point(s). This overrides the original pool setting and cannot be changed once published."
=> SAK-46029 Additional/Improved wording warning when using QP random draw in quizzes

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/js/saveForm.js, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
https://jira.sakaiproject.org/browse/SAK-46026
Currently when an autosave happens, the buttons are momentarily disable but there is no explanation. To make things more obvious, add messaging to indicate when autosave is happening and display the last autosave time.
=> SAK-46026 Indicate when Samigo Autosave is happening

user/user-tool-prefs/tool/src/webapp/prefs/editor.jsp
https://jira.sakaiproject.org/browse/SAK-46044
This is a bug, introduced in SAK-33240.
SAK-23895 created a new sakai.property (preference.show.tab.label.option), which exposes a setting in Preferences to allow users to display the tab text as either the site title or the site short description.
At Western, we do not want users to be able to switch this setting (we only want them seeing the site/roster title as the tab text), so we set this sakai.property explicitly to false.
SAK-33240 then introduced a new UI in Preferences for the CKEditor. For some reason, this UI makes use of conditionals on elements which use the boolean value of what amounts to be an unrelated sakai.property (the one from above that defaults to true and we set to false explicitly).
So this ended up passing QA because …
=> SAK-46044 preferences > editor > no options, just update and cancel buttons

reset-pass/account-validator-impl/src/bundle/validate_requestAccount.xml
https://jira.sakaiproject.org/browse/SAK-46042
account-validator-impl/src/bundle/validate_requestAccount.xml has no indication of the user's eid.
Added `<version>2</version>` in the hopes that like our institution, the version in your database is "1", so this will cause the email template to be updated automatically.
=> SAK-46042 request account's email should indicate the user's login id

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/EnrolmentsHandler.java, site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_enrolments.vm
https://jira.sakaiproject.org/browse/SAK-46050
When a roster is used in multiple sites, My Official Course Enrolments lists each. However, the links are squished together, and appear as one giant link. In fact they are distinct, but could use some better spacing.
This PR employs an unordered list if the roster is attached to more than one site, and also sorts the sites alphabetically.
Before and after screenshots attached to the JIRA ticket.
=> SAK-46050 membership > enrolments > rosters attached to multiple sites get squished together

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/JoinableSiteSettings.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/MembershipAction.java
https://jira.sakaiproject.org/browse/SAK-46055
If you are an inactive member of a joinable site, that site will still appear in the list of Joinable Sites in the Membership tool. If you try to join the site from this UI, the page simply refreshes and it looks as if nothing happened.
The user is already a member of this site, but marked as inactive, therefore you cannot join the site again.
Joinable Sites should not display any sites where the user is an inactive member.
=> SAK-46055 membership > joinable sites > filter out sites where user is an inactive member

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-46053
Create a new assignment that will be sent to the gradebook. Save as Draft. Edit the draft assignment, notice that your gradebook settings are not saved.
This happens because the gradebook integration settings were only being saved when posting the assignment due to the if (post) statement around the entire block.
=> SAK-46053 Assignments > Save Draft Doesn't Save Grading Options

library/src/webapp/js/lang-datepicker/lang-datepicker.js
https://jira.sakaiproject.org/browse/SAK-46052
The date picker doesn't appear when creating a Tests & Quizzes assessment through Lessons. Since dates are required field, you are unable to create an assessment through Lessons, unless you type the date format into the input field correctly.
The issue is that when embedded in the Lessons iframe, Samigo doesn't have direct access to the portal object and therefore lang-datepicker.js can't find it.
=> SAK-46052 Difficulty creating a quiz through Lessons

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemConfigBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
https://jira.sakaiproject.org/browse/SAK-46039
When you are editing a question, you can change the question type using the dropdown menu, which contains "select a question type". This triggers a validation error on the page.
There is no reason to include this option when editing an existing question, so it should be removed.
Similarly, when adding a question to a question pool, there is an intermediate page to choose a question type that starts with "select a question type" selected. Since in this case, unlike on the main assessment page, selecting a question type does not trigger any further action, there is no reason to start this form in an invalid state. Instead, it should default to the most common question type, Multiple Choice.
=> SAK-46039 Changing item type to 'select a question type' when editing a question triggers error

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
https://jira.sakaiproject.org/browse/SAK-46056
If you take specific actions within Manage Access, you can produce a valid state that does not enable the Continue/Update button. This affects both existing sites and the site creation wizard.
For example:
* during the site creation process on the Manage Access page, "Allow any Sakai user to join the site"
* limit join to specific accounts
* don't select any account types
* switch to "Limit to official course members or to those I add manually (recommended)" under "Global Access"
* observe: you have provided valid options, but the Continue button remains disabled
This also happens if you switch "Publish Site (accessible by all participants)" to Draft mode for step 4.
=> SAK-46056 site info > manage access > specific workflows do not enable Continue button when they should

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ar.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_ca.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_de_DE.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_es.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_fr_FR.properties, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric_tr_TR.properties, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
https://jira.sakaiproject.org/browse/SAK-46025
This message has been present for 3 major versions: 19, 20, and 21. This is ample time for people to get used to the new location of the manage participants list, so lets remove this text for 22.
=> SAK-46025 remove info text from 19 about manage participants being moved

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/SelectIndexMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
https://jira.sakaiproject.org/browse/SAK-46049
If an instructor makes a change such as giving the entire class another retake, the student gets the following message:
"This assessment has been modified since you submitted it. Please consult your instructor if you find any discrepancies." (as a legend at the button of their submission list, to explain the icon next to the quiz that was modified).
But if the student retakes the assessment, the message continues to display to them. Visibility of the legend should be conditional so that if there are no marked quizzes, it does not appear.
Additionally, the part "since you submitted it" is not technically accurate. Quizzes are marked as modified if the modificaiton was after the submission with the recorded score, not just the most recent …
=> SAK-46049 'This assessment has been modified' message doesn't go away

site-manage/site-group-manager/src/main/resources/Messages.properties, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-46058
Users are routinely confused by the intention and purpose of locked groups, and we've had several support inquiries related to this. We were requested to update the information provided in Manage Groups to better explain the current state of group locking and how it interacts with certain tools.
The linked PR introduces some new information for the legend, as well as improving some a11y pieces around the lock icons, etc.
This may need to be expanded in the future as more tools utilize group locking, and more types of group locking are employed (currently there are 4 supported locking modes, but only 2 of them are actually utilized).
=> SAK-46058: improved language for locked groups

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
https://jira.sakaiproject.org/browse/SAK-46075
Currently if you provide a file which is over the hard coded 2MB limit for uploading in GBNG, nothing happens: the button is not enabled, there's no error on the UI, and you'll see the following in the logs:
> 8-Apr-2020 16:04:26.985 WARN [https-jsse-nio-8443-exec-1] org.sakaiproject.util.ResourceLoader.getString bundle 'org.sakaiproject.gradebookng.GradebookNgApplication'  missing key: 'form.uploadTooLarge'  from: org.sakaiproject.gradebookng.framework.GradebookNgStringResourceLoader.loadString(GradebookNgStringResourceLoader.java:46)
This PR introduces proper error messaging for this condition, as well as providing configuration for the maximum upload file size.
New property: `gradebook.import.maxSize` which defaults to 2 megabytes
=> SAK-46075 GBNG > import > no error message when uploading file that exceeds max allowed size

webcomponents/tool/src/main/frontend/js/forums/sakai-forums.js
This is the property used by the original synoptic component where all the other properties were taken from
=> SAK-45980 Dashboard: Hide on Discussions is hardcoded

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-45995
Issues:
* 'Hide this category' on a partially shown category will actually 'Show this category'
* 'Hide this category' menu item never gets updated
* 'Show All'/'Hide All' does not update menu items
These issues are related to the fact that there's only one algorithm to do the hide/show, and it's a toggle:
```
on("click", ".gb-toggle-this-category", function(event) {
event.preventDefault();
var $filter = $(event.target).closest(".gb-item-category-filter");
$filter.find(":input").trigger("click");
$(this).focus();
})
```
This ticket fixes some of the issues described in SAK-33740, but does not address the last issue described there: "Show Only this Category" does not hide individual items within other categories; it will only hide other …
=> SAK-45995 GBNG > selecting 'hide this category' for a partially shown category will actually 'show this category'

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
https://jira.sakaiproject.org/browse/SAK-46020
If any of the origin sites contain stealth tools, these tools will appear at the top of the list of tools to migrate, but they won't have a tool name. This is different from past versions of Sakai where stealthed tools would never appear in this list. Example screenshot attached to the JIRA ticket.
The proposed fix here would restore the original functionality for instructors/maintainers (they do not see any stealthed tools in the list), but retains the new functionality for admins only. In the case of an admin viewing the list, they will see the tool ID of the stealthed tool(s) rather than their pretty tool names.
Resolving the tool name for stealthed tools (for both maintainers and admins) requires kernel modifications which are out of …
=>  SAK-46020 site info > import > dont show mysterious (stealthed) tools to maintainers

content/content-tool/tool/src/webapp/vm/content/sakai_resources_properties.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm
https://jira.sakaiproject.org/browse/SAK-46033
1. Edit a file in resources/drop box
2. Change the copyright drop down to "Please select a copyright status"
3. Save
4. Notice the form refreshes, but no error message is present at the top
5. Focus is put on the copyright field with no indication as to why the save didn't work
This is a regression introduced in parts by SAK-40422 and SAK-42121
=> SAK-46033 resources > edit > no copyright warning when flipping copyright back to 'please select...'

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://jira.sakaiproject.org/browse/SAK-46088
This algorithm suffers from some design decisions. Mainly, it sets each student's grade for each gradebook item to zero serially, rather than in batch. From GradebookNgBusinessService.updateUngradedItems():
```
// for each student remaining, add the grade
for (final String studentUuid : studentUuids) {
log.debug("Setting default grade. Values of assignmentId: {}, studentUuid: {}, grade: {}", assignmentId, studentUuid, grade);
// TODO if this is slow doing it one by one, might be able to
// batch it
this.gradebookService.saveGradeAndCommentForStudent(gradebook.getUid(), assignmentId, studentUuid, String.valueOf(grade), null);
}
```
The comment even states that the author was aware of the potential performance problem here.
I tested the …
=> SAK-46088 GBNG > improve performance of 'Set Score for Empty Cells' algorithm

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
https://jira.sakaiproject.org/browse/SAK-46086
Student #'s are important for instructors for a variety of reasons. If we have student #'s in the system, we should include them in the export by default for both regular and custom exports. Instructors can still elect to do a custom export without student #'s if they so desire.
=> SAK-46086 GBNG > export > include student #'s by default

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Hi, small change but it was hard to find 😅
I'm removing the points validation when the request is in the "attach" mode
The validation executes when the user tries to save the assignment
=> SAK-45722 Assignments / error adding an attachment before points entered

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
Consider if you create an assignment, change some Content Review settings, then add the assignment (or possibly take any action that persists the settings in the state, like visiting Model Answer, etc). If you then create a second assignment, the content review settings you've created on the previous assignment will stick.
These settings should be cleared / returned to their defaults.
=> SAK-46128 - Assignments - Content Review settings stick when creating two assignments in the same session

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
https://jira.sakaiproject.org/browse/SAK-46118
Prevented question numbers and point values from being read as a single number by screen readers (e.g. "Question 1 of 10 2 Points" used to read as "Question 1 of 102 Points" to screen readers). 
No visual change.
=> SAK-46118 Samigo: prevented merging of question number and point value for screen readers

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-46146
Instructors may wish to search for students by student number. Extend the search filter to look in the student number column if it exists.
=> SAK-46146 Gradebook > Extend search filter to student number column

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
https://jira.sakaiproject.org/browse/SAK-46145
The Group by Category action can be a bit slow to respond due to triggering a full page refresh. Adding spinners to the buttons will let users know their action is processing.
=> SAK-46145 Add spinners to Group By Category buttons

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java, gradebookng/tool/src/webapp/scripts/gradebook-import.js
https://jira.sakaiproject.org/browse/SAK-46087
This is a regression compared to Sakai 11 GBNG. There used to be a a select all/none checkbox on this UI. It no longer exists in Sakai 20+.
Users may complain about this, especially those who import lots of new items or lots of changed items.
This PR restores the select all/none checkbox.
=> SAK-46087 GBNG > import > item selection > no way to select all

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://jira.sakaiproject.org/browse/SAK-46092
This is directly related to SAK-42468. TA's should only see those users who are members of the groups and/or sections they're assigned to. TA's should only see non-provided site members if the TA is assigned to the "All sections/groups" setting.
=> SAK-46092 GBNG > TA with permission to grade empty group can see non-roster students not present in the group

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
https://jira.sakaiproject.org/browse/SAK-46093
If you import some items, change the values along the way in the wizard, reach the confirmation page, then navigate all the way back to the item selection stage, then start going forwards through the wizard again, you'll notice that all the changes you made originally have been lost. This is annoying for users. Let's preserve their input as they traverse through the wizard.
There is one known caveat here: if you navigate all the way back to the item selection step, this UI will show the original values from the imported spreadsheet. However, once you start going forwards through the item modification steps, you'll notice that all your previous modifications are still present.
=> SAK-46093 GBNG > import > user data loss when navigating backwards through the wizard

content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java, content/content-tool/tool/src/webapp/vm/resources/sakai_dropbox_multiple_folders_upload.vm
https://jira.sakaiproject.org/browse/SAK-46114
Copyright enforcement can be bypassed in Drop Box by using the "Upload files to multiple dropbox folders" interface. The copyright field is not present on this UI at all.
=> SAK-46114 copyright enforcement can be bypassed using drop box

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentConstants.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-46115
We've had multiple issues where users are somehow able to trigger situations where all previously entered grades disappear when the instructor elects to release the grades. Despite how many times this has happened at Western, we've been unable to identify exact steps to reproduce. However, all cases have one thing in common: they're sending grades to an existing gradebook item.
Due to not having solid steps to reproduce, we've historically been in a reactionary cycle, where when this happens it forces us to do a clone and restore to get the grades back into place. This process is extremely cumbersome and time consuming.
As a result, we decided to develop a feature to hide the ability for an Assignment to send grades to an existing gradebook …
=> SAK-46115 assignments > ability to disable setting to send grades to existing gradebook item

commons/api/src/bundle/commons.properties, commons/api/src/java/org/sakaiproject/commons/api/datamodel/Post.java, commons/impl/src/java/org/sakaiproject/commons/impl/PersistenceManagerImpl.java, commons/tool/src/java/org/sakaiproject/commons/tool/entityprovider/CommonsEntityProvider.java, commons/tool/src/webapp/WEB-INF/applicationContext.xml, commons/tool/src/webapp/WEB-INF/templates/post.hbs, commons/tool/src/webapp/WEB-INF/templates/posts.hbs, commons/tool/src/webapp/js/commons.js, commons/tool/src/webapp/js/commons_utils.js, library/src/morpheus-master/sass/modules/tool/commons/_commons.scss
These commits add a checkbox below the main Commons textbox that sets the post to High-Priority. This will highlight the post and add an icon on its right side, and send an email to members of the site when it's added.
This works using a new database column called Priority; I will make a corresponding PR to sakai-reference with that change and link to it here.
=> SAK-46022 Add High-Priority option to Commons posts

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkEditItemsPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-bulk-edit.js
https://jira.sakaiproject.org/browse/SAK-46148
If you enable the "Delete" checkbox on the Bulk Edit Items modal (Gradebook > Bulk Edit) and then click "Save Changes", the page refreshes, the column is gone, and a success message at the top says "The gradebook items were successfully updated".
Deleting content, particularly when it is unrecoverable, such as in Gradebook, should always have a confirmation for the user, such as:
"Are you sure you want to delete the following Gradebook items?"
Deleting a GB item individually says:
Are you sure you want to delete ''Item 1''? Please be aware that deleting this Gradebook item cannot be undone and scores entered will be removed from the gradebook.
=> SAK-46148 Gradebook > Bulk Edit has no confirmation for deleting GB items

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/webapp/styles/gradebook-gbgrade-table.css, gradebookng/tool/src/webapp/styles/gradebook-grades.css
https://jira.sakaiproject.org/browse/SAK-46151
When a category is set to use the equal weighting feature, this is indicated with a small icon so the instructor can easily recognize why the calculation doesn't reflect the raw point values. However, no such indication is given in the student view, which could be very confusing for students trying to understand how their category score was derived. Equal weight categories are also not indicated for instructors on the category column header itself, only in the item headers. This contrasts with extra credit, which is indicated in both places.
Additionally, students are also given no indication that a category is extra credit.
-----------
The styling colour changes are needed because by default both the extra credit and equal weight icons are …
=> SAK-46151 Categories using equal weighting or extra credit are not indicated to students

library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss, site-manage/datemanager/tool/src/main/resources/Messages.properties, site-manage/datemanager/tool/src/main/resources/static/js/initDatePicker.js, site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
https://jira.sakaiproject.org/browse/SAK-46140
Date Manager is useful but date adjustments are entirely manual. A basic level of automation should be provided, allowing for users to shift all dates by a certain number of days. For example, an instructor may want to shift all dates from last year's imported course by 365 days, to put them in the ballpark of the desired dates for the current year's course. This could save a lot of clicks by avoiding manual changes to year.
See UI screenshot on SAK ticket.
=> SAK-46140 Add simple date shifter to provide some level of automation for Date Manager

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/CompilatioReviewServiceImpl.java, content-review/impl/service/pom.xml, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/BaseContentReviewService.java, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java, content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java, content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/ContentReviewServiceVeriCite.java, content-review/pack/src/webapp/WEB-INF/compilatio.xml, content-review/pack/src/webapp/WEB-INF/components.xml, content-review/pack/src/webapp/WEB-INF/turnitin-oc.xml, content-review/pack/src/webapp/WEB-INF/turnitin.xml, content-review/pack/src/webapp/WEB-INF/vericite.xml
Consider this scenario:
- An assignment is created without content-review
- A student submits to the assignment
- The assignment is edited, using content-review
The system should attempt to queue the student's content with the content-review service for both inline content and attachments.
=> SAK-46139 - Assignments - submitted content should be queued when content-review is enabled on an existing assignment

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://jira.sakaiproject.org/browse/SAK-46156
Gradebook uses toLocaleString() for each grade it renders. During an investigation into client-side rendering performance I noted that this was taking a long time in Firefox. I found the following MDN article that recommends a different approach for performance reasons:
https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Number/toLocaleString#performance
Anecdotally, after making this change locally I measured a reduction in JS rendering time for a large gradebook of approximately 1000ms, taking the entire time from 2200ms to 1100ms, so this is a noticeable improvement in this scenario. This was in Firefox. There was no real improvement in Chromium, so I assume it already makes this optimization under the hood. …
=> SAK-46156 Improve gradebook JS rendering time in some browsers

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
https://jira.sakaiproject.org/browse/SAK-46159
The instructions on the tool selection page when importing content are a little scattered. Moving all the banners to the top of the page and removing redundant messages would help streamline things.
=> SAK-46159 Site Info > Improve layout of tool selection page when importing content

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ChangeProfilePictureUpload.html
https://jira.sakaiproject.org/browse/SAK-45327
My solution to this is to restrict the allowed file types, to accept only images, so the user is not able to select a video or something else
Also the OS file explorer will only show allowed files
=> SAK-45327 Error trying to upload video to Profile gallery

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, content-review/api/src/main/java/org/sakaiproject/contentreview/service/ContentReviewService.java, content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/CompilatioReviewServiceImpl.java, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/BaseContentReviewService.java, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/ContentReviewFederatedServiceImpl.java, content-review/impl/service/src/main/java/org/sakaiproject/contentreview/service/NoOpContentReviewService.java, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java, content-review/impl/turnitin/src/main/java/org/sakaiproject/contentreview/turnitin/TurnitinReviewServiceImpl.java, content-review/impl/urkund/src/main/java/org/sakaiproject/contentreview/urkund/UrkundReviewServiceImpl.java, content-review/impl/vericite/src/main/java/org/sakaiproject/contentreview/vericite/ContentReviewServiceVeriCite.java, content-review/pack/src/webapp/WEB-INF/compilatio.xml, content-review/pack/src/webapp/WEB-INF/components.xml, content-review/pack/src/webapp/WEB-INF/turnitin-oc.xml, content-review/pack/src/webapp/WEB-INF/turnitin.xml, content-review/pack/src/webapp/WEB-INF/urkund.xml, content-review/pack/src/webapp/WEB-INF/vericite.xml
When an assignment is hard deleted, it leaves behind content-review items that still refer to the assignment. When these items are in the content-review queue, they can produce errors since their associated assignment no longer exists.
These items should be deleted from the queue.
=> SAK-46160 - Assignments - clean up content-review items when assignments are hard deleted

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm
https://jira.sakaiproject.org/browse/SAK-46179
Currently the buttons for the peer review page are: Save, Cancel, Submit. There is no primary action button.
The Submit button should be made the primary action and moved to the left: Submit, Save, Cancel.
=> SAK-46179 Assignments - Peer Review - no primary action button, button order questionable

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
https://jira.sakaiproject.org/browse/SAK-46173
Samigo will run JavaScript that will silently uncheck the anon grading box if you switch "release to" from "Entire Site" to "Selected Groups" or vice-versa. The intention here was to do this when switching from "Anonymous Users" to another selection, but it seems "Selected Groups" was not considered. Furthermore, silently changing settings is not a good practice. Users need to know that this will happen.
=> SAK-46173 Samigo > Create/Edit > Settings > User selections lost/changed silently

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
Hi,
The problem was caused because after the parseFloat, the dot was removed and that value was set as the input value
I'm moving the parseFloat operation to right before the API update and keeping the value as a string to maintain the dot in the input
=> SAK-45847 Rubrics > Adjust Individual Scores > Deleting a number after a decimal deletes the decimal too

library/src/morpheus-master/sass/modules/navigation/_base.scss, library/src/morpheus-master/sass/modules/quicklinks/_base.scss, library/src/morpheus-master/sass/themes/_light.scss
https://jira.sakaiproject.org/browse/SAK-46106
Adding two-tone colours to the top header bar for greater branding customization as well as a visual transition for 22 to act as a transition to the new "Trinity" design coming in a later Sakai version. Also fixed some minor issues with the header bar. 
See SAK-46106 for after screenshots.
=> SAK-46106 Library: Added two-tone colours to the Sakai top header bar

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
In my opinion all these "update" events should only happen when editing an announcement, not on creation. This change won't have any side effects besides fixing the bullhorns bug.
=> SAK-46083 Announcement: duplicated bullhorns, move events to edit

sections/sections-app/src/bundle/sections.properties, sections/sections-app/src/webapp/roster.jsp
To solve this, a warn banner will be displayed when there are no students to show, instead of the empty table. 
The message will appear in two cases:
- The search result doesn't match with any user.
- There are no students associated with the site.
I wrote it trying to fit both situations. Of course, I'm open for suggestions.
Jira: [SAK-44069](https://jira.sakaiproject.org/browse/SAK-44069)
=> SAK-44069 SECTION INFO: First row shouldn't appear if 0 items found

assignment/impl/src/java/org/sakaiproject/assignment/impl/EmailUtil.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
Within submitted attachment lists, "Inline Submission.html" is often included. This attachment is not a user-uploaded attachment; it's an implementation detail required in case the assignment is edited, and content-review is enabled.
Hide this file from all UIs and emails.
=> SAK-46169 - Assignments - submitted attachment lists include "Inline Submission.html" which is an implementation detail

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemConfigBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/StartInsertItemListener.java, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
This bug was originally introduced on https://jira.sakaiproject.org/browse/SAK-42865 so I'm putting back some of what was removed back then. For that reason I'm also overriding the changes from https://jira.sakaiproject.org/browse/SAK-46039 (as now they won't be needed).
=> SAK-44981 Samigo : assign items to pools, parts or keep sequence

webcomponents/tool/src/main/frontend/js/sakai-i18n.js
`window.portal` was always undefined in the opened dialog
=> SAK-45963 Discussions:  rubric property values are missing

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
This fixes the critical issue with the NPE, however, the approach is suboptimal since the EXTERNAL_EMAIL column in the MFR_MESSAGE_T table is nullable and doesn't have a default false value.
=> SAK-46255 Messages: Unable to access replies saved as drafts

profile2/impl/src/java/org/sakaiproject/profile2/dao/impl/ProfileDaoImpl.java
currentImage is null when removing an empty profile image.
https://jira.sakaiproject.org/browse/SAK-46279
=> SAK-46279: ERROR: ProfileDaoImpl.invalidateCurrentProfileImage invalidateCurrentProfileImage failed. class java.lang.NullPointerException: null

library/src/morpheus-master/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
Hi, here are some previews of my proposal to fit rubrics in a mobile viewport
https://jira.sakaiproject.org/browse/SAK-44545
---
<details> 
<summary>Rubrics tool page (screenshot of the whole page)</summary>
</details>
<details> 
<summary>Rubrics long text</summary>
</details>
<details> 
<summary>Rubrics Grading</summary>
</details>
<details> 
<summary>Rubrics fine tune</summary>
</details>
<details> 
<summary>Rubrics student-view</summary>
</details>
=> SAK-44545 Rubrics text overlapping/cut off at 500px

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-46304
When using property assignment.grade.default=false
=> SAK-46304 Assignments grading pane is not visible

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
Replace icons and fix spacing accordingly. Kept spacing images with smaller width to have a little bit wider focus indicator on the icon.
=> SAK-46287: Tests & Quizzes: Question pool icons should be caret icons

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-reorder.vm, assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_reorder_assignment.vm, library/src/morpheus-master/sass/base/_extendables.scss, site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js, site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
A `cursor: grab;` when you hover over the items, that turns into a `cursor: grabbing;` when you click and drag one of them to another position, for a more intuitive rearrange.
Defined in the CSS, used for the html element classes and managed with JS functions.
Affects: 
- Announcements -> Reorder
- Assignments -> Reorder
- Site Info -> Tool Order
> A full restart of tomcat is needed for the desired behavior.
=> SAK-43911 Drag and Drop Reorder lists should display a grabbing cursor

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
This is in order to improve consistency comparing to what's done on other tools.
There are some subtasks (subjiras?) that will be required: duplicate, export and transfer published assessments.
=> SAK-34596 Samigo : remove drafts when publishing

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/MessageForumStatisticsBean.java
Change '==' to equals method to avoid a false false
=> SAK-46345: Reopened - Discussions > Statistics > Student View > Print Buttons do not work

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
Removed this links for students because display in thread view is broken for students. When there is a fix for [SAK-46353](https://jira.sakaiproject.org/browse/SAK-46353), this can be removed.
=> SAK-46352: Discussions: Remove [display in thread] links for students

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/printFriendlyAllAuthoredMsg.jsp
Fix print page for students (Discussions -> Statistics -> Show Full Text for All Authored Messages), by not only rendering the view to instructors, but also for the author of the messages.
=> SAK-46357: CLONE - Reopened - Discussions > Statistics > Student View > Print Buttons do not work

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Remove '}' form template and add '.' to text property of info text
=> SAK-46375: T&Q: Question Metadata contains a curly brace behind the text

samigo/samigo-app/src/webapp/js/calcQuestInputValidator.js, samigo/samigo-app/src/webapp/js/delivery.js, samigo/samigo-app/src/webapp/js/finInputValidator.js
I think this should fix it, but I'm working on getting a dev environment going locally to test
I didn't realise the throttle() method was used during grading, the finInputValidator.js file was included in gradeStudentResult.jsp since 21.0 ([SAK-42863](https://github.com/sakaiproject/sakai/commit/dbd430898ac5551e6c92b53db6c518882825d32e))
=> SAK-46489: keep throttle() method in validator js files

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java
Even if I'd say this fixes the issue, that part of code hasn't been modified for years... So I tried to look after the "recent" change that introduced the issue just in case, it might be js? No big deal, mentioning it to see if anyone has any clue.
=> SAK-46475 Gradebook category columns remain after disabling categories

kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java
This seem to come from an "ignore" exception that was changed to WARN (see https://github.com/sakaiproject/sakai/pull/6536), where they were converted to DEBUG for BaseCalendar.. and BaseMessage but not for BaseUser..).
=> SAK-46544 Kernel : warn log message shouldn't appear

.github/workflows/server.yml, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm, user/user-tool-prefs/tool/src/java/org/sakaiproject/user/jsf/HideDivisionRenderer.java
Per accessibility review comment: "list of the expanded item has role of menu and menuitem which is not correct since it does not include the only link but it also includes text information."
Basically: we need to only use the roles of menu/menuitem when it is a pure menu. This upper-right profile is more like a super menu and has information and links so doesn't use the menu/menuitem 
You can do some testing locally with your aXe Chrome console .... open the menu up in upper-right, scan the page, look for errors
=> SAK-38394 cleanup use of role=menu and menuitem to improve aXe a11y score

gradebookng/tool/src/webapp/scripts/gradebook-chart.js
My working solution is based the top answer from the following stackoverflow post:
https://stackoverflow.com/questions/37699485/skip-decimal-points-on-y-axis-in-chartjs
An important adaptation to the solution in that post that I make here attends to the different contexts in which X and Y axes are used in Gradebook-- namely between the course grade stats graph and a gradebook item stats graph. For the former, the X axis displays the Number of Students. For the former, the Y axis displays the Number of Students. Thus, callback functions for each axis use isNaN() to distinguish whether or not the axis variable is a number. If it is, then the axis is for Number of Students, and for such cases, I filter out all fractional values to display only whole number values in the graph.
=> SAK-45314 - Gradebook: Grade statistics graphs show fractional students.

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm, velocity/tool/src/templates/VM_chef_library.vm
The label should not be hidden from view. Use aria-label instead.
=> SAK-46590 resolve aXe-identified a11y issues.

user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
Change getServiceName to use the standard sakai property ui.service
to get the local service name to display in the Preferences tool.
=> SAK-46612 [User] Preferences use correct property for service name

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_estimate.vm
https://sakaiproject.atlassian.net/browse/SAK-46610
ORACLE 11g, for example, does not allow VARCHAR2 bigger than 4000 so we should modify length before anyone can add this feature to their instances.
On other PR I'll change the scripts:
https://github.com/sakaiproject/sakai-reference/pull/143/files
=> SAK-46610: ORACLE: Assignment Work log, change maxlength from 4096 to 4000

jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java, jobscheduler/scheduler-tool/src/webapp/scheduler/filter_events.jsp
There was a problem with the migration of this tool to JSF2, since the tag <sakai:script> wasn't recognized. That was the reason of the crash and the exceptions being printed on the console. I removed those unnecessary scripts and changed the input date fields of the form to the standard input type "datetime-local". Now we receive that data on the bean manager to configure the filters properly.
=> SAK-46665 Scheduler: Filter Events page not displaying, stack traces on the server

feedback/pom.xml, feedback/src/webapp/WEB-INF/bootstrap.jsp
The Handlebars plugin was creating a compiled file with a ".handlebars" extension that wasn't recognized as a valid mimetype when using security configuration in the server side. I changed the name of the output file on the "handlebars-maven-plugin" properties of the pom.xml to use a valid ".js" extension.
=> SAK-46722 Feedback tool: When setting the 'X-Content-Type-Options' header the tool does not load.

library/src/webapp/content/gateway/acknowledgements.html
This file is static and only present in nightlies, most of the institutions don't use the content in production.
=> NOJIRA Sakai Community link updated

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsMessageManager.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/DiscussionForumManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsMessageManagerImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/MessageImpl.hbm.xml
when looking for ability to moderate a topic
It looks like all topics to create in modern Sakai create a set of custom permissions. But very old topics in Sakai may use a default permission level. These changes make this querying much more efficient.
=> SAK-46754 refactor to avoid scanning entire MFR_PERMISSION_LEVEL table

usermembership/tool/src/java/org/sakaiproject/umem/tool/ui/SiteListBean.java, usermembership/tool/src/webapp/usermembership/js/usermembership.js, usermembership/tool/src/webapp/usermembership/sitelist.jsp
https://sakaiproject.atlassian.net/browse/SAK-46732
I had to put the command buttons in their own form and remove the
disabled flag. This means the buttons are always enabled which isn't
ideal but causes no harm. If you set disabled in a jsf command button
you can't enable it in JS as the backing component is not updated. It's
always treated as disabled and won't trigger any actions. If I was to do
more work on this I'd literally just rewrite this tool in spring mvc +
thymeleaf.
=> SAK-46732 UserMembership: put buttons in their own form

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
Used `sakai.editor.launch` function from `library/src/webapp-filtered/editor/ckeditor.launch.js`
Includes `CKEDITOR.skin.chameleon`, that enables ckeditor to reflect themeswitcher changes.
I've kept the previous way inside an _else_, just in case.
See [SAK-46532](https://sakaiproject.atlassian.net/browse/SAK-46532) for more info.
=> SAK-46532 Assignments/Grader: Feedback Comments dark theme

signup/tool/src/webapp/signup/newMeeting/step2.jsp, signup/tool/src/webapp/signup/organizer/copyMeeting.jsp, signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
It seems like having itemDisabled here as the default made it so that JSF wouldn't pass any value through to the bean. I don't know if this is something new with JSF2 or not. I'd have to imagine it was working as this was added back in 11. From what I can tell it doesn't need to be disabled by default as there is code client side to enable or disable and this code isn't processed if the checkbox isn't checked.
=> SAK-46753 - Signup: NPE with email to potential participants

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
I've changed the way the drop menu worked when invoked by keyboard. I've added a "switch case" statement instead of a bunch of "if" statements, and wrote new code for the keys that were missing (left and right arrows & tab).
=> SAK-46439 Gradebook: When using keyboard navigation, item menus do not close until another item menu opens

library/src/morpheus-master/js/src/sakai.morpheus.reorderer.js
I've changed the code for the reorder script in the library. Before, the code was searching only in the children nodes of the "reorder-element". Using the ".find()" function from JQuery we can search properly in all the nodes beneath the DOM tree, independently of the structure of DOM elements.
=> SAK-46456 Reorder library not working for numerical inputs

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
There was a problem related to SAK-40644. When hiding a dropdown menu item on the Gradebook, the keyboard navigation ceased to work properly because the navigator couldn't focus on the hidden item. Those menu items had to be removed from the DOM in order to make the whole menu accessible.
=> SAK-46438 Gradebook: Item menus are not keyboard accessible when on far left/right of gradebook or category

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchAccessPage.html, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchUsersPage.html, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/ShoppingEditPage.html, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserEditPage.html, library/src/morpheus-master/sass/modules/tool/delegatedaccess/_delegatedaccess.scss
I moved many of these styles into morpheus-master. There are still some inline styles mostly for the wicket-tree-table component which is deprecated.
These should really all be removed when/if this component is replaced. I did a slight adjustment to make this more useable in darkmode, even though it's got a white background.
Most of the styles for this are internal to the wicket component and not currently overridden.
=> SAK-46736 - Admin Workspace: Delegated Access - Dark Theme Makes List Unreadable

rubrics/api/src/main/bundle/rubrics.properties, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
https://sakaiproject.atlassian.net/browse/SAK-46781
This error is displayed by a browser when a 404 is received. Rubrics
makes a get request for the returned evaluation backup copy when saving,
and it's perfectly valid for this to return a 404. The code handles the
404 returned, but the browser also prints the 404 "error" to the
console.
=> SAK-46781 Added js log message explaining the 404 error

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties, lessonbuilder/tool/src/resources/messages_es.properties, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml, lessonbuilder/tool/src/webapp/WEB-INF/requestContext.xml, lessonbuilder/tool/src/webapp/removePage.jsp, lessonbuilder/tool/src/webapp/templates/ShowPage.html
This change allows the Lessons tool to create tasks when adding new pages, questions, comments or student content. Settings of all of these components have a new checkbox option to create these tasks. Tasks are updated or removed automatically when pages and/or components are changed or deleted. @mpellicer @bgarciaentornos
=> SAK-45054 Add Lessons items to Tasks widget

edu-services/gradebook-service/api/pom.xml, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/Assignment.java, edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, edu-services/gradebook-service/sakai-pack/src/webapp/WEB-INF/components.xml, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/bundle/src/main/bundle/gradebookng_es.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java, gradebookng/tool/src/webapp/WEB-INF/applicationContext.xml
This pull request includes modifications in edu-services to implement an entity to GradebookAssignments, since it was required on task creation to have a reference to the items on the gradebook. The gradebook was also modified to have a new checkbox option when creating gradebook items in order to create new tasks for the widget. Tasks created within the gradebook will be also updaded or deleted when corresponding gradebook items do so.
=> SAK-45051 Add Gradebook items to Tasks widget

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es_ES_Pearson.properties, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionForumBean.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionTopicBean.java, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
This pull request includes changes into Discussions tools in order to feed the tasks widget on the dashboard. It includes a new option in forum/topic settings to create a task for students when you add grading to a forum or topic. When students post a comment on a graded forum/topic that has a task related to it, this task will be marked as being completed automatically. Also, when you edit a forum or a topic, if there is a task related to it, this task will be updated as well.
@bgarciaentornos, @mpellicer, will you take a look?
=> SAK-45053 Add Discussions items to Tasks widget

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeValidator.java, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
https://sakaiproject.atlassian.net/browse/SAK-46617
I've deleted the validation for the due date being greater or equal to the current date and all properties refered to this restriction.
=> SAK-46617 Tests & Quizzes: Exceptions have restrictions not present for non-excepted students

site/admin-perms-tool/src/main/webapp/WEB-INF/spring-servlet.xml
Added additional wildcard map for this file. I'm not 100% sure why this was needed in Sakai 21 now. I was just [reading through this guide](https://www.baeldung.com/spring-handler-mappings) and noticed the difference which fixed it and makes sense.
=> SAK-46869 - Admin Site Permissions:  No mapping for GET /adminsiteperms/sitePerms.htm

msgcntr/messageforums-app/src/webapp/jsp/compose.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgForward.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/pvtMsgReplyAll.jsp
https://sakaiproject.atlassian.net/browse/SAK-46884
With this changes now the checkbox is always shown, but it is disabled if the user can not select the option of send or not the copy.
=> SAK-46884 Messages Always sending CC just shows text

portal/portal-render-engine-impl/impl/src/bundle/org/sakaiproject/portal/charon/velocity/portalvelocity.config, portal/portal-render-engine-impl/impl/src/bundle/trinity/options.config, portal/portal-render-engine-impl/impl/src/java/org/sakaiproject/portal/charon/velocity/VelocityPortalRenderEngine.java
Fixes stacktrace on every page load that was caused when VelocityPortalRenderEngine tried to load non existing options for the portal and alsodisabled velocity loader caching (for now) to make switching between morpheus and trinity more possible.
=> TRINITY-42 Add missing config and disable velocity caching

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
For some reason o the change for[ SAK-45828 ](https://sakaiproject.atlassian.net/browse/SAK-45828)related to fields, doUpdate was added to the doAddSubscription. This should not be run as part of this workflow step here.
=> SAK-46060 - Calendar: Merge External Calendars - Unexpected Error

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
https://sakaiproject.atlassian.net/browse/SAK-46886
This affects to the previous commit of this SAK, but a related error occurs in the new ChoiceRenderer<GbUser>() (line 155 and line 160 of PermissionsPage.java)
=> SAK-46886 Gradebook when some user is null permission tab does not work

jobscheduler/scheduler-tool/src/java/org/sakaiproject/tool/app/scheduler/SchedulerTool.java
Corrected a bug. When filtering two consecutive times, filters where not initialized again to null, so they were handling old values.
=> SAK-46976 Job Scheduler date filters are not being applied

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java, webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SitesController.java, webcomponents/tool/src/main/frontend/js/announcements/sakai-announcements.js
Added related commit from Adrian, which is on master, but not on the trinity branch yet.
I wanted to remove `getAnnouncementRange` from AnnouncementActions in favor of having it in the AnnouncementService, but found myself to deep in that rabbit hole.
=> TRINITY-52 Extend Announcements API

webapi/src/main/java/org/sakaiproject/webapi/beans/AnnouncementRestBean.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webcomponents/tool/src/main/frontend/js/announcements/sakai-announcements.js
Removed links except one to view announcement. This is similar to how it was pre TRINITY-52.
Fixed and tested announcement widget webcomponent as well
=> TRINITY-52 Remove links from announcements rest api

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java
The main problem was the fact that when a student sent the exam to grading, the task in the students' dashboard didn't appear as completed. Currently, it has been fixed changing the state of the task to complete in SubmitToGradingActionListener class. I only had to add a call to completeUserTaskByReference method from the TaskService to fix this issue.
=> SAK-46903 User's Dashboard: Submitted quizzes not displaying as completed for tasks

library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js, library/src/morpheus-master/sass/modules/more-sites/_base.scss, portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/moresites.vm
**Jira [SAK-45729](https://sakaiproject.atlassian.net/browse/SAK-45729)**
- When opening the dialog, its first element will receive focus if "Organize Favorites" tab was selected.
- Three ways of closing the modal will send focus back to the initial button.
- Use dialog role.
**TAB behavior inside modal**
- Shift + TAB on the first element will get you to the last one.
- Site lists will close when getting out with TAB key.
- Pressing TAB while having focus on a Tool from the **last** Site list won't throw focus out of the modal.
**Style**
- Improve visibility of blue outline on Site lists' elements. Also panel tabs.
Add outline for "Filter sites" input.
- Small design upgrades.
_Used auto code formatter._
=> SAK-45729 Sites drawer: Improve usage with keyboard & screen reader

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
Previously, if no Gradebook Tool is added before to the site, when an instructor tried to create a new forum in Discussions tool, it threw a NPE. Currently, it has been fixed with an if statement in DiscussionForumTool class taking into account the fact that the value of GradeBookService is null due to there wasn't a Gradebook Tool added to the site.
=> SAK-45053 A new forum can be created avoiding NPE

assignment/tool/src/webapp/js/assignments.js, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, library/src/morpheus-master/sass/modules/tool/_menu.scss
In Sakai 22, in Assignments tool, when a user is going to grade submissions the menu items (“Download All“,”Upload All” and ”Release Grades”) are too close. A little separation is needed
=> SAK-47131 Menu items in assignments tool are too close and need some separation

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
I searched this property in the entire code and looks like it's not used and the functionality is not implemented, I don't know cases of institutions limiting the number of single user sessions.
=> KNL-1089 - Remove unused property from the documentation

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UserIdentificationReport.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/importExport/UsernameIdentifier.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUnidentifiedUser.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUser.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/GbUserBase.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedRow.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.java
https://sakaiproject.atlassian.net/browse/SAK-47117
JDK seems to be calling `compareTo` now for the sorted set. I tried implemented equals/hash on the existing `GbUser` object, but due to complexities with how we use this object, it became difficult to keep equals and hashcode in sync.
Instead, I decided to split the usage of `GbUser` into a new class, so we use `GbUser` when we know we have UUID etc, and we use the new `GbUnidentifiedUser` for when we don't have a UUID. This makes the equals/hash on each consistent and easy to implement.
Really we are only using the new object to report on users contained within the file who are not members of the site, so it was a small refactor.
Also added fallback logic to the EID in the compareTo.
=> SAK-47117 Gradebook import fails if 2 or more users have the same name with different IDs

kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
Adds a new cache configuration to Ignite that uses an eternal expiry
policy so that the LTI13Servlet Sakai Access Token will never expire
from the Ignite cache.
=> SAK-47146 Add cache config for eternal expiry policy for LTI 1.3

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-47158
1. Create a draft assignment
2. Return to the assignment list
3. Notice the assignment title is prefixed with “Draft - “
4. Move the assignment to the Trash
5. Go to the Trash list
6. Notice there is no indication that the assignment is a draft
The assignment is restored to draft status. For consistency and clarity, we should apply the draft label to draft assignments in the Trash list. This could cause annoyances if someone has multiple assignments with the same name, but some are draft and some are published.
=> SAK-47158 Assignments > trash doesn't indicate draft status

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/StudentScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreListener.java, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, webcomponents/tool/src/main/frontend/js/grader/submission.js
https://sakaiproject.atlassian.net/browse/SAK-47157
Assignments: If two students have the same name  you can't tell them apart when navigating between submissions. Sakai  Grader has the same issue.
Samigo: If two students have the same name and you forget which one  you clicked on, you have to go back a page and click on the right one to  be sure. You could also use the Email link at the bottom but that's  easily overlooked. Not as big a problem as in Assignments since you  can't navigate between students in this view, but for consistency it  should be the same in all tools.
=> SAK-47157 assignments, samigo > submission page should display EID

assignment/api/src/resources/assignment.properties, assignment/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_deleted_assignments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_confirm_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_preview_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_assignment_honor_pledge.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
https://github.com/bjones86/sakai/pull/new/SAK-47154
We don't need an entire column for one icon. Also, the column is pointlessly rendered even when no assignments have attachments. All icons should appear to the right of the assignment title, not to the left, so that the text of the assignment names is left aligned in tables, etc.
=> SAK-47154 assignments > remove dedicated column for attachment icon

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
https://sakaiproject.atlassian.net/browse/SAK-47074
See the SAK ticket for full details. In short, with the restrictions on having correct answers for Short Answer questions removed in SAK-44975, the grading logic for Lessons questions needed to be revised, particularly for manually graded questions. This PR resolves the problem and makes Multiple Choice and Short Answer grading consistent.
=> SAK-47074 Lessons short answer questions auto graded

library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss, profile2/api/src/resources/ProfileApplication.properties, profile2/api/src/resources/ProfileApplication_es.properties, profile2/tool/src/java/org/sakaiproject/profile2/tool/components/ProfileStatusRenderer.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStatusPanel.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStatusPanel.java
Jira: [SAK-47145](https://sakaiproject.atlassian.net/browse/SAK-47145)
Fixes
- `placeholder` and `char counter` weren't showing until a status was submitted.
now they are completely managed from the script, and a proper placeholder in beeing used.
- After refreshing the page, the "Clear status" link wasn't working (till reloading again).
Accessibility
- Added a "Status" header and aria-labels.
- Clear link is now a button, improved text readability.
=> SAK-47145 Profile: Status section fixes & A11y improvements

kernel/api/src/main/java/org/sakaiproject/tasks/api/UserTaskAdapterBean.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
Before, when an instructor created a task on the dashboard, it didn't appear. There was also a problem with the due date picker that didn't get the value of the due date properly and its value wasn't store in the database. Currently, tasks created by an instructor will appear on the students' dashboard if the instructor wants to and the values of due dates will appear and can also be modified by an instructor.
=> SAK-46436 Tasks created by an instructor don't appear on students' dashboard & due date issue

samigo/samigo-app/src/webapp/jsf/author/restoreAssessments.jsp
https://sakaiproject.atlassian.net/browse/SAK-47187
The “Trash” UI uses some kind of client-side sorting that seems to sort the date column as text, rather than actual dates. Before and after screenshots on the JIRA ticket.
=> SAK-47187 Samigo > Trash > incorrect date sorting for 'deleted on' column

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-47192
When previewing a submission as an instructor, the assignment name will appear in quotes with unnecessary spaces, and the Accept Until date is not formatted properly.
=> SAK-47192 Display issues on the assignment submission preview for instructors

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47186
We’ve occasionally seen this in our logs:
Caused by: java.lang.ClassCastException: org.sakaiproject.assignment.api.model.Assignment cannot be cast to org.sakaiproject.assignment.tool.AssignmentAction$SubmitterSubmission
at org.sakaiproject.assignment.tool.AssignmentAction.calcPageFromSubmission(AssignmentAction.java:3958)
at org.sakaiproject.assignment.tool.AssignmentAction.doPrev_back_next_submission(AssignmentAction.java:3891)
at org.sakaiproject.assignment.tool.AssignmentAction.doAssignment_form(AssignmentAction.java:10165)
at org.sakaiproject.assignment.tool.AssignmentAction.doAssignment_form(AssignmentAction.java:10021)
I don’t know how to reproduce but I’m assuming it is still an issue since the code hasn’t changed. The problem is …
=> SAK-47186 Assignments > ClassCastException in calcPageFromSubmission()

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/api/src/java/org/sakaiproject/assignment/api/persistence/AssignmentRepository.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentEventObserver.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/persistence/AssignmentRepositoryImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47176
AssignmentEventObserver watches for Gradebook grade updates for non-external items to sync up the grades with the ones in Assignments that use the “link to existing Gradebook item” option. In most cases, a Gradebook item will not be linked to any assignment, and in these cases, every gradebook update results in a warn message in the logs. This is unnecessary log bloat.
There are really two problems here. The root problem is that the Assignments service will return the String “null” for the assignment id when there is no assignment linked to the Gradebook item, causing it to log a warning when it shouldn’t. The second problem is that this scenario is too common to be logged at the warn level, and so the logging that does get properly …
=> SAK-47176 AssignmentEventObserver logs a warning for every Gradebook grade update

assignment/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_preview_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_review_edit.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_feedback_attachments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm, kernel/api/src/main/java/org/sakaiproject/entity/api/ResourceProperties.java, kernel/kernel-util/src/main/java/org/sakaiproject/util/BaseResourceProperties.java
https://sakaiproject.atlassian.net/browse/SAK-47170
Instructors will sometimes remove the read resources permission from the student role if they upload files they don’t want students to see. While this causes numerous problems throughout Sakai, one in particular is that in Assignments, student will see a stack trace on the submission page if the assignment has attachments, or if they have previously submitted attachments to the assignment. This happens whether or not they have more submissions for the assignment available.
In previous versions of Sakai, a stack trace would only be shown if the student had previously submitted attachments (due to NullPointerException that is was what I was actually intending to fix here), and any attachments on the assignment itself would simply not be …
=> SAK-47170 Assignments > Students see stack trace on assignments and submissions with attachments if read resources permission is removed

site-manage/datemanager/api/src/java/org/sakaiproject/datemanager/api/DateManagerService.java, site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java, site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/service/SakaiService.java, userauditservice/tool/src/java/org/sakaiproject/userauditservice/tool/UserAuditEventLog.java
https://sakaiproject.atlassian.net/browse/SAK-47198
When editing a site from Worksite Setup, if you go to some tabs you will not see the data from the site you selected to edit, but rather from the user’s home site (which likely contains no data, or very little data, and certainly not the data from the site the user selected to edit).
This appears to be a regression introduced when certain aspects (tabs) of Site Info were rewritten from RSF to a newer framework, or a new tool was introduced. The affected tabs include:
* Manage Groups
* Date Manager
* User Audit Log
=> SAK-47198 Worksite Setup > Edit Site > Some tabs show data from Home site rather than selected site

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-47204
The Oracle driver class name changed a long time ago from oracle.jdbc.driver.OracleDriver to just oracle.jdbc.OracleDriver. HikariCP spits out a warning on startup if using the old name. Update default.sakai.properties with the new name.
=> SAK-47204 Update default.sakai.properties Oracle driver class name

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp
https://sakaiproject.atlassian.net/browse/SAK-47184
Students often attempt to take multiple quizzes in multiple tabs, all at the same time. This leads to data discrepancy errors. Students are not warned about the dangers of this practise, and therefore aren’t aware that their behaviour is causing the problem.
Add a warning on the begin assessment page explaining the potential danger of doing so.
=> SAK-47184 samigo > add messaging when beginning an assessment warning of multiple tab dangers

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/AutoSubmitAssessmentsJob.java
Make this stateful for consistency with the declaration in components.xml and to avoid concurrent job execution
=> SAK-47216 Change the autosubmit job to implement StatefulJob

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThreadBodyInclude.jsp
https://sakaiproject.atlassian.net/browse/SAK-47211
Forum topics have a permission “mark as read”, yet when this permission is not granted, mark as read buttons still appear. The only thing the permission seems to actually control is the “Mark All As Read” button on the thread view.
Users without the permission should not see any Mark as Read buttons, nor should the Mark as Read column appear at all for them.
=> SAK-47211 Discussions: Mark as read button appears when corresponding permission is not granted

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://sakaiproject.atlassian.net/browse/SAK-47201
If a student submits only inline text, they still get a paperclip icon next to their submission in the submissions list. This may lead to confusion for graders, who may think there is a missing attachment when viewing the submission.
=> SAK-47201 Assignments > Submissions show paperclip icon in the submission list for submissions that only include inline text

assignment/tool/src/webapp/js/instructorNewEdit.js
https://sakaiproject.atlassian.net/browse/SAK-47197
When changing the grading scale for a non-group assignment, the group assignment radio button is enabled so it becomes possible to change a non-group assignment into a group assignment, which is normally prohibited. Additionally, changing the grading scale from a non-points scale into a points scale can autopopulate the points field with the text “Ungraded”. This ticket will address both issues.
=> SAK-47197 Assignments > Switching grading scale allows non-group assignments to become group assignments

admin-tools/src/java/org/sakaiproject/authz/tool/PermissionsHelperAction.java, admin-tools/src/webapp/vm/authz-helper/chef_permissions.vm, content/content-bundles/resources/content.properties, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java, kernel/api/src/main/java/org/sakaiproject/authz/api/PermissionsHelper.java, site-manage/pageorder/tool/src/bundle/org/sakaiproject/tool/pageorder/bundle/Messages.properties, site-manage/pageorder/tool/src/webapp/content/templates/PageList.html
https://sakaiproject.atlassian.net/browse/SAK-47185
We know instructors like to remove content.read permissions thinking it will secure all their secret exam files from students in one click. What they don't realize is that doing this breaks other tools.
Locking Resources in Site Info > Tool Order is another way instructors can inadvertently cause issues in other tools, as this takes away the "Resource resources" permission.
They should be warned of the consequences of this action in both locations.
The linked PR introduces a new function for the permissions widget: if you supply `permissionWarning` in the state context, the permission widget will render this message inside a `sak-banner-warn`, so that this can be utilized in all tools generically. If no warning is supplied, the banner is …
=> SAK-47185 warn users of the consequences of locking resources

library/src/webapp/js/spinner.js, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step1.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step4.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import_confirmation.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/joinable_set.html
https://sakaiproject.atlassian.net/browse/SAK-47200
Buttons within the Manage Groups interfaces lack spinners and disabling after clicking. This can lead to users mashing the buttons multiple times, which can result in duplicate groups being created.
This PR will also introduce support for `<button>` tags in `spinner.js`
=> SAK-47200 Site Info > Manage Groups > all buttons lack spinners

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ActionSelectListener.java, samigo/samigo-app/src/webapp/jsf/author/confirmEditPublishedAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp
https://sakaiproject.atlassian.net/browse/SAK-47217
When editing a published quiz, you will see a confirmation page first. If the quiz is already retracted, it is not necessary to show this page again, and the wording on it is somewhat inaccurate the second time, so it can just be skipped.
Also, some banners related to retracted quizzes are styled as errors when they should be warnings.
=> SAK-47217 Samigo > Skip confirmation page if quiz is already retracted, and improve banner consistency

samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AutoSubmitFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AutoSubmitFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/PersistenceService.java
https://sakaiproject.atlassian.net/browse/SAK-47222
Please see the SAK ticket for additional information.
This ticket will address the following two problems with the job:
1. The whole job is in a single transaction, so any rollback will undo all the processing and effectively reset the queue to its initial state. This can cause the queue to just continue to grow over time. Additionally, each time the queue is reset due to rollback, the autosubmitted attempts that were processed will be processed again and the student will get another email about it.
2. Performance can be extremely poor. Job runs can take many hours to complete with large queues or “heavy” quizzes, potentially impacting users if the job runs past its expected window and into peak usage times.
The modifications to address …
=> SAK-47222 Samigo > Autosubmit job > Separate transactions and major performance improvement

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47203
There is a site property (and sakai.property) one can use to force updating a score in GB when a quiz is taken and the same score is achieved. The site property is not respected when accessing a quiz through the Lessons tool.
The reason this occurs is because we are without portal in this situation, so the site ID cannot be resolved using the normal method. This results in a failure to look up the site property, and then it falls back to the global sakai.property. If the global property is set to false, but the site property is true, it will fail to update the record in GB when the quiz is access through Lessons.
The same issue occurs when accessing a quiz using the direct link from Samigo itself. Ex: …
=> SAK-47203 update same score site property not respected when taking quiz through lessons or direct link

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStatusPanel.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStatusPanel.java
[SAK-47208](https://sakaiproject.atlassian.net/browse/SAK-47208)
Used `maxlength` attr.
Extra fix: "clear status" button was showing on first load even if there wasn't any status setted.
=> SAK-47208 Profile: Character limit can be exceeded if you paste a copied text

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java, kernel/api/src/main/java/org/sakaiproject/tool/api/ToolManager.java, kernel/api/src/main/java/org/sakaiproject/tool/cover/ToolManager.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tool/impl/ToolComponent.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/test/org/sakaiproject/site/tool/SiteActionTestTools.java
https://sakaiproject.atlassian.net/browse/SAK-47250
This is a regression compared to 11.x.
After a stealthed LTI tool has been added to a site, it should appear in the Manage Tools list as selected, so the instructor can elect to remove it if necessary.
This is no longer possible. After adding a stealthed LTI tool to a site, it does not appear in Manage Tools. This then requires the instructor to (again) contact support so that an admin can remove it on their behalf.
Restore the ability for maintainers to remove stealthed LTI tools which are already present in their site. The linked PR also allows maintainers to remove regularly stealthed, non-LTI tools from their sites (this is a new feature, as they would have never seen regular stealthed tools in the tool list in previous versions of …
=> SAK-47250 Site Info > Manage Tools > allow maintainers to remove stealthed tools present in their site

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://sakaiproject.atlassian.net/browse/SAK-47202
Observe the submission history time zone format
> Sakai 11:
> Wed Feb 10 13:00:59 EST 2021 Albi Tremblay (student01) saved draft
> Sakai 20+:
> Wed, 10 Feb 2021 13:00:57 -0500 Albi Tremblay (student01) saved draft
Time zones are confusing for people, and they don’t want to do have to do math to figure out which time zone the string is referring to. Users who were polled unanimously prefer time zones listed by name (Sakai 11) over their difference to GMT (Sakai 20+).
Sakai 23 before:
> Fri, 22 Apr 2022 12:47:59 -0400 Albi Tremblay (student01) saved draft
Sakai 23 after:
> Apr. 22, 2022, 12:57 p.m. EDT Albi Tremblay (student01) saved draft
=> SAK-47202 Assignments > history log > time zone format displays offset rather than name

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm
https://sakaiproject.atlassian.net/browse/SAK-47156
Instructor’s see the “ - late” label applied to late submissions in both the submission list and the submission grading UIs. However, students do not see the late status on any of the UIs (assignment list, nor view submission). This information has meaning for both students and instructors, and should be communicated to both.
Part of this is a regression: the late status used to be displayed to students in the assignment list table. However this doesn’t seem to be the case in 23. Also, the "status" column for the student assignment list should not display the status in red bold text. Only the "late" label is meant to receive this styling.
=> SAK-47156 Assignments > late status is not communicated to students

content-review/impl/turnitin-oc/README.md, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java
When configuring a Turnitin assignment, you can choose whether or not papers should be indexed.
Indexing a paper means that it can be matched against by other papers.
The ability to index can be unsuitable in non-production environments. E.g. if a production Sakai instance is cloned to a restore environment while papers are still in the content-review queue, end-user papers will be marked as fully plagiarized against their own clone.
=> SAK-47233 - TurnitinOC - introduce a sakai.property to disable indexing (e.g. for non-production environments)

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Although answerList should be empty on entering this function according to the javadoc, changes elsewhere have led to a case where it's not always empty. 
This can lead to an answerList that is sized larger than it should be, depending on previous questions in the assessment, leading to item scores being divided by the wrong number of items for a question.
=> SAK-47236 T&Q calculated questions grading: clear answerList map

vuecomponents/tool/pom.xml
=> SAK-47228 Vue components: Bump Node and NPM to 16.15.0 and 8.5.5

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission_confirmation.vm
Before, if a instructor made assignments invisible to students, after a student submitted an assignment in lessons could access the rest of assignments of the site pressing "back to list" button. In order to accomplish the features described in this Jira, I have taken into account if assignments tool is visible. In case it is visible, the button "back to list" will be shown whereas if it isn't visible it won't be shown avoiding to see assignments list.
=> SAK-38240 Do not allow access to all Assignments from Lessons

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionForumBean.java, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp
https://sakaiproject.atlassian.net/browse/SAK-47227
- Javascript has been cleaned, removing not necesary functionality
- setCloseDate and setOpenDate was called twice, changing the value both times. Now dates are setted just when open/close dates comes in ISO format. Also, I tried the datetime-local input, but currently is displayed in the browser's languange, not in the user's defined language in the site.
=> SAK-47227 Discussions - Sometimes open/close dates are not set properly

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
The qtip and popover libraries are missing the T&Q Numeric Response question type when it is invoked from within Lessons.
=> SAK-47188 - Lessons-T&Q: Numeric Response popups/warnings not working

content/content-bundles/resources/content.properties, content/content-bundles/resources/content_es.properties, content/content-tool/tool/src/java/org/sakaiproject/content/entityproviders/ContentEntityProvider.java
Fixed a problem when pasting images in the CK editor. When you reached 100 images pasted and then uploaded, you got an error because all images were named the same ("image"). It was being considered as a hundredth attempt to upload the same image, but it was not.
In addition, I have added internationalization of error messages related to these uploads.
Please @josecebe @mpellicer, could you keep an eye out?
=> SAK-47362 Content tool: Error uploading pasted images in editor

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
Use `.` [prefix](https://lit.dev/docs/templates/expressions/#property-expressions) to pass criteria data to the from the rubric- to the criteria-component, to avoid weird behavior.
=>  SAK-45614 Rubrics / updating to weighted after altering criteria resets scale

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js
This is reverting one change from SAK-45614(#10596) which was not necessary for the fix, but causing the rubrics preview to break
=> SAK-47386 Rubrics: Rubric student preview does not display

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
https://sakaiproject.atlassian.net/browse/SAK-47281
The issue here is that Grader is storing the "Checked" string into database in the language that the Grader is displayed. In the old grader, "Checked" is always stored in english. So in the submissions list, if language is different of english, "Checked" is not displayed.
With this fix, now we are going to send to the endpoint the english value, but checks has to be done in both languages, because values comes in user's language to the new grader.
=> SAK-47281 Assignments - Checked is missing when grading using grader on another language using Grader

webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java
Make filename of rubrics pdf export safer for
browsers and other programs.
=> SAK-46889 Rubric | Export rubric with period followed by more characters leads to bad export

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/authz/AuthorizationBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/LoginServlet.java, samigo/samigo-app/src/webapp/jsf/delivery/submitted.jsp
In this PR I have controlled the visibility of the review results button when exams are accessed from the Lessons tool or through anonymous access (both are done by URL). This should allow students to get feedback from the Lessons tool and from anonymous access as well.
=> SAK-34456 Lessons: Cannot see feedback when Tests & Quizzes is used in Lessons

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp
https://sakaiproject.atlassian.net/browse/SAK-47309
- Removing undocumented property.
- All dropdowns are collapsed by default now.
=> SAK-47309 Discussions - Description dropdown duplicating Forum works backwards

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsAllAuthoredMsgForOneUser.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsDisplayInThread.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsFullTextForOne.jsp
https://sakaiproject.atlassian.net/browse/SAK-47306
The alternative text inserted to the pictures has broken some views in "Statistics and Grading" tab in Discussions, so to get rid of the images and also correct this problem, I changed the images by FA icons.
Before it looks like this:
And after, using FA:
=> SAK-47306 Discussions - Changing word count images by FontAwesome

deploy/pom.xml, master/pom.xml
There are some systems on which the com.sun.xml.bind:jaxb-impl jar does
not work properly, throwing startup errors. Using the Glassfish jar
appears to resolve this. Later versions move fully to the jakarta.xml
namespace.
Resolves: https://sakaiproject.atlassian.net/browse/SAK-47417
=> SAK-47417 LIB switch to glassfish JAXB runtime

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
There was no default case to show the _Back to list_ button, so I have set it to true when there is no PORTAL_VISIBLE property defined for the tool.
=> SAK-47357 Assignments: Back to list button is missing when student submits an assignment

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
https://sakaiproject.atlassian.net/browse/SAK-47439
Just two fixes:
- 0 == "" -> true, so I changed by the strict equality operator (===)
- Decimal with comma is interpreted as NaN when it comes as String, so now we check if isNaN with the parsed float and not with the raw value.
=> SAK-47439 Gradebook - Grades with decimal comma are not sorted properly

calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/PDFExportService.java
https://sakaiproject.atlassian.net/browse/SAK-47438
=> SAK-47438: Calendar: Month and year are wrong on PDF when printing monthly using month instead of actual

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
When switching a rubric to weighted the weight for the first criterion get’s set to 100%. If there is a criterion group before other criteria, the criterion group get’s the weight value instead (hidden). The weight should only be set for “real” criteria.
This also fixes console errors when changing to weighted for a rubric without criteria.
=> SAK-47462 Rubrics: Don't set weight for criterion groups

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties, kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/HtmlPageFilter.java, library/src/webapp/js/mathjax-config.js, portal/portal-impl/impl/pom.xml, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm, portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
Jira: [SAK-47442](https://sakaiproject.atlassian.net/browse/SAK-47442)
`mathjax-config.js` generates the "MathJax.Hub.Config" based on the new properties (stored on the portal header).
`SkinnableCharonPortal.java` is where the config is applied for the whole site.
`DeliveryBean.java` applies the config for Tests inside an iFrame on Lessons.
There is an excepcion related to `HtmlPageFilter.java` { Site / Resources / Actions / Create THML Page ) as you can download a html file outside Sakai, where the script wont be called. That's why I implemented a similar method using Java.
=> SAK-47442  MathJax: Global configuration using properties.

basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/BasicLTISecurityServiceImpl.java, basiclti/basiclti-impl/src/java/org/sakaiproject/basiclti/impl/LTIContentArchiveBean.java
This adds the relevant lti_content items into the basiclti.xml file created as part of the site archive.
A filtered list of fields is included, excluding placement info and other site context info which would not be relevant if these were imported into another context.
The exported XML elements look like this:
```
<LTIContent id="12010">
<settings/>
<lti13_settings/>
<newpage>0</newpage>
<custom>tool=/play/67948c69-7a18-4f90-b239-047c8a8cb1dd</custom>
<description/>
<tool_id>228</tool_id>
<launch>https://media.uct.ac.za/lti/player/67948c69-7a18-4f90-b239-047c8a8cb1dd</launch>
<id>12010</id>
<contentitem>{"@graph":[{"thumbnail":{"@id":"https:\/\/media.uct.ac.za\/static\/mh_default_org\/engage-player\/67948c69-7a18-4f90-b239-047c8a8cb1dd\/889af55c-af04-441e-8784-93e899ab0c54\/presenter_5_000 …
```
=> SAK-47282 Add lti_content to site archive

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, library/src/morpheus-master/js/src/sakai.morpheus.bullhorns.js, library/src/webapp/js/sakai-message-broker.js, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
SSE is awesome as it reduces the cost of polling, and we should move more tools to use it. We also need more experience with SSE and managing connections.
This commit:
a) Sets up the number of alerts in portal server page load
b) Avoids a fetch call to setup bullhorns
c) Bullhorns only called onclick
d) Disables setting up the SSE
To use SSE, I'd like to see one more tool use it (not just Bullhorns) and would like to see more research into how to resume an SSE conn.
=> SAK-47489 this disables SSE for Bullhorns and modifies the fetch to the /direct/ endpoint

library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
In a site with many files or folders in Resources, when displaying the menu with title "All site files", the last item is displayed outside the space reserved by the container.  As can be seen in [SAK-47415](https://sakaiproject.atlassian.net/browse/SAK-47415).
=> SAK-47415. Resources: drop-down menu content exceeds parent's size

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-criteria.js
When trying to rename an criterion group as an instructor, it fails and an error will be promoted in the browser console. This happens, because `site-id` and `rubric-id` is not passed to the criterion group, so the request is being made to `undefined` site and rubric which will cause an permission exemption.
Also removed the token attribute, which seems to be a thing of the past.
=> SAK-47519 Rubrics: Criterion groups can not be renamed by an instructor

gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-47465
After changes, names apppears as it looks in the main list:
=> SAK-47465 GradebookNG - Message Students - Alphabetically order the 'Show Recipients' list

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf, samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf
Jira: [SAK-46294](https://sakaiproject.atlassian.net/browse/SAK-46294) (screenshot)
- The label will always start next to the Radio button (not from next line).
- Now the section content will expand further to the right & added space between date input and its button.
=> SAK-46294 T&Q: Test Settings - Improve Text Wrapping around Radio Buttons for Exceptions

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Supports cross-referencing Lessons links with Discussions in site archive.
=> SAK-47526 Add Topic ID to Discussions archive (msgcntr)

library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js, library/src/morpheus-master/sass/base/_defaults.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
https://sakaiproject.atlassian.net/browse/SAK-47536
The reason for putting the message at the end of the HTML instead of at the beginning is because, when a browser for the visually impaired scrolls the page, it always shows that "exit full screen", when they don't even have a screen.
A couple of users complained to us about that. By putting it at the end of the document, as they were reading where they were interested and did not get to the end of the page, it was much more comfortable for them.
This change, as I said, was made because some people with sight problems told us about it.
Also, maximize button has been removed from mobile design.
=> SAK-47536 Full screen message should appear at the bottom on vm

lessonbuilder/tool/src/webapp/js/checklist.js, lessonbuilder/tool/src/webapp/templates/Checklist.html
The cancel button needs a 'formnovalidate' attribute. The jQuery validation for 'Save' should scroll to the top of the window to make the displayed error more apparent.
=> SAK-47167 - Lessons Checklist: Cancel button does not work

library/src/webapp/content/myworkspace_info.html, library/src/webapp/content/myworkspace_info_ca.html, library/src/webapp/content/myworkspace_info_es.html, library/src/webapp/content/myworkspace_info_ja.html, library/src/webapp/content/myworkspace_info_mn.html, library/src/webapp/content/myworkspace_info_tr_TR.html, library/src/webapp/content/myworkspace_info_zh_CN.html, library/src/webapp/content/server_info.html, library/src/webapp/content/server_info_ca.html, library/src/webapp/content/server_info_es.html, library/src/webapp/content/server_info_ja.html, library/src/webapp/content/server_info_mn.html, library/src/webapp/content/server_info_tr_TR.html, library/src/webapp/content/server_info_zh_CN.html, library/src/webapp/content/webcontent_instructions.html, library/src/webapp/content/webcontent_instructions_ca.html, library/src/webapp/content/webcontent_instructions_es.html, library/src/webapp/content/webcontent_instructions_ja.html, library/src/webapp/content/webcontent_instructions_mn.html, library/src/webapp/content/webcontent_instructions_tr_TR.html, library/src/webapp/content/webcontent_instructions_zh_CN.html, library/src/webapp/content/webdav_instructions.html, library/src/webapp/content/webdav_instructions_ca.html, library/src/webapp/content/webdav_instructions_es.html, library/src/webapp/content/webdav_instructions_ja.html, library/src/webapp/content/webdav_instructions_mn.html, library/src/webapp/content/webdav_instructions_sv.html, library/src/webapp/content/webdav_instructions_zh_CN.html, library/src/webapp/js/sakai-iframe-copy-classes.js
When the web content tool is added to a site, a language-dependent static HTML appears that does not display correctly according to the user's theme preferences.
This also occurs in other static HTML displayed as an iframe.
A new JS is added that copies, if in an iframe, the HTML and BODY tag classes to the web document inside the iframe.
=> SAK-47597 - Web content is not on dark mode

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/beans/AssociationTransferBean.java, rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/ToolItemRubricAssociation.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47654
We can get the ownerId from the rubric instead.
=> SAK-47654 rubrics: remove siteId from rubric association

sitestats/sitestats-impl-hib/src/java/org/sakaiproject/sitestats/impl/SitePresenceTotalImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47649
SST_PRESENCE_TOTALS has not null constraint in column LAST_VISIT_TIME and new rows are populated with data from SST_PRESENCES and column LAST_VISIT_START_TIME that has “default null”, so you have to avoid this using P_DATE column instead, that is also NOT NULL. Just restoring the original line from [SAK-31760: ORA-01407 Error with LAST_VISIT_TIME when site presence enabledRESOLVED](https://sakaiproject.atlassian.net/browse/SAK-31760) here lost in [SAK-39989: Sitestats: test failureCLOSED](https://sakaiproject.atlassian.net/browse/SAK-39989).
=> SAK-47649 SITESTATS Avoid NULL when recompiling sitestats

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47662
We already don't know what is the exact cause of the error in the Jira, but this should be checked to avoid the NPE.
=> SAK-47662 Roster - Avoid endpoint crash due to concurrent modification and NPE recovering search indexes

library/src/morpheus-master/sass/base/_extendables.scss, mailsender/api/src/bundle/mailsender.properties, mailsender/api/src/bundle/mailsender_es.properties, mailsender/tool/src/webapp/content/css/MailSender.css, mailsender/tool/src/webapp/content/js/mailsender.js, mailsender/tool/src/webapp/content/templates/compose.html
Jira: [SAK-45778](https://sakaiproject.atlassian.net/browse/SAK-45778) + img
- Arrange items using tab panels and lists.
- Verbal info about the checkboxes for multiple selection (SR + title).
- User list:
- dropdown icon for the button to show the list + action info and expanded status (SR + title).
- delimit area and make it scrollable when needed.
- click user label to select its checkbox.
- Screen Reader should also announce:
- the amount of btn-tabs and the one that is selected.
- which panel or list you are accessing.
- when there isn't any type of role/section/group or when there isn't any user related to an existing type. `aria-live`
- Use buttons instead of links.
=> SAK-45778 Email: Improve Accessibility and Design for Recipients selector

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
Related to [Commit #10378](https://github.com/sakaiproject/sakai/pull/10378)
Jira: [SAK-47700](https://sakaiproject.atlassian.net/browse/SAK-47700)
Reason: incompatibility with decimal comma based languages.
It makes sense to use type “number” as the input will always receive a score, and results in less checks on the backend.
So the best option would be to modify the backend, but by the way it’s coded, a lot of extra inputs/logic should be modified, taking longer than expected. Then, this should be a temporal patch.
=>  SAK-47700 Assignments: Get back to "type text" for bulk grading input

common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
The URI provided here isn't a real path on www.sakailms.org but that doesn't matter because it just needs to be unique.
=> SAK-47702 Add sakai namespace prefix to site archive XML files

kernel/kernel-impl/src/main/java/org/sakaiproject/messaging/impl/UserMessagingServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-47540
This fixes an issue with the user messaging service where an attempt to
add the preferences link to outgoing emails fails due the lack of a
user's home site.
=> SAK-47540 kernel: warn if user site doesn't exist yet

common/archive-api/src/main/java/org/sakaiproject/archive/api/ArchiveService.java, common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
And define a constant for the namespace string
=> SAK-47702 Add namespace to additional site archive .xml files

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java
Adds support for site groups in the site.xml exported by Site Archive.
Both groups and sections are supported, as sections are decorated groups with additional properties defined. group properties are included in the export.
=> SAK-47777 Implement toXml for groups and include site groups in site XML

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-tool/tool/src/java/org/sakaiproject/portal/tool/ToolPortal.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java
Jira: [SAK-47829](https://sakaiproject.atlassian.net/browse/SAK-47829)
=> SAK-47829 MathJax: Apply portalCDNQuery on mathjax-config.js imports

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/OpenForum.java, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/Topic.java, msgcntr/messageforums-app/pom.xml, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/OpenForum.hbm.xml, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/OpenForumImpl.java, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/Topic.hbm.xml, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/TopicImpl.java
This PR adds the option [defaulted to On] to send discussion forums/topics' opening and closing dates to Calendar when their access is set to be date-restricted. If the option is turned off, or the date restriction overall is turned off, Calendar events created for them will go away.
https://sakaiproject.atlassian.net/browse/SAK-43881
=> SAK-43881 Discussions add calendar events for opening and closing of discussion forums and topics

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
This PR allows externally-maintained Gradebook items to be updated with a Category ID as a parameter. It could be used with any tool that can send grades to Gradebook, but it's currently relevant as a part of an Attendance function we've recently made at University Of Dayton. The separate Attendance ticket and PR are on GitHub.
Ticket: https://github.com/sakaicontrib/attendance/issues/110
PR: https://github.com/sakaicontrib/attendance/pull/111
=> SAK-47743 Make GradingService.updateExternalAssessment accept a category parameter

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/actions/QuickEntryAction.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/QuickEntryPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkGradePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BulkGradePanel.java, gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js, gradebookng/tool/src/webapp/scripts/gradebook-quick-entry.js, gradebookng/tool/src/webapp/styles/gradebook-shared.css
This PR adds University Of Dayton's Quick Entry feature to Gradebook. It's a page that allows the user to rapidly enter grades for an assignment for many students on one form, eliminating the lag we've experienced waiting for the one-by-one saving that the main Gradebook table does. It has group filtering, and also offers bulk replacement of blanks for grades and comments.
https://sakaiproject.atlassian.net/browse/SAK-47725
=> SAK-47725 Gradebook: Add a Quick Entry form for rapid grading

library/src/morpheus-master/js/src/sakai.morpheus.responsive.menus.js, library/src/morpheus-master/js/src/sakai.morpheus.skipnav.js
The layer of gray is a mask that should only be enabled for mobile layouts. It is needed for those layouts because the tool menu will cover most of the screen. Thus, I've added a conditional for desktop layouts.
Furthermore, I've added some jQuery to grant focus to the first tool (an anchor element) in the tool menu so that something visible has focus when the user keystrokes accesskey-l.
=> SAK-42153: portal: Tools skip link turns screen gray

commons/tool/src/webapp/WEB-INF/templates/post.hbs, commons/tool/src/webapp/WEB-INF/templates/posts.hbs, library/src/morpheus-master/sass/modules/tool/commons/_commons.scss
…" values when the content is removed.
The change in post.hbs didn't seem like it was part of the problem, it just looked wrong, so I fixed it!
In posts.hbs, changing from a div to a span was enough to make it stop putting a `<br>` when the content was cleared out.
The scss change fixes the same issue when editing a post.  It was putting in `<span></span>` when the content was cleared.  So, the css rule puts content in there when empty.
=> SAK-47748 Commons creating/editing posts inserts default values when the content is removed

calendar/calendar-bundles/resources/calendar_fr_FR.properties, kernel/kernel-util/src/main/java/org/sakaiproject/util/ResourceLoader.java
https://sakaiproject.atlassian.net/browse/SAK-47776
We need the replaceAll
Seen here: https://www.tabnine.com/code/java/methods/java.text.MessageFormat/applyPattern
```
/**
* Translate a text string based on our i18n files.
* @since 3.1
*/
public static String i18n(ResourceBundle messages, String key, Object... messageArguments) {
MessageFormat formatter = new MessageFormat("");
formatter.applyPattern(messages.getString(key).replaceAll("'", "''"));
return formatter.format(messageArguments);
```
=> SAK-47776 Erreur de lecture de [dateAsString] sur le type [org.sakaiproject.tool.summarycalendar.ui.Day]

assignment/impl/src/java/org/sakaiproject/assignment/impl/sort/AssignmentSubmissionComparator.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentComparatorTest.java
When exporting submissions from an assignment, the grade spreadsheets use AssignmentSubmissionComparator, which has code duplication and minor inconsistencies from comparators used elsewhere in Sakai. Make it use UserSortNameComparator when appropriate.
=> SAK-46837 Assignment submission export should sorting correctly when there are spaces

roster2/bundle/src/bundle/roster.properties, roster2/bundle/src/bundle/roster_ca.properties, roster2/bundle/src/bundle/roster_es.properties, roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
Fix startup error with `sakai.demo=false` by setting candidateDetailProvider as an non required property.
Also add Spanish and Catalan translations for the special needs feature.
=> SAK-47992 Fix startup error with demo mode disabled

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, providers/sample/src/java/org/sakaiproject/provider/user/SampleCandidateDetailProvider.java, providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
Control decryption of candidate details by using one property 'encryptCandidateDetails'
Enabled by default, like 'encryptInstitutionalNumericID' was, which has been replaced by this commit.
=> SAK-47992 Add property to encrypt candidate details

providers/userdetail/src/java/org/sakaiproject/user/detail/CandidateDetailProviderImpl.java
When the CandidateDetailProvider is enabled it will need setter methods for its dependencies, so they can be injected.
=> SAK-47992 Add setters needed for injection to CDP

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
The autosubmit strings are a bit tricky, because either `header_extendedTime_due_date=Fechas de entrega` or
`header_extendedTime_retract_date=Fecha l\u00edmite de entrega` will be inserted for `{0}`. and I could not find out if `Fechas de entrega` has to be plural.
https://sakaiproject.atlassian.net/browse/SAK-48084
=> SAK-48084 Samigo: Add spanish translations

basiclti/basiclti-tool/src/webapp/vm/lti_tool_system.vm, lessonbuilder/tool/src/webapp/templates/BltiPicker.html, library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
In BltiPicker.html the JS object “modal” is not part of the DOM which is why addEventListener cannot be invoked from that object. Use of the ‘el’ object instead works.
Besides some CSS styling for the LTI iframe presented in the modal, I added some "data-" attributes to force the backdrop of the modal to be static-- without which it’s frustratingly easy to inadvertently close the modal while attempting to fill out multiple data entry fields.
=> SAK-48072 - Lessons: BltiPicker not working in Trinity

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages_es.properties
I Tried to base the translations on the rewording that has been made in English.
Does that look fine? else I can still change `Todas las secciones/grupos` to `Todas las usuarios/grupos`
=> SAK-48095 Samigo: Spanish Assessment Settings reword "Who can access this assessment?"

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
Changed bi-eye-fill icon to bi-eye-slash icon
Removed CSS strikethrough line (that was underlining the icon)
Aligned icon with header title, previously aligned with dropdown button.
https://sakaiproject.atlassian.net/browse/SAK-48103
=> SAK-48103 Gradebook: Change grades not released icon and position

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, library/src/skins/default/src/sass/base/_icons.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAccountNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm
https://sakaiproject.atlassian.net/browse/SAK-48115
@ern I want the below Sakai properties to be added for testing purposes on nightly server 23: 
**update:**  I have created a pr on sakai-nighlty branch :)
`portal.quicklink.info=Links open in a new window 
portal.quicklink.url.count=4
portal.quicklink.title.count=4
portal.quicklink.name.count=4
portal.quicklink.icon.count=4
portal.quicklink.url.1=https://www.sakailms.org/
portal.quicklink.title.1=Sakai Project Website
portal.quicklink.name.1=Sakai Project
portal.quicklink.icon.1=cl bi bi-globe
portal.quicklink.url.2=https://www.apereo.org/
portal.quicklink.title.2=Apereo Website
portal.quicklink.name.2=Apereo
portal.quicklink.icon.2=cl bi bi-globe
portal.quicklink.url.3=https://github.com/sakaiproject/sakai
portal.quicklink.title.3=Sakai …
=> SAK-48115: Trinity Portal: Add Quick Links Button

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeAnalytics.vm
This cleans up the 3 old properties that are long deprecated
* portal.google.analytics_id=UA-XXXXXX-XX
* portal.google.analytics_domain=yoursakaihost.edu
* portal.google.analytics_detail=true
And adds support for GA4.
I figured it be worth using a new property rather than re-using this old one since you can have both UA and GA4 sending events together.
=> SAK-48153 - Support Analytics GA4 since Universal is being deprecated

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteHierarchy.vm
Redundant breadcrumbs induce a confusing or disorienting UX, so the approach I propose is to omit the breadcrumb that indicates the current site if the current site isUserSite (i.e., a user's "Home").
=> SAK-48123 - Fix double Home entry on breadcrumb

library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
With respect to CSS selectors and styling, the font-awesome classes used by LTI tools (e.g., lti_tools.fa_icon and lti_controls.fa_icon) seem to conflict with the new "si" class, so I've retrofitted the (legacy?) font-awesome stuff to at least have fa icons display in Trinity. In that vein, the fa-tool-menu-icon class I added is intended to correct otherwise noticeable vertical misalignment between the icon and the tool title.
=> SAK-48135 - Trinity portal: Selected custom icon for LTI ignored

library/src/skins/default/src/sass/modules/tool/_base.scss
I placed the .modal-title in tool/_base.scss instead of _defaults.scss where the h1 through h6 rules are since not many class or id specific selectors seem to be defined in the latter.
=> SAK-48217 - Trinity: Remove excess margin for modal-title headings

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/IgniteEntityProvider.java
I thought refactoring this method through other classes might be useful. I was thinking of moving this method to the DeveloperHelperService but that seemed out of scope for this fix. It would also be nice if this could be used as an annotation.
All of the end points aside from the cacheNames are currently protected, but the metrics or a specific cache is blocked.
=> SAK-48042 - Ignite direct endpoint must be secured

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
https://sakaiproject.atlassian.net/browse/SAK-48247
Before:
After:
=> SAK-48247 -TRINITY: Navbar sites don't line up

rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/VelocityInlineDispatcher.java, rwiki/rwiki-tool/tool/src/java/uk/ac/cam/caret/sakai/rwiki/tool/bean/FullSearchBean.java, rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/full_search.vm
I'm speculating a bit, but I think rwiki was still using the old lucene style of searching?  I switched it so that the tool gets passed into the appropriate field instead of appended to the search terms.
Also, removed the html escaping from the results since we need to render the returned markup (matching search terms are bolded).  This should be consistent with the way the main search tool is working.
=> SAK-48105 rWiki search using incorrect namespace

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
If the SEB config mode is not UPLOAD, it the pre-delivery phase should just return success, because no action is needed.
Missing this check cause problems publishing assessments using SEB without uploaded config.
=> S2U-21 SEB: Only run pre-delivery phase for uploaded configs

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
When `titleDecoration` was an empty string, all white-spaces were removed from the title.
=> S2U-21 Fix whitespaces being removed from assessment title

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
Remove properties for SEB configuration that are useful for a demo (screen record/share), but should not be set in production.
=> S2U-21 SEB: Remove demo configuration properties

kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/serialize/impl/test/ByteStorageConversionCheck.java
This removes logging individual characters of which certain characters can cause the build to abort on some terminal settings when running tests.
=> SAK-48536 - Remove ByteStorageConversionCheck individual char log

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
I've reduced the height of the cell menu button to match Sakai 22 and before. I also moved the down arrow icon to be in the center of the button's active area.
=> SAK-48546 - Gradebook: Comment icon overlapped by cell menu button

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
Besides preventing clicks outside the modal, I've also included data-bs-keyboard="false" to prevent inadvertent ESC keystrokes from dismissing the modal. This conforms to the behavior of these modals in 22.x and earlier.
=> SAK-48585 Grader: Set modal backdrop to static

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48601
=> SAK-48601 Rubrics exception when more than 1 active association exists after a site import

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemDataIfc.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemCancellationListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/webapp/js/authoringQuestionCancellation.js, samigo/samigo-app/src/webapp/js/deliveryQuestionCancellation.js, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/ItemData.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.hbm.xml, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ItemFacade.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/PublishedAssessmentService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/ItemCancellationTest.java
This lets instructors cancel questions, which will give them a score of 0 and scores are recalculated.
Changes to `PublishedAssessmentService`:
1. Added method `preparePublishedItemCancellation` which will process cancellation of the items
2. Moved `regradePublishedAssessment` from `RepublishAssessmentListener`
`preparePublishedItemCancellation` is used by `ItemCancellationListener`
`regradePublishedAssessment` is used by `RepublishAssessmentListener` and `ItemCancellationListener`
`ItemCancellationListener` is called from Edit assessment page - `editAssessment.jsp`, when editing a published assessment (republishing). And also from the Questions ab Published Assessment -> Scores -> Questions `questionScores.jsp`
Item cancellation works like so:
1. Is called and sets pending cancellation …
=> S2U-14 Tests & Quizzes: Canceled questions and score re-calculation

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/rubrics-element.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading.js
On 23.x and Master, the Rubrics summary tabs to not behave properly on click; they all stay the same so that it can't be visually discerned which one is active/current. The current tab is also never disabled, which causes multiple copies of its content to appear if you click it again.
Using the same "instanceSalt" values that Adrian added to each tab's content div, this PR adds IDs to the tabs so that each may be individually selected for different styling and behavior when clicked.
I opened a Jira for this: https://sakaiproject.atlassian.net/browse/SAK-48616
=> SAK-48616 Add IDs to rubric summary tabs and restyle on click

library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
I added new classes for CSS styling predicated on the arrow-0, etc. classes recently introduced, but I break from that nomenclature to signal the class's purpose. 
I needed to add an !important to .rubrics-comment-popover to override a 'top' value that is (somehow) dynamically set within a style attribute of the target div.
=> SAK-48584 Rubrics: Adapt comment popovers to B-5

samigo/samigo-app/src/webapp/js/deliveryQuestionCancellation.js
In the delivery all `input`'s are disabled for cancelled questions. This adds the same functionality for `textarea`'s, which will disable the rationale input.
=> S2U-14 Disable rationale for cancelled Questions in delivery

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, library/src/skins/default/src/sass/base/_extendables.scss, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
The w_blue class needs to be maintained throughout all modals launched from the Grades tab in order to retain the 'X' close button at the top right corner of the modal. Re-adding this class for the "Add Gradebook Item" modal restores that close button.
I then simplified the selector in the CSS file for restricting the max-height across all modals in Gradebook.
=> SAK-48603 Gradebook: Multiple modals not scrollable

site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html
In ```site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html```:
```
<div class="row">
<div class="col-sm-8">
<label for="groupMembers" class="form-control-label block" th:text="#{groups.assigned.members}">Assigned Members</label>
<select name="groupMembers" th:field="*{groupMembers}" id="groupMembers" class="form-control" multiple="multiple">
.......
</select>
</div>
</div>
```
And In ```site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/fragments/javascript.html```:
```
//Initialize the select2 component
var searchPlaceHolderText = /*[[#{groups.multiselect.search}]]*/;
$('#groupMembers').select2({
placeholder: searchPlaceHolderText,
allowClear: true,
closeOnSelect: false
});
```
So, the issue occurred because the width of ```<select>``` or …
=> SAK-47240: Site Info > Manage Groups > Create New Group > New "Assigned Members" field is not responsive

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
https://sakaiproject.atlassian.net/browse/SAK-48627
Originally, the dependency on site.upd.site.mbrshp was introduced in RSTR-77 as permissions changes back then must have required this permission. They don't any longer.
=> SAK-48627 roster: remove the need for site.upd.site.mbrshp

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
The excludedFromGrade field of AssignmentGradeRecord is a Boolean allowed to be null. This allowance to be null also holds when examining the GB_GRADE_RECORD_T.IS_EXCLUDED_FROM_GRADE column in MySQL.
However, the excused field in GradeDefinition is a primitive Boolean. NPEs are thrown when attempting to set a null value for excused. 
I added a line that translates null values to the default of Boolean.FALSE, making the assumption that excused is a primitive boolean for a good reason.
=> SAK-48060 Gradebook: NPE for convertGradeRecordToGradeDefinition

kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
I also didn't see any usages of odftoolkit so I removed that one too.
=> SAK-46909 - Remove the last usage of itext in kernel from fr.opensagres

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java
This PR addresses SAK-48248:
https://sakaiproject.atlassian.net/browse/SAK-48248
RubricsServiceImpl.saveRubricAssociation required a rubric ID in order to save associations, but that value is blank when a user attempts to remove an association. Earle showed me that using NumberUtils.toLong on the blank value would return 0 in this case, which we can then process much more naturally than the try/catch statement that createLong required, as it would throw an error trying to parse the same blank. This code interprets a rubric ID of 0 as an indication that the existing association for the tool and item should be removed ["deactivated"].
I added a couple tests based on Earle's advice, and added another workflow to handle the case of an association that has been removed and needs to be …
=> SAK-48248 Rubrics: Allow removal of item associations by parsing blank rubric IDs as 0

library/src/skins/default/src/sass/modules/tool/navigation/_skipnav.scss, library/src/skins/default/src/sass/modules/tool/portal/_portal.scss, library/src/skins/default/src/sass/modules/tool/theme-switcher/_base.scss, library/src/skins/default/src/sass/themes/_dark.scss, login/login-render-engine-impl/impl/src/webapp/vm/defaultskin/xlogin.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeFooter.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeLoginNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeMobileFooter.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/header-snippet.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/profile-snippet.vm
https://sakaiproject.atlassian.net/browse/SAK-48682
1. Refined Header Layout: We've optimized the header layout to ensure intuitive access to various tools, even on smaller devices, for an improved browsing experience.
2. Revamped Theme Switcher Button: We've redesigned the theme switcher button to provide a sleek and modern appearance, complementing the overall user interface.
3. Improved Login Button & Popup: We've fixed the login button and login popup for mobile view.
4. Convenient Site Description Popup: Users can now close the site description popup by simply clicking anywhere on the page, providing a more user-friendly experience.
5. Enhanced Mobile Responsiveness for Created Tasks: We've resolved responsive issues for created tasks on mobile view, ensuring that users can easily …
=> SAK-48682 Improve Portal UI and Responsiveness on Smaller Devices

gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.java, library/src/skins/default/src/sass/base/_icons.scss, library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-sorter.css
I have posted to the SAK-48595 jira two "expected" screenshots for what my proposed restyling looks like.
I attempted to use a bootstrap class like "fs-6" to shrink down these icons, but I needed to go smaller with explicit CSS statements. Also, the fill versions of caret-up and caret-down improved the contrast needed for the background color of the buttons when the icons are at a font-size of 10px.
=> SAK-48595 Gradebook: Restyle sort order buttons to not overlap

library/src/skins/default/src/sass/modules/tool/iframe/_iframe.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
A screenshot of the expected two column layout which results from this proposed fix is attached to SAK-48661.
I removed the CSS styling for "#{$namespace}multipleTools .#{$namespace}sakai-iframe" to prevent one column from being higher than another when an iframe tool is presented as one of the columns (like we use at our institution's custom Gateway page).
=> SAK-48661 Trinity: Restore double column layout for Overview, etc.

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-readonly.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubrics-shared-list.js
This PR re-adds the backing for PDF downloads of Publicly Shared rubrics by correcting typos in the sakai-shared-list and sakai-rubric-readonly webcomponents, injecting a native site ID for the rubric in sakai-rubric-readonly, and granting public PDF access to any rubric that is public in RubricsServiceImpl.
https://sakaiproject.atlassian.net/browse/SAK-48678
=> SAK-48678 Rubrics: Enable PDFs of publicly shared rubrics for all users who can view them

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
I placed the responsive breakpoint between lg and md. Doing so between md and sm made the two columns look too confining for smaller screens. Below are screenshots for a desktop, tablet, and phone rendering of a two-column layout.
=> SAK-48703 Trinity: Two-column layouts should have one-column on phones

plus/tool/src/main/webapp/WEB-INF/templates/form.html
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48654
Screen readers will read the error message from the ```title``` in the ```<input>``` tag only after incorrect input has been submitted.
=> SAK-48654:  SakaiPlus: Screen reader should prompt the user to enter a value on initial tab to field instead of announcing invalid entry

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java
Null Pointer on org.sakaiproject.tool.messageforums.PrivateMessagesTool.processPvtMsgDraft
https://sakaiproject.atlassian.net/browse/SAK-48686
=> SAK-48686 Messages a draft message with no scheduled date can cause an NPE

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentToolUtils.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
The proposed solution resolves two distinct bugs:
The first fix in AssignmentToolUtils prevents calls to gradingService.setAssignmentScoreComment which throw IllegalArgumentExceptions for blank comments.
The second fix conditionally reroutes assignmentName values which-- instead of being the titles of gradebook items-- are now the IDs, at least for Sakai 23 & 24. Note however that prior to Sakai 23 & 24, the associations between assignments and gradebook items that originate from Gradebook are still based on gradebook item titles. This second fix assumes that continuity with those associations will still be upheld (without necessarily provisioning a one-time Quartz job to homogenize all such associations to be based on gradebook item ID).
=> SAK-48613 Assignments: Existing GB item not receiving scores

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student.js, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-summary.js
https://sakaiproject.atlassian.net/browse/SAK-48715
Rubric summaries loaded from sakai-rubric-student were never Salted with random unique IDs like summries from sakai-rubric-grading were, which could lead to duplicate IDs among the tags present on a page. I've updated sakai-rubric-student to use Adrian's salt numbers too.
I also initialized this.criteria on sakai-rubric-summary, as leaving it undefined would trigger needless console errors between renders of summaries.
=> SAK-48715 Rubrics: Salt IDs for summaries triggered from sakai-rubric-student, suppress console error

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-student-button.js
https://sakaiproject.atlassian.net/browse/SAK-48690
When dont-check-association is one of the attributes on a sakai-rubric-student-button, it will automatically hide the button every time because the rest of the visibility logic hinges on retrieval of the association data. This PR makes the button visible if dont-check-association is present when the user is an instructor, since the association data is necessary for determining visibility only when the user is a student.
=> SAK-48690 Rubrics: Show sakai-rubric-student-button when instructor, provide additional data in Assignments

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
The cause of the Settings view distortions is extraneous and/or misplaced closing div tags.
I've attached a screencast to demo the results of this proposed fix to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-48710).
=> SAK-48710 T&Q: Distorted settings view 

common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteArchiver.java
Some content attributes can show up with DAV namespace, so add this to the declaration.
=> SAK-48751 Archive add DAV namespace to Sakai archive xml

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.html
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48490
t appears that the issue with the blue button on the instructor's view has already been resolved somewhere. I only fixed the issue with the blue button in the student’s view.
=> SAK-48490: Gradebook: Print button is incorrect color and inconsistent between instructor and student views

lessonbuilder/tool/src/webapp/js/show-page.js
The 'url' is modified further below, causing an error which prevents the proper assignment of mm-display-type for YouTube URLs. This proposed fix defines the url back to a 'var' which fixes the bug.
Jira: https://sakaiproject.atlassian.net/browse/SAK-48762
=> SAK-48762 Lessons: Embedded YouTube videos don’t display via URL

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
Include inline audio files recorded in CKeditor and cross-site media resources as attachments in the Lessons archive.
=> SAK-48756 Lessons archiving fix

lessonbuilder/tool/src/webapp/templates/ShowPage.html
Besides fixing the ‘Prerequisites & Requirements’ div, I also fixed:
1. the default collapsed state for the ‘Visibility & Access’ div so that the collapse/expand arrow doesn’t point down (while the section is collapsed) by default 
2. the allocated column spacing for the Width and Height labels so that the latter does not wrap.
A screenshot of the proposed fix is depicted below:
=> SAK-48759 Lessons: Edit Multimedia modal needs ‘card’ div

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
https://sakaiproject.atlassian.net/browse/S2U-37
When adding an announcement always unchecked by default.
=> S2U-37 Announcements: Ability to highlight announcements

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48746
To resolve the issue, I removed the third parameter ```i.getName()``` in the following code:
```code
UILink link = UILink.make(container, ID, i.getName(), URL);
```
Additionally, I also adjust the inappropriate indentation caused by line 3648.
```code
}
else {
```
=> SAK-48746: Lesson: When the 'Open in New Window' setting is selected under 'Display Options', the 'Item Name' field appears empty.

library/src/skins/default/src/sass/modules/tool/editor/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-48747
=> SAK-48747 Trinity: 'Expand toolbar' in HTML editor is back on black in dark mode

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Avoid ambiguity about whether the optional forum and topic open and close dates are in server local time or UTC by exporting in UTC with a date/time format with explicit timezone.
=> SAK-47901 Use ISO8601 for archive date formats

library/pom.xml, roster2/tool/pom.xml, sitestats/sitestats-tool/pom.xml
I tested this both with and without running tests.
Just had to upgrade yuicompressor but there's no upgrade for minify-maven-plugin so that needs this explicit dependency and I removed the other that was commented out.
=> SAK-48511 - Apache Maven >= 3.9, some plugins are causing an error

kernel/api/src/main/java/org/sakaiproject/tool/api/Session.java, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/UsageSessionServiceAdaptor.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
The Home site is only collapsed immediately after login, via a new proposed Session attribute "JUST_LOGGED_IN". After applied to the portal this Session attribute is immediately removed. 
The screenshot below depicts the Home site collapsed immediately after login. After which, the Home site will be expanded when it is the current site.
=> SAK-48337 Trinity: Collapse Home after login to improve pinned site visibility 

library/pom.xml, library/src/webapp-filtered/editor/ckeditor.launch.js, master/pom.xml
Updated webjar abandoned repository by a new one with all changes required.
Related PRs with the actual changes:
- https://github.com/SedueRey/ckeditor-html5-video/pull/1
- https://github.com/SedueRey/ckeditor-html5-video/pull/2
Release: https://github.com/SedueRey/ckeditor-html5-video/releases/tag/1.1
Also, related Jira: https://sakaiproject.atlassian.net/browse/SAK-45131
=> SAK-48748 HTML Editor: Embedded Videos should have controls enabled by default

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48795
Attached a screenshot for Firefox and Chrome
=> SAK-48795: Gradebook / print icon alignment issue

library/src/skins/default/src/sass/modules/tool/gradebook/gradebook-sorter.css
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48780
Instead of using the previous method of adding icons before text with the ```#gradebookSorter .gb-sorter-sortable:before``` selector, we now utilize the ```si-grip-horizontal``` class to achieve the same result. This change was implemented in [SAK-48172](https://sakaiproject.atlassian.net/browse/SAK-48172) ```<span wicket:id="name" class="si si-grip-horizontal"></span>```.
[SAK-48172]: https://sakaiproject.atlassian.net/browse/SAK-48172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-48780: Gradebook: Item Order has a phantom f0c9 icon in Firefox

roster2/tool/src/webapp/js/roster.js
This fixes the NaN error, but there are still issues with the scroll-to-load content that I can't get figured out!
=> SAK-48373 - Roster: use a css class that actually exists

webcomponents/tool/src/main/frontend/js/sui-picture-changer/sui-picture-changer.js
The save button needed a data-bs-dismiss to dismiss the modal when saving the change. I also renamed the 'Done' button to 'Cancel'. I found the meaning of the former to be confusing, especially in relation to 'Save'. The button actually cancels without preserving changes made in the modal.
=> SAK-48407 Profile: Takes more steps to update a profile pic

webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
JIRA: https://sakaiproject.atlassian.net/browse/SAK-47516
```this.selectedGroups``` is an HTMLCollection and does not have a ```map()``` function. The ```...``` spread operator is used to convert the HTMLCollection to an array.
=> SAK-47516: Dashboard: Tasks widget - creating a group task fails, then blocks future task creation

msgcntr/messageforums-app/src/webapp/js/forum.js, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumDetail.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfAllMessages.jsp
I'm removing the client-side setupLongDesc function which seems vestigial and is causing the tool menu in the site nav to disappear. With setupLongDesc, I'm not observing the "moreDescription" logic actually working-- which seems redundant anyway given the methods attached to .toggle elements. Also the attachments, if present, should be hidden when the .toggle element is collapsed; the "View/Hide Full Description and Attachment(s)" labels would then make more sense. Removing setupLongDesc seems to fix that issue.
=> SAK-48729 Viewing a forum in Discussions hides the tools in sitenav

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionNavBean.java, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
This update to S2U-15 will:
1. Make the date-time display of the submission navigation be consistent with the time displayed in the assessment list
2. Remove the navigation to the assessment list when clicking the "Update" button while grading.
https://sakaiproject.atlassian.net/browse/S2U-15
=> S2U-15 Make submission date format consistent and remove navigation to list when clicking update

samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp
When saving the updated score of a submission, the score in the table of contents doesn't update. Adding back the `StudentScoreListener` will update the bean and fix the issue.
https://sakaiproject.atlassian.net/browse/S2U-15
=> S2U-15 Tests & Quizzes: Add back StudentScoreListener to Update button

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
The switch to BS 5 changed the edit link next to an embedded image from opening the multimedia dialog to opening the movie dialog, which broke everything. The link was labeled wrong previously, which was probably why it was accidentally switched.
=> SAK-48849 Lessons: Edit embedded multimedia was opening the wrong dialog

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
=> SAK-48928 GB: Incorrect icon for excused grades

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
I’ve attached screenshots of Assignments, Announcements, Resources, and Tests & Quizzes where my proposed fix restores a magnifying glass icon for the filter part of bootstrap-multiselect. 
With this proposed fix, I am overriding the default ‘filter’ parameter not only out of expedience. It seems like the class ‘fas’ found in the default for bootstrap-multiselect (since 0.9.16) is intentional; that ‘fas’ class is also used elsewhere in bootstrap-multiselect.js. We instead need an “fa” class for the magnifying icon to display.
=> SAK-48914 Search group icon missing for bootstrap-multiselect

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverrideLogPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditCourseGradeCommentPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/EditGradeCommentPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeLogPanel.java
I obviously don't have lots of test data locally, so if there are use cases where you would still need to escape these pieces, I'd be interested to hear about them!
=> SAK-48927 - Gradebook: Don't escape the strings when setting the panel titles

msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_ca.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_es.properties, msgcntr/messageforums-api/src/bundle/org/sakaiproject/api/app/messagecenter/bundle/Messages_eu.properties, msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/MessageForumPublishToFaqBean.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgDetail.jsp, msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsgPublishToFaqEdit.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java
- When the automatically created faq forum or topic is deleted, the private message page was broken. Now a new forum or topic is created. 
- A success message is displayed, after the message is published to faq
- The answer field was not displayed in the edit form, that's fixed as well
https://sakaiproject.atlassian.net/browse/S2U-27
=> S2U-27 Handle deleted forums/topic and other fixes

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EventLogMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/EventLogBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EventLogListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/model/DataTableColumn.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/event/ExportEventLogServlet.java
Fixes:
- Only English bundle being used for export
- Spanish bundle is Catalan, Catalan bundle is English
- UTF-8 encoding not specified in HTTP header for export
- Errors header not present in export
- IP Address column not present in export
- Datatables column configuration for IP Address column not defined 
https://sakaiproject.atlassian.net/browse/S2U-24
=> S2U-24 Tests & Quizzes: Event Log - Several fixes

gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48763
The reason for the issue is that an error is raised at the beginning of the ```setAssignmentScoreComment()``` function, preventing the grade from being populated in the Gradebook. 
To address this, the solution is to resolve the parameter checking. In my opinion, ```commentText``` can be an empty string, so the empty string checking for it can be removed. @adrianfish Is it correct?
=> SAK-48763 Gradebook: Scores are not visible for all students in group assignment

webcomponents/tool/src/main/frontend/js/sakai-date-picker.js, webcomponents/tool/src/main/frontend/js/tasks/sakai-tasks-create-task.js
https://sakaiproject.atlassian.net/browse/SAK-48818
The basic problem with this issue is that on FF change is only fired when the time fields are populated, so due on the task is never set. Setting the default due to the current epoch millis will populate the datetime-local time fields and hopefully inform the user how to set those fields.
Mozilla has an open ticket about actually showing the time picker alongside the date picker, as Chrome does. *Hopefully*, this will be coming down the pipeline soon.
https://bugzilla.mozilla.org/show_bug.cgi?id=1726108
=> SAK-48818 set due on defaultTask to be current epoch millis

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/AuthorSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ConfirmPublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js, samigo/samigo-app/src/webapp/js/deliverySafeExamBrowser.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/SecureDeliveryController.java
Fixes (Further documented on [S2U-21](https://sakaiproject.atlassian.net/browse/S2U-21):
- SEB-21-1: Spell checking radio button has no value in published settings
- SEB-21-2: Assessment settings not saved correctly when publishing without saving first
- SEB-21-3: Standard settings - Reload fails with Access denied error
[S2U-21]: https://sakaiproject.atlassian.net/browse/S2U-21?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> S2U-21 Several fixes

config/pom.xml, master/pom.xml, pack/pom.xml, webjars/ckeditor-a11ychecker/pom.xml, webjars/ckeditor-balloonpanel/pom.xml
This fixes [SAK-48998]. It looks like a previous commit pushed the antrun plugin back to 1.3.
I tested some more and didn't see any issue upgrading everything up to 3.1.0. Everything is building and this fixes the issue.
[SAK-48998]: https://sakaiproject.atlassian.net/browse/SAK-48998?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-48998 Footer build info is missing

assignment/tool/src/webapp/vm/assignment/assignment_macros.vm, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar-opaqueUrlExisting.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportOmissionsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/PreviewImportedGradesPanel.html, help/help-component/src/bundle/TutorialMessages.properties, samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step2.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/auto_groups_step3.html, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/group.html, webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-summary.js
https://sakaiproject.atlassian.net/browse/SAK-48773
During the early stages of the Trinity project, the `bg-light` class from Bootstrap 5 was incorporated. However, it's time to eliminate it now. This is because it persistently overrides the appropriate background color when in dark mode.
=> SAK-48773 Calendar: Dark mode not obeyed + removed 'bg-light' class

assignment/api/src/java/org/sakaiproject/assignment/api/AssignmentService.java, assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48969
This issue occurs because the ```getGradableForSite()``` endpoint returns all submissions without filtering those that the current user does not have access to. To address this, we need to update the endpoint implementation to filter the submissions based on the access rights of the current user.
1. The ```getSelectedGroupUsers()``` function has been modified to make it ```public``` and the last parameter type has been changed from ```List``` to ```List<User>```. This change ensures consistency across all usages of the function, as all the places where it is used already pass a ```List<User>``` as the last parameter. 
2. I use ```assignmentService.allowAddSubmissionUser()``` function to fetch the users who are allowed to submit. …
=> SAK-48969 Assignments TAs unable to grade group submissions for their own section

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-49015
The issue arises because we are retrieving the title of the site instead of its Id. 
In course sites created by the Job Scheduler, there is no error since `site.getTitle()` is the same as `site.getId()`. However, in manually created course sites, `site.getTitle()` differs from `site.getId()`.
=> SAK-49015 Assignments Grader not loading

library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
https://sakaiproject.atlassian.net/browse/SAK-49025
=> SAK-49025 Samigo: Table page length select is small and not aligned with label (22.x)

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-48741
Now icons show up:
=> SAK-48741 Gradebook Icons not appearing

lessonbuilder/tool/src/webapp/templates/ShowPage.html
Probably during the transition to Trinity, the switchLink class for the Add Comment button was omitted. The switchEditors function defined in comments.js relies on the switchLink class for showing/hiding the button.
=> SAK-49046 Lessons: Add Comment button should disappear after clicked

site-manage/site-manage-impl/impl/src/bundle/notifyAddedParticipants.xml, site-manage/site-manage-impl/impl/src/bundle/notifyNewuser.xml, site-manage/site-manage-impl/impl/src/bundle/notifySiteImportConfirmation.xml, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/ETSUserNotificationProviderImpl.java
Jira: [SAK-49006](https://sakaiproject.atlassian.net/browse/SAK-49006)
Two issues where causing mails to be received only in English, regardless of the course or user language preferences.
- Only the default mail template was being stored on database. I'm fixing this by putting the default template last.
- `user.getReference()` was being used to get the user locale. It returns _"user/" + internal ID_ instead of just the _internal ID_.
By using `user.getId()` we can make `getRenderedTemplateForUser(...)` work fine.
For the DB changes to get applied,  _email_template_item_ has to be emptied and tomcat restarted.
Or use conversion script: https://github.com/sakaiproject/sakai-reference/pull/211
[SAK-49006]: https://sakaiproject.atlassian.net/browse/SAK-49006?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVm …
=> SAK-49006 Site Manage: The course and user locale is ignored for mail templates

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java
Adding si for each of the three tools (Assignments, Discussions, and T&Q) is needed for the icon to appear. However, if 'si' was moved to the class list for the element in ShowPage.html, it would break the font-awesome icons used for external tools, etc.
=> SAK-48806 Lessons no icons for links to other tools

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-association.js
Setting display to none caused the regression. I've also tested the removal of setting display to none with a site that does not contain rubrics; the rubric association does not display unless site rubrics are present. 
I'm not aware of a use case where this web component needs to be hidden via display:none.
=> SAK-47797 Gradebook: Unable to add Rubric to existing item

kernel/api/src/main/java/org/sakaiproject/springframework/data/SpringCrudRepositoryImpl.java
JIRA: https://sakaiproject.atlassian.net/browse/SAK-47604
The reason is that it raises an error when removing a detached instance in ```delete()``` method.
```
Removing a detached instance org.sakaiproject.grading.api.model.Permission#37
...
```
@ern Thank you for guiding me through the issue :)
=> SAK-47604 GB Adding or removing a TA's permissions causes duplicate values

site/admin-perms-tool/src/main/webapp/css/AdminSitePerms.css
Not sure if this is the best pattern or if the shadowed forms fit with the rest of Sakai's pattern but this was a quick fix and it does look quite nice now. Tested the buttons and the page on light and dark and checked for accessibility color contrast.
=> SAK-47801 - Admin Site Perms is rather difficult to read on dark theme

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementsUserNotificationHandler.java
Jira: [SAK-49093](https://sakaiproject.atlassian.net/browse/SAK-49093)
- If availability is updated with draft or **a beginning date in the future** remove existing notification.
- When removing alerts, take into account announcements that have been updated, not only the new ones.
[SAK-49093]: https://sakaiproject.atlassian.net/browse/SAK-49093?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49093 Announcements: Notifications persist despite setting future start date & after the first availability update

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
The intent of [this jira](https://sakaiproject.atlassian.net/browse/SAK-49107) is to remove excess noise from catalina.out, generated merely by instructors' navigating Sakai.
=> SAK-49107 Gradebook: Excess info logs from GradingServiceImpl

mailsender/tool/src/webapp/content/templates/compose.html
For a demo of the proposed changes to the display of controls in the Compose view of Mailsender, refer to the screencast attached to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49103).
=> SAK-49103 Mailsender compose view missing bootstrap classes

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementsUserNotificationHandler.java
Fix for [SAK-49093 Announcements: Notifications persist despite setting future start date ... #11763](https://github.com/sakaiproject/sakai/pull/11763)
Query was missing parenthesis.
=> SAK-49093 Announcements notifications persist despite setting a future start date - query update

samigo/samigo-app/src/webapp/jsf/shared/mimeicon.jsp
For details refer to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49110) and the screenshot below which depicts the Word icon restored by this PR.
=> SAK-49110 T&Q: Common MS Word docs missing icon

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_eu.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/webapp/jsf/delivery/beginTakingAssessment.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
This fixes the preview when SEB is active on an assessment, because buttons were clickable, but without action
Jira: https://sakaiproject.atlassian.net/browse/S2U-21
=> S2U-21 Tests & Quizzes: Support for Safe Exam Browser

signup/tool/pom.xml
This is 22.x direct fix because the commons-beanutils is deployed centrally in master
=> SAK-49123 Fix for NoClassDefFound on PropertyUtils.

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
Jira: [SAK-49137](https://sakaiproject.atlassian.net/browse/SAK-49137)
- The assignment title will be escaped for the zip filename.
- The escape function will replace some dash variants by a regular dash.
[SAK-49137]: https://sakaiproject.atlassian.net/browse/SAK-49137?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49137 Assignments: Some chars in assignment title affect download all submissions

.gitignore, providers/component/src/webapp/WEB-INF/unboundid-ldap.xml, providers/unboundid/pom.xml, providers/unboundid/src/java/org/sakaiproject/unboundid/AttributeMappingConstants.java, providers/unboundid/src/java/org/sakaiproject/unboundid/SimpleLdapCandidateAttributeMapper.java
https://sakaiproject.atlassian.net/browse/SAK-49138
Prior to the move to UnboundID, Sakai had the capability to encrypt (and subsequently decrypt when needed) candidate details through LDAP (for instance student/employee numbers).
This capability was not ported when the move from JLDAP to UnboundID was performed. This is a regression for any institution that was previously using this functionality with JLDAP.
=> SAK-49138: UnboundID > support encrypted candidate details

webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric.js
https://sakaiproject.atlassian.net/browse/SAK-47741
If you are the owner of the public rubric (meaning you have the rubric in both “Site Rubrics” and “Public Rubrics”), attempting to expand the public version of the rubric will expand the “private” version of the rubric because they share the same rubric ID.
If you are not the owner of the public rubric (meaning you only have the rubric in your “Public Rubrics” section), attempting to expand the public rubric will do nothing because you don’t have a corresponding rubric ID in your “Site Rubrics” section.
=> SAK-47741: rubrics > can't expand public rubrics

search/elasticsearch/impl/pom.xml, search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/ElasticSearchService.java, search/elasticsearch/impl/src/java/org/sakaiproject/search/elasticsearch/serialization/NodeStatsResponseFactory.java, search/elasticsearch/impl/src/test/org/sakaiproject/search/elasticsearch/NodeStatsResponseFactoryTest.java
https://sakaiproject.atlassian.net/browse/SAK-49153
=> SAK-49153 Search allow a sakai node to be a true client

site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/MainController.java, site-manage/site-group-manager/src/main/resources/Messages.properties, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/index.html
https://sakaiproject.atlassian.net/browse/SAK-49139
It is rather simple to delete a locked group using either multiple tabs, or concurrent edits with multiple users. The group deletion prevention is purely in UI code; there is no server side prevention when the UI has stale data.
=> SAK-49139 site-manage can delete locked groups using multiple tabs

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/renderer/TimerBarRenderer.java
https://sakaiproject.atlassian.net/browse/SAK-49156
When taking a timed assessment through the published assessment URL, there are some timerbar.js errors in the console. The timer in the UI doesn’t update while sitting on a question, it only updates when you progress to the next question. On the first question, the timer doesn’t show any time at all. The auto redirection after the timer expires can be a little delayed.
It should be noted that momentjs is hard-coded in several other places as well:
> $ ag "momentjs\/2.29.1"
portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeStandardHead.vm
87:        <script src="${pageWebjarsPath}momentjs/2.29.1/min/moment-with-locales.min.js$!{portalCDNQuery}"></script>
>
> samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/ …
=> SAK-49156: samigo > moment.js errors when taking a timed assessment through the published assessment URL

library/src/skins/default/src/sass/modules/tool/siteinfo/_siteinfo.scss, site-manage/datemanager/api/src/java/org/sakaiproject/datemanager/api/DateManagerService.java, site-manage/datemanager/impl/src/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java, site-manage/datemanager/tool/src/main/java/org/sakaiproject/datemanager/tool/MainController.java, site-manage/datemanager/tool/src/main/resources/static/js/initDatePicker.js, site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/tool_fragment.html
This pull request adds UX features to Date Manager and fixes several open issues. 
Fixed are the following:
From the re-opened [SAK-46023 - Date Manager > Nullable fields for some activities needs to be allowed](https://sakaiproject.atlassian.net/browse/SAK-46023)
- Tests & Quizzes hide feedback date - No error, but no change in the settings. When you reload date manager, these dates re-appear
- Announcements start/end dates - “Uncaught Error” in Date Manager when trying to save after clearing out dates
- Lessons hide until date- “Uncaught Error” in Date Manager when trying to save after clearing out dates
Also fixed:
- [SAK-46212 - Date Manager: unable to change announcement dates if open date set without hide date](https://sakaiproject.atlassian.net/browse/SAK-46212)
- [SAK-48788 - Date …
=> SAK-49082 DateManager improvements to additional nullable date support

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/AssignmentPicker.html, lessonbuilder/tool/src/webapp/templates/Checklist.html, lessonbuilder/tool/src/webapp/templates/EditPage.html, lessonbuilder/tool/src/webapp/templates/ForumPicker.html, lessonbuilder/tool/src/webapp/templates/QuizPicker.html, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Refer to the [corresponding jira](https://sakaiproject.atlassian.net/browse/SAK-49177).
Note that for Checklists, the checklist title needs to have a value for the spinner logic to be invoked. Otherwise, the disable and spin invocation would conflict with extant form validation behavior. 
I intentionally avoided using jquery for the corresponding logic within the onclick attribute. Furthermore, I needed to avoid using '&&' for a logical-AND within onclick-- otherwise the RSF template for Checklist.html encounters a syntax error; thus, I used nested if statements to workaround that problem.
=> SAK-49177 Lessons several buttons are missing spinners

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/BeginDeliveryActionListener.java, samigo/samigo-app/src/webapp/js/authoringSecureDeliverySettings.js
**IMPORTANT**
Both problems with seb.enabled=site
- siteId is null
```
023-08-17T11:21:43,811 DEBUG [org.sakaiproject.event.impl.ClusterEventTracking$$EnhancerBySpringCGLIB$$e098a3c6] umu.sakai.login.event.UmuLoginEvent.update Evento: sam.assessment.submit.from_last::siteId=null, submissionId=2505840
2023-08-17T11:21:43,811 DEBUG [org.sakaiproject.event.impl.ClusterEventTracking$$EnhancerBySpringCGLIB$$e098a3c6] umu.sakai.login.event.UmuLoginEvent.update Evento: sam.assessment.submit.click_sub::siteId=null, submissionId=2505840
2023-08-17T11:21:43,811 DEBUG [org.sakaiproject.event.impl.ClusterEventTracking$$EnhancerBySpringCGLIB$$e098a3c6] umu.sakai.login.event.UmuLoginEvent.update Evento: sam.assessment.submit.checked::siteId=null, …
```
=> S2U-21 5.1.1.17 Tests & Quizzes: Support for Safe Exam Browser

site-manage/datemanager/tool/src/main/webapp/WEB-INF/templates/index.html
The main fix is 
`+              url: window.location.href.replace(/#.*$/, '') + '/date-manager/update',`
I used the error handler to help debug this so I left it in. Normally that shouldn't be ever hit but I think it would be useful to retain. There was an error handler code in the success method and I don't know how that would ever trigger.
=> SAK-48579 - Site Info: Screen Reader/Keyboard Users Unable to Edit Items Using Date Manager

library/src/skins/default/src/sass/modules/tool/profile2/_profile2.scss, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyBusinessDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyContactDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInterestsDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyNamePronunciationDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStaffDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStudentDisplay.html, profile2/tool/src/webapp/javascript/profile2.js
This feels a little bit of a hack but I couldn't figure out how to get this to work with how this page was implemented otherwise.
My idea was to set all of the divs to be tab navigable. And when then the edit button will be displayed. When you navigate to another div it will just clean up all the edit buttons.
The _best_ way might be to redesign this page to not have hidden buttons like this, and I'm not sure why it's implemented this was with the hidden buttons.
The downside of this is that the last edit button will remain if you tab past the last element. And you also can't directly shift-tab to the previous edit button as you'd have to shift-tab then tab again to get to edit. 
If there's a better way someone has to do this go for it, but this at least makes this fully navigable with …
=> SAK-48875 - Profile: Options for editing “Basic Information” and “Name Pronunciation” are no longer keyboard/screen reader accessible

chat/chat-tool/tool/pom.xml, help/help-tool/pom.xml, jobscheduler/scheduler-tool/pom.xml, jsf/jsf-tool-sun/pom.xml, jsf/jsf-widgets/pom.xml, jsf/myfaces-tool/pom.xml, jsf/myfaces-widgets/pom.xml, jsf2/jsf2-tool-sun/pom.xml, jsf2/jsf2-widgets/pom.xml, kernel/kernel-impl/pom.xml, master/pom.xml, msgcntr/messageforums-app/pom.xml, samigo/samigo-app/pom.xml, sections/sections-app/pom.xml, signup/tool/pom.xml, syllabus/syllabus-app/pom.xml, user/user-tool-prefs/tool/pom.xml, userauditservice/tool/pom.xml, usermembership/tool/pom.xml
I'm still testing this locally but haven't seen any issue yet without these dependencies. 
I was basically running `mvn dependency:tree` and looking for any instances of  `xml-apis:xmlParserAPIs:jar:2.0.2:compile` to exclude. 
There are other xml-apis like `xerces:xmlParserAPIs:jar:2.6.2:compile` but they don't *seem* to cause an issue with this.
Though looking at the xerces:xmlParserAPIs, it seems like that's really old too and we shouldn't need that one either anymore. That appears to be used directly by rwiki and announcement. And indirectly included a few other places by these other old dependencies. 
* `org.apache.pluto:pluto-descriptor-impl:jar:1.1.7:compile`
* `org.apache.pluto:pluto-container:jar:1.1.7:provided`
* `xom:xom:jar:1.1:compile`
It seems like since these are included in …
=> SAK-46857 Eclipse IDE the package org.w3c.dom is accessible from more than one module: <unnamed>, java.xml

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html, library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Adds client side file size testing vs sakai.properties limit for Lessons tool:
- File size test when adding content links, embedding content, uploading ZIP files content 
- if size limit exceeded a warning banner is displayed and the Save button is disabled
- removing file(s) such that limit is no longer exceeded removes the banner and re-enables the Save button
- displays file size (in KB or MB) next to file name
=> SAK-47868 Lessons client side check for exceeding file size limit before uploading

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/entityproviders/LessonsEntityProvider.java
Added missing dataDirectory field to response of lesson endpoint for the resource folder item type.
https://sakaiproject.atlassian.net/browse/SAK-49276
=> SAK-49276 Lessons: Add dataDirectory field to lesson endpoint for RESOURCE_FOLDER type

library/src/skins/default/src/sass/tool.scss
Jira: [SAK-49286](https://sakaiproject.atlassian.net/browse/SAK-49286)
`.reqStar & .reqStarInline` css classes are already beeing used for this matter in multiple tools, but there isn’t a global definition for them -most local implementations are missing too- resulting in not stylized asterisks.
[SAK-49286]: https://sakaiproject.atlassian.net/browse/SAK-49286?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49286 Library: Global style for Request Field Asterisks

kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-test/src/main/java/org/sakaiproject/test/SakaiTests.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalService.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/model/PinnedSite.java, portal/portal-api/api/src/java/org/sakaiproject/portal/api/repository/PinnedSiteRepository.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/repository/PinnedSiteRepositoryImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
This proposed PR revises the auto-pinning behavior introduced with [SAK-48809](https://sakaiproject.atlassian.net/browse/SAK-48809) such that auto-pinning would behave like the auto-favorites behavior before Trinity, except that auto-favoriting / auto-pinning would be enabled for all users (instead of controlled per user preference before Sakai 23). The test plan in [SAK-48948](https://sakaiproject.atlassian.net/browse/SAK-48948) has been revised to clarify distinctive changes to be fixed with this PR.  What's key though and not necessarily clear in the test plan is that this PR: a) auto-pins sites for instructors regardless of the published/unpublished state of the site, and b) honors unpinning events for all users by not re-pinning sites a user has explicitly unpinned.
Accordingly, in …
=> SAK-48948 Portal: Pinned status should behave like auto-favorites before Trinity

roster2/tool/src/webapp/js/card-game/card-game.js
Fix  "null" displayed instead of "0" in  info banner
https://sakaiproject.atlassian.net/browse/SAK-49271
=> S2U-42 SAK-49271 Card game: Fix "null" displayed in info banner

profile2/api/src/java/org/sakaiproject/profile2/model/ProfileImage.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileImageLogicImpl.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/CardGameController.java
https://sakaiproject.atlassian.net/browse/SAK-49311
The isDefault property on the ProfileImage is not handled by the new profile image editor. For the scope of the issue that caused this problem it makes more sense to not use this property. This might still be another issue depending on sakai.properties, I add a comment to the Jira regarding that.
=> SAK-49311 Cannot change / add profile photo

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/SecureDeliverySeb.java
The main change here is passing the published assessment id to the `secureDelivery.isSecureDeliveryAvaliable` call. This will give some context so the seb module can figure out the siteId even when the assessment is not taken through the portal. The param is added to the places that are related to the delivery.
=> S2U-21 Tests & Quizzes: Fixes seb.enabled=site

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/EditAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/RepublishAssessmentListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/TestsAndQuizzesUserNotificationHandler.java, webcomponents/bundle/src/main/bundle/sui-notifications.properties, webcomponents/tool/src/main/frontend/js/sui-notifications/sui-notifications.js
This implementation does consider delays and exceptions for users/groups
=> SAK-42608 Samigo display user notifications for available assessments

pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Banners.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/acknowledgements/AcknowledgementStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/banners/BannerStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/rest/PASystemEntityProvider.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/PASystemServlet.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/handlers/BannersHandler.java
https://sakaiproject.atlassian.net/browse/SAK-43953
=> SAK-43953 PA System: Banner Dismissal Resets Upon Any Form of Update

announcement/announcement-api/api/src/bundle/announcement.properties, announcement/announcement-api/api/src/bundle/announcement_ca.properties, announcement/announcement-api/api/src/bundle/announcement_es.properties, announcement/announcement-api/api/src/bundle/announcement_eu.properties, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/entityprovider/AnnouncementEntityProviderImpl.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementActionState.java, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements.vm, lessonbuilder/tool/src/webapp/js/announcements.js, library/src/skins/default/src/sass/modules/tool/announcements/_announcements.scss, library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss, library/src/skins/default/src/sass/modules/tool/synoptic/_synoptic.scss
It looks like that:
When creating an announcement:
In announcement page:
In the homepage:
In content page (lessons) > when embedding the announcements:
=> S2U-37 5.2.1.2 Announcements: Ability to highlight announcements - Master

webcomponents/tool/src/main/frontend/js/grader/sakai-grader.js
…match.  This usecase comes from the browser suggesting a value that you choose (with the mouse, I suppose), therefore not having a key event.
=> SAK-49401 SakaiGrader check e.key is undefined before matching

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
Jira  [SAK-47385](https://sakaiproject.atlassian.net/browse/SAK-47385)
This affects published exams that have been imported from another site, and were present on a lessons page that has also been imported. They won't show for students until the instructor views the lessons page.
To fix it:
On the isItemVisible method
Before checking if the assessment is published or not, [getEntity(...)](https://github.com/sakaiproject/sakai/blob/defdc46fdd6597978006ddf446b0bece3a1a2c4a/lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/SamigoEntity.java#L293) will update the assessment id from "sam_core/x" to "sam_pub/x" if it is present on SAM_PUBLISHEDASSESSMENT_T table (published on samigo).
[SAK-47385]: https://sakaiproject.atlassian.net/browse/SAK-47385?atlOrigin=eyJpIjoiNWRkNTlj …
=> SAK-47385 Lessons: Links to T&Q not visible in imported site unless instructor visits the page

admin-tools/src/webapp/js/userEditValidation.js
This somewhat awkward conditional is necessary for both [SAK-49446](https://sakaiproject.atlassian.net/browse/SAK-49446) and [SAK-48161](https://sakaiproject.atlassian.net/browse/SAK-48161) to pass. The use of a conditional like "(pwcur)" -- i.e., without comparing it to null-- makes SAK-48161 fail.
[SAK-49446]: https://sakaiproject.atlassian.net/browse/SAK-49446?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
[SAK-48161]: https://sakaiproject.atlassian.net/browse/SAK-48161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49446 - Changing Passwords in Admin is Broken

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/Task.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/TaskService.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/UserTask.java, kernel/api/src/main/java/org/sakaiproject/tasks/api/repository/UserTaskRepository.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/TaskServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/tasks/impl/repository/UserTaskRepositoryImpl.java, kernel/kernel-impl/src/test/java/org/sakaiproject/tasks/impl/test/TaskServiceTest.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/TasksController.java
https://sakaiproject.atlassian.net/browse/SAK-48446
=> SAK-48446 tasks. Do not show unstarted tasks

kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, master/pom.xml, search/search-impl/impl/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-49497
https://cwiki.apache.org/confluence/display/TIKA/Migrating+to+Tika+2.0.0
=> SAK-49497 Update Tika Parsers and dependencies

basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/UserFinderOrCreatorImpl.java, plus/api/src/main/java/org/sakaiproject/plus/api/PlusService.java, plus/api/src/main/java/org/sakaiproject/plus/api/repository/MembershipRepository.java, plus/impl/src/main/java/org/sakaiproject/plus/impl/PlusServiceImpl.java, plus/impl/src/main/java/org/sakaiproject/plus/impl/repository/MembershipRepositoryImpl.java, plus/impl/src/main/webapp/WEB-INF/components.xml, plus/provider/src/bundle/plus.properties, plus/provider/src/main/java/org/sakaiproject/plus/ProviderServlet.java
While investigating several other JIRAs, I did a detailed review and testing of the Plus "first launch" code because I thought those JIRAs were caused by my code.  After all the investigation of those JIRAs it turns out the tutorial was the problem all along so I moved the First launch cleanup to a new JIRA.
But during the review, in hopes of catching whatever error was happening, I strengthened some areas of the first launch code.
Some error messages have been improved, some error messages have been added, some extra checking has been added to catch inconsistencies in new site setup earlier, and the initial roster pull has been moved from a Thread in ProviderServlet to an Executor in the PlusServiceImpl - following the example in RefreshAuthZGroups.
This is the pull request formerly …
=> SAK-49486 Plus improve launch logic and use executor pattern for NRPS retrieval

.github/workflows/maven.yml, assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/FormattedTextImpl.java, kernel/kernel-impl/src/main/webapp/WEB-INF/util-components.xml, kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/FormattedTextTest.java
Legacy Sakai databases use utf8mb3 meaning that 4-byte emojis cannot be stored as a native character. New Sakai orgs or orgs that can do a complete conversion should use utf8mb4 instead.
This code uses an emoji library to convert emojis into the HTML entity. 
We should probably consider changing the default in Sakai or doing automatic detection of the database.
=> SAK-49162 Kernel convert 4-byte emojis into HTML entities before saving

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentServiceTest.java
Jira: [SAK-49294](https://sakaiproject.atlassian.net/browse/SAK-49294)
> In Lessons, the student can't access the group assignment (to which he belongs) despite having completed the prerequisite
An assignment with assigned group(s) will be managed through a single ACCESS group on Lessons.
To access the assignment after completing the prerequisite, the user should be automatically added to the ACCESS group - if it's present on the original group(s).
To allow this behavior to work, membership won't be locked for ACCESS groups ✅ 
___
Also within this commit, the locks won't be removed for the initial group after being 'replaced' by the ACCESS one.
As they can prevent inconsistent behaviors.
_img B/A this fix - result of setting "Don't release item until all prerequisites are completed"_ …
=> SAK-49294 Group assignments with prerequisites inaccessible in Lessons

library/pom.xml, library/src/skins/default/src/sass/modules/tool/editor/_base.scss, library/src/webapp/js/headscripts.js, master/pom.xml, portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/EditorRegistryImpl.java
This should be broken until the library gets deployed to Maven Central.
=> SAK-49518 CKEditor: Upgrade CKEditor from 4.21.0 to 4.22.1

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Jira [SAK-49312](https://sakaiproject.atlassian.net/browse/SAK-49312)
I'm following the existing `prerequisite-info` logic to show the checkbox status.
Instead of relying on the `status-icon` (check/asterisk) - As the item having been completed should not affect the required status.
[SAK-49312]: https://sakaiproject.atlassian.net/browse/SAK-49312?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49312 Lessons: 'Require this item' doesn't remain checked on some items completed by the instructor

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
Jira [SAK-49339](https://sakaiproject.atlassian.net/browse/SAK-49339)
T&Q (with 1 exam) and Lessons (with the exam attached) is imported to a second Site.
There, instructor publishes the exam to make it available on Lessons.
When Lessons is accessed for the first time, a new access group has to be created to manage the exam item (as it has prerequisite options).
The issue comes when the first user is a student, as it won't have the permissions for this action to be performed.
So we're making an exception for this case.
Relocated `siteUpdAdvisor` as a global variable, to reuse the SecurityAdvisor.
[SAK-49339]: https://sakaiproject.atlassian.net/browse/SAK-49339?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49339 Lessons: Imported Tests with prereqs not accessible util instructor visits the page

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/util/LessonConditionUtil.java
When creating a text item right after opening a subpage currentPageItem is null on SimplePageBean. The UIComponent does not need to be rendered anyway in this view, so we can skip it.
=> S2U-35 Lessons: Fix nullpointer when creating text item after opening a subpage

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeBodyScripts.vm, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
The added if clause clause will prevent loosing the focus from the login fields to the focus on the portal wrapper.
Removing the "focus password field" code will prevent the username field from becoming focus while typing the password. This piece of code was already inactive due to the code focusing on the portal wrapper.
https://sakaiproject.atlassian.net/browse/SAK-49599
=> SAK-49599 Portal: Fix lost focus on eid and pw fields

webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-date-picker/src/SakaiDatePicker.js, webcomponents/tool/src/main/frontend/packages/sakai-date-picker/test/sakai-date-picker.test.js, webcomponents/tool/src/main/frontend/packages/sakai-tasks/test/sakai-tasks-create-task.test.js, webcomponents/tool/src/main/frontend/packages/sakai-tasks/test/sakai-tasks.test.js
tested and working locally
I'd like to be able to run the sakai-date-picker-test.js but can't figure out how/where it gets run. maybe adrian can show us and then i can add more tests
=> SAK-49664 use the user's preferred timezone to calculate epochMillis as relying on the current timezoneOffset is wrong

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/user/prefs/AnnouncementUserNotificationPreferencesRegistrationImpl.java, announcement/announcement-impl/impl/src/webapp/WEB-INF/components.xml, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/component-manager/src/main/bundle/org/sakaiproject/config/kernel.properties
Jira [SAK-49666](https://sakaiproject.atlassian.net/browse/SAK-49666)
We'll get the value form a property using `serverConfigurationService`, instead of the hard coded XML.
The default property value is set on _kernel.properties_
[SAK-49666]: https://sakaiproject.atlassian.net/browse/SAK-49666?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-49666 Preferences: Set users default option for Announcement notifications through a property

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGradingComment.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49729
Setting versionCheck to false here conforms to the solution applied elsewhere with the versionCheck setting in ckeditor.launch.js implemented for SAK-49518.
Also, note that to fix this for 23.x, a different implementation is necessary, given prior webcomponent reorganizing. The relevant source file to fix for 23.x would instead be:
webcomponents/tool/src/main/frontend/js/rubrics/sakai-rubric-grading-comment.js
=> SAK-49729 Rubrics: Adding comments displays CKEditor warning

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityMember.java, kernel/api/src/main/java/org/sakaiproject/authz/api/Member.java, kernel/api/src/main/java/org/sakaiproject/authz/api/SecurityService.java, kernel/api/src/main/java/org/sakaiproject/event/api/UsageSessionService.java, kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java, kernel/api/src/main/java/org/sakaiproject/user/api/User.java, kernel/api/src/main/java/org/sakaiproject/user/api/UserDirectoryService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroup.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseMember.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/UsageSessionServiceAdaptor.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java, kernel/kernel-impl/src/main/webapp/WEB-INF/site-components.xml, kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockSecurityService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/authz/impl/RoleSwapMembershipTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/site/impl/SiteServiceTest.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/RoleSwitchHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/RoleSwitchOutHandler.java
https://sakaiproject.atlassian.net/browse/SAK-49726
- user not being restored correctly
- session switching is not fundamental job of the SecurityService
- mock user email address improvements
- ComponentManager removal in RoleSwitchHandler
- general improvements in related places
- standardized naming convention to roleview
=> SAK-49726 Kernel view site as updates

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/PublishingSiteScheduleServiceImpl.java, site-manage/site-manage-impl/impl/src/java/org/sakaiproject/sitemanage/impl/UnpublishingSiteScheduleServiceImpl.java, site-manage/site-manage-impl/impl/src/webapp/WEB-INF/components.xml
jira: https://sakaiproject.atlassian.net/browse/SAK-49716
I revised PortalServiceImpl.canUserUpdateSite because securityService.unlock-- the basis for that method-- failed to deliver the desired value for students for the scheduled unpublishing test case. Whereas use of site.isAllowed(userId, SiteService.SECURE_UPDATE_SITE) instead provided consistent results for all test cases.
=> SAK-49716 Scheduled (un)publishing not pinning/removing sites correctly

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-49742
Building on a new method introduced with SAK-49726, check that the user is not a pseudo-user for 'View Site As' before proceeding to launch the tutorial.
=> SAK-49742 Portal: Prevent tutorial launching for View Site As role

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/FavoritesHandler.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-49725
For the user's desired order of pinned sites to be retained, FavoriteSites.favoriteSiteIds needs to be a List instead of a Set.
=> SAK-49725 Portal Organize Pinned should retain the order

library/pom.xml, master/pom.xml, meetings/ui/pom.xml, vuecomponents/tool/pom.xml
I built and started this up, everything seems like it's working as expected. The antrun-plugin looks like it's does the same thing as that other custom plugin we had.
=> SAK-49730 Global updating maven plugins for validation issues

kernel/api/src/main/java/org/sakaiproject/serialization/BasicSerializableRepository.java
in BasicSerializableRepository to avoid breaking archiving when there are control characters in text being archived.
=> SAK-49813 Use XML 1.1 serialization

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestFormatHelper.java
jira: https://sakaiproject.atlassian.net/browse/SAK-49811
Much of the logic added to saveExclude is adapted from the sibling methd, saveGrade. I also removed a redundant block of calls from the saveGrade method; the three deleted lines are a repetition of three lines directly above.
=> SAK-49811 Gradebook: ‘Excuse/Include Grade’ with percentage entry distorts scores

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
The logic implemented in the HTML template for rendering a 'd-none' was not sufficient for all conditions. I moved that logic from the HTML template to the function, GbGradeTable.cellRenderer.
=> SAK-49387 Gradebook: Grade Rubric option unavailable

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
This is untested code. Just want to capture our discussion from this morning
https://github.com/instructure/canvas-lms/blob/bacccef7d8c3cb7f2402ad14834219008438c5b8/spec/lib/lti/messages/jwt_message_spec.rb#L517
=> SAK-49855 LTI13 let tool know what scopes the endpoint can handle

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/SubmissionStatusBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/TotalScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScorePagerListener.java
Hi @bgarciaentornos, I spent a bunch of hours in here. It's really difficult code.
This reverts a lot of the code in SAK-48067 from Vincent. I tested paging, and it works with this code.
This also reverts some code from the Dynamic Rubrics: S2U-5 5.1.1.1 Tests & Quizzes: Dynamic Rubrics - MASTER (#12241)
My main question: is the Dynamic Rubrics code very important? It scares me because I don't understand it. And it seems to touch lots of code. Will it be maintained going forward?
Note that I also revert a bit of code from Fernando in SAK-47090 Test & Quizzes - Set a bigger number of students in Sakai Pager and set it as default selected value (#10374). I don't think that code had much of an effect as the number gets overridden via the setter.
=> SAK-49757 Samigo: fix attachment to a question response and cleanup

roster2/bundle/src/bundle/roster.properties, roster2/tool/src/handlebars/members_cards.handlebars
This link now says
```
<a href="http://localhost:8080/portal/site/~4372ed7b-ddd7-4b5a-a944-96cd80771e04/tool/d5fe1d77-9b5e-4a41-9055-bf0b85bc2340/viewprofile/e279941b-8ca8-4441-ac18-db68c5cba455" title="Click Here : Profile of Albert Albertson" aria-label="Profile of Albert Albertson">Click Here</a>
```
=> SAK-48898 - Roster Click Here needs to have the user's name explination for screenreaders.

site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js
Classic fix updated for a new UI!
=> SAK-49909 "u" or "d" cannot be entered as Tool Title

library/src/skins/default/src/sass/base/_extendables.scss
Not sure if this is the best fix or but this does fix it. I had to move some margins around and set the position to be relative for  the active tab so it would highlight over that but it looks like it's working nice and similar to the rest other non-bootstrap tabs.
I was kind of wondering if we could get rid of this custom code and theme this directly in bootstrap but this code hasn't been touched for awhile and maybe that was tried?
=> SAK-48624 Gradebook: No blue line around currently active tabs(Grade Summary/Student Review Mode)

library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
Added an explicit gold color to match the background.
=> SAK-49784 Gradebook: Extra credit warning is not readable in dark mode.

library/src/skins/default/src/sass/base/_extendables.scss
Feels like all of these backgrounds should have precedence for overriding bootstrap?
Not sure about the contrast of the `--successBanner-color` here but it looks a lot better than it currently is against purple.
=> SAK-49896 Lessons: Page layout checklists include custom CSS

library/src/skins/default/src/sass/modules/tool/editor/_base.scss
https://sakaiproject.atlassian.net/browse/SAK-49940
=> SAK-49940 ckEditor: enabled dark mode results in a white line between toolbar and content

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/PresenceConsolidation.java, sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/PresenceRecord.java
There have been test failures where the truncation of the timestamp resulted in a different day than the begin time of the presence. This is because the truncation of an Instant is UTC based and in some tests a Presence record is inserted into the test db with a Date that is based on an Instant that has not been truncated. Truncating the Instants in the tests would have solved this failures as well, but to keep the behavior consistent with the previous code and other stats I changed my code to use the system timezone - not UTC - for the date truncation of the presence times.
https://sakaiproject.atlassian.net/browse/SAK-47101
=> SAK-47101 Sitestats: Use server time for date truncation

library/src/skins/default/src/sass/modules/tool/lessonbuilder/_lessonbuilder.scss
Adding !important to the color overrides
Fixing Purple color
This is what it looks like with the fix. I'm not entirely sure if that's the problem here but the color styles were not getting precedence.
=> SAK-49895 Lessons border color property  of css class .col<color>-trans takes no effect

site-manage/site-group-manager/src/main/java/org/sakaiproject/groupmanager/controller/ImportController.java, site-manage/site-group-manager/src/main/webapp/WEB-INF/templates/import_confirmation.html
Jira: https://sakaiproject.atlassian.net/browse/SAK-48749
The CSV file in the jira's test plan has a non-printable character: first line, first character. Removing such characters when parsing the CSV file results in expected behavior.
I also styled two buttons in the Bulk Creation confirmation view that were missing bootstrap styling.
=> SAK-48749 Site Info / Manage Groups ->Bulk creation creates duplicate groups

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricCriteria.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49921
Besides sakai-item-delete, the sakai-rubric-criterion-edit needs updating too, in light of a pending fix to its tooltip in SAK-49934. Empirically testing with a "this.requestUpdate" at the end of criterionEdited method does not propagate the necessary changes to these webcomponents. Furthermore, the absence of this.requestUpdate doesn't produce the desired changes either, so I left it at its current position (line 311).
=> SAK-49921 Rubrics: Removing a newly-created criterion before refreshing the page shows the wrong name

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudent.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49933
I changed the 'instructor' type from Boolean to String because this.instructor would return 'true' for cases other than setting the attributed, instructor="true". This is important so as not to display the tab row (and especially not the summaries) to students (e.g., when sakai-rubric-student is used in Gradebook for students).
=> SAK-49933 Rubrics rubric statistics feature not working in gradebook

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGradingComment.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49867
I added more conditional logic on line 97 to prevent cases where the instructor clicks inside the ckeditor but doesn't type anything and clicks out of the popover. Some cases were counting these as differences such that the 'draft' alert would display.
On line 108 I introduced a requestUpdate call because the word balloon icon would not update to 'active' after a comment is added (and before dismissing or continuing on with grading in the rubric modal). Inserting it within this block as opposed to after the hideToolTip call doesn't seem to cause any noticeable issues, so I kept it within the block so as not to store block's conditional as a variable (to refer to it below hideToolTip and invoke requestUpdate).
=> SAK-49867 Rubrics comment displays undefined when instructor grades

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/model/Rubric.java
Jira: https://sakaiproject.atlassian.net/browse/SAK-50052
Note that the scope of this fix does not repair rubric listings already imported without this fix. (Some could be fixed if edited to prompt the update of max points, but those would likely be a minority.)
=> SAK-50052 Rubrics max points do not display for imported rubrics

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/QuestionPoolMessages_es.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java
Jira [SAK-50016](https://sakaiproject.atlassian.net/browse/SAK-50016)
This is an issue we've experienced at UPV, although I haven't been able to reproduce it on nightly servers. Anyway, catching the exception should be harmless.
This makes sure the export is successful despite exceeding the maximum char length in a cell.
It will also set a message in the problematic cell informing that something went wrong and the possible reason:
"ALERT: Reached cell character limit. Probably due to a file being inserted directly, instead of its link to Resources"
[SAK-50016]: https://sakaiproject.atlassian.net/browse/SAK-50016?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-50016 Samigo handle cell character limit exception for question pool export

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/snippets/search-snippet.vm
Looks like the webcomponent is actually creating something calledcalled `sakai-search-input `and not `sakai-search-field.` 
Not sure if we want to be more explicit about that as an attribute for this webcomponent or not?
=> SAK-50062 Console log error for incorrect use of label for

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/site.vm
https://sakaiproject.atlassian.net/browse/SAK-50055
The pageBody div was removed in the trinity refactor. Instead of adding a the div back it seemed reasonable to simply add it to an existing div that encompasses the same elements as pre trinity.
=> SAK-50055 Portal add pageBody id to portal

site-manage/pageorder/tool/src/java/org/sakaiproject/site/tool/helper/order/impl/SitePageEditHandler.java
This currently includes site.visit, site.upd, and rubrics.manager.view
=> SAK-49876 SiteManage tool order certain permissions can never be granted to students

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
https://sakaiproject.atlassian.net/browse/SAK-49150
=> SAK-49150 Gradebook TA not in group, but with permission to grade a group, cannot actually grade

library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/authorSettings_attachment.jsp, samigo/samigo-app/src/webapp/jsf/author/inc/extraCreditSetting.jspf, samigo/samigo-app/src/webapp/jsf/author/item/audioRecording.jsp, samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp, samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp, samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp, samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp, samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp, samigo/samigo-app/src/webapp/jsf/author/item/itemHeadings.jsp, samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp, samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp, samigo/samigo-app/src/webapp/jsf/author/item/shortAnswer.jsp, samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings_attachment.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/addPool.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp, samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
https://sakaiproject.atlassian.net/browse/SAK-48398
=> SAK-48398 Samigo Improve Question texts layouts inconsistency

jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/SoftSiteDeletionJob.java
Delete AuthzGroups for groups when running he “Expunge softly deleted sites“ job for  softly deleted site.
=> SAK-48820 Scheduler SoftSiteDeletionJob deleting AuthzGroups for groups

common/impl/src/java/org/sakaiproject/component/common/edu/person/SakaiPersonImpl.hbm.xml, common/impl/src/java/org/sakaiproject/component/common/type/TypeImpl.hbm.xml, kernel/kernel-impl/src/main/webapp/WEB-INF/ignite-components.xml
https://sakaiproject.atlassian.net/browse/SAK-49146
Pending work. We were talking about this problem some months ago :)
=> SAK-49146 Common switch TypeImpl to nonstrict-read-write cache strategy and atomic

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGradingComment.js
jira: https://sakaiproject.atlassian.net/browse/SAK-50004
The ‘Grade’ views in Discussions where rubrics are displayed occur within an iframe. The means for setting up the comment editor between 22.x and 23.x/25.x changed such that the latter breaks when displayed within an iframe. 
The solution proposed here resolves that critical issue by using a method to set up an editor used in Sakai 22 and earlier. However, that solution is not entirely satisfactory because only Bold and Italic buttons actually display in the toolbar. Underline doesn’t seem to be defined any longer (with 4.22?) when creating an editor via CKEDITOR.replace. I’ve attached a screenshot of the tools available when [config.toolbar is set to null](https://ckeditor.com/docs/ckeditor4/latest/api/CKEDITOR_config.html#cfg-tool …
=> SAK-50004 Rubrics criteria comments not saved while grading

basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
While this may seem related to the general LTI / Ckeditor issues identified in https://sakaiproject.atlassian.net/browse/SAK-50202 and https://sakaiproject.atlassian.net/browse/SAK-47327 it is not related to the JavaScript “bootstrap missing error” that causes those overall problems.
This just fixes the stores mistakenly showing up in both the top and bottom of the shopping cart dialog.
=> SAK-50205 - Fix display of stores in Shopping Cart Dialog

basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
This regression was introduced when the returnUrl serialization was switched from URL Encoding to Base-64 serialization in JIRA 49209 and a de-serialization was missed in one place.  This adds the missing de-serialization.
=> SAK-49944 - Fix Add External Tool (LTI 1.1) as an Assignment Type

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm
The following issues have been resolved:
- When collapsing a student or returning from the Grader or Submit on behalf of Student, the view no longer jumps back to the top.
- Assignments that are not visible to each student (group-specific assignments) are now filtered accordingly.
- The display of grades in the list has been improved.
=> SAK-49998 Assignments updates to group filtering, grades viewing, and navigation

announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java
Jira [SAK-50227](https://sakaiproject.atlassian.net/browse/SAK-50227)
In this case, the 'Access' options on the ‘Post Announcement’ view ([chef_announcements-revise.vm](https://github.com/sakaiproject/sakai/blob/cc81ae9ad4fff75bd7f0c9c6d42bb28a060dc3c3/announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm#L233)) are displayed based on `pubviewset`
The issue comes when returning from the 'Add Attachments' view, as the template reloads without `pubviewset` being added into
the context
[SAK-50227]: https://sakaiproject.atlassian.net/browse/SAK-50227?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-50227 Announcements access options reset after returning from attachments view with anon role enabled

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbGradeTable.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbGradebookData.java, library/src/skins/default/src/sass/modules/tool/gradebook/_gradebook.scss
Gradebook item titles and Category titles can overflow into adjacent cells (if the title doesn't have word breaks). Also column resizing allows narrowing of columns which can exacerbate the overflow issue while additionally introducing misalignment for gradebook - Student/Course grade columns may no longer line up with the grade book item columns for rows.
I have approached this by changing the overflow behavior to the use of ellipses instead of trying word wrap within the cells.
=> SAK-50094 Gradebook titles can overflow and grid can become misaligned

library/src/skins/default/package-lock.json, library/src/skins/default/package.json
Upgrading to 5.3 will require more changes to our dark mode codes
=> SAK-50230 Library Revert to bootstrap-5.2.0 due to broken dark mode

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
https://sakaiproject.atlassian.net/browse/SAK-50169
=> SAK-50169 Gradebook: Custom Export has a small and a large X to close the modal

sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/StatsUpdateManagerTest.java
The current log of the test failure does not help much with figuring out why the assert failed. Using `assertEquals`, we should see the duration values that caused the failure.
https://sakaiproject.atlassian.net/browse/SAK-47101
=> SAK-47101 Sitestats: Improve log output of test failure

profile2/api/src/java/org/sakaiproject/profile2/util/ProfileConstants.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ViewProfilePanel.java, profile2/util/src/java/org/sakaiproject/profile2/util/ProfileUtils.java
Much of the code changes in here are because I wasn't sure if adding locale support to all calls of this method would be be a regression or not, so I left that as false. I was looking at the code and it seems like it's using these strings in some places for internal use with the pickers and such and that might have problems if it was doing locale formatting. But we do want it for the display in this case.
=> SAK-50274 Profile: When looking at another user's profile, the birthdate is not formatted correctly

content/content-tool/tool/src/webapp/js/content.js, content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Jira: https://sakaiproject.atlassian.net/browse/SAK-50289
For expedience, I retained the predominant jquery syntax for proposed fixes in the JS file. While I’m not sure why the template seeds both the d-none and d-md-table-cell to the target elements, I make sure to remove one class before adding another when either showing or hiding a given element.
I recall that the ‘access’ class is (with Trinity) used either in portal or some framework in a broader way than with Sakai 22 and earlier. Thus, I supplanted it with “contentAccess” to distinguish between the intent in Resources and intent for “access” elsewhere.
I added d-flex and flex-row-reverse classes to relevant elements to prevent the Display Columns from jumping around when it’s clicked.
Finally, I reverted the styling of the Save …
=> SAK-50289 Resources display columns controls not hiding whole columns

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50290
For Sakai 25+ this fix depends on the PR (https://github.com/sakaiproject/sakai/pull/12722) for SAK-50073 to be merged to master. (That dependency is not required for Sakai 23.)
=> SAK-50290 rubrics remove adjusted score when removing rubric

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricGrading.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50073
For master/25.x the creation of the file SakaiRubricGrading.js for commit f5902019164ca2719cdc03645b424913a541c589 (SAK-48323) omits the line that I've restored (which fixes the bug). Curiously, when merging the fix to 23.x (commit 24b455c19e9bf5d6ee1ce5d508157b0f21400572) the line I've restored is already present (or not removed).
Thus, 23.x does not have this bug and this fix is not need for 23.x.
=> SAK-50073 rubrics can not grade if adjust scores is selected

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js
I researched this awhile and noticed that Offcanvas like Modal has a focus trap which is why this focus is unable to go into the CKEditor popups.
This comment clued me into this https://stackoverflow.com/a/75091146/3708872 but Offcanvas uses the same 
https://github.com/twbs/bootstrap/blob/e20cc0d660f72c12befbfcbe90eef2aa39655c48/js/src/offcanvas.js#L71
I'm not sure if there's a better way to handle this or if  there's a11y regressions but this seems to work with some basic testing I've done on this grader panel.
I did notice in an earlier jira you tried to simplify the editor panel mostly because of this error but it was mentioned that it was a regression from 22 and still gave users the capability of accessing these links.
=> SAK-49717 sakai-grader CKEditor does not accept text or a URL for comment when clicking link icon

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java
Jira: [SAK-50325](https://sakaiproject.atlassian.net/browse/SAK-50325)
Included `peerAssessmentInstructions` to the existing updateEntityReferences() process
Also simplified a bit the logic for the assignment instructions
[SAK-50325]: https://sakaiproject.atlassian.net/browse/SAK-50325?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-50325 Assignments: link migration not working for peer assignment instructions

assignment/tool/src/webapp/js/studentViewSubmission.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricStudentComment.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50262
Similar to the solution adopted for SAK-50010 and for the sake of consistency with that approach, this proposed solution jettisons the use of bootstrap popovers, supplanting them with bootstrap dropdowns.
The revision for the Assignments javascript is to cover a niche case where a student accesses their assignments feedback by clicking a link within a Lessons page. Note that the conditional loading of the bootstrap webjar library must be qualified. If it's loaded when the Assignments tool is not embedded within an iframe, then the dropdowns will not display when clicked (assuming a comment is present).
=> SAK-50262 Rubrics criterion comments don’t always display

scormplayer/wicket-tool/src/java/org/sakaiproject/wicket/ajax/markup/html/table/SakaiDataTable.java, scormplayer/wicket-tool/src/java/org/sakaiproject/wicket/ajax/markup/html/table/SakaiPagingNavigator.html, scormplayer/wicket-tool/src/java/org/sakaiproject/wicket/ajax/markup/html/table/SakaiPagingNavigator.java
Some cleanups I did here
* Cleaned up the code in `SakaiDataTable` that removes components and instead it just overrides the addToolBar to do nothing and adds them in afterward. This wasn't necessary for the fix but it seemed like a better pattern than was there and was something I'd tested earlier. I had to do this to delay to retain the pageable parameter, though it was set to `true `in all instances in Scorm so probably unnecessary.
* Converted the inputs to anchors in the html to match what's in the current base [PagingNavigator](https://github.com/apache/wicket/blob/master/wicket-core/src/main/java/org/apache/wicket/markup/html/navigation/paging/PagingNavigator.html). I believe this was the ultimate fix and these input's no longer worked with the Ajax pattern. 
Since it converted …
=> SAK-50308 Scorm while viewing results and clicking next page produces exception

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiItemDelete.js
…component gets used for deleting rubrics and criteria.  Deleting a rubric with ID 3 would generate the same elements as deleting a criterion with ID 3.  When that happens, triggering the modals is problematic.  New functionality will now include the type (rubric/criterion) when generating the IDs.
=> SAK-50334 Rubrics ensure dom element IDs are unique during rubric deletion

library/src/webapp/bundled-js/sakai.morpheus.session.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-50359
The dismiss_session_alert callback function when calling createDHTMLMask immediately calls that function which removes the portalMask div. Omitting this callback function prevents that, so that the portalMask div is removed when the timeout warning is dismissed by the user.
Also, the portalMask's z-index when set to 1300 overlaps the timeout warning modal. Setting it to 1000 places portalMask behind that modal.
Refer to the 'PortalMaskExpected-*.png' attachments in the jira for the results of implementing the proposed fix.
=> SAK-50359 Portal: Background not darkened when timeout warning displays

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, content-review/impl/turnitin-oc/src/main/java/org/sakaiproject/contentreview/turnitin/oc/ContentReviewServiceTurnitinOC.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
https://sakaiproject.atlassian.net/browse/SAK-50361
Enforces file names on Windows Operating Systems cannot contain the colon (':') character.
=> SAK-50361 Global avoid using commons-io FilenameUtils.getExtension()

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/OrphanPageFinder.java
Add null check when checking for orphaned Lessons pages. This can cause archive failures.
=> SAK-50377 Lessons safe initialization of topLevelPages for orphaned pages

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
Jira: https://sakaiproject.atlassian.net/browse/SAK-49894
The intent of this PR is to share how to fix the specific bug described in the test plan of SAK-49894, the core problem being in AssignmentEntityProvider. The approach I took was to add a new parameter “mergeOverride” that the Grader code could explicitly invoke to solve this issue without breaking some other scenario (which I don’t know if such exists, but erring on the side of caution I thought it might).
Furthermore, the introduction of ‘mergeOverride’ exposed another bug where the “grade” value that would be returned is not formatted for displaying to users. I remove this logic (lines 682-685), given that it seems redundant based on the if-else conditional immediately preceding it (unless there’s something subtle here that I’m …
=> SAK-49894 WC SakaiGrader distorts group assignment scores with overrides

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ActionSelectListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/PublishAssessmentListener.java
The idea here is to use a JSF attribute to tell the PublishAssessmentListener where we are coming from. 
There are multiple scenarios as the bulk publish introduced a new one:
1) Bulk publish from the authoring screen
2) Single publish from the authoring screen
3) Confirmed publish from the notification screen
4) Publish from the settings screen
=> SAK-50433 Samigo separate pathway for single publish and bulk publish

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiInterface.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
I reformatted the BltiEntity file and cleaned up old stuff. 
This in progress for now.  It even has some debug stuff that will be removed.
=> SAK-49826 Lessons LTI Learning App does not follow new page rules

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java
https://sakaiproject.atlassian.net/browse/SAK-50323
=> SAK-50323 announcementswc Allow super users to view announcements

postem/postem-app/src/main/webapp/WEB-INF/templates/create_gradebook.html
https://sakaiproject.atlassian.net/browse/SAK-44538
=> SAK-44538 postem Improve responsiveness of add screen

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission_withgrader.vm, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-group-picker/src/SakaiGroupPicker.js
After thoroughly testing the previous PR, I found that with the change, the selected student is lost, and the first one is set by default. Similarly (as was already happening), when changing groups, the displayed student is not retained if they are in the group being filtered.
=> SAK-44225 SakaiGrader keep the selected submission

lessonbuilder/tool/src/webapp/templates/ShowPage.html, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
Fixed the heading hierarchy structure on the Lessons tool page.
=> SAK-38024 Lessons accessibility incorrect heading structure on pages

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricAssociation.js
[S2U-34: 5.1.4.5 Assignments and Rubrics: Use Rubrics in Peer Review Assignments](https://sakaiproject.atlassian.net/browse/S2U-34) introduced a new feature in assignments to allow students to self-report using a rubric. The checkbox should be aligned with the other checkboxes (currently it looks almost like it’s part of Hide Rubric from Student) and a space is needed between the checkbox and the word Allow.
https://sakaiproject.atlassian.net/browse/SAK-49986
Also fixed the spacing of Adjust individual student scores.
=> SAK-49986 Rubrics allow students to self-report their work checkbox alignment and spacing needed

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
=> SAK-50134 Portal theme property for auto detecting dark mode should match documentation

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubrics.test.js
Add some tests to make sure all places are updated
=> SAK-50206 Rubrics update all nested components after a rubric title change

kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/LinkMigrationHelperImpl.java
During the import process, in the migration of links, it is checked whether the links are shortened, and then they are expanded. To do this, it checks if the link includes the string "http://bit.ly/ " or "/x/".
This check fails when we encounter an image inserted with its base64 encoding, a format in which images from the clipboard were pasted in previous versions of Sakai.
`<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAA... (rest of the base64 encoding)">`
This string is very long and is highly likely to include "/x/". As a result, a large number of images from a variety of tools are lost.
https://sakaiproject.atlassian.net/browse/SAK-50554
=> SAK-50554 Site Import Fails to Import Some Embedded Images

portal/portal-service-impl/impl/src/java/org/sakaiproject/portal/service/PortalServiceImpl.java, portal/portal-service-impl/impl/src/test/org/sakaiproject/portal/service/PortalServiceTests.java
https://sakaiproject.atlassian.net/browse/SAK-50572
=> SAK-50572 Portal don't remove recent sites from pinned

polls/tool/src/webapp/templates/votePolls.html, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePage.vm
I have resolved the responsiveness issue of the polls tool by using table-responsive. I observed that the grid system applied to the portal-main-container was interfering with the styling of table-responsive, so I replaced it with flex and added two classes: d-flex and flex-column. 
I'd love some feedback on changing the portal-main-container from grid to flex. 
Thanks!
=> SAK-50454 Polls improve voting ui responsiveness

basiclti/basiclti-tool/src/webapp/vm/lti_tool_insert.vm
This is a direct to 23.x merge
I fixed this as follows - if your set the “allow” value for title or launch, all my magic “clean stuff up” code leaves it alone.  If you set those values - they stay set.  That said - this is not a common use case.  I know it works with Tsugi and saves a lot of time and pasting stuff and nicely tests Dynamic Registration a lot.  But knowing how to patch the URL, and tweak all the check boxes is not something that I think folks do when installing a random vendor LTI tool - especially by Dynamic Registration.  So I hope this fixes your Tsugi / QA use case.   Let me know.
=> SAK-50558 LTI modify external tools form to simplify adding an LTI 1.3 single tool

meetings/tool/src/main/java/org/sakaiproject/meetings/controller/MeetingsController.java, meetings/ui/src/main/frontend/src/components/sakai-input.vue, meetings/ui/src/main/frontend/src/views/CreateMeeting.vue, microsoft-integration/api/src/java/org/sakaiproject/microsoft/api/MicrosoftCommonService.java, microsoft-integration/impl/src/main/java/org/sakaiproject/microsoft/impl/MicrosoftCommonServiceImpl.java
If, once the meeting is created, a mantain user is added to the site, in order to add that participant to the meeting there would have to be an option to update the meeting and also make the option that only organizers and co-organizers can present in the microsoft meeting configuration to be activated by default.
=> SAK-50592 Meetings default option and updating of teachers not included in the meeting

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java
https://sakaiproject.atlassian.net/browse/SAK-50616
Same patch as https://github.com/sakaiproject/sakai/pull/9020/files but on LTI1.3 method
=> SAK-50616 LTI 1.3 Synchronizing grades doesn't work well when Tomcat language's decimal separator is a comma

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, gradebookng/api/src/main/java/org/sakaiproject/grading/api/GradingService.java, gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java
Applying some retro-compatibility fixes for a better management of the gradebook Uid in the LTI integration. The idea is the LTI can work as always for regular sites, but we'll work too on improving the gradebook for groups + LTI mix (we'll add a warning in the meantime).
Also moving the initialization to the service and renaming it as the original method wasn't too specific.
=> SAK-49493 LTI fix gradebook uid bug and improve initialization

samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
https://sakaiproject.atlassian.net/browse/SAK-50635
In test & quizzes, there is an input that stores the variable attemptDate, which is the date and time when the student starts the exam. However, the value of this field is currently incorrect, as it only saves the date instead of both the date and time.
=> SAK-50635 Samigo incorrect value of hidden input for attempt date

assignment/tool/src/java/org/sakaiproject/assignment/entityproviders/AssignmentEntityProvider.java
https://sakaiproject.atlassian.net/browse/SAK-50646
The new Sakai grader breaks when a submission contains corrupted files, resulting in a 404 error. In contrast, the classic grader successfully filtered out these corrupted files. The new grader, however, does not, and gets stuck on the message: 
'Loading the grading data... This may take a few seconds.'
=> SAK-50646 Assignments-Grader: Grader fails to load with corrupted file submissions

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, library/src/skins/default/src/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Quoting Christina: There was a problem viewing the Actions menu for Tests & Quizzes on a desktop-sized browser. It keeps it within the height of the table and enables a horizontal scroll. It was a side-effect of this Jira. It’s not appearing when there’s multiple tests present, just when there’s one or two - a list shorter than the menu length.
Removed the table-responsive bootstrap class and instead added a media query. The issue has been fixed on Tests & Quizzes and Resources tools.
=> SAK-50391 Resources and Samigo ui reponsiveness

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewSearchBarThread.jsp
Added aria-live="assertive" to enable the screen reader when grade submission is successful.
=> SAK-50697 Accessibility Grade submission successful message not announced

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/print/PDFAssessmentBean.java
https://sakaiproject.atlassian.net/browse/SAK-50715
When generating a PDF for an assessment that includes a calculated question with a formula containing the < or > operators, the content is rendered incorrectly.
=> SAK-50715 Samigo issue with calculated questions and angle brackets

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/EditablePanelDate.java, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/EditablePanelDropdown.java, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/SearchAccessPage.java, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserPage.java, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/UserPageSiteSearch.java, scormplayer/scorm-tool/src/java/org/sakaiproject/scorm/ui/player/components/ActivityLinkPanel.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/ReportsEditPage.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/pages/UserActivityPage.java, sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/widget/WidgetTabTemplate.java
Wicket 6 deprecated the usage of JS event names like "onclick","onblur", etc...in favor of their short version without 'on' prefix, i.e. "click","blur", etc... Starting from this version the event old names won't work anymore.
=> SAK-50716 DA SiteStats fix Wicket9 upgrade use of onchange

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
https://sakaiproject.atlassian.net/browse/SAK-50725
Test & Quizzes fail when a calculated question contains an @ symbol in the question body used for something other than a global variable.
=> SAK-50725 Samigo calculated question fails if ampersand character exists in the text

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
…entation so that we can ensure it's properly parsed
=> SAK-48501 Site Manage use a proper date/time format

rubrics/api/src/main/java/org/sakaiproject/rubrics/api/RubricsService.java, rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java, webapi/src/main/java/org/sakaiproject/webapi/controllers/RubricsRestController.java, webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubric.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricReadonly.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricsSharedList.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/data.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubrics.test.js
https://sakaiproject.atlassian.net/browse/SAK-50620
A super user can now only delete a shared rubric, ie: one displayed in a site other than the one it was originally authored in, if it does *not* have any evaluations attached to it, so if it has never been used to grade. This makes the shared rubric case consistent with the owner site case where the delete button is never shown if the rubric has evaluations.
=> SAK-50620 rubrics prevent deletion of evaluated rubrics

assignment/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
https://sakaiproject.atlassian.net/browse/SAK-50736
The assignment grades column (for students) displays "$service.getGradeForSubmitter($submission, $user.getId())" when $submission is null.
It is important to handle the case where a submission is null or the service returns an incorrect value.
=> SAK-50736 Assignments raw code displayed in grades column

content-review/impl/turnitin/pom.xml, entitybroker/core-providers/pom.xml, entitybroker/impl/pom.xml, entitybroker/pom.xml, entitybroker/rest/pom.xml, entitybroker/utils/pom.xml, kernel/kernel-impl/pom.xml, master/pom.xml, signup/pom.xml
https://sakaiproject.atlassian.net/browse/SAK-50777
=> SAK-50777 Upgrade libs reflectutils and genericdao

samigo/samigo-api/src/java/xml/xsl/dataTransform/import/v1p2/extractItem.xsl, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/CalculatedQuestionBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-hibernate/src/java/org/sakaiproject/tool/assessment/data/dao/assessment/PublishedItemData.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/item/ItemHelper12Impl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
https://sakaiproject.atlassian.net/browse/SAK-50613
The formulas for calculated questions are stored in the database by concatenating the formula with "|tol,dec". This causes two issues:  
1. The "|" symbol is also used as the OR operator.  
2. The comma is not only used as a decimal separator but is also used in formulas (such as `if`) to separate arguments.  
When a formula is configured, for example, as: `iff({numero}<2, {sub}|{numero}, {numero}=2, {sub}*3, {numero}>2, {sub}*6)`, the question breaks.
=> SAK-50613 Samigo issue with calculated questions using the pipe and comma operators

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java
https://sakaiproject.atlassian.net/browse/SAK-50772
The "Allow only specified IP addresses" list in the "Security and Proctoring" section retrieves the IP addresses in a random order, causing confusion for instructors when verifying that the list is correct. This list should be displayed in a sorted order, for example, from smallest to largest.
=> SAK-50772 Tests & Quizzes: IP list sorting in Allowo only specified IP addresses

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/business/entity/SebConfig.java
https://sakaiproject.atlassian.net/browse/SAK-50666
On the Sakai login screen, there are often external links (e.g., to the APAREO page). When accessing the SEB (Safe Exam Browser), this screen appears, allowing users to open links and navigate to Instagram, Twitter, Google, etc. A student could also type a link (e.g., Google) into a short-answer question and open a new tab.
By default, block access to any link outside the platform itself. If a teacher wants to allow specific links, they can configure them using the SEB app.
=> SAK-50666 Samigo prevent opening links from SEB by default

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-50775
=> SAK-50775 Grader: Add Feedback Comment button should still appear when clicking on (should be same behavior like Add Private Notes)

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm, lti/lti-tool/src/java/org/sakaiproject/lti/tool/LTIAdminTool.java, lti/lti-tool/src/webapp/vm/lti_assignment_return.vm
Assignments LTI Adding a single (resource link) tool with "allow to change" for pop-up does not launch tool in new window
=> SAK-50788 Assignments LTI Adding a single (resource link) popup setting fix

webcomponents/tool/src/main/frontend/package-lock.json, webcomponents/tool/src/main/frontend/package.json, webcomponents/tool/src/main/frontend/packages/sakai-conversations/package.json
Multiple versions of lerna (8.1.8 and 8.1.9) were bringing in multiple versions of nx. Now:
```
sakai-ui@1.0.0 /Users/samo/dev/trunk-git/webcomponents/tool/src/main/frontend
└─┬ lerna@8.1.9
├─┬ @lerna/create@8.1.9
│ └── nx@20.2.1 deduped
├─┬ @nx/devkit@20.2.1
│ └── nx@20.2.1 deduped
└── nx@20.2.1
```
=> SAK-50795 Webcomponents fix Github build failures

msgcntr/messageforums-app/src/webapp/jsp/dfMessageReply.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfMessageReplyThread.jsp
Uncaught TypeError: document.forms.dfCompose.elements[rteId] is undefined.
This may be an "over-engineered" solution but it will attempt to detect the id from the text area in the previous element rather than using the one I observed as being on the document.
=> SAK-50792 Discussions: insert original text fails

commons/tool/src/webapp/js/commons.js, commons/tool/src/webapp/js/commons_utils.js
Existing popover safe version of initializing popovers. This `getOrCreateInstance `method was added in Bootstrap 5. 
Alternatively I was going to check 
`  if (!bootstrap.Popover.getInstance(t)) {  ... } 
`
But this worked and seemed more straightforward. I tested on some of the popups in commons as well as the information popup.
=> SAK-50787 Portal footer on Commons page: build info no pop-up

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/DeliveryBean.java, samigo/samigo-app/src/webapp/jsf/delivery/getTimerProgress.jsp, samigo/samigo-app/src/webapp/jsf/widget/timerBar/timerbar.js
https://sakaiproject.atlassian.net/browse/SAK-50631
We have identified some rare cases where the frontend loses the values of timeLimit and timeElapse (resetting them to 0). This leads to the frontend triggering the final submission of the assessment, rendering it inaccessible to the student, which is unacceptable during an assessment. This solution aims to prevent these errors. When the frontend encounters a timeLimit value of 0 (which is not possible in a timed assessment) it should use timeLimit_bck and timeElapse_bck instead.
=> SAK-50631 Samigo SEB autosave modal message is sometimes permanently displayed

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-50846
If a user is connected when the SiteStats Event Aggregator job is run, the user's previously closed session is merged with the active session.
`real time presence   `| `x-----x       x------------x`
`calculation          `| `x--------------------------x`
=> SAK-50846 Sitestats successive stats calculated incorrectly

assignment/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
https://sakaiproject.atlassian.net/browse/SAK-50851
When the grading rubric and the self-assessment rubric coexist in a assignment submission for the student, if marking all the rubric criteria is required, the verification also takes into account the instructor's rubric criteria, which may remain unmarked. The student, obviously, cannot mark these criteria, making it impossible to submit the assignment since the condition is not met.
=> SAK-50851 Assignments peer review submission blocked due to unmarked instructor rubric criteria

kernel/api/src/main/java/org/sakaiproject/authz/api/Role.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseRole.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/SiteAddParticipantHandler.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/impl/UserRoleEntry.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/AddProducer.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/AddViewParameters.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/ConfirmProducer.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/DifferentRoleProducer.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/EmailNotiProducer.java, site-manage/site-manage-participant-helper/src/java/org/sakaiproject/site/tool/helper/participant/rsf/SameRoleProducer.java, site-manage/site-manage-participant-helper/src/webapp/WEB-INF/requestContext.xml, site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteParticipantHelper.java
https://sakaiproject.atlassian.net/browse/SAK-50640 
This also adds modernization and general improvements to the add participant helper tool
=> SAK-50640 site-manage add participants add permission check in default view

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, gradebookng/bundle/src/main/bundle/gradebookng.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/EventHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/BasePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
https://sakaiproject.atlassian.net/browse/SAK-50770
Creates an export with student eid and course score in percent like:
`gradebook_export-DAC-EDUCATION-DEPT1-SUBJ1-101-osiris.txt`
```
student0002 90
student0001 80
```
Currently disabled by default.
=> SAK-50770 Gradebook Add Osiris Export

library/src/skins/default/src/sass/modules/more-sites/_more-sites.scss
https://sakaiproject.atlassian.net/browse/SAK-50878
Before:
After:
In 22.x is OK. This was removed in Trinity
=> SAK-50878 Adding overflow hidden for the large sites on the menu

library/src/skins/default/src/sass/tool.scss
Added a Sakai-color with better color contrast ratio that meets the WCAG 1.4.3 standard for username and password labels.
=> SAK-50849 Accessibility WCAG 1.4.3 Color Contrast on Gateway Welcome Page

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/impl/src/test/org/sakaiproject/assignment/impl/AssignmentTestConfiguration.java, assignment/impl/src/webapp/WEB-INF/components.xml, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/BltiEntity.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lti/docs/IMPORTCC.md, lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java, lti/lti-common/src/java/org/sakaiproject/lti/util/SakaiLTIUtil.java, lti/lti-common/src/java/org/sakaiproject/util/foorm/Foorm.java, lti/lti-common/src/test/org/sakaiproject/lti/util/SakaiLTIUtilTest.java, lti/lti-common/src/test/org/sakaiproject/util/foorm/FoormTest.java, lti/lti-common/src/test/org/sakaiproject/util/foorm/TestFoormJUnit.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
=> SAK-50820 Assignment / LTI improve archive/merge

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm
https://sakaiproject.atlassian.net/browse/SAK-50805
The option to enable sub page navigation should always be visible and not dependent on whether tools that support it are enabled.
=> SAK-50805 SiteManage sub page navigation option

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/FileConversionServiceImpl.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/converters/LoolFileConverter.java
Do not attempt to use httpclient5. It's really meant for async.
=> SAK-45711 Kernel improve error handling in LoolFileConverter

library/src/skins/default/src/sass/themes/_light.scss, library/src/skins/default/src/sass/tool.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
1. This reverts SAK-50849 Accessibility WCAG 1.4.3 Color Contrast on Gateway Welcome Page (#13207)
2. WAVE does not seem trustworthy here. It clear that this is not 1:1 (e.g., the same color) contrast
3. We should also use manual testing to confirm color contrast
4. Cypress now has a pre-login test that will fail if any issues are found
5. This fixes all other items that were triggering aXe
=> SAK-50908 Portal a11y fix all accessibility issues on home

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-50916
This bug was introduced by the webcomponents refactor done here -> https://github.com/sakaiproject/sakai/pull/11789
Fix is taken from the original s2u-34 piece which introduced the group submission + rubrics feature -> https://github.com/sakaiproject/sakai/pull/11950
=> SAK-50916 SakaiGrader rubrics evaluation should use group id

assignment/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
SAK-50903 Creating a new assignment and putting it to site users creates an asn.new.assignment event, but this does not happen when putting it to selected groups.
https://sakaiproject.atlassian.net/browse/SAK-50903
=> SAK-50903 Assignments a new assignment using groups should emit an asn.new.assignment event

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
https://sakaiproject.atlassian.net/browse/SAK-50931
Before:
After:
=> SAK-50931 Assignment: Change text-info class (blue color)

common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteMerger.java, kernel/api/src/main/java/org/sakaiproject/util/Xml.java, kernel/api/src/test/java/org/sakaiproject/util/XmlTest.java, web/web-impl/impl/src/java/org/sakaiproject/web/impl/WebServiceImpl.java
Note, I added a method to the Xml utility to dump an Element object for debugging.  This also turns off the merge processing of the web.xml because more complete information is contained in the site.xml import.
=> SAK-50943 Web Content cc+ export not keeping the "open in new window" option

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java, msgcntr/messageforums-component-impl/src/webapp/WEB-INF/components.xml
https://sakaiproject.atlassian.net/browse/SAK-50955
=> SAK-50955 forums repeated rubrics permissions appears in realm tables

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/ccexport/CCExport.java
Imported assignments will be site wide - any group settings need to be added manually post import.
=> SAK-50945 assignment cc+archive should not export group data and turn off assign to group

assignment/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, webcomponents/bundle/src/main/bundle/grader_ca.properties, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js
https://sakaiproject.atlassian.net/browse/SAK-50917
After adding the rubrics, the content of each peer review may be too lengthy to display all of them expanded. I have changed the format to an accordion (as it is in the classic grader).
=> SAK-50917 WC SakaiGrader when grading move peer review rubrics to an accordion

content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm, library/src/skins/default/src/sass/base/_defaults.scss
Jira: https://sakaiproject.atlassian.net/browse/SAK-50982
This proposed PR yields the display depicted in the ExpectedLayout.png screenshot attached to the jira. I'm using the h5 bootstrap class because the 'Availability and Access' link is an h4. Presumably, we could instead revise the p element to be h5. I'm open to either approach.
=> SAK-50982 Resources style availability and access option in detail settings

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSqlDefault.java
https://sakaiproject.atlassian.net/browse/SAK-51003
=> SAK-51003 Kernel SiteService limit column TITLE to a length of 99 chars

announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/DbAnnouncementService.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lti/lti-common/src/java/org/sakaiproject/lti/util/SakaiLTIUtil.java, lti/lti-common/src/test/org/sakaiproject/lti/util/SakaiLTIUtilTest.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java, mailarchive/mailarchive-impl/impl/pom.xml, mailarchive/mailarchive-impl/impl/src/java/org/sakaiproject/mailarchive/impl/BaseMailArchiveService.java, mailarchive/mailarchive-impl/impl/src/webapp/WEB-INF/components.xml, message/message-api/api/src/java/org/sakaiproject/message/api/MessageService.java, message/message-util/util/pom.xml, message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java
Hey @ern athanks for the two abstract and one concrete with setters, getters, and beans fix :)
=> SAK-50752 Announcements support in CC+Archive archive / merge

lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java
This is a really small change where the RTE mapping code did all the difficult bits but used the old, not new serverURL as the base of the new RTE launch URL.  Easy fix.  I partially blame AI for this because it helped be tweak the URL and the code looked sooo cool.  And it worked until you were moving between servers.
=> SAK-47782 Fix server url mapping in RTE link fix

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlDefault.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/ContentServiceSqlOracle.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
https://sakaiproject.atlassian.net/browse/SAK-51007
=> SAK-51007 Kernel saving a pronunciation in profile causes SQL syntax error ORA-00933

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java
The problem seems to come from a very old, very ugly js+vm related to the 24h vs am/pm formats, that should probably be rewritten entirely. In the meantime, I think it's fine to fix this specific bug by adding the same default value used by the English format.
The value is not even used, but it's just preventing from accessing and using the frequency feature.
=> SAK-51010 Calendar : frequency not working in Spanish with unset hour

lessonbuilder/tool/src/webapp/js/lessons-calendar.js
https://sakaiproject.atlassian.net/browse/SAK-51045
If you embed a calendar in a Lessons section that starts collapsed, the calendar is rendered with a height of 0px.
=> SAK-51045 Lessons embedding calendar in a collapsible section (start collapsed) does not display correctly

roster2/bundle/src/bundle/roster_es.properties
https://sakaiproject.atlassian.net/browse/SAK-51020
I've just changed it on Transifex too
=> SAK-51020 Roster - Export funcionality is broken

library/src/skins/default/src/sass/modules/tool/roster/_roster.scss
https://sakaiproject.atlassian.net/browse/SAK-51021
Before:
After:
I'll fix the width on another ticket with other little thing.
=> SAK-51021 Roster switching to list mode photos are not displayed

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, calendar/calendar-impl/impl/src/java/org/sakaiproject/calendar/impl/BaseCalendarService.java, common/archive-impl/impl2/src/java/org/sakaiproject/archive/impl/SiteMerger.java, kernel/api/src/main/java/org/sakaiproject/content/api/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/content/cover/ContentHostingService.java, kernel/api/src/main/java/org/sakaiproject/entity/api/EntityProducer.java, kernel/api/src/main/java/org/sakaiproject/util/MergeConfig.java, kernel/api/src/main/java/org/sakaiproject/util/api/LinkMigrationHelper.java, kernel/api/src/main/java/org/sakaiproject/util/cover/LinkMigrationHelper.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/LinkMigrationHelperImpl.java, kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/LinkMigrationHelperImplTest.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lti/lti-api/src/java/org/sakaiproject/lti/api/LTIService.java, lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java, message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/DiscussionForumServiceImpl.java, polls/impl/src/java/org/sakaiproject/poll/service/impl/PollListManagerImpl.java, scormplayer/scorm-impl/service/src/java/org/sakaiproject/scorm/service/sakai/impl/mocks/MockContentHostingService.java, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
This is a refactor for @ern - I have been adding to merge / archive for a while and the method signatures have gotten too long.  The invents a MergeConfig (similar to CCConfig) to gather these loop-carried data structures that cut across the multiple steps of the merge() process.
=> SAK-50154 CC+Archive refactor merge() calling sequences

content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
The problem is that the jquery-ui modal does not handle scrolling. The CONTINUE button is essential and Bootstrap Modal solves this with their `modal-footer` concept. The rest of the modal can scroll but the buttons absolutely need to be present.
**BEFORE**
_Note that the Continue button is not on the page. The user can do nothing_
**AFTER**
=> SAK-51053 Content use bootstrap modal for Add Attachments

admin-tools/src/java/org/sakaiproject/site/tool/AdminSitesAction.java, admin-tools/src/webapp/vm/sites/chef_sites_saveas.vm
[SAK-51080](https://sakaiproject.atlassian.net/browse/SAK-51080)
[SAK-51080]: https://sakaiproject.atlassian.net/browse/SAK-51080?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SAK-51080 Duplicate Site: New parameter for title

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSitePage.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseToolConfiguration.java, lessonbuilder/components/src/java/org/sakaiproject/lessonbuildertool/model/SimplePageToolDaoImpl.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/webapp/WEB-INF/applicationContext.xml
This is quite a change.  I redid the spacing on the file.  It was impossible to seriously work on this code - not only did it use inconsistent indentation, mixing spaces and tabs - it also used a pattern where there was a for loop with a bunch of sanity checks at the top of the loop so by the time the loop body was starting the code was about 4-5 unnecessary indents in.  Further as the body of the loop did more sanity checks as it progressed, instead of just doing "continue" it indented further.  But actually it added a open brace but often did *not* indent the code because the original author did not want to be looking at code 7 indents deep. Impossible to look at.  Impossible to understand. It is best to review this with white space turned off - and then ignore any apparent white space …
=> SAK-50978 Lessons cc+ import does not import content unless the file is imported twice

rubrics/impl/src/main/java/org/sakaiproject/rubrics/impl/RubricsServiceImpl.java, rubrics/impl/src/test/org/sakaiproject/rubrics/impl/test/RubricsServiceTests.java, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricAssociation.js
* Throwing an exception just gets buried and user never sees it
* If the user has no permissions, just returning an empty list seems sane.
* There is no way to short-circuit the loading of `<sakai-rubric-association>` if Rubrics is not enabled in the site.
* Add more safety to the JSON.parse to avoid an error preventing normal user behavior
=> SAK-51060 Rubrics avoid throwing an exception when user doesn't have the edit permission

webcomponents/tool/src/main/frontend/packages/sakai-user-photo/src/SakaiUserPhoto.js
This work was primarily done by Cursor and the Gemini 2.0 Pro Exp model. 
It was tested and confirmed by a human.
> Fix: Update user photo on property change
> The SakaiUserPhoto component was not updating correctly when the user-id, official, or blank properties were changed because the image URL was only being set in connectedCallback. This commit moves the URL calculation to willUpdate to ensure the URL is updated whenever these properties change. Additionally, the unnecessary shouldUpdate method has been removed, allowing Lit to correctly manage component updates when the url state variable changes.
=> SAK-51070 Webcomponents fix image url for sakai-user-photo when moving between students

roster2/tool/src/java/org/sakaiproject/roster/impl/SakaiProxyImpl.java
Need to cache bust after a permission change because now they may not be able to see as many user properties.
=> SAK-49670 Roster cache bust after permissions update

lti/lti-impl/src/java/org/sakaiproject/lti/impl/BaseLTIService.java, samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/pom.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentEntityProducer.java
There are three steps to this change - they are separate commits below:
1.  Make it so that "Import from Site" fixes embedded images in the correct and incorrect feedback.
2. Make it so that "Import from Site" handles embedded LTI links (shipping cart) in all RTE areas
3. Make it so that "Lessons - Import from CC+" also works across all RTE areas and attachments
To do this, I extended the calling sequences for internal methods for updateEntityReferences() and migrateText() so they can handle the "Import from Site" or "merge()" use cases. The method signatures got a little long but I really wanted to avoid duplicating the complex code that goes through and finds all the RTE areas post copy or post merge.  It seemed more reliable in the long run the have a few more parameters and if tests …
=> SAK-51055 Samigo cc+ import issues with embedded image in CKEditor

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51108
When a site's session (site 1) expires due to inactivity while the user is browsing another site (site 2), the pres.end event for site 1 incorrectly records the context with the id of site 2. This causes errors in presence time calculations, as the system interprets the session expiration as belonging to site 2.
Typically, there’s no context available.
=> SAK-51108 Sitestats filter incorrect context from event in presence records

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsAggregateJobImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51153
We found this while testing. This is a real case:
---
**17:21:48.463** → Finished reading events **3137257703 to 3137268571**. A total of **10,868** events were read (`sqlBlockSize` is **10,000**) (**868 events have no session**).  
**17:23:56.049** → Finished processing events up to **3137268571**.  
**17:23:56.477** → Reads event ID **3137278134** for the first time. The event is at position **10,431**, exceeding the queue.  
**17:23:56.495** → Finished reading events **3137267703 to 3137278651**. A total of **10,948** events were read (**948 events have no session**).  
(The last event processed in the previous queue was **3137268571**, but now it starts at **3137267703**, repeating **868** events.)
**17:26:14.342** → Finished …
=> SAK-51153 Sitestats: Event collection duplicates event processing

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java
https://sakaiproject.atlassian.net/browse/SAK-51154
=> SAK-51154 Lessons: siteId replacement fails after importing content if destination siteId is part of the source siteId

.github/workflows/server.yml, library/src/skins/default/src/sass/modules/tool/grader/_base.scss, library/src/skins/default/src/sass/modules/tool/rubrics/_rubrics.scss, webcomponents/bundle/src/main/bundle/grader.properties, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/SakaiGrader.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/src/sakai-grader-rendering-mixin.js, webcomponents/tool/src/main/frontend/packages/sakai-grader/test/i18n.js
=> SAK-50468 Grader should scroll with instructor on desktop instead of overlaying

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
Made the element focusable and added a keydown event handler.
=> SAK-37749 Lessonbuilder accessibility collapsible sections cannot be opened with keyboard

library/src/skins/default/src/sass/modules/_toolmenu.scss, portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includeSiteNav.vm
On sites where a custom icon has been defined using the Icon URL site property it comes out very small and is not distinguishable no matter how big the image is set.
=> SAK-51211 The custom site icon is too small

gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradingEvent.java
https://sakaiproject.atlassian.net/browse/SAK-51249
=> SAK-51249 Gradebook oracle doesn't allow inserting empty values GB_GRADING_EVENT_T.IS_EXCLUDED

lti/lti-common/src/java/org/sakaiproject/lti/util/SakaiLTIUtil.java
The problem is because you cannot reuse the same LTI signature twice due to invalid nonce error.
It is not useful to resubmit the POST in a timeout with the same signature, you have to wait for the current POST to finalize and not cancel it, just wait until the end.
=> SAK-51318 LTI avoid using the same signature by setting a timeout

site-manage/datemanager/impl/src/main/java/org/sakaiproject/datemanager/impl/DateManagerServiceImpl.java
https://sakaiproject.atlassian.net/browse/SAK-51326
=> SAK-51326 DateManager gradebook by groups introduced a thread safety issue

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarAction.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/tool/CalendarActionState.java, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm, library/src/webapp/js/lang-datepicker/lang-datepicker.js
Resolve 'Declaration or statement expected' error in lang-datepicker.js caused by incorrect nesting of date string format parsing logic within the DateHelper.normalize method. The conditional blocks for handling YYYY-MM-DD format and the native Date parsing fallback were incorrectly nested inside the block checking for the ISO 'T' format.
=> SAK-51264 Calendar fix date errors and datepicker errors

portal/portal-render-engine-impl/impl/src/webapp/vm/morpheus/includePortalHeaderBreadcrumb.vm
https://sakaiproject.atlassian.net/browse/SAK-51225
=> SAK-51225 Portal site breadcrumb mobile view uses an incorrect site name

assignment/impl/src/java/org/sakaiproject/assignment/impl/AssignmentServiceImpl.java, assignment/tool/src/webapp/vm/assignment/instructor_new_edit/grading_section.vm
https://sakaiproject.atlassian.net/browse/SAK-51218
=> SAK-51218 Assignments ui shows correct state of GB integration after import

pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/banners/BannerStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/popups/PopupStorage.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/views/index.hbs
This change adds **sorting by start time** (descending) to the **Banners** and **Popups** lists. Applying a consistent order improves usability by making the most recent or upcoming items easier to find, rather than leaving the lists in an unpredictable state.
=> SAK-51357 PASystem define a meaningful deterministic order for banners and popups

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionForumBean.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/ui/DiscussionTopicBean.java, msgcntr/messageforums-app/src/webapp/jsp/compose.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp
Fixed issues with forum and topic date handling to ensure that dates are properly persisted when a form is submitted with validation errors. This addresses problems where open and close dates were not being stored correctly.
The fix properly addresses the issue with forum and topic date handling, ensuring that dates are preserved when there are validation errors during form submission. Key changes include:
1. Fixed the date parsing and persistence in both forum and topic beans
2. Added proper handling of ISO date values
3. Enhanced the JavaScript to ensure date values are properly synchronized
4. Added initialization to make sure dates are properly loaded on form load
=> SAK-51360 Forums fix date handling issues

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsUpdateManagerImpl.java, sitestats/sitestats-impl/src/webapp/WEB-INF/components.xml
https://sakaiproject.atlassian.net/browse/SAK-51453
This commit will switch the stats service to always collect stats, even if the sitestats tool has not been added to the site. The previous behaviour can be restored by adding:
collectEventsForSiteWithToolOnly@org.sakaiproject.sitestats.api.StatsUpdateManager.target=true
to your sakai properties.
=> SAK-51453 sitestats Default to always collecting stats

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java
1. We added the itemData property to the QuestionScoresBean class to store the item data.
2. We confirmed the bean.setItemData(item) call was already present in the QuestionScoreListener class.
3. We added code to ensure that itemData is properly set even when sorting by modifying the QuestionScoreUpdateListener class to check if itemData is null and set it if needed.
4. We imported the necessary classes to make this work.
The JSP was trying to access the itemData property, but it wasn't being set properly during sorting operations.
=> SAK-51462 Samigo fix sorting on score column on Questions page

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/ui/DiscussionForumManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java, msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/includes/dfAreaInclude.jsp, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/DiscussionForumManagerImpl.java
When duplicating a topic with attachments, the original implementation reused the same attachment ID, creating a shared reference to the same underlying file.
This caused problems when a duplicated topic was deleted, as it would try to access attachments that no longer existed.
The fix:
1. Added a new createDuplicateDFAttachment method to properly copy attachment files
2. Modified duplicateTopic to use the new method, ensuring each attachment gets a true copy
3. Uses ContentHostingService.copyAttachment to create actual copies of files
=> SAK-51363 Forums deleting a topic that was duplicated would remove attachment used by other topics

library/src/skins/default/src/sass/modules/tool/wiki/_wiki.scss
https://sakaiproject.atlassian.net/browse/SAK-51561
On 22
Before
After
=> SAK-51561 Wiki icons from the text editor are incorrect

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-settings.js
What we changed:
1. Removed Wicket AJAX behavior - No more setupAccordionBehavior() calls that destroy/recreate DOM elements
2. Kept Bootstrap accordion attributes - The HTML already has proper data-bs-toggle="collapse" attributes
3. Added JavaScript state persistence - Uses localStorage instead of server-side state management
4. Set initial CSS classes only - Java just sets the right CSS classes based on this.expanded
Why this fixes the sortable issue:
- No DOM destruction - Bootstrap accordion only toggles CSS classes (show/hide) on existing elements
- jQuery UI sortable survives - Since the table DOM elements are never destroyed, the sortable behavior remains attached
- Pure client-side - No AJAX requests that could interfere with JavaScript behaviors
Benefits:
- Better performance - …
=> SAK-51565 Gradebook fix reordering in Categories

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SortGradeItemsByGradeItemPanel.html
JAWS wants to use the arrow keys. You either need to be an expert user of JAWS (to go into bypass mode) or we need to use role=application so we can capture the arrow keys
=> SAK-51269 Gradebook use role=application to put JAWS into mode where we can use arrow keys

gradebookng/tool/src/webapp/scripts/gradebook-gbgrade-table.js
The fix:
1. Added a check for columnType to ensure only assignment columns trigger the POST request
2. Added a guard clause that returns early if the column isn't an assignment or doesn't have an assignmentId
3. Added a debug log to help with troubleshooting
This prevents the POST request with assignmentId: undefined when users drag category columns in the gradebook.
=> SAK-51605 GradebookNG fix undefined assignmentId in drag and drop for category columns

library/src/skins/default/src/sass/themes/_light.scss
https://sakaiproject.atlassian.net/browse/SAK-51646
On Dark
=> SAK-51646 Library active tab should be same background color as active navigation

gradebookng/impl/src/main/java/org/sakaiproject/grading/impl/GradingServiceImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java, library/src/skins/default/src/sass/print.scss
Fixes percentage grades appearing blank (-) in student grade summary after
SAK-51562 optimization. The optimization incorrectly switched from using
calculateEquivalentPercent() to getPercentEarned() for percentage gradebooks.
Restored original percentage calculation logic in convertGradeRecordToGradeDefinition()
to properly calculate percentage from pointsEarned/pointsPossible while maintaining
the performance benefits of the bulk grade fetching optimization.
- These panels were setting "gradingType" in the data map
- But GradeSummaryTablePanel was looking for "gradeType"
- This caused gradeType to always be null
- Result: Percentage logic NEVER triggered, always used points display
```java
// BEFORE (broken):
tableModel.put("gradingType", gradebook.getGradeType());
// AFTER (fixed): …
```
=> SAK-51664 Gradebook fix percentage grades showing blank in student summary

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
The fix aligns Grade Override export with how Course Grade export works:
- Course Grade: Uses `courseGrade.getMappedGrade()` directly (letter grade, no formatting)
- Grade Override: Now uses `courseGrade.getEnteredGrade()` directly (letter grade, no formatting)
- Calculated Grade: Still uses `FormatHelper.formatGradeForDisplay(courseGrade.getCalculatedGrade())` (numeric percentage, needs formatting)
This change will:
✅ Eliminate the server log warnings
✅ Export Grade Override values correctly as letter grades
✅ Maintain consistency with Course Grade handling
✅ Keep the same user-visible behavior (letter grades in exports)
=> SAK-51535 Gradebook course grade export use raw entered grade instead of formatted display

webcomponents/tool/src/main/frontend/packages/sakai-rubrics/src/SakaiRubricEdit.js, webcomponents/tool/src/main/frontend/packages/sakai-rubrics/test/sakai-rubric-edit.test.js
Just get rid of the cancel button as Cancel doesn't work as people expect it to
=> SAK-51663 Rubrics remove cancel button from edit modal

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://sakaiproject.atlassian.net/browse/SAK-51701
Property missing on this commit: https://github.com/sakaiproject/sakai/commit/c94861b624de3f89e4ed21f60a50f5c2aef9d895
=> SAK-51701 Missing content.singleInstanceStore property on the default sakai.properties file

webcomponents/tool/src/main/frontend/packages/sakai-grader/src/submission.js
The classic grader stores submission log entries with numbered keys (log0, log1, log2, etc.) and uses a TreeMap to maintain chronological order. However, the SakaiGrader was simply extracting these entries using Object.keys() without respecting the numeric ordering, causing drafts and submissions to appear in incorrect order.
=> SAK-51695 Grader fix submission history order

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
- Fixed removeResource to count references in both main and deleted tables before deleting physical files
- Fixed removeDeletedResource to add missing reference counting for shared files
- Optimized to only check deleted table when main table has ≤1 references
=> SAK-51705 Kernel singleInstanceStore should also count soft deleted files

gradebookng/api/src/main/java/org/sakaiproject/grading/api/model/GradableObject.java, gradebookng/impl/src/test/java/org/sakaiproject/grading/impl/test/GradingServiceTests.java
Fixed IllegalArgumentException "Comparison method violates its general contract"
that occurred when sorting assignments with NaN mean values. The meanComparator
now properly handles NaN values by treating them consistently in comparisons,
preventing TimSort from detecting contract violations.
Added test to verify NaN values can be sorted without throwing exceptions.
=> SAK-51743 Gradebook Fix meanComparator NaN handling to prevent sorting exception

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
This commit fixes a long-standing issue where text-based files (CSS, Python, JavaScript, etc.) containing non-ASCII characters display garbled when accessed directly through Sakai's access servlet. Characters like "ñ", "á", and "é" were appearing as "Ã±", "Ã¡", and "Ã©" respectively.
The root cause is that browsers in 2025 still don't default to UTF-8 encoding when no charset is specified in the HTTP Content-Type header. Instead, they fall back to:
- Platform-specific defaults (Windows-1252 on Windows, ISO-8859-1 on Linux)
- Heuristic detection (unreliable and inconsistent)
- System locale settings
This creates a vicious cycle where legacy web content prevents browsers from defaulting to UTF-8, even though UTF-8 has been the de facto standard for new content for over a decade.
SOLUTION: …
=> SAK-51736 Content: Default to UTF-8 charset for text-based files served via direct access

webapi/src/main/java/org/sakaiproject/webapi/controllers/AnnouncementsController.java, webcomponents/tool/src/main/frontend/packages/sakai-announcements/src/SakaiAnnouncements.js
- Change Dashboard announcements widget default sort from Earliest First to Latest First
- Hide site sorting options (Site A-Z, Site Z-A) when viewing announcements within a specific course site
- Fix API sorting: getUserAnnouncements now sorts combined results by latest first
- Fix API sorting: getSiteAnnouncements changed from ascending=true to ascending=false
=> SAK-51309 Dashboard announcements widget default to Latest First
