sakaiproject/sakai

reference/library/src/webapp/editor/FCKeditor/editor/filemanager/browser/default/frmresourceslist.html
Relating to arrows not appearing
=> SAK-29807 - Error in browse server (resource picker) about tFld 

site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-type.vm
Better wording on template page
=> SAK-29524 - Better wording on template page

samigo/samigo-api/pom.xml, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/AssessmentGradingData.java, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/ItemGradingData.java, samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/dao/grading/MediaData.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java, samigo/samigo-services/pom.xml
Simplified and cleaned up various comparison methods in Samigo.
Removed fix from SAM-2185 as it didn't seem like it actually fixed this
problem.
=> SAM-2241 - Grading was incorrect for some newer options. 

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm
I would like Uday to take a look at this one.
=> SAK-29801 - Remove the reference to the global bootstrap.css in resources

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-29854
=> SAK-29854 update javax.transaction.jta version to fix build for fresh local repo

dashboard/tool/pom.xml
=> Dash-345 wicket 1.4.23

delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
SAK-29860 delegatedaccess-demo: project -> course
https://jira.sakaiproject.org/browse/SAK-29860
=> SAK-29860 delegatedaccess-demo: project -> course

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
I think this is low risk. There may be additional issues of the same type, but it's very unlikely that this will cause trouble, and it seems to fix at least some important symptom.
=> SAK-29849; can't import Lessons content in import from site

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsForumManager.java, msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/PrivateMessagesTool.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/MessageForumsForumManagerImpl.java, msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java, msgcntr/messageforums-hbm/src/java/org/sakaiproject/component/app/messageforums/dao/hibernate/PrivateForum.hbm.xml
Screenshot showing query plan is in the JIRA: https://jira.sakaiproject.org/browse/SAK-29857
=> SAK-29857 avoid the double join from hibernate that results in a bad MySQL 5.6 query plan

citations/citations-tool/tool/src/java/org/sakaiproject/citation/tool/CitationHelperAction.java
Setting here ,as it gets defaulted to app/binary when its null
=> SAK-29309 - Setting revised mime type to pipe

webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java, webservices/cxf/src/resources/applicationContext.xml
Two webservices to know the session load in the servers.
getSessionCountForServer
getSessionTotalCount (all the servers)
=> SAK-29815- New WS to know the number of sessions in the servers.

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
Created a nested form tag which is prohibited.
=> SAK-29798 Regression with bottom pager on Site Info Participant list

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupMeetingsBean.java
to display all reoccurring meetings
=> SAK-27982 add new property signup.showAllRecurMeetings.default

oauth/pom.xml
https://jira.sakaiproject.org/browse/SAK-29861
=> SAK-29861 wicket 1.4.23

kernel/api/src/main/java/org/sakaiproject/site/api/SiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/SiteServiceSqlDefault.java, reference/library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss, reference/library/src/morpheus-master/sass/tool.scss, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm, site-manage/site-manage-util/util/src/java/org/sakaiproject/site/util/SiteConstants.java
See https://jira.sakaiproject.org/browse/SAK-29873
=> SAK-29873 allow non maintain role users to see unpublished sites in worksite setup

delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
=> SAK-29850 roster -> roster2

portal/README.md, reference/README.md
Morpheus Documentation initial commit
=> SAK-29907: Morpheus Documentation

assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
Looks like this was removed for some reason in #65 is causing this regression.
=> SAK-29818 - NPE when selecting assignment list by student for new group

roster2/src/java/org/sakaiproject/roster/api/RosterMemberComparator.java
Sorting was not doing well with accents or other utf8 characters.
=> SAK-29910 Using Collator instead regular string methods to compare string containing i18n characters for sorting

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ReorderQuestionsListener.java
Fixes 2 issues
Reorder questions does not transfer question point value
Reorder working copy questions creates duplicate numbers
=> SAM-2615 SAM-2613

shortenedurl/impl/src/java/org/sakaiproject/shortenedurl/impl/RandomisedUrlService.java
This fixes downloads where files have non ascii characters in the name.
Cached values are consistent with value in the db, and are only encoded
after retrieving from the cache.
Updated cache logic to not use containsExisting as this could still
return null when a cached item expired.
=> SAK-26032 Shortedned URL's encode non ASCII chars

reference/library/src/morpheus-master/sass/examples/_customization_example_empty.scss
This file is an example for a customization file with all possible variables you can change easily.
=> Added an example for morpheus customization

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-29926
=> SAK-29926 Tika 1.10

master/pom.xml
SAK-29927 poi 3.13 & joda-time 2.8.2
=> SAK-29927 poi 3.13 joda-time 2.8.2

content/content-tool/tool/src/webapp/vm/content/chef_resources_more.vm, content/content-tool/tool/src/webapp/vm/content/chef_resources_webdav.vm, content/content-tool/tool/src/webapp/vm/content/sakai_dropbox_options.vm, content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm, content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_select.vm, content/content-tool/tool/src/webapp/vm/content/sakai_make_site_page.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_cwiz_finish.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_options.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_properties.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_html.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_text.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_upload.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_url.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_dropbox_multiple_folders_upload.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties_scripts.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_replace_file.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_revise_html.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_revise_text.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_revise_url.vm
toggleShortUrlOutput was declared in portalscript.js so renamed the Resources version to toggleResourcesShortUrlOutput.
Psuedo protocol javascript: should be avoided
See http://stackoverflow.com/questions/372159/do-you-ever-need-to-specify-javascript-in-an-onclick
javascript: is mostly an IE leftover
=> SAK-29298 Resources - Fix Short URL option in Edit Details page

pack/pack-bin/build.xml, pack/pack-demo/build.xml
After SAK-29896 we need to fix some paths inside ant build for packaging.
=> SAK-29931 Solve fail in pack task.

feedback/README.md, feedback/toolOrder.xml
Also show how to make the feedback tool always available in all sites.
=> SAK-29944 Document how to backfill Feedback tool.

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
New version of these web services following all the comments.
Finally no way to make a SelectionType.ANY
=> SAK-29813 - New User Webservices

login/login-tool/tool/src/java/org/sakaiproject/login/tool/SkinnableLogin.java
SAK-27488 cleanup bracket style and log messages
=> SAK-27488 Returns to the previous user after SU

content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesAction.java
Since Tomcat 8 use a strict policy for getRealPath(), so cannot use '..' directly.
=> SAK-29334 WebDAV instructions page throws NPE except if your language is English

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeService.java
Updated SimpleDateFormat pattern
=> SAM-1408 bug fix commit

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/site.vm
Could you review this @csev. It looks like there was still a problem getting the original library back to the dollar sign if it wasn't jQuery. This looks like it fixes a few gradebook issues (uses myfaces) and relates to https://jira.sakaiproject.org/browse/SAK-29843 but doesn't seem super clean. It looks like you were doing something similar there.
=> SAK-29374 - Gradebook datepicker is broken (prototype)

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, portal/portal-api/api/src/java/org/sakaiproject/portal/api/Portal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/DefaultSiteViewImpl.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeSitesNav.vm, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/moresites.vm, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss, reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
We've been testing a little this issue and we've realized that Portal.CONFIG_DEFAULT_TABS was still used by instructors but this is not necessary anymore.
=> SAK-29736 - Tabs limited to 4 sites and no more sites button visible.

config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/authzimpl/authz-impl.properties, config/localization/bundles/src/bundle/org/sakaiproject/localization/bundle/authzimpl/authz-impl_es.properties, kernel/api/src/main/java/org/sakaiproject/authz/api/AuthzGroupService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroup.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/BaseAuthzGroupService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlMySql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java, kernel/kernel-impl/src/main/sql/hsqldb/sakai_realm.sql, kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql, kernel/kernel-impl/src/main/sql/oracle/sakai_realm.sql, kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockAuthzGroupService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/authz/impl/DummyUserEncodingTest.java, providers/component/src/webapp/WEB-INF/components-demo.xml, providers/jldap/pom.xml, providers/jldap/src/java/edu/amc/sakai/user/UserAttributeRoleProvider.java, providers/jldap/src/resources/UserAttributeRoleProvider.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteConfirm.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
- Added demo provider in .../providers/component/src/webapp/WEB-INF
/components-demo.xml
- Updated site-manage (SiteAction.java) to show labels for role
categories dynamically
=> SAK-29401 : Role-based access to sites

kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java
=> KNL-1383; add X-Sakai-Session header so we can log UsageSession ID

gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GraderRulesBean.java
https://jira.sakaiproject.org/browse/SAK-29984
=> SAK-29984 skip the 'view course grade' permission in gradebook classique

msgcntr/messageforums-app/src/java/org/sakaiproject/tool/messageforums/DiscussionForumTool.java
=> SAK-29555 - Forums unable to reply to conversation with customized

kernel/api/src/main/java/org/sakaiproject/event/api/EventQueryService.java, kernel/kernel-component/src/main/webapp/WEB-INF/event-components.xml, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/EventQueryServiceImpl.java, webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java, webservices/cxf/src/java/org/sakaiproject/webservices/Activity.java, webservices/cxf/src/resources/applicationContext.xml
Updated pull request. 
Added the service in the kernel event and then called from a new webservices package.
-getUserActivityByType returns all the events of a type from a user
-getUserLogonActivity returns all the logins of a user
-getUserActivity and getUserActivityRestVersion return the events of a
user between 2 dates.
=> SAK-29808 New User Activity Webservices

webservices/cxf/src/java/org/sakaiproject/webservices/AbstractWebService.java, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
SAK-29895 Webservice to change the user locale.
=> SAK-29895 Webservice to change the user locale.

reference/library/src/morpheus-master/sass/base/_extendables.scss, user/user-tool/tool/src/webapp/css/sakai-user-tool.css
The changes are from morpheus and New Account disabled buttons... if there's any disabled button inside tools will rise up on Morpheus QA we are doing these weeks.
=> SAK-29956 - Some disabled buttons will not look disabled in Morpheus

syllabus/syllabus-app/src/webapp/js/jqueryui-editable.js
This was pulled "as-is" from https://github.com/vitalets/x-editable/pull/724. Probably includes a lot of updates. Seems to fix the problem.
The alternative was to use a different library (that didn't have the jqueryui dependency). But that would require also changing the event listeners and using poshytip is we stuck with this library, which doesn't look as good, or choosing a different library which would be more work.
=> SAK-29947 - Can't edit syllabus items

reference/docs/conversion/sakai_11_mysql_conversion.sql, reference/docs/conversion/sakai_11_oracle_conversion.sql
The database column wasn't matching.
=> SAK-29740 Fix the conversion scripts

site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupAutoCreateProducer.java, site-manage/site-manage-group-section-role-helper/tool/src/webapp/WEB-INF/requestContext.xml
https://jira.sakaiproject.org/browse/SAK-30003
The section eids can be a little confusing for users. Change the format to read: "<sectionTitle> (<sectionEID>)"
=> SAK-30003 show title for roster groups instead of EID (auto groups)

syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java
Removed the ACCESS_CACHE variable from the 'SyllabusTool' class.
=> SAK-27970 syllabus in 'access view' does not show the edit mode now.

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
https://jira.sakaiproject.org/browse/SAK-29934
Property not added to default.sakai.properties in original PR (#1137).
=> SAK-29934 add sakai.property to disable Forums ranks feature to default.sakai.properties

reference/docs/conversion/sakai_11_oracle_conversion.sql
This got missed in the original pull request.
=> SAK-29733 Call Schedules Calendars (Oracle SQL)

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java
changeSitePublishStatus (passing the siteid and a boolean to select the
state)
checkForMemberInSite (passing siteid and eid return boolean)
getAvailableRoles (get the roles passing the authz)
getExistingFunctions (get the functions of a role passing the roleid
and the authz)
getSiteDefaultJoinerRole (know the default sitejoiner role apssing the
siteid)
=> SAK-29810 New SakaiScript Site related webservices

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
WIP merge. Needed for GBNG development.
=> SAK-29740 updates to backend service to persist category changes

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-30030
=> SAK-30030 joda-time 2.9

reference/library/src/morpheus-master/sass/base/_defaults.scss
https://jira.sakaiproject.org/browse/SAK-29639
These styles we removed when we went to Morpheus.
=> SAK-29639 need better styles for disabled input elements

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java, webservices/cxf/src/resources/applicationContext.xml, webservices/cxf/src/test/java/org/sakaiproject/webservices/MockingAbstractWebService.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiScriptSetUserTimeZoneTest.java
Add a webservice to change the user timezone:
sakai-ws/rest/sakai/setUserTimeZone?sessionid=ac37f8fd-eae4-4104-9020-e2300b33ab7e&eid=theuseid&timeZoneId=Europe/Oslo
=> SAK-30034 Webservice to change the user timeone

assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java, assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/conversion/impl/AssignmentSubmissionAccess.java
Would also fix the bug with this being invalid and not maching in
assignment xml
=> SAK-30087 & SAK-29824 - Clean up redundant attributes from submission.

kernel/kernel-impl/src/main/resources/antisamy/high-security-policy.xml, kernel/kernel-impl/src/main/resources/antisamy/low-security-policy.xml
Can read about these new HTML elements here:
http://html5doctor.com/the-figure-figcaption-elements/
=> KNL-1398 CKEditor allows use of a caption which creates an HTML5 figure and figcaption

mailarchive/mailarchive-impl/impl/src/bundle/mailarchive-noti-prefs.properties, mailarchive/mailarchive-impl/impl/src/bundle/mailarchive-noti-prefs_en_GB.properties
=> SAK-21687 Corrected text for Email Archive notifications preference in

profile2/tool/src/webapp/css/profile2.css
Hide the default browser text for the file input that is useless.
=> SAK-30107 - Fixed up a fixed width td so message displays

rsf/sakai-rsf-core/pom.xml, rsf/sakai-rsf-web/evolvers/pom.xml
I need this for the rsf project to build. It's hard to believe others are seeing it, or we'd get complains about builds breaking. But if others are seeing problems building rsf, please accept this PR.
=> RSF-18; add dependences needed for rsf to build

mailsender/tool/pom.xml, mailsender/tool/src/java/org/sakaiproject/mailsender/tool/beans/BasicTemplateResolver.java, mailsender/tool/src/webapp/WEB-INF/applicationContext.xml, mailsender/tool/src/webapp/WEB-INF/web.xml, mailsender/tool/src/webapp/content/js/mailsender.js
This fixes mail sender. However I'm concerned about RSF. I had to add some additional dependencies to get it to build. That would have nothing to do with this patch. I'm going to issue a separate pull request.
=> SAK-29630; fix mailsender for 11

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookFrameworkServiceImpl.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/.settings/org.eclipse.jdt.core.prefs, gradebookng/tool/pom.xml, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
Move updateGradeMapping to BaseHibernateManager so it is shared.
Remove the commented out code, now finalised.
Remove compiler plugin so we use the main one. Removes the restriction on JRE 1.7.
Update eclipse settings to allow 1.8 compliance
Fix sorting based on grading schema name
Migrate a few iterations over to single line lambdas.
Feature should now be complete.
=> SAK-29740 update gb settings

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnCellPanel.java
... for calculating category average for student when a score changes.
Delivers #1384.
=> Refactor to use new getCategoryScoreForStudent endpoint 

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> Fade in category headers and fix course grade not refreshing in fixed column

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
=> 1408: only show categories form fields when categories are enabled

samigo/samigo-app/src/webapp/js/extendedTime.js
SAM-1408 update date string format value which caused a date parse exception.
=> SAM-1408 update date format string value

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.html
=> 1451: Provide actions to expand and collapse all settings panels

authz/authz-tool/tool/src/webapp/css/authz.css, authz/authz-tool/tool/src/webapp/js/authz.js, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_confirm_remove.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_edit.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_edit_role.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_edit_user.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_list.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_saveas.vm, authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_saveas_role.vm, authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions-Main.vm, authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions.vm
https://jira.sakaiproject.org/browse/SAK-30069
=> SAK-30069 clean-up authz JavaScript, remove old spinners and code in favour of new centralized approach

site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/CreateJoinableGroupsProducer.java, site-manage/site-manage-group-section-role-helper/tool/src/webapp/WEB-INF/requestContext.xml, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/js/util.js, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/CreateJoinableGroups.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupAutoCreate.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupDel.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupEdit.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupImportStep1.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupImportStep2.html, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupList.html, site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-addCourseConfirm.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editClass.vm
https://jira.sakaiproject.org/browse/SAK-30068
* move some JavaScript out of *.vm files and into appropriate *.js file(s)
* remove old spinners/notifications and related JavaScript code in favour of new centralized approach
=> SAK-30068 clean-up site-manage JavaScript, remove old spinners and code in favour of new centralized approach

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.java
... and logic to support the different types of course grades.
Added properties to support the course grade preview
Add panel markup
Delivers #1454
=> #1454 Add course grade preview 

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
https://jira.sakaiproject.org/browse/SAK-30073
=> SAK-30073 apply new centralized spinner to some areas in forums

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Addresses #1421 
Added a converter to the textfield handle the conversion between decimal fraction and percentage for UI and persistence.
=> #1421 Change “weight” display in categories & weighting to be percentages instead of decimals

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
Change the editable cell from using an AjaxEditableLabel to a TextInput with an AjaxFormComponentUpdatingBehavior(onchange). This remedies the latency experienced in previously loading the input field and allows for touch devices to successfully focus and edit a grade.
Delivers #1388 and looks like it fixes touch device issues reported in #1364.
=> 1388: Refactor AjaxEditableLabel to become an ajaxified TextInput

gradebook/app/ui/src/webapp/addAssignment.jsp, gradebook/app/ui/src/webapp/assignmentDetails.jsp, gradebook/app/ui/src/webapp/calculateCourseGrades.jsp, gradebook/app/ui/src/webapp/courseGradeDetails.jsp, gradebook/app/ui/src/webapp/gradeOptions.jsp, gradebook/app/ui/src/webapp/gradebookSetup.jsp, gradebook/app/ui/src/webapp/hideShowColumns.jsp, gradebook/app/ui/src/webapp/inc/filterPaging.jspf, gradebook/app/ui/src/webapp/inc/filterPagingRoster.jspf, gradebook/app/ui/src/webapp/instructorView.jsp, gradebook/app/ui/src/webapp/js/gradebook.js, gradebook/app/ui/src/webapp/overview.jsp, gradebook/app/ui/src/webapp/spreadsheetEntireGBImport.jsp, gradebook/app/ui/src/webapp/spreadsheetUpload.jsp
https://jira.sakaiproject.org/browse/SAK-30070
=> SAK-30070 clean-up Gradebook JavaScript, remove old spinners and code in favour of new centralized approach

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Also changed the other model lookups to match the rest of the page, for better type checking.
=> #1474 hide category table on initial page load if category type = 1

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MessageView.java
This regression was introduced in SAK-29629 where messagePhoto was
removed.
=> SAK-30150 Profile2 regression with Messages

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 1496: Fix firefox bug where drop down menu would hide before it can be clicked

basiclti/basiclti-blis/src/java/org/sakaiproject/blti/ServiceServlet.java, basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-util/src/java/org/imsglobal/lti2/LTI2Vars.java
This also adds 
basiclti.strict=true
To suppress extensions that would violate XSD.  This should be used very sparingly.
=> Sak 29560 - Tweaks from Interoperability Testing

assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
To non-electronic assignement, submissions is always submitted.
=> SAK-30174 Instructors can not download grade file if the assignment is non-electronic

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Note that we are using a new code format preference in eclipse so this has changed a significant portion of the file, however the actual fix is the additional of the javascript to hide the tr with class gb-category-runningtotal when the weightings are disabled.
=> 1408 hide the percent tally when weightings disabled.

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
=> 1502 ensure the date picker calendar is hidden when the Add Gradebook Item dialog closes

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java, gradebookng/tool/src/webapp/WEB-INF/web.xml
=> 1517: GradebookNG static resource caching

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeReleasePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.java
=> 1505: preserve the settings accordion panel state on refresh and form submit

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Addresses #1527
Weight calculations now ignore the extra credit items, and the validation has been updated to suit. I have also disabled the weight field if the extra credit field is checked.
_Note that I have incorrectly tagged the commits with #1485 instead of #1527. Shouldn't matter too much and I don't want to force push to fix the message._
**Please merge #1550 before this one**
=> #1527 fix extra credit categories weight calculation bug

roster2/src/webapp/WEB-INF/bootstrap.jsp, roster2/src/webapp/js/roster.js
Updated css link to smoothness theme
=> SAK-29842 Desynchronised some roster.js code

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiScriptSetUserPropertyTest.java
Very simple webservice to add a userProperty.
http://localhost:8080/sakai-ws/rest/sakai/setUserProperty?sessionid=c3750c88-71d8-4731-9547-47cbd0d9d7d7&eid=admin&key=Company&value=Apereo
if value is null, then the property is deleted
if property exists, then property is updated with the new value.
=> SAK-30167 Webservice to set a User Property

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 1560: interface usability improvements

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
... from the custom Javascript and also store this on the GradebookUISettings session object to retain the color state for the duration of the wicket session
=> 1558: Move the category color generation code into Java/Wicket

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_es.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java
=> 1469: Add missing popover close action to the external item flag

content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm
Fix to submit the form only once in restore and remove links.
=> SAK-30132: Resource successfully restored with error message displayed

samigo/samigo-app/src/webapp/js/extendedTime.js
I removed the datepicker format from concatenated String value that gets persisted, seemed like the format caused all sorts of issues.
=> SAM-1408 Removed datepicker format from concatenated String value

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnCellPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 1574: flash success-green on course grade or category average cells change

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Proxy wasn't finding the right cell when categories enabled nor working correctly for flag elements.
Delivers #1572.
=> 1572: fix click proxy from fixed header cells to the real cell 

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseSitePublishService.java, edu-services/cm-service/cm-api/api/src/java/org/sakaiproject/coursemanagement/api/CourseSiteRemovalService.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSitePublishServiceImpl.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSiteRemovalServiceImpl.java, edu-services/cm-service/cm-impl/hibernate-pack/src/webapp/WEB-INF/components.xml, jobscheduler/scheduler-component-shared/pom.xml, jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSitePublishJob.java, jobscheduler/scheduler-component-shared/src/java/org/sakaiproject/component/app/scheduler/jobs/coursepublish/CourseSiteRemovalJob.java, jobscheduler/scheduler-component/src/webapp/WEB-INF/components.xml
Publish and unpublish sites automatically based in the term's dates. 
Based in the rsmart code.
=> SAK-29952 Publish and unpublish sites automatically based in the terms

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
GBNG UI also updated to give the user the ability to clear it.
Delivers #1582.
=> Categories can now be unset from a gradebook item. 

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
=> #1527 don't disable the weight field for extra credit items

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 1486 fix ipad scrolling issues

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
…when its value is dynmically updated.
Delivers #1601.
=> 1601: ensure fixed column course grade cell flashes green 

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
... so it doesn't flash when traversing to the fixed column header.
Delivers #1605.
Refactors the category label repositioning slightly so it animates after scroll but will update the fixedheader right away when it is first shown.  Also, it will only update the category label position if the horizontal position changes to avoid ghost flashes.
=> 1605: improve category label repositioning 

assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java, assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
https://jira.sakaiproject.org/browse/SAK-30237
=> SAK-30237: non harmful warnings about property not defined after recent patches

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 1621: clean up some Gradebook styles post morpheus update

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
… when the label left offset stays the same however the visible cell width changes.
Delivers #1605.
=> 1605: fix category label not repositioning

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Includes a little refactor of the `generateRandomRGBColorString` so it can be called from multiple classes.  Perhaps could go on a helper class rather than the page?
Delivers #1469.
=> 1469: add popovers to category extra credit flag and color swatch

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/msgcntr/MsgCntrSiteVolumeFactory.java, textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
Checked permissions for topics in forums before displaying in elfinder.
Used method 'isRead' of UIPermissionsManager class to check for read
permissions
=> SAK-30158 Added elFinder support to Forums.

reference/library/src/webapp/skin/tool_base.css, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css, site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_refresh.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm, velocity/tool/src/bundle/velocity-tool.properties, velocity/tool/src/java/org/sakaiproject/cheftool/VelocityPortletPaneledAction.java, velocity/tool/src/templates/VM_chef_library.vm
Moved css from site manage for flash notifications.Added macro
for standard flash notification message and also added duplicate
site variables to context, displaying in flash notification UI.
=> SAK-30230 Duplicate site now displays alert message when created.

master/pom.xml
https://jira.sakaiproject.org/browse/KNL-1406
=> KNL-1406 Tika 1.11

reference/library/src/webapp/js/headscripts.js
updateReq set correctly. to null now.
Third times the charm for this one...
=> SAK-29192 Chat messages refresh correctly. updateReq set correctly.

web/web-portlet/src/java/org/sakaiproject/portlets/PortletIFrame.java
storing in DB.
Prepend the server url back to the site-info on the edit screen of home
page.
=> SAK-30097 Removed hostname(server-url) from site-info url while 

kernel/kernel-util/src/main/java/org/sakaiproject/util/Validator.java
These methods aren’t used anywhere so should be removed.
=> KNL-1404 Drop some deprecated validator methods.

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
Also a code style cleanup from previous commits.
Updated the GbModalWindow to mention the requirement for the markupId to be set. 
Delivers #1639
=> #1639 add course grade header dropdown

gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers new #1607 requirements from 1/28 tech group call.
=> 1607: modify assignment header title link and sort icon styles

kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BasePreferencesService.java
The original code did this:
//is the preference in the cache
if (m_cache.containsKey(id))
{
prefs = (BasePreferences) m_cache.get(id);
}
which fails when there's an entry in the cache that has passed its TTL (.containsKey() returns true but .get() returns NULL).
Rework the code to deal with the null case, and to clarify the overall logic.
Further background in https://jira.sakaiproject.org/browse/KNL-1408.
=> KNL-1408 Preferences not loaded when cache entry expires

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
Delivers #1580.
Added to both top and bottom* of the table.  *only add to bottom when pagination visible.
To change the wording of the NavigationToolbar I had to pull a tricksy and override the `newNavigatorLabel` method.
=> 1580: add a student summary e.g. "Showing 1 to 100 of 155 students"

reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
We have watched this little issues just installing
=> SAK-30324 - Different errors in portal with many gateways or many sites.

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, dav/dav/src/java/org/sakaiproject/dav/DavServlet.java
- add property content.dav.upload.hidden
=> SAK-30270 Add option to enforce uploads via webdav to be hidden

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
... and then dynamically update this number as the student filter is applied.
Delivers #1580.
=> 1580: update the student summary to read 'Showing {n} students' 

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java
=> 1700: when NO_CHANGE, ensure old styles and notifications are cleared

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js
Add an alias for templateControls->site.setup.templateControls
Also add publishSite to the controls.
=> SAK-30148 - Better documentation for site.setup.templateControls

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_ca.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/DeliveryMessages_es.properties, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
JIRA : https://jira.sakaiproject.org/browse/SAM-2695:
Students can´t view the discount points of each question
=> SAM-2695 Students can´t view the discount points of each question

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_restore.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm, reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss, reference/library/src/morpheus-master/sass/tool.scss
Resolved the UI bugs that affected resources tool using Morpheus. Table, inputs, textsareas labels overflows. Dropdown menus overflows in mobile view transformed to a dialog style menu. Solved some style in DnD area
=> SAK-30115 Resolved the UI bugs that affected resources tool using Morpheus

gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Delivers #1366.  Assumed my assertions weren't crazy and went ahead with it :fearful: 
Three changes:
1. introduce checkInstructorOrTA so TAs can view edits of other users
2. disable drag and drop for TAs and leave sort-order update endpoints as instructor-only
3. remove the assignemnts list endpoint
=> 1366: Review TA permissions on GBNG entity provider

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeSitesNav.vm
Previously you would only see it if it also happened to be a favorite.
=> SAK-30334 Always show the active site in the top bar

roster2/src/webapp/js/roster.js
=> SAK-30335 Clear button not working with role select

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AssignmentColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/HeaderFlagPopoverPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/HeaderFlagPopoverPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1596.  
This required a bit of fussing about and resulted in the creation a new panel to represent the header flag popover content.  It takes the form of `HeaderFlagPopoverPanel`.
=> 1596 introduce links to header flag popovers

gradebookng/pom.xml, gradebookng/tool/pom.xml
=> #1678 fix version

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityUser.java
'type' field is populated with user type in constructor.
=> SAK-30343: Included type field in constructor of EntityUser.

master/pom.xml, oauth/pom.xml
https://jira.sakaiproject.org/browse/SAK-30342
=> SAK- 30342 Joda 2.9.2

mailarchive/mailarchive-subetha/pom.xml
The relative path for the subetha module was wrong.
=> SAK-30344 Cleanup build warning.

cloud-content/impl/src/main/java/coza/opencollab/sakai/cloudcontent/BlobStoreFileSystemHandler.java, cloud-content/impl/src/main/java/coza/opencollab/sakai/cloudcontent/SwiftFileSystemHandler.java
Pretty simple change .... just close the streams when done with them .....
=> SAK-30347 close streams after saving to the remote blob store

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Delivers #1738 
Fixes the comparison between Longs. Was meant to be by value not object.
=> #1738 Fix Long comparison as it is meant to be by value.

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
Delivers #1739
Fix a bug in the usage of setScale where it wasn't being applied
=> #1739 fix usage of setScale

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java
Hopefully the last we see of #1698.
=> #1698 a further fix to the treatment of decimals and the rounding issue.

edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSitePublishServiceImpl.java, edu-services/cm-service/cm-impl/hibernate-impl/impl/src/java/org/sakaiproject/coursemanagement/impl/CourseSiteRemovalServiceImpl.java
Filter all the  sites and not only the ones from the user, plus some cleaning in the comments.
=> SAK-30309 Filter all the  sites and not only the ones from the user

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
Delivers #1751
Added null guards around the categoryId checks
=> #1751 category comparison needed null guards

assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_reorder_assignment.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_report_submissions.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_student_list_submissions.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_options.vm
This is my first work on making a tool more responsive so review would be appreciated....
=> SAK-29985 start using bootstrap classes in assignments velocity templates

reference/library/src/morpheus-master/sass/base/_extendables.scss, reference/library/src/morpheus-master/sass/modules/tool/_menu.scss
Okay @SedueRey and @juanjmerono new PR for the bootstrap callouts.....
=> SAK-30355 use bootstrap callouts from bootstrap documentation

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, basiclti/tsugi-util/src/java/org/tsugi/lti2/ContentItem.java
=> SAK-30360 - Small changes identified in the IMS ContentItem Testing

calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar-customize_fields.vm, reference/library/src/morpheus-master/sass/modules/tool/calendar/_calendar.scss
Solved a remaining mobile bug for morpheus in calendar.
=> SAK-29989 Solved calendar mobile errors for Morpheus

samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
Modified the addFibTextAndAnswers method. Now, the whole FIB text is is 
formatted (including FIB_BLANK_INDICATOR).
=> SAM-2703 addFibTextAndAnswers

mailarchive/mailarchive-subetha/pom.xml, mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java, mailarchive/mailarchive-subetha/src/test/no-permission.txt, mailarchive/mailarchive-subetha/src/test/no-reply.txt, mailarchive/mailarchive-subetha/src/test/org/sakaiproject/mailarchive/SakaiMessageHandlerTest.java, mailarchive/mailarchive-subetha/src/webapp/WEB-INF/components.xml
We already have a Session class imported so it needs to be fully qualified. We also add some checking to make sure the object is correctly initialised.
=> SAK-30364 Fix the permission issue in SubethaSMTP.

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
It's not used at all and can be removed.
=> KNL-1417 Removed unused content cache.

reference/library/pom.xml
Added version 1.2.2 to webjars
=> SAK-30365 Added 1.2.2 jquery-i18n-properties

roster2/src/webapp/WEB-INF/bootstrap.jsp, roster2/src/webapp/i18n/languages.json, roster2/src/webapp/js/roster.js, roster2/src/webapp/lib/sakai_utils.js
Added jquery.18n.properties via webjars. Refactored Roster code into
callbacks.
=> SAK-30366 Roster2 now fully async

gradebookng/tool/pom.xml, gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
=> 1353: Add a chart to the statistics panel

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 1775: add support for numeric keypad (different keycode range)

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-settings.js, gradebookng/tool/src/webapp/styles/gradebook-settings.css
=> 1424 1777: enhancements to the category settings panel

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
=> #1799 don't process assignments if the setting is disabled

lessonbuilder/tool/src/webapp/js/show-page.js, lessonbuilder/tool/src/webapp/templates/ShowPage.html
The first patch fixed what it was supposed to, but in testing I found another artifact that it makes sense to fix under the same Jira. Left part of the column dialog sitting at the end of the page for students.
=> LSNBLDR_562; didn't quite work

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/ImportExportPage.java
=> 1833: jQueryUI has moved so update URL location so things work again

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
=> SAM-2654 - In progress counter incorrectly shows 0 for linear access

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/SakaiSecurity.java
This accidentally got removed in KNL-1271 and should have been refactored to just be a normal Cache. Most of this isn’t actually new code but just adding back of code that was wrongly removed.
=> KNL-1412 Add back in the main SecurityService cache.

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 1775: fix typos in event keycode handling for keypads

samigo/samigo-api/src/java/xml/author/v1p2/sectionTemplate.xml, samigo/samigo-api/src/java/xml/xsl/dataTransform/import/v1p2/extractSection.xsl, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/asi/Section.java, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/helper/ExtractionHelper.java
Import/export functionality modified to include Section Metadata
(Question ordering,Objective,Keyword,Rubric)
=> SAM-2460 Assessment's part attribute lost export/import assesment

reference/README.md, reference/library/pom.xml, reference/library/src/morpheus-master/README.md, reference/library/src/morpheus-master/compile-skin.md, reference/library/src/morpheus-master/customization-tool.md, reference/library/src/morpheus-master/sass/base/_defaults.scss
Also forgot to add the compressed and ul default in last commit.
=> SAK-30439 Documentation update

reference/library/pom.xml
Can be set on the command line like
-Dsakai.skin.outputSyle=nested
or in your .m2/settings.xml
=> SAK-30439 output style is now a property

.gitignore
I've added .DS_Store to Sakai's .gitignore file as described here: 
https://help.github.com/articles/ignoring-files/
=> SAK-30456: Added Mac's DS_Store file to the project's gitignore file

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 1813: retain edit mode when navigating with keyboard

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java
Also refactored the arrangement code to reduce duplication.
=> SAK-30462 Use isCourseType to identify course sites

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoExpressionParser.java, samigo/samigo-services/src/test/org/sakaiproject/tool/assessment/services/GradingServiceTest.java
New method GradingService.toScientificNotation used for calculating
variables and answers.
Now using scientific notation when creating and editing calculated
question and reviewing assessments.
=> SAM-2711 Calculated Questions. Issues with small and large numbers

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/CommonMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/EvaluationMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/AgentResults.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreListener.java, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
assessment (from the Questions tab)
New column (answer key) addded in the Questions tab. Only for Calculated
Questions
=> SAM-2719 Calculated Questions. Answer key not showed when reviewing

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm, reference/library/src/morpheus-master/js/src/sakai.morpheus.usernav.js, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
I've normalized some paddings, margins too and one error with overlay on mobile.
=> SAK-30452 - Cannot logout of mobile view, no links on top right profile work

reference/library/src/webapp/js/lang-datepicker/lang-datepicker.js, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AssessmentSettingsMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/AssessmentSettingsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/PublishedAssessmentSettingsBean.java, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
I've added a cross icon to allow to clear the datepickers once they have a date, and I've allowed empty values on them.
I've changed the bean code to accept empty values too.
=> SAM-2607 Allow to have empty dates and clear the dates in the datepicker

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
=> 1353: update the gradebook statistics chart

portal/portal-impl/impl/src/bundle/sitenav.properties, portal/portal-impl/impl/src/bundle/sitenav_en_GB.properties, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/moresites.vm, reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js, reference/library/src/morpheus-master/js/src/sakai.morpheus.usernav.js, reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss, reference/library/src/webapp/js/jquery/qtip/tutorial.js, user/user-tool-prefs/tool/src/webapp/css/prefs.css, user/user-tool-prefs/tool/src/webapp/js/manage-hidden-sites.js
Several changes:
* Correct scroll behavior to make sure we can always scroll to the bottom of the list.
* Use a custom CSS class for the star icons to allow them to be overridden via stylesheet change.
* Increase spacing between the button bar and the top of the site drawer.
* Add a close button when in desktop view.
* Correct keyboard strangeness
* If a page doesn't have a tool on it, just skip over it.
* Add more space around the "Profile" link.
* Align the user dropdown arrow to align with the username
=> SAK-30457 UI updates to new Favorites and User dropdown features

reference/library/src/webapp/editor/ckeditor.launch.js
=> SAK-30480 - ckeditor isn't present in resources (removing jquery from

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
:star: Relies on PR #1811 being merged first.
Delivers #1753.  Namely, further improves page load time by speeding up fixedheader and column generation, lazy loading cells with custom JavaScript and loading in the context menu on demand.
=> 1753 performance stuff again

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/GenerateBugReportHandler.java
Logged in users can GET /portal/generatebugreport to trigger the Bug Report screen.
=> SAK-30375 Add a new URL to generate a bug report

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-30495
http://poi.apache.org/changes.html
=> SAK-30495 Poi 3.14

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GbModalWindow.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
Delivers #1353.
Namely: 
- rename > 100% column to EC
- add new yaxis label and reword existing xaxis label
- take into account the vertical scroll offset when positioning the modal at the top of the browser viewport
=> 1353: statistic chart enhancements

kernel/kernel-impl/src/main/sql/mysql/sakai_realm.sql, syllabus/components/src/webapp/WEB-INF/components.xml, syllabus/syllabus-api/src/java/org/sakaiproject/api/app/syllabus/SyllabusService.java, syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java, syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/entityproviders/SyllabusEntityProvider.java, syllabus/syllabus-app/src/webapp/syllabus/main.jsp, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
Fixed up all of the permission checks, wasn't checking correct
permissions for saving or in the Entity. Fixed up a permission check on
the UI.
=> SAK-30141 - Syllabus permissions - Mispelling in SQL script

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/PublishedAssessmentFacadeQueries.java
Idea for fix from @juanjmerono
=> SAM-2742 - Samigo is broken for students

syllabus/syllabus-app/src/java/org/sakaiproject/tool/syllabus/SyllabusTool.java, syllabus/syllabus-app/src/webapp/syllabus/main.jsp, syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
=> SAK-30141 - Loosened permissions some more, fixed some more jsp

samigo/samigo-app/src/webapp/WEB-INF/faces-config.xml
This reverts commit 3678d07e395d92c10eef152dd54207a4e0c5c4a1.
=> SAM-2766 revert "SAM-2378" until jsf 2 where flash params are supported.

reference/library/src/morpheus-master/sass/modules/_toolmenu.scss, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
Fixed an issue leading to the login toolbar overlapping to element below it before authentication (see the bug on Jira).
=> SAK-30489 - Fixed login toolbar height issue.

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/CalculatedQuestionExtractListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
Added validation to check if the formulas have at least one variable
before saving.
=> SAM-2723 Calc. quest. Validation when saving formulas with no variables

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-30565
=> SAK-30565 elasticsearch 1.7.5

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html, gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css, gradebookng/tool/src/webapp/styles/gradebook-print.css
Delivers #1468.
PDF.js looked a little heavy weight for what we needed, which was a dynamic iframe that we populate and print from the content on the page.  I started to go down the new Wicket-page route, but it turned out to be a little heavy weight also.
How it works:  I insert a new iframe, poke in the content and tell it to print.
=> 1468: Add print to student grade summary modal and page

signup/tool/src/webapp/css/signupStyle.css
Adding an extra table/row is how padding is done elsewhere on the page.
=> SAK-30573: Increase space beneath 'View' label and dropdown

site-manage/site-manage-tool/tool/src/webapp/css/site-manage.css, site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm, site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_joinable.vm
https://jira.sakaiproject.org/browse/SAK-30569
Improve spacing between textbox and search button.
=> SAK-30569 improve spacing between textbox and search button

reference/library/src/webapp/js/lang-datepicker/lang-datepicker.js, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/webapp/js/authoring.js, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
I don't think the red X solution was a very good one .... instead this just allows the user to delete the date and leave it empty if the field allows it....
=> SAM-2748 remove crossmark for providing an empty date and just allow user to empty the field

content/content-tool/tool/src/webapp/js/content.js, content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_properties.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_duration.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_enum.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_group.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_number.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_string.vm, content/content-tool/tool/src/webapp/vm/metadata/meta_edit_user.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_text.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_create_urls.vm, content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
See:
https://jira.sakaiproject.org/browse/SAK-30564
There is still quite a bit to be done, just wanted to get this in as things are changing quite rapidly. I apologize in advance for the whitespace changes, but was dealing with 10 years + of inconsistent indentation and it was just very hard to parse the logic and dom structure of the Velocity templates without some whitespace changes.
Also I renamed the branch so commits have the name of the temporary branch, sorry.
=> SAK-30564 Morpheus: Resource responsive changes

webservices/cxf/src/java/org/sakaiproject/webservices/SakaiScript.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiScriptAddMemberToSiteWithRoleBatchTest.java, webservices/cxf/src/test/java/org/sakaiproject/webservices/SakaiScriptRemoveMemberFromSiteBatchTest.java
Improve performance with websevices integrations that need to insert or remove more than one user in a site.
=> SAK-30521 Batch webservices for enroll and remove users in a site

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
https://jira.sakaiproject.org/browse/SAK-29259
regression from SAK-27508
=> SAK-29259 regression: site creation forces site to be added to public index

assignment/assignment-tool/tool/src/webapp/css/assignment.css, assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_tags_list.vm, reference/library/src/webapp/js/spinner.js
Blocker issue because grades can no longer be released.
/CC: @bjones86 does this look okay?
=> SAK-30433 insertSpinnerAfter was using override of an element that did not exist

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/authz/AuthorizationBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/servlet/delivery/DownloadAllMediaServlet.java
responses, can only downlload responses individually.
=> SAM-2622 - Access denied error when attempting to download all

samigo/samigo-app/src/webapp/jsf/template/templateEditor.jsp
Made sure the for attribute of labels matched the correct ID.
Set all the hideDivision id's to the correct value.
=> SAM-2786 Trivial Improvements

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2063: fix bugs for some gradebookng panels when categories are disabled

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java
... to settings page form submission.  Also had handle for `IllegalArgumentException` which seems like another likely exception.
Delivers #2017.
=> 2017: add exception handling for unique category name

samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivityHeadings.jsp
show assessment type tab only if it should
add class so appearance is consistent with other tabs
=> SAM-2789; make tabs in User Activity consistent with the rest of Samigo

portal/portal-util/util/src/java/org/sakaiproject/portal/util/PortalUtils.java
This change ensures that a neccessary variable is correctly inserted
into the Javascript.
=> SAK-30640 Ensure variable is inserted correctly

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/TemplateUpdateListener.java, samigo/samigo-pack/src/bundle/template-assessmentAutoSubmission.xml, samigo/samigo-pack/src/bundle/template-assessmentSubmission.xml, samigo/samigo-pack/src/bundle/template-assessmentTimedSubmission.xml
https://jira.sakaiproject.org/browse/SAM-2794
address the following minor issues:
* Catch possible NPE/NFE when accessing assessment setting for instructor notification
* Remove hard-coded Dayton instance name in favour of "ui.service" from sakai.properties
* Remove hard-coded en_US locale from email template XML so the templates are loaded as 'default' locale
Also did some minor clean-up in the files while I was editing them.
=> SAM-2794: a few small issues with samigo email notifications

assignment/assignment-tool/tool/src/webapp/js/assignments.js, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_grade.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
Hey @bjones86 I think this was another method you added in SAK-26318 and there were two versions of it. I just used this one here which seems to be more specific to the button being clicked on and moved it into the .js file. I tested it out and it seems to be good.
=> SAK-30643 - Clean up handleReportsTriangleDisclosure in assignments

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/data/ifc/assessment/ItemMetaDataIfc.java, samigo/samigo-api/src/java/xml/author/v1p2/fibTemplate.xml, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemModifyListener.java, samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/asi/Item.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
Add ignore spaces option to Fill in the Bank questions within Samigo.
=> SAM-2778 Add "Ignore spaces" option to FIB

citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/BaseCitationService.java, citations/citations-impl/impl/src/java/org/sakaiproject/citation/impl/CitationListAccessServlet.java, citations/citations-tool/tool/src/webapp/css/citations.css
These are:
1.   Remove the 'make site page' action from citations
2.   Correct the jquery path to point at the webjars one.
3.   Only show the white div for action links if there are links.   
4.   Don't show the Export and Print links on the print view.
5.   Increase the height of the success message.
=> SAK-30322: Fixing bugs (E. 1-6)

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp, samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivity.jsp
Fairly straightforward changes to make Samigo appear in similar ways across these new pages.
=> SAM-2793 more bootstrap HTML mods in Samigo esp in Event Log and User Activity Report

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/TemplateUpdateListener.java
https://jira.sakaiproject.org/browse/SAM-2794
Amendment to address the issue @master-bob brought up.
=> SAM-2794 ammendment: set notification to default on catch of NPE/NFE

syllabus/syllabus-app/src/webapp/js/syllabus.js
Bug seems to have been introduced in SAK-29988
/CC: @bjones86 @willkara
=> SAK-30251 syllabus add item was not posting content. 

assignment/assignment-impl/impl/src/java/org/sakaiproject/assignment/impl/BaseAssignmentService.java
https://jira.sakaiproject.org/browse/SAK-30644
@jonespm do you think this will suffice?
=> SAK-30644 problems with assignment submissions that were created prior to 10.6

samigo/samigo-app/src/webapp/jsf/author/allHeadings.jsp, samigo/samigo-app/src/webapp/jsf/author/assessmentHeadings.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/evaluationHeadings.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/questionpoolHeadings.jsp, samigo/samigo-app/src/webapp/jsf/section-activity/sectionActivityHeadings.jsp
Fix up the crazy JSF HTML conditionals and just use panelGroups
=> SAM-2789 re-do JSF HTML to use panelGroups

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Assignment.java, gradebookng/tool/src/webapp/scripts/gradebook-grades.js
.. and also fix categorized sorting not working in the new UI :cry: 
Delivers #2091.
=> 2091: fix NPE when gradable item doesn't have a sort order

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
https://jira.sakaiproject.org/browse/SAK-30388
I took the approach of just using a dedicated 'view' for the grade report UI.
@ern, what say you, good sir?
=> SAK-30388: navigation tabs in assignments is not always showing the correct selected tab

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm
=> SAK-30648 fix assignment title issue

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/TemplateBean.java
samigo.showAssessmentTypes = false
=> SAM-2799 - Admin should still be able to get to templates UI for

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
Search button not in the same line as "View" and "Filter by Term"
Remove the blue box style
=> SAK-30670 Worksite Setup (Tickets 1 & 2)

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java, reset-pass/account-validator-impl/src/java/org/sakaiproject/accountvalidator/logic/impl/ValidationLogicImpl.java, reset-pass/account-validator-tool/src/java/org/sakaiproject/accountvalidator/tool/otp/AcountValidationLocator.java, reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/ConfirmProducer.java, reset-pass/reset-pass/src/java/org/sakaiproject/tool/resetpass/FormHandler.java
=> SAK-29935 - The support.email property isn't defined, chang to

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradeEntryPanel.java
Part of #1363 but does not resolve it.
=> #1363 temporarily disable the percentage entry type

roster2/src/handlebars/overview.handlebars, roster2/src/webapp/WEB-INF/bootstrap.jsp, roster2/src/webapp/css/roster.css
close to the top
This also resolves SAK-30672,SAK-30673 and SAK-30680
=> SAK-30671 Roster - Select components too far one from the other and too

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Also resolves SAK-30676 (Dropbox - select list not aligned and texts)
=> SAK-30678 Dropbox - buttons has no color

syllabus/syllabus-app/src/webapp/syllabus/css/syllabus.css
Not the best color combination but at least is readable
=> SAK-30674 Header text is unreadable on all items

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbHeadersToolbar.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnHeaderPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.java
... so panels don't have to generate their own (causing potential mismatches).
Delivers #2160.
=> 2160: pre-set all category colors on the session's UI settings

chat/chat-tool/tool/src/webapp/css/chat.css, chat/chat-tool/tool/src/webapp/jsp/editRoom.jsp, chat/chat-tool/tool/src/webapp/jsp/listRooms.jsp
This also resolves SAK-30677 Chat - Padding between Start/End dates
needs to be increased
=> SAK-30675 Chat - Table header formatted incorrectly

reference/library/src/morpheus-master/README.md, reference/library/src/morpheus-master/folder-structure.es.md, reference/library/src/morpheus-master/folder-structure.md, reference/library/src/morpheus-master/technologies.es.md, reference/library/src/morpheus-master/technologies.md
Could you take a look to check this documentation? 
Feel free to tell if I missed something of I've lefted over something else
=> SAK-30716 - Morpheus documentation for GIT

samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp
=> SAM-2804 Wrong page Layout (Editing a Survey Question)

assignment/assignment-tool/tool/src/webapp/css/assignment.css, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
=> SAK-30726 Overlapping elements on Assignments resubmission screen

kernel/api/pom.xml, kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java, kernel/api/src/test/java/org/sakaiproject/util/RequestFilterTest.java
This is the start of some tests for RequestFilter.
=> KNL-1336 Add tests for RequestFilter

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/UpdateRandomPoolQuestionsListener.java, samigo/samigo-app/src/webapp/jsf/author/editAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/editPart.jsp, samigo/samigo-app/src/webapp/jsf/author/previewAssessment.jsp, samigo/samigo-app/src/webapp/jsf/author/removePart.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
https://jira.sakaiproject.org/browse/SAM-2811
* Scores -> Total Scores -> "Apply this Score" button
* Edit Assessment -> "Update Questions" button
* Edit Assessment -> "Edit" part links
* Edit Assessment -> Remove Part -> "Remove" and "Cancel" buttons
* Edit Assessment -> Add/Edit Part -> "Save" and "Cancel" buttons.
=> SAM-2811 A few spinners for Samigo

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/poolList.jsp, samigo/samigo-app/src/webapp/jsf/questionpool/poolTreeTable.jsp
=> SAM-2809 Missing folder icon when you have subpools

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/GrantSubmissionListener.java
Fix is very straight forward. Tested locally. Fixed. Please merge to resolve the issue reported by @Molly Kelsey in Jira SAM-1074
=> SAM-1074: Fixing audio recording type submission deletion

samigo/samigo-app/src/webapp/jsf/questionpool/editPool.jsp
=> SAM-2819 Questions table without color-background and unaligned

sections/sections-app/src/webapp/css/sections.css
=> SAK-30689 Section info - Margin needed in Student Membership Input

delegatedaccess/impl/pom.xml, delegatedaccess/pom.xml, deploy/shared/pom.xml, edu-services/cm-service/cm-impl/hibernate-impl/impl/pom.xml, edu-services/sections-service/sections-impl/sakai/impl/pom.xml, webservices/cxf/pom.xml, webservices/cxf/src/java/org/sakaiproject/webservices/SakaiJob.java
- update quartz dependency to use 2.2.x from master
- remove legacy proiles
- use log4j dependency declared in master
=> SAK-30747 Delegatedaccess update quartz dependency

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
Bootstrap added in the jsp and a little code formatting too
=> SAM-2820 Create True/False question screen. Add Bootstrap

samigo/samigo-app/src/webapp/jsf/author/item/fillInNumeric.jsp, samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
Also modified trueFalse.jsp (missed the min points section and removed
an extra div)
=> SAM-2825 Create Numeric Response Screen. Add BootStrap

samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp
=> SAM-2826 Create File upload question screen. Add Bootstrap

samigo/samigo-app/src/webapp/jsf/author/item/calculatedQuestion.jsp
=> SAM-2827 Create CalculatedQuestion screen. Add Bootstrap

reference/library/src/morpheus-master/sass/modules/tool/_base.scss, reference/library/src/morpheus-master/sass/modules/tool/iframe/_iframe.scss, reference/library/src/morpheus-master/sass/tool.scss, web/web-portlet/src/bundle/vm/edit.vm
SAK-30577 - Changed layout of web content edit form and changed placement of edit buttons. Could not replicate other ui issues in ticket. 
Hopefully this pull request is correct. Please let me know what would need to be done to correct it if it is not.  Thank you.
=> Sak-30577  - Web Content Fixes

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/item/fillInTheBlank.jsp
=> SAM-2828 Create Fill in the blank question screen. Add Bootstrap

samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
=> SAM-2830 Create Matching question screen. Add Bootstrap

samigo/samigo-app/src/webapp/jsf/author/item/audioRecording.jsp
=> SAM-2831 Create Student Audio Response question screen. Add Bootstrap

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp
=> SAM-2832 Create Survey question screen. Add Bootstrap

polls/tool/src/webapp/templates/voteAdd.html
Added Bootstrap in the Add Poll screen
=> SAK-30113 QA Testing Poll Tool in Desktop display

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyFriends.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyMessages.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPicture.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPictures.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyProfile.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MySearch.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewFriends.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewPicture.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewPictures.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/ViewProfile.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ChangeProfilePictureUpload.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/CreateWorksitePanel.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyBusinessDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyContactDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInfoDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyInterestsDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MySocialNetworkingDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStaffDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStatusPanel.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/MyStudentDisplay.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/panels/ViewProfilePanel.html, profile2/tool/src/webapp/css/profile2-profile-entity.css, profile2/tool/src/webapp/css/profile2.css, reference/library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, reference/library/src/morpheus-master/sass/base/_extendables.scss, reference/library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss
SAK-30840 - Profile > pictures migration to Bootstrap
SAK-30841 - Profile > Search migration to Bootstrap
SAK-30850 - Privacy migration to Bootstrap
SAK-30852 - Profile > Preferences migration to Bootstrap
=> SAK-30783 - MY PROFILE migration to Bootstrap

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 2122: fix tab from input not retaining focus

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ToggleGradeItemsToolbarPanel.html, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2166: fix show/hide regressions

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbCourseGradeLabel.java
Delivers #2232.
Also fixes Course Grades displaying to TAs after setting a score when Course Grades are hidden to a particular TA (due to bug in dynamic course grade behaviour).
=> 2232: Fix NPE when TA viewing course grades

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
=> 2233: honor the sortBy parameter when getting assignments for TA users

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_grading_submission.vm, reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
=> SAK-30812 Problem with list of "Assign Grade Overrides"

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
=> SAK-30849: xxx111 in filename

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-30867
=> SAK-30867 joda 2.9.3

site-manage/site-manage-tool/tool/pom.xml, site-manage/site-manage-tool/tool/src/bundle/sitesetupgeneric.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-duplicate.vm
Looks like this patch provided some useful code for site duplication. I'm attaching the diff from the ticket that was left uncommitted.
=> SAK-26205 - Integrate the ScoringAgent API into Site Info

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/msgcntr/MsgCntrSiteVolumeFactory.java, textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
Implemented 'getUrl' method for MsgCntrSiteVolumeFactory class so that
correct url is generated for a particular forum or topic in elfinder.
=> SAK-30853 Added correct url for Forums/topic in elFinder.

assignment/assignment-tool/tool/src/webapp/css/assignment.css
=> SAK-30810 Arrow appears in "Model Answer" section

rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/edit.vm
=> SAK-30746 Minor changes checkbox not visible in Wiki

reference/library/src/morpheus-master/sass/modules/tool/_base.scss
=> SAK-30759 Full URLs not displayed well in Short URL pop-up

web/web-portlet/src/bundle/vm/edit.vm
=> SAK-30868 Customize Web Content. Can´t set focus

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
=> SAK-30845 Sakai footer floats to top right of Assignments resubmission

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
=> SAM-2734 The cross out text is missing when deleting a variable/formula

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.java
Delivers #2234 and #2235 and #2273.
=> 2234,2235: Review permissions when categories are disabled

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/ChecklistBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ChecklistProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/webapp/js/checklistAjax.js, lessonbuilder/tool/src/webapp/templates/Checklist.html, lessonbuilder/tool/src/webapp/templates/ShowPage.html
At this point I believe the checklist is functionally complete. There are appearance changes yet to be done, but you can test this version.
=> LSNBDLR-540; make it work in multi-column setup; add CSRF tokens

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java, gradebookng/tool/src/webapp/WEB-INF/web.xml
=> 2225 put app into deployment mode

mailsender/tool/src/java/org/sakaiproject/mailsender/tool/producers/NavBarRenderer.java, mailsender/tool/src/webapp/component-templates/Navbar.html, mailsender/tool/src/webapp/content/css/MailSender.css, mailsender/tool/src/webapp/content/templates/options.html
This also solves SAK-30623 and SAK-30626
=> SAK-30624 Tabbed layout for options/links missing

site/admin-perms-tool/src/main/webapp/WEB-INF/jsp/sitePerms.jsp, site/admin-perms-tool/src/main/webapp/css/AdminSitePerms.css
=> SAK-30851 Misplaced legend on admin site perms

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/permissions/permissions_include.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-30829 Margin issues in permissions when add new forum

samigo/samigo-app/src/webapp/jsf/author/item/matrixChoicesSurvey.jsp
Changed display for large resolutions
=> SAM-2833 Create Survey Matrix question screen. Add Bootstrap

samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/item/matching.jsp
Changed display for large resolutions
=> SAM-2843 Create Matching question screen. Add Bootstrap. Large screens

announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-merge.vm, reference/library/src/morpheus-master/sass/modules/tool/announcements/_announcements.scss
=> SAK-30919 Table too wide in "Merge" screen

portal/portal-api/api/src/java/org/sakaiproject/portal/api/PortalSiteHelper.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/JoinHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PageHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/ToolHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/WorksiteHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/PortalSiteHelperImpl.java
https://jira.sakaiproject.org/browse/SAK-30920
**CC:** @juanjmerono
=> SAK-30920 double escaped characters in site title string

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/statistics/dfStatisticsListByTopic.jsp
=> SAK-30987 Apply Grade to All Ungraded does not display correctly

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfMsgGrade.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-30984 Padding issues on post grading screen

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includePageWithNav.vm, reference/library/src/morpheus-master/sass/_defaults.scss, reference/library/src/morpheus-master/sass/modules/navigation/_breadCrumbs.scss
Incorporates several changes to the Sakai breadcrumb layout in the
desktop view.  Fully described in the above JIRA issue.
=> SAK-30559 Updates to breadcrumbs

sections/sections-app/src/webapp/inc/navMenu.jspf
=> SAK-30948 Section info - The currently selected tab is not styled

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/forum/dfForumSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/topic/dfTopicSettings.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-30982 Link/Help buttons overlap warning when deleting forum/topic

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-30980 Radio buttons in "Template Settings" screen off

reference/library/src/morpheus-master/sass/modules/tool/sitemanage/_sitemanage.scss, site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm
=> SAK-30882 Membership checkbox column doesn't fully collapse

reference/library/src/morpheus-master/js/src/sakai.morpheus.utils.js, reference/library/src/morpheus-master/sass/base/_defaults.scss
This should improve a lot, IMO, the UX on forms
=> SAK-30977 - Disabled anonymous post checkbox should have greyed out styling

profile2/tool/src/webapp/css/profile2.css
Modified to fix the minor issue on mobile display
=> SAK-30866 - Minor issues in profile

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editAccess.vm
=> SAK-31059 Site Visibility Radio input misaligned

reference/library/src/morpheus-master/sass/base/_extendables.scss
=> SAK-31022 Mobile - site description "More" lightbox opens to the right

jobscheduler/scheduler-tool/src/webapp/scheduler/create_job.jsp
https://jira.sakaiproject.org/browse/SAK-31069
**CC:** @ottenhoff looks like this is a regression introduced in SAK-30719. Reverting changes to this file from that commit fixes the issue, and no other display issues are created by doing so.
=> SAK-31069 admin workspace->job scheduler->jobs->new job->stack trace

assignment/assignment-tool/tool/src/webapp/css/assignment.css, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
=> SAK-31063 All Purpose Item needs some reformatting

authz/authz-tool/tool/src/webapp/vm/admin/chef_realms_edit_role.vm
=> SAK-30065 Realms show incorrectly the checkboxes in Morpheus

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/PagePickerProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowItemProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/producers/ShowPageProducer.java, lessonbuilder/tool/src/resources/messages.properties, lessonbuilder/tool/src/resources/messages_ca.properties, lessonbuilder/tool/src/resources/messages_de.properties, lessonbuilder/tool/src/resources/messages_es.properties, lessonbuilder/tool/src/resources/messages_fr.properties, lessonbuilder/tool/src/resources/messages_it.properties, lessonbuilder/tool/src/resources/messages_ko.properties, lessonbuilder/tool/src/resources/messages_pt_BR.properties, lessonbuilder/tool/src/resources/messages_zh_TW.properties
this commit contains no substantive changes. Its intent is to set the committer correctly.
=> LSNBLDR-585; "Return to Lessons" now dynamic

reference/library/src/morpheus-master/js/src/sakai.morpheus.subnav.js, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
* Show the tool dropdown for the active site as well.
* Left align menus and adjust styles to match
* Improve keyboard handling for tool menus
* Close the active tool menu when clicking outside of the menu
=> SAK-30530 Sakai Favorite Site Tool Dropdown Menu Enhancements

basiclti/pom.xml, dashboard/impl/pom.xml, delegatedaccess/pom.xml, help/help-component/pom.xml, master/pom.xml
@ern is this correct way to do dependencies? version gets defined in master but not listed as provided?
=> SAK-31112 rationalizing commons-configuration dependencies

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-30055 QA Testing Forum Tool in Desktop display

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
=> SAK-30994 Honor pledge check box is out of alignment

polls/tool/src/webapp/templates/voteQuestion.html
=> SAK-31095 the poll text appears as an info box

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
=> 2299: hide the toolbar when gradebook is empty

samigo/samigo-app/src/webapp/jsf/evaluation/detailedStatistics.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/exportResponses.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/histogramScores.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/submissionStatus.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/totalScores.jsp
=> SAM-2862 missing styling on subset of tabs

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
=> 2381 don't do any category score work when the category is null

syllabus/syllabus-app/src/webapp/js/syllabus.js
=> SAK-30953 Reposition modal for new item lower on page

reference/library/src/morpheus-master/sass/modules/tool/siteinfo/_siteinfo.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-list.vm
=> SAK-31035 Groups Unjoin button does not line up with joined group

sitestats/sitestats-tool/src/webapp/html/pages/AdminPage.html, sitestats/sitestats-tool/src/webapp/html/pages/OverviewPage.html, sitestats/sitestats-tool/src/webapp/html/pages/PreferencesPage.html, sitestats/sitestats-tool/src/webapp/html/pages/ReportDataPage.html, sitestats/sitestats-tool/src/webapp/html/pages/ReportsEditPage.html, sitestats/sitestats-tool/src/webapp/html/pages/ReportsPage.html, sitestats/sitestats-tool/src/webapp/html/pages/ServerWidePage.html
=> SAK-31083 Link/Help buttons overlay horizontal line for tool subpages

reference/library/src/morpheus-master/sass/modules/tool/iframe/_iframe.scss
=> SAK-30968 Buttons appear on top of the tool content

sitestats/sitestats-tool/src/java/org/sakaiproject/sitestats/tool/wicket/components/EventRegistryTree.java, sitestats/sitestats-tool/src/webapp/html/components/EventRegistryTree.html
I've updated the branch, my mistake
=> SAK-31081 - Statistics does not use updated tool/info icons

profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPreferences.html, profile2/tool/src/java/org/sakaiproject/profile2/tool/pages/MyPrivacy.html, reference/library/src/morpheus-master/sass/modules/tool/profile2/_profile2.scss
This also solves SAK-31120 Privacy tab - table elements display
full-width, causing spacing issues
=> SAK-31121 Preferences tab - table displays full-width

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-editToolGroupFeatures.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteConfirm.vm
https://jira.sakaiproject.org/browse/SAK-31128
Change the buttons to type="submit"
=> SAK-31128 spinner not being applied to select tool list and confirmation page's buttons during worksite setup process

textarea/elfinder-sakai/pom.xml, textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/SakaiFsService.java, textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/samigo/SamFsItem.java, textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/samigo/SamSiteVolumeFactory.java, textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
I feel there are some things we can improve in the future here (as show or not this option based in some permissions and add the i18n. But this is the basic functionality working and we can improve that in next jiras.
=> SAM-2687 Adding elFinder support to samigo

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/assignment/AssignmentSiteVolumeFactory.java, textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
Implemented getUrl method in AssignmentSiteVolumeFactory classwhich returns
correct url for each assignment item.
=> SAK-30854 Corrected url for assignments in elFinder.

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp
All options have been indented, the javascript hardcoded has been refined and changed to allow every suboption to appear in the right place.
=> SAM-2855: Options not indented

assignment/assignment-tool/tool/src/webapp/css/assignment.css, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_list_submissions.vm, reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss
=> SAK-30998 Styling issues on "Grade" screen

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/css/tool_sam.css, samigo/samigo-app/src/webapp/jsf/event/eventLog.jsp
=> SAM-2857 Text missing in Search and clear buttons, also not aligned

reference/library/src/morpheus-master/sass/modules/tool/jobscheduler/_jobscheduler.scss, reference/library/src/morpheus-master/sass/tool.scss
=> SAK-30722 Quartz logo is cut off at bottom

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-modifyENW.vm
https://jira.sakaiproject.org/browse/SAK-31144
Change the buttons to type="submit"
=> SAK-31144 spinner not being applied to buttons on configure instance based tools UI

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/site/MoreSiteViewImpl.java
Fixing a NPE caused by this branch in trunk. My apologies.
=> SAK-30712 - Fixing NullPointerException

roster2/src/handlebars/enrollments.handlebars, roster2/src/handlebars/members.handlebars
https://jira.sakaiproject.org/browse/SAK-31154
=> SAK-31154 Added alt tags to profile images in the Roster tool

profile2/tool/src/java/org/sakaiproject/profile2/tool/components/ProfileImage.java
https://jira.sakaiproject.org/browse/SAK-30748
=> SAK-30748 Added alt text to ProfileImage component

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesConstants.java, content/content-tool/tool/src/java/org/sakaiproject/content/tool/ResourcesHelperAction.java, kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/BaseContentService.java
This is the long-term behavior of Sakai that was changed in Sakai 10.6.
/CC: @bjones86 can you review the one functionality change here the *fileSizeKB* conditional
=> KNL-1433 setting default site quota to 1GB. 

reference/library/src/morpheus-master/sass/modules/tool/signup/_signup.scss, reference/library/src/morpheus-master/sass/tool.scss, signup/tool/src/webapp/css/signupStyle.css, signup/tool/src/webapp/js/signupScript.js, signup/tool/src/webapp/signup/attendee/editComment.jsp, signup/tool/src/webapp/signup/attendee/signupMeeting.jsp, signup/tool/src/webapp/signup/download/downloadSelections.jsp, signup/tool/src/webapp/signup/newMeeting/assignStudents.jsp, signup/tool/src/webapp/signup/newMeeting/step1.jsp, signup/tool/src/webapp/signup/newMeeting/step2.jsp, signup/tool/src/webapp/signup/organizer/copyMeeting.jsp, signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp, signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp, signup/tool/src/webapp/signup/organizer/viewComment.jsp, signup/tool/src/webapp/signup/signupMeetings.jsp, signup/tool/src/webapp/signup/updatePermission.jsp
This also solves SAK-31156 Signup. Several screens are not responsive
=> SAK-31099 Signup. Padding/spacing in "add" screen

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPanel.java, gradebookng/tool/src/webapp/styles/gradebook-grades.css
Delivers #1701.
- show it by default as 'All Changes Saved'
- float it to the right of the Add button
- remove background color
- also ensure is showing ok for TAs
=> 1701: restyle the live feedback notification

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CategoryColumnCellPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeItemCellPanel.java
=> 2471: only flash the course grade or category average if the value of the cell changes

announcement/announcement-tool/tool/src/bundle/announcement.properties, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-customize.vm, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-delete.vm, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-metadata.vm, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-preview.vm, announcement/announcement-tool/tool/src/webapp/vm/announcement/chef_announcements-revise.vm, reference/library/src/morpheus-master/sass/modules/tool/announcements/_announcements.scss
This also resolves:
SAK-30908 2 page navigations
SAK-30460 Checkbox left margin too small on Home Display Options
SAK-30912 visual distinction for the actual "Message"
=> SAK-30910 increase padding between the info box

mailsender/api/src/java/org/sakaiproject/mailsender/logic/ExternalLogic.java, mailsender/impl/src/java/org/sakaiproject/mailsender/logic/impl/ExternalLogicImpl.java, mailsender/impl/src/test/org/sakaiproject/mailsender/logic/impl/ExternalLogicImplTest.java, mailsender/pack/src/webapp/WEB-INF/components.xml, mailsender/tool/src/java/org/sakaiproject/mailsender/tool/beans/EmailBean.java
Attachments sent to email archive from Email tool arent accessible
=> SAK-31174 - Attachments sent to email archive from Email tool arent accessible

gradebookng/tool/pom.xml
https://jira.sakaiproject.org/browse/SAK-31181
=> SAK-31181 poi & xlmsbeans

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsGradingSchemaPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html
=> 2508: Fix Bootstrap/Morpheus styling anomalies for dropdowns and a few buttons

samigo/samigo-pack/pom.xml, samigo/samlite-impl/pom.xml
https://jira.sakaiproject.org/browse/SAM-2881
2.2.0 - 2007
2.6.0 - 2012
=> SAM-2881 XMLBeans 2.6.0

calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_new.vm, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_revise.vm, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_setFrequency.vm, calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar_viewList.vm, reference/library/src/webapp/js/lang-datepicker/lang-datepicker.js
Included correction on lang-datepicker library, as it sometimes added default time even when it should only show the date.
=> SAK-30240 update date widget in Calendar tool

reference/library/src/webapp/editor/ckextraplugins/autosave/lang/zh-cn.js
change sakai11.x\reference\library\src\webapp\editor\ckextraplugins\autosave\lang\zh-cn.js
=> SAK-30863 change zh to zh-cn

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/BasePage.java
=> 2538 Moved the tabs around

site-manage/site-manage-participant-helper/src/webapp/content/css/AddParticipant.css, site-manage/site-manage-participant-helper/src/webapp/content/templates/Add.html
=> SAK-31143 Participant Status options are cut off in Firefox

reset-pass/account-validator-tool/src/webapp/templates/newUser.html, reset-pass/account-validator-tool/src/webapp/templates/passwordReset.html, reset-pass/account-validator-tool/src/webapp/templates/requestAccount.html, reset-pass/account-validator-tool/src/webapp/templates/transferMemberships.html, reset-pass/account-validator-tool/src/webapp/templates/validate.html
jQuery is not loaded correctly in Account Validator
=> SAK-31202 - jQuery is not loaded correctly in Account Validator

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/SettingsCategoryPanel.html
=> 1858: use btn-default more consistently

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 2552: Fix javascript selector for visual cue when columns are hidden

msgcntr/messageforums-app/src/webapp/jsp/privateMsg/pvtMsg.jsp, reference/library/src/morpheus-master/sass/modules/tool/messages/_messages.scss
=> SAK-30929 "Check All" column too wide

reference/library/src/morpheus-master/sass/modules/tool/sitesetup/_sitesetup.scss, reference/library/src/morpheus-master/sass/tool.scss, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-findCourse.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteConfirm.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourseManual.vm
This also solves SAK-31044 Confirmation screen - multiple blue info boxes
=> SAK-31041 Mobile - course/section information - extra table/column

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm, reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
The spinner was replaced by a FA icon. This commit automatically also removed unnecessary tabs and spaces in empty lines.
=> SAK-31185 Replaced ajax loading gif for a FA icon

reset-pass/account-validator-tool/src/webapp/WEB-INF/web.xml
Validate account page looks right ugly
=> SAK-31160 - Validate account page looks right ugly

chat/chat-tool/tool/pom.xml, content/content-tool/tool/pom.xml, gradebook/app/business/pom.xml, gradebook/app/sakai-tool/pom.xml, gradebook/app/ui/pom.xml, jsf/jsf-widgets/pom.xml, msgcntr/messageforums-app/pom.xml, postem/postem-app/pom.xml, signup/pom.xml, syllabus/syllabus-app/pom.xml, user/user-tool-prefs/tool/pom.xml
https://jira.sakaiproject.org/browse/SAK-31197
=> SAK-31197 tomahawk 1.1.14

samigo/samigo-app/src/webapp/jsf/template/templateEditor.jsp
Added in labels for some form elements.
=> SAM-2786 -2 Accessibility improvements

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/rest/GradebookNgEntityProvider.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/webapp/scripts/gradebook-grades.js, gradebookng/tool/src/webapp/styles/gradebook-grades.css
- added a 'ping' endpoint to the gbng entity provider
- employ some JavaScript to hit this ping endpoint every 5 seconds to check for a connection
- show a message if the request errors or suffers a timeout after 10 seconds
Delivers #2537.
=> 2537: add poll to detect broken connection and display a message to the user

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/SakaiFsService.java
Do not search admin site for tools
=> SAK-30922 - Do not search admin site for tools

calendar/calendar-tool/tool/src/webapp/vm/calendar/chef_calendar-merge.vm
=> SAK-31182 Mobile view: extra empty column shown when merging internal

mailsender/tool/src/java/org/sakaiproject/mailsender/tool/beans/EmailBean.java
Show the original file name instead of multipart file name
=> Sak 31174 - Show the original file name instead of multipart file name

msgcntr/messageforums-app/src/webapp/jsp/synoptic/synMainLite.jsp
=> SAK-31230 Extra blank column in "Message Center Notifications" Synoptic

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourse.vm
https://jira.sakaiproject.org/browse/SAK-31235
Change the buttons to type="submit"
=> SAK-31235 spinner not being applied to buttons on course section selection interface

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-list.vm
=> SAK-31231 Extra blank column in Sites list

reference/library/src/morpheus-master/sass/modules/tool/sitesetup/_sitesetup.scss, reference/library/src/webapp/skin/tool_base.css
=> SAK-31045 "Created" confirmation lightbox displays too low on page

user/user-tool-prefs/tool/src/webapp/css/prefs.css, user/user-tool-prefs/tool/src/webapp/js/manage-hidden-sites.js
=> SAK-31173 H2 title in hidden sites is cut off if title is too long

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewMessage.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/message/dfViewThread.jsp, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-31232 Previous/Next Conversation links not styled

msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateOrganize.jsp
=> SAK-30979 Odd styling of "Organize" screen

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventEntityProvider.java
This was missed from previous PR. Should be part of that.
=> SAK-31206 apply the refactored code to the site provider

calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventEntityProvider.java, calendar/calendar-tool/tool/src/java/org/sakaiproject/calendar/entityproviders/CalendarEventSummary.java
Note that is depends on #2618. Please merge that first.
=> SAK-31247 Add siteId to event response in calendar event entityprovider

calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/css/cal.css, calendar/calendar-summary-tool/tool/src/webapp/summary-calendar/prefs.jsp
=> SAK-31103 calendar options - formatting of elements & select icon in

reference/library/src/morpheus-master/sass/base/_extendables.scss, reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
=> SAK-30960 Drag-n-drop upload field missing formatting

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
=> SAM-2889 Messy formatting in "About this assesment" for a published

reference/docs/conversion/sakai_10_7-10_8_mysql_conversion.sql, reference/docs/conversion/sakai_10_7-10_8_oracle_conversion.sql, reference/docs/conversion/sakai_11_mysql_conversion.sql, reference/docs/conversion/sakai_11_oracle_conversion.sql
LSNBLDR-500 was merged into 10.x .... so now we need proper conversion scripts.
=> SAK-31237 Sakai 10.8 conversion scripts

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/model/GradebookUiSettings.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameColumnHeaderPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameColumnHeaderPanel.java
Delivers #2594. We already had the ability to sort by student first or last name.  I've added the ability to set the SortDirection for that column via a cell header link.
=> 2594: add ability to click student header to change sort direction

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
=> 2591: make info messages success messages where it makes sense

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
The input style is only required for multiple choices questions.
=> SAM-2891: Extra Margin in True False questions

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
Allow roles returned by RoleProvider to be enabled/disabled.
=> SAK-29970 - Allow roles returned by RoleProvider to be enabled/disabled.

reference/library/src/webapp/editor/ckeditor.launch.js, textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/SakaiFsService.java, textarea/elfinder-sakai/src/webapp/WEB-INF/applicationContext.xml
elFinder not longer working for browsing My Workspace
=> SAK-31115 - elFinder not longer working for browsing My Workspace

postem/postem-app/src/webapp/WEB-INF/faces-config.xml
=> SAK-31251 - Postem doesn't display error messages, remove redirect

samigo/samigo-app/src/webapp/include/header.inc, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp
using the "Published Assessment URL"
=> SAM-2890 Styles lost and CKEditor not working when taking an assesment

signup/tool/src/webapp/signup/newMeeting/step1.jsp, signup/tool/src/webapp/signup/organizer/copyMeeting.jsp, signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp
=> SAK-31258 Announce Availability radio button misaligned (with spanish

reference/library/src/morpheus-master/sass/modules/tool/signup/_signup.scss, signup/tool/src/webapp/signup/download/downloadSelections.jsp, signup/tool/src/webapp/signup/signupMeetings.jsp
=> SAK-31259 - Expand/Collapse button in Meeting list cut off

reference/library/src/morpheus-master/sass/modules/navigation/_breadCrumbs.scss
=> SAK-31256 Default anchor hover same color as background on small screen

reference/library/src/morpheus-master/sass/base/_rtl.scss, reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss
I've modified profile and some issues on breadcrumbs and moresites too because they were not thinked for internationalization
=> SAK-31260 - Sakai 11 RTL layout Issue

reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
text for hidden folders
After:
=> SAK-31176 - All site files: difficult to read file tree

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/StudentPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameCellPanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
=> 2594 fixes for student grade summary sorting, printing and category grouping

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2669: fix course grade cell alignment

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
=> SAM-2888 Settings, padding/alignment issues

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
Potential bug in MathUtils.equalsIncludingNaN, MathUtils.equals should be sufficient.
=> SAM-2873 Samigo Question review shows incorrect scoring due.

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
=> SAM-2883 Bullets do not display in question or answer text

deploy/shared/pom.xml, master/pom.xml, samigo/samigo-app/pom.xml, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/jsf/validator/FinQuestionValidator.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/author/ItemBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ContentsDeliveryBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/ItemContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/delivery/SectionContentsBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/evaluation/QuestionScoresBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/QuestionScoreUpdateListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/TotalScoreUpdateListener.java, samigo/samigo-services/pom.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/integration/helper/integrated/GradebookServiceHelperImpl.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java
It looks like it's all samigo, and it wouldn't conflict if we did want to leave both commons-math3 and commons-math in there, but the upgrade was pretty easy and I'm sure would fix some bugs from 2011's version for whoever used it.
=> SAK-31280 - Upgrade to commons-math3

samigo/samigo-app/src/webapp/jsf/questionpool/addPool.jsp
=> SAM-2898 Add Question Pool screen needs some formatting

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java, gradebookng/tool/src/webapp/styles/gradebook-importexport.css
Add internationalisation to the selection step page
Fix placeholders on other pages
WIP.
=> #1356 Grey out items with no changes

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/select/SelectActionListener.java
https://jira.sakaiproject.org/browse/SAM-2900
=> SAM-2900: Show scoring option to student if they have been allowed retakes

samigo/samigo-app/src/webapp/jsf/author/item/trueFalse.jsp
=> SAM-2902 Create Question (True/False) Label for answer displayed below

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp
https://jira.sakaiproject.org/browse/SAM-2903
=> SAM-2903: Relocate extended date/time exceptions to after the main date/time setting

samigo/samigo-app/src/webapp/css/print/print.css
Fixed in Chrome and Explorer. Still not working in Firefox (it prints
only the first two pages).
=> SAM-2720 Wrong format when printing an assessment in HTML

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/samlite/samLiteEntry.jsp
=> SAM-2906 Create Assessment using markup text screen needs some

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-newSiteCourseManual.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-siteInfo-editInfo.vm
[JIRA - SAK-31261](https://jira.sakaiproject.org/browse/SAK-31261)
=> SAK-31261 - site-manage - create site with no roster issue

reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss
=> SAK-31289 Label does not wrap when text too long in Permissions

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
=> SAM-2876 Questions Page: question text is grey in trunk, expect black

samigo/samigo-app/src/webapp/jsf/evaluation/downloadFileSubmissions.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResult.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/gradeStudentResultFromSectionActivity.jsp, samigo/samigo-app/src/webapp/jsf/select/selectIndex_content.jsp
https://jira.sakaiproject.org/browse/SAM-2908
=> SAM-2908: Restore remaining statistics links hidden by hasRandomDrawPart flag

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/DirectToolHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/PresenceHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/ToolHandler.java
Revert "SAK-15710"
This reverts commit fdc55154304980e7f9e143c70c8289997b50683a.
=> SAK-31221 Remove support for sitevisit.security.advisor

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/css/tool_sam.css
https://jira.sakaiproject.org/browse/SAM-2910
=> SAM-2910: Let Morpheus control the navIntraTool styles

kernel/kernel-impl/src/main/sql/hsqldb/sakai_site.sql, kernel/kernel-impl/src/main/sql/mysql/sakai_site.sql, kernel/kernel-impl/src/main/sql/oracle/sakai_site.sql, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeLoginNav.vm
Reverts sakaiproject/sakai#2729 so it can just be merged to 11.x
=> Revert "SAK-31286 - Remove remaining references to dashboard"

common/import-impl/src/test/org/sakaiproject/importer/impl/XPathHelperTest.java, samigo/samigo-qti/pom.xml, samigo/samigo-qti/src/java/org/sakaiproject/tool/assessment/qti/util/XmlStringBuffer.java
Added tests for common/import-impl/.../XPathHelper.java
Added common-impl dependency to samigo-qti
Updated samigo/samigo-qti/.../XmlStringBuffer.java to use XPathHelper.java
=> SAK-31209 Remove duplicated code from samigo-qti/.../XmlStringBuffer.java

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
=> SAK-31318 Recent Item star appears on the left of the folder

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-31317
=> SAK-31317 joda-time 2.9.4

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
=> SAK-31313 Footer not in the right place for student's Submissions

msgcntr/messageforums-app/src/webapp/css/msgcntr.css
=> SAK-31268 Copy-link popup. If the title is too long overlaps with the

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
=> SAM-2829 Create Hot Spot question screen. Add Bootstrap

gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2649: remove button styling from notification popover lists

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
=> 2747: tinker with wording of the Edit Comment menu option label

msgcntr/messageforums-app/src/webapp/css/msgcntr.css, msgcntr/messageforums-app/src/webapp/jsp/synoptic/synMainLite.jsp
=> SAK-31327 Synoptic messages tool needs re-adjusting to be able to show

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includePageBody.vm
https://jira.sakaiproject.org/browse/SAK-31341
=> SAK-31341 add the ability for a tool to suppress it's own title

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
=> SAM-2922 Checkboxes and Radio buttons in Assessment Settings not

samigo/samigo-app/src/webapp/jsf/author/item/shortAnswer.jsp
=> SAM-2923 Footer misplaced in Create Short Answer/Essay screen

kernel/api/pom.xml, kernel/api/src/main/java/org/sakaiproject/util/RequestFilter.java, rsf/sakai-rsf-core/pom.xml, rsf/sakai-rsf-core/src/java/org/sakaiproject/rsf/copies/Web.java
Improves the use of the force.url.secure property to reduce the chances
of an exception.
=> KNL-1435 Improve force.url.secure implementation

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss
=> SAM-2929 Bullet points appear in student´s answers screen when reviewing

reference/library/src/morpheus-master/sass/base/_extendables.scss
=> SAK-31360 Drag-n-Drop Upload: Error message max upload size cut off

syllabus/syllabus-impl/pom.xml, syllabus/syllabus-impl/src/java/org/sakaiproject/component/app/syllabus/SyllabusServiceImpl.java
Fix syllabus duplication issue by adding in a null check.
=> SAK-31361 Fix syllabus dupe issue caused by NPE

samigo/samigo-app/src/webapp/js/samigo-global.js, samigo/samigo-app/src/webapp/jsf/delivery/deliverAssessment.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
[JIRA - SAM-2926](https://jira.sakaiproject.org/browse/SAM-2926)
=> SAM-2926 - Survey: Matrix of Choices - many instances of this type in a single page produces misbehavior

reference/library/src/morpheus-master/sass/base/_extendables.scss
=> SAK-30743 Upload file bar covers file title when uploading to Resources

samigo/samigo-app/src/webapp/jsf/evaluation/questionScore.jsp
=> SAM-2931 Grading an assessment. Question screen needs some formatting

samigo/samigo-app/src/webapp/jsf/print/printAssessment.jsp
=> SAM-2934 Option overlaps with Link/Help buttons in the Print assesment

basiclti/basiclti-common/src/java/org/sakaiproject/basiclti/util/SakaiBLTIUtil.java, basiclti/basiclti-common/src/test/org/sakaiproject/basiclti/util/SakaiBLTIUtilTest.java
=> SAK-31364 - Restore legacy semicolon processing

reference/docs/conversion/sakai_11_mysql_conversion.sql, reference/docs/conversion/sakai_11_oracle_conversion.sql
This change backports only the database changes from SAK-31184 in
order to reduce migration issues in the future.
=> SAK-31315 -2 Backport DB changes from SAK-31184

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.java
=> 2686: in export default course grade to false and ensure has '#' prefix

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/InstructorGradeSummaryGradesPanel.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.java
=> 2849: add support for percentage mode on grade summary views

gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2848: fix toggle column button flow in FF

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java
=> 2806: only show live feedback message when there are grades to be graded

samigo/samigo-app/src/webapp/jsf/template/templateEditor.jsp
Removed an extraneous div which broke the accordions. Also caused
SAM-2933 (footer misplaced).
Removed old comments.
=> SAM-2915 SAM-2933 Fix Assessment Template Editor

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
=> SAK-31372 "+" indicating content in Folder does not appear in Mobile

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/template/templateIndex.jsp
This also fixes SAM-2932 Display issues in Assessment types list
=> SAK-31379 Error Message Cutoff / Awkward Spacing in Assessment Type

site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership.vm, site-manage/site-manage-tool/tool/src/webapp/vm/membership/chef_membership_joinable.vm
=> SAK-31390 Extra blank column in "My Current Sites" and "Joinable Sites"

signup/tool/src/webapp/signup/attendee/signupMeeting.jsp
=> SAK-31287 "Back" button formatted as a link in the View meeting screen

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/author/preview_item/MatrixChoicesSurvey.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatrixChoicesSurvey.jsp
=> SAM-2665 Survey Matrix Question Type Column Headers - No Space

basiclti/basiclti-portlet/src/webapp/edit.jsp
=> SAK-30629 Checkboxes not aligned properly in Edit screen

gradebook/app/ui/src/webapp/css/spreadsheetUI.css
=> SAK-30637 text within cells is cut off at the bottom in "all grades"

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp
=> SAK-30830 Empty message shown after file attached

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.java
=> 2850: update statistics view to handle percentage mode

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.java
=> 2844: update set empty grade workflow to handle percentage mode

reference/library/src/morpheus-master/sass/base/_icons.scss, reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverImageMapQuestion.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMatching.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceMultipleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverMultipleChoiceSingleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverTrueFalse.jsp
Replace gifs with Font Awesome Icons
=> SAM-2928 Formatting errors when showing feedback on Multiple Choice.

reference/library/src/morpheus-master/sass/_defaults.scss, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
[JIRA](https://jira.sakaiproject.org/browse/SAK-31397)
=> SAK-31397 - Suggested style improvement to minimized flags in minimized tools side navigator

content/content-tool/tool/src/webapp/vm/resources/sakai_properties.vm
=> SAK-31227 Formatting issues in Create Folder screen

reference/library/src/webapp/content/server_info.html
forgot to open the links in their own windows. this fixes that.
=> SAK-31385 Update the Welcome text for Sakai OOTB

reference/library/src/webapp/editor/ckextraplugins/templates/default.js
Add header row information for accessibility purposes to two table examples.
=> SAK-31193 Add header row information for accessibility purposes to two table examples.

user/user-util/src/java/org/sakaiproject/user/util/ConvertUserFavoriteSitesSakai11.java
Just put out a message every 10 seconds.
=> SAK-31408 Simplify progress reporting

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
=> 2912: when viewing as a student and getTotalPointsPossible returns null

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbAjaxButton.java
=> 2791: ensure ajaxbutton stays disabled when it invokes a redirect and that redirect is SLOW

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbHeadersToolbar.java
=> 2914: add tooltip to category header cells

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
=> 2849: fix % showing if there's no grade in student summary

user/user-util/pom.xml
Thanks for the heads up @ern :)
=> SAK-31433 Drop the unused commons-logging dependency

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/ExtendedTimeService.java
=> SAM-2914 - Auto submit job doesn't handle extended due dates

reference/library/src/morpheus-master/sass/_defaults.scss, reference/library/src/morpheus-master/sass/base/_bootstrap-defaults.scss, reference/library/src/morpheus-master/sass/base/_defaults.scss, reference/library/src/morpheus-master/sass/base/_extendables.scss, reference/library/src/morpheus-master/sass/base/_responsive.scss, reference/library/src/morpheus-master/sass/examples/_customization_example_empty.scss, reference/library/src/morpheus-master/sass/modules/_main.scss, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss, reference/library/src/morpheus-master/sass/modules/access/_base.scss, reference/library/src/morpheus-master/sass/modules/more-sites/_base.scss, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss, reference/library/src/morpheus-master/sass/modules/navigation/_skipnav.scss, reference/library/src/morpheus-master/sass/modules/profile-popup/_base.scss, reference/library/src/morpheus-master/sass/modules/tool/_base.scss, reference/library/src/morpheus-master/sass/modules/tool/_menu.scss, reference/library/src/morpheus-master/sass/modules/tool/assignments/_assignments.scss, reference/library/src/morpheus-master/sass/modules/tool/forums/_forums.scss, reference/library/src/morpheus-master/sass/modules/tool/lessonbuilder/_lessonbuilder.scss, reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, reference/library/src/morpheus-master/sass/modules/tool/signup/_signup.scss
https://jira.sakaiproject.org/browse/SAK-31402
=> SAK-31402: Provide finer grained morpheus style variables

textarea/elfinder-sakai/src/java/org/sakaiproject/elfinder/sakai/samigo/SamSiteVolumeFactory.java
This PR fixes the problems on original PR by Diego:
https://github.com/sakaiproject/sakai/pull/2891
=> SAK-31330 Problem in opening an assessment from elFinder

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
=> 2940: fix category average calculation for 'points' gradebook

assignment/assignment-tool/tool/src/webapp/vm/assignment/assignment_macros.vm, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_instructor_new_edit_assignment.vm
The parameter is not needed any more and so can be dropped.
=> SAK-31389 Cleanup buttonBar macro.

reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js
[SAK-31456](https://jira.sakaiproject.org/browse/SAK-31456)
=> SAK-31456 - Collapsible side-tools menu won't stayed minimized after page refreshes

reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
[JIRA](https://jira.sakaiproject.org/browse/SAK-31465)
[Video demo](https://goo.gl/bHC7jZ)
=> Animated following side navTools on scroll

gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 2957: ensure greater padding so menu doesn't invoke second vertical scrollbar

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbHeadersToolbar.java
=> 2914: add weight to the category header tooltip

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/CollectionAccessFormatter.java
File type icons not shown in access view of resources
=> SAK-31463 File type icons not shown in access view of resources

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSiteService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/content/impl/test/RoleAccessTest.java, kernel/kernel-impl/src/test/java/org/sakaiproject/site/impl/test/SiteAliasCleanupNotificationActionIntegrationTest.java, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
NOTE: add label for merging this into the 11 version
=> SAK-31415 Turn on soft site deletion by default

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
=> SAM-2914 - Auto submit job, logic reversed

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/PermissionsPage.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/CourseGradeOverridePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeStatisticsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/UpdateUngradedItemsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/ZeroUngradedItemsPanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
I've somewhat begrudgingly made buttons blue for most actions and a few notable secondary actions are now grey.
Delivers #2979.
=> 2979: Bring GradebookNG buttons into line with Sakai button paradigms

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
=> #2736 fix the percentage conversion error

reference/library/src/morpheus-master/sass/_defaults.scss, reference/library/src/morpheus-master/sass/modules/swapped-view/_base.scss
=> SAK-31480 Student view show a black bar on top

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentNameColumnHeaderPanel.html
=> 2653: add accesskey 'f' to the student column filter field

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
=> SAM-2916 Regression: Samigo allows to save Survey questions without

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/ExportPanel.html
=> 3028: make export button blue

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java
… when category does not have any assignments.
Delivers #3024.
=> 3024: fix categoryGrade exception on student grade summary

reference/library/src/morpheus-master/sass/base/_icons.scss
Evaluation system does not have an icon
=> SAK-31499 - Evaluation system does not have an icon

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java
When a user is submitting an assignment we grant them the ability to see hidden folders so that they
can see inside the hidden attachments folder. This also switch the content review security advisor to use the same code. The permissions it granted were slightly different but I don’t think that the additional permissions are needed.
=> SAK-31516 Assignments submissions allow hidden perm

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java
Delivers #3057 (can go to test) as part of #1356 (leave open)
=> #3057 show points on the import confirmation screen

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/ItemAddListener.java
=> SAM-2961 Insert New Question pop down not resetting after question

master/pom.xml
Fixed sakai version in the master pom.xml
=> Fixed sakai version in the master pom.xml

content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
Drop box on mobile doesnt have "Highlight (*) individual dropboxes with
recent changes" label
=> SAK-31565 - Drop box on mobile doesnt have a label

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includePageWithNav.vm
=> SAK-31566 - Missing title in reset link

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
SAK-29458 & SAK-29367 / Icon URL is ignored / not displayed
=> SAK-29458 Icon URL is ignored / not displayed

site-manage/site-manage-tool/tool/src/webapp/vm/sitebrowser/chef_sitebrowser_list.vm
Poor display of paging at site browser
=> SAK-31578 - Poor display of paging at site browser

kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/ClusterEventTracking.java
This change allows for caching to be set up if it is definied in the
sakai.properties. Previously, the ClusterEventTracking.eventsCache
and CET.eventsLastCache where enabled regardless of the
memory.cluster.names settings.
Jira: https://jira.sakaiproject.org/browse/KNL-1442
=> KNL-1442 Improve ClusterEventTracking cache setup

assignment/assignment-tool/tool/src/webapp/js/assignments.js
Check the property and add all submissions in case.
=> SAK-31532 allow downloading all submissions

samigo/samigo-app/src/webapp/jsf/author/item/multipleChoice.jsp, samigo/samigo-app/src/webapp/jsf/author/item/shortAnswer.jsp
for Multiple Choice and Short anwer questions
I´ve also added some bootstrap classes missing.
=> SAM-2986 Regression: Save/Cancel buttons missing on the top of the page

samigo/samigo-api/src/java/org/sakaiproject/samigo/api/SamigoETSProvider.java, samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java, samigo/samigo-pack/src/bundle/template-assessmentAutoSubmitErrors.xml, samigo/samigo-pack/src/webapp/WEB-INF/components.xml, samigo/samigo-services/pom.xml, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/util/autosubmit/AutoSubmitQueries.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/util/autosubmit/AutoSubmitQueriesAPI.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/AutoSubmitAssessmentsJob.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/GradingService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/PersistenceService.java
https://jira.sakaiproject.org/browse/SAM-2940
=> SAM-2940: Refactor autosubmit to enclose each update in a separate transaction and notify on failure

tool/tool-tool/su/src/java/org/sakaiproject/tool/su/SuTool.java
Have removed the redirect to template 'redirect' and used
'context.redirect' to directly go to portal Url.
=> SAK-31556 Become User redirects to welcome page not to Admin workspace.

reference/library/src/morpheus-master/sass/modules/tool/samigo/_samigo.scss, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp
displayed in one web page
Link replaced with a span
=> SAM-2988 Focus lost if clicking in Numeric Response Help for assessment

gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/helpers/TestImportGradesHelper.java
=> Fix failing test from 3059

profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileConnectionsLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileKudosLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfilePreferencesLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfilePrivacyLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileSearchLogicImpl.java
This fixes the cache expiration issues in profile2,
https://jira.sakaiproject.org/browse/SAK-31645
=> SAK-31645: fix cache expiration problems in profile2

profile2/api/src/java/org/sakaiproject/profile2/cache/CacheManager.java, profile2/impl/src/java/org/sakaiproject/profile2/cache/CacheManagerImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileConnectionsLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileExternalIntegrationLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileKudosLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfilePreferencesLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfilePrivacyLogicImpl.java, profile2/impl/src/java/org/sakaiproject/profile2/logic/ProfileSearchLogicImpl.java
Fixed a few other broken windows
=> SAK-31645 replace duplicated cache evict method with a common one.

master/pom.xml
Checking to see if this makes travis any faster.
=> SAK-31558 Improve speed of test when VM doesn’t have ok rnd.

pasystem/pasystem-impl/impl/pom.xml, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/rest/PASystemEntityProvider.java
=> SAK-31648: Fix annoying log message on gateway site (with StringUtils)

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
Sitebrowser returns no results
=> SAK-31647 - Sitebrowser returns no results

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/GradebookPage.html
=> 3156 Add missing I18n entries for toolbar buttons

entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityGroup.java
New PR against master rather than 11.x
=> SAK-31653: missing return statement in EntityGroup.java

content/content-impl-providers/impl/src/java/org/sakaiproject/content/providers/BaseEventDelayHandler.java, dashboard/impl/src/java/org/sakaiproject/dash/jobs/DashAggregateJob.java, dashboard/impl/src/java/org/sakaiproject/dash/logic/EventCopy.java, kernel/api/src/main/java/org/sakaiproject/event/api/Event.java, kernel/api/src/main/java/org/sakaiproject/event/api/EventTrackingService.java, kernel/api/src/main/java/org/sakaiproject/event/api/SimpleEvent.java, kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseEventTrackingService.java, kernel/kernel-impl/src/test/java/org/sakai/memory/impl/test/MockEventTrackingService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/conditions/impl/TestConditionService.java, sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/CustomEventImpl.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeEvent.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/mocks/FakeEventTrackingService.java, sitestats/sitestats-impl/src/test/org/sakaiproject/sitestats/test/perf/mock/MockEventTrackingService.java
Another PR would actually make the LRS Service make use of this in the Observer and clean up some other code.
=> KNL-1451 - Add support for metadata (or LRS Statements) to events

access/access-impl/impl/src/templates/vm/access/copyrightAlert.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
This seems like it works as I expect but I could really use some review! I mean it was really quick because I didn't like how the dialog box opened in it's whole new window.
=> SAK-31464 - Move copyright warning from new window/tab to dialog box

pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Acknowledger.java, pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Banners.java, pasystem/pasystem-api/api/src/java/org/sakaiproject/pasystem/api/Popups.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/PASystemImpl.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/acknowledgements/AcknowledgementStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/banners/BannerStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/popups/PopupForUser.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/popups/PopupStorage.java, pasystem/pasystem-impl/impl/src/java/org/sakaiproject/pasystem/impl/rest/PASystemEntityProvider.java, pasystem/pasystem-impl/impl/src/resources/db/migration/hsqldb.sql, pasystem/pasystem-impl/impl/src/resources/db/migration/mysql.sql, pasystem/pasystem-impl/impl/src/resources/db/migration/oracle.sql, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/forms/PopupForm.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/handlers/PopupsHandler.java, pasystem/pasystem-tool/tool/src/java/org/sakaiproject/pasystem/tool/views/popup_form.hbs, reference/docs/conversion/sakai_12_mysql_conversion.sql, reference/docs/conversion/sakai_12_oracle_conversion.sql
Includes a DB migration to convert existing data.
=> SAK-31563 Rework PA System to use User IDs instead of EIDs

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/helpers/TestImportGradesHelper.java
The model was being overwritten rather than being added to
Fixes #3153
=> Fix bug where import was failing when more than one item was being imported

gradebook/app/ui/src/java/gradebook.properties, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradeAssignmentItem.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradeAssignmentItemDetail.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradeCourse.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/GradebookEntityProvider.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/model/Category.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/model/ExternalInfo.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/model/GradebookData.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/model/GradebookItem.java, gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/helpers/entity/model/StudentGrade.java
This allows for a batch of sites (or a single site) to have their gradebook data returned over REST.
=> SAK-31661 Add the ability to get gradebook data for a batch of sites

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/component/GbFeedbackPanel.java
=> 3187: ensure the feedback panel is hidden when there are no messages

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/FormatHelper.java
=> 3212: disable grouping from double formatter to avoid ambiguity when comparing grades

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 3211: if we strip the value, be sure to unstrip it so the '%' is retained

access/access-impl/impl/src/templates/vm/access/copyrightAlert.vm, content/content-tool/tool/src/webapp/vm/content/sakai_resources_list.vm
contents don't open in the popup box
=> SAK-31464 - Some updates so that the initial window closes that the

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/GradebookService.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
=> If you only have an extra credit item in a category w/ a score attached, the category subtotal should not update

gradebookng/tool/src/webapp/scripts/gradebook-grades.js
=> 3187: ensure fixed headers are realigned after vertical scroll changes

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html
=> 3222: add widths to import table so it doesn't jump about as rows are hidden

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/CreateGradeItemStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportConfirmationStep.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
=> 3224: add cancel button to each step of the import process

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeItemImportSelectionStep.java
May need to merge #3238 first, it's seeing commits from there (i think I created the branch from that one actually).
Fixes #3223 again, a regression crept in. Need decent tests...
=> #3223 reject import if comment imported without corresponding item

site-manage/pageorder/tool/src/webapp/content/js/orderUtil.js
Delivers https://jira.sakaiproject.org/browse/SAK-31643.
=> SAK-31643 fix removed tools not being removed from the tool order listing

site-manage/site-manage-tool/tool/src/webapp/js/site-manage.js, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSites.vm, site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/chef_site-importSitesMigrate.vm
Delivers https://jira.sakaiproject.org/browse/SAK-31699 so it looks something like this:
=> SAK-31699 Add a select all / unselect all button to "Import from Site"

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/CourseGradeFormatter.java
=> #3246 handle the case when an overridden course grade can't be mapped

msgcntr/messageforums-app/src/webapp/css/msgcntr.css
Increased the specificity of the markAsReadIcon so that the image
is displayed.
=> SAK-31711 Improve forums MarkasReadIcon

samigo/samigo-app/src/webapp/jsf/author/publishedSettings.jsp
Fix up errornously using assessmentSettings values where
publishedSettings values are needed.
=> SAM-3006 Use publishedSettings values

emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-31384
Currently, all updates to email templates have to be propagated manually, either though database script updates, or through the GUI.
This is because in the past the ETS.updateTemplate() method didnt't seem to work. It now works properly, but is not called when processing XML email templates during server start-up.
The linked PR will add code to the xmlToTemplate() method to call the updateTemplate() method if the template already exists and the version is greater than the version currently loaded.
The result of this work is that all updates to email templates can be done in code (in the XML files). Provided that you also bump up the version (whole integers), the code will update the template for you. No more database scripts and no more …
=> SAK-31384 add template updating code to ETS.xmlToTemplate()

delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/EditablePanelList.html, delegatedaccess/tool/src/java/org/sakaiproject/delegatedaccess/tool/pages/EditablePanelList.java
https://jira.sakaiproject.org/browse/SAK-31576
=> SAK-31576 In the delegated access tool, add toggle all actions to the tool restriction form

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
=> 3059: update wording for import messages

edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Assignment.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradableObject.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/GradeMapping.java, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/Spreadsheet.java
=> SAK-31420 Issue with import from site not working due to logger serialization

kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/BaseLearningResourceStoreService.java
Okay, I *think* this is finally the last commit on this task, looking good to me now! Samigo commit coming up!
=> KNL-1461 - Carry LRS_Result forward on LRS getEventStatement

user/user-tool-prefs/tool/src/java/org/sakaiproject/user/tool/UserPrefsTool.java
=> SAK-31727 cleanup info message observed thousands of times in Sakai 11 logs

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/exception/GbImportExportDuplicateColumnException.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/exception/GbImportExportInvalidColumnException.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/exception/GbImportExportInvalidFileTypeException.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/exception/GbImportExportUnknownStudentException.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/model/ImportedColumn.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java
=> #3263 check for duplicates in the imported column and raise an exception

edu-services/gradebook-service/api/src/java/org/sakaiproject/service/gradebook/shared/exception/UnmappableCourseGradeOverrideException.java, edu-services/gradebook-service/hibernate/src/hibernate/org/sakaiproject/tool/gradebook/GradeRecord.hbm.xml, edu-services/gradebook-service/hibernate/src/java/org/sakaiproject/tool/gradebook/AssignmentGradeRecord.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/BaseHibernateManager.java, edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/pages/SettingsPage.java, reference/docs/conversion/sakai_12_mysql_conversion.sql, reference/docs/conversion/sakai_12_oracle_conversion.sql
=> Provide a warning when changing the grading schema if there are unmappable course grade overrides

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
it does not run in a separate thread like Import from Site does
=> SAK-27908 disable duplicate button because

lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/service/LessonBuilderEntityProducer.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/OrphanPageFinder.java, lessonbuilder/tool/src/java/org/sakaiproject/lessonbuildertool/tool/beans/SimplePageBean.java
I removed a lot of debugging code here in the original site and changed it to log.debug.
I also removed the original code that did page finding and relied on the new class to do all of the page finding. I haven't completely tested this but it looks like it should be good.
=> LSNBLDR-677 - Stop sites from importing orphaned pages

site-manage/site-manage-tool/tool/src/webapp/vm/sitesetup/toolGroupMultipleDisplay.vm
=> SAK-30371 Fix small bug in the template

mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java
/CC: @buckett or anyone else who understands SMTP and mail rejection ....
=> SAK-31729 send a 550 reject so the sending mail server stops trying

samigo/samigo-api/src/java/org/sakaiproject/samigo/util/SamigoConstants.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/SubmitToGradingActionListener.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/evaluation/StudentScoreUpdateListener.java
=> SAM-3010 - Add actual event string for auto graded event and fix score

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/LinearAccessDeliveryActionListener.java
=> SAM-3014 - isviaURL parameter incorrect in event post from Linear Access

reference/library/src/morpheus-master/js/src/sakai.morpheus.more.sites.js, reference/library/src/morpheus-master/js/src/sakai.morpheus.toggletools.js, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
I've moved subsites behaviour too from one file to the file where all toolmenu behaviour is.
=> SAK-31723 - Subsites position is not in right position

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.java
=> 3311 standardize label for null value on category dropdown as 'Uncategorized'

kernel/kernel-impl/src/main/java/org/sakaiproject/content/impl/DbContentService.java
so that we actually wrap the HTML fragment in the relevant HTML head tags
=> KNL-1462 dont send a direct link for a WrappedContentResource 

kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/DbSiteService.java
When searching for sites the cache of fully loaded sites is replaced with sites that are partially loaded. This is because we’re searching for all the sites in the DB and replacing the values in the cache with them.
=> KNL-1456 Don’t flush the cache when loading.

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
until" is disabled
Set to null the retract date if autosubmit and late submission are
disabled.
=> SAM-3008 Retract date warnings being showed even when the option "Yes,

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/util/SamigoLRSStatements.java
=> SAM-3017 - Changing id to eid in LRS statements, changing to current

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeItemCellPopoverPanel.html, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 3313 change warning icon and color the error icon and red respectively

delegatedaccess/impl/pom.xml, entitybroker/core-providers/pom.xml, entitybroker/impl/pom.xml, feedback/pom.xml, kernel/api/pom.xml, kernel/deploy/shared/pom.xml, kernel/kernel-impl/pom.xml, kernel/kernel-util/pom.xml, mailarchive/mailarchive-impl/impl/pom.xml, mailarchive/mailarchive-subetha/pom.xml, mailsender/impl/pom.xml, master/pom.xml, msgcntr/messageforums-component-impl/pom.xml, reset-pass/account-validator-impl/pom.xml, samigo/samigo-app/pom.xml, samigo/samigo-impl/pom.xml
Upgrade JavaMail from 1.4.5 to 1.5.6
=> SAK-31768 - Upgrade JavaMail from 1.4.5 to 1.5.6

sitestats/sitestats-impl/src/java/org/sakaiproject/sitestats/impl/StatsManagerImpl.java
Solves the ORA-00979: not a GROUP BY expression
=> SAK-31785: Lesson tool activity not working in Oracle

portal/portal-util/util/src/java/org/sakaiproject/portal/util/ToolUtils.java
NPE when creating an empty site (With no tools) - Regression from 10x
=> SAK-31742 - NPE when creating an empty site (With no tools) - Regression from 10x

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/GradebookNgBusinessService.java
=> 3356 handle null calculated grade when sorting rows by course grade

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/AssessmentGradingFacadeQueries.java
auto submit job can cause no submissions to process when type isn't guessed correctly.
=> SAM-3029 auto submit job can cause no submissions to process

jobscheduler/scheduler-tool/src/webapp/scheduler/create_trigger.jsp
SAK-31803 - JobScheduler. Trigger help link throws 404
=> SAK-31803 - JobScheduler. Trigger help link throws 404

edu-services/gradebook-service/impl/src/java/org/sakaiproject/component/gradebook/GradebookServiceHibernateImpl.java
SAK-29004 - Validation error entering a grade
=> SAK-29004 - Validation error entering a grade

user/user-tool-prefs/tool/src/java/org/sakaiproject/user/jsf/HideDivisionRenderer.java, user/user-tool-prefs/tool/src/webapp/prefs/noti.jsp
Switched to bootstrap collapse
=> SAK-31618 - Avoid the sole use of device-dependent event handlers

emailtemplateservice/impl/logic/src/java/org/sakaiproject/emailtemplateservice/service/impl/EmailTemplateServiceImpl.java
https://jira.sakaiproject.org/browse/SAK-31817
=> SAK-31817 Fix NPE in EmailTemplateService.xmlToTemplate()

basiclti/basiclti-tool/src/webapp/vm/lti_tool_site.vm
=> SAK-31780 Url replace in client side

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties
=> 3361 fix typo 'gradenook'

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SaveAssessmentSettings.java
when saving with the "No, not after due date" option
=> SAM-3027 Non-Published assessment: Retract date should be set to null

kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupService.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSql.java, kernel/kernel-impl/src/main/java/org/sakaiproject/authz/impl/DbAuthzGroupSqlDefault.java, kernel/kernel-impl/src/test/java/org/sakaiproject/authz/impl/RoleSwapMembershipTest.java
Check if the user is member of the realm to grant permissions during role swap.
=> KNL-1447 Role swap consider membership

basiclti/basiclti-api/src/java/org/sakaiproject/lti/api/LTIService.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/DBLTIService.java, basiclti/basiclti-impl/src/java/org/sakaiproject/lti/impl/LTIExportServiceImpl.java, basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java, config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties
The defaults shouldn’t be in default.sakai.properties but in the code.
=> SAK-31832 Move defaults out of default.sakai.properties

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/email/impl/test/EmailServiceTest.java
CC: @jonespm ..... if you want to add more features to this, lmk.
=> KNL-1469 avoid sending gigantic emails that will inevitably be rejected

samigo/samigo-app/src/webapp/jsf/author/item/fileUpload.jsp, samigo/samigo-app/src/webapp/jsf/author/item/multipleChoiceSurvey.jsp
=> SAM-2858 "Display Point Value" option is missing from some question

samigo/samigo-api/src/java/org/sakaiproject/tool/assessment/shared/api/questionpool/QuestionPoolServiceAPI.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/bean/questionpool/QuestionPoolBean.java, samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/questionpool/SortQuestionListListener.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/QuestionPoolService.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/shared/impl/questionpool/QuestionPoolServiceImpl.java
speed up question pool loading by avoiding the unnecessary sort because it is not client-side and dont load entire pool twice
Commit after the SAM-3023 is merged
=> SAM-3024 question pool loading performance

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
=> SAK-31848 - Site Information tool doesn't display label when importing

user/user-tool-prefs/tool/src/java/org/sakaiproject/user/jsf/HideDivisionRenderer.java
=> SAK-31822 - Screen jumps on some items in preferences page clicking

kernel/kernel-impl/src/main/java/org/sakaiproject/util/impl/FormattedTextImpl.java, kernel/kernel-impl/src/test/java/org/sakaiproject/util/impl/FormattedTextTest.java, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
- Added a new unit test
- clean up log messages
- clean up stripHtmlFromText method
=> SAM-3048 FormattedText.stripHtmlFromText handle null input correctly

signup/tool/src/bundle/messages.properties, signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp
=> SAK-31632 Add alt text for signup meeting details page

kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BasePreferencesService.java, kernel/kernel-impl/src/test/java/org/sakaiproject/user/impl/BasePreferencesServiceTest.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/SkinnableCharonPortal.java
=> SAK-31764 - Error with saving favorites if user doesn't have a

textarea/FCKeditor/connector/src/java/org/sakaiproject/connector/fck/FCKConnectorServlet.java
I really don't know the best fix for this, this fix is the same as the other issue. It maybe could go as a method in ContentHostingService and both could call those, but that would require an API change to kernel and this really needs to get backported. 
I think ideally it wouldn't need to create a security advisor just to add attachments, but that seems like it would be a rewrite of the kernel to get around these few (from what I can see 2) places that do add content and don't have permission. 
I feel like addAttachmentResource could be unprotected as it is, but the PermissionException isn't thrown in that method, it occurs a few methods deeper. So then addAttachmentResource would need to create this Advisor.
=> SAK-31856 - Unable to make second audio recording (or equation)

feedback/README.md
Update the feedback tool readme to reflect it's status.
=> Update Feedback Tool README

basiclti/basiclti-tool/src/java/org/sakaiproject/blti/tool/LTIAdminTool.java
This applies to processing the ContentItemResponse.
=> SAK-31872 - Fix misprocessing of title and text

profile2/bundle/src/resources/ProfileApplication.properties, profile2/tool/src/java/org/sakaiproject/profile2/tool/components/CloseButton.java, profile2/tool/src/java/org/sakaiproject/profile2/tool/components/GalleryImageRenderer.java
rA11y alt text fix for profile2 My Pictures page
=> SAK-31623 Add alt text to images for Profile2 tool My Pictures page

site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
=> SAK-31874 site-manage is sending a reference instead of the site id to the permission check

kernel/kernel-impl/src/main/java/org/sakaiproject/user/impl/BaseUserDirectoryService.java, signup/api/src/java/org/sakaiproject/signup/logic/SakaiFacade.java, signup/impl/src/java/org/sakaiproject/signup/logic/SakaiFacadeImpl.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/NewSignupMeetingBean.java, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/SignupUIBaseBean.java
of users not a Collection that can contain duplicates
=> KNL-1476 findUsersByEmail should return a unique Set 

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/bundle/AuthorMessages.properties, samigo/samigo-app/src/webapp/js/jquery.dynamiclist.author.js, samigo/samigo-app/src/webapp/jsf/author/item/imageMapQuestion.jsp
Also added validation for descriptions
=> SAM-3044 HOT SPOT description labels lost when you save the question

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeSitesNav.vm
SAK-31818 modified where attributes exist in span tag line 23 on includeSitesNav.vm
=> SAK-31818 - Ensure ARIA roles, states, and properties are valid on Mrphs-sitesNav__menuitem

samigo/samigo-app/src/webapp/jsf/delivery/deliveryjQuery.jsp
=> SAM-2968 Javascript error when a student retakes the assessment after

signup/tool/src/bundle/messages.properties, signup/tool/src/java/org/sakaiproject/signup/tool/jsf/HtmlSortHeaderRenderer.java
rA11y for signup sorting icons alt text.  Internationalized.
=> SAK-31633 Add alt text for sorting icons in the table header columns

portal/portal-impl/impl/src/java/org/sakaiproject/portal/charon/handlers/SiteHandler.java
I tested this locally with and without quicklinks defined.
=> SAK-31891 - Quick links shouldn't display if there aren't any quicklinks

portal/portal-charon/charon/src/webapp/WEB-INF/applicationContext.xml, portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/PortalEntityProvider.java, portal/portal-impl/impl/src/java/org/sakaiproject/portal/entityprovider/profile-popup.vm
Also, this fixes a bit of stupidity where the profile-eb.js was being pulled from localhost. Doh.
Also, turn off velocity logging. This was preventing you from starting tomcat from a directory that tomcat couldn't write to.
=> SAK-31892 Profile popup display name is now a link to their profile

syllabus/syllabus-app/src/java/org/sakaiproject/jsf/syllabus/SyllabusIframeRender.java, syllabus/syllabus-app/src/webapp/js/syllabus.js, syllabus/syllabus-app/src/webapp/syllabus/main.jsp, syllabus/syllabus-app/src/webapp/syllabus/main_edit.jsp
and set the frame …to take up 80 percent of the viewport height instead
=> SAK-31887 get rid of the old syllabus mySetFrameHeight code 

portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/includeSitesNav.vm, reference/library/src/morpheus-master/js/src/sakai.morpheus.subnav.js, reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
I've tried to respect all ARIA roles for the dropdown item, I think "separator" is appropiate but I'm open to any comment.
@mclare, what do you think?
=> SAK-31886 : Sites Nav misplaced (Mrphs-sitesNav__menuitem)

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-31906
=> SAK-31906 commons-lang3 3.5

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-31909
=> SAK-31909 commons.fileupload.version

kernel/kernel-impl/src/main/java/org/sakaiproject/email/impl/BasicEmailService.java
Refactoring code used in sendToUsers to honor "maxRecipients" in sendMail method also.
=> KNL-1481 ETS is not honoring maxRecipients property sending emails.

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/AddOrEditGradeItemPanelContent.html
=> 3513 provide a locale label for the date format

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_fr_CA.properties
=> 3546 Add fr_CA properties file

reference/docs/conversion/sakai_12_mysql_conversion.sql, reference/docs/conversion/sakai_12_oracle_conversion.sql
Thanks to Matt Jones for the SQL.
=> SAK-31819 Remove the old quartz job.

reference/library/src/morpheus-master/sass/_defaults.scss, reference/library/src/morpheus-master/sass/base/_responsive.scss, reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
Allow the icon to be displayed on the left hand side and setting of the
width of the collapsed tool menu.
=> SAK-31824 Enhance configuration of the tool/subsite menu.

gradebookng/tool/src/webapp/styles/gradebook-print.css
=> 3549 fix print CSS to better display student summing content when printing

gradebookng/pom.xml, profile2/pom.xml, sitestats/pom.xml
https://jira.sakaiproject.org/browse/SAK-31895
=> SAK-31895 Wicket 6.25.0

msgcntr/messageforums-app/src/webapp/jsp/dfReviseForumSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/dfReviseTopicSettingsAttach.jsp, msgcntr/messageforums-app/src/webapp/jsp/discussionForum/area/dfTemplateSettings.jsp
=> SAK-31918 - Open and close dates in forums should be optional again

kernel/kernel-impl/src/main/java/org/sakaiproject/event/impl/ClusterEventTracking.java
This can happen if the ComponentManager hasn't finished starting in a
timely manner for example when auto.ddl is on
=> KNL-1478 Startup can be interrupted if events begin to process

rwiki/rwiki-impl/pack/src/webapp/WEB-INF/coreServiceComponents.xml
https://jira.sakaiproject.org/browse/SAK-30760
RTF generation is buggy; recommendation was to disable it.
=> SAK-30760 disable wiki RTF generation

master/pom.xml
=> SAK-31917 MariaDB Connector and MySQL connector latest

rwiki/rwiki-util/radeox/src/java/org/radeox/filter/XHTMLFilter.java
https://jira.sakaiproject.org/browse/SAK-31833
cc: @juanjmerono
=> SAK-31833 fix error in logs (rwiki)

delegatedaccess/impl/pom.xml, delegatedaccess/impl/src/java/org/sakaiproject/delegatedaccess/dao/impl/DelegatedAccessSampleDataLoader.java
https://jira.sakaiproject.org/browse/SAK-31958
=> SAK-31958 ResourceProperties: term, term_eid

announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementChannel.java, announcement/announcement-api/api/src/java/org/sakaiproject/announcement/api/AnnouncementChannelEdit.java, announcement/announcement-impl/impl/src/java/org/sakaiproject/announcement/impl/BaseAnnouncementService.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementAction.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementComparator.java, announcement/announcement-tool/tool/src/java/org/sakaiproject/announcement/tool/AnnouncementGroupComparator.java, message/message-api/api/src/java/org/sakaiproject/message/api/MessageChannel.java, message/message-api/api/src/java/org/sakaiproject/message/api/MessageChannelEdit.java, message/message-util/util/src/java/org/sakaiproject/message/util/BaseMessage.java
If the list of announcements contains an announcement made by a user who is now deleted then sorting by "Saved By" will cause a NullPointerException and the tool to crash.
=> SAK-31957 Don't NPE when announcements sorted by user.

assignment/assignment-bundles/resources/assignment_fr_FR.properties
Fix references to turnitin in content review for French locale
=> SAK-31986  - Fix references to turnitin in content review for French locale

gradebook/app/ui/src/java/org/sakaiproject/tool/gradebook/ui/GradebookBean.java, gradebook/app/ui/src/webapp/WEB-INF/faces-beans.xml
Fixes only to the gradebook tool, no changes to service
=> SAK-26637 - NPE from Gradebook on DAC sites (nightly2 10.x)

roster2/src/handlebars/members.handlebars, roster2/src/handlebars/overview.handlebars, roster2/src/webapp/js/roster.js
Roster groups where being shown regardless of what the permission
was. This was fixed.
=> SAK-31820 Fix roster display of roster group

gradebookng/tool/src/java/org/sakaiproject/gradebookng/business/util/ImportGradesHelper.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/importExport/GradeImportUploadStep.java, gradebookng/tool/src/test/org/sakaiproject/gradebookng/business/util/TestImportGradesHelper.java
so also need to check extension. Test with Windows with Excel installed and CSV will have an Excel mimetype.
=> 3617 The browser may not send a proper CSV mimetype 

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.html, gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/GradeSummaryTablePanel.java, gradebookng/tool/src/webapp/scripts/gradebook-grade-summary.js
… in student grade summary view.
Delivers #3603 and relies on patch for #3580.
=> 3603 only show category weight column when weights are enabled

feedback/src/java/org/sakaiproject/feedback/tool/FeedbackTool.java
and then uses contact us tool to report a problem with content.
=> SAK-31981: Email not sent if user tries to visit non-existant site

portal/portal-charon/charon/src/webapp/scripts/webrtc-adapter.js
Some changes to handle correctly the prefixes of WebRTC API in the portal chat
=> SAK-31992 Changed the way WebRTC prefixes are handled.

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/delivery/DeliveryActionListener.java
DeliveryActionListener.java was forgetting if students selected a wrong
answer when it checked to see if they got the right number of correct
answers.
=> SAM-3084 Fix feedback logic for MC-MC

msgcntr/messageforums-api/src/java/org/sakaiproject/api/app/messageforums/MessageForumsMessageManager.java
https://jira.sakaiproject.org/browse/SAK-31990
=> SAK-31990 Fix for NPE while accessing saveMesage from outside sakai context

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/ExtendedTimeFacade.java
=> When publishing an assessment extended time entry on working copy

samigo/samigo-impl/src/java/org/sakaiproject/samigo/impl/SamigoETSProviderImpl.java, samigo/samigo-pack/src/webapp/WEB-INF/components.xml
If this commit is accepted it should be accepted by doing a "Merge Commit" doing any other way will cause the author of the commit to be lost.
=> SAM-3004 Fix display of dates in Samigo Emails

samigo/samigo-app/src/webapp/jsf/author/authorSettings.jsp, samigo/samigo-app/src/webapp/jsf/author/inc/extendedTime.jspf, samigo/samigo-app/src/webapp/jsf/author/inc/publishedExtendedTime.jspf
Moved all these items into the datatable so they would align correctly.
=> SAM-3085 - Extended Time - Layout wrong for first item.

rwiki/rwiki-tool/tool/src/bundle/uk/ac/cam/caret/sakai/rwiki/tool/bundle/Messages.properties, rwiki/rwiki-tool/tool/src/webapp/WEB-INF/vm/info.vm
https://jira.sakaiproject.org/browse/SAK-32024
=> SAK-32024: Wiki Info page: "Info:" to "Information for:"

assignment/assignment-bundles/resources/assignment_en_GB.properties
when saving an assignment
https://jira.sakaiproject.org/browse/SAK-32030
=> SAK-32030: odd message about turnitin is displayed

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication.java, gradebookng/tool/src/java/org/sakaiproject/gradebookng/framework/GradebookNgStringResourceLoader.java
=> 3644 gradebookng use sakai's resource loader

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFileUpload.jsp
Inappropriate to show the Upload button when reviewing an assessment submission.
=> SAM-2682 Don't show file upload button when reviewing assessment

gradebookng/tool/src/java/org/sakaiproject/gradebookng/tool/panels/StudentGradeSummaryGradesPanel.html, gradebookng/tool/src/webapp/styles/gradebook-grades.css
=> 3725 fix course grade overlapping with message on student view

portal/portal-charon/charon/src/webapp/scripts/chat.js, portal/portal-charon/charon/src/webapp/scripts/jescape.js, portal/portal-render-engine-impl/pack/src/webapp/vm/morpheus/snippets/portalChat-snippet.vm
I think this jescape is kind of a cool (although not maintained) library that could be useful including in the general portal. I just have it here included in chat though as I don't think we have many other "non-jquery" dialogs?
=> SAK-31587 - Ensure simulated dialogs can be closed via the keyboard

config/configuration/bundles/src/bundle/org/sakaiproject/config/bundle/default.sakai.properties, site-manage/site-manage-tool/tool/src/java/org/sakaiproject/site/tool/SiteAction.java
=> SAK-32067 - Change default value of site-manage.importoption.siteinfo to

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32052
=> SAK-32052 joda-time 2.9.7

master/pom.xml
https://jira.sakaiproject.org/browse/SAK-32050
=> SAK-32050 elasticsearch 1.7.6

gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_en_GB.properties, gradebookng/tool/src/java/org/sakaiproject/gradebookng/GradebookNgApplication_en_ZA.properties
https://jira.sakaiproject.org/browse/SAK-31907
=> SAK-31907 GB & ZA date

msgcntr/messageforums-component-impl/src/java/org/sakaiproject/component/app/messageforums/ui/PrivateMessageManagerImpl.java
=> SAK-32039: Make Msg Centre notifications more

reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
=> SAK-32038: Image in tools menu on mobile when site

reference/library/src/morpheus-master/sass/modules/navigation/_base.scss
when not logged in (Mobile view)
=> SAK-32042: Tools & Subsites menu obscured

samigo/samigo-app/src/webapp/jsf/questionpool/questionTreeTable.jsp, samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/facade/QuestionPoolFacadeQueries.java
Now we return the pool´s question list ordered by item id.
Also i add a modified date column to the pool´s question list
=> SAM-2684 Handling a lots of questions in pools is tricky

samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMultipleChoiceMultipleCorrect.jsp, samigo/samigo-app/src/webapp/jsf/evaluation/item/displayMultipleChoiceSingleCorrect.jsp
Regression: Multiple Choice answers missing when revising assessment
=> SAM-3081 - Regression: Multiple Choice answers missing when revising assessment

samigo/samigo-services/src/java/org/sakaiproject/tool/assessment/services/assessment/AssessmentService.java
This PR fixes SAM-2595 and SAM-2596. Verified in https://sakai-trunk.atica.um.es/. 
Regards,
Raúl
=> SAM-2595/SAM-2596: Images from shared pools

kernel/api/src/main/java/org/sakaiproject/config/api/HibernateConfigItem.hbm.xml
Reduce column lengths to avoid total row width exceeding 64K with utf8mb4
=> KNL-1484 Reduce column lengths to support mysql utf8mb4 databases

site-manage/site-manage-impl/impl/src/bundle/notifyAddedParticipants.xml
https://jira.sakaiproject.org/browse/SAK-32091
The wording of this email needs to be updated due to the major UI changes that happened in 11/12.
There are several translations of this email template provided in the XML file. I have only changed the English ones. NL and CA will need to be updated by someone familiar with those languages.
The part at the bottom which was removed were old translations for other languages that have been commented out for some time; no sense in keeping them commented out if we don't want/use them.
=> SAK-32091 updated wording of sitemange.notifyAddedParticipant email template

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SectionActivityListener.java
User Activity Report always displays 0/X for Score/Total Points
https://jira.sakaiproject.org/browse/SAM-2770
=> SAM-2770 User Activity Report always displays 0/X for Score/Total Points

samigo/samigo-app/src/webapp/jsf/author/authorIndex_content.jsp
Add time (hh:mm:ss) to "Release Date" and "Due Date" in published
assessment
=> SAM-3112 Add time (hh:mm:ss) to "Release Date" and "Due Date" in published assessment

lessonbuilder/tool/src/webapp/css/checklist.css, lessonbuilder/tool/src/webapp/templates/Checklist.html
Changed the silk image to a font awesome one as consistent with the other icons in the lessons tool as well as making the fix easier.
=> LSNBLDR-765 Modified Checklist button to use default colors.

authz/authz-tool/tool/src/webapp/vm/helper/chef_permissions.vm
=> SAK-31626 do not wrap input in label and use bootstrap sr-only instead of skip class

portal/portal-chat/tool/src/java/org/sakaiproject/portal/chat/entity/PCServiceEntityProvider.java
I'm not very familiar with this code ... so seeing if @adrianfish  can take a look?
=> SAM-32108 avoid two calls to heartbeatMap and avoid NPE

assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_student_view_submission.vm
=> SAM-32121 div tag wasnt being closed preventing student from seeing resubmit buttons

content/content-tool/tool/src/webapp/vm/resources/sakai_create_folders.vm
=> SAK-31594 fix DIV closing tag

reference/library/src/morpheus-master/sass/base/_defaults.scss, reference/library/src/webapp/skin/tool_base.css
Looks like it needs to be in the scss for Sakai 11/12.
=> SAK-32089 - CKEditor marker not working on 12

mailarchive/mailarchive-subetha/src/java/org/sakaiproject/mailarchive/SakaiMessageHandlerFactory.java
Leaving for @buckett  review
Untested.
=> SAK-32068 also split the from address to strip BATV

content/content-tool/tool/src/bundle/helper.properties, content/content-tool/tool/src/webapp/vm/content/sakai_filepicker_attach.vm
=> SAK-31899 add explanation about the Continue button for sr

calendar/calendar-impl/impl/pom.xml, external-calendaring-service/impl/pom.xml, external-calendaring-service/impl/src/java/org/sakaiproject/calendaring/api/ExternalCalendaringServiceImpl.java, master/pom.xml, signup/api/pom.xml, signup/impl/pom.xml, signup/tool/pom.xml
Mainly just dependency updates, only one change to the actual code of an import.
=> SAK-32119 Upgrade to ical4j 2.0

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverCalculatedQuestion.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInNumeric.jsp, samigo/samigo-app/src/webapp/jsf/delivery/item/deliverFillInTheBlank.jsp
=> SAM-2995 wrap question text in a label

content/content-tool/tool/src/webapp/vm/resources/sakai_create_uploads.vm, reference/library/src/morpheus-master/sass/modules/tool/resources/_resources.scss
=> SAK-31592 wrap availability in fieldset and legend for a11y

assignment/assignment-tool/tool/src/webapp/css/assignment.css, assignment/assignment-tool/tool/src/webapp/vm/assignment/chef_assignments_list_assignments.vm
=> SAK-31474 stop use of h4 inside table. add scope=col and scope=row

site/site-tool/tool/src/webapp/vm/adminsites/chef_sites_list.vm
=> SAK-32129 cleanup admin sites page

kernel/kernel-impl/src/main/java/org/sakaiproject/component/impl/ToolConfigurationService.java
Assigning to buckett because I think he did the refactor here
=> SAK-31223 preselected tools in toolOrder.xml do not take effect

content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/CompilatioAccountConnection.java, content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/CompilatioReviewServiceImpl.java, content-review/impl/compilatio/src/main/java/org/sakaiproject/contentreview/compilatio/util/CompilatioAPIUtil.java
* Solved bug : Submissions to be processed on assignments due date, now
are uploaded immediately and analyzed on due date.
* Source code refactor :
- Proxy is not used -> removed
- processItem -> Reuse code
=> SAK-32128 compilatio submissions to be processed on assignments due date

samigo/samigo-app/src/java/org/sakaiproject/tool/assessment/ui/listener/author/SavePublishedSettingsListener.java
Comments (from the Tests & Quizzes Total Scores page) are not being
sended to GradeBook
=> SAM-3121 comments not being sent to gradebook

kernel/kernel-impl/pom.xml, kernel/kernel-impl/src/test/java/org/sakaiproject/component/impl/ToolConfigurationServiceTest.java, kernel/kernel-impl/src/test/resources/org/sakaiproject/component/impl/emptyToolGroups.xml, kernel/kernel-impl/src/test/resources/org/sakaiproject/component/impl/emptyToolOrder.xml, kernel/kernel-impl/src/test/resources/org/sakaiproject/component/impl/simpleToolGroups.xml, kernel/kernel-impl/src/test/resources/org/sakaiproject/component/impl/simpleToolOrder.xml
This adds some basic tests for ToolConfigurationService which check it’s working as expected.
=> SAK-31223 Add basic tests for ToolConfigurationService

signup/tool/src/webapp/signup/newMeeting/step1.jsp, signup/tool/src/webapp/signup/newMeeting/step2.jsp, signup/tool/src/webapp/signup/organizer/modifyMeeting.jsp, signup/tool/src/webapp/signup/organizer/orgSignupMeeting.jsp, signup/tool/src/webapp/signup/signupMeetings.jsp
=> SAK-31630 signup a11y better labels for inputs

samigo/samigo-app/src/webapp/jsf/delivery/item/deliverAudioRecording.jsp
=> SAM-2991 Audio Response question Pop Up with wrong format

samigo/samigo-app/src/webapp/css/tool_sam.css
Currently in master:
Proposed change:
=> SAM-3031 fix wrapping on long questions

assignment/assignment-tool/tool/src/java/org/sakaiproject/assignment/tool/AssignmentAction.java, edu-services/sections-service/sections-api/src/java/org/sakaiproject/section/api/coursemanagement/CourseSection.java, edu-services/sections-service/sections-impl/sakai/model/src/java/org/sakaiproject/component/section/sakai/CourseSectionImpl.java, edu-services/sections-service/sections-impl/standalone/src/java/org/sakaiproject/component/section/CourseSectionImpl.java, entitybroker/core-providers/src/java/org/sakaiproject/entitybroker/providers/model/EntityGroup.java, kernel/api/src/main/java/org/sakaiproject/site/api/Group.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseGroup.java, kernel/kernel-impl/src/main/java/org/sakaiproject/site/impl/BaseSite.java, sections/sections-app-util/src/java/org/sakaiproject/tool/section/decorator/SectionDecorator.java, sections/sections-app/src/java/org/sakaiproject/tool/section/jsf/backingbean/LocalSectionModel.java, site-manage/site-manage-group-section-role-helper/tool/src/bundle/org/sakaiproject/site/tool/managegroupsectionrole/bundle/Messages.properties, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/impl/SiteManageGroupSectionRoleHandler.java, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupDelProducer.java, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupEditProducer.java, site-manage/site-manage-group-section-role-helper/tool/src/java/org/sakaiproject/site/tool/helper/managegroupsectionrole/rsf/GroupListProducer.java, site-manage/site-manage-group-section-role-helper/tool/src/webapp/content/templates/GroupList.html
Removing a group will orphan the group's assignment submission
=> SAK-27980 - Removing a group will orphan the group's assignment submissions

reference/library/src/morpheus-master/sass/modules/_toolmenu.scss
https://jira.sakaiproject.org/browse/SAK-32100
=> SAK-32100 Prevent collapsed tools menu on a mobile sized screen.
